import { createVideoRenderer, createVideoRenderSurface, createVideoDecodeSource, createFFmpegVideoDecoder } from '@ubos/media-plane';

export default async function RenderV2Page() {
  const renderer = createVideoRenderer({ preferredBackend: 'webgpu', webgpuSupported: false });
  await renderer.initialize(createVideoRenderSurface({ id: 'demo-preview-surface', kind: 'canvas', width: 1280, height: 720 }));
  const decoder = createFFmpegVideoDecoder({ ffprobeExecutable: 'ffprobe', dryRun: true });
  await decoder.open(createVideoDecodeSource({ id: 'demo-video', uri: 'file:///demo/phase-2-5.mp4', label: 'Phase 2.5 decoded stream' }));
  const decoded = await decoder.decodeNext();
  const snapshot = decoded ? await renderer.renderDecodedFrame(decoded) : renderer.getSnapshot();
  const frame = snapshot.latestFrame;

  return <main className="min-h-screen bg-slate-950 p-6 text-slate-100"><div className="mx-auto max-w-5xl space-y-5"><header><p className="text-xs uppercase tracking-widest text-cyan-300">UBOS Version 2.0 · Phase 2.5</p><h1 className="text-3xl font-bold">GPU Rendering Foundation Demo</h1><p className="text-slate-400">Decoded video metadata rendered into an isolated render surface with WebGPU fallback.</p></header><section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="relative aspect-video overflow-hidden rounded-lg bg-black ring-1 ring-cyan-400/30"><div className="absolute inset-0 grid place-items-center text-sm text-slate-500">RenderSurface: 1280×720</div>{frame ? <div className="absolute border border-cyan-300 bg-cyan-400/15 text-xs text-cyan-100" style={{ left: frame.destinationRect.x, top: frame.destinationRect.y, width: frame.destinationRect.width, height: frame.destinationRect.height }}><div className="p-3">Frame #{frame.videoFrame.frameIndex} · {frame.sourceWidth}×{frame.sourceHeight} · PTS {frame.videoFrame.ptsMs}ms</div></div> : null}</div></section><section className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-cyan-200">Renderer</h2><p>Backend: {snapshot.backend}</p><p>State: {snapshot.state}</p><p>Presented: {snapshot.presentedFrames}</p></div><div className="rounded-lg border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-cyan-200">Scheduling</h2><p>Presentation: {frame?.presentationTimeMs ?? 0}ms</p><p>Aspect fit: {frame ? `${frame.destinationRect.width}×${frame.destinationRect.height}` : 'none'}</p></div><div className="rounded-lg border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-cyan-200">Architecture</h2><p>Metadata-first: {String(snapshot.metadataFirst)}</p><p>Payloads: {String(snapshot.containsMediaPayloads)}</p></div></section></div></main>;
}
