import type { ProductionGraph, DestinationNode } from '../../../shared/src/production-graph.js';
import type { AudioRoutePlan } from '../audio-routing/index.js';
import type { VideoRoutePlan } from '../routing.js';
import type { FrameTickEvent, MediaClock } from '../sync/index.js';

export type StreamingProtocol = 'RTMP' | 'RTMPS' | 'SRT' | 'WHIP' | 'WebRTC Egress' | 'HLS' | 'DASH' | 'Custom';
export const supportedStreamingProtocols = ['RTMP','RTMPS','SRT','WHIP','WebRTC Egress','HLS','DASH','Custom'] as const satisfies readonly StreamingProtocol[];
export type StreamingStatus = 'idle' | 'planned' | 'connecting' | 'connected' | 'streaming' | 'reconnecting' | 'paused' | 'stopping' | 'stopped' | 'failed' | 'unavailable';
export type StreamingHealth = 'healthy' | 'degraded' | 'warning' | 'critical' | 'unavailable';

export interface StreamingFailure { readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly destinationId?: string; }
export interface StreamingTransport { readonly id: string; readonly protocol: StreamingProtocol; readonly mode: 'mock' | 'planned' | 'future_live'; readonly switchedFromProtocol?: StreamingProtocol; readonly latencyMs?: number; readonly diagnostics: readonly string[]; }
export interface StreamingDestination { readonly id: string; readonly name: string; readonly platform: string; readonly protocol: StreamingProtocol; readonly enabled: boolean; readonly endpointRef?: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface StreamingTarget { readonly id: string; readonly destinationId: string; readonly transport: StreamingTransport; readonly status: StreamingStatus; readonly connected: boolean; readonly health: StreamingHealth; readonly warnings: readonly string[]; readonly failures: readonly StreamingFailure[]; }
export interface StreamingPlan { readonly id: string; readonly broadcastOutputPlanId: string; readonly videoRoutePlanId: string; readonly audioRoutePlanId: string; readonly outputEngineId: string; readonly recordingEngineId?: string; readonly mediaClockId: string; readonly frameId: number; readonly graphRevision: number; readonly destinations: readonly StreamingDestination[]; readonly targets: readonly StreamingTarget[]; readonly createdAt: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface StreamingSession { readonly id: string; readonly planId: string; readonly status: StreamingStatus; readonly health: StreamingHealth; readonly targets: readonly StreamingTarget[]; readonly startedAt?: string; readonly stoppedAt?: string; readonly updatedAt: string; readonly warnings: readonly string[]; readonly failures: readonly StreamingFailure[]; }
export interface StreamingExecutionResult { readonly success: boolean; readonly session: StreamingSession; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
export interface StreamingManifest { readonly id: string; readonly planId: string; readonly graphRevision: number; readonly frameId: number; readonly destinations: readonly Pick<StreamingDestination, 'id'|'name'|'platform'|'protocol'|'enabled'>[]; readonly transports: readonly StreamingTransport[]; readonly generatedAt: string; readonly containsMediaPayloads: false; }

const now = () => new Date().toISOString();
const protocolFromDestination = (destination: DestinationNode): StreamingProtocol => {
  const value = String(destination.metadata.protocol ?? destination.platform ?? '').toLowerCase();
  if (value.includes('rtmps')) return 'RTMPS'; if (value.includes('rtmp')) return 'RTMP'; if (value.includes('srt')) return 'SRT'; if (value.includes('whip')) return 'WHIP'; if (value.includes('webrtc')) return 'WebRTC Egress'; if (value.includes('hls')) return 'HLS'; if (value.includes('dash')) return 'DASH'; return 'Custom';
};
const healthRank: Record<StreamingHealth, number> = { healthy: 0, warning: 1, degraded: 2, critical: 3, unavailable: 4 };

export function createStreamingPlan(input: { graph: ProductionGraph; broadcastOutputPlanId?: string; videoRoutePlan: VideoRoutePlan; audioRoutePlan: AudioRoutePlan; outputEngineId?: string; recordingEngineId?: string; mediaClock?: MediaClock; frame?: FrameTickEvent; frameId?: number; metadata?: Record<string, unknown>; }): StreamingPlan {
  const createdAt = now();
  const destinations = Object.values(input.graph.destinations).filter((d) => d.enabled).map((d) => (() => { const endpointRef = typeof d.metadata.endpointRef === 'string' ? d.metadata.endpointRef : undefined; return { id: d.id, name: d.name, platform: d.platform, enabled: d.enabled, protocol: protocolFromDestination(d), ...(endpointRef ? { endpointRef } : {}), metadata: d.metadata }; })());
  const targets = destinations.map((destination) => ({ id: `stream-target:${destination.id}`, destinationId: destination.id, transport: { id: `transport:${destination.id}:${destination.protocol}`, protocol: destination.protocol, mode: 'mock' as const, diagnostics: ['mock transport only; no sockets, encoder, FFmpeg, CDN, or packets'] }, status: 'planned' as const, connected: false, health: 'healthy' as const, warnings: [], failures: [] }));
  return { id: `stream-plan:${input.graph.metadata.revision}:${input.frame?.frameId ?? input.frameId ?? 0}`, broadcastOutputPlanId: input.broadcastOutputPlanId ?? `output:${input.graph.broadcastSessionId}`, videoRoutePlanId: input.videoRoutePlan.id, audioRoutePlanId: input.audioRoutePlan.id, outputEngineId: input.outputEngineId ?? 'output-engine:mock', ...(input.recordingEngineId ? { recordingEngineId: input.recordingEngineId } : {}), mediaClockId: input.mediaClock ? `media-clock:${input.mediaClock.getState().frameRate}fps` : 'media-clock:unbound', frameId: input.frame?.frameId ?? input.frameId ?? 0, graphRevision: input.graph.metadata.revision, destinations, targets, createdAt, metadata: input.metadata ?? {} };
}
export function validateStreamingPlan(plan: StreamingPlan) { const warnings: string[] = []; const errors: string[] = []; if (!plan.videoRoutePlanId) errors.push('Missing video route plan'); if (!plan.audioRoutePlanId) errors.push('Missing audio route plan'); if (plan.destinations.length === 0) warnings.push('No enabled streaming destinations'); if (plan.targets.some((t) => !supportedStreamingProtocols.includes(t.transport.protocol))) errors.push('Unsupported protocol'); return { valid: errors.length === 0, warnings, errors }; }
function session(plan: StreamingPlan, status: StreamingStatus, extra: Partial<StreamingSession> = {}): StreamingSession { const targets = extra.targets ?? plan.targets.map((t) => ({ ...t, status, connected: status === 'connected' || status === 'streaming', health: status === 'unavailable' ? 'unavailable' : t.health })); const worst = targets.map((t) => t.health).sort((a,b)=>healthRank[b]-healthRank[a])[0] ?? 'unavailable'; return { id: `stream-session:${plan.id}`, planId: plan.id, status, health: worst, targets, updatedAt: now(), warnings: [], failures: [], ...extra }; }
export const prepareStreaming = (plan: StreamingPlan): StreamingExecutionResult => ({ success: validateStreamingPlan(plan).valid, session: session(plan, 'planned'), warnings: validateStreamingPlan(plan).warnings, errors: validateStreamingPlan(plan).errors });
export const connectStreaming = (s: StreamingSession): StreamingExecutionResult => ({ success: true, session: { ...s, status: 'connected', health: summarizeStreamingHealth({ ...s, targets: s.targets.map((t)=>({ ...t, status:'connected', connected:true })) }).health, targets: s.targets.map((t)=>({ ...t, status:'connected', connected:true })), updatedAt: now() }, warnings: [], errors: [] });
export const startStreaming = (s: StreamingSession): StreamingExecutionResult => ({ success: true, session: { ...s, status: 'streaming', startedAt: s.startedAt ?? now(), targets: s.targets.map((t)=>({ ...t, status:'streaming', connected:true })), updatedAt: now() }, warnings: [], errors: [] });
export const pauseStreaming = (s: StreamingSession): StreamingExecutionResult => ({ success: true, session: { ...s, status: 'paused', targets: s.targets.map((t)=>({ ...t, status:'paused' })), updatedAt: now() }, warnings: [], errors: [] });
export const resumeStreaming = (s: StreamingSession): StreamingExecutionResult => startStreaming({ ...s, status: 'connected' });
export const stopStreaming = (s: StreamingSession): StreamingExecutionResult => ({ success: true, session: { ...s, status: 'stopped', stoppedAt: now(), targets: s.targets.map((t)=>({ ...t, status:'stopped', connected:false })), updatedAt: now() }, warnings: [], errors: [] });
export function failStreaming(s: StreamingSession, failure: StreamingFailure): StreamingExecutionResult { return { success: false, session: { ...s, status: failure.retryable ? 'reconnecting' : 'failed', health: failure.retryable ? 'degraded' : 'critical', failures: [...s.failures, failure], targets: s.targets.map((t)=> failure.destinationId && t.destinationId !== failure.destinationId ? t : { ...t, status: failure.retryable ? 'reconnecting' : 'failed', connected: false, health: failure.retryable ? 'degraded' : 'critical', failures: [...t.failures, failure] }), updatedAt: now() }, warnings: failure.retryable ? [failure.message] : [], errors: failure.retryable ? [] : [failure.message] }; }
export function summarizeStreamingHealth(s: StreamingSession) { const warnings = [...s.warnings, ...s.targets.flatMap((t)=>t.warnings)]; const failures = [...s.failures, ...s.targets.flatMap((t)=>t.failures)]; const health = s.targets.map((t)=>t.health).sort((a,b)=>healthRank[b]-healthRank[a])[0] ?? s.health; return { health, connectedTargets: s.targets.filter((t)=>t.connected).length, activeTargets: s.targets.filter((t)=>t.status === 'streaming').length, warnings, failures }; }
export function createStreamingManifest(plan: StreamingPlan): StreamingManifest { return { id: `stream-manifest:${plan.id}`, planId: plan.id, graphRevision: plan.graphRevision, frameId: plan.frameId, destinations: plan.destinations.map(({id,name,platform,protocol,enabled})=>({id,name,platform,protocol,enabled})), transports: plan.targets.map((t)=>t.transport), generatedAt: now(), containsMediaPayloads: false }; }
export class StreamingStore { private plans = new Map<string, StreamingPlan>(); setStreamingPlan(plan: StreamingPlan) { this.plans.set(plan.id, plan); return plan; } getStreamingPlan(id: string) { return this.plans.get(id); } listStreams() { return [...this.plans.values()]; } getActiveStreams() { return this.listStreams().filter((p)=>p.destinations.some((d)=>d.enabled)); } clearStreams() { this.plans.clear(); } }
export function simulateStreamingHealthChange(s: StreamingSession, destinationId: string, health: StreamingHealth, warning = `Mock ${health} network condition`): StreamingSession { return { ...s, health, warnings: [...s.warnings, warning], targets: s.targets.map((t)=>t.destinationId === destinationId ? { ...t, health, warnings: [...t.warnings, warning] } : t), updatedAt: now() }; }
export function simulateTransportSwitch(s: StreamingSession, destinationId: string, protocol: StreamingProtocol): StreamingSession { return { ...s, targets: s.targets.map((t)=>t.destinationId === destinationId ? { ...t, transport: { ...t.transport, id: `${t.transport.id}->${protocol}`, switchedFromProtocol: t.transport.protocol, protocol, diagnostics: [...t.transport.diagnostics, `mock transport switch to ${protocol}`] } } : t), updatedAt: now() }; }
export function simulateDisconnect(s: StreamingSession, destinationId: string) { return failStreaming(s, { code: 'MOCK_DISCONNECT', message: 'Mock destination disconnect', retryable: true, occurredAt: now(), destinationId }); }
export function simulateDestinationFailure(s: StreamingSession, destinationId: string) { return failStreaming(s, { code: 'MOCK_DESTINATION_FAILURE', message: 'Mock destination failure', retryable: false, occurredAt: now(), destinationId }); }
