import type { ProductionGraph } from '../../../shared/src/production-graph.js';
import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
import { buildCommand, createFFmpegRuntime, locateFFmpeg, type FFmpegRuntime } from '../ffmpeg-runtime/index.js';
import { createProductionRuntime, RuntimeSupervisor, type RuntimeSubsystem } from '../production-runtime/index.js';
import { createClock } from '../sync/clock.js';
import { FrameScheduler } from '../sync/index.js';

declare const process: { env: Record<string,string|undefined>; cwd?:()=>string };
declare const Buffer: { byteLength(input:string): number };
type Fs = { mkdirSync:(p:string,o?:unknown)=>void; writeFileSync:(p:string,d:string)=>void; renameSync:(a:string,b:string)=>void; unlinkSync:(p:string)=>void; existsSync:(p:string)=>boolean; statSync:(p:string)=>{isDirectory():boolean;isFile():boolean;isSymbolicLink?:()=>boolean;size:number}; realpathSync:(p:string)=>string };
type Path = { resolve:(...p:string[])=>string; basename:(p:string)=>string; extname:(p:string)=>string; join:(...p:string[])=>string; dirname:(p:string)=>string };
async function loadFs():Promise<{fs:Fs;path:Path}>{ const [fs,path]=await Promise.all([Function('return import("node:fs")')(),Function('return import("node:path")')()]) as [{default?:Fs}&Fs,{default?:Path}&Path]; return {fs:(fs.default??fs) as Fs,path:(path.default??path) as Path}; }

export type RecordingFormat='mp4'|'mkv'|'mov'|'ts'|'wav'|'mp3';
export type RecordingKind='program'|'preview'|'iso'|'scene';
export type RecordingLifecycle='created'|'prepared'|'recording'|'paused'|'splitting'|'stopped'|'finalized'|'archived'|'deleted'|'failed';
export interface RecordingOutput { readonly id:string; readonly directory:string; readonly filename:string; readonly finalPath:string; readonly temporaryPath:string; readonly format:RecordingFormat; readonly overwrite:boolean; readonly segment?:boolean; readonly currentSizeBytes:number; readonly finalized:boolean; }
export interface RecordingStatistics { readonly durationMs:number; readonly currentSizeBytes:number; readonly bitrateKbps:number; readonly fps:number; readonly droppedFrames:number; readonly diskUsageBytes:number; readonly remainingSpaceBytes:number; readonly writeSpeedBytesPerSecond:number; readonly estimatedCompletion?:string; }
export interface RecordingJob { readonly id:string; readonly graphRevision:number; readonly kind:RecordingKind; readonly state:RecordingLifecycle; readonly output:RecordingOutput; readonly createdAt:string; readonly startedAt?:string; readonly stoppedAt?:string; readonly scheduleAt?:string; readonly tracks:readonly string[]; readonly segmentIndex:number; readonly manual:boolean; readonly statistics:RecordingStatistics; readonly latestFailure?:RecordingFailure; readonly replay:readonly RecordingReplayRecord[]; readonly containsRuntimeHandles:false; }
export interface RecordingManifest { readonly id:string; readonly jobId:string; readonly generatedAt:string; readonly output:Pick<RecordingOutput,'finalPath'|'format'|'filename'|'segment'|'finalized'>; readonly lifecycle:RecordingLifecycle; readonly statistics:RecordingStatistics; readonly tracks:readonly string[]; readonly replaySafe:true; readonly containsMediaPayloads:false; readonly containsFileHandles:false; readonly containsProcessHandles:false; }
export interface RecordingFailure { readonly kind:'disk_full'|'permission_denied'|'output_unavailable'|'encoder_failure'|'ffmpeg_crash'|'write_timeout'|'interrupted'|'unexpected_shutdown'|'security_violation'; readonly message:string; readonly retryable:boolean; readonly occurredAt:string; readonly ubosFailure:UBOSFailure; }
export interface RecordingReplayRecord { readonly type:'command'|'lifecycle'|'state'|'health'; readonly timestamp:string; readonly jobId:string; readonly data:Readonly<Record<string,string|number|boolean>>; }
export interface RecordingPipelineOptions { readonly outputDirectory:string; readonly format?:RecordingFormat; readonly kind?:RecordingKind; readonly filename?:string; readonly graphRevision?:number; readonly tracks?:readonly string[]; readonly segment?:boolean; readonly scheduleAt?:string; readonly manual?:boolean; readonly overwrite?:boolean; readonly minFreeBytes?:number; readonly env?:Record<string,string|undefined>; }
const now=()=>new Date().toISOString();
const formats:RecordingFormat[]=['mp4','mkv','mov','ts','wav','mp3'];
const safeName=/^[A-Za-z0-9][A-Za-z0-9._ -]{0,180}$/;
const badName=/[\\/\0\n\r`$;&|<>:]|(^\.)|\.\./;
export function isRealRecordingEnabled(env:Record<string,string|undefined>=process.env){ return env.UBOS_ENABLE_REAL_RECORDING==='true'&&env.NEXT_PUBLIC_UBOS_REAL_RECORDING==='true'; }
export function safeRecordingFilename(input:string|undefined, format:RecordingFormat, date=new Date()):string{ const stamp=date.toISOString().replace(/[:.]/g,'-'); const base=(input?.trim()||`ubos-recording-${stamp}`).replace(/\s+/g,' '); if(!safeName.test(base)||badName.test(base)) throw new Error('Invalid or unsafe recording filename rejected'); const ext=`.${format}`; if(!formats.includes(format)) throw new Error('Unsafe recording extension rejected'); return base.toLowerCase().endsWith(ext)?base:`${base}${ext}`; }
export async function validateRecordingOutput(input:RecordingPipelineOptions):Promise<RecordingOutput>{ const {fs,path}=await loadFs(); const format=input.format??'mp4'; if(!formats.includes(format)) throw new Error('Unsupported recording format'); const root=path.resolve(input.outputDirectory); if(root.includes('\0')) throw new Error('Output directory contains null byte'); fs.mkdirSync(root,{recursive:true}); const stat=fs.statSync(root); if(!stat.isDirectory() || stat.isSymbolicLink?.()) throw new Error('Output directory unavailable or symbolic link'); const real=fs.realpathSync(root); const filename=safeRecordingFilename(input.filename,format); const finalPath=path.resolve(real,filename); if(!finalPath.startsWith(real+'/')&&finalPath!==path.join(real,filename)) throw new Error('Path traversal rejected'); if(fs.existsSync(finalPath)&&!input.overwrite) throw new Error('Recording overwrite protection rejected existing file'); const temporaryPath=path.join(real,`.${filename}.tmp`); return Object.freeze({id:`recording-output-${Date.now()}`,directory:real,filename,finalPath,temporaryPath,format,overwrite:input.overwrite??false,...(input.segment !== undefined ? { segment: input.segment } : {}),currentSizeBytes:0,finalized:false}); }
function stats(bytes=0, startedAt?:string):RecordingStatistics{ const durationMs=startedAt?Math.max(0,Date.now()-Date.parse(startedAt)):0; return {durationMs,currentSizeBytes:bytes,bitrateKbps:durationMs?Math.round(bytes*8/durationMs):0,fps: durationMs?30:0,droppedFrames:0,diskUsageBytes:bytes,remainingSpaceBytes:1024*1024*1024,writeSpeedBytesPerSecond:durationMs?Math.round(bytes/(durationMs/1000)):0}; }
function failure(kind:RecordingFailure['kind'],message:string,retryable=true):RecordingFailure{ return {kind,message,retryable,occurredAt:now(),ubosFailure:createFailureRecord({category:'RECORDING_FAILURE',sourceLayer:'execution',subsystem:'recording-runtime',message,recoverable:retryable,metadata:{runtimeSupervised:true,graphMutationAllowed:false}})}; }
const rec=(type:RecordingReplayRecord['type'],jobId:string,data:Record<string,string|number|boolean>):RecordingReplayRecord=>Object.freeze({type,timestamp:now(),jobId,data});
export async function createRecordingJob(options:RecordingPipelineOptions):Promise<RecordingJob>{ const output=await validateRecordingOutput(options); const id=`recording-job-${Date.now()}`; return Object.freeze({id,graphRevision:options.graphRevision??0,kind:options.kind??'program',state:'created',output,createdAt:now(),...(options.scheduleAt?{scheduleAt:options.scheduleAt}:{}),tracks:options.tracks??['program-video','program-audio'],segmentIndex:0,manual:options.manual??!options.scheduleAt,statistics:stats(),replay:[rec('command',id,{command:'create',graphRevision:options.graphRevision??0})],containsRuntimeHandles:false}); }
export class RecordingMonitor { summarize(job:RecordingJob){return Object.freeze({...job.statistics,state:job.state,healthy:!job.latestFailure,currentFile:job.output.finalPath,outputFolder:job.output.directory});} }
export class RecordingScheduler { constructor(private readonly maxConcurrent=2){} queue:RecordingJob[]=[]; active=new Set<string>(); enqueue(j:RecordingJob){this.queue.push(j);return this.queue.length;} canStart(){return this.active.size<this.maxConcurrent;} markStarted(id:string){this.active.add(id);} markStopped(id:string){this.active.delete(id);} }
export class RecordingRecovery { recover(job:RecordingJob){ return Object.freeze({...job,state:'prepared' as const,replay:[...job.replay,rec('lifecycle',job.id,{recovered:true})]}); } }
export class RecordingValidator { validateOutput=validateRecordingOutput; validateFilename=safeRecordingFilename; }
export function createRecordingManifest(job:RecordingJob):RecordingManifest{ return Object.freeze({id:`recording-manifest-${job.id}`,jobId:job.id,generatedAt:now(),output:{finalPath:job.output.finalPath,format:job.output.format,filename:job.output.filename,...(job.output.segment !== undefined ? { segment: job.output.segment } : {}),finalized:job.output.finalized},lifecycle:job.state,statistics:job.statistics,tracks:job.tracks,replaySafe:true,containsMediaPayloads:false,containsFileHandles:false,containsProcessHandles:false}); }
export class RecordingSessionManager { private jobs=new Map<string,RecordingJob>(); upsert(j:RecordingJob){this.jobs.set(j.id,j);return j;} get(id:string){return this.jobs.get(id);} list(){return [...this.jobs.values()];} delete(id:string){return this.jobs.delete(id);} }
export class RecordingPipeline { readonly sessions=new RecordingSessionManager(); readonly scheduler=new RecordingScheduler(); readonly monitor=new RecordingMonitor(); readonly recovery=new RecordingRecovery(); readonly validator=new RecordingValidator(); readonly supervisor:RuntimeSupervisor; readonly ffmpeg:FFmpegRuntime; constructor(private readonly env:Record<string,string|undefined>=process.env){ this.supervisor=new RuntimeSupervisor(createProductionRuntime({id:'recording-production-runtime'})); this.ffmpeg=createFFmpegRuntime({env:{} as Record<string,string>,featureFlags:{UBOS_ENABLE_REAL_FFMPEG:isRealRecordingEnabled(env),NEXT_PUBLIC_UBOS_REAL_FFMPEG:isRealRecordingEnabled(env)}}); this.supervisor.register(this.subsystem('idle')); }
  private subsystem(state:RuntimeSubsystem['state'],job?:RecordingJob):RuntimeSubsystem{return {id:'recording-runtime',type:'recording',label:'Recording Runtime',required:false,state,health:job?.latestFailure?'failed':state==='running'?'healthy':'degraded',degradedModes:[],diagnostics:job?{jobId:job.id,durationMs:job.statistics.durationMs,currentSizeBytes:job.statistics.currentSizeBytes,bitrateKbps:job.statistics.bitrateKbps,fps:job.statistics.fps,droppedFrames:job.statistics.droppedFrames,diskUsageBytes:job.statistics.diskUsageBytes,remainingSpaceBytes:job.statistics.remainingSpaceBytes,writeSpeedBytesPerSecond:job.statistics.writeSpeedBytesPerSecond}: {featureFlag:isRealRecordingEnabled(this.env)}};}
  async create(options:RecordingPipelineOptions){ const job=await createRecordingJob(options); return this.sessions.upsert(job); }
  prepare(jobId:string){ const j=this.must(jobId); return this.patch(j,{state:'prepared',replay:[...j.replay,rec('lifecycle',j.id,{prepared:true})]}); }
  async start(jobId:string){ let j=this.must(jobId); if(!this.scheduler.canStart()){this.scheduler.enqueue(j); return this.patch(j,{state:'prepared',replay:[...j.replay,rec('command',j.id,{queued:true})]});} this.scheduler.markStarted(j.id); const startedAt=now(); if(isRealRecordingEnabled(this.env)){ const args=this.ffmpegArgs(j.output); await this.ffmpeg.manager.start(buildCommand({executable:locateFFmpeg(this.env),args,outputs:[j.output.temporaryPath],metadata:{recordingJobId:j.id}})); } else { const {fs}=await loadFs(); fs.writeFileSync(j.output.temporaryPath,`UBOS mock recording ${j.id}\n`); } j=this.patch(j,{state:'recording',startedAt,statistics:stats(128,startedAt),replay:[...j.replay,rec('lifecycle',j.id,{started:true})]}); this.supervisor.register(this.subsystem('running',j)); return j; }
  private ffmpegArgs(o:RecordingOutput){ const audioOnly=o.format==='wav'||o.format==='mp3'; return audioOnly?['-y','-f','lavfi','-i','sine=frequency=1000:duration=1',o.temporaryPath]:['-y','-f','lavfi','-i','testsrc=size=1280x720:rate=30','-f','lavfi','-i','sine=frequency=1000:duration=1','-t','1','-pix_fmt','yuv420p',o.temporaryPath]; }
  pause(id:string){const j=this.must(id); return this.patch(j,{state:'paused',replay:[...j.replay,rec('state',id,{paused:true})]});} resume(id:string){const j=this.must(id); return this.patch(j,{state:'recording',replay:[...j.replay,rec('state',id,{resumed:true})]});} split(id:string){const j=this.must(id); return this.patch(j,{state:'splitting',segmentIndex:j.segmentIndex+1,replay:[...j.replay,rec('command',id,{split:j.segmentIndex+1})]});}
  async stop(id:string){ let j=this.must(id); await this.ffmpeg.manager.stop(); this.scheduler.markStopped(id); j=this.patch(j,{state:'stopped',stoppedAt:now(),statistics:stats(j.statistics.currentSizeBytes,j.startedAt),replay:[...j.replay,rec('lifecycle',id,{stopped:true})]}); this.supervisor.register(this.subsystem('stopped',j)); return j; }
  async finalize(id:string){ const {fs}=await loadFs(); const j=this.must(id); if(fs.existsSync(j.output.temporaryPath)) fs.renameSync(j.output.temporaryPath,j.output.finalPath); else if(!fs.existsSync(j.output.finalPath)) fs.writeFileSync(j.output.finalPath,`UBOS recording placeholder ${id}\n`); const size=fs.statSync(j.output.finalPath).size; return this.patch(j,{state:'finalized',output:{...j.output,currentSizeBytes:size,finalized:true},statistics:stats(size,j.startedAt),replay:[...j.replay,rec('lifecycle',id,{finalized:true,size})]}); }
  archive(id:string){const j=this.must(id); return this.patch(j,{state:'archived',replay:[...j.replay,rec('lifecycle',id,{archived:true})]});} async delete(id:string){ const {fs}=await loadFs(); const j=this.must(id); if(fs.existsSync(j.output.finalPath)) fs.unlinkSync(j.output.finalPath); const d=this.patch(j,{state:'deleted',replay:[...j.replay,rec('lifecycle',id,{deleted:true})]}); this.sessions.delete(id); return d; }
  manifest(id:string){return createRecordingManifest(this.must(id));} health(id:string){return this.monitor.summarize(this.must(id));} fail(id:string,kind:RecordingFailure['kind'],message:string){const j=this.must(id); const f=failure(kind,message); this.supervisor.failSubsystem('recording-runtime',message); return this.patch(j,{state:'failed',latestFailure:f,replay:[...j.replay,rec('state',id,{failed:true})]});}
  private patch(j:RecordingJob,p:Partial<RecordingJob>){ const n=Object.freeze({...j,...p,containsRuntimeHandles:false}) as RecordingJob; this.sessions.upsert(n); return n; } private must(id:string){ const j=this.sessions.get(id); if(!j) throw new Error(`Recording job ${id} not found`); return j; }
}
export { RecordingPipeline as RecordingJobRuntime };


// UBOS 2.0 Phase 2.13 Recording Pipeline foundation
export type RecordingContainer = 'mp4' | 'mov' | 'mkv';
export type RecordingPipelineLifecycle = 'idle' | 'preparing' | 'recording' | 'paused' | 'stopped' | 'failed';
export type RecordingRuntimeEventType = 'recording_created' | 'recording_preparing' | 'recording_started' | 'recording_frame_recorded' | 'recording_audio_recorded' | 'recording_paused' | 'recording_resumed' | 'recording_stopped' | 'recording_failed';
export interface RecordingMetadata { readonly durationMs: number; readonly frameCount: number; readonly audioSamples: number; readonly droppedFrames: number; readonly estimatedFileSizeBytes: number; }
export interface RecordingSourceBinding { readonly programOutputId: string; readonly audioMixerId: string; readonly videoSurfaceId?: string; readonly audioBusId?: string; readonly containsRuntimeHandles: false; }
export interface RecordingSession { readonly id: string; readonly state: RecordingPipelineLifecycle; readonly container: RecordingContainer; readonly outputUri: string; readonly source: RecordingSourceBinding; readonly createdAt: string; readonly startedAt?: string; readonly pausedAt?: string; readonly stoppedAt?: string; readonly clock: ReturnType<import('../sync/clock.js').MediaClock['getState']>; readonly scheduler: ReturnType<import('../sync/index.js').FrameScheduler['getStats']>; readonly metadata: RecordingMetadata; readonly events: readonly RecordingRuntimeEvent[]; readonly backend: RecordingBackendDescriptor; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface RecordingRuntimeEvent { readonly id: string; readonly type: RecordingRuntimeEventType; readonly timestamp: string; readonly sessionId: string; readonly state: RecordingPipelineLifecycle; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface RecordingBackendDescriptor { readonly id: string; readonly name: string; readonly mode: 'metadata_only' | 'future_encoder'; readonly containers: readonly RecordingContainer[]; readonly supportsIsoRecording: false; readonly supportsCloudRecording: false; }
export interface RecordingPipelineSnapshot { readonly id: string; readonly state: RecordingPipelineLifecycle; readonly sessions: readonly RecordingSession[]; readonly activeSessionId?: string; readonly events: readonly RecordingRuntimeEvent[]; readonly backend: RecordingBackendDescriptor; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface RecordingPipelineV2 { readonly id: string; createSession(input: CreateRecordingSessionInput): RecordingSession; prepare(sessionId: string): RecordingSession; start(sessionId: string): RecordingSession; pause(sessionId: string): RecordingSession; resume(sessionId: string): RecordingSession; stop(sessionId: string): RecordingSession; fail(sessionId: string, message: string): RecordingSession; recordProgramFrame(sessionId: string, tick?: import('../sync/index.js').FrameTickEvent): RecordingSession; recordAudioFrame(sessionId: string, samples?: number, tick?: import('../sync/index.js').FrameTickEvent): RecordingSession; getSession(sessionId: string): RecordingSession | undefined; getSnapshot(): RecordingPipelineSnapshot; getEvents(): readonly RecordingRuntimeEvent[]; onRuntimeEvent(callback: (event: RecordingRuntimeEvent) => void): () => void; }
export interface CreateRecordingSessionInput { readonly id?: string; readonly container?: RecordingContainer; readonly outputUri?: string; readonly programOutput: import('../output-pipeline.js').ProgramOutput; readonly audioMixer: import('../media-runtime/audio-mixer.js').AudioMixer; readonly mediaClock?: import('../sync/clock.js').MediaClock; readonly frameScheduler?: import('../sync/index.js').FrameScheduler; readonly estimatedVideoBitrateMbps?: number; readonly estimatedAudioBitrateMbps?: number; readonly metadata?: Readonly<Record<string, unknown>>; }

const recordingContainers: readonly RecordingContainer[] = ['mp4', 'mov', 'mkv'];
const defaultRecordingBackend: RecordingBackendDescriptor = Object.freeze({ id: 'recording-backend:metadata-only', name: 'Metadata-only recording backend', mode: 'metadata_only', containers: recordingContainers, supportsIsoRecording: false, supportsCloudRecording: false });
const emptyRecordingMetadata = (): RecordingMetadata => Object.freeze({ durationMs: 0, frameCount: 0, audioSamples: 0, droppedFrames: 0, estimatedFileSizeBytes: 0 });
const reid = (type: string) => `${type}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
const estimateBytes = (durationMs: number, videoMbps = 12, audioMbps = 0.192) => Math.round(((videoMbps + audioMbps) * 1_000_000 / 8) * (durationMs / 1000));

export class MetadataRecordingPipeline implements RecordingPipelineV2 {
  private sessions = new Map<string, RecordingSession>();
  private events: RecordingRuntimeEvent[] = [];
  private listeners = new Set<(event: RecordingRuntimeEvent) => void>();
  private state: RecordingPipelineLifecycle = 'idle';
  private activeSessionId: string | undefined;
  constructor(readonly id = 'recording-pipeline:program', private readonly backend: RecordingBackendDescriptor = defaultRecordingBackend) {}
  createSession(input: CreateRecordingSessionInput): RecordingSession { const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const scheduler = input.frameScheduler ?? new FrameScheduler(clock); const container = input.container ?? 'mp4'; if (!recordingContainers.includes(container)) throw new Error(`Unsupported recording container ${container}`); const outputState = input.programOutput.getRuntimeState(); const sessionId = input.id ?? `recording-session:${Date.now()}`; const session: RecordingSession = Object.freeze({ id: sessionId, state: 'idle', container, outputUri: input.outputUri ?? `ubos-program-recording.${container}`, source: Object.freeze({ programOutputId: input.programOutput.id, audioMixerId: input.audioMixer.id, videoSurfaceId: outputState.videoSurface.id, audioBusId: outputState.audioBus.mixerBusId, containsRuntimeHandles: false }), createdAt: now(), clock: clock.getState(), scheduler: scheduler.getStats(), metadata: emptyRecordingMetadata(), events: [], backend: this.backend, containsRuntimeHandles: false, containsMediaPayloads: false }); this.sessions.set(sessionId, this.withEvent(session, 'recording_created', 'Recording session created', input.metadata)); return this.must(sessionId); }
  prepare(id: string) { this.state = 'preparing'; return this.patch(this.must(id), { state: 'preparing' }, 'recording_preparing', 'Recording pipeline preparing'); }
  start(id: string) { this.state = 'recording'; this.activeSessionId = id; const s = this.must(id); return this.patch(s, { state: 'recording', startedAt: s.startedAt ?? now() }, 'recording_started', 'Recording synchronized program output and audio mixer'); }
  pause(id: string) { this.state = 'paused'; return this.patch(this.must(id), { state: 'paused', pausedAt: now() }, 'recording_paused', 'Recording paused'); }
  resume(id: string) { this.state = 'recording'; return this.patch(this.must(id), { state: 'recording' }, 'recording_resumed', 'Recording resumed'); }
  stop(id: string) { this.state = 'stopped'; this.activeSessionId = undefined; return this.patch(this.must(id), { state: 'stopped', stoppedAt: now() }, 'recording_stopped', 'Recording stopped'); }
  fail(id: string, message: string) { this.state = 'failed'; return this.patch(this.must(id), { state: 'failed' }, 'recording_failed', message); }
  recordProgramFrame(id: string, tick?: import('../sync/index.js').FrameTickEvent) { const s = this.must(id); if (s.state !== 'recording') return s; const durationMs = tick?.presentationTimestamp ?? tick?.timestamp ?? s.clock.presentationTimestamp; const dropped = tick?.diagnostics?.droppedFrames ?? 0; const metadata = Object.freeze({ ...s.metadata, durationMs: Math.max(s.metadata.durationMs, durationMs), frameCount: s.metadata.frameCount + 1, droppedFrames: s.metadata.droppedFrames + dropped, estimatedFileSizeBytes: estimateBytes(Math.max(s.metadata.durationMs, durationMs)) }); return this.patch(s, { metadata }, 'recording_frame_recorded', 'Program frame recorded', { frameId: tick?.frameId, droppedFrames: dropped }); }
  recordAudioFrame(id: string, samples = 480, tick?: import('../sync/index.js').FrameTickEvent) { const s = this.must(id); if (s.state !== 'recording') return s; const durationMs = tick?.presentationTimestamp ?? tick?.timestamp ?? s.metadata.durationMs; const metadata = Object.freeze({ ...s.metadata, durationMs: Math.max(s.metadata.durationMs, durationMs), audioSamples: s.metadata.audioSamples + samples, estimatedFileSizeBytes: estimateBytes(Math.max(s.metadata.durationMs, durationMs)) }); return this.patch(s, { metadata }, 'recording_audio_recorded', 'Audio mixer frame recorded', { samples, frameId: tick?.frameId }); }
  getSession(id: string) { return this.sessions.get(id); }
  getSnapshot(): RecordingPipelineSnapshot { return Object.freeze({ id: this.id, state: this.state, sessions: Object.freeze([...this.sessions.values()]), ...(this.activeSessionId ? { activeSessionId: this.activeSessionId } : {}), events: Object.freeze([...this.events]), backend: this.backend, containsRuntimeHandles: false, containsMediaPayloads: false }); }
  getEvents() { return Object.freeze([...this.events]); }
  onRuntimeEvent(callback: (event: RecordingRuntimeEvent) => void) { this.listeners.add(callback); return () => this.listeners.delete(callback); }
  private patch(s: RecordingSession, patch: Partial<RecordingSession>, type: RecordingRuntimeEventType, message: string, metadata: Record<string, unknown> = {}) { const next = Object.freeze({ ...s, ...patch, events: s.events, containsRuntimeHandles: false, containsMediaPayloads: false }) as RecordingSession; this.sessions.set(s.id, this.withEvent(next, type, message, metadata)); return this.must(s.id); }
  private withEvent(s: RecordingSession, type: RecordingRuntimeEventType, message: string, metadata: Readonly<Record<string, unknown>> = {}) { const event: RecordingRuntimeEvent = Object.freeze({ id: reid(type), type, timestamp: now(), sessionId: s.id, state: s.state, message, metadata: Object.freeze({ ...metadata, backend: this.backend.id }) }); this.events = [event, ...this.events].slice(0, 250); this.listeners.forEach((cb) => cb(event)); return Object.freeze({ ...s, events: Object.freeze([event, ...s.events].slice(0, 250)) }) as RecordingSession; }
  private must(id: string) { const s = this.sessions.get(id); if (!s) throw new Error(`Recording session ${id} not found`); return s; }
}

export const createRecordingPipeline = (input: { id?: string; backend?: RecordingBackendDescriptor } = {}): RecordingPipelineV2 => new MetadataRecordingPipeline(input.id, input.backend);

export async function createDemoRecordingSession(input: { programOutput: import('../output-pipeline.js').ProgramOutput; audioMixer: import('../media-runtime/audio-mixer.js').AudioMixer; mediaClock?: import('../sync/clock.js').MediaClock; frameScheduler?: import('../sync/index.js').FrameScheduler } ) { const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const scheduler = input.frameScheduler ?? new FrameScheduler(clock); const pipeline = createRecordingPipeline({ id: 'recording-pipeline:demo' }); const session = pipeline.createSession({ id: 'recording-session:demo', container: 'mkv', outputUri: 'demo-program-recording.mkv', programOutput: input.programOutput, audioMixer: input.audioMixer, mediaClock: clock, frameScheduler: scheduler, metadata: { demo: true } }); pipeline.prepare(session.id); pipeline.start(session.id); const tick = scheduler.createTick(); pipeline.recordProgramFrame(session.id, tick); pipeline.recordAudioFrame(session.id, 480, tick); pipeline.pause(session.id); pipeline.resume(session.id); pipeline.stop(session.id); return { pipeline: pipeline.getSnapshot(), session: pipeline.getSession(session.id)!, events: pipeline.getEvents() }; }
