import type { BroadcastInputDefinition, BroadcastIoInspector, BroadcastIoManifest, BroadcastIoProtocol, BroadcastOutputDestination, BroadcastOutputKind, BroadcastOutputRoute, BroadcastRouteSource, DestinationHealth, DestinationRuntimeStatus, EncoderSettings, LatencyMode, ReconnectPolicy } from './types.js';

const now = () => new Date().toISOString();
const protocols: BroadcastInputDefinition['protocol'][] = ['ndi_source','srt_listener','srt_caller','rtmp_input','rtmps_input','rtp','udp','hls','mpeg_ts','webrtc_input','ip_camera','hardware_capture_card','virtual_camera'];
export const createBroadcastInputs = (): BroadcastInputDefinition[] => protocols.map((protocol) => ({ id: `input-${protocol}`, name: protocol.replace(/_/g, ' ').toUpperCase(), protocol, enabled: true, metadata: { metadataOnly: true } }));
const encoder = (resolution = '1920x1080', fps = 60, bitrateKbps = 8000): EncoderSettings => ({ resolution, fps, bitrateKbps, codec: 'h264', audioChannels: 2 });
const runtime = (health: DestinationHealth = 'unknown'): DestinationRuntimeStatus => ({ status: health === 'healthy' ? 'connected' : 'disconnected', droppedFrames: 0, packetsLost: 0, currentBitrateKbps: 0, currentFps: 0, latencyMs: 0, reconnectAttempts: 0, health, healthHistory: [{ at: now(), health, message: 'Metadata-only telemetry snapshot' }] });
export function createOutputDestination(input: { id: string; name: string; kind: BroadcastOutputKind; protocol: BroadcastIoProtocol; encoder?: Partial<EncoderSettings>; latencyMode?: LatencyMode; reconnectPolicy?: ReconnectPolicy; health?: DestinationHealth; }): BroadcastOutputDestination { const timestamp = now(); const enc = { ...encoder(), ...input.encoder }; return { id: input.id, name: input.name, kind: input.kind, protocol: input.protocol, encoder: enc, latencyMode: input.latencyMode ?? 'low', reconnectPolicy: input.reconnectPolicy ?? 'exponential', protocolSettings: { host: 'localhost', port: input.protocol === 'srt' ? 9000 : 1935, passwordConfigured: false, encryption: input.protocol === 'rtmps' ? 'tls' : 'none', latencyMs: 120, retries: 5, reconnect: true, bandwidthKbps: enc.bitrateKbps }, status: input.health === 'healthy' ? 'connected' : 'disconnected', runtime: runtime(input.health), createdAt: timestamp, updatedAt: timestamp }; }
export function createDefaultOutputDestinations(): BroadcastOutputDestination[] { const outputs: Array<{ id: string; name: string; kind: BroadcastOutputKind; protocol: BroadcastIoProtocol }> = [ { id: 'program-main', name: 'Program Output', kind: 'program', protocol: 'srt' }, { id: 'preview-out', name: 'Preview Output', kind: 'preview', protocol: 'ndi' }, { id: 'aux-1', name: 'Aux Output 1', kind: 'aux', protocol: 'udp' }, { id: 'clean-feed', name: 'Clean Feed', kind: 'clean_feed', protocol: 'rtmps' }, { id: 'multiview', name: 'Multiview Output', kind: 'multiview', protocol: 'hls' }, { id: 'replay-out', name: 'Replay Output', kind: 'replay', protocol: 'srt' }, { id: 'graphics-out', name: 'Graphics Output', kind: 'graphics', protocol: 'ndi' }, { id: 'iso-cam-1', name: 'ISO Camera 1', kind: 'iso', protocol: 'rtmp' }, { id: 'recording-feed', name: 'Recording Feed', kind: 'recording', protocol: 'mpeg_ts' }, { id: 'streaming-feed', name: 'Streaming Feed', kind: 'streaming', protocol: 'rtmps' } ]; return outputs.map((output, index) => createOutputDestination({ ...output, health: index === 0 ? 'healthy' : 'unknown' })); }
export const createRoute = (source: BroadcastRouteSource, destinationId: string): BroadcastOutputRoute => ({ id: `route-${source}-${destinationId}`, source, destinationId, enabled: true });
export function createDefaultRoutes(destinations = createDefaultOutputDestinations()): BroadcastOutputRoute[] { const byKind = (kind: BroadcastOutputKind) => destinations.find((d) => d.kind === kind)?.id ?? destinations[0]!.id; return [createRoute('program', byKind('program')), createRoute('preview', byKind('preview')), createRoute('replay', byKind('replay')), createRoute('graphics', byKind('graphics'))]; }
export function createBroadcastIoManifest(input?: Partial<BroadcastIoManifest>): BroadcastIoManifest { const destinations = input?.destinations ?? createDefaultOutputDestinations(); return { version: '3.13', inputs: input?.inputs ?? createBroadcastInputs(), destinations, routes: input?.routes ?? createDefaultRoutes(destinations), settings: input?.settings ?? { defaultReconnectPolicy: 'exponential', preserveMetadataOnlyState: true }, containsRuntimeSockets: false, containsRuntimeTransportObjects: false }; }
export function inspectDestination(manifest: BroadcastIoManifest, destinationId: string): BroadcastIoInspector | null { const destination = manifest.destinations.find((item) => item.id === destinationId); if (!destination) return null; const { runtime } = destination; return { destination, protocol: destination.protocol, encoder: destination.encoder, transport: destination.protocolSettings, packetStatistics: { droppedFrames: runtime.droppedFrames, packetsLost: runtime.packetsLost, currentBitrateKbps: runtime.currentBitrateKbps, currentFps: runtime.currentFps, latencyMs: runtime.latencyMs, reconnectAttempts: runtime.reconnectAttempts }, healthHistory: runtime.healthHistory }; }
