import type { CompositorManifest, CompositionLayer, EffectDefinition, TransitionDefinition, ShaderDefinition, RenderPass, RenderNode, LayerGroupKind } from './types.js';
import { COMPOSITOR_SCHEMA_VERSION } from './types.js';
const base = (id: string, name: string, description: string) => ({ id, name, version: COMPOSITOR_SCHEMA_VERSION, description, metadataOnly: true as const });
export function createCompositionLayer(partial: Partial<CompositionLayer> & Pick<CompositionLayer, 'id' | 'name' | 'layerType'>): CompositionLayer { return { ...base(partial.id, partial.name, 'Compositor layer metadata.'), visible: true, opacity: 1, blendMode: 'normal', position: { x: 0, y: 0 }, scale: { x: 1, y: 1 }, rotation: 0, crop: { top: 0, right: 0, bottom: 0, left: 0 }, anchor: { x: 0.5, y: 0.5 }, zOrder: 0, locked: false, muted: false, selected: false, programVisible: true, previewVisible: true, effectIds: [], ...partial }; }
const effectTypes = ['opacity','blur','shadow','glow','mask','chroma_key','luma_key','crop','color_correction','transform','perspective','gaussian_blur','sharpen','brightness','contrast','saturation'] as const;
const transitionTypes = ['cut','fade','dissolve','wipe','slide','push','zoom','stinger','dip','custom'] as const;
export const createDefaultEffectDefinitions = (): EffectDefinition[] => effectTypes.map((type) => ({ ...base(`effect-${type}`, type.replace(/_/g, ' '), 'Effect metadata definition; no shader execution.'), type, parameters: {}, enabled: false }));
export const createDefaultTransitionDefinitions = (): TransitionDefinition[] => transitionTypes.map((type) => ({ ...base(`transition-${type}`, type.toUpperCase(), 'Transition metadata definition; no frame execution.'), type, durationMs: type === 'cut' ? 0 : 500, parameters: {} }));
export const createDefaultShaderDefinitions = (): ShaderDefinition[] => ['vertex','fragment','compute'].map((stage) => ({ ...base(`shader-${stage}`, `${stage} shader metadata`, 'Shader contract metadata only; no shader source.'), stage: stage as ShaderDefinition['stage'], parameters: [], uniforms: [], textures: [], inputs: [], outputs: [], language: 'metadata_only' }));
const passes = ['background','scene','media','graphics','effects','transition','output','preview','confidence','aux'] as const;
export const createDefaultRenderPasses = (): RenderPass[] => passes.map((passType) => ({ ...base(`pass-${passType}`, `${passType} pass`, 'Render pass contract metadata only.'), passType, inputNodeIds: [], effectIds: [], enabled: true }));
export function createDefaultRenderGraph() { const nodeTypes = ['scene','layer_stack','effects','transition','output','encoder'] as const; const nodes: RenderNode[] = nodeTypes.map((nodeType) => ({ ...base(`node-${nodeType}`, nodeType.replace(/_/g, ' '), 'Reusable compositor render graph node.'), nodeType, inputIds: [], outputIds: [] })); return { ...base('render-graph-default', 'Scene → Layer Stack → Effects → Transition → Output → Encoder', 'Reusable render graph contract; no execution.'), nodes, passes: createDefaultRenderPasses(), edges: nodeTypes.slice(0, -1).map((from, index) => ({ from: `node-${from}`, to: `node-${nodeTypes[index + 1]}` })), executionEnabled: false as const }; }
export function createCompositorManifest(): CompositorManifest { const effects = createDefaultEffectDefinitions(); const transitions = createDefaultTransitionDefinitions(); const graph = createDefaultRenderGraph(); const layers = [createCompositionLayer({ id: 'layer-background', name: 'Background', layerType: 'background' }), createCompositionLayer({ id: 'layer-program-graphics', name: 'Program Graphics', layerType: 'graphics', zOrder: 10 }), createCompositionLayer({ id: 'layer-lower-third', name: 'Lower Third', layerType: 'lower_third', zOrder: 20 })]; const composition = { ...base('composition-default','Default Composition','Layer stack metadata only.'), layers, groups: ['graphics','replay','media','guests','branding','lower_thirds','sponsors','sports','news','virtual_sets'].map((kind) => ({ ...base(`group-${kind}`, kind.replace(/_/g, ' '), 'Reusable layer group.'), kind: kind as LayerGroupKind, layerIds: [], locked: false, visible: true })), effects, transitions, activeTransitionId: 'transition-cut', renderGraphId: graph.id }; const stats = { ...base('render-statistics','Render Statistics','Unavailable renderer statistics metadata.'), layerCount: layers.length, effectCount: effects.length, transitionCount: transitions.length, outputTargetCount: 0, frameQueueStatus: 'unavailable' as const, rendererStatus: 'unavailable' as const }; const health = { ...base('render-health','Render Health','Renderer inactive health metadata.'), status: 'renderer_inactive' as const, gpuConnected: false as const, rendererActive: false as const, messages: ['Unavailable','Renderer inactive','GPU not connected','Metadata only'] }; const context = { ...base('render-context','Render Context','Read-only engine integration references.'), readOnlyIntegration: true as const, rendererStatus: 'renderer_inactive' as const }; return { ...base('compositor-manifest','UBOS GPU Compositor Manifest','Phase 19 compositor architecture manifest.'), containsRuntimeHandles: false, shaders: createDefaultShaderDefinitions(), renderTargets: [], renderSurfaces: [], outputSurfaces: [], sceneRenderer: { ...base('scene-renderer','Scene Renderer','Future scene renderer contract.'), rendererStatus: 'renderer_inactive', supportedPasses: [...passes] }, frameRenderer: { ...base('frame-renderer','Frame Renderer','Future frame renderer contract.'), rendererStatus: 'renderer_inactive', acceptsRuntimeFrames: false }, compositor: { ...base('compositor','GPU Compositor','Professional compositor architecture; metadata only.'), status: 'renderer_inactive', composition, graph, pipeline: { ...base('render-pipeline','Render Pipeline','Pipeline contract; no execution.'), graphId: graph.id, passIds: graph.passes.map((p) => p.id), targetIds: [], outputSurfaceIds: [], executionEnabled: false }, context, statistics: stats, health } }; }
