import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
import type { EncoderBackend, EncoderPlan, EncoderProfile } from '../encoder/index.js';
import type { GpuBackendType, GpuSession } from '../gpu-runtime/index.js';
declare const process: { env: Record<string, string | undefined> } | undefined;
import { RuntimeSupervisor, createProductionRuntime, type RuntimeSubsystemType } from '../production-runtime/index.js';

export type HardwareVendor = 'NVIDIA'|'Intel'|'Apple'|'AMD'|'Mesa'|'Microsoft'|'Browser'|'Software'|'Unknown';
export type HardwareApi = 'NVENC'|'QuickSync'|'VideoToolbox'|'VAAPI'|'AMF'|'CUDA'|'OpenCL'|'Vulkan'|'Metal'|'DirectX'|'WebGPU'|'Software';
export type HardwareCodec = 'h264'|'h265'|'av1'|'vp8'|'vp9'|'prores';
export type HardwareHealthStatus = 'healthy'|'degraded'|'warning'|'critical'|'unavailable'|'recovering';
export type HardwareEventType = 'hardware_detected'|'capability_snapshot'|'device_reserved'|'device_released'|'encoder_selected'|'scheduling_decision'|'diagnostics_snapshot'|'recovery_planned'|'software_fallback';
export interface HardwareCapabilities { readonly apis: readonly HardwareApi[]; readonly codecs: readonly HardwareCodec[]; readonly maxResolution: { readonly width: number; readonly height: number }; readonly maxFps: number; readonly bitrateKbps: { readonly min: number; readonly max: number }; readonly memoryMb: number; readonly encoderCount: number; readonly driverVersion: string; readonly metadataOnly: true; }
export interface GPUDevice { readonly id: string; readonly name: string; readonly vendor: HardwareVendor; readonly api: HardwareApi; readonly backendType?: GpuBackendType; readonly capabilities: HardwareCapabilities; readonly temperatureC?: number; readonly utilization: number; readonly memoryUsedMb: number; readonly activeEncoders: number; readonly available: boolean; readonly health: HardwareHealthStatus; readonly warnings: readonly string[]; readonly metadata: Readonly<Record<string, unknown>>; }
export interface HardwareReservation { readonly id: string; readonly deviceId: string; readonly encoderApi: HardwareApi; readonly codec: HardwareCodec; readonly priority: number; readonly budget: { readonly memoryMb: number; readonly bitrateKbps: number; readonly fps: number }; readonly sessionId?: string; readonly planId?: string; readonly createdAt: string; readonly metadataOnly: true; }
export interface HardwareStatistics { readonly gpuUsage: number; readonly encoderUsage: number; readonly memoryUsedMb: number; readonly memoryLimitMb: number; readonly temperatureC?: number; readonly utilization: number; readonly latencyMs: number; readonly droppedFrames: number; readonly activeReservations: number; }
export interface HardwareHealth { readonly status: HardwareHealthStatus; readonly deviceId?: string; readonly warnings: readonly string[]; readonly driverVersion?: string; readonly temperatureC?: number; readonly utilization: number; readonly latestFailure?: HardwareFailure; }
export interface HardwareFailure { readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly deviceId?: string; readonly ubosFailure: UBOSFailure; }
export interface HardwareRecoveryPlan { readonly id: string; readonly action: 'retry_device'|'restart_driver'|'restart_encoder'|'fallback_software'|'fail_session'; readonly deviceId?: string; readonly reason: string; readonly steps: readonly string[]; readonly fallbackBackend: EncoderBackend; readonly replaySafe: true; readonly metadataOnly: true; }
export interface HardwareDiagnostics { readonly devices: readonly GPUDevice[]; readonly reservations: readonly HardwareReservation[]; readonly statistics: readonly HardwareStatistics[]; readonly health: HardwareHealth; readonly warnings: readonly string[]; readonly containsRuntimeHandles: false; }
export interface HardwareManifest { readonly id: string; readonly name: 'Hardware Acceleration Runtime'; readonly version: '9.7'; readonly enabled: boolean; readonly fallback: 'software_encoder'; readonly capabilities: readonly HardwareCapabilities[]; readonly diagnostics: HardwareDiagnostics; readonly replay: readonly HardwareEvent[]; readonly containsRuntimeHandles: false; readonly metadataOnly: true; }
export interface HardwareEvent { readonly id: string; readonly type: HardwareEventType; readonly timestamp: string; readonly payload: Readonly<Record<string, unknown>>; readonly containsRuntimeHandles: false; }
const now=()=>new Date().toISOString(); let seq=0;
export const isHardwareRuntimeEnabled=(env:Record<string,string|undefined>=typeof process !== 'undefined' && process ? process.env : {})=>env.UBOS_ENABLE_HARDWARE_RUNTIME==='true'||env.NEXT_PUBLIC_UBOS_HARDWARE_RUNTIME==='true';
export const defaultHardwareCapabilities=(api:HardwareApi='Software'):HardwareCapabilities=>({ apis:[api], codecs:api==='Software'?['h264','vp8','vp9']:['h264','h265','av1'], maxResolution:{width:api==='Software'?1920:7680,height:api==='Software'?1080:4320}, maxFps:api==='Software'?60:240, bitrateKbps:{min:100,max:api==='Software'?25000:120000}, memoryMb:api==='Software'?1024:8192, encoderCount:api==='Software'?1:3, driverVersion:api==='Software'?'software-fallback':'metadata-driver', metadataOnly:true});
export function createHardwareDevice(input: Partial<GPUDevice> & { id:string; api?:HardwareApi } ): GPUDevice { const api=input.api??input.capabilities?.apis[0]??'Software'; return { name:`${api} metadata device`, vendor:api==='NVENC'||api==='CUDA'?'NVIDIA':api==='QuickSync'?'Intel':api==='VideoToolbox'||api==='Metal'?'Apple':api==='AMF'?'AMD':api==='DirectX'?'Microsoft':api==='WebGPU'?'Browser':api==='Software'?'Software':'Unknown', api, capabilities:defaultHardwareCapabilities(api), utilization:0, memoryUsedMb:0, activeEncoders:0, available:true, health:'healthy', warnings:[], metadata:{runtimeOnly:false,serializesHandles:false}, ...input }; }
export class DeviceManager { constructor(private devices:GPUDevice[]=[]){} detect(env:Record<string,string|undefined>={}){ if(!this.devices.length){ const apis:HardwareApi[]=isHardwareRuntimeEnabled(env)?['NVENC','QuickSync','VideoToolbox','VAAPI','AMF','CUDA','OpenCL','Vulkan','Metal','DirectX','WebGPU','Software']:['Software']; this.devices=apis.map((api,i)=>createHardwareDevice({id:`hardware-device:${api.toLowerCase()}:${i}`,api})); } return this.enumerate(); } enumerate(){ return [...this.devices]; } get(id:string){ return this.devices.find(d=>d.id===id); } update(device:GPUDevice){ this.devices=this.devices.map(d=>d.id===device.id?device:d); return device; } }
export class HardwareValidator { validateDevice(d:GPUDevice){ const errors:string[]=[]; if(!d.id||d.vendor==='Unknown')errors.push('Unknown devices are rejected'); if(d.capabilities.metadataOnly!==true)errors.push('Invalid capabilities: metadataOnly must be true'); if(d.capabilities.encoderCount<0||d.capabilities.memoryMb<0||d.capabilities.maxFps<=0)errors.push('Invalid capabilities'); if(!d.capabilities.driverVersion)errors.push('Driver mismatch: missing driver version'); return {valid:errors.length===0,errors,warnings:d.warnings}; } validateReservation(r:HardwareReservation,d?:GPUDevice){ const errors:string[]=[]; if(!d)errors.push('Unknown device reservation'); else { if(!d.available)errors.push('Unsafe reservation: device unavailable'); if(d.activeEncoders>=d.capabilities.encoderCount)errors.push('Over allocation: encoder count exceeded'); if(d.memoryUsedMb+r.budget.memoryMb>d.capabilities.memoryMb)errors.push('Over allocation: memory exceeded'); if(r.budget.bitrateKbps>d.capabilities.bitrateKbps.max||r.budget.fps>d.capabilities.maxFps)errors.push('Invalid capabilities: request exceeds limits'); if(!d.capabilities.apis.includes(r.encoderApi))errors.push('Driver mismatch: requested API unsupported'); } return {valid:errors.length===0,errors,warnings:[]}; } assertMetadataOnly(value:unknown){ const text=JSON.stringify(value); const forbidden=/(GPUDevice|CUcontext|ID3D|VkDevice|MTLDevice|CVPixelBuffer|VADisplay|AMFContext|cl_context|runtimeOnly":true|serializable":false)/; return {valid:!forbidden.test(text),errors:forbidden.test(text)?['Runtime hardware handle marker detected']:[],warnings:[]}; } }
export class DeviceScheduler { constructor(private validator=new HardwareValidator()){} estimateCapacity(d:GPUDevice){ return Math.max(0,d.capabilities.encoderCount-d.activeEncoders); } selectDevice(devices:readonly GPUDevice[], profile?:Partial<EncoderProfile>, priority=0){ const codec=(profile?.videoCodec??'h264') as HardwareCodec; return [...devices].filter(d=>d.available&&d.capabilities.codecs.includes(codec)&&this.validator.validateDevice(d).valid).sort((a,b)=>b.health.localeCompare(a.health)||a.activeEncoders-b.activeEncoders||a.utilization-b.utilization||priority)[0]; } reserve(device:GPUDevice,input:Partial<HardwareReservation> & {codec?:HardwareCodec}):HardwareReservation{ return { id:input.id??`hardware-reservation:${++seq}`, deviceId:device.id, encoderApi:input.encoderApi??device.api, codec:input.codec??'h264', priority:input.priority??0, budget:input.budget??{memoryMb:512,bitrateKbps:4500,fps:30}, ...(input.sessionId?{sessionId:input.sessionId}:{}), ...(input.planId?{planId:input.planId}:{}), createdAt:now(), metadataOnly:true }; } }
export class EncoderManager { selectEncoder(device?:GPUDevice):EncoderBackend{ if(!device)return 'software'; const map:Partial<Record<HardwareApi,EncoderBackend>>={NVENC:'nvenc',QuickSync:'quicksync',VideoToolbox:'videotoolbox',AMF:'amf',VAAPI:'vaapi',Software:'software'}; return map[device.api]??'software'; } allocate(plan:EncoderPlan, devices:readonly GPUDevice[]){ const scheduler=new DeviceScheduler(); const device=scheduler.selectDevice(devices,plan.profile,plan.profile.lowLatency?100:0); const backend=this.selectEncoder(device); return {backend,device,reservation:device?scheduler.reserve(device,{planId:plan.id,codec:plan.profile.videoCodec as HardwareCodec,budget:{memoryMb:512,bitrateKbps:plan.profile.bitrate.targetKbps,fps:plan.profile.resolution.fps}}):undefined,warnings:backend==='software'?['Hardware unavailable; falling back to software encoder']:[]}; } }
export class HardwareResourcePool { private reservations=new Map<string,HardwareReservation>(); add(r:HardwareReservation){this.reservations.set(r.id,r);return r;} release(id:string){return this.reservations.delete(id);} list(){return [...this.reservations.values()];} }
export class HardwareStatisticsCollector { summarize(device:GPUDevice,reservations:readonly HardwareReservation[]=[]):HardwareStatistics{ return {gpuUsage:device.utilization,encoderUsage:device.capabilities.encoderCount?device.activeEncoders/device.capabilities.encoderCount:0,memoryUsedMb:device.memoryUsedMb,memoryLimitMb:device.capabilities.memoryMb,...(device.temperatureC!==undefined?{temperatureC:device.temperatureC}:{}),utilization:device.utilization,latencyMs:Math.round(4+device.utilization*20),droppedFrames:device.health==='healthy'?0:1,activeReservations:reservations.filter(r=>r.deviceId===device.id).length}; }}
export class HardwareRecovery { plan(failure:HardwareFailure):HardwareRecoveryPlan{ const action=failure.code.includes('DRIVER')?'restart_driver':failure.code.includes('ENCODER')?'restart_encoder':failure.retryable?'retry_device':'fallback_software'; return {id:`hardware-recovery:${++seq}`,action,...(failure.deviceId ? { deviceId: failure.deviceId } : {}),reason:failure.message,steps:action==='fallback_software'?['select software encoder','preserve graph metadata','emit replay event']:['quiesce sessions','refresh capability snapshot','resume scheduling'],fallbackBackend:'software',replaySafe:true,metadataOnly:true}; }}
export class HardwareHealthMonitor { summarize(devices:readonly GPUDevice[], failures:readonly HardwareFailure[]=[]):HardwareHealth{ const latestFailure=failures.at(-1); const worst=devices.find(d=>d.health==='critical'||d.health==='unavailable')??devices.find(d=>d.health==='degraded'||d.health==='warning'); return {status:latestFailure&&!latestFailure.retryable?'critical':worst?.health??'healthy',...(worst?.id?{deviceId:worst.id}:{}),warnings:devices.flatMap(d=>d.warnings),...(worst?.capabilities.driverVersion?{driverVersion:worst.capabilities.driverVersion}:{}),...(worst?.temperatureC!==undefined?{temperatureC:worst.temperatureC}:{}),utilization:Math.max(0,...devices.map(d=>d.utilization)),...(latestFailure?{latestFailure}: {})}; }}
export function createHardwareFailure(input:{code:string;message:string;deviceId?:string;retryable?:boolean}):HardwareFailure{ return {code:input.code,message:input.message,retryable:input.retryable??true,occurredAt:now(),...(input.deviceId?{deviceId:input.deviceId}:{}),ubosFailure:createFailureRecord({category:'EXECUTION_FAILURE',sourceLayer:'execution',subsystem:'hardware-runtime',message:input.message,recoverable:input.retryable??true,metadata:{graphMutationAllowed:false,runtimeOnly:false}})}; }
export class HardwareRuntime { readonly devices=new DeviceManager(); readonly encoders=new EncoderManager(); readonly scheduler=new DeviceScheduler(); readonly pool=new HardwareResourcePool(); readonly recovery=new HardwareRecovery(); readonly validator=new HardwareValidator(); readonly stats=new HardwareStatisticsCollector(); readonly health=new HardwareHealthMonitor(); readonly supervisor=new RuntimeSupervisor(createProductionRuntime({id:'hardware-production-runtime'})); private events:HardwareEvent[]=[]; private failures:HardwareFailure[]=[]; constructor(private env:Record<string,string|undefined>=typeof process !== 'undefined' && process ? process.env : {}){ this.supervisor.register({id:'hardware-runtime',type:'gpu' as RuntimeSubsystemType,label:'Hardware Runtime',required:false,state:'ready',health:'healthy',degradedModes:[],diagnostics:{metadataOnly:true}}); }
  detect(){ const devices=this.devices.detect(this.env); this.emit('hardware_detected',{deviceCount:devices.length}); this.emit('capability_snapshot',{capabilities:devices.map(d=>d.capabilities)}); return devices; }
  schedule(plan:EncoderPlan){ const devices=this.detect(); const allocation=this.encoders.allocate(plan,devices); if(allocation.reservation){ const validation=this.validator.validateReservation(allocation.reservation,allocation.device); if(!validation.valid) return {success:false,backend:'software' as EncoderBackend,warnings:allocation.warnings,errors:validation.errors}; this.pool.add(allocation.reservation); this.emit('device_reserved',{...allocation.reservation}); } if(allocation.backend==='software') this.emit('software_fallback',{planId:plan.id}); this.emit('encoder_selected',{backend:allocation.backend,deviceId:allocation.device?.id}); return {success:true,backend:allocation.backend,device:allocation.device,reservation:allocation.reservation,warnings:allocation.warnings,errors:[]}; }
  recover(failure:HardwareFailure){ this.failures=[...this.failures,failure]; const plan=this.recovery.plan(failure); this.emit('recovery_planned',{...plan}); return plan; }
  diagnostics():HardwareDiagnostics{ const devices=this.devices.enumerate(); const reservations=this.pool.list(); const statistics=devices.map(d=>this.stats.summarize(d,reservations)); const health=this.health.summarize(devices,this.failures); this.emit('diagnostics_snapshot',{health:health.status,deviceCount:devices.length}); return {devices,reservations,statistics,health,warnings:health.warnings,containsRuntimeHandles:false}; }
  manifest():HardwareManifest{ const diagnostics=this.diagnostics(); return {id:'hardware-runtime',name:'Hardware Acceleration Runtime',version:'9.7',enabled:isHardwareRuntimeEnabled(this.env),fallback:'software_encoder',capabilities:diagnostics.devices.map(d=>d.capabilities),diagnostics,replay:this.events,containsRuntimeHandles:false,metadataOnly:true}; }
  integrateGpu(session?:GpuSession){ return {gpuRuntimeIntegrated:Boolean(session),backend:session?.backend.type??'metadata',metadataOnly:true}; }
  private emit(type:HardwareEventType,payload:Record<string,unknown>){ const event={id:`hardware-event:${++seq}`,type,timestamp:now(),payload,containsRuntimeHandles:false as const}; this.events=[...this.events,event]; return event; }
}
export const createHardwareRuntime=(env?:Record<string,string|undefined>)=>new HardwareRuntime(env);
export type DeviceManagerType=DeviceManager; export type EncoderManagerType=EncoderManager; export type DeviceSchedulerType=DeviceScheduler; export type HardwareStatisticsType=HardwareStatisticsCollector; export type HardwareHealthType=HardwareHealthMonitor; export type HardwareRecoveryType=HardwareRecovery; export type HardwareValidatorType=HardwareValidator; export type HardwareDiagnosticsType=HardwareDiagnostics; export type HardwareResourcePoolType=HardwareResourcePool;
