import type { EncoderFailure, EncoderHealth as CoreEncoderHealth, EncoderPlan, EncoderSession, EncoderStatus } from '../index.js';
import { estimateEncoderLoad, validateEncoderPlan } from '../index.js';

declare const process: { env?: Record<string, string | undefined>; versions?: Record<string, string | undefined> } | undefined;

type RuntimeMode = 'disabled' | 'dry_run' | 'mock_live' | 'live_ready';
type PlaceholderInput = 'test_source' | 'raw_pipe';
type PlaceholderOutput = 'file' | 'null' | 'rtmp' | 'segment';
export type FFmpegProcessState = 'idle' | 'disabled' | 'planned' | 'preparing' | 'ready' | 'starting' | 'running' | 'paused' | 'draining' | 'stopping' | 'stopped' | 'failed' | 'unavailable';
export type FFmpegCapability = 'availability_detection' | 'command_preview' | 'dry_run' | 'test_source_input' | 'raw_pipe_input' | 'file_output' | 'null_output' | 'rtmp_plan' | 'segment_plan' | 'redacted_diagnostics';
export interface FFmpegInputSpec { readonly kind: PlaceholderInput; readonly label: string; readonly pipeIndex?: number; readonly durationSeconds?: number; }
export interface FFmpegOutputSpec { readonly kind: PlaceholderOutput; readonly url: string; readonly format: string; readonly planOnly: boolean; }
export interface FFmpegCommandPlan { readonly id: string; readonly encoderPlanId: string; readonly ffmpegPath: string; readonly input: FFmpegInputSpec; readonly output: FFmpegOutputSpec; readonly args: readonly string[]; readonly sanitizedArgs: readonly string[]; readonly redactedPreview: string; readonly dryRun: boolean; readonly commandPreviewOnly: boolean; readonly createdAt: string; readonly warnings: readonly string[]; }
export interface FFmpegRuntimeError { readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly stderrSummary?: string; }
export interface FFmpegLogEvent { readonly timestamp: string; readonly level: 'debug' | 'info' | 'warning' | 'error'; readonly source: 'stdout' | 'stderr' | 'lifecycle'; readonly message: string; readonly redacted: true; }
export interface FFmpegHealth { readonly available: boolean; readonly enabled: boolean; readonly version?: string; readonly processState: FFmpegProcessState; readonly capability: readonly FFmpegCapability[]; readonly latestCommandPreview?: string; readonly latestInputKind?: PlaceholderInput; readonly latestOutputKind?: PlaceholderOutput; readonly latestLogSummary?: string; readonly latestError?: FFmpegRuntimeError; readonly checkedAt: string; }
export interface FFmpegAvailability { readonly available: boolean; readonly ffmpegPath: string; readonly version?: string; readonly error?: string; }
export interface FFmpegEncoderBackendOptions { readonly enabled?: boolean; readonly ffmpegPath?: string; readonly runtimeMode?: RuntimeMode; readonly dryRun?: boolean; readonly commandPreviewOnly?: boolean; readonly spawnEnabled?: boolean; }
export interface FFmpegEncoderSession extends EncoderSession { readonly ffmpeg: FFmpegHealth; }
const now = () => new Date().toISOString();
const secretPatterns = [/([?&](?:key|token|secret|password)=)[^&\s]+/gi, /(rtmps?:\/\/[^/:\s]+:)([^@\s]+)(@)/gi, /(stream[_-]?key[=:])[^\s&]+/gi];
export function redactFFmpegSecret(value: string) { return secretPatterns.reduce((text, pattern) => text.replace(pattern, '$1<redacted>$3'), value); }
export function sanitizeFFmpegArgs(args: readonly string[]) { return args.map((arg) => { if (/\0|[\n\r]|[`$;&|<>]/.test(arg)) throw new Error(`Unsafe FFmpeg argument rejected: ${redactFFmpegSecret(arg)}`); if (arg === '..' || arg.includes('/../') || arg.includes('\\..\\')) throw new Error('Unsafe FFmpeg path traversal rejected'); return arg; }); }
function safeOutputForPlan(plan: EncoderPlan): FFmpegOutputSpec { const url = String(plan.target.metadata.outputUrl ?? plan.target.metadata.url ?? 'pipe:null'); if (plan.target.kind === 'streaming' || plan.streamId) return { kind: 'rtmp', url: url.startsWith('rtmp') ? url : 'rtmp://example.invalid/live/<stream-key>', format: 'flv', planOnly: true }; if (plan.target.kind === 'recording' || plan.recordingId) return { kind: 'segment', url: String(plan.target.metadata.outputPath ?? 'ubos-recording-%03d.ts'), format: 'segment', planOnly: true }; if (url === 'pipe:null' || plan.target.kind === 'monitor') return { kind: 'null', url: '-', format: 'null', planOnly: false }; return { kind: 'file', url: url === 'pipe:null' ? 'ubos-preview.mp4' : url, format: 'mp4', planOnly: false }; }
export function buildFFmpegArgs(commandPlan: Omit<FFmpegCommandPlan, 'args' | 'sanitizedArgs' | 'redactedPreview'>) { const r = commandPlan.input.kind === 'test_source' ? commandPlan.input.durationSeconds ?? 1 : undefined; const args = ['-hide_banner', '-nostdin', ...(r ? ['-f', 'lavfi', '-t', String(r), '-i', `testsrc2=size=1280x720:rate=30`] : ['-f', 'rawvideo', '-pix_fmt', 'rgba', '-s', '1280x720', '-i', `pipe:${commandPlan.input.pipeIndex ?? 0}`]), '-an', '-c:v', 'libx264', '-preset', 'veryfast']; const out = commandPlan.output; if (out.kind === 'null') args.push('-f', 'null', '-'); else if (out.kind === 'rtmp') args.push('-f', 'flv', out.url); else if (out.kind === 'segment') args.push('-f', 'segment', '-segment_time', '6', out.url); else args.push('-f', out.format, out.url); return sanitizeFFmpegArgs(args); }
export function createFFmpegCommandPlan(plan: EncoderPlan, options: FFmpegEncoderBackendOptions = {}): FFmpegCommandPlan { if ((options.runtimeMode ?? 'dry_run') === 'disabled') throw new Error('FFmpeg adapter disabled; command plan not created'); const base = { id: `ffmpeg-command:${plan.id}`, encoderPlanId: plan.id, ffmpegPath: options.ffmpegPath ?? process?.env?.UBOS_FFMPEG_PATH ?? 'ffmpeg', input: { kind: (plan.target.metadata.inputKind as PlaceholderInput | undefined) ?? 'test_source', label: 'UBOS safe placeholder input', durationSeconds: 1 } satisfies FFmpegInputSpec, output: safeOutputForPlan(plan), dryRun: options.dryRun ?? true, commandPreviewOnly: options.commandPreviewOnly ?? false, createdAt: now(), warnings: ['FFmpeg command is placeholder-only; no production recording or streaming is active'] };
  const args = buildFFmpegArgs(base); const redactedPreview = [base.ffmpegPath, ...args].map(redactFFmpegSecret).join(' '); return { ...base, args, sanitizedArgs: args, redactedPreview }; }
export function validateFFmpegCommandPlan(commandPlan: FFmpegCommandPlan) { const errors: string[] = []; const warnings = [...commandPlan.warnings]; try { sanitizeFFmpegArgs([commandPlan.ffmpegPath, ...commandPlan.args]); } catch (error) { errors.push(error instanceof Error ? error.message : String(error)); } if (commandPlan.output.planOnly) warnings.push(`${commandPlan.output.kind} output is plan-only in Phase 8.4`); return { valid: errors.length === 0, warnings, errors }; }
export function mapEncoderPlanToFFmpegCommand(plan: EncoderPlan, options?: FFmpegEncoderBackendOptions) { return createFFmpegCommandPlan(plan, options); }
export function parseFFmpegVersion(output: string) { return output.match(/ffmpeg version\s+([^\s]+)/i)?.[1]; }
export async function detectFFmpegAvailability(ffmpegPath = process?.env?.UBOS_FFMPEG_PATH ?? 'ffmpeg'): Promise<FFmpegAvailability> { if (!process?.versions?.node) return { available: false, ffmpegPath, error: 'Node runtime unavailable' }; try { const child = await (Function('return import(\"node:child_process\")')() as Promise<{ spawn: (...args: unknown[]) => { stdout: { on: (event: string, cb: (d: unknown) => void) => void }; stderr: { on: (event: string, cb: (d: unknown) => void) => void }; on: (event: string, cb: (...args: unknown[]) => void) => void } }>); return await new Promise<FFmpegAvailability>((resolve) => { const proc = child.spawn(ffmpegPath, ['-version'], { stdio: ['ignore', 'pipe', 'pipe'], shell: false }); let out = ''; let err = ''; const done = (available: boolean, error?: string) => { const version = parseFFmpegVersion(out || err); resolve({ available, ffmpegPath, ...(version ? { version } : {}), ...(error ? { error } : {}) }); }; proc.stdout.on('data', (d: unknown) => { out += String(d); }); proc.stderr.on('data', (d: unknown) => { err += String(d); }); proc.on('error', (e: unknown) => done(false, e instanceof Error ? e.message : String(e))); proc.on('close', (code: unknown) => done(code === 0, code === 0 ? undefined : `ffmpeg -version exited ${String(code)}`)); }); } catch (error) { return { available: false, ffmpegPath, error: error instanceof Error ? error.message : String(error) }; } }
export function createFFmpegLogEvent(input: { level?: FFmpegLogEvent['level']; source?: FFmpegLogEvent['source']; message: string }): FFmpegLogEvent { return { timestamp: now(), level: input.level ?? 'info', source: input.source ?? 'lifecycle', message: redactFFmpegSecret(input.message).slice(0, 1000), redacted: true }; }
export function mapFFmpegErrorToFailure(error: FFmpegRuntimeError): EncoderFailure { return { code: error.code, message: error.message, retryable: error.retryable, occurredAt: error.occurredAt, backend: 'ffmpeg' }; }
export function createFFmpegHealth(input: Partial<FFmpegHealth> = {}): FFmpegHealth { return { available: false, enabled: false, processState: 'idle', capability: ['availability_detection','command_preview','dry_run','redacted_diagnostics'], checkedAt: now(), ...input }; }
export function summarizeFFmpegHealth(health: FFmpegHealth) { return `${health.enabled ? 'enabled' : 'disabled'}/${health.available ? 'available' : 'unavailable'}/${health.processState}${health.version ? ` ffmpeg ${health.version}` : ''}`; }
function makeSession(plan: EncoderPlan, status: EncoderStatus, health: FFmpegHealth, extra: Partial<EncoderSession> = {}): FFmpegEncoderSession { const load = estimateEncoderLoad(plan); return { id: `ffmpeg-session:${plan.id}`, planId: plan.id, status, health: status === 'unavailable' ? 'unavailable' : status === 'failed' ? 'critical' : 'healthy' as CoreEncoderHealth, backend: 'ffmpeg', updatedAt: now(), estimatedBitrateKbps: plan.profile.bitrate.targetKbps, estimatedFps: plan.profile.resolution.fps, estimatedLatencyMs: load.estimatedLatencyMs, warnings: [], failures: [], ...extra, ffmpeg: health }; }
export class FFmpegEncoderBackend { private state: FFmpegProcessState = 'idle'; private latestPlan?: FFmpegCommandPlan; private latestError?: FFmpegRuntimeError; private logs: FFmpegLogEvent[] = []; constructor(private readonly options: FFmpegEncoderBackendOptions = {}) {}
  get enabled() { return this.options.enabled ?? process?.env?.UBOS_ENABLE_FFMPEG_ADAPTER === 'true'; }
  get runtimeMode(): RuntimeMode { return this.options.runtimeMode ?? 'dry_run'; }
  validate(plan: EncoderPlan) { const core = validateEncoderPlan({ ...plan, backend: 'ffmpeg' }); if (!this.enabled || this.runtimeMode === 'disabled' || this.runtimeMode === 'mock_live') return { valid: false, warnings: core.warnings, errors: ['FFmpeg adapter is disabled or bypassed by runtime mode'] }; const command = createFFmpegCommandPlan(plan, this.options); const ff = validateFFmpegCommandPlan(command); return { valid: core.valid && ff.valid, warnings: [...core.warnings, ...ff.warnings], errors: [...core.errors, ...ff.errors] }; }
  async prepare(plan: EncoderPlan) { if (!this.enabled || this.runtimeMode === 'disabled') { this.state = 'disabled'; return { success: false, session: makeSession(plan, 'unavailable', this.health({ enabled: false, processState: 'disabled' })), warnings: [], errors: ['FFmpeg adapter disabled'] }; } this.latestPlan = createFFmpegCommandPlan(plan, { ...this.options, dryRun: this.runtimeMode !== 'live_ready' || (this.options.dryRun ?? true) }); this.state = 'ready'; return { success: true, session: makeSession(plan, 'ready', this.health({ processState: 'ready' })), warnings: this.latestPlan.warnings, errors: [] }; }
  async start(session: FFmpegEncoderSession) { if (this.runtimeMode !== 'live_ready' || this.latestPlan?.dryRun || !this.options.spawnEnabled) return { success: true, session: { ...session, status: 'encoding' as const, startedAt: session.startedAt ?? now(), updatedAt: now(), ffmpeg: this.health({ processState: 'running' }) }, warnings: ['FFmpeg dry-run/preview start did not spawn a process'], errors: [] }; const err = { code: 'FFMPEG_SPAWN_NOT_ENABLED', message: 'Safe spawn hook is reserved for future production wiring', retryable: true, occurredAt: now() }; this.latestError = err; return { success: false, session: makeSession({ ...session, id: session.planId } as never, 'failed', this.health({ processState: 'failed', latestError: err }), { failures: [mapFFmpegErrorToFailure(err)] }), warnings: [], errors: [err.message] }; }
  pause(session: FFmpegEncoderSession) { return { success: true, session: { ...session, status: 'paused' as const, updatedAt: now(), ffmpeg: this.health({ processState: 'paused' }) }, warnings: ['FFmpeg pause is placeholder-only'], errors: [] }; }
  resume(session: FFmpegEncoderSession) { return { success: true, session: { ...session, status: 'encoding' as const, updatedAt: now(), ffmpeg: this.health({ processState: 'running' }) }, warnings: ['FFmpeg resume is placeholder-only'], errors: [] }; }
  drain(session: FFmpegEncoderSession) { return { success: true, session: { ...session, status: 'draining' as const, updatedAt: now(), ffmpeg: this.health({ processState: 'draining' }) }, warnings: ['FFmpeg drain is placeholder-only'], errors: [] }; }
  stop(session: FFmpegEncoderSession) { this.state = 'stopped'; return { success: true, session: { ...session, status: 'stopped' as const, stoppedAt: now(), updatedAt: now(), ffmpeg: this.health({ processState: 'stopped' }) }, warnings: [], errors: [] }; }
  fail(session: FFmpegEncoderSession, error: FFmpegRuntimeError) { this.latestError = error; return { success: false, session: { ...session, status: 'failed' as const, health: 'critical' as const, failures: [...session.failures, mapFFmpegErrorToFailure(error)], updatedAt: now(), ffmpeg: this.health({ processState: 'failed', latestError: error }) }, warnings: [], errors: [error.message] }; }
  cleanup() { this.state = 'stopped'; this.logs.push(createFFmpegLogEvent({ message: 'FFmpeg cleanup completed without retained process handles' })); }
  health(extra: Partial<FFmpegHealth> = {}) { const latestLog = this.logs.at(-1)?.message; return createFFmpegHealth({ enabled: this.enabled, available: this.enabled, processState: this.state, ...(this.latestPlan ? { latestCommandPreview: this.latestPlan.redactedPreview, latestInputKind: this.latestPlan.input.kind, latestOutputKind: this.latestPlan.output.kind } : {}), ...(latestLog ? { latestLogSummary: latestLog } : {}), ...(this.latestError ? { latestError: this.latestError } : {}), ...extra }); }
}
