export type ProductionState = 'idle' | 'ready' | 'live' | 'warning' | 'error' | 'completed' | 'offline';
export type ReadinessState = 'ready' | 'warning' | 'blocked' | 'unknown';
export interface DirectorProductionMetadata { productionId:string; title:string; environment:'rehearsal'|'live'|'simulation'; state:ProductionState; scheduledStart:string; scheduledEnd:string; currentTimeLabel:string; expectedEndLabel:string; elapsedLabel:string; overrunLabel?:string; currentRundownItemId:string; nextRundownItemId?:string; activeAlertCount:number; overallReadiness:ReadinessState }
export interface DirectorRundownItemMetadata { id:string; order:number; title:string; type:'countdown'|'scene'|'segment'|'guest'|'graphics'|'replay'|'sponsor'|'break'|'closing'; status:'completed'|'current'|'next'|'upcoming'|'skipped'|'blocked'; scheduledStartLabel:string; expectedDurationLabel:string; elapsedLabel?:string; remainingLabel?:string; presenter?:string; sceneId?:string; readiness:ReadinessState; graphicsState:ProductionState; audioState:ProductionState; guestState:ProductionState; destinationState:ProductionState; automationState:ProductionState; notes?:string }
export interface DirectorTimelineItemMetadata { id:string; rundownItemId:string; label:string; startLabel:string; durationLabel:string; status:'completed'|'current'|'upcoming'|'delayed'|'overrun'; relativePosition:number; relativeWidth:number }
export interface BroadcastHealthMetadata { cpuPercent:number; memoryPercent:number; encoderState:ProductionState; droppedFrames:number; networkState:ProductionState; networkLabel:string; audioState:ProductionState; recordingState:ProductionState; streamingState:ProductionState; destinationHealthyCount:number; destinationTotalCount:number }
export interface DirectorGuestMetadata { id:string; name:string; role:string; location?:string; status:'ready'|'waiting'|'muted'|'warning'|'offline'; cameraState:ProductionState; microphoneState:ProductionState; connectionState:ProductionState; connectionLabel:string; sceneAssignment?:string; note?:string }
export interface DirectorOperatorMetadata { id:string; name:string; role:'director'|'technical-director'|'audio'|'graphics'|'replay'|'streaming'|'moderator'; status:'ready'|'busy'|'warning'|'offline'; currentTask?:string }
export interface DirectorIntelligenceItemMetadata { id:string; severity:'info'|'warning'|'critical'; category:'timing'|'graphics'|'guest'|'audio'|'destination'|'recording'|'automation'|'scene'; title:string; message:string; recommendedAction?:string; relatedRundownItemId?:string }
export interface DirectorEmergencyActionMetadata { id:string; label:string; description:string; severity:'safe'|'warning'|'critical'; confirmationRequired:boolean; enabled:boolean; presentationOnly:true }
export const DIRECTOR_NOTES_STORAGE_KEY = 'ubos.director-workspace.notes.v5.13.0';
export const directorProduction: DirectorProductionMetadata = { productionId:'ubos-launch-day', title:'UBOS Launch Day', environment:'live', state:'warning', scheduledStart:'12:00 UTC', scheduledEnd:'13:00 UTC', currentTimeLabel:'12:24 UTC', expectedEndLabel:'13:02 UTC', elapsedLabel:'00:24:10', overrunLabel:'+00:02', currentRundownItemId:'host-welcome', nextRundownItemId:'product-overview', activeAlertCount:5, overallReadiness:'warning' };
const item = (id:string, order:number, title:string, type:DirectorRundownItemMetadata['type'], status:DirectorRundownItemMetadata['status'], time:string, duration:string, readiness:ReadinessState, extra:Partial<DirectorRundownItemMetadata> = {}):DirectorRundownItemMetadata => ({id,order,title,type,status,scheduledStartLabel:time,expectedDurationLabel:duration,presenter:'Production',readiness,graphicsState:'ready',audioState:'ready',guestState:'ready',destinationState:'ready',automationState:'warning',...extra});
export const directorRundown = [item('countdown',1,'Countdown','countdown','completed','12:00','02:00','ready'),item('opening',2,'Opening Sequence','scene','completed','12:02','01:30','ready'),item('host-welcome',3,'Host Welcome','segment','current','12:03','04:00','ready',{presenter:'Maya Chen',elapsedLabel:'03:10',remainingLabel:'00:50',automationState:'warning'}),item('product-overview',4,'Product Overview','segment','next','12:07','06:00','warning',{presenter:'Maya Chen',graphicsState:'warning',notes:'Lower-third package is not armed.'}),item('guest-interview',5,'Guest Interview','guest','upcoming','12:13','10:00','warning',{presenter:'Maya Chen + Jordan',guestState:'warning'}),item('platform-demo',6,'Platform Demonstration','scene','upcoming','12:23','12:00','ready',{presenter:'Alex Rivera'}),item('sponsor',7,'Sponsor Message','sponsor','upcoming','12:35','01:00','ready'),item('questions',8,'Audience Questions','segment','upcoming','12:36','10:00','warning',{destinationState:'warning'}),item('closing',9,'Closing Remarks','closing','upcoming','12:46','05:00','ready'),item('credits',10,'End Credits','closing','upcoming','12:51','02:00','ready') ] as const;
export const directorTimeline: readonly DirectorTimelineItemMetadata[] = directorRundown.map((r,index)=>({id:`timeline-${r.id}`,rundownItemId:r.id,label:r.title,startLabel:r.scheduledStartLabel,durationLabel:r.expectedDurationLabel,status:r.status === 'completed' ? 'completed' : r.status === 'current' ? 'overrun' : r.status === 'next' ? 'delayed' : 'upcoming',relativePosition:index*10,relativeWidth:9}));
export const broadcastHealth:BroadcastHealthMetadata={cpuPercent:42,memoryPercent:58,encoderState:'ready',droppedFrames:0,networkState:'warning',networkLabel:'TikTok degraded',audioState:'ready',recordingState:'idle',streamingState:'live',destinationHealthyCount:4,destinationTotalCount:5};
export const directorGuests:readonly DirectorGuestMetadata[]=[{id:'maya',name:'Maya Chen',role:'Host',location:'Studio A',status:'ready',cameraState:'live',microphoneState:'live',connectionState:'ready',connectionLabel:'Wired · 24 Mbps',sceneAssignment:'Host Welcome'},{id:'jordan',name:'Jordan Lee',role:'Guest B',location:'Remote',status:'warning',cameraState:'ready',microphoneState:'warning',connectionState:'warning',connectionLabel:'Unstable · 3 Mbps',sceneAssignment:'Guest Interview',note:'Confirm audio before transition.'}];
export const directorOperators:readonly DirectorOperatorMetadata[]=[{id:'d',name:'Avery Stone',role:'director',status:'busy',currentTask:'Calling Host Welcome'},{id:'td',name:'Sam Patel',role:'technical-director',status:'ready',currentTask:'Preview staged'},{id:'a',name:'Morgan Bell',role:'audio',status:'ready',currentTask:'Program mix healthy'},{id:'g',name:'Riley Kim',role:'graphics',status:'warning',currentTask:'Product lower third missing'},{id:'r',name:'Casey Wu',role:'replay',status:'ready',currentTask:'Standby'},{id:'s',name:'Taylor Brooks',role:'streaming',status:'warning',currentTask:'TikTok degraded'},{id:'m',name:'Drew Fox',role:'moderator',status:'ready',currentTask:'Questions queue'}];
export const directorIntelligence:readonly DirectorIntelligenceItemMetadata[]=[{id:'recording',severity:'critical',category:'recording',title:'Recording has not started',message:'Recording is armed but not started.',recommendedAction:'Confirm recording before audience questions.'},{id:'graphics',severity:'warning',category:'graphics',title:'Graphics package missing',message:'Product Overview lower third is not armed.',recommendedAction:'Confirm graphics with operator.',relatedRundownItemId:'product-overview'},{id:'guest',severity:'warning',category:'guest',title:'Guest B network unstable',message:'Remote connection is below preferred quality.',recommendedAction:'Hold current scene and confirm guest audio.',relatedRundownItemId:'guest-interview'},{id:'destination',severity:'warning',category:'destination',title:'TikTok destination degraded',message:'Four of five destinations are healthy.',recommendedAction:'Monitor distribution operator.'},{id:'automation',severity:'info',category:'automation',title:'Automation is paused',message:'Cues require a director call.',recommendedAction:'Resume only when ready.'}];
export const emergencyActions:readonly DirectorEmergencyActionMetadata[]=[{id:'fade',label:'Fade to Black',description:'Simulated safety transition',severity:'critical',confirmationRequired:true,enabled:true,presentationOnly:true},{id:'slate',label:'Emergency Slate',description:'Simulated emergency slate',severity:'critical',confirmationRequired:true,enabled:true,presentationOnly:true},{id:'safe',label:'Safe Scene',description:'Simulated safe scene',severity:'warning',confirmationRequired:true,enabled:true,presentationOnly:true},{id:'pause',label:'Pause Automation',description:'Automation remains presentation only',severity:'warning',confirmationRequired:true,enabled:true,presentationOnly:true},{id:'stop',label:'Stop Recording',description:'Recording runtime is not connected',severity:'critical',confirmationRequired:true,enabled:true,presentationOnly:true},{id:'credits',label:'Roll Credits',description:'Simulated credits cue',severity:'safe',confirmationRequired:true,enabled:true,presentationOnly:true}];
export const demoDirectorNotes = 'Roll intro after countdown.\nMention sponsor before demonstration.\nDisplay lower third before Guest A.\nSwitch to split layout during demonstration.\nConfirm recording before audience questions.';
