'use client';
import { useState, type ReactNode } from 'react';
import { DIRECTOR_NOTES_STORAGE_KEY, broadcastHealth, demoDirectorNotes, directorGuests, directorIntelligence, directorOperators, directorProduction, directorRundown, directorTimeline, emergencyActions, type DirectorRundownItemMetadata } from './director-metadata';
import './director-workspace.css';

type Controls={cutToProgram:()=>void;autoTransition:()=>void;takePreview:()=>void;pending:boolean;programName:string;previewName:string};
const tone=(value:string | undefined)=>{ const state=value ?? ''; return state === 'warning'||state==='blocked'||state==='error'||state==='offline'?'warning':state==='live'||state==='current'?'live':state==='ready'||state==='next'?'ready':'neutral'; };
function Panel({title,summary,children}:{title:string;summary?:string;children:ReactNode}){return <section className="director-panel"><header><strong>{title}</strong><small>{summary}</small></header>{children}</section>}
export function DirectorRundownItem({item,selected,onSelect}:{item:DirectorRundownItemMetadata;selected:boolean;onSelect:()=>void}){return <button className={`director-rundown-item is-${item.status} ${selected?'is-selected':''}`} onClick={onSelect}><span className="director-order">{item.order}</span><span className="director-rundown-copy"><b>{item.status==='current'?'LIVE · ':item.status==='next'?'NEXT · ':''}{item.title}</b><small>{item.scheduledStartLabel} · {item.expectedDurationLabel} · {item.presenter}</small><i>Ready: {item.readiness} · GFX: {item.graphicsState} · Audio: {item.audioState} · Guest: {item.guestState} · Dest: {item.destinationState} · Auto: {item.automationState}</i></span>{item.remainingLabel&&<em>{item.elapsedLabel} / {item.remainingLabel}</em>}</button>}
export function DirectorRundown({selectedId,onSelect}:{selectedId:string;onSelect:(id:string)=>void}){return <Panel title="Production Rundown" summary="10 items · metadata only"><div className="director-rundown">{directorRundown.map(item=><DirectorRundownItem key={item.id} item={item} selected={selectedId===item.id} onSelect={()=>onSelect(item.id)}/>)}</div></Panel>}
export function DirectorTimeline(){return <Panel title="Production Timeline" summary={`${directorProduction.elapsedLabel} elapsed · expected ${directorProduction.expectedEndLabel}`}><div className="director-timeline">{directorTimeline.map(item=><div key={item.id} className={`timeline-item is-${item.status}`} style={{left:`${item.relativePosition}%`,width:`${item.relativeWidth}%`}} title={`${item.label} · ${item.startLabel} · ${item.durationLabel}`}><span>{item.label}</span></div>)}</div><small className="director-caption">Static schedule · +00:02 current overrun · no live clock source connected</small></Panel>}
export function NextActionPanel(){const next=directorRundown.find(x=>x.status==='next')!;return <Panel title="NEXT ACTION" summary="Director decision"><div className="next-action"><b>{next.title}</b><span>Transition: AUTO · Ready in: 00:50</span><strong>Warning: graphics package missing</strong><p>Hold current scene and confirm graphics and guest audio.</p><button>Review checklist</button></div></Panel>}
export function DirectorStatusCenter(){const entries=[['Program','LIVE · Host Welcome'],['Preview','READY · Product Overview'],['Recording','ARMED · not started'],['Streaming','LIVE · 4/5 destinations'],['Audio','HEALTHY · program mix'],['Graphics','WARNING · package missing'],['Guests','WARNING · Guest B unstable'],['Automation','PAUSED · director call'],['Network','WARNING · TikTok degraded']] as const;return <Panel title="Production Status" summary="9 summaries"><div className="status-grid">{entries.map(([label,value])=><div key={label}><b>{label}</b><span className={`state-${tone(value.toLowerCase())}`}>{value}</span></div>)}</div></Panel>}
export function BroadcastHealthDashboard(){return <Panel title="Broadcast Health" summary="No live telemetry"><div className="health-list"><span>CPU <i style={{width:`${broadcastHealth.cpuPercent}%`}}/> {broadcastHealth.cpuPercent}%</span><span>Memory <i style={{width:`${broadcastHealth.memoryPercent}%`}}/> {broadcastHealth.memoryPercent}%</span><span>Encoder <b>Ready</b> · Dropped frames <b>0</b></span><span>Network <b>Warning</b> · {broadcastHealth.networkLabel}</span><span>Destinations <b>4 / 5 healthy</b> · Audio <b>Healthy</b></span></div></Panel>}
export function GuestOperationCard({guest}:{guest:(typeof directorGuests)[number]}){return <article className="guest-card"><b>{guest.name} <small>{guest.role}</small></b><span className={`state-${tone(guest.status)}`}>{guest.status} · {guest.connectionLabel}</span><p>Camera {guest.cameraState} · Mic {guest.microphoneState} · {guest.sceneAssignment}</p><small>{guest.note??'Waiting room cleared.'}</small><div>{['Invite','Admit','Mute','Remove','Spotlight','Move to Preview'].map(action=><button key={action} disabled title="Presentation-only control">{action}</button>)}</div></article>}
export function GuestOperationsPanel(){return <Panel title="Guest Operations" summary="2 guests"><div className="guest-list">{directorGuests.map(guest=><GuestOperationCard key={guest.id} guest={guest}/>)}</div></Panel>}
export function AIProductionAssistant(){return <Panel title="AI Production Assistant" summary="Advisory · no AI execution"><ul className="advisory-list">{directorIntelligence.slice(1).map(item=><li key={item.id} className={`is-${item.severity}`}><b>{item.title}</b><span>{item.message}</span><small>Recommended: {item.recommendedAction}</small></li>)}</ul></Panel>}
export function SceneFlowPanel(){return <Panel title="Scene Flow" summary="Metadata only"><ol className="scene-flow">{['Intro','Host','Interview','Demo','Questions','Closing'].map((name,index)=><li key={name} className={index<2?'done':index===2?'next':index===3?'warning':''}>{name}</li>)}</ol></Panel>}
export function OperatorStatusBoard(){return <Panel title="Operators" summary="7 assigned"><ul className="operator-list">{directorOperators.map(o=><li key={o.id}><span className={`state-${tone(o.status)}`}/><b>{o.name}</b><small>{o.role} · {o.currentTask}</small></li>)}</ul></Panel>}
export function ProductionClockPanel(){return <Panel title="Production Clock" summary="Static labels"><div className="clock-grid"><span>Show elapsed<b>00:24:10</b></span><span>Segment elapsed<b>03:10</b></span><span>Remaining<b>00:50</b></span><span>Next item<b>00:50</b></span><span>Expected end<b>13:02 UTC</b></span><span>Overrun<b>+00:02</b></span></div></Panel>}
export function WorkspaceIntelligencePanel(){return <Panel title="Attention Queue" summary="5 items"><ul className="advisory-list">{directorIntelligence.map(item=><li key={item.id} className={`is-${item.severity}`}><b>{item.title}</b><span>{item.message}</span></li>)}</ul></Panel>}
export function EmergencyControlsPanel(){const [confirm,setConfirm]=useState<string>();return <Panel title="Emergency Controls" summary="Simulation only"><div className="emergency">{emergencyActions.map(action=><button key={action.id} className={`is-${action.severity}`} onClick={()=>setConfirm(action.label)}>{action.label}</button>)}</div>{confirm&&<p className="confirm">Confirm {confirm}? This is presentation-only. <button onClick={()=>setConfirm(undefined)}>Dismiss</button></p>}</Panel>}
export function DirectorNotesPanel(){const [notes,setNotes]=useState(()=>typeof window==='undefined'?demoDirectorNotes:window.localStorage.getItem(DIRECTOR_NOTES_STORAGE_KEY)??demoDirectorNotes);const save=(value:string)=>{setNotes(value);window.localStorage.setItem(DIRECTOR_NOTES_STORAGE_KEY,value)};return <div className="notes"><textarea value={notes} onChange={e=>save(e.target.value)} aria-label="Director Notes"/><div><span>Saved locally · static presentation label</span><button onClick={()=>{if(window.confirm('Clear Director Notes?')) save('')}}>Clear notes</button><button onClick={()=>save(demoDirectorNotes)}>Reset demo notes</button></div></div>}
export function DirectorBottomWorkbench({selectedId,onSelect}:{selectedId:string;onSelect:(id:string)=>void}){const [tab,setTab]=useState('Rundown');const tabs=['Rundown','Notes','Audio Summary','Automation','Logs'];return <section className="director-workbench"><div role="tablist">{tabs.map(t=><button role="tab" key={t} aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}<span/><button title="Collapse workbench">−</button><button title="Maximize workbench">□</button></div><header><b>{tab}</b><small>{tab==='Notes'?'Local-only production notes':`${directorProduction.title} operational detail`}</small></header>{tab==='Rundown'?<DirectorRundown selectedId={selectedId} onSelect={onSelect}/>:tab==='Notes'?<DirectorNotesPanel/>:<p className="workbench-copy">{tab==='Audio Summary'?'Program mix healthy · no clipping · Guest B microphone requires confirmation.':tab==='Automation'?'Automation paused · current cue requires director call.':'12:24:10 Director called Host Welcome · 12:23:58 Graphics warning acknowledged.'}</p>}</section>}
function Monitor({kind,name,detail}:{kind:'PROGRAM'|'PREVIEW';name:string;detail:string}){return <section className={`director-monitor ${kind==='PROGRAM'?'program':'preview'}`} data-monitor={kind.toLowerCase()} data-testid={kind==='PROGRAM'?'program-monitor':'preview-monitor'}><div className="monitor-overlay"><b>{kind==='PROGRAM'?'LIVE':'NEXT'} · {name}</b><span>{detail}</span></div><div className="monitor-slate"><strong>{kind}</strong><span>Stable monitor ownership boundary</span></div></section>}
export function DirectorCommandCenter({controls}:{controls:Controls}){const [selectedId,setSelectedId]=useState(directorProduction.currentRundownItemId);return <div className="director-command-center"><aside className="director-left"><DirectorRundown selectedId={selectedId} onSelect={setSelectedId}/><DirectorTimeline/><SceneFlowPanel/></aside><main data-testid="workspace-main-stage" className="director-stage"><div className="director-controls"><button onClick={controls.cutToProgram} disabled={controls.pending}>CUT</button><button onClick={controls.autoTransition} disabled={controls.pending}>AUTO</button><button onClick={controls.takePreview} disabled={controls.pending}>TAKE</button><span>Selection: {directorRundown.find(x=>x.id===selectedId)?.title}</span></div><Monitor kind="PROGRAM" name={controls.programName} detail="00:24:10 · 2 participants · Interview layout · 4 destinations · Ready"/><Monitor kind="PREVIEW" name={controls.previewName} detail="AUTO · Ready · 1 blocking issue"/></main><aside className="director-right"><NextActionPanel/><DirectorStatusCenter/><GuestOperationsPanel/><AIProductionAssistant/><OperatorStatusBoard/><ProductionClockPanel/><WorkspaceIntelligencePanel/><BroadcastHealthDashboard/><EmergencyControlsPanel/></aside><DirectorBottomWorkbench selectedId={selectedId} onSelect={setSelectedId}/></div>}
export function DirectorWorkspace(props:Controls){return <DirectorCommandCenter controls={props}/>}
