import type { UbosDockPanelId, UbosWorkspaceModeId } from './ubos-menu-types';
import type { WorkspacePresetId } from '../workspace-canvas/types';
import type { ProfessionalWorkspaceId } from '../workspaces/workspace-types';

export type UbosWorkspaceModeDefinition = {
  id: UbosWorkspaceModeId;
  label: string;
  description: string;
  canvasPresetId: WorkspacePresetId;
  professionalWorkspaceId: ProfessionalWorkspaceId;
  dockVisibility: Partial<Record<UbosDockPanelId, boolean>>;
  zoneCollapsed: { left: boolean; right: boolean; bottom: boolean };
  compactChrome?: boolean;
};

const allDocksVisible: Partial<Record<UbosDockPanelId, boolean>> = {
  scenes: true,
  sources: true,
  'audio-mixer': true,
  'audio-channels': true,
  'scene-transitions': true,
  replay: true,
  media: true,
  graphics: true,
  guests: true,
  inspector: true,
  'pipeline-inspector': false,
  'broadcast-io': true,
  streaming: true,
  recording: true,
  automation: true,
  'monitor-wall': false,
  timeline: true,
  logs: true,
};

export const ubosWorkspaceModes: Record<UbosWorkspaceModeId, UbosWorkspaceModeDefinition> = {
  director: {
    id: 'director',
    label: 'Director',
    description: 'Program-dominant switching with full production controls',
    canvasPresetId: 'technical-director',
    professionalWorkspaceId: 'director',
    dockVisibility: {
      ...allDocksVisible,
      'monitor-wall': false,
      'pipeline-inspector': false,
    },
    zoneCollapsed: { left: false, right: false, bottom: false },
  },
  audio: {
    id: 'audio',
    label: 'Audio',
    description: 'Large mixer and routing console focus',
    canvasPresetId: 'audio-engineer',
    professionalWorkspaceId: 'audio-engineer',
    dockVisibility: {
      scenes: true,
      sources: true,
      'audio-mixer': true,
      'audio-channels': true,
      'scene-transitions': true,
      replay: false,
      media: false,
      graphics: false,
      guests: false,
      inspector: false,
      'pipeline-inspector': false,
      'broadcast-io': true,
      streaming: false,
      recording: false,
      automation: false,
      'monitor-wall': false,
      timeline: false,
      logs: true,
    },
    zoneCollapsed: { left: true, right: false, bottom: false },
  },
  graphics: {
    id: 'graphics',
    label: 'Graphics',
    description: 'Layer stack, overlays, and lower thirds',
    canvasPresetId: 'graphics-operator',
    professionalWorkspaceId: 'graphics-operator',
    dockVisibility: {
      scenes: true,
      sources: false,
      'audio-mixer': false,
      'audio-channels': false,
      'scene-transitions': true,
      replay: false,
      media: true,
      graphics: true,
      guests: false,
      inspector: true,
      'pipeline-inspector': false,
      'broadcast-io': false,
      streaming: false,
      recording: false,
      automation: false,
      'monitor-wall': false,
      timeline: true,
      logs: false,
    },
    zoneCollapsed: { left: false, right: false, bottom: false },
  },
  replay: {
    id: 'replay',
    label: 'Replay',
    description: 'Instant replay and clip management',
    canvasPresetId: 'replay-operator',
    professionalWorkspaceId: 'replay',
    dockVisibility: {
      scenes: true,
      sources: false,
      'audio-mixer': true,
      'audio-channels': false,
      'scene-transitions': true,
      replay: true,
      media: true,
      graphics: false,
      guests: false,
      inspector: true,
      'pipeline-inspector': false,
      'broadcast-io': false,
      streaming: false,
      recording: true,
      automation: false,
      'monitor-wall': false,
      timeline: true,
      logs: false,
    },
    zoneCollapsed: { left: false, right: true, bottom: false },
  },
  streaming: {
    id: 'streaming',
    label: 'Streaming',
    description: 'Distribution, encoding, and output health',
    canvasPresetId: 'solo-streamer',
    professionalWorkspaceId: 'distribution-operator',
    dockVisibility: {
      scenes: true,
      sources: true,
      'audio-mixer': true,
      'audio-channels': true,
      'scene-transitions': true,
      replay: false,
      media: true,
      graphics: true,
      guests: true,
      inspector: false,
      'pipeline-inspector': false,
      'broadcast-io': true,
      streaming: true,
      recording: true,
      automation: true,
      'monitor-wall': false,
      timeline: false,
      logs: true,
    },
    zoneCollapsed: { left: true, right: false, bottom: true },
  },
  'monitor-wall': {
    id: 'monitor-wall',
    label: 'Monitor Wall',
    description: 'Multi-feed monitoring and confidence views',
    canvasPresetId: 'producer',
    professionalWorkspaceId: 'producer',
    dockVisibility: {
      scenes: true,
      sources: false,
      'audio-mixer': false,
      'audio-channels': false,
      'scene-transitions': true,
      replay: false,
      media: false,
      graphics: false,
      guests: false,
      inspector: false,
      'pipeline-inspector': false,
      'broadcast-io': false,
      streaming: true,
      recording: false,
      automation: false,
      'monitor-wall': true,
      timeline: false,
      logs: true,
    },
    zoneCollapsed: { left: true, right: false, bottom: true },
  },
  compact: {
    id: 'compact',
    label: 'Compact',
    description: 'Minimal chrome with large program and preview monitors',
    canvasPresetId: 'technical-director',
    professionalWorkspaceId: 'director',
    dockVisibility: {
      scenes: true,
      sources: false,
      'audio-mixer': true,
      'audio-channels': false,
      'scene-transitions': true,
      replay: false,
      media: false,
      graphics: false,
      guests: false,
      inspector: false,
      'pipeline-inspector': false,
      'broadcast-io': false,
      streaming: false,
      recording: false,
      automation: false,
      'monitor-wall': false,
      timeline: false,
      logs: false,
    },
    zoneCollapsed: { left: true, right: true, bottom: true },
    compactChrome: true,
  },
};

export const ubosWorkspaceModeList = Object.values(ubosWorkspaceModes);
