import { AlertSeverity, HealthStatus, redact, type MetricSample } from '../observability/index.js';

export enum ResourceType { CPU='cpu', GPU='gpu', GPUMemory='gpu_memory', Memory='memory', Storage='storage', StorageIO='storage_io', Network='network', Encoder='encoder', Decoder='decoder', Graphics='graphics', Replay='replay', Recording='recording', Streaming='streaming', Workflow='workflow', Automation='automation', License='license', AICompute='ai_compute', OperatorSeat='operator_seat', Custom='custom' }
export enum ResourceState { Available='available', Reserved='reserved', Allocated='allocated', Shared='shared', Maintenance='maintenance', Failed='failed', Offline='offline', Retired='retired' }
export enum CapacityEnforcement { Advisory='advisory', Warning='warning', Block='block', AutomaticOptimization='automatic_optimization' }
export enum TrendDirection { Stable='stable', Increasing='increasing', Decreasing='decreasing', Oscillating='oscillating', Unknown='unknown' }
export enum SaturationState { Normal='normal', Approaching='approaching', Saturated='saturated', Exceeded='exceeded' }

export interface ResourceCapacity { resourceId:string; resourceType:ResourceType; total:number; reserved:number; allocated:number; available:number; utilizationPercent:number; safeLimitPercent:number; warningLimitPercent:number; criticalLimitPercent:number; measuredAt:number; }
export interface ResourceInventoryItem { resourceId:string; resourceType:ResourceType; logicalName:string; physicalId?:string; location?:string; owner?:string; redundancyGroup?:string; assignment?:string; state:ResourceState; maintenanceUntil?:number; metadata?:Record<string,unknown>; capacity:ResourceCapacity; generation:number; }
export interface CapacityLimit { resourceType:ResourceType; maximumUtilizationPercent:number; minimumAvailable?:number; reserveAmount?:number; enforcementMode:CapacityEnforcement; }
export interface CapacityBudget { productionId:string; limits:CapacityLimit[]; createdAt:number; updatedAt:number; }
export interface PerformanceBaseline { id:string; metricName:string; productionType?:string; expectedMinimum:number; expectedAverage:number; expectedMaximum:number; confidence:number; collectedFrom:number; collectedTo:number; }
export interface BaselineProfile { id:string; name:string; productionType:string; baselines:PerformanceBaseline[]; createdAt:number; updatedAt:number; }
export interface CapacityTrend { metricName:string; direction:TrendDirection; slope:number; confidence:number; observedWindowMs:number; }
export interface CapacityForecast { resourceType:ResourceType; predictedUtilization:number; predictedAt:number; confidence:number; assumptions:string[]; }
export interface ResourceReservation { id:string; productionId:string; resourceType:ResourceType; quantity:number; startsAt:number; endsAt:number; createdBy:string; exclusive?:boolean; }
export interface CapacityValidationResult { productionId:string; passed:boolean; blockers:string[]; warnings:string[]; recommendations:string[]; }
export interface OptimizationRecommendation { id:string; title:string; expectedBenefit:string; estimatedImpact:string; implementationRisk:string; automated:boolean; }
export interface CapacityScenario { id:string; productionId:string; resourceDeltas:Partial<Record<ResourceType, number>>; startsAt:number; endsAt:number; assumptions:string[]; }
export interface ComparisonReport { id:string; metricName:string; leftLabel:string; rightLabel:string; delta:number; percentChange:number; summary:string; }
export interface UpgradePlan { id:string; title:string; addedResources:Partial<Record<ResourceType, number>>; estimatedBenefits:string[]; risks:string[]; }
export interface CapacitySnapshot { inventory:ResourceInventoryItem[]; budgets:CapacityBudget[]; reservations:ResourceReservation[]; baselines:PerformanceBaseline[]; trends:CapacityTrend[]; forecasts:CapacityForecast[]; recommendations:OptimizationRecommendation[]; audit:string[]; health:{status:HealthStatus; score:number; reasons:string[]}; }
const clone=<T>(v:T):T=>structuredClone(v);
const freeze=<T>(v:T):T=>Object.freeze(clone(v));
const bounded=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
function assertFinite(n:number,name:string){ if(!Number.isFinite(n)||n<0) throw new Error(`${name} must be a non-negative finite number`); }
export function calculateCapacity(input:Omit<ResourceCapacity,'available'|'utilizationPercent'>):ResourceCapacity{ assertFinite(input.total,'total'); assertFinite(input.reserved,'reserved'); assertFinite(input.allocated,'allocated'); assertFinite(input.safeLimitPercent,'safeLimitPercent'); assertFinite(input.warningLimitPercent,'warningLimitPercent'); assertFinite(input.criticalLimitPercent,'criticalLimitPercent'); const available=Math.max(0,input.total-input.reserved-input.allocated); const utilizationPercent=input.total===0?100:bounded(((input.reserved+input.allocated)/input.total)*100); return {...input,available,utilizationPercent}; }
export function analyzeTrend(metricName:string,samples:MetricSample[]):CapacityTrend{ const points=samples.filter(s=>s.metricName===metricName).sort((a,b)=>a.timestamp-b.timestamp); if(points.length<2) return {metricName,direction:TrendDirection.Unknown,slope:0,confidence:0,observedWindowMs:0}; const first=points[0]!, last=points.at(-1)!; const slope=(last.value-first.value)/Math.max(1,last.timestamp-first.timestamp); const signs=points.slice(1).map((p,i)=>Math.sign(p.value-points[i]!.value)); const flips=signs.slice(1).filter((s,i)=>s!==0&&signs[i]!==0&&s!==signs[i]).length; const direction=flips>points.length/3?TrendDirection.Oscillating:Math.abs(slope)<0.00001?TrendDirection.Stable:slope>0?TrendDirection.Increasing:TrendDirection.Decreasing; return {metricName,direction,slope,confidence:Math.min(1,points.length/10),observedWindowMs:last.timestamp-first.timestamp}; }
export function detectSaturation(capacity:ResourceCapacity, forecast?:CapacityForecast):SaturationState{ const value=Math.max(capacity.utilizationPercent,forecast?.predictedUtilization??0); if(value>=capacity.criticalLimitPercent) return SaturationState.Exceeded; if(value>=capacity.safeLimitPercent) return SaturationState.Saturated; if(value>=capacity.warningLimitPercent) return SaturationState.Approaching; return SaturationState.Normal; }
export class CapacityPlanner { #inventory=new Map<string,ResourceInventoryItem>(); #budgets=new Map<string,CapacityBudget>(); #reservations=new Map<string,ResourceReservation>(); #baselines=new Map<string,PerformanceBaseline>(); #trends=new Map<string,CapacityTrend>(); #forecasts=new Map<ResourceType,CapacityForecast>(); #recommendations=new Map<string,OptimizationRecommendation>(); #audit:string[]=[]; constructor(private readonly maxAudit=10000){}
  registerResource(input:Omit<ResourceInventoryItem,'capacity'> & {capacity:Omit<ResourceCapacity,'available'|'utilizationPercent'>}):ResourceInventoryItem{ const existing=this.#inventory.get(input.resourceId); if(existing&&input.generation<=existing.generation) throw new Error(`stale resource generation: ${input.resourceId}`); const item={...input,metadata:redact(input.metadata??{}) as Record<string,unknown>,capacity:calculateCapacity(input.capacity)}; this.#inventory.set(item.resourceId,freeze(item)); this.#audit.push(`resource.registered:${item.resourceId}:${item.generation}`); return clone(item); }
  defineBudget(budget:CapacityBudget):void{ this.#budgets.set(budget.productionId,freeze({...budget,limits:[...budget.limits].sort((a,b)=>a.resourceType.localeCompare(b.resourceType))})); this.#audit.push(`budget.defined:${budget.productionId}`); }
  reserve(reservation:ResourceReservation):ResourceReservation{ if(reservation.endsAt<=reservation.startsAt) throw new Error('reservation end must be after start'); assertFinite(reservation.quantity,'quantity'); const overlap=[...this.#reservations.values()].filter(r=>r.resourceType===reservation.resourceType&&r.endsAt>reservation.startsAt&&r.startsAt<reservation.endsAt); const committed=overlap.reduce((a,r)=>a+r.quantity,0)+reservation.quantity; const available=this.#totalFor(reservation.resourceType)-this.#maintenanceFor(reservation.resourceType); if(committed>available) throw new Error(`reservation oversubscription: ${reservation.resourceType}`); if(reservation.exclusive&&overlap.some(r=>r.exclusive)) throw new Error(`exclusive reservation conflict: ${reservation.resourceType}`); this.#reservations.set(reservation.id,freeze({...reservation,createdBy:String(redact(reservation.createdBy))})); this.#audit.push(`reservation.created:${reservation.id}`); return clone(reservation); }
  establishBaseline(baseline:PerformanceBaseline):void{ if(baseline.collectedTo<=baseline.collectedFrom) throw new Error('baseline collection window is invalid'); this.#baselines.set(baseline.id,freeze({...baseline,confidence:bounded(baseline.confidence,0,1)})); this.#audit.push(`baseline.established:${baseline.id}`); }
  updateTrend(trend:CapacityTrend):void{ this.#trends.set(trend.metricName,freeze(trend)); }
  forecast(resourceType:ResourceType,predictedAt:number):CapacityForecast{ const caps=this.#byType(resourceType).map(r=>r.capacity); const avg=caps.length?caps.reduce((a,c)=>a+c.utilizationPercent,0)/caps.length:0; const trend=[...this.#trends.values()].find(t=>t.metricName.includes(resourceType)); const predictedUtilization=bounded(avg+(trend?.slope??0)*Math.max(0,predictedAt-Date.now())); const forecast={resourceType,predictedUtilization,predictedAt,confidence:trend?.confidence??0.5,assumptions:[`current-average:${avg.toFixed(2)}`,trend?`trend:${trend.direction}`:'trend:static']}; this.#forecasts.set(resourceType,freeze(forecast)); return clone(forecast); }
  validateProduction(productionId:string, now:number):CapacityValidationResult{ const budget=this.#budgets.get(productionId); const blockers:string[]=[], warnings:string[]=[], recommendations:string[]=[]; if(!budget) return {productionId,passed:false,blockers:['missing capacity budget'],warnings,recommendations:['define a production capacity budget before launch']}; for(const limit of budget.limits){ const caps=this.#byType(limit.resourceType).map(r=>r.capacity); const aggregate=this.#aggregate(limit.resourceType,now); const msg=`${limit.resourceType} utilization ${aggregate.utilizationPercent.toFixed(2)}%`; const breach=aggregate.utilizationPercent>limit.maximumUtilizationPercent||(limit.minimumAvailable!==undefined&&aggregate.available<limit.minimumAvailable)||(limit.reserveAmount!==undefined&&aggregate.available<limit.reserveAmount); if(breach&&limit.enforcementMode===CapacityEnforcement.Block) blockers.push(msg); else if(breach) warnings.push(msg); if(caps.some(c=>detectSaturation(c,this.#forecasts.get(limit.resourceType))!==SaturationState.Normal)) recommendations.push(`review ${limit.resourceType} saturation and reduce load or reserve more capacity`); } return {productionId,passed:blockers.length===0,blockers,warnings,recommendations}; }
  simulate(scenario:CapacityScenario):CapacityValidationResult{ const blockers:string[]=[], warnings:string[]=[], recommendations=[...scenario.assumptions]; for(const [type,delta] of Object.entries(scenario.resourceDeltas) as [ResourceType,number][]) { const agg=this.#aggregate(type,scenario.startsAt); const projected=agg.total===0?100:((agg.total-agg.available+delta)/agg.total)*100; if(projected>=agg.criticalLimitPercent) blockers.push(`${type} would exceed critical capacity at ${projected.toFixed(2)}%`); else if(projected>=agg.safeLimitPercent) warnings.push(`${type} would exceed safe capacity at ${projected.toFixed(2)}%`); } return {productionId:scenario.productionId,passed:blockers.length===0,blockers,warnings,recommendations}; }
  optimize():OptimizationRecommendation[]{ this.#recommendations.clear(); for(const item of this.#inventory.values()){ const state=detectSaturation(item.capacity,this.#forecasts.get(item.resourceType)); if(state!==SaturationState.Normal){ const rec={id:`opt-${item.resourceId}`,title:`Reduce ${item.resourceType} pressure on ${item.logicalName}`,expectedBenefit:'restores safe operating headroom',estimatedImpact:`current utilization ${item.capacity.utilizationPercent.toFixed(2)}%`,implementationRisk:'operator approval required before automated redistribution',automated:false}; this.#recommendations.set(rec.id,freeze(rec)); } } return [...this.#recommendations.values()].map(clone).sort((a,b)=>a.id.localeCompare(b.id)); }
  bottleneck():ResourceType|undefined{ return [...Object.values(ResourceType)].map(t=>this.#aggregate(t,Date.now())).sort((a,b)=>b.utilizationPercent-a.utilizationPercent)[0]?.resourceType; }
  upgradePlan(plan:UpgradePlan):OptimizationRecommendation{ const benefit=Object.entries(plan.addedResources).map(([t,q])=>`${q} additional ${t}`).join(', '); return {id:`upgrade-${plan.id}`,title:plan.title,expectedBenefit:plan.estimatedBenefits.join('; ')||benefit,estimatedImpact:benefit,implementationRisk:plan.risks.join('; ')||'capacity model only; requires engineering approval',automated:false}; }
  compare(id:string,metricName:string,left:MetricSample[],right:MetricSample[],leftLabel='left',rightLabel='right'):ComparisonReport{ const avg=(s:MetricSample[])=>s.length?s.reduce((a,b)=>a+b.value,0)/s.length:0; const l=avg(left), r=avg(right), delta=r-l; return {id,metricName,leftLabel,rightLabel,delta,percentChange:l===0?0:(delta/l)*100,summary:`${metricName} changed by ${delta.toFixed(2)} (${(l===0?0:(delta/l)*100).toFixed(2)}%)`}; }
  efficiencyScore():number{ const items=[...this.#inventory.values()].filter(i=>i.state!==ResourceState.Retired); if(!items.length) return 0; const scores=items.map(i=>{ const u=i.capacity.utilizationPercent; const headroom=i.capacity.safeLimitPercent-u; const statePenalty=[ResourceState.Failed,ResourceState.Offline,ResourceState.Maintenance].includes(i.state)?40:0; const wastePenalty=u<10?10:0; const saturationPenalty=headroom<0?30:headroom<10?10:0; return bounded(100-statePenalty-wastePenalty-saturationPenalty); }); return scores.reduce((a,b)=>a+b,0)/scores.length; }
  health(){ const recs=this.optimize(); const critical=[...this.#inventory.values()].filter(i=>detectSaturation(i.capacity)===SaturationState.Exceeded); return {status:critical.length?HealthStatus.Critical:recs.length?HealthStatus.Warning:HealthStatus.Healthy,score:bounded(this.efficiencyScore()),reasons:[...critical.map(i=>`${i.resourceId} exceeded critical limit`),...recs.map(r=>r.title)].slice(0,20)}; }
  alertSeverity(resourceId:string):AlertSeverity|undefined{ const item=this.#inventory.get(resourceId); if(!item) return undefined; const sat=detectSaturation(item.capacity,this.#forecasts.get(item.resourceType)); return sat===SaturationState.Exceeded?AlertSeverity.Critical:sat===SaturationState.Saturated?AlertSeverity.Major:sat===SaturationState.Approaching?AlertSeverity.Warning:undefined; }
  snapshot():CapacitySnapshot{ return clone({inventory:[...this.#inventory.values()].sort((a,b)=>a.resourceId.localeCompare(b.resourceId)),budgets:[...this.#budgets.values()].sort((a,b)=>a.productionId.localeCompare(b.productionId)),reservations:[...this.#reservations.values()].sort((a,b)=>a.id.localeCompare(b.id)),baselines:[...this.#baselines.values()].sort((a,b)=>a.id.localeCompare(b.id)),trends:[...this.#trends.values()].sort((a,b)=>a.metricName.localeCompare(b.metricName)),forecasts:[...this.#forecasts.values()].sort((a,b)=>a.resourceType.localeCompare(b.resourceType)),recommendations:[...this.#recommendations.values()].sort((a,b)=>a.id.localeCompare(b.id)),audit:this.#audit.slice(-this.maxAudit),health:this.health()}); }
  #byType(t:ResourceType){ return [...this.#inventory.values()].filter(i=>i.resourceType===t&&!['offline','failed','retired'].includes(i.state)); }
  #totalFor(t:ResourceType){ return this.#byType(t).reduce((a,i)=>a+i.capacity.total,0); }
  #maintenanceFor(t:ResourceType){ return [...this.#inventory.values()].filter(i=>i.resourceType===t&&i.state===ResourceState.Maintenance).reduce((a,i)=>a+i.capacity.total,0); }
  #aggregate(t:ResourceType, _now:number):ResourceCapacity{ const caps=this.#byType(t).map(i=>i.capacity); const total=caps.reduce((a,c)=>a+c.total,0), reserved=caps.reduce((a,c)=>a+c.reserved,0), allocated=caps.reduce((a,c)=>a+c.allocated,0); return calculateCapacity({resourceId:`aggregate:${t}`,resourceType:t,total,reserved,allocated,safeLimitPercent:Math.min(...caps.map(c=>c.safeLimitPercent),70),warningLimitPercent:Math.min(...caps.map(c=>c.warningLimitPercent),60),criticalLimitPercent:Math.min(...caps.map(c=>c.criticalLimitPercent),90),measuredAt:_now}); }
}
