export type MediaRuntimeBackend = 'ffmpeg' | 'browser' | 'mock';
export type MediaRuntimeStateValue = 'idle' | 'probing' | 'ready' | 'starting' | 'running' | 'recording' | 'streaming' | 'stopping' | 'stopped' | 'failed' | 'unavailable';
export type MediaSourceKind = 'video_file' | 'audio_file' | 'camera' | 'microphone';
export type MediaSinkKind = 'mp4_recording' | 'rtmp_stream';
export type MediaPacketFormat = 'rawvideo' | 'rgba' | 'yuv420p' | 'pcm_s16le' | 'encoded';
export type RuntimeStatusEventType = 'runtime_created' | 'source_registered' | 'sink_registered' | 'clock_tick' | 'scheduler_tick' | 'pipeline_started' | 'pipeline_stopped' | 'pipeline_failed' | 'recording_started' | 'recording_stopped' | 'rtmp_stubbed';

export interface MediaRuntimeId { readonly id: string; readonly label?: string; readonly metadata?: Readonly<Record<string, unknown>>; }
export interface MediaFormat { readonly codec?: string; readonly width?: number; readonly height?: number; readonly fps?: number; readonly sampleRate?: number; readonly channels?: number; readonly bitrateKbps?: number; readonly pixelFormat?: string; }
export interface MediaSource extends MediaRuntimeId { readonly kind: MediaSourceKind; readonly uri: string; readonly format?: MediaFormat; readonly enabled: boolean; readonly graphSourceId?: string; readonly containsRuntimeHandles: false; }
export interface MediaSink extends MediaRuntimeId { readonly kind: MediaSinkKind; readonly uri: string; readonly format?: MediaFormat; readonly enabled: boolean; readonly graphOutputId?: string; readonly containsRuntimeHandles: false; }
export interface VideoFramePacket { readonly id: string; readonly sourceId: string; readonly ptsMs: number; readonly durationMs: number; readonly format: MediaPacketFormat; readonly width: number; readonly height: number; readonly metadataOnly: true; readonly payloadRef?: string; readonly containsFrameData: false; }
export interface AudioPacket { readonly id: string; readonly sourceId: string; readonly ptsMs: number; readonly durationMs: number; readonly format: MediaPacketFormat; readonly sampleRate: number; readonly channels: number; readonly metadataOnly: true; readonly payloadRef?: string; readonly containsAudioData: false; }
export interface CoreMediaClockSample { readonly frameId: number; readonly monotonicMs: number; readonly wallClock: string; readonly fps: number; readonly driftMs: number; }
export interface CoreMediaClock { readonly id: string; readonly fps: number; now(): CoreMediaClockSample; reset(): CoreMediaClockSample; }
export interface FrameSchedule { readonly frameId: number; readonly dueAtMs: number; readonly sources: readonly string[]; readonly sinks: readonly string[]; readonly graphRevision?: number; readonly metadataOnly: true; }
export interface CoreFrameScheduler { schedule(clock: CoreMediaClock, sources: readonly MediaSource[], sinks: readonly MediaSink[], graphRevision?: number): FrameSchedule; }
export interface RuntimeStatusEvent { readonly id: string; readonly type: RuntimeStatusEventType; readonly timestamp: string; readonly state: MediaRuntimeStateValue; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface MediaRuntimeState { readonly id: string; readonly backend: MediaRuntimeBackend; readonly state: MediaRuntimeStateValue; readonly sources: readonly MediaSource[]; readonly sinks: readonly MediaSink[]; readonly clock: CoreMediaClockSample; readonly schedules: readonly FrameSchedule[]; readonly events: readonly RuntimeStatusEvent[]; readonly graphRevision?: number; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface MediaRuntimePipeline { readonly id: string; readonly sources: readonly MediaSource[]; readonly sinks: readonly MediaSink[]; readonly graphRevision?: number; readonly metadataOnly: true; }
export interface MediaRuntimeAdapter { readonly backend: MediaRuntimeBackend; createPipeline(pipeline: MediaRuntimePipeline): Promise<MediaRuntimeState>; start(pipeline: MediaRuntimePipeline): Promise<MediaRuntimeState>; stop(): Promise<MediaRuntimeState>; recordMp4(pipeline: MediaRuntimePipeline, outputUri: string): Promise<MediaRuntimeState>; streamRtmp(pipeline: MediaRuntimePipeline, rtmpUrl: string): Promise<MediaRuntimeState>; }

const now = () => new Date().toISOString();
const id = (p: string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
export const createMediaSource = (input: Omit<MediaSource, 'containsRuntimeHandles' | 'enabled'> & { enabled?: boolean }): MediaSource => Object.freeze({ ...input, enabled: input.enabled ?? true, containsRuntimeHandles: false });
export const createMediaSink = (input: Omit<MediaSink, 'containsRuntimeHandles' | 'enabled'> & { enabled?: boolean }): MediaSink => Object.freeze({ ...input, enabled: input.enabled ?? true, containsRuntimeHandles: false });
export function createMediaClock(fps = 30, clockId = 'ubos-media-clock'): CoreMediaClock { let frameId = 0; const start = Date.now(); return { id: clockId, fps, now() { frameId += 1; const monotonicMs = Date.now() - start; return { frameId, monotonicMs, wallClock: now(), fps, driftMs: monotonicMs - (frameId * (1000 / fps)) }; }, reset() { frameId = 0; return { frameId, monotonicMs: 0, wallClock: now(), fps, driftMs: 0 }; } }; }
export class DefaultFrameScheduler implements CoreFrameScheduler { schedule(clock: CoreMediaClock, sources: readonly MediaSource[], sinks: readonly MediaSink[], graphRevision?: number): FrameSchedule { const sample = clock.now(); return { frameId: sample.frameId, dueAtMs: sample.monotonicMs + (1000 / clock.fps), sources: sources.filter((s) => s.enabled).map((s) => s.id), sinks: sinks.filter((s) => s.enabled).map((s) => s.id), ...(graphRevision !== undefined ? { graphRevision } : {}), metadataOnly: true }; } }
export const createRuntimeStatusEvent = (type: RuntimeStatusEventType, state: MediaRuntimeStateValue, message: string, metadata: Record<string, unknown> = {}): RuntimeStatusEvent => ({ id: id(type), type, timestamp: now(), state, message, metadata });
export const createMediaRuntimePipeline = (input: Omit<MediaRuntimePipeline, 'metadataOnly'>): MediaRuntimePipeline => Object.freeze({ ...input, metadataOnly: true });
export function createMediaRuntimeState(input: { id?: string; backend?: MediaRuntimeBackend; state?: MediaRuntimeStateValue; sources?: readonly MediaSource[]; sinks?: readonly MediaSink[]; clock?: CoreMediaClockSample; schedules?: readonly FrameSchedule[]; events?: readonly RuntimeStatusEvent[]; graphRevision?: number; }): MediaRuntimeState { return Object.freeze({ id: input.id ?? id('media-runtime'), backend: input.backend ?? 'mock', state: input.state ?? 'idle', sources: input.sources ?? [], sinks: input.sinks ?? [], clock: input.clock ?? createMediaClock().reset(), schedules: input.schedules ?? [], events: input.events ?? [], ...(input.graphRevision !== undefined ? { graphRevision: input.graphRevision } : {}), containsRuntimeHandles: false, containsMediaPayloads: false }); }
export function mapProductionGraphSources(graph: { revision?: number; scenes?: readonly { sources?: readonly { id: string; type?: string; name?: string; uri?: string }[] }[] }): MediaRuntimePipeline { const sources = (graph.scenes ?? []).flatMap((scene) => scene.sources ?? []).map((source) => createMediaSource({ id: `runtime:${source.id}`, ...(source.name ? { label: source.name } : {}), kind: source.type === 'audio' ? 'audio_file' : 'video_file', uri: source.uri ?? `graph://${source.id}`, graphSourceId: source.id })); return createMediaRuntimePipeline({ id: id('graph-pipeline'), sources, sinks: [], ...(graph.revision !== undefined ? { graphRevision: graph.revision } : {}) }); }

export * from "./video-decoder.js";
export * from "./ffmpeg/video-decoder.js";
