import { createClock, type MediaClock } from '../sync/clock.js';
import { FrameScheduler, type FrameTickEvent } from '../sync/index.js';

export type VideoContainerFormat = 'mp4' | 'mov' | 'mkv' | 'webm';
export type VideoDecoderState = 'idle' | 'opening' | 'decoding' | 'paused' | 'completed' | 'failed';
export type VideoDecoderEventType = 'decoder_created' | 'decoder_opening' | 'decoder_opened' | 'frame_decoded' | 'decoder_paused' | 'decoder_resumed' | 'decoder_completed' | 'decoder_failed' | 'decoder_closed';

export interface VideoDecodeSource { readonly id: string; readonly uri: string; readonly container: VideoContainerFormat; readonly label?: string; readonly metadataOnly: true; }
export interface VideoFrameMetadata { readonly frameIndex: number; readonly ptsMs: number; readonly dtsMs?: number; readonly durationMs: number; readonly width: number; readonly height: number; readonly pixelFormat: string; readonly colorSpace: string; readonly clockFrameId: number; readonly scheduledPresentationMs: number; readonly late: boolean; readonly metadataOnly: true; readonly containsFrameData: false; readonly payloadRef?: string; }
export interface VideoDecoderStatusEvent { readonly id: string; readonly type: VideoDecoderEventType; readonly timestamp: string; readonly state: VideoDecoderState; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface VideoDecoderSnapshot { readonly id: string; readonly backend: 'ffmpeg' | 'mock'; readonly state: VideoDecoderState; readonly source?: VideoDecodeSource; readonly framesDecoded: number; readonly endOfStream: boolean; readonly bufferedFrames: number; readonly latestFrame?: VideoFrameMetadata; readonly events: readonly VideoDecoderStatusEvent[]; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface FrameBuffer<TFrame extends VideoFrameMetadata = VideoFrameMetadata> { readonly capacity: number; push(frame: TFrame): TFrame | undefined; peek(): TFrame | undefined; pop(): TFrame | undefined; clear(): void; size(): number; isFull(): boolean; isEmpty(): boolean; snapshot(): readonly TFrame[]; }
export interface VideoDecoder { readonly id: string; readonly backend: 'ffmpeg' | 'mock'; open(source: VideoDecodeSource): Promise<VideoDecoderSnapshot>; decodeNext(): Promise<VideoFrameMetadata | undefined>; pause(): VideoDecoderSnapshot; resume(): VideoDecoderSnapshot; close(): Promise<VideoDecoderSnapshot>; getSnapshot(): VideoDecoderSnapshot; getBuffer(): FrameBuffer; onStatus(callback: (event: VideoDecoderStatusEvent) => void): () => void; }

const now = () => new Date().toISOString();
const eventId = (type: string) => `${type}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
export const supportedVideoDecodeContainers: readonly VideoContainerFormat[] = ['mp4', 'mov', 'mkv', 'webm'] as const;
export function inferVideoContainer(uri: string): VideoContainerFormat { const ext = uri.split('?')[0]?.split('.').pop()?.toLowerCase(); if (ext === 'mp4' || ext === 'mov' || ext === 'mkv' || ext === 'webm') return ext; throw new Error(`Unsupported video container: ${ext ?? 'unknown'}`); }
export function createVideoDecodeSource(input: Omit<VideoDecodeSource, 'container' | 'metadataOnly'> & { container?: VideoContainerFormat }): VideoDecodeSource { return Object.freeze({ ...input, container: input.container ?? inferVideoContainer(input.uri), metadataOnly: true }); }
export function createVideoDecoderStatusEvent(type: VideoDecoderEventType, state: VideoDecoderState, message: string, metadata: Record<string, unknown> = {}): VideoDecoderStatusEvent { return Object.freeze({ id: eventId(type), type, timestamp: now(), state, message, metadata: Object.freeze(metadata) }); }

export class RingFrameBuffer<TFrame extends VideoFrameMetadata = VideoFrameMetadata> implements FrameBuffer<TFrame> { private frames: TFrame[] = []; constructor(readonly capacity = 30) { if (capacity <= 0) throw new Error('Frame buffer capacity must be positive'); } push(frame: TFrame) { const dropped = this.isFull() ? this.frames.shift() : undefined; this.frames.push(frame); return dropped; } peek() { return this.frames[0]; } pop() { return this.frames.shift(); } clear() { this.frames = []; } size() { return this.frames.length; } isFull() { return this.frames.length >= this.capacity; } isEmpty() { return this.frames.length === 0; } snapshot() { return Object.freeze([...this.frames]); } }

export interface MetadataVideoDecoderOptions { readonly id?: string; readonly backend?: 'ffmpeg' | 'mock'; readonly clock?: MediaClock; readonly scheduler?: FrameScheduler; readonly buffer?: FrameBuffer; readonly events?: readonly VideoDecoderStatusEvent[]; }
export abstract class MetadataVideoDecoder implements VideoDecoder { readonly id: string; readonly backend: 'ffmpeg' | 'mock'; protected state: VideoDecoderState = 'idle'; protected source?: VideoDecodeSource; protected frameIndex = 0; protected endOfStream = false; protected latestFrame?: VideoFrameMetadata; protected events: VideoDecoderStatusEvent[]; protected listeners = new Set<(event: VideoDecoderStatusEvent) => void>(); protected clock: MediaClock; protected scheduler: FrameScheduler; protected buffer: FrameBuffer; constructor(options: MetadataVideoDecoderOptions = {}) { this.id = options.id ?? `video-decoder-${Date.now()}`; this.backend = options.backend ?? 'mock'; this.clock = options.clock ?? createClock(); this.scheduler = options.scheduler ?? new FrameScheduler(this.clock); this.buffer = options.buffer ?? new RingFrameBuffer(); this.events = [...(options.events ?? [createVideoDecoderStatusEvent('decoder_created', 'idle', 'Video decoder created', { decoderId: this.id })])]; }
  abstract open(source: VideoDecodeSource): Promise<VideoDecoderSnapshot>; abstract decodeNext(): Promise<VideoFrameMetadata | undefined>;
  pause() { if (this.state === 'decoding') { this.state = 'paused'; this.clock.pause(); this.emit('decoder_paused', 'Decoder paused'); } return this.getSnapshot(); }
  resume() { if (this.state === 'paused') { this.state = 'decoding'; this.clock.resume(); this.emit('decoder_resumed', 'Decoder resumed'); } return this.getSnapshot(); }
  async close() { this.state = this.endOfStream ? 'completed' : 'idle'; this.buffer.clear(); this.clock.stop(); this.emit('decoder_closed', 'Decoder closed'); return this.getSnapshot(); }
  getSnapshot() { return Object.freeze({ id: this.id, backend: this.backend, state: this.state, ...(this.source ? { source: this.source } : {}), framesDecoded: this.frameIndex, endOfStream: this.endOfStream, bufferedFrames: this.buffer.size(), ...(this.latestFrame ? { latestFrame: this.latestFrame } : {}), events: Object.freeze([...this.events]), containsRuntimeHandles: false, containsMediaPayloads: false }); }
  getBuffer() { return this.buffer; }
  onStatus(callback: (event: VideoDecoderStatusEvent) => void) { this.listeners.add(callback); return () => this.listeners.delete(callback); }
  protected emit(type: VideoDecoderEventType, message: string, metadata: Record<string, unknown> = {}) { const e = createVideoDecoderStatusEvent(type, this.state, message, metadata); this.events = [e, ...this.events].slice(0, 200); this.listeners.forEach((cb) => cb(e)); return e; }
  protected attachTiming(frame: Omit<VideoFrameMetadata, 'clockFrameId' | 'scheduledPresentationMs' | 'late' | 'metadataOnly' | 'containsFrameData'>): VideoFrameMetadata { if (this.clock.getState().status === 'stopped') this.clock.start(); const tick: FrameTickEvent = this.scheduler.createTick(this.clock.getState().startTime + frame.ptsMs); const scheduledPresentationMs = this.clock.getFrameTimestamp(frame.frameIndex); return Object.freeze({ ...frame, clockFrameId: frame.frameIndex, scheduledPresentationMs, late: tick.diagnostics?.classification === 'late', metadataOnly: true, containsFrameData: false }); }
}
