export type AnalyticsRuntimeSource = 'production'|'execution'|'switching'|'media'|'replay'|'graphics'|'audio'|'webrtc'|'monitoring'|'cluster'|'plugin'|'security'|'automation'|'distribution'|'recording'|'ai-director'|'cloud';
export type AnalyticsKpi = 'switches'|'transitions'|'productionDuration'|'guestCount'|'operatorActivity'|'audioLevels'|'graphicsUsage'|'mediaUsage'|'replayUsage'|'recordingHours'|'streamingOutputs'|'systemHealth'|'cpuUsage'|'gpuUsage'|'droppedFrames'|'latency'|'storage'|'bandwidth'|'operatorErrors'|'automationEvents'|'securityEvents'|'pluginUsage';
export type AnalyticsDashboard = { id:string; title:string; category:'executive'|'operations'|'production'|'engineering'|'ai'|'monitoring'|'media'|'graphics'|'audio'|'distribution'|'security'|'cloud'|'plugin'; widgets: AnalyticsVisualization[]; metadataOnly:true };
export type AnalyticsReport = { id:string; title:string; cadence:'daily'|'weekly'|'monthly'|'ad-hoc'; sections:string[]; generatedAt:string; rows: Record<string,string|number|boolean>[]; metadataOnly:true };
export type AnalyticsMetric = { kpi: AnalyticsKpi; value:number; unit:string; source:AnalyticsRuntimeSource; timestamp:string; dimensions?:Record<string,string>; metadataOnly:true };
export type AnalyticsEvent = { id:string; source:AnalyticsRuntimeSource; type:string; timestamp:string; count?:number; durationMs?:number; severity?:'info'|'warning'|'critical'; dimensions?:Record<string,string>; metadataOnly:true };
export type AnalyticsQuery = { sources?:AnalyticsRuntimeSource[]; kpis?:AnalyticsKpi[]; since?:string; until?:string; filters?:AnalyticsFilter[]; metadataOnly:true };
export type AnalyticsSnapshot = { id:string; at:string; metrics:AnalyticsMetric[]; events:AnalyticsEvent[]; dashboards:AnalyticsDashboard[]; alerts:AnalyticsAlert[]; metadataOnly:true };
export type AnalyticsTimeline = { id:string; events:AnalyticsEvent[]; metadataOnly:true };
export type AnalyticsTrend = { kpi:AnalyticsKpi; direction:'up'|'down'|'flat'; delta:number; points:AnalyticsMetric[]; metadataOnly:true };
export type AnalyticsFilter = { field:string; op:'eq'|'neq'|'gt'|'gte'|'lt'|'lte'|'contains'; value:string|number|boolean; metadataOnly:true };
export type AnalyticsDimension = { key:string; label:string; values:string[]; metadataOnly:true };
export type AnalyticsMeasure = { kpi:AnalyticsKpi; label:string; unit:string; aggregation:'sum'|'avg'|'min'|'max'|'count'; metadataOnly:true };
export type AnalyticsForecast = { kpi:AnalyticsKpi; horizon:'next-hour'|'next-production'|'next-day'|'next-week'; expected:number; confidence:number; method:'deterministic-moving-average'; metadataOnly:true };
export type AnalyticsAlert = { id:string; kpi:AnalyticsKpi; severity:'info'|'warning'|'critical'; message:string; threshold:number; value:number; metadataOnly:true };
export type AnalyticsInsight = { id:string; title:string; detail:string; source:AnalyticsRuntimeSource|'aggregate'; severity:'info'|'warning'|'critical'; metadataOnly:true };
export type AnalyticsExport = { format:'pdf'|'csv'|'json'|'markdown'|'excel-table'; filename:string; content:string; metadataOnly:true };
export type AnalyticsDataset = { id:string; name:string; metrics:AnalyticsMetric[]; events:AnalyticsEvent[]; metadataOnly:true };
export type AnalyticsVisualization = { id:string; title:string; type:'line'|'bar'|'pie'|'heat-map'|'trend'|'timeline'|'kpi-card'|'gauge'|'scorecard'|'activity-stream'; kpis:AnalyticsKpi[]; metadataOnly:true };
export type AnalyticsWorkspace = { dashboards:AnalyticsDashboard[]; reports:AnalyticsReport[]; insights:AnalyticsInsight[]; forecasts:AnalyticsForecast[]; metadataOnly:true };
export type AnalyticsHistory = { snapshots:AnalyticsSnapshot[]; metadataOnly:true };
export type AnalyticsCache = { datasets:Map<string,AnalyticsDataset>; metadataOnly:true };
export type AnalyticsRegistry = { sources:AnalyticsRuntimeSource[]; measures:AnalyticsMeasure[]; dimensions:AnalyticsDimension[]; metadataOnly:true };
export type AnalyticsPipeline = { stages:string[]; externalTelemetryEnabled:false; browserSdksEnabled:false; metadataOnly:true };
export type AnalyticsSession = { id:string; name:string; events:AnalyticsEvent[]; metrics:AnalyticsMetric[]; history:AnalyticsHistory; metadataOnly:true };
const sources: AnalyticsRuntimeSource[] = ['production','execution','switching','media','replay','graphics','audio','webrtc','monitoring','cluster','plugin','security','automation','distribution','recording','ai-director','cloud'];
const kpis: AnalyticsKpi[] = ['switches','transitions','productionDuration','guestCount','operatorActivity','audioLevels','graphicsUsage','mediaUsage','replayUsage','recordingHours','streamingOutputs','systemHealth','cpuUsage','gpuUsage','droppedFrames','latency','storage','bandwidth','operatorErrors','automationEvents','securityEvents','pluginUsage'];
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${Date.now().toString(36)}`;
export class AnalyticsValidator { static rejectUnsafe(input:Record<string,unknown>){ const banned=['runtimeHandle','mediaData','videoFrame','audioBuffer','pixel','cookie','trackingPixel','googleAnalytics','mixpanel','amplitude','segment','telemetryUpload','endpoint','url','sdk']; for(const key of banned) if(key in input) throw new Error(`Unsafe analytics field rejected: ${key}`); } }
export class AnalyticsCollector { collect(event:Omit<AnalyticsEvent,'id'|'timestamp'|'metadataOnly'>):AnalyticsEvent{ AnalyticsValidator.rejectUnsafe(event as Record<string,unknown>); return {...event,id:id('analytics-event'),timestamp:now(),metadataOnly:true}; } }
export class AnalyticsAggregator { aggregate(events:AnalyticsEvent[]):AnalyticsMetric[]{ return kpis.map((kpi)=>({kpi,value:events.filter((e)=>e.type===kpi).reduce((n,e)=>n+(e.count??1),0),unit:'count',source:'production',timestamp:now(),metadataOnly:true})); } }
export class AnalyticsEngine { aggregator=new AnalyticsAggregator(); query(session:AnalyticsSession, query:AnalyticsQuery):AnalyticsDataset{ AnalyticsValidator.rejectUnsafe(query as Record<string,unknown>); const events=session.events.filter((e)=>(!query.sources||query.sources.includes(e.source))); const metrics=session.metrics.concat(this.aggregator.aggregate(events)).filter((m)=>(!query.kpis||query.kpis.includes(m.kpi))); return {id:id('dataset'),name:'Analytics Query Result',events,metrics,metadataOnly:true}; } trends(metrics:AnalyticsMetric[]):AnalyticsTrend[]{ return kpis.map((kpi)=>{const points=metrics.filter((m)=>m.kpi===kpi); const delta=(points.at(-1)?.value??0)-(points[0]?.value??0); return {kpi,direction:delta>0?'up':delta<0?'down':'flat',delta,points,metadataOnly:true};}); } forecast(metrics:AnalyticsMetric[]):AnalyticsForecast[]{ return kpis.map((kpi)=>{const points=metrics.filter((m)=>m.kpi===kpi); const expected=points.reduce((n,m)=>n+m.value,0)/(points.length||1); return {kpi,horizon:'next-production',expected,confidence:points.length?0.7:0.3,method:'deterministic-moving-average',metadataOnly:true};}); } }
export class AnalyticsRuntime { collector=new AnalyticsCollector(); engine=new AnalyticsEngine(); constructor(public session:AnalyticsSession=createAnalyticsSession()){} record(input:Omit<AnalyticsEvent,'id'|'timestamp'|'metadataOnly'>){const e=this.collector.collect(input); this.session.events.push(e); this.session.metrics=this.engine.aggregator.aggregate(this.session.events); return e;} snapshot():AnalyticsSnapshot{const snap: AnalyticsSnapshot={id:id('analytics-snapshot'),at:now(),metrics:[...this.session.metrics],events:[...this.session.events],dashboards:createAnalyticsWorkspace().dashboards,alerts:[],metadataOnly:true}; this.session.history.snapshots.push(snap); return snap;} }
export class AnalyticsScheduler { schedule(report:AnalyticsReport){return {...report, metadataOnly:true as const};} }
export function createAnalyticsSession(name='UBOS Analytics Session'):AnalyticsSession{return {id:id('analytics-session'),name,events:[],metrics:[],history:{snapshots:[],metadataOnly:true},metadataOnly:true};}
export function createAnalyticsWorkspace():AnalyticsWorkspace{ const cats:AnalyticsDashboard['category'][]=['executive','operations','production','engineering','ai','monitoring','media','graphics','audio','distribution','security','cloud','plugin']; return {dashboards:cats.map((category)=>({id:`${category}-dashboard`,title:`${category.charAt(0).toUpperCase()}${category.slice(1)} Dashboard`,category,widgets:[{id:`${category}-kpis`,title:'KPI Cards',type:'kpi-card',kpis,metadataOnly:true}],metadataOnly:true})),reports:['Daily Report','Weekly Report','Monthly Report','Production Summary','Operator Summary','Performance Report','Failure Report','Availability Report','Compliance Report','Executive Summary'].map((title)=>({id:title.toLowerCase().replaceAll(' ','-'),title,cadence:title.includes('Weekly')?'weekly':title.includes('Monthly')?'monthly':'daily',sections:['KPIs','Insights','Alerts','Performance'],generatedAt:now(),rows:[],metadataOnly:true})),insights:[],forecasts:[],metadataOnly:true}; }
export function createAnalyticsPipeline():AnalyticsPipeline{return {stages:['collect','validate','aggregate','snapshot','report','export'],externalTelemetryEnabled:false,browserSdksEnabled:false,metadataOnly:true};}
