import { ExtensionCategory, ExtensionProcessType, ExtensionRiskLevel, ExtensionRuntimeType, ExtensionType, TenantIsolationMode, UBOSClient, validateManifest } from './index.js';
const manifest={id:'com.acme.social-monitor',name:'Social Monitor',description:'Safe social monitoring panel',publisherId:'pub-acme',version:'1.2.3',type:ExtensionType.UIExtension,category:ExtensionCategory.SocialConnector,entrypoints:[{id:'panel',runtime:ExtensionRuntimeType.JavaScript,module:'panel.js',processType:ExtensionProcessType.UI,startupMode:'on_demand' as const}],capabilities:[{capability:'social.messages.read',reason:'Read approved social messages',required:true,riskLevel:ExtensionRiskLevel.Low},{capability:'ui.panel.create',reason:'Create monitored UI panel',required:true,riskLevel:ExtensionRiskLevel.Low}],supportedUBOSVersions:'v5.11',supportedEnvironments:['cloud'],tenantIsolationMode:TenantIsolationMode.MultiTenantIsolated,riskLevel:ExtensionRiskLevel.Low,dependencies:[],support:{contact:'support@example.invalid',responseTargetHours:24},license:{model:'free'},integrity:{signature:'sig',sha256:'sha256:abc',signedBy:'key'}};
if(validateManifest(manifest).length) throw new Error('valid manifest rejected');
const bad={...manifest,id:'bad',capabilities:[{capability:'credential.export',reason:'steal secrets',required:true,riskLevel:ExtensionRiskLevel.Critical}]};
if(!validateManifest(bad).some(f=>f.includes('forbidden'))) throw new Error('forbidden capability accepted');
const client=new UBOSClient({extensionId:manifest.id,installationId:'inst-a',publisherId:'pub-acme',tenantId:'tenant-a',grantedCapabilities:['social.messages.read'],credentialId:'cred-a',installedAt:1,installedBy:'admin',status:'active'});
if(client.execute({type:'social.messages.read',scope:{tenantId:'tenant-a'},payload:{token:'secret'}}).payload instanceof Object === false) throw new Error('redaction failed');
try{ client.execute({type:'production.program.change',scope:{tenantId:'tenant-a'}}); throw new Error('denied command accepted'); } catch(error){ if((error as Error).message==='denied command accepted') throw error; }
console.log('v5.11.9 sdk validation passed');
