import { redact } from '../observability/index.js';
import type { AlertSeverity, HealthStatus } from '../observability/index.js';

export enum AlertStatus { Pending='pending', Active='active', Acknowledged='acknowledged', Suppressed='suppressed', Resolved='resolved', Expired='expired', ConvertedToIncident='converted_to_incident' }
export enum IncidentSeverity { Sev0='sev0', Sev1='sev1', Sev2='sev2', Sev3='sev3', Sev4='sev4' }
export enum IncidentStatus { Detected='detected', Open='open', Acknowledged='acknowledged', Investigating='investigating', Mitigating='mitigating', Monitoring='monitoring', Stabilized='stabilized', Resolved='resolved', Closed='closed', Reopened='reopened' }
export enum IncidentResponseRole { IncidentCommander='incident_commander', TechnicalLead='technical_lead', ProductionLead='production_lead', CommunicationsLead='communications_lead', SecurityLead='security_lead', SiteRecoveryLead='site_recovery_lead', Operator='operator', Scribe='scribe', Observer='observer' }
export enum IncidentTimerType { Acknowledgement='acknowledgement', Ownership='ownership', Investigation='investigation', Mitigation='mitigation', StatusUpdate='status_update', Escalation='escalation', Stabilization='stabilization', Resolution='resolution', Review='review' }
export enum IncidentTimerStatus { Running='running', Completed='completed', Breached='breached', Cancelled='cancelled' }
export enum RunbookStatus { Draft='draft', InReview='in_review', Approved='approved', Active='active', Deprecated='deprecated', Retired='retired' }
export enum RunbookStepType { Information='information', Verify='verify', Diagnose='diagnose', ManualAction='manual_action', AutomatedAction='automated_action', Approval='approval', Wait='wait', Decision='decision', Communication='communication', Escalation='escalation', Validation='validation', Rollback='rollback', Complete='complete' }
export enum RunbookExecutionStatus { Pending='pending', Running='running', Waiting='waiting', Paused='paused', Completed='completed', Failed='failed', Cancelled='cancelled', RolledBack='rolled_back' }
export enum RemediationRisk { Diagnostic='diagnostic', Low='low', Moderate='moderate', High='high', Critical='critical' }
export enum ReviewStatus { Required='required', Scheduled='scheduled', Completed='completed', Waived='waived' }
export enum CorrectiveActionStatus { Proposed='proposed', Approved='approved', InProgress='in_progress', Blocked='blocked', Completed='completed', Verified='verified', Cancelled='cancelled' }

export interface AlertEvidence { type:string; referenceId?:string; timestamp:number; summary:string; metricName?:string; value?:number; threshold?:number; traceId?:string; logQuery?:string; }
export interface OperationalAlert { id:string; source:string; sourceAlertId?:string; title:string; description?:string; severity:AlertSeverity; status:AlertStatus; productionId?:string; siteId?:string; nodeId?:string; componentType?:string; componentId?:string; detectedAt:number; lastObservedAt:number; observedCount:number; labels:Record<string,string>; evidence:AlertEvidence[]; correlationKey?:string; deduplicationKey?:string; recommendedRunbookId?:string; }
export interface SeverityAssessment { programImpact:number; audienceImpact:number; safetyImpact:number; securityImpact:number; redundancyRemaining:number; durationRisk:number; calculatedSeverity:IncidentSeverity; confidence:number; reasons:string[]; }
export interface IncidentComponent { componentType:string; componentId:string; health?:HealthStatus; impact:string; }
export interface OperationalIncident { id:string; title:string; description?:string; severity:IncidentSeverity; status:IncidentStatus; productionId?:string; siteId?:string; detectedAt:number; declaredAt:number; acknowledgedAt?:number; stabilizedAt?:number; resolvedAt?:number; closedAt?:number; ownerId?:string; commanderId?:string; affectedComponents:IncidentComponent[]; affectedOutputs:string[]; alertIds:string[]; correlationIds:string[]; runbookExecutionIds:string[]; communicationPlanId?:string; tags:string[]; createdBy:string; updatedAt:number; }
export interface IncidentAssignment { incidentId:string; role:IncidentResponseRole; identityId:string; assignedAt:number; assignedBy:string; acceptedAt?:number; releasedAt?:number; }
export interface IncidentTimer { incidentId:string; type:IncidentTimerType; startedAt:number; deadlineAt?:number; completedAt?:number; status:IncidentTimerStatus; }
export interface EscalationStep { order:number; afterMs:number; targetRoleIds?:string[]; targetIdentityIds?:string[]; targetScheduleIds?:string[]; channels:string[]; condition?:'no_acknowledgement'|'no_owner'|'duration_exceeded'|'recovery_failed'; requireAcknowledgement:boolean; }
export interface EscalationPolicy { id:string; name:string; severity:IncidentSeverity; steps:EscalationStep[]; enabled:boolean; }
export interface EscalationEvent { id:string; incidentId:string; policyId:string; stepOrder:number; triggeredAt:number; targets:string[]; channels:string[]; acknowledged:boolean; suppressed?:boolean; }
export interface OnCallRotation { startsAt:number; endsAt:number; primaryIdentityId:string; secondaryIdentityId?:string; roles:string[]; }
export interface OnCallSchedule { id:string; name:string; timezone:string; rotations:OnCallRotation[]; fallbackIdentityIds:string[]; enabled:boolean; }
export interface ValidationCheck { id:string; description:string; passed:boolean; observedAt:number; }
export interface RemediationAction { id:string; command:string; risk:RemediationRisk; idempotencyKey:string; requiresApproval:boolean; authorizedRoles:string[]; }
export interface RunbookStep { id:string; order:number; title:string; description?:string; type:RunbookStepType; action?:RemediationAction; timeoutMs?:number; approvalRequired?:boolean; successCriteria?:ValidationCheck[]; failureBehavior:'stop'|'continue'|'rollback'|'escalate'; }
export interface OperationalRunbook { id:string; name:string; description:string; applicableAlertTypes:string[]; applicableIncidentTypes:string[]; minimumSeverity?:IncidentSeverity; steps:RunbookStep[]; requiredRoles?:string[]; approvalPolicyId?:string; version:number; status:RunbookStatus; createdAt:number; updatedAt:number; }
export interface RunbookStepExecution { stepId:string; status:'pending'|'running'|'completed'|'failed'|'skipped'; startedAt?:number; completedAt?:number; result?:string; }
export interface RunbookExecution { id:string; runbookId:string; runbookVersion:number; incidentId:string; status:RunbookExecutionStatus; startedAt:number; startedBy:string; currentStepId?:string; stepExecutions:RunbookStepExecution[]; completedAt?:number; }
export interface StatusUpdate { id:string; incidentId:string; audience:'internal'|'external'; message:string; createdAt:number; createdBy:string; approvedBy?:string; publishedAt?:number; }
export interface RootCauseFinding { classification:'confirmed'|'probable'|'unknown'; summary:string; evidenceRecordIds:string[]; confidence:number; }
export interface CorrectiveAction { id:string; title:string; description:string; ownerId:string; priority:string; dueAt?:number; status:CorrectiveActionStatus; verificationCriteria?:string[]; }
export interface PostIncidentReview { id:string; incidentId:string; ownerId:string; scheduledAt?:number; completedAt?:number; summary?:string; impact?:string; rootCause?:RootCauseFinding; contributingFactors:string[]; whatWentWell:string[]; whatWentPoorly:string[]; correctiveActions:CorrectiveAction[]; status:ReviewStatus; }
export interface IncidentMetrics { incidentId:string; timeToDetectMs?:number; timeToAcknowledgeMs?:number; timeToAssignMs?:number; timeToMitigateMs?:number; timeToStabilizeMs?:number; timeToResolveMs?:number; escalationCount:number; responderCount:number; runbookStepsCompleted:number; automatedActions:number; manualActions:number; reopened:boolean; }
export interface IncidentResponseSnapshot { alerts:OperationalAlert[]; incidents:OperationalIncident[]; assignments:IncidentAssignment[]; timers:IncidentTimer[]; escalations:EscalationEvent[]; runbooks:OperationalRunbook[]; executions:RunbookExecution[]; statusUpdates:StatusUpdate[]; reviews:PostIncidentReview[]; audit:string[]; }

const clone=<T>(v:T):T=>structuredClone(v);
const freezeClone=<T>(v:T):T=>Object.freeze(clone(v));
const sevRank:Record<IncidentSeverity,number>={sev0:0,sev1:1,sev2:2,sev3:3,sev4:4};
function assertIdentity(id:string):void{ if(!id.trim()) throw new Error('identity is required'); }

export function assessSeverity(input:Omit<SeverityAssessment,'calculatedSeverity'|'confidence'|'reasons'>):SeverityAssessment{ const score=input.programImpact*3+input.audienceImpact*2+input.safetyImpact*4+input.securityImpact*4+input.durationRisk*2-input.redundancyRemaining; const calculatedSeverity=score>=25?IncidentSeverity.Sev0:score>=18?IncidentSeverity.Sev1:score>=11?IncidentSeverity.Sev2:score>=5?IncidentSeverity.Sev3:IncidentSeverity.Sev4; return {...input,calculatedSeverity,confidence:Math.min(1,Math.max(.2,score/30)),reasons:[`impact-score:${score}`,`redundancy-remaining:${input.redundancyRemaining}`]}; }

export class IncidentResponseEngine {
  #alerts=new Map<string,OperationalAlert>(); #incidents=new Map<string,OperationalIncident>(); #assignments:IncidentAssignment[]=[]; #timers:IncidentTimer[]=[]; #policies=new Map<string,EscalationPolicy>(); #escalations:EscalationEvent[]=[]; #runbooks=new Map<string,OperationalRunbook>(); #executions=new Map<string,RunbookExecution>(); #updates:StatusUpdate[]=[]; #reviews=new Map<string,PostIncidentReview>(); #audit:string[]=[];
  constructor(private readonly maxRecords=10000){}
  ingestAlert(input:Omit<OperationalAlert,'id'|'status'|'observedCount'|'labels'|'evidence'> & {id?:string; labels?:Record<string,string>; evidence?:AlertEvidence[]}):OperationalAlert{ const key=input.deduplicationKey??`${input.source}:${input.sourceAlertId??input.title}`; const existing=[...this.#alerts.values()].find(a=>a.deduplicationKey===key&&![AlertStatus.Resolved,AlertStatus.Expired].includes(a.status)); const labels=redact(input.labels??{}) as Record<string,string>; const evidence=(input.evidence??[]).map(e=>redact(e) as AlertEvidence); if(existing){ const next={...existing,lastObservedAt:input.lastObservedAt,observedCount:existing.observedCount+1,evidence:[...existing.evidence,...evidence].slice(-50)}; this.#alerts.set(existing.id,freezeClone(next)); this.#audit.push(`alert.deduplicated:${existing.id}`); return clone(next); } const alert:OperationalAlert={...input,id:input.id??`alert-${this.#alerts.size+1}`,status:AlertStatus.Active,observedCount:1,labels,evidence,deduplicationKey:key}; this.#alerts.set(alert.id,freezeClone(alert)); this.#audit.push(`alert.normalized:${alert.id}`); return clone(alert); }
  correlate(alertIds:string[]){ const alerts=alertIds.map(id=>this.#alerts.get(id)).filter(Boolean) as OperationalAlert[]; const key=alerts[0]?.correlationKey??alerts[0]?.componentId; const related=alerts.filter(a=>key&&(a.correlationKey===key||a.componentId===key)); return {alertIds:related.map(a=>a.id),confidence:related.length>1?.8:.4,likelyRootComponentId:key,reasons:[`shared-correlation:${key??'none'}`]}; }
  createIncident(input:{title:string; description?:string; severity:IncidentSeverity; alertIds?:string[]; productionId?:string; siteId?:string; now:number; createdBy:string; affectedComponents?:IncidentComponent[]; affectedOutputs?:string[]; runbookId?:string;}):OperationalIncident{ assertIdentity(input.createdBy); const id=`incident-${this.#incidents.size+1}`; const incident:OperationalIncident={id,title:String(redact(input.title)),description:String(redact(input.description??'')),severity:input.severity,status:IncidentStatus.Open,productionId:input.productionId,siteId:input.siteId,detectedAt:Math.min(...(input.alertIds??[]).map(a=>this.#alerts.get(a)?.detectedAt??input.now),input.now),declaredAt:input.now,affectedComponents:input.affectedComponents??[],affectedOutputs:input.affectedOutputs??[],alertIds:input.alertIds??[],correlationIds:[],runbookExecutionIds:[],tags:input.severity===IncidentSeverity.Sev0||input.severity===IncidentSeverity.Sev1?['major-incident']:[],createdBy:input.createdBy,updatedAt:input.now}; this.#incidents.set(id,freezeClone(incident)); for(const aid of incident.alertIds){ const a=this.#alerts.get(aid); if(a)this.#alerts.set(aid,freezeClone({...a,status:AlertStatus.ConvertedToIncident})); } this.#timers.push(freezeClone({incidentId:id,type:IncidentTimerType.Acknowledgement,startedAt:input.now,deadlineAt:input.now+(input.severity===IncidentSeverity.Sev1?30000:input.severity===IncidentSeverity.Sev0?0:300000),status:IncidentTimerStatus.Running})); this.#audit.push(`incident.created:${id}`); if(input.runbookId)this.startRunbook(input.runbookId,id,input.createdBy,input.now); return clone(incident); }
  acknowledge(incidentId:string, identityId:string, now:number, note=''):OperationalIncident{ assertIdentity(identityId); const i=this.#requireIncident(incidentId); const next={...i,status:IncidentStatus.Acknowledged,acknowledgedAt:now,ownerId:i.ownerId??identityId,updatedAt:now}; this.#incidents.set(incidentId,freezeClone(next)); this.#completeTimer(incidentId,IncidentTimerType.Acknowledgement,now); this.#audit.push(`incident.acknowledged:${incidentId}:${identityId}:${redact(note)}`); return clone(next); }
  assign(input:IncidentAssignment):IncidentAssignment{ assertIdentity(input.identityId); this.#assignments.push(freezeClone(input)); const i=this.#requireIncident(input.incidentId); this.#incidents.set(i.id,freezeClone({...i,ownerId:i.ownerId??input.identityId,commanderId:input.role===IncidentResponseRole.IncidentCommander?input.identityId:i.commanderId,updatedAt:input.assignedAt})); this.#audit.push(`incident.assigned:${input.incidentId}:${input.role}:${input.identityId}`); return clone(input); }
  changeSeverity(incidentId:string,severity:IncidentSeverity,identityId:string,reason:string,now:number):OperationalIncident{ assertIdentity(identityId); if(!reason.trim()) throw new Error('severity change reason is required'); const i=this.#requireIncident(incidentId); const next={...i,severity,updatedAt:now,tags:[...new Set([...i.tags,...(sevRank[severity]<=1?['major-incident']:[])])]}; this.#incidents.set(incidentId,freezeClone(next)); this.#audit.push(`incident.severity_changed:${incidentId}:${identityId}:${redact(reason)}`); return clone(next); }
  registerEscalationPolicy(policy:EscalationPolicy):void{ this.#policies.set(policy.id,freezeClone({...policy,steps:[...policy.steps].sort((a,b)=>a.order-b.order)})); }
  evaluateEscalations(now:number):EscalationEvent[]{ for(const incident of this.#incidents.values()){ if([IncidentStatus.Resolved,IncidentStatus.Closed].includes(incident.status)) continue; for(const policy of this.#policies.values()){ if(!policy.enabled||policy.severity!==incident.severity) continue; for(const step of policy.steps){ if(now-incident.declaredAt<step.afterMs) continue; if(this.#escalations.some(e=>e.incidentId===incident.id&&e.policyId===policy.id&&e.stepOrder===step.order)) continue; const conditionOk=step.condition==='no_acknowledgement'?!incident.acknowledgedAt:step.condition==='no_owner'?!incident.ownerId:true; if(!conditionOk) continue; const event={id:`escalation-${this.#escalations.length+1}`,incidentId:incident.id,policyId:policy.id,stepOrder:step.order,triggeredAt:now,targets:[...(step.targetIdentityIds??[]),...(step.targetRoleIds??[])],channels:step.channels,acknowledged:false}; this.#escalations.push(freezeClone(event)); this.#audit.push(`incident.escalated:${incident.id}:${step.order}`); } } } return this.#escalations.map(clone); }
  suppressEscalation(eventId:string,identityId:string,until:number,reason:string):EscalationEvent{ assertIdentity(identityId); if(until<=0||!reason.trim()) throw new Error('temporary suppression with reason is required'); const e=this.#escalations.find(e=>e.id===eventId); if(!e) throw new Error(`unknown escalation: ${eventId}`); const next={...e,suppressed:true}; Object.assign(e,next); this.#audit.push(`escalation.suppressed:${eventId}:${identityId}:${until}:${redact(reason)}`); return clone(next); }
  registerRunbook(runbook:OperationalRunbook):void{ if(![RunbookStatus.Approved,RunbookStatus.Active].includes(runbook.status)) throw new Error('only approved or active runbooks can be registered for live use'); this.#runbooks.set(runbook.id,freezeClone({...runbook,steps:[...runbook.steps].sort((a,b)=>a.order-b.order)})); }
  startRunbook(runbookId:string,incidentId:string,identityId:string,now:number):RunbookExecution{ assertIdentity(identityId); const rb=this.#runbooks.get(runbookId); if(!rb) throw new Error(`unknown runbook: ${runbookId}`); const incident=this.#requireIncident(incidentId); if(rb.minimumSeverity&&sevRank[incident.severity]>sevRank[rb.minimumSeverity]) throw new Error('incident severity is below runbook minimum'); const execution:RunbookExecution={id:`runbook-execution-${this.#executions.size+1}`,runbookId,runbookVersion:rb.version,incidentId,status:RunbookExecutionStatus.Running,startedAt:now,startedBy:identityId,currentStepId:rb.steps[0]?.id,stepExecutions:rb.steps.map(s=>({stepId:s.id,status:s.id===rb.steps[0]?.id?'running':'pending',startedAt:s.id===rb.steps[0]?.id?now:undefined}))}; this.#executions.set(execution.id,freezeClone(execution)); this.#incidents.set(incidentId,freezeClone({...incident,runbookExecutionIds:[...incident.runbookExecutionIds,execution.id],updatedAt:now})); this.#audit.push(`runbook.started:${execution.id}`); return clone(execution); }
  completeRunbookStep(executionId:string,stepId:string,result:string,identityId:string,now:number):RunbookExecution{ assertIdentity(identityId); const ex=this.#executions.get(executionId); if(!ex) throw new Error(`unknown execution: ${executionId}`); if(ex.currentStepId!==stepId) throw new Error('step is not current'); const rb=this.#runbooks.get(ex.runbookId)!; const steps=ex.stepExecutions.map(s=>s.stepId===stepId?{...s,status:'completed' as const,completedAt:now,result:String(redact(result))}:s); const idx=rb.steps.findIndex(s=>s.id===stepId); const nextStep=rb.steps[idx+1]; const completed=!nextStep; const next:RunbookExecution={...ex,status:completed?RunbookExecutionStatus.Completed:RunbookExecutionStatus.Running,currentStepId:nextStep?.id,stepExecutions:steps.map(s=>s.stepId===nextStep?.id?{...s,status:'running',startedAt:now}:s),completedAt:completed?now:undefined}; this.#executions.set(executionId,freezeClone(next)); this.#audit.push(`runbook.step_completed:${executionId}:${stepId}`); return clone(next); }
  publishStatus(update:StatusUpdate):StatusUpdate{ this.#updates.push(freezeClone({...update,message:String(redact(update.message))})); this.#audit.push(`status.published:${update.incidentId}:${update.audience}`); return clone(update); }
  stabilize(incidentId:string,identityId:string,now:number):OperationalIncident{ assertIdentity(identityId); const i=this.#requireIncident(incidentId); const next={...i,status:IncidentStatus.Stabilized,stabilizedAt:now,updatedAt:now}; this.#incidents.set(incidentId,freezeClone(next)); this.#audit.push(`incident.stabilized:${incidentId}:${identityId}`); return clone(next); }
  resolve(incidentId:string,identityId:string,now:number,checks:ValidationCheck[],overrideReason?:string):OperationalIncident{ assertIdentity(identityId); if(!checks.every(c=>c.passed)&&!overrideReason) throw new Error('incident resolution requires passing validation checks or authorized override reason'); const i=this.#requireIncident(incidentId); const next={...i,status:IncidentStatus.Resolved,resolvedAt:now,updatedAt:now}; this.#incidents.set(incidentId,freezeClone(next)); this.#audit.push(`incident.resolved:${incidentId}:${identityId}:${redact(overrideReason??'validated')}`); if(sevRank[i.severity]<=1)this.createReview(incidentId,identityId,now); return clone(next); }
  close(incidentId:string,identityId:string,now:number):OperationalIncident{ assertIdentity(identityId); const i=this.#requireIncident(incidentId); if(i.status!==IncidentStatus.Resolved) throw new Error('only resolved incidents can be closed'); const review=[...this.#reviews.values()].find(r=>r.incidentId===incidentId); if(sevRank[i.severity]<=1&&review?.status!==ReviewStatus.Completed) throw new Error('severe incidents require completed review before closure'); const next={...i,status:IncidentStatus.Closed,closedAt:now,updatedAt:now}; this.#incidents.set(incidentId,freezeClone(next)); this.#audit.push(`incident.closed:${incidentId}:${identityId}`); return clone(next); }
  reopen(incidentId:string,identityId:string,reason:string,now:number):OperationalIncident{ assertIdentity(identityId); if(!reason.trim()) throw new Error('reopen reason is required'); const i=this.#requireIncident(incidentId); const next={...i,status:IncidentStatus.Reopened,resolvedAt:undefined,closedAt:undefined,updatedAt:now,tags:[...new Set([...i.tags,'reopened'])]}; this.#incidents.set(incidentId,freezeClone(next)); this.#audit.push(`incident.reopened:${incidentId}:${identityId}:${redact(reason)}`); return clone(next); }
  createReview(incidentId:string,ownerId:string,now:number):PostIncidentReview{ const existing=[...this.#reviews.values()].find(r=>r.incidentId===incidentId); if(existing)return clone(existing); const review:PostIncidentReview={id:`review-${this.#reviews.size+1}`,incidentId,ownerId,scheduledAt:now,status:ReviewStatus.Required,contributingFactors:[],whatWentWell:[],whatWentPoorly:[],correctiveActions:[]}; this.#reviews.set(review.id,freezeClone(review)); this.#audit.push(`review.created:${review.id}`); return clone(review); }
  completeReview(review:PostIncidentReview):PostIncidentReview{ if(review.rootCause?.classification==='confirmed'&&review.rootCause.evidenceRecordIds.length===0) throw new Error('confirmed root cause requires evidence'); const next={...review,status:ReviewStatus.Completed,completedAt:review.completedAt??Date.now()}; this.#reviews.set(review.id,freezeClone(next)); this.#audit.push(`review.completed:${review.id}`); return clone(next); }
  metrics(incidentId:string):IncidentMetrics{ const i=this.#requireIncident(incidentId); const responders=new Set(this.#assignments.filter(a=>a.incidentId===incidentId).map(a=>a.identityId)); const executions=[...this.#executions.values()].filter(e=>e.incidentId===incidentId); return {incidentId,timeToDetectMs:i.declaredAt-i.detectedAt,timeToAcknowledgeMs:i.acknowledgedAt?i.acknowledgedAt-i.declaredAt:undefined,timeToAssignMs:this.#assignments.find(a=>a.incidentId===incidentId)?.assignedAt!==undefined?this.#assignments.find(a=>a.incidentId===incidentId)!.assignedAt-i.declaredAt:undefined,timeToStabilizeMs:i.stabilizedAt?i.stabilizedAt-i.declaredAt:undefined,timeToResolveMs:i.resolvedAt?i.resolvedAt-i.declaredAt:undefined,escalationCount:this.#escalations.filter(e=>e.incidentId===incidentId).length,responderCount:responders.size,runbookStepsCompleted:executions.flatMap(e=>e.stepExecutions).filter(s=>s.status==='completed').length,automatedActions:0,manualActions:0,reopened:i.tags.includes('reopened')}; }
  snapshot():IncidentResponseSnapshot{ return clone({alerts:[...this.#alerts.values()],incidents:[...this.#incidents.values()],assignments:this.#assignments,timers:this.#timers,escalations:this.#escalations,runbooks:[...this.#runbooks.values()],executions:[...this.#executions.values()],statusUpdates:this.#updates,reviews:[...this.#reviews.values()],audit:this.#audit.slice(-this.maxRecords)}); }
  #requireIncident(id:string):OperationalIncident{ const i=this.#incidents.get(id); if(!i) throw new Error(`unknown incident: ${id}`); return clone(i); }
  #completeTimer(incidentId:string,type:IncidentTimerType,now:number):void{ this.#timers=this.#timers.map(t=>t.incidentId===incidentId&&t.type===type&&t.status===IncidentTimerStatus.Running?freezeClone({...t,status:IncidentTimerStatus.Completed,completedAt:now}):t); }
}
