export enum MetricType { Counter='counter', Gauge='gauge', Histogram='histogram', Summary='summary', Rate='rate', Duration='duration', State='state' }
export enum HealthStatus { Healthy='healthy', Warning='warning', Degraded='degraded', Critical='critical', Unavailable='unavailable', Unknown='unknown' }
export enum LogLevel { Trace='trace', Debug='debug', Info='info', Notice='notice', Warning='warning', Error='error', Critical='critical' }
export enum TraceSpanStatus { Unset='unset', Success='success', Error='error', Cancelled='cancelled', TimedOut='timed_out' }
export enum AlertSeverity { Info='info', Warning='warning', Major='major', Critical='critical', Emergency='emergency' }
export enum AlertState { Pending='pending', Firing='firing', Acknowledged='acknowledged', Suppressed='suppressed', Resolved='resolved', Expired='expired' }
export type CollectionMode = 'push'|'pull'|'event-derived'|'state-derived'|'sampled';
export type TelemetryPriority = 'critical'|'high'|'normal'|'low';
export interface MetricDefinition { name:string; description:string; type:MetricType; unit:string; labels:string[]; collectionIntervalMs?:number; retentionClass:string; }
export interface MetricRegistryEntry { definition:MetricDefinition; ownerService:string; enabled:boolean; deprecated?:boolean; replacementMetric?:string; collectionMode?:CollectionMode; }
export interface MetricSample { metricName:string; timestamp:number; value:number; labels:Record<string,string>; sourceNodeId?:string; productionId?:string; workspaceId?:string; priority?:TelemetryPriority; }
export interface MetricQuery { metricName:string; since?:number; until?:number; labels?:Record<string,string>; }
export interface AggregateResult { metricName:string; count:number; minimum:number; maximum:number; sum:number; average:number; p50:number; p90:number; p95:number; p99:number; last:number; }
export interface HealthReason { code:string; message:string; severity:string; metricName?:string; currentValue?:number; threshold?:number; firstObservedAt:number; lastObservedAt:number; }
export interface HealthState { componentId:string; status:HealthStatus; score:number; reasons:HealthReason[]; updatedAt:number; confidence:number; dependencies?:string[]; }
export interface ProgramHealth { videoPresent:boolean; audioPresent:boolean; videoScore:number; audioScore:number; synchronizationScore:number; continuityScore:number; overallScore:number; issues:string[]; }
export interface TelemetryEvent { id:string; timestamp:number; type:string; service:string; priority:TelemetryPriority; attributes:Record<string,unknown>; productionId?:string; traceId?:string; }
export interface LogEvent { id:string; timestamp:number; level:LogLevel; service:string; component?:string; message:string; productionId?:string; nodeId?:string; traceId?:string; correlationId?:string; commandId?:string; attributes?:Record<string,unknown>; }
export interface TraceContext { traceId:string; spanId:string; parentSpanId?:string; sampled:boolean; baggage?:Record<string,string>; }
export interface TraceSpanEvent { name:string; timestamp:number; attributes?:Record<string,unknown>; }
export interface TraceSpan { traceId:string; spanId:string; parentSpanId?:string; name:string; service:string; startedAt:number; endedAt?:number; status:TraceSpanStatus; attributes:Record<string,unknown>; events?:TraceSpanEvent[]; }
export interface AlertExpression { metricName:string; operator:'>'|'>='|'<'|'<='|'=='|'!='; threshold:number; labelMatchers?:Record<string,string>; }
export interface AlertRule { id:string; name:string; expression:AlertExpression; severity:AlertSeverity; evaluationWindowMs:number; requiredDurationMs?:number; cooldownMs?:number; labels?:Record<string,string>; notificationPolicyId?:string; enabled:boolean; }
export interface AlertInstance { id:string; ruleId:string; state:AlertState; severity:AlertSeverity; firstObservedAt:number; lastObservedAt:number; message:string; acknowledgedBy?:string; acknowledgementNote?:string; suppressedUntil?:number; recommendedAction?:string; }
export interface MaintenanceWindow { id:string; startsAt:number; endsAt:number; scopes:string[]; reason:string; suppressAlerts:boolean; createdBy:string; }
export interface AnomalyResult { metricName:string; timestamp:number; expectedRange:{minimum:number; maximum:number}; actualValue:number; anomalyScore:number; confidence:number; modelVersion:string; mode:'observe'|'recommend'; }
export interface ServiceLevelObjective { id:string; name:string; indicator:string; target:number; comparison:'>='|'<='; windowMs:number; errorBudgetPolicy?:string; }
export interface SLOResult { objectiveId:string; actual:number; target:number; violated:boolean; errorBudgetRemaining:number; burnRate:number; }
export interface CapacityState { resourceId:string; used:number; available:number; reserved:number; utilizationPercent:number; warningThreshold:number; criticalThreshold:number; predictedExhaustionAt?:number; }
export interface DiagnosticFinding { code:string; severity:AlertSeverity; evidence:string[]; }
export interface DiagnosticResult { id:string; target:string; startedAt:number; completedAt:number; status:'passed'|'warning'|'failed'|'unknown'; findings:DiagnosticFinding[]; recommendedActions:string[]; }
const SECRET=/password|secret|token|key|credential|certificate|authorization|bearer|streamKey/i;
const ALLOWED_LABELS=new Set(['production_id','node_id','service','output_type','destination_type','status','severity','component','site','environment']);
export function redact(value:unknown):unknown{ if(Array.isArray(value)) return value.map(redact); if(value&&typeof value==='object'){ const out:Record<string,unknown>={}; for(const [k,v] of Object.entries(value)) out[k]=SECRET.test(k)?'[REDACTED]':redact(v); return Object.freeze(out);} if(typeof value==='string'&&SECRET.test(value)) return '[REDACTED]'; return value; }
function stableLabels(labels:Record<string,string>):Record<string,string>{ const out:Record<string,string>={}; for(const k of Object.keys(labels).sort()){ if(!ALLOWED_LABELS.has(k)) throw new Error(`unapproved metric label: ${k}`); out[k]=String(redact(labels[k])); } return Object.freeze(out); }
function clone<T>(v:T):T { return structuredClone(v); }
export class MetricRegistry{ #entries=new Map<string,MetricRegistryEntry>(); register(entry:MetricRegistryEntry):void{ if(this.#entries.has(entry.definition.name)) throw new Error(`metric already registered: ${entry.definition.name}`); for(const label of entry.definition.labels) if(!ALLOWED_LABELS.has(label)) throw new Error(`unapproved metric label: ${label}`); this.#entries.set(entry.definition.name, Object.freeze(clone(entry))); } get(name:string){ const e=this.#entries.get(name); return e?clone(e):undefined;} list(){ return [...this.#entries.values()].map(clone).sort((a,b)=>a.definition.name.localeCompare(b.definition.name)); }}
export class MetricStore{ #samples:MetricSample[]=[]; constructor(private readonly maxSamples=10000){} record(sample:MetricSample):void{ this.#samples.push(Object.freeze({...sample, labels:stableLabels(sample.labels)})); if(this.#samples.length>this.maxSamples) this.#samples.splice(0,this.#samples.length-this.maxSamples); } query(q:MetricQuery):MetricSample[]{ return this.#samples.filter(s=>s.metricName===q.metricName && (q.since===undefined||s.timestamp>=q.since) && (q.until===undefined||s.timestamp<=q.until) && (!q.labels||Object.entries(q.labels).every(([k,v])=>s.labels[k]===v))).map(clone); }}
export function aggregate(metricName:string, samples:MetricSample[]):AggregateResult{ const values=samples.filter(s=>s.metricName===metricName).map(s=>s.value).sort((a,b)=>a-b); if(values.length===0) return {metricName,count:0,minimum:0,maximum:0,sum:0,average:0,p50:0,p90:0,p95:0,p99:0,last:0}; const pct=(p:number)=>values[Math.min(values.length-1,Math.floor((values.length-1)*p))] ?? 0; const sum=values.reduce((a,b)=>a+b,0); return {metricName,count:values.length,minimum:values[0]??0,maximum:values.at(-1)??0,sum,average:sum/values.length,p50:pct(.5),p90:pct(.9),p95:pct(.95),p99:pct(.99),last:samples.filter(s=>s.metricName===metricName).at(-1)?.value??0}; }
export class HealthRegistry{ #states=new Map<string,HealthState>(); update(state:HealthState):void{ const score=Math.max(0,Math.min(100,state.score)); const status=score===0?HealthStatus.Unavailable:state.confidence<0.5?HealthStatus.Unknown:score>=100?HealthStatus.Healthy:score>=80?HealthStatus.Warning:score>=60?HealthStatus.Degraded:HealthStatus.Critical; this.#states.set(state.componentId,Object.freeze({...clone(state),score,status,reasons:state.reasons.map(clone)})); } get(id:string){return this.#states.has(id)?clone(this.#states.get(id)!):{componentId:id,status:HealthStatus.Unknown,score:0,reasons:[],updatedAt:0,confidence:0};} rollup(componentId:string, childIds:string[], updatedAt:number):HealthState{ const children=childIds.map(id=>this.get(id)); if(children.length===0) return this.get(componentId); const critical=children.some(c=>[HealthStatus.Critical,HealthStatus.Unavailable,HealthStatus.Unknown].includes(c.status)); const score=Math.min(...children.map(c=>c.score)); const confidence=Math.min(...children.map(c=>c.confidence)); const state={componentId,status:critical?HealthStatus.Critical:score>=80?HealthStatus.Warning:HealthStatus.Degraded,score,reasons:children.flatMap(c=>c.reasons),updatedAt,confidence,dependencies:childIds}; this.update(state); return this.get(componentId); }}
export class LogWriter{ #events:LogEvent[]=[]; constructor(private readonly maxEvents=5000){} write(event:LogEvent):void{ this.#events.push(Object.freeze({...event, message:String(redact(event.message)), attributes:redact(event.attributes??{}) as Record<string,unknown>})); if(this.#events.length>this.maxEvents) this.#events.shift(); } query(filter:Partial<Pick<LogEvent,'service'|'level'|'traceId'|'correlationId'>>={}):LogEvent[]{ return this.#events.filter(e=>Object.entries(filter).every(([k,v])=>e[k as keyof LogEvent]===v)).map(clone); }}
export class TraceCollector{ #spans=new Map<string,TraceSpan>(); startSpan(input:Omit<TraceSpan,'spanId'|'status'|'attributes'> & {spanId?:string; attributes?:Record<string,unknown>}):TraceSpan{ const span={...input,spanId:input.spanId??`${input.traceId}-${this.#spans.size+1}`,status:TraceSpanStatus.Unset,attributes:redact(input.attributes??{}) as Record<string,unknown>}; this.#spans.set(span.spanId,Object.freeze(span)); return clone(span);} endSpan(spanId:string,status:TraceSpanStatus,endedAt:number):TraceSpan{ const span=this.#spans.get(spanId); if(!span) throw new Error(`unknown span: ${spanId}`); const next={...span,status,endedAt}; this.#spans.set(spanId,Object.freeze(next)); return clone(next);} get(traceId:string){return [...this.#spans.values()].filter(s=>s.traceId===traceId).map(clone).sort((a,b)=>a.startedAt-b.startedAt);}}
export class AlertEngine{ #rules=new Map<string,AlertRule>(); #alerts=new Map<string,AlertInstance>(); #suppression:MaintenanceWindow[]=[]; registerRule(rule:AlertRule){this.#rules.set(rule.id,Object.freeze(clone(rule)));} suppress(window:MaintenanceWindow){this.#suppression.push(Object.freeze(clone(window)));} evaluate(now:number, store:MetricStore):AlertInstance[]{ for(const rule of this.#rules.values()){ if(!rule.enabled) continue; const q=store.query({metricName:rule.expression.metricName,since:now-rule.evaluationWindowMs,labels:rule.expression.labelMatchers}); const last=q.at(-1); if(!last) continue; const active=this.#compare(last.value,rule.expression.operator,rule.expression.threshold); const id=`alert:${rule.id}`; const existing=this.#alerts.get(id); const suppressed=this.#suppression.some(w=>w.suppressAlerts&&w.startsAt<=now&&w.endsAt>=now); if(active){ const first=existing?.firstObservedAt??now; const requiredMet=now-first>=(rule.requiredDurationMs??0); this.#alerts.set(id,{id,ruleId:rule.id,state:suppressed?AlertState.Suppressed:requiredMet?AlertState.Firing:AlertState.Pending,severity:rule.severity,firstObservedAt:first,lastObservedAt:now,message:`${rule.name}: ${last.value} ${rule.expression.operator} ${rule.expression.threshold}`,recommendedAction:'Inspect affected component, verify dependencies, and follow the configured runbook.'}); } else if(existing) this.#alerts.set(id,{...existing,state:AlertState.Resolved,lastObservedAt:now}); } return [...this.#alerts.values()].map(clone); } acknowledge(alertId:string, operator:string, note:string){ const a=this.#alerts.get(alertId); if(!a) throw new Error(`unknown alert: ${alertId}`); this.#alerts.set(alertId,{...a,state:AlertState.Acknowledged,acknowledgedBy:operator,acknowledgementNote:String(redact(note))}); } #compare(v:number,op:AlertExpression['operator'],t:number){ return op==='>'?v>t:op==='>='?v>=t:op==='<'?v<t:op==='<='?v<=t:op==='=='?v===t:v!==t; }}
export function detectAnomaly(metricName:string,samples:MetricSample[],actualValue:number,timestamp:number):AnomalyResult{ const agg=aggregate(metricName,samples); const spread=Math.max(1,(agg.maximum-agg.minimum)||Math.abs(agg.average*.1)); const min=agg.average-spread*2; const max=agg.average+spread*2; const outside=actualValue<min||actualValue>max; return {metricName,timestamp,expectedRange:{minimum:min,maximum:max},actualValue,anomalyScore:outside?Math.min(1,Math.abs(actualValue-agg.average)/(spread*3)):0,confidence:agg.count>=3?.8:.3,modelVersion:'ubos-static-baseline-v1',mode:'observe'}; }
export function evaluateSLO(slo:ServiceLevelObjective, result:AggregateResult):SLOResult{ const actual=result.average; const violated=slo.comparison==='>='?actual<slo.target:actual>slo.target; const errorBudget=Math.max(0,100-Math.abs(slo.target-actual)); return {objectiveId:slo.id,actual,target:slo.target,violated,errorBudgetRemaining:errorBudget,burnRate:violated?Math.max(1,Math.abs(slo.target-actual)):0}; }
export function evaluateCapacity(state:CapacityState):AlertSeverity|undefined{ if(state.utilizationPercent>=state.criticalThreshold) return AlertSeverity.Critical; if(state.utilizationPercent>=state.warningThreshold) return AlertSeverity.Warning; return undefined; }
export function diagnose(target:string, health:HealthState[], alerts:AlertInstance[], startedAt:number):DiagnosticResult{ const findings:DiagnosticFinding[]=[]; for(const h of health.filter(h=>h.componentId.includes(target)||h.dependencies?.includes(target))) if(h.status!==HealthStatus.Healthy) findings.push({code:`health.${h.status}`,severity:h.status===HealthStatus.Critical?AlertSeverity.Critical:AlertSeverity.Warning,evidence:h.reasons.map(r=>r.message)}); for(const a of alerts.filter(a=>a.state===AlertState.Firing)) findings.push({code:`alert.${a.ruleId}`,severity:a.severity,evidence:[a.message]}); return {id:`diag:${target}:${startedAt}`,target,startedAt,completedAt:startedAt+1,status:findings.some(f=>f.severity===AlertSeverity.Critical)?'failed':findings.length?'warning':'passed',findings,recommendedActions:findings.length?['Review root cause evidence, confirm live output impact, and execute the approved runbook.']:['No action required.']}; }
