export type WorkspaceId = 'director'|'solo-streamer'|'technical-director'|'audio-engineer'|'graphics-operator'|'replay-operator'|'streaming-operator'|'monitor-wall'|'compact';
export type Binding = { status: 'unwired'|'prototype'|'read-only'|'planned'; domain: string; futureCommand?: string; futureSelector?: string; permission?: string; safety: 'informational'|'reversible'|'live-impacting'|'destructive'|'emergency' };
export type WorkspaceDefinition = { id: WorkspaceId; name: string; role: string; mission: string; layout: string; panels: string[]; commands: { id: string; label: string; binding: Binding }[]; responsive: string; accessibility: string; version: 1 };
const prototype = (id:string,label:string,domain:string,safety:Binding['safety']='live-impacting') => ({id,label,binding:{status:'unwired' as const,domain,futureCommand:id,permission:`${domain}.operate`,safety}});
export const domains=['Production','Sources','Production Scenes','Audio','Graphics','Replay','Guests','Social Fabric','Distribution','Recording','Automation','Monitoring','Assets','Settings'];
export const workspaces: WorkspaceDefinition[] = [
 {id:'director',name:'Director',role:'Show caller',mission:'Call the show, pace the rundown, and supervise readiness.',layout:'dual-confidence + scene runway + cue deck',panels:['preview','program','transition-deck','production-scenes','rundown','next-actions','readiness'],commands:[prototype('transition.cut','CUT','production-graph'),prototype('transition.auto','AUTO','production-graph'),prototype('transition.take','TAKE','production-graph'),prototype('transition.ftb','Fade to Black','production-graph','emergency')],responsive:'Cue deck collapses below confidence surfaces.',accessibility:'Landmarked show calling console with named prototype controls.',version:1},
 {id:'solo-streamer',name:'Solo Streamer',role:'Creator operator',mission:'Produce, engage, and distribute from one focused console.',layout:'program-led studio + engagement rail + quick actions',panels:['program','preview','quick-scenes','unified-chat','engagement','guest-ready','stream-health'],commands:[prototype('scene.prepare','Prepare scene','production-graph'),prototype('clip.marker','Mark clip','recording'),prototype('cross-follow.prompt','Cross Follow','social-fabric')],responsive:'Engagement becomes a drawer while quick actions remain visible.',accessibility:'Compact operator flow with labelled chat and health updates.',version:1},
 {id:'technical-director',name:'Technical Director',role:'Signal supervisor',mission:'Supervise switching integrity, routing, sync, and failover.',layout:'dual-confidence + signal matrix + technical inspector',panels:['preview','program','source-matrix','input-routing','keyers','sync','diagnostics'],commands:[prototype('routing.apply','Apply route','media-runtime'),prototype('failover.arm','Arm failover','media-runtime','emergency')],responsive:'Diagnostics move below the signal matrix.',accessibility:'Matrix headers and diagnostics are announced structurally.',version:1},
 {id:'audio-engineer',name:'Audio Engineer',role:'Audio mixer',mission:'Mix, protect, and monitor production sound.',layout:'mixer-first + compact confidence monitors',panels:['audio-mixer','buses','master-loudness','talkback','remote-audio','preview','program'],commands:[prototype('audio.mute','Mute channel','audio'),prototype('audio.solo','Solo channel','audio'),prototype('audio.route','Route bus','audio')],responsive:'Channel strips horizontally scroll within a labelled mixer region.',accessibility:'Meter values include text values; color is supplemental.',version:1},
 {id:'graphics-operator',name:'Graphics Operator',role:'Graphics playout',mission:'Prepare branded graphics, validate fields, and manage safe overlays.',layout:'graphics-preview + template browser + queue',panels:['preview','program','graphics-preview','template-browser','graphics-queue','safe-area','brand-kit'],commands:[prototype('graphics.take','Take graphic','graphics'),prototype('graphics.clear','Clear graphic','graphics')],responsive:'Template browser becomes an inspector drawer.',accessibility:'Required field warnings are explicit text.',version:1},
 {id:'replay-operator',name:'Replay Operator',role:'Replay producer',mission:'Mark moments, build replay sequences, and return safely to live.',layout:'replay-monitor bank + timeline + highlight queue',panels:['program','preview','replay-sources','selected-replay','clip-timeline','clip-bin','highlights'],commands:[prototype('replay.cue','Cue replay','replay'),prototype('replay.take','Take replay','replay'),prototype('replay.return-live','Return live','replay')],responsive:'Source bank becomes a selectable compact strip.',accessibility:'Transport metadata is named and never executes.',version:1},
 {id:'streaming-operator',name:'Streaming Operator',role:'Distribution supervisor',mission:'Protect destination delivery, recording, and output health.',layout:'output confidence + destination matrix + delivery telemetry',panels:['program','preview','destination-matrix','encoder-health','recording','network','audience'],commands:[prototype('distribution.reconnect','Reconnect destination','distribution'),prototype('recording.start','Start recording','recording')],responsive:'Destination cards stack by urgency.',accessibility:'Each destination exposes a textual state and profile.',version:1},
 {id:'monitor-wall',name:'Monitor Wall',role:'Operations monitor',mission:'Maintain broad situational awareness across every confidence surface.',layout:'priority multiview 4×4 + alert ribbon',panels:['multiview-grid','alerts','audio-confidence','destinations','network','recording'],commands:[prototype('monitor.layout','Change multiview layout','media-runtime','reversible')],responsive:'Grid moves from 4×4 to 3×3 to 2×2 without obscuring tallies.',accessibility:'Every tile has an accessible source, tally, and status label.',version:1},
 {id:'compact',name:'Compact',role:'Mobile control',mission:'Keep essential confidence and preparation actions reachable on constrained displays.',layout:'compact dual confidence + essentials + tool drawer',panels:['preview','program','scene-quick-switcher','transition-essentials','audio-confidence','destination-health'],commands:[prototype('transition.take','TAKE','production-graph'),prototype('drawer.open','Open tools','presentation','reversible')],responsive:'Tools remain in an explicit drawer; essential status never hides.',accessibility:'Large targets and keyboard order prioritize confidence and warnings.',version:1}
];
export const workspaceById=Object.fromEntries(workspaces.map(workspace=>[workspace.id,workspace])) as Record<WorkspaceId,WorkspaceDefinition>;
/** Server-safe route validation for the isolated presentation lab. */
export const isPrototypeWorkspace=(value:string):value is WorkspaceId=>value in workspaceById;
export const fixtures=[
 {id:'healthy',label:'Healthy interview',note:'Demonstration data · Host + guest · outputs healthy',warning:''},
 {id:'destination-warning',label:'Destination warning',note:'Demonstration data · TikTok degraded · Instagram reconnecting',warning:'Destination attention: TikTok packet loss; Instagram reconnecting.'},
 {id:'guest-warning',label:'Guest readiness',note:'Demonstration data · Guest 2 waiting · return audio unavailable',warning:'Guest readiness: Jordan has no return audio.'},
 {id:'graphics-warning',label:'Graphics not ready',note:'Demonstration data · Lower third missing required name',warning:'Graphics readiness: lower third requires a speaker name.'},
 {id:'replay-prepared',label:'Replay prepared',note:'Demonstration data · 12 second clip · 50% speed · queued',warning:''},
 {id:'vertical',label:'Vertical production',note:'Demonstration data · TikTok 9:16 · YouTube 16:9',warning:''}
] as const;
