'use client';
import { useState } from 'react';
import { fixtures, workspaceById, type WorkspaceId } from './metadata';
const scenes=[['Interview','PROGRAM','Host + Maya · 2 sources'],['Audience Q&A','PREVIEW','Questions queued · graphics ready'],['Sponsor break','STANDBY','00:30 · platform variants'],['Closing','READY','1 source · end card']];
const channels=['Host','Maya','Music','Remote 2','Playback','Master'];
const destinations=[['YouTube','16:9','Healthy'],['Facebook','16:9','Healthy'],['TikTok','9:16','Degraded'],['Instagram','9:16','Reconnecting'],['LinkedIn','16:9','Ready']];
function Panel({title,children,kind='' }:{title:string;children:React.ReactNode;kind?:string}){return <section className={`next-panel ${kind}`}><header><h2>{title}</h2><span>Metadata only</span></header>{children}</section>}
function Monitor({kind,vertical=false}:{kind:'PROGRAM'|'PREVIEW';vertical?:boolean}){return <section className={`monitor ${kind.toLowerCase()} ${vertical?'vertical':''}`} aria-label={`${kind} confidence surface; media runtime wiring pending`}><div className="monitor-art"><div className="safe-frame"><span>{vertical?'9:16':'16:9'}</span></div><div className="lower-third">THE NEXT CHAPTER <small>LIVE EXPERIENCE FORUM</small></div></div><footer><b>{kind === 'PROGRAM' ? '● PROGRAM' : '◇ PREVIEW'}</b><span>{kind === 'PROGRAM'?'Interview — Host / Maya':'Audience Q&A — 02:30'}</span><small>Media wiring pending · 1080p59.94</small></footer></section>}
export function PrototypeWorkspaceView({workspaceId}:{workspaceId:WorkspaceId}){
 const workspace=workspaceById[workspaceId]; const [fixture,setFixture]=useState('healthy'); const [notice,setNotice]=useState(''); const active=fixtures.find(item=>item.id===fixture)??fixtures[0]; const vertical=fixture==='vertical';
 const action=(label:string)=>setNotice(`${label}: Prototype only — runtime command binding is scheduled for the next milestone.`);
 const audio=workspaceId==='audio-engineer', wall=workspaceId==='monitor-wall', streaming=workspaceId==='streaming-operator', graphics=workspaceId==='graphics-operator', replay=workspaceId==='replay-operator', technical=workspaceId==='technical-director', solo=workspaceId==='solo-streamer', compact=workspaceId==='compact';
 return <main className={`next-workspace workspace-${workspaceId}`}><div className="workspace-heading"><div><p>BUILT-IN WORKSPACE · PRESENTATION PROTOTYPE</p><h1>{workspace.name}</h1><span>{workspace.mission}</span></div><label>Scenario <select value={fixture} onChange={event=>setFixture(event.target.value)} aria-label="Demonstration fixture scenario">{fixtures.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div>
 {active.warning&&<div className="warning" role="status"><b>Attention</b><span>{active.warning}</span><small>Demonstration data</small></div>}
 {notice&&<div className="prototype-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss prototype notice">×</button></div>}
 {wall ? <MonitorWall vertical={vertical}/> : audio ? <AudioWorkspace action={action}/> : <><div className={`confidence ${solo?'solo-confidence':''}`}><Monitor kind="PREVIEW" vertical={vertical}/><Monitor kind="PROGRAM" vertical={vertical}/></div><div className="workspace-grid"><section className="primary-stack">{technical?<Technical/>:graphics?<Graphics action={action}/>:replay?<Replay action={action}/>:streaming?<Streaming/>:compact?<Compact action={action}/>:solo?<Solo/>:<Director action={action}/>}</section><aside className="context-rail"><Panel title={workspaceId==='director'?'Show readiness':'Context & readiness'}><ul className="readiness"><li><b>Guests</b><span>Host and Maya ready</span></li><li><b>Graphics</b><span>{fixture==='graphics-warning'?'1 field required':'Brand kit loaded'}</span></li><li><b>Destinations</b><span>{fixture==='destination-warning'?'2 need attention':'5 profiles ready'}</span></li><li><b>Recording</b><span>Active · 1h 42m capacity</span></li></ul></Panel><Panel title="Binding inspector"><p className="metadata-copy">All visible controls are intentionally unwired. Future owner metadata: <b>Production Graph / Media Runtime / Social Fabric</b>.</p></Panel></aside></div></>}
 </main>
}
function Director({action}:{action:(label:string)=>void}){return <><Panel title="Production scenes"><div className="scene-runway">{scenes.map(([name,state,detail])=><button key={name} className={`scene state-${state!.toLowerCase()}`} onClick={()=>action(`${name} metadata`)}><b>{name}</b><span>{state}</span><small>{detail}</small></button>)}</div></Panel><Panel title="Transition deck"><div className="deck">{['CUT','AUTO','TAKE','FTB'].map(label=><button key={label} onClick={()=>action(label)}><b>{label}</b><small>Unwired</small></button>)}<div><b>Mix · 00:20</b><span>T-bar concept · previous: Interview</span></div></div></Panel><Panel title="Rundown & next action"><div className="rundown"><b>14:10</b><span>Audience Q&A</span><small>Next · 02:30 · guests and graphics ready</small><b>14:13</b><span>Sponsor break</span><small>Standby · 00:30 · automation planned</small></div></Panel></>}
function Solo(){return <><Panel title="Quick scenes"><div className="quick-scenes">{scenes.slice(0,3).map(item=><button key={item[0]}>{item[0]}<small>Prototype</small></button>)}</div></Panel><Panel title="Unified audience"><div className="chat"><p><b>YouTube · Nia</b> “Could Maya share the checklist?” <small>Priority question</small></p><p><b>TikTok · @summit_live</b> “This is exactly what I needed.”</p><p><b>Facebook · Theo</b> ❤️ 48 · Featured response</p></div></Panel><Panel title="Creator momentum"><div className="metrics"><b>12.8K <small>audience</small></b><b>68% <small>engaged</small></b><b>↑ 14% <small>growth signal</small></b></div></Panel></>}
function Technical(){return <><Panel title="Signal readiness matrix"><div className="matrix">{['Camera A','Camera B','Guest RT','Playback','Program Out'].map((v,i)=><div key={v}><b>{v}</b><span>{i===3?'FORMAT WARN':'LOCKED · 59.94'}</span><small>{i===4?'42 ms output latency':'Genlock stable'}</small></div>)}</div></Panel><Panel title="Routing, keyers & failover"><div className="technical-list"><b>Input routing <span>12 paths resolved</span></b><b>USK / DSK <span>2 keys armed as metadata</span></b><b>Failover <span>Warm standby · planned</span></b></div></Panel></>}
function AudioWorkspace({action}:{action:(label:string)=>void}){return <><div className="audio-confidence"><Monitor kind="PREVIEW"/><Monitor kind="PROGRAM"/><Panel title="Master loudness"><b className="loudness">−16.2 LUFS</b><span>Target −16 LUFS · no clipping</span></Panel></div><Panel title="Channel bank"><div className="mixer">{channels.map((name,index)=><div className="channel" key={name}><b>{name}</b><div className="meter"><i style={{height:`${42+index*7}%`}}/></div><input aria-label={`${name} prototype fader`} type="range" value={55+index*5} readOnly/><small>−{6+index}.2 dB</small><button onClick={()=>action(`Mute ${name}`)}>M</button><button onClick={()=>action(`Solo ${name}`)}>S</button></div>)}</div></Panel><Panel title="Buses, remote health & monitor mix"><div className="metrics"><b>PGM <small>stereo bus</small></b><b>AUX 1 <small>guest return</small></b><b>IFB <small>talkback planned</small></b></div></Panel></>}
function Graphics({action}:{action:(label:string)=>void}){return <><Panel title="Graphics preview & safe area"><div className="graphics-preview"><div><b>LOWER THIRD</b><span>Maya Chen</span><small>Product strategist</small></div><i>16:9 SAFE</i><i className="vertical-guide">9:16 SAFE</i></div></Panel><Panel title="Template browser"><div className="template-list">{['Lower third · Speaker','Live bug · Summit','Sponsor slate','Question card'].map((x,i)=><button onClick={()=>action(x)} key={x}>{x}<span>{i===0?'FIELD REQUIRED':'Ready'}</span></button>)}</div></Panel><Panel title="Overlay stack"><div className="rundown"><b>01</b><span>Live bug</span><small>Persistent · YouTube 16:9 / TikTok 9:16</small><b>02</b><span>Lower third</span><small>Queued · name pending</small></div></Panel></>}
function Replay({action}:{action:(label:string)=>void}){return <><Panel title="Replay source bank"><div className="source-bank">{['CAM A','CAM B','ISO GUEST','WIDE'].map(x=><div key={x}><b>{x}</b><span>SYNCED</span></div>)}</div></Panel><Panel title="Selected clip · Summit reaction"><div className="timeline"><b>00:12</b><div><i/><i/><i/><i/></div><span>IN 01:22:08 · 50% speed · queued, not taken</span></div><div className="deck">{['MARK IN','MARK OUT','CUE','TAKE REPLAY','RETURN LIVE'].map(x=><button key={x} onClick={()=>action(x)}>{x}<small>Unwired</small></button>)}</div></Panel><Panel title="Highlights queue"><div className="rundown"><b>01</b><span>Audience response</span><small>12 sec · 50% · tag: reaction</small></div></Panel></>}
function Streaming(){return <><Panel title="Destination matrix"><div className="destination-grid">{destinations.map(([name,ratio,status])=><article key={name} className={status!.toLowerCase()}><b>{name}</b><span>{status}</span><small>{ratio} · Platform graphic variant</small><em>{name==='TikTok'?'3.2 Mbps · 1.8% loss':name==='Instagram'?'Reconnecting · retry planned':'6.0 Mbps · 42 ms'}</em></article>)}</div></Panel><Panel title="Encoder, recording & network"><div className="metrics"><b>6.0 Mbps <small>encoder target</small></b><b>0 <small>dropped frames</small></b><b>01:18:22 <small>recording active</small></b><b>42 ms <small>delivery latency</small></b></div></Panel></>}
function Compact({action}:{action:(label:string)=>void}){return <><Panel title="Essential switching"><div className="deck">{['CUT','AUTO','TAKE'].map(x=><button key={x} onClick={()=>action(x)}>{x}<small>Unwired</small></button>)}<div><b>Quick scene: Audience Q&A</b><span>Tool drawer · audio confident · 5 outputs</span></div></div></Panel><Panel title="Warning summary"><div className="readiness"><b>No critical warnings</b><span>Prototype fixture healthy · tap a scenario above to review alternate readiness.</span></div></Panel></>}
function MonitorWall({vertical}:{vertical:boolean}){const tiles=['PROGRAM','PREVIEW','CAM A','CAM B','GUEST','TikTok 9:16','YouTube','RECORD','AUDIO','NETWORK','ENCODER','ALERTS'];return <main className="next-workspace monitor-wall-view"><div className="workspace-heading"><div><p>BUILT-IN WORKSPACE · DENSE MULTIVIEW</p><h1>Monitor Wall</h1><span>Demonstration data · operator-defined priority tiles</span></div></div><div className="wall-grid">{tiles.map((tile,i)=><article key={tile} className={i<2?'hero-tile':''}><div className={tile.includes('TikTok')||vertical?'portrait-tile':'tile-art'}><b>{tile}</b><span>{i===0?'● PROGRAM':i===1?'◇ PREVIEW':i===9?'42 ms · stable':'READY · 1080p59.94'}</span></div><small>Runtime pending · metadata only</small></article>)}</div></main>}
