import { AlertSeverity, HealthStatus, redact, type MetricSample } from '../observability/index.js';
import type { OperationalIncident } from '../incident-response/index.js';
import type { CapacityForecast } from '../capacity/index.js';

export enum AnalyticsAggregation { Sum='sum', Count='count', Average='average', Minimum='minimum', Maximum='maximum', Median='median', Percentile='percentile', Ratio='ratio', Rate='rate', Duration='duration', DistinctCount='distinct_count', WeightedAverage='weighted_average', Custom='custom' }
export enum AnalyticsDimensionType { Time='time', Production='production', Organization='organization', Location='location', User='user', Service='service', Platform='platform', Destination='destination', Workflow='workflow', Incident='incident', Resource='resource', Custom='custom' }
export enum ReportStatus { Draft='draft', Generating='generating', Provisional='provisional', Final='final', Revised='revised', Certified='certified', Failed='failed', Archived='archived' }
export enum SLAComparisonOperator { GreaterThan='greater_than', GreaterThanOrEqual='greater_than_or_equal', LessThan='less_than', LessThanOrEqual='less_than_or_equal', Equals='equals' }
export enum SLAComplianceStatus { Met='met', Missed='missed', InsufficientData='insufficient_data', Disputed='disputed', Excluded='excluded' }
export enum AnalyticsConfidence { High='high', Medium='medium', Low='low', InsufficientData='insufficient_data' }
export enum DashboardWidgetType { Kpi='kpi', LineChart='line_chart', BarChart='bar_chart', StackedChart='stacked_chart', Heatmap='heatmap', AvailabilityTimeline='availability_timeline', IncidentTable='incident_table', DestinationComparison='destination_comparison', SLAStatus='sla_status', CapacityGauge='capacity_gauge', ForecastPanel='forecast_panel', RankedList='ranked_list', AuditSummary='audit_summary', ReportLink='report_link' }

export interface AnalyticsMetric { id:string; name:string; description:string; measure:string; aggregation:AnalyticsAggregation; dimensions:string[]; unit:string; calculationVersion:number; dataSourceIds:string[]; enabled:boolean; }
export interface AnalyticsDimension { id:string; name:string; sourceField:string; type:AnalyticsDimensionType; hierarchy?:string[]; }
export interface AnalyticsFilter { dimensionId:string; operator:'equals'|'not_equals'|'in'|'range'; value:unknown; }
export interface AnalyticsComparison { type:'previous_period'|'same_period_last_year'|'target'|'baseline'|'peer'|'customer_average'|'site_average'|'destination_average'; targetValue?:number; label?:string; }
export interface AnalyticsQuery { metricIds:string[]; dimensions?:string[]; filters?:AnalyticsFilter[]; from:number; to:number; granularity?:string; comparisons?:AnalyticsComparison[]; limit?:number; requesterScope?:AccessScope; }
export interface AnalyticsRecord { id:string; timestamp:number; measure:string; value:number; dimensions:Record<string,string>; sourceId:string; evidenceIds:string[]; generation:number; metadata?:Record<string,unknown>; }
export interface AggregatedMetric { metricId:string; value:number; unit:string; dimensions:Record<string,string>; from:number; to:number; aggregation:AnalyticsAggregation; calculationVersion:number; confidence:AnalyticsConfidence; dataCompleteness:number; sourceIds:string[]; evidenceIds:string[]; }
export interface DataQualityResult { datasetId:string; completeness:number; freshness:number; consistency:number; validity:number; traceability:number; overallScore:number; confidence:AnalyticsConfidence; warnings:string[]; }
export interface ProductionAvailabilityMetric { productionId:string; measurementWindowMs:number; expectedAvailableMs:number; actualAvailableMs:number; availabilityPercent:number; excludedMaintenanceMs:number; unplannedDowntimeMs:number; confidence:number; }
export interface CostRecord { id:string; timestamp:number; productionId?:string; customerId?:string; resourceType:string; resourceId?:string; quantity:number; unit:string; unitCost:number; totalCost:number; source:string; }
export interface SLAObjective { id:string; name:string; indicator:string; target:number; operator:SLAComparisonOperator; measurementWindow:'per_production'|'daily'|'weekly'|'monthly'|'quarterly'|'rolling_30_days'|'contract_term'; severity:string; penaltyPolicyId?:string; }
export interface SLAExclusion { id?:string; type:string; description:string; requiresApproval:boolean; evidenceRequired:boolean; approved?:boolean; evidenceIds?:string[]; from?:number; to?:number; }
export interface ServiceLevelAgreement { id:string; name:string; customerId?:string; productionIds?:string[]; effectiveFrom:number; effectiveTo?:number; objectives:SLAObjective[]; exclusions:SLAExclusion[]; reportingScheduleId?:string; enabled:boolean; generation:number; }
export interface SLAEvaluationResult { agreementId:string; objectiveId:string; period:{from:number;to:number}; measuredValue:number; target:number; status:SLAComplianceStatus; evidenceIds:string[]; exclusionsApplied:SLAExclusion[]; calculationVersion:number; dataQuality:DataQualityResult; breachId?:string; }
export interface SLAReport { id:string; agreementId:string; period:{from:number;to:number}; results:SLAEvaluationResult[]; status:ReportStatus; hash:string; certifiedBy?:string; certifiedAt?:number; }
export interface ReportDefinition { id:string; name:string; templateId:string; audience:string; metricIds:string[]; defaultDimensions:string[]; accessPolicyId:string; version:number; }
export interface GeneratedReport { id:string; definitionId:string; status:ReportStatus; period:{from:number;to:number}; generatedAt:number; metrics:AggregatedMetric[]; dataQuality:DataQualityResult; summary:string; evidenceIds:string[]; hash:string; certifiedBy?:string; certifiedAt?:number; revisionOf?:string; }
export interface ReportSchedule { id:string; reportDefinitionId:string; recurrence:string; timezone:string; finalizeDelayMs?:number; enabled:boolean; }
export interface DashboardWidget { id:string; type:DashboardWidgetType; title:string; metricIds:string[]; dimensions?:string[]; drillDownEvidence?:boolean; }
export interface DashboardDefinition { id:string; name:string; audience:string; widgets:DashboardWidget[]; defaultTimeRange:string; refreshIntervalMs?:number; accessPolicyId:string; scope:AccessScope; }
export interface AnalyticsRecommendation { id:string; category:string; title:string; description:string; priority:string; confidence:AnalyticsConfidence; evidenceMetricIds:string[]; evidenceReportIds?:string[]; expectedBenefit?:string; estimatedCost?:number; status:string; }
export interface AccessScope { customerIds?:string[]; productionIds?:string[]; roles?:string[]; permissions:string[]; allowSensitive?:boolean; }
export interface AnalyticsSnapshot { metrics:AnalyticsMetric[]; dimensions:AnalyticsDimension[]; records:number; reports:GeneratedReport[]; dashboards:DashboardDefinition[]; agreements:ServiceLevelAgreement[]; evaluations:SLAEvaluationResult[]; recommendations:AnalyticsRecommendation[]; audit:string[]; health:{status:HealthStatus; score:number; reasons:string[]}; }

const clone=<T>(v:T):T=>structuredClone(v); const freeze=<T>(v:T):T=>Object.freeze(clone(v)); const bounded=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n));
function confidence(score:number):AnalyticsConfidence{ return score>=0.9?AnalyticsConfidence.High:score>=0.7?AnalyticsConfidence.Medium:score>0?AnalyticsConfidence.Low:AnalyticsConfidence.InsufficientData; }
function hash(value:unknown):string{ const s=JSON.stringify(value); let h=2166136261; for(let i=0;i<s.length;i++){ h^=s.charCodeAt(i); h=Math.imul(h,16777619); } return (h>>>0).toString(16).padStart(8,'0'); }
function compare(value:number, op:SLAComparisonOperator, target:number):boolean{ switch(op){ case SLAComparisonOperator.GreaterThan:return value>target; case SLAComparisonOperator.GreaterThanOrEqual:return value>=target; case SLAComparisonOperator.LessThan:return value<target; case SLAComparisonOperator.LessThanOrEqual:return value<=target; case SLAComparisonOperator.Equals:return value===target; } }
function scoped(record:AnalyticsRecord, scope?:AccessScope):boolean{ if(!scope) return true; const c=record.dimensions.customer, p=record.dimensions.production; if(c&&scope.customerIds&&!scope.customerIds.includes(c)) return false; if(p&&scope.productionIds&&!scope.productionIds.includes(p)) return false; if(record.dimensions.sensitive==='true'&&!scope.allowSensitive) return false; return true; }
function percentile(values:number[], p:number):number{ if(!values.length) return 0; const sorted=[...values].sort((a,b)=>a-b); const idx=Math.min(sorted.length-1,Math.max(0,Math.ceil((p/100)*sorted.length)-1)); return sorted[idx]!; }

export function calculateAvailability(input:Omit<ProductionAvailabilityMetric,'availabilityPercent'|'unplannedDowntimeMs'|'confidence'> & { missingEvidenceMs?:number }):ProductionAvailabilityMetric{ const eligible=Math.max(0,input.expectedAvailableMs-input.excludedMaintenanceMs); const actual=Math.min(input.actualAvailableMs,eligible); const availabilityPercent=eligible===0?100:(actual/eligible)*100; const unplannedDowntimeMs=Math.max(0,eligible-actual); const confidenceValue=eligible===0?0:bounded(1-((input.missingEvidenceMs??0)/eligible)); return {...input,actualAvailableMs:actual,availabilityPercent,unplannedDowntimeMs,confidence:confidenceValue}; }
export function evaluateDataQuality(datasetId:string, expected:number, actual:AnalyticsRecord[], now:number):DataQualityResult{ const unique=new Set(actual.map(r=>r.id)); const invalid=actual.filter(r=>!Number.isFinite(r.value)||r.timestamp<0||!r.evidenceIds.length).length; const newest=actual.reduce((m,r)=>Math.max(m,r.timestamp),0); const completeness=expected===0?(actual.length?1:0):bounded(actual.length/expected); const freshness=newest===0?0:bounded(1-((now-newest)/(24*60*60*1000))); const consistency=actual.length===unique.size?1:bounded(unique.size/Math.max(1,actual.length)); const validity=actual.length===0?0:bounded(1-invalid/actual.length); const traceability=actual.length===0?0:bounded(actual.filter(r=>r.evidenceIds.length>0).length/actual.length); const overallScore=(completeness+freshness+consistency+validity+traceability)/5; const warnings:string[]=[]; if(completeness<0.95) warnings.push(`incomplete data: ${(completeness*100).toFixed(2)}%`); if(freshness<0.8) warnings.push('stale data may affect report confidence'); if(consistency<1) warnings.push('duplicate or conflicting records detected'); if(validity<1) warnings.push('invalid values excluded from authority'); if(traceability<1) warnings.push('some results lack evidence traceability'); return {datasetId,completeness,freshness,consistency,validity,traceability,overallScore,confidence:confidence(overallScore),warnings}; }

export class AnalyticsEngine { #metrics=new Map<string,AnalyticsMetric>(); #dimensions=new Map<string,AnalyticsDimension>(); #records=new Map<string,AnalyticsRecord>(); #reports=new Map<string,GeneratedReport>(); #reportDefs=new Map<string,ReportDefinition>(); #dashboards=new Map<string,DashboardDefinition>(); #agreements=new Map<string,ServiceLevelAgreement>(); #evaluations=new Map<string,SLAEvaluationResult>(); #recommendations=new Map<string,AnalyticsRecommendation>(); #schedules=new Map<string,ReportSchedule>(); #audit:string[]=[]; constructor(private readonly maxRecords=100000, private readonly maxAudit=20000){}
  registerMetric(metric:AnalyticsMetric):void{ this.#metrics.set(metric.id,freeze({...metric,dimensions:[...metric.dimensions].sort(),dataSourceIds:[...metric.dataSourceIds].sort()})); this.#audit.push(`metric.registered:${metric.id}:v${metric.calculationVersion}`); }
  registerDimension(dimension:AnalyticsDimension):void{ this.#dimensions.set(dimension.id,freeze(dimension)); this.#audit.push(`dimension.registered:${dimension.id}`); }
  ingest(record:AnalyticsRecord):void{ const existing=this.#records.get(record.id); if(existing&&record.generation<=existing.generation) throw new Error(`stale analytics generation: ${record.id}`); if(!Number.isFinite(record.value)) throw new Error('analytics value must be finite'); const safe={...record,dimensions:redact(record.dimensions) as Record<string,string>,metadata:redact(record.metadata??{}) as Record<string,unknown>}; this.#records.set(record.id,freeze(safe)); while(this.#records.size>this.maxRecords){ const oldest=[...this.#records.values()].sort((a,b)=>a.timestamp-b.timestamp)[0]; if(!oldest) break; this.#records.delete(oldest.id); } this.#audit.push(`record.ingested:${record.id}:${record.generation}`); }
  ingestMetricSamples(samples:MetricSample[], sourceId='observability'):void{ for(const [i,s] of samples.entries()) this.ingest({id:`${sourceId}:${s.metricName}:${s.timestamp}:${i}`,timestamp:s.timestamp,measure:s.metricName,value:s.value,dimensions:Object.fromEntries(Object.entries(s.labels).map(([k,v])=>[k,String(v)])),sourceId,evidenceIds:[`${sourceId}:${s.metricName}:${s.timestamp}`],generation:1}); }
  ingestIncident(incident:OperationalIncident):void{ this.ingest({id:`incident:${incident.id}`,timestamp:incident.detectedAt,measure:'incident.count',value:1,dimensions:{incident:incident.id,severity:incident.severity,status:incident.status,production:incident.productionId??'unknown'},sourceId:'incident-response',evidenceIds:[incident.id],generation:Math.max(1,incident.updatedAt)}); }
  ingestCapacityForecast(forecast:CapacityForecast):void{ this.ingest({id:`capacity:${forecast.resourceType}:${forecast.predictedAt}`,timestamp:forecast.predictedAt,measure:'capacity.predicted_utilization',value:forecast.predictedUtilization,dimensions:{resource:forecast.resourceType},sourceId:'capacity',evidenceIds:[`forecast:${forecast.resourceType}:${forecast.predictedAt}`],generation:1}); }
  query(query:AnalyticsQuery):AggregatedMetric[]{ if(query.to<=query.from) throw new Error('analytics query period is invalid'); const limit=Math.min(query.limit??1000,5000); const out:AggregatedMetric[]=[]; for(const metricId of query.metricIds){ const metric=this.#metrics.get(metricId); if(!metric||!metric.enabled) continue; let records=[...this.#records.values()].filter(r=>r.measure===metric.measure&&r.timestamp>=query.from&&r.timestamp<=query.to&&scoped(r,query.requesterScope)); records=this.#applyFilters(records,query.filters??[]); const groups=this.#group(records,query.dimensions??[]); for(const [key,group] of groups){ const value=this.#aggregate(metric.aggregation,group); const dq=evaluateDataQuality(`${metricId}:${key}`,Math.max(1,group.length),group,query.to); out.push({metricId,value,unit:metric.unit,dimensions:key?JSON.parse(key) as Record<string,string>:{},from:query.from,to:query.to,aggregation:metric.aggregation,calculationVersion:metric.calculationVersion,confidence:dq.confidence,dataCompleteness:dq.completeness,sourceIds:[...new Set(group.map(r=>r.sourceId))].sort(),evidenceIds:[...new Set(group.flatMap(r=>r.evidenceIds))].sort()}); } }
    this.#audit.push(`query.executed:${query.metricIds.join(',')}:${out.length}`); return out.sort((a,b)=>a.metricId.localeCompare(b.metricId)||JSON.stringify(a.dimensions).localeCompare(JSON.stringify(b.dimensions))).slice(0,limit); }
  defineReport(def:ReportDefinition):void{ this.#reportDefs.set(def.id,freeze(def)); this.#audit.push(`report.defined:${def.id}:v${def.version}`); }
  generateReport(definitionId:string, period:{from:number;to:number}, status=ReportStatus.Final, requesterScope?:AccessScope):GeneratedReport{ const def=this.#reportDefs.get(definitionId); if(!def) throw new Error(`unknown report definition: ${definitionId}`); const metrics=this.query({metricIds:def.metricIds,dimensions:def.defaultDimensions,from:period.from,to:period.to,requesterScope}); const quality=evaluateDataQuality(`report:${definitionId}`,def.metricIds.length,metrics.flatMap(m=>m.evidenceIds.map((e,i)=>({id:e,timestamp:period.to,measure:m.metricId,value:m.value,dimensions:m.dimensions,sourceId:m.sourceIds[i]??'aggregate',evidenceIds:[e],generation:1}))),period.to); const report={id:`report:${definitionId}:${period.from}:${period.to}:${this.#reports.size+1}`,definitionId,status,period,generatedAt:period.to,metrics,dataQuality:quality,summary:this.#summarize(metrics,quality),evidenceIds:[...new Set(metrics.flatMap(m=>m.evidenceIds))].sort(),hash:''}; report.hash=hash({...report,hash:''}); this.#reports.set(report.id,freeze(report)); this.#audit.push(`report.generated:${report.id}:${status}`); return clone(report); }
  reviseReport(reportId:string):GeneratedReport{ const old=this.#reports.get(reportId); if(!old) throw new Error(`unknown report: ${reportId}`); const revised={...old,id:`${old.id}:rev${Date.now()}`,status:ReportStatus.Revised,revisionOf:old.id,hash:''}; revised.hash=hash({...revised,hash:''}); this.#reports.set(revised.id,freeze(revised)); this.#audit.push(`report.revised:${old.id}:${revised.id}`); return clone(revised); }
  certifyReport(reportId:string, identityId:string):GeneratedReport{ const report=this.#reports.get(reportId); if(!report) throw new Error(`unknown report: ${reportId}`); if(report.status===ReportStatus.Certified) throw new Error('report is already certified'); const certified={...report,status:ReportStatus.Certified,certifiedBy:String(redact(identityId)),certifiedAt:report.generatedAt,hash:''}; certified.hash=hash({...certified,hash:''}); this.#reports.set(reportId,freeze(certified)); this.#audit.push(`report.certified:${reportId}`); return clone(certified); }
  scheduleReport(schedule:ReportSchedule):void{ this.#schedules.set(schedule.id,freeze(schedule)); this.#audit.push(`report.schedule:${schedule.id}`); }
  createDashboard(def:DashboardDefinition):void{ if(!def.scope.permissions.includes('dashboard.create')&&!def.scope.permissions.includes('analytics.view')) throw new Error('dashboard scope lacks view permission'); this.#dashboards.set(def.id,freeze({...def,widgets:[...def.widgets].sort((a,b)=>a.id.localeCompare(b.id))})); this.#audit.push(`dashboard.created:${def.id}`); }
  createSLA(agreement:ServiceLevelAgreement):void{ const existing=this.#agreements.get(agreement.id); if(existing&&agreement.generation<=existing.generation) throw new Error(`stale SLA generation: ${agreement.id}`); this.#agreements.set(agreement.id,freeze(agreement)); this.#audit.push(`sla.created:${agreement.id}:g${agreement.generation}`); }
  approveExclusion(agreementId:string, exclusionId:string, evidenceIds:string[]):void{ const agreement=this.#agreements.get(agreementId); if(!agreement) throw new Error(`unknown SLA: ${agreementId}`); const exclusions=agreement.exclusions.map((e,i)=>((e.id??String(i))===exclusionId?{...e,approved:true,evidenceIds:[...(e.evidenceIds??[]),...evidenceIds].sort()}:e)); this.#agreements.set(agreementId,freeze({...agreement,exclusions,generation:agreement.generation+1})); this.#audit.push(`sla.exclusion.approved:${agreementId}:${exclusionId}`); }
  evaluateSLA(agreementId:string, period:{from:number;to:number}):SLAEvaluationResult[]{ const agreement=this.#agreements.get(agreementId); if(!agreement||!agreement.enabled) throw new Error(`unknown or disabled SLA: ${agreementId}`); const scope:AccessScope={customerIds:agreement.customerId?[agreement.customerId]:undefined,productionIds:agreement.productionIds,permissions:['sla.view'],allowSensitive:false}; const results: SLAEvaluationResult[]=[]; for(const objective of agreement.objectives){ const metric=this.#metricByMeasure(objective.indicator); const metrics=metric?this.query({metricIds:[metric.id],from:period.from,to:period.to,requesterScope:scope}):[]; const value=metrics[0]?.value??0; const dq=metrics[0]?evaluateDataQuality(`sla:${agreementId}:${objective.id}`,1,[{id:`sla:${objective.id}`,timestamp:period.to,measure:objective.indicator,value,dimensions:{},sourceId:'analytics',evidenceIds:metrics[0].evidenceIds,generation:1}],period.to):evaluateDataQuality(`sla:${agreementId}:${objective.id}`,1,[],period.to); const exclusions=agreement.exclusions.filter(e=>e.approved&&(!e.from||e.to)&&((e.from??period.from)<=period.to)&&((e.to??period.to)>=period.from)); const met=dq.confidence===AnalyticsConfidence.InsufficientData?false:compare(value,objective.operator,objective.target); const status=dq.confidence===AnalyticsConfidence.InsufficientData?SLAComplianceStatus.InsufficientData:exclusions.length?SLAComplianceStatus.Excluded:met?SLAComplianceStatus.Met:SLAComplianceStatus.Missed; const result={agreementId,objectiveId:objective.id,period,measuredValue:value,target:objective.target,status,evidenceIds:metrics.flatMap(m=>m.evidenceIds),exclusionsApplied:exclusions,calculationVersion:metric?.calculationVersion??1,dataQuality:dq,breachId:status===SLAComplianceStatus.Missed?`breach:${agreementId}:${objective.id}:${period.from}`:undefined}; this.#evaluations.set(`${agreementId}:${objective.id}:${period.from}:${period.to}`,freeze(result)); results.push(clone(result)); this.#audit.push(`sla.evaluated:${agreementId}:${objective.id}:${status}`); } return results.sort((a,b)=>a.objectiveId.localeCompare(b.objectiveId)); }
  recommendations():AnalyticsRecommendation[]{ const recs:AnalyticsRecommendation[]=[]; for(const r of this.#reports.values()){ if(r.dataQuality.overallScore<0.8) recs.push({id:`rec:data-quality:${r.id}`,category:'data-quality',title:'Improve analytics evidence completeness',description:r.dataQuality.warnings.join('; ')||'Report quality below target',priority:'high',confidence:r.dataQuality.confidence,evidenceMetricIds:r.metrics.map(m=>m.metricId),evidenceReportIds:[r.id],expectedBenefit:'higher-confidence compliance and executive reporting',status:'open'}); for(const m of r.metrics){ if(m.metricId.includes('availability')&&m.value<99.9) recs.push({id:`rec:availability:${r.id}:${JSON.stringify(m.dimensions)}`,category:'reliability',title:'Investigate availability decline',description:`${m.metricId} measured ${m.value.toFixed(2)}${m.unit}`,priority:'critical',confidence:m.confidence,evidenceMetricIds:[m.metricId],evidenceReportIds:[r.id],expectedBenefit:'reduced SLA breach risk',status:'open'}); } }
    for(const e of this.#evaluations.values()) if(e.status===SLAComplianceStatus.Missed) recs.push({id:`rec:sla:${e.breachId}`,category:'sla',title:'Remediate missed SLA objective',description:`${e.objectiveId} measured ${e.measuredValue} against ${e.target}`,priority:'critical',confidence:e.dataQuality.confidence,evidenceMetricIds:[e.objectiveId],expectedBenefit:'close breach evidence and prevent recurrence',status:'open'}); this.#recommendations=new Map(recs.map(r=>[r.id,freeze(r)])); return [...this.#recommendations.values()].sort((a,b)=>a.id.localeCompare(b.id)).map(clone); }
  dataQuality(datasetId:string, now=Date.now()):DataQualityResult{ const records=[...this.#records.values()].filter(r=>r.sourceId===datasetId||r.measure===datasetId); return evaluateDataQuality(datasetId,Math.max(1,records.length),records,now); }
  metrics(){ return [...this.#metrics.values()].sort((a,b)=>a.id.localeCompare(b.id)).map(clone); } dimensions(){ return [...this.#dimensions.values()].sort((a,b)=>a.id.localeCompare(b.id)).map(clone); }
  health(){ const q=[...this.#reports.values()].map(r=>r.dataQuality.overallScore); const avg=q.length?q.reduce((a,b)=>a+b,0)/q.length:1; const missed=[...this.#evaluations.values()].filter(e=>e.status===SLAComplianceStatus.Missed).length; const status=missed?HealthStatus.Critical:avg<0.8?HealthStatus.Warning:HealthStatus.Healthy; return {status,score:bounded(avg)*100,reasons:[...(missed?[`${missed} SLA objective(s) missed`]:[]),...(avg<0.8?['report data quality below target']:[])]}; }
  snapshot():AnalyticsSnapshot{ return clone({metrics:this.metrics(),dimensions:this.dimensions(),records:this.#records.size,reports:[...this.#reports.values()].sort((a,b)=>a.id.localeCompare(b.id)),dashboards:[...this.#dashboards.values()].sort((a,b)=>a.id.localeCompare(b.id)),agreements:[...this.#agreements.values()].sort((a,b)=>a.id.localeCompare(b.id)),evaluations:[...this.#evaluations.values()].sort((a,b)=>a.objectiveId.localeCompare(b.objectiveId)),recommendations:this.recommendations(),audit:this.#audit.slice(-this.maxAudit),health:this.health()}); }
  #applyFilters(records:AnalyticsRecord[], filters:AnalyticsFilter[]):AnalyticsRecord[]{ return records.filter(r=>filters.every(f=>{ const v=r.dimensions[f.dimensionId]; if(f.operator==='equals') return v===String(f.value); if(f.operator==='not_equals') return v!==String(f.value); if(f.operator==='in') return Array.isArray(f.value)&&f.value.map(String).includes(v); if(f.operator==='range') return Array.isArray(f.value)&&Number(v)>=Number(f.value[0])&&Number(v)<=Number(f.value[1]); return false; })); }
  #group(records:AnalyticsRecord[], dims:string[]):Map<string,AnalyticsRecord[]>{ const m=new Map<string,AnalyticsRecord[]>(); for(const r of records){ const key=JSON.stringify(Object.fromEntries(dims.map(d=>[d,r.dimensions[d]??'unknown']).sort(([a],[b])=>a.localeCompare(b)))); m.set(key,[...(m.get(key)??[]),r]); } return m; }
  #aggregate(agg:AnalyticsAggregation, records:AnalyticsRecord[]):number{ const values=records.map(r=>r.value); if(!values.length) return 0; switch(agg){ case AnalyticsAggregation.Sum: return values.reduce((a,b)=>a+b,0); case AnalyticsAggregation.Count: return records.length; case AnalyticsAggregation.Average: return values.reduce((a,b)=>a+b,0)/values.length; case AnalyticsAggregation.Minimum: return Math.min(...values); case AnalyticsAggregation.Maximum: return Math.max(...values); case AnalyticsAggregation.Median: return percentile(values,50); case AnalyticsAggregation.Percentile: return percentile(values,95); case AnalyticsAggregation.Ratio: return values.length<2?0:values[0]!/Math.max(1,values[1]!); case AnalyticsAggregation.Rate: return values.reduce((a,b)=>a+b,0)/Math.max(1,(records.at(-1)!.timestamp-records[0]!.timestamp)/1000); case AnalyticsAggregation.Duration: return values.reduce((a,b)=>a+b,0); case AnalyticsAggregation.DistinctCount: return new Set(values).size; case AnalyticsAggregation.WeightedAverage: return values.reduce((a,b)=>a+b,0)/values.length; case AnalyticsAggregation.Custom: return values.reduce((a,b)=>a+b,0); } }
  #metricByMeasure(measure:string):AnalyticsMetric|undefined{ return [...this.#metrics.values()].find(m=>m.measure===measure||m.id===measure); }
  #summarize(metrics:AggregatedMetric[], q:DataQualityResult):string{ return `${metrics.length} metric groups generated with ${q.confidence} confidence and ${(q.overallScore*100).toFixed(2)}% data quality`; }
}
