import type { ProductionGraph } from '../../../shared/src/production-graph.js';
import type { VideoRoutePlan } from '../routing.js';
import type { AudioRoutePlan } from '../audio-routing/index.js';
import type { FrameTickEvent, MediaClock } from '../sync/index.js';

export type EncoderBackend = 'mock'|'ffmpeg'|'webcodecs'|'nvenc'|'quicksync'|'videotoolbox'|'amf'|'vaapi'|'software'|'custom';
export type EncoderStatus = 'idle'|'planned'|'preparing'|'ready'|'encoding'|'paused'|'draining'|'stopped'|'failed'|'unavailable';
export type EncoderHealth = 'healthy'|'degraded'|'warning'|'critical'|'unavailable';
export type EncoderCapability = 'video'|'audio'|'multiplex'|'hardware'|'software'|'low_latency'|'replay_safe'|'mock_only';
export type VideoCodec = 'h264'|'h265'|'av1'|'vp8'|'vp9'|'prores'|'raw'|'unknown';
export type AudioCodec = 'aac'|'opus'|'pcm'|'mp3'|'unknown';
export type HardwareAcceleration = 'none'|'optional'|'required'|'mock'|'unknown';
export interface BitrateProfile { readonly targetKbps: number; readonly maxKbps?: number; readonly minKbps?: number; readonly mode: 'cbr'|'vbr'|'lossless'|'unknown'; }
export interface ResolutionProfile { readonly width: number; readonly height: number; readonly fps: number; readonly scan: 'progressive'|'interlaced'|'unknown'; }
export interface EncoderFailure { readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly backend?: EncoderBackend; }
export interface EncoderTarget { readonly id: string; readonly outputId: string; readonly kind: 'broadcast_output'|'recording'|'streaming'|'monitor'|'custom'; readonly recordingId?: string; readonly streamId?: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface EncoderProfile { readonly id: string; readonly name: string; readonly videoCodec: VideoCodec; readonly audioCodec: AudioCodec; readonly bitrate: BitrateProfile; readonly resolution: ResolutionProfile; readonly hardwareAcceleration: HardwareAcceleration; readonly keyframeIntervalFrames?: number; readonly lowLatency: boolean; readonly metadata: Readonly<Record<string, unknown>>; }
export interface EncoderPlan { readonly id: string; readonly broadcastSessionId: string; readonly graphRevision: number; readonly frameId: number; readonly outputId: string; readonly videoRouteId: string; readonly audioRouteId: string; readonly recordingId?: string; readonly streamId?: string; readonly target: EncoderTarget; readonly profile: EncoderProfile; readonly backend: EncoderBackend; readonly timing: Readonly<{ mediaClockId: string; frameTimestamp?: number; createdAt: string; deadlineMs?: number }>; readonly failurePolicy: Readonly<Record<string, unknown>>; readonly backpressurePolicy: Readonly<Record<string, unknown>>; readonly replay: Readonly<{ replaySafe: true; sourceGraphRevision: number; deterministicMock: boolean }>; readonly warnings: readonly string[]; }
export interface EncoderSession { readonly id: string; readonly planId: string; readonly status: EncoderStatus; readonly health: EncoderHealth; readonly backend: EncoderBackend; readonly startedAt?: string; readonly stoppedAt?: string; readonly updatedAt: string; readonly estimatedBitrateKbps: number; readonly estimatedFps: number; readonly estimatedLatencyMs: number; readonly warnings: readonly string[]; readonly failures: readonly EncoderFailure[]; }
export interface EncoderExecutionResult { readonly success: boolean; readonly session: EncoderSession; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
export interface EncoderManifest { readonly id: string; readonly planId: string; readonly graphRevision: number; readonly frameId: number; readonly backend: EncoderBackend; readonly target: Pick<EncoderTarget,'id'|'outputId'|'kind'|'recordingId'|'streamId'>; readonly profile: Pick<EncoderProfile,'id'|'videoCodec'|'audioCodec'|'bitrate'|'resolution'|'hardwareAcceleration'>; readonly capabilities: readonly EncoderCapability[]; readonly generatedAt: string; readonly containsMediaPayloads: false; readonly containsEncodedPackets: false; }
const now = () => new Date().toISOString();
export function validateEncoderProfile(profile: EncoderProfile) { const errors:string[]=[]; const warnings:string[]=[]; if (profile.bitrate.targetKbps < 0) errors.push('Invalid target bitrate'); if (profile.resolution.width <= 0 || profile.resolution.height <= 0) errors.push('Invalid resolution'); if (profile.resolution.fps <= 0) errors.push('Invalid fps'); if (profile.videoCodec === 'raw') warnings.push('Raw video codec is metadata-only in this foundation'); if (profile.hardwareAcceleration === 'required') warnings.push('Hardware acceleration is declared but not used by the mock layer'); return { valid: errors.length===0, warnings, errors }; }
export function selectEncoderBackend(input: { preferred?: EncoderBackend; profile?: EncoderProfile; available?: readonly EncoderBackend[] } = {}): EncoderBackend { const available = input.available ?? ['mock','software']; if (input.preferred && available.includes(input.preferred)) return input.preferred; if (input.profile?.hardwareAcceleration === 'required') return available.find((b)=>['nvenc','quicksync','videotoolbox','amf','vaapi'].includes(b)) ?? 'mock'; return available.includes('mock') ? 'mock' : (available[0] ?? 'mock'); }
export function createEncoderPlan(input: { graph: ProductionGraph; videoRoutePlan: VideoRoutePlan; audioRoutePlan: AudioRoutePlan; outputId?: string; recordingId?: string; streamId?: string; target?: Partial<EncoderTarget>; profile?: Partial<EncoderProfile>; backend?: EncoderBackend; mediaClock?: MediaClock; frame?: FrameTickEvent; frameId?: number; failurePolicy?: Record<string, unknown>; backpressurePolicy?: Record<string, unknown>; metadata?: Record<string, unknown>; }): EncoderPlan { const frameId = input.frame?.frameId ?? input.frameId ?? 0; const outputId = input.outputId ?? `output:${input.graph.broadcastSessionId}`; const profile = { id:`encoder-profile:${input.graph.metadata.revision}:${frameId}`, name:'Mock contribution profile', videoCodec:'h264' as const, audioCodec:'aac' as const, bitrate:{ targetKbps:4500, maxKbps:6000, mode:'vbr' as const }, resolution:{ width:1920, height:1080, fps:30, scan:'progressive' as const }, hardwareAcceleration:'mock' as const, lowLatency:true, metadata:{}, ...input.profile }; const backend = input.backend ?? selectEncoderBackend({ profile }); const target = { id:`encoder-target:${outputId}:${input.recordingId ?? input.streamId ?? 'program'}`, outputId, kind: input.streamId ? 'streaming' as const : input.recordingId ? 'recording' as const : 'broadcast_output' as const, ...(input.recordingId ? { recordingId: input.recordingId } : {}), ...(input.streamId ? { streamId: input.streamId } : {}), metadata: input.metadata ?? {}, ...input.target }; const validation = validateEncoderProfile(profile); return { id:`encoder-plan:${input.graph.metadata.revision}:${frameId}:${target.id}`, broadcastSessionId: input.graph.broadcastSessionId, graphRevision: input.graph.metadata.revision, frameId, outputId, videoRouteId: input.videoRoutePlan.id, audioRouteId: input.audioRoutePlan.id, ...(input.recordingId ? { recordingId: input.recordingId } : {}), ...(input.streamId ? { streamId: input.streamId } : {}), target, profile, backend, timing:{ mediaClockId: input.mediaClock ? `media-clock:${input.mediaClock.getState().frameRate}fps` : 'media-clock:unbound', ...(input.frame ? { frameTimestamp: input.frame.timestamp } : {}), createdAt: now() }, failurePolicy: input.failurePolicy ?? { retry: 'mock_once', recover: 'fail_session' }, backpressurePolicy: input.backpressurePolicy ?? { strategy: 'drop_or_throttle_metadata_only', maxQueueDepth: 0 }, replay:{ replaySafe:true, sourceGraphRevision: input.graph.metadata.revision, deterministicMock:true }, warnings:[...validation.warnings, 'Mock encoder plan only; no raw frames, samples, encoded packets, FFmpeg, WebCodecs, or GPU APIs'] }; }
export function validateEncoderPlan(plan: EncoderPlan) { const profile = validateEncoderProfile(plan.profile); const errors = [...profile.errors]; const warnings = [...plan.warnings, ...profile.warnings]; if (!plan.broadcastSessionId) errors.push('Missing broadcast session id'); if (!plan.videoRouteId) errors.push('Missing video route id'); if (!plan.audioRouteId) errors.push('Missing audio route id'); if (plan.backend !== 'mock') warnings.push(`${plan.backend} backend is declared for future integration only`); return { valid: errors.length===0, warnings, errors }; }
export function estimateEncoderLoad(plan: EncoderPlan) { const pixels = plan.profile.resolution.width * plan.profile.resolution.height * plan.profile.resolution.fps; const normalized = pixels / (1920*1080*30); return { normalizedLoad: Number(normalized.toFixed(2)), estimatedLatencyMs: Math.round(8 + normalized * 12), estimatedBitrateKbps: plan.profile.bitrate.targetKbps, estimatedFps: plan.profile.resolution.fps }; }
function makeSession(plan: EncoderPlan, status: EncoderStatus, extra: Partial<EncoderSession> = {}): EncoderSession { return { id:`encoder-session:${plan.id}`, planId: plan.id, status, health: status === 'failed' ? 'critical' : status === 'unavailable' ? 'unavailable' : status === 'paused' || status === 'draining' ? 'warning' : 'healthy', backend: plan.backend, updatedAt: now(), estimatedBitrateKbps: plan.profile.bitrate.targetKbps, estimatedFps: plan.profile.resolution.fps, estimatedLatencyMs: estimateEncoderLoad(plan).estimatedLatencyMs, warnings: [], failures: [], ...extra }; }
export const prepareEncoder = (plan: EncoderPlan): EncoderExecutionResult => { const v=validateEncoderPlan(plan); return { success:v.valid, session:makeSession(plan, v.valid ? 'ready':'failed', { warnings:v.warnings }), warnings:v.warnings, errors:v.errors }; };
export const startEncoder = (s: EncoderSession): EncoderExecutionResult => ({ success:true, session:{ ...s, status:'encoding', health:'healthy', startedAt:s.startedAt ?? now(), updatedAt:now() }, warnings:s.warnings, errors:[] });
export const pauseEncoder = (s: EncoderSession): EncoderExecutionResult => ({ success:true, session:{ ...s, status:'paused', health:'warning', updatedAt:now(), warnings:[...s.warnings,'Mock encoder paused'] }, warnings:['Mock encoder paused'], errors:[] });
export const resumeEncoder = (s: EncoderSession): EncoderExecutionResult => startEncoder({ ...s, status:'ready' });
export const drainEncoder = (s: EncoderSession): EncoderExecutionResult => ({ success:true, session:{ ...s, status:'draining', health:'warning', updatedAt:now(), warnings:[...s.warnings,'Mock drain completed without packets'] }, warnings:['Mock drain completed without packets'], errors:[] });
export const stopEncoder = (s: EncoderSession): EncoderExecutionResult => ({ success:true, session:{ ...s, status:'stopped', health:'healthy', stoppedAt:now(), updatedAt:now() }, warnings:[], errors:[] });
export function failEncoder(s: EncoderSession, failure: EncoderFailure): EncoderExecutionResult { return { success:false, session:{ ...s, status:failure.retryable?'paused':'failed', health:failure.retryable?'degraded':'critical', failures:[...s.failures, failure], warnings: failure.retryable ? [...s.warnings, failure.message] : s.warnings, updatedAt:now() }, warnings:failure.retryable?[failure.message]:[], errors:failure.retryable?[]:[failure.message] }; }
export function summarizeEncoderHealth(session: EncoderSession) { return { health: session.health, active: session.status === 'encoding', warningCount: session.warnings.length, failureCount: session.failures.length, summary: `${session.status}/${session.health} ${session.estimatedBitrateKbps}kbps ${session.estimatedFps}fps ${session.estimatedLatencyMs}ms` }; }
export function createEncoderManifest(plan: EncoderPlan): EncoderManifest { return { id:`encoder-manifest:${plan.id}`, planId:plan.id, graphRevision:plan.graphRevision, frameId:plan.frameId, backend:plan.backend, target:{ id:plan.target.id, outputId:plan.target.outputId, kind:plan.target.kind, ...(plan.target.recordingId ? { recordingId:plan.target.recordingId } : {}), ...(plan.target.streamId ? { streamId:plan.target.streamId } : {}) }, profile:{ id:plan.profile.id, videoCodec:plan.profile.videoCodec, audioCodec:plan.profile.audioCodec, bitrate:plan.profile.bitrate, resolution:plan.profile.resolution, hardwareAcceleration:plan.profile.hardwareAcceleration }, capabilities:['video','audio', plan.backend === 'mock' ? 'mock_only' : 'software', 'replay_safe'], generatedAt:now(), containsMediaPayloads:false, containsEncodedPackets:false }; }
export class EncoderStore { private plans = new Map<string, EncoderPlan>(); setEncoderPlan(plan: EncoderPlan) { this.plans.set(plan.id, plan); return plan; } getEncoderPlan(id: string) { return this.plans.get(id); } listEncoders() { return [...this.plans.values()]; } getActiveEncoders() { return this.listEncoders().filter((p)=>p.backend !== 'custom' && validateEncoderPlan(p).valid); } getEncoderManifest(id: string) { const plan = this.getEncoderPlan(id); return plan ? createEncoderManifest(plan) : undefined; } clearEncoders() { this.plans.clear(); } }

export * from './ffmpeg/index.js';
