'use client';

import { Fragment, useMemo, useState, type ReactNode } from 'react';
import { analytics, audienceSummary, chatMessages, groupCrm, moderationQueue, platforms, type ChatMessage, type ModerationItem } from './social-metadata';
import './social-fabric.css';

const label = (value: string) => value === 'x' ? 'X' : value.charAt(0).toUpperCase() + value.slice(1);
const platformBadge = (platform: string) => ({ youtube: 'YT', facebook: 'FB', tiktok: 'TT', twitch: 'TW', linkedin: 'IN', instagram: 'IG', x: 'X', kick: 'KI' }[platform] ?? platform);
const audienceTimeline = [{ id: '09-00', height: 32 }, { id: '09-30', height: 48 }, { id: '10-00', height: 43 }, { id: '10-30', height: 67 }, { id: '11-00', height: 59 }, { id: '11-30', height: 75 }, { id: '12-00', height: 72 }, { id: '12-30', height: 88 }, { id: '13-00', height: 81 }, { id: '13-30', height: 94 }, { id: '14-00', height: 86 }, { id: '14-30', height: 100 }] as const;
const campaigns = [{ id: 'youtube-tiktok', label: 'YouTube audience → Follow TikTok' }, { id: 'facebook-instagram', label: 'Facebook audience → Follow Instagram' }, { id: 'linkedin-youtube', label: 'LinkedIn audience → Follow YouTube' }] as const;
const topics = [{ id: 'ubos-live', label: '#UBOSLive' }, { id: 'production-workflow', label: 'production workflow' }, { id: 'guest-timing', label: 'guest timing' }, { id: 'audio-quality', label: 'audio quality' }, { id: 'multistreaming', label: 'multistreaming' }, { id: 'scene-templates', label: 'scene templates' }, { id: 'next-guest', label: 'When is the next guest?' }] as const;
const notifications = [{ id: 'tiktok-health', ordinal: 1, label: 'TikTok stream unhealthy.' }, { id: 'youtube-subscriber', ordinal: 2, label: 'New subscriber on YouTube.' }, { id: 'facebook-comments', ordinal: 3, label: 'Facebook comments increasing.' }, { id: 'moderation-review', ordinal: 4, label: 'Moderator required for one comment.' }] as const;
const liveEvents = [{ id: 'live-started', label: 'Live Started', time: '12:20 UTC' }, { id: 'subscriber', label: 'New Subscriber', time: '12:19 UTC' }, { id: 'gift', label: 'Gift Received', time: '12:18 UTC' }, { id: 'poll', label: 'Poll Created', time: '12:17 UTC' }, { id: 'milestone', label: 'Milestone Reached', time: '12:16 UTC' }, { id: 'moderator-action', label: 'Moderator Action', time: '12:15 UTC' }] as const;
const workbenchTabs = [{ id: 'chat', label: 'Unified Chat' }, { id: 'moderation', label: 'Moderation' }, { id: 'publishing', label: 'Publishing' }, { id: 'share', label: 'Cross Share' }, { id: 'follow', label: 'Cross Follow' }, { id: 'crm', label: 'CRM' }, { id: 'analytics', label: 'Analytics' }, { id: 'logs', label: 'Logs' }] as const;

export function PlatformCard({ platform }: { platform: typeof platforms[number] }) { return <article className="sf-platform"><header><b><i>{platformBadge(platform.platform)}</i>{platform.displayName}</b><span className={platform.status}>{platform.status}</span></header><strong>{platform.viewerCount.toLocaleString()} <small>viewers</small></strong><p>{platform.commentsToday.toLocaleString()} comments · {platform.sharesToday.toLocaleString()} shares</p><footer>{platform.healthMessage}</footer></article>; }
export function PlatformOverview() { return <section><div className="sf-section-title"><h2>Platform overview</h2><span>8 deterministic social surfaces</span></div><div className="sf-platforms">{platforms.map((platform) => <PlatformCard key={platform.id} platform={platform} />)}</div></section>; }
export function UnifiedChatMessage({ item }: { item: ChatMessage }) { return <article className="sf-message"><i className="avatar">{item.username.charAt(0)}</i><div><header><b><em>{platformBadge(item.platform)}</em> {item.username}</b><time>{item.timestamp}</time></header><p>{item.message}</p><footer><span className={item.sentiment}>{item.sentiment}</span><span>{item.moderation}</span><button>Reply target: {label(item.platform)}</button><button>Highlight</button><button>Pin</button></footer></div></article>; }
export function UnifiedChat() { const [query, setQuery] = useState(''); const messages = useMemo(() => chatMessages.filter((item) => `${item.username} ${item.message} ${item.platform}`.toLowerCase().includes(query.toLowerCase())), [query]); return <section className="sf-panel chat"><header><div><h2>Unified Chat</h2><small>All incoming audience conversations · metadata only</small></div><input aria-label="Search unified chat" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search conversation" /></header><div className="sf-message-list">{messages.map((item) => <UnifiedChatMessage key={item.id} item={item} />)}</div></section>; }
export function AudienceSummary() { const summary = audienceSummary(); const items = [{ id: 'viewers', name: 'Total viewers', value: summary.viewers.toLocaleString() }, { id: 'comments', name: 'Total comments', value: summary.comments.toLocaleString() }, { id: 'reactions', name: 'Total reactions', value: summary.reactions.toLocaleString() }, { id: 'engagement', name: 'Average engagement', value: `${summary.engagement.toFixed(1)}%` }, { id: 'fastest', name: 'Fastest growing', value: label(summary.fastest) }, { id: 'retention', name: 'Highest retention', value: label(summary.retention) }, { id: 'active', name: 'Most active', value: label(summary.active) }, { id: 'region', name: 'Top region', value: summary.region }]; return <section className="sf-summary">{items.map((item) => <article key={item.id}><small>{item.name}</small><b>{item.value}</b></article>)}</section>; }
export function AudienceTimeline() { return <section className="sf-panel timeline"><h2>Audience timeline <small>Deterministic engagement</small></h2><div>{audienceTimeline.map((point) => <span key={point.id} style={{ height: `${point.height}%` }} title={`${point.height}% engagement index`} />)}</div><footer>09:00 · 10:00 · 11:00 · 12:00 · 13:00 · 14:00</footer></section>; }
export function AudienceDashboard() { return <section><AudienceSummary /><div className="sf-dashboard"><AudienceTimeline /><AudienceInsightsPanel /></div></section>; }
export function ModerationCard({ item }: { item: ModerationItem }) { return <article className="sf-moderation"><header><b><em>{platformBadge(item.platform)}</em> {item.author}</b><span>{item.status}</span></header><p>{item.message}</p><footer>{item.reason} · Future moderation action placeholder</footer></article>; }
export function ModerationQueue() { return <section className="sf-panel"><h2>Moderation queue <small>Needs review · Hidden · Reported · Spam · Blocked words · Muted users</small></h2>{moderationQueue.map((item) => <ModerationCard key={item.id} item={item} />)}</section>; }
export function CrossPublishingPanel() { return <section className="sf-panel"><h2>Publishing console</h2><p>Original Live</p><div className="sf-flow">Facebook ↓ LinkedIn ↓ Instagram ↓ X ↓ TikTok</div><small>Distribution planning metadata only — no publishing execution.</small></section>; }
export function CrossSharePanel() { return <CrossPublishingPanel />; }
export function CrossFollowPanel() { return <section className="sf-panel"><h2>Cross follow campaigns</h2>{campaigns.map((campaign) => <p className="campaign" key={campaign.id}>{campaign.label}<small>Campaign metadata</small></p>)}</section>; }
export function PlatformHealthDashboard() { return <section className="sf-panel"><h2>Platform health</h2><div className="health-list">{platforms.map((platform) => <p key={platform.id}><b>{platform.displayName}</b><span className={platform.status}>{platform.status}</span><small>{platform.healthMessage}</small></p>)}</div></section>; }
export function TrendingTopicsPanel() { return <section className="sf-panel"><h2>Trending topics</h2><div className="tags">{topics.map((topic) => <span key={topic.id}>{topic.label}</span>)}</div><small>Keywords · hashtags · requested features · FAQs</small></section>; }
export function SentimentPanel() { return <section className="sf-panel"><h2>Sentiment</h2><div className="sentiment-chart"><p><b>Positive</b><span style={{ width: '64%' }}>64%</span></p><p><b>Neutral</b><span style={{ width: '24%' }}>24%</span></p><p><b>Negative</b><span style={{ width: '8%' }}>8%</span></p><p><b>Unknown</b><span style={{ width: '4%' }}>4%</span></p></div></section>; }
export function AudienceInsightsPanel() { return <section className="sf-panel insights"><h2>Audience insights</h2><p>Most engaged: <b>TikTok</b></p><p>Peak conversation: <b>12:20 UTC</b></p><p>Creator participation: <b>14 contributors</b></p></section>; }
export function NotificationsPanel() { return <section className="sf-panel"><h2>Notifications</h2>{notifications.map((notification) => <p className="notification" key={notification.id}><b>{notification.ordinal}</b>{notification.label}</p>)}</section>; }
export function LiveEventsPanel() { return <section className="sf-panel"><h2>Live events</h2>{liveEvents.map((event) => <p className="event" key={event.id}><time>{event.time}</time>{event.label}</p>)}</section>; }
export function CommunityCRM() { const groups = groupCrm(); return <section className="sf-panel crm"><h2>Community CRM</h2>{Object.entries(groups).map(([segment, people]) => <div key={segment}><h3>{label(segment)} <small>{people.length}</small></h3>{people.map((person) => <p key={person.id}><b>{person.name}</b><span>{label(person.platform)} · {person.detail}</span></p>)}</div>)}</section>; }
export function AudienceSegmentPanel() { return <CommunityCRM />; }
export function AnalyticsPanel() { return <section className="sf-panel analytics"><h2>Cross analytics</h2><div className="analytics-grid"><b>Platform</b><b>Viewers</b><b>Growth</b><b>Comments</b><b>Shares</b><b>Watch time</b><b>Engagement</b><b>Retention</b>{analytics.map((row) => <Fragment key={row.platform}><span>{label(row.platform)}</span><span>{row.viewers.toLocaleString()}</span><span>+{row.growth}%</span><span>{row.comments.toLocaleString()}</span><span>{row.shares}</span><span>{row.watchTime}</span><span>{row.engagement}%</span><span>{row.retention}%</span></Fragment>)}</div></section>; }
export function SocialWorkbench() { const [tab, setTab] = useState<(typeof workbenchTabs)[number]['id']>('chat'); const content: Record<(typeof workbenchTabs)[number]['id'], ReactNode> = { chat: <UnifiedChat />, moderation: <ModerationQueue />, publishing: <CrossPublishingPanel />, share: <CrossSharePanel />, follow: <CrossFollowPanel />, crm: <CommunityCRM />, analytics: <AnalyticsPanel />, logs: <LiveEventsPanel /> }; return <section className="sf-workbench"><div role="tablist">{workbenchTabs.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>{content[tab]}</section>; }
export function SocialFabricWorkspace() { return <main className="social-fabric"><header className="sf-header"><div><p>SOCIAL FABRIC · v5.15.0</p><h1>Social Operations Center</h1><span>Unified audience operations across every social input and output · presentation only</span></div><b>LIVE AUDIENCE FABRIC <small>Deterministic metadata</small></b></header><PlatformOverview /><AudienceDashboard /><div className="sf-columns"><div><SocialWorkbench /></div><aside><PlatformHealthDashboard /><TrendingTopicsPanel /><SentimentPanel /><NotificationsPanel /></aside></div></main>; }
