'use client';
import {useMemo,useState,type ReactNode} from 'react'; import {analytics,audienceSummary,chatMessages,crmContacts,groupCrm,moderationQueue,platforms,type ChatMessage,type ModerationItem} from './social-metadata'; import './social-fabric.css';
const label=(value:string)=>value==='x'?'X':value.charAt(0).toUpperCase()+value.slice(1); const badge=(p:string)=>({youtube:'YT',facebook:'FB',tiktok:'TT',twitch:'TW',linkedin:'IN',instagram:'IG',x:'X',kick:'KI'}[p]??p);
export function PlatformCard({platform}:{platform:typeof platforms[number]}){return <article className="sf-platform"><header><b><i>{badge(platform.platform)}</i>{platform.displayName}</b><span className={platform.status}>{platform.status}</span></header><strong>{platform.viewerCount.toLocaleString()} <small>viewers</small></strong><p>{platform.commentsToday.toLocaleString()} comments · {platform.sharesToday.toLocaleString()} shares</p><footer>{platform.healthMessage}</footer></article>}
export function PlatformOverview(){return <section><div className="sf-section-title"><h2>Platform overview</h2><span>8 deterministic social surfaces</span></div><div className="sf-platforms">{platforms.map(platform=><PlatformCard key={platform.id} platform={platform}/>)}</div></section>}
export function UnifiedChatMessage({item}:{item:ChatMessage}){return <article className="sf-message"><i className="avatar">{item.username.charAt(0)}</i><div><header><b><em>{badge(item.platform)}</em> {item.username}</b><time>{item.timestamp}</time></header><p>{item.message}</p><footer><span className={item.sentiment}>{item.sentiment}</span><span>{item.moderation}</span><button>Reply target: {label(item.platform)}</button><button>Highlight</button><button>Pin</button></footer></div></article>}
export function UnifiedChat(){const [query,setQuery]=useState('');const messages=useMemo(()=>chatMessages.filter(x=>`${x.username} ${x.message} ${x.platform}`.toLowerCase().includes(query.toLowerCase())),[query]);return <section className="sf-panel chat"><header><div><h2>Unified Chat</h2><small>All incoming audience conversations · metadata only</small></div><input aria-label="Search unified chat" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversation"/></header><div className="sf-message-list">{messages.map(item=><UnifiedChatMessage key={item.id} item={item}/>)}</div></section>}
export function AudienceSummary(){const s=audienceSummary();return <section className="sf-summary">{[['Total viewers',s.viewers.toLocaleString()],['Total comments',s.comments.toLocaleString()],['Total reactions',s.reactions.toLocaleString()],['Average engagement',`${s.engagement.toFixed(1)}%`],['Fastest growing',label(s.fastest)],['Highest retention',label(s.retention)],['Most active',label(s.active)],['Top region',s.region]].map(([name,value])=><article key={name}><small>{name}</small><b>{value}</b></article>)}</section>}
export function AudienceTimeline(){return <section className="sf-panel timeline"><h2>Audience timeline <small>Deterministic engagement</small></h2><div>{[32,48,43,67,59,75,72,88,81,94,86,100].map((height,i)=><span key={i} style={{height:`${height}%`}} title={`${height}% engagement index`}/>)}</div><footer>09:00 · 10:00 · 11:00 · 12:00 · 13:00 · 14:00</footer></section>}
export function AudienceDashboard(){return <section><AudienceSummary/><div className="sf-dashboard"><AudienceTimeline/><AudienceInsightsPanel/></div></section>}
export function ModerationCard({item}:{item:ModerationItem}){return <article className="sf-moderation"><header><b><em>{badge(item.platform)}</em> {item.author}</b><span>{item.status}</span></header><p>{item.message}</p><footer>{item.reason} · Future moderation action placeholder</footer></article>}
export function ModerationQueue(){return <section className="sf-panel"><h2>Moderation queue <small>Needs review · Hidden · Reported · Spam · Blocked words · Muted users</small></h2>{moderationQueue.map(item=><ModerationCard key={item.id} item={item}/>)}</section>}
export function CrossPublishingPanel(){return <section className="sf-panel"><h2>Publishing console</h2><p>Original Live</p><div className="sf-flow">Facebook ↓ LinkedIn ↓ Instagram ↓ X ↓ TikTok</div><small>Distribution planning metadata only — no publishing execution.</small></section>}; export function CrossSharePanel(){return <CrossPublishingPanel/>};
export function CrossFollowPanel(){return <section className="sf-panel"><h2>Cross follow campaigns</h2>{['YouTube audience → Follow TikTok','Facebook audience → Follow Instagram','LinkedIn audience → Follow YouTube'].map(x=><p className="campaign" key={x}>{x}<small>Campaign metadata</small></p>)}</section>}
export function PlatformHealthDashboard(){return <section className="sf-panel"><h2>Platform health</h2><div className="health-list">{platforms.map(x=><p key={x.id}><b>{x.displayName}</b><span className={x.status}>{x.status}</span><small>{x.healthMessage}</small></p>)}</div></section>}
export function TrendingTopicsPanel(){return <section className="sf-panel"><h2>Trending topics</h2><div className="tags">{['#UBOSLive','production workflow','guest timing','audio quality','multistreaming','scene templates','When is the next guest?'].map(x=><span key={x}>{x}</span>)}</div><small>Keywords · hashtags · requested features · FAQs</small></section>}
export function SentimentPanel(){return <section className="sf-panel"><h2>Sentiment</h2><div className="sentiment-chart"><p><b>Positive</b><span style={{width:'64%'}}>64%</span></p><p><b>Neutral</b><span style={{width:'24%'}}>24%</span></p><p><b>Negative</b><span style={{width:'8%'}}>8%</span></p><p><b>Unknown</b><span style={{width:'4%'}}>4%</span></p></div></section>}
export function AudienceInsightsPanel(){return <section className="sf-panel insights"><h2>Audience insights</h2><p>Most engaged: <b>TikTok</b></p><p>Peak conversation: <b>12:20 UTC</b></p><p>Creator participation: <b>14 contributors</b></p></section>}
export function NotificationsPanel(){return <section className="sf-panel"><h2>Notifications</h2>{['TikTok stream unhealthy.','New subscriber on YouTube.','Facebook comments increasing.','Moderator required for one comment.'].map((x,i)=><p className="notification" key={x}><b>{i+1}</b>{x}</p>)}</section>}
export function LiveEventsPanel(){return <section className="sf-panel"><h2>Live events</h2>{['Live Started','New Subscriber','Gift Received','Poll Created','Milestone Reached','Moderator Action'].map((x,i)=><p className="event" key={x}><time>12:{20-i} UTC</time>{x}</p>)}</section>}
export function CommunityCRM(){const groups=groupCrm();return <section className="sf-panel crm"><h2>Community CRM</h2>{Object.entries(groups).map(([segment,people])=><div key={segment}><h3>{label(segment)} <small>{people.length}</small></h3>{people.map(person=><p key={person.id}><b>{person.name}</b><span>{label(person.platform)} · {person.detail}</span></p>)}</div>)}</section>}
export function AudienceSegmentPanel(){return <CommunityCRM/>}
export function AnalyticsPanel(){return <section className="sf-panel analytics"><h2>Cross analytics</h2><div className="analytics-grid"><b>Platform</b><b>Viewers</b><b>Growth</b><b>Comments</b><b>Shares</b><b>Watch time</b><b>Engagement</b><b>Retention</b>{analytics.map(x=><div key={`analytics-${x.platform}`} className="analytics-row"><span key={`${x.platform}n`}>{label(x.platform)}</span><span key={`${x.platform}v`}>{x.viewers.toLocaleString()}</span><span key={`${x.platform}g`}>+{x.growth}%</span><span key={`${x.platform}c`}>{x.comments.toLocaleString()}</span><span key={`${x.platform}s`}>{x.shares}</span><span key={`${x.platform}w`}>{x.watchTime}</span><span key={`${x.platform}e`}>{x.engagement}%</span><span key={`${x.platform}r`}>{x.retention}%</span></div>)}</div></section>}
export function SocialWorkbench(){const [tab,setTab]=useState('Unified Chat');const tabs=['Unified Chat','Moderation','Publishing','Cross Share','Cross Follow','CRM','Analytics','Logs'];const content:Record<string,ReactNode>={'Unified Chat':<UnifiedChat/>,Moderation:<ModerationQueue/>,Publishing:<CrossPublishingPanel/>,'Cross Share':<CrossSharePanel/>,'Cross Follow':<CrossFollowPanel/>,CRM:<CommunityCRM/>,Analytics:<AnalyticsPanel/>,Logs:<LiveEventsPanel/>};return <section className="sf-workbench"><div role="tablist">{tabs.map(x=><button key={x} role="tab" aria-selected={tab===x} onClick={()=>setTab(x)}>{x}</button>)}</div>{content[tab]}</section>}
export function SocialFabricWorkspace(){return <main className="social-fabric"><header className="sf-header"><div><p>SOCIAL FABRIC · v5.15.0</p><h1>Social Operations Center</h1><span>Unified audience operations across every social input and output · presentation only</span></div><b>LIVE AUDIENCE FABRIC <small>Deterministic metadata</small></b></header><PlatformOverview/><AudienceDashboard/><div className="sf-columns"><div><SocialWorkbench/></div><aside><PlatformHealthDashboard/><TrendingTopicsPanel/><SentimentPanel/><NotificationsPanel/></aside></div></main>}
