import type { AudienceSegment, PlatformMetadata, SocialPlatform } from '@ubos/shared';
export type Sentiment='positive'|'neutral'|'negative'|'unknown'; export type ModerationStatus='visible'|'needs-review'|'hidden'|'reported'|'spam';
export interface ChatMessage {id:string;platform:SocialPlatform;username:string;timestamp:string;message:string;sentiment:Sentiment;moderation:ModerationStatus}
export interface ModerationItem {id:string;platform:SocialPlatform;author:string;message:string;status:Exclude<ModerationStatus,'visible'>;reason:string}
export interface AnalyticsRow {platform:SocialPlatform;viewers:number;growth:number;comments:number;shares:number;watchTime:string;engagement:number;retention:number}
export interface CrmContact {id:string;name:string;segment:AudienceSegment;platform:SocialPlatform;detail:string}
const p=(id:string,platform:SocialPlatform,displayName:string,status:PlatformMetadata['status'],viewerCount:number,followers:number,commentsToday:number,sharesToday:number,likesToday:number,healthMessage:string):PlatformMetadata=>({id,platform,displayName,status,connected:status!=='offline',viewerCount,followers,commentsToday,sharesToday,likesToday,healthMessage});
export const platforms:readonly PlatformMetadata[]=[p('youtube','youtube','YouTube','healthy',18420,92800,2340,482,15120,'Excellent delivery'),p('facebook','facebook','Facebook','healthy',9430,55400,1880,362,8250,'Comments accelerating'),p('tiktok','tiktok','TikTok','warning',12780,102000,3210,714,22180,'Delivery quality requires review'),p('twitch','twitch','Twitch','healthy',4130,21800,970,66,4020,'Community active'),p('linkedin','linkedin','LinkedIn','healthy',2860,42100,412,93,1940,'Professional audience engaged'),p('instagram','instagram','Instagram','offline',0,78800,0,0,0,'Presentation connection unavailable'),p('x','x','X','healthy',3640,35200,622,287,3210,'Conversation healthy'),p('kick','kick','Kick','healthy',1180,9200,244,31,1080,'Creator community active')] as const;
export const chatMessages:readonly ChatMessage[]=[{id:'m1',platform:'youtube',username:'John',timestamp:'12:24',message:'This looks amazing.',sentiment:'positive',moderation:'visible'},{id:'m2',platform:'facebook',username:'Sarah',timestamp:'12:23',message:'Audio is perfect.',sentiment:'positive',moderation:'visible'},{id:'m3',platform:'tiktok',username:'Chris',timestamp:'12:22',message:'When is the next guest?',sentiment:'neutral',moderation:'visible'},{id:'m4',platform:'twitch',username:'NovaLive',timestamp:'12:21',message:'Love this production workflow!',sentiment:'positive',moderation:'visible'},{id:'m5',platform:'x',username:'Mira',timestamp:'12:20',message:'Could you repeat that feature?',sentiment:'neutral',moderation:'needs-review'},{id:'m6',platform:'facebook',username:'SpamBot',timestamp:'12:19',message:'Click my profile for offers',sentiment:'negative',moderation:'spam'}] as const;
export const moderationQueue:readonly ModerationItem[]=[{id:'q1',platform:'x',author:'Mira',message:'Could you repeat that feature?',status:'needs-review',reason:'Manual review'},{id:'q2',platform:'facebook',author:'SpamBot',message:'Click my profile for offers',status:'spam',reason:'Spam pattern'},{id:'q3',platform:'tiktok',author:'ChannelWatch',message:'Reported by viewer',status:'reported',reason:'Reported'},{id:'q4',platform:'youtube',author:'OldThread',message:'Hidden comment retained for audit',status:'hidden',reason:'Hidden'}] as const;
export const analytics:readonly AnalyticsRow[]=platforms.map((x,i)=>({platform:x.platform,viewers:x.viewerCount,growth:[12,8,18,5,7,0,9,4][i]!,comments:x.commentsToday,shares:x.sharesToday,watchTime:['14m 22s','11m 48s','8m 16s','19m 02s','16m 31s','—','7m 44s','12m 08s'][i]!,engagement:[8.7,7.2,11.4,9.1,6.8,0,8.4,7.6][i]!,retention:[72,68,54,79,75,0,61,70][i]!}));
export const crmContacts:readonly CrmContact[]=[{id:'c1',name:'Avery Chen',segment:'vip',platform:'youtube',detail:'Top conversation starter'},{id:'c2',name:'Jordan Lee',segment:'subscriber',platform:'twitch',detail:'18-month subscriber'},{id:'c3',name:'Samira Cole',segment:'donor',platform:'tiktok',detail:'Gift supporter'},{id:'c4',name:'Morgan Fox',segment:'moderator',platform:'facebook',detail:'Trusted moderator'},{id:'c5',name:'Rae Kim',segment:'guest',platform:'linkedin',detail:'Upcoming guest'},{id:'c6',name:'Northstar',segment:'sponsor',platform:'x',detail:'Campaign partner'},{id:'c7',name:'Taylor Wu',segment:'returning',platform:'youtube',detail:'12 live events attended'},{id:'c8',name:'Drew Park',segment:'future-lead',platform:'instagram',detail:'Requested follow-up'}] as const;
export function audienceSummary(rows:readonly AnalyticsRow[]=analytics){const active=rows.filter(x=>x.viewers>0);return {viewers:rows.reduce((n,x)=>n+x.viewers,0),comments:rows.reduce((n,x)=>n+x.comments,0),reactions:platforms.reduce((n,x)=>n+x.likesToday,0),engagement:active.reduce((n,x)=>n+x.engagement,0)/active.length,fastest:active.reduce((a,b)=>a.growth>b.growth?a:b).platform,retention:active.reduce((a,b)=>a.retention>b.retention?a:b).platform,active:active.reduce((a,b)=>a.comments>b.comments?a:b).platform,region:'United States'};}
export function groupChat(messages:readonly ChatMessage[]=chatMessages){return messages.reduce<Record<string,ChatMessage[]>>((groups,item)=>{(groups[item.platform]??=[]).push(item);return groups;},{});}
export function groupCrm(contacts:readonly CrmContact[]=crmContacts){return contacts.reduce<Record<string,CrmContact[]>>((groups,item)=>{(groups[item.segment]??=[]).push(item);return groups;},{});}
