import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
import { createProductionRuntime, RuntimeSupervisor, type RuntimeSubsystem } from '../production-runtime/index.js';

declare const process: { env: Record<string,string|undefined> } | undefined;
const now=()=>new Date().toISOString();
export type AudioBusKind='master'|'program'|'preview'|'monitor'|'guest'|'operator'|'aux'|'recording'|'streaming';
export type AudioEffectKind='noise_gate'|'compressor'|'limiter'|'eq'|'high_pass'|'low_pass'|'delay'|'expander'|'ducker';
export type AudioHealthStatus='healthy'|'degraded'|'critical'|'unavailable';
export interface ChannelControls{readonly mute:boolean;readonly solo:boolean;readonly gain:number;readonly balance:number;readonly trim:number;readonly pan:number;readonly delayMs:number;readonly phase:number;readonly invert:boolean;}
export interface AudioEffect{readonly id:string;readonly kind:AudioEffectKind;readonly enabled:boolean;readonly order:number;readonly parameters:Readonly<Record<string,number|string|boolean>>;readonly containsRuntimeHandles:false;}
export interface AudioMeter{readonly vu:number;readonly peakDb:number;readonly rmsDb:number;readonly lufs:number;readonly truePeakDb:number;readonly clipped:boolean;readonly noiseFloorDb:number;readonly dynamicRangeDb:number;}
export interface AudioChannel{readonly id:string;readonly sourceId:string;readonly label:string;readonly groupId?:string;readonly controls:ChannelControls;readonly effects:readonly AudioEffect[];readonly routes:readonly string[];readonly meter:AudioMeter;readonly containsRuntimeHandles:false;}
export interface AudioBus{readonly id:string;readonly kind:AudioBusKind;readonly label:string;readonly gain:number;readonly delayMs:number;readonly protected:boolean;readonly routes:readonly string[];readonly effects:readonly AudioEffect[];readonly meter:AudioMeter;readonly containsRuntimeHandles:false;}
export interface AudioGroup{readonly id:string;readonly label:string;readonly channelIds:readonly string[];readonly gain:number;readonly mute:boolean;readonly solo:boolean;}
export interface AudioMatrixSnapshot{readonly routes:readonly {from:string;to:string;gain:number;enabled:boolean}[];readonly containsRuntimeHandles:false;}
export interface MixMinusTarget{readonly id:string;readonly role:'host'|'guest'|'operator'|'remote_contributor';readonly sourceChannelId:string;readonly busId:string;readonly excludedSourceIds:readonly string[];readonly noEcho:true;}
export interface AudioReplayEvent{readonly id:string;readonly timestamp:string;readonly type:'gain'|'mute'|'solo'|'bus_route'|'delay'|'effect';readonly targetId:string;readonly payload:Readonly<Record<string,string|number|boolean>>;readonly containsRuntimeHandles:false;}
export interface AudioFailure{readonly code:string;readonly message:string;readonly retryable:boolean;readonly occurredAt:string;readonly ubosFailure:UBOSFailure;}
export interface AudioSession{readonly id:string;readonly enabled:boolean;readonly mode:'real'|'mock';readonly graphRevision:number;readonly buses:readonly AudioBus[];readonly channels:readonly AudioChannel[];readonly groups:readonly AudioGroup[];readonly matrix:AudioMatrixSnapshot;readonly mixMinus:readonly MixMinusTarget[];readonly replay:readonly AudioReplayEvent[];readonly failures:readonly AudioFailure[];readonly warnings:readonly string[];readonly containsRuntimeHandles:false;}
export interface AudioStatistics{readonly channelCount:number;readonly busCount:number;readonly activeRoutes:number;readonly queuedEffectChanges:number;readonly processingLoad:number;readonly diagnosticsThrottled:boolean;readonly prioritizedBuses:readonly string[];}
export interface AudioHealth{readonly status:AudioHealthStatus;readonly summary:string;readonly statistics:AudioStatistics;readonly latestFailure?:AudioFailure;}
const defaultControls:ChannelControls={mute:false,solo:false,gain:1,balance:0,trim:0,pan:0,delayMs:0,phase:0,invert:false};
const silentMeter:AudioMeter={vu:0,peakDb:-Infinity,rmsDb:-Infinity,lufs:-70,truePeakDb:-Infinity,clipped:false,noiseFloorDb:-70,dynamicRangeDb:0};
const busKinds:AudioBusKind[]=['master','program','preview','monitor','guest','operator','aux','recording','streaming'];
export function isRealAudioEnabled(env:Record<string,string|undefined>=typeof process!=='undefined'?process.env:{}){return env.UBOS_ENABLE_REAL_AUDIO==='true'||env.NEXT_PUBLIC_UBOS_REAL_AUDIO==='true';}
export function createAudioBus(kind:AudioBusKind,input:Partial<AudioBus>={}):AudioBus{return Object.freeze({id:input.id??`bus:${kind}`,kind,label:input.label??`${kind} bus`,gain:input.gain??1,delayMs:input.delayMs??0,protected:input.protected??['master','program','monitor'].includes(kind),routes:input.routes??[],effects:input.effects??[],meter:input.meter??silentMeter,containsRuntimeHandles:false});}
export function createAudioChannel(input:{id:string;sourceId:string;label?:string;routes?:readonly string[];controls?:Partial<ChannelControls>;effects?:readonly AudioEffect[];groupId?:string}):AudioChannel{return Object.freeze({id:input.id,sourceId:input.sourceId,label:input.label??input.id,...(input.groupId?{groupId:input.groupId}:{}),controls:{...defaultControls,...input.controls},effects:input.effects??[],routes:input.routes??['bus:program'],meter:silentMeter,containsRuntimeHandles:false});}
export function createDefaultBuses(){return busKinds.map((k)=>createAudioBus(k));}
export class AudioValidator{validateGain(v:number){return Number.isFinite(v)&&v>=0&&v<=4;} validateDelay(v:number){return Number.isFinite(v)&&v>=0&&v<=2000;} validateRouting(buses:readonly AudioBus[],channels:readonly AudioChannel[],matrix:AudioMatrixSnapshot){const ids=new Set([...buses.map(b=>b.id),...channels.map(c=>c.id)]);const errors:string[]=[];for(const r of matrix.routes){if(!ids.has(r.from)||!ids.has(r.to))errors.push(`Invalid route ${r.from}->${r.to}`);if(r.from===r.to)errors.push(`Circular route ${r.from}`);if(buses.find(b=>b.id===r.from)?.protected&&buses.find(b=>b.id===r.to)?.protected)errors.push('Protected bus loop rejected');if(!this.validateGain(r.gain))errors.push('Invalid route gain');}return{valid:errors.length===0,warnings:[],errors};} validateSession(s:AudioSession){return this.validateRouting(s.buses,s.channels,s.matrix);}}
export class AudioMatrix{routes:AudioMatrixSnapshot['routes']=[];connect(from:string,to:string,gain=1){this.routes=[...this.routes.filter(r=>!(r.from===from&&r.to===to)),{from,to,gain,enabled:true}];return this.snapshot();}disconnect(from:string,to:string){this.routes=this.routes.filter(r=>!(r.from===from&&r.to===to));return this.snapshot();}snapshot():AudioMatrixSnapshot{return Object.freeze({routes:this.routes,containsRuntimeHandles:false});}}
export class MixMinusManager{create(input:Omit<MixMinusTarget,'excludedSourceIds'|'noEcho'> & {allSourceIds:readonly string[]}):MixMinusTarget{const {allSourceIds,...rest}=input;return Object.freeze({...rest,excludedSourceIds:allSourceIds.filter(id=>id===input.sourceChannelId),noEcho:true});} autoRoute(channels:readonly AudioChannel[],targets:readonly MixMinusTarget[]):AudioMatrixSnapshot{return Object.freeze({routes:targets.flatMap(t=>channels.filter(c=>c.id!==t.sourceChannelId).map(c=>({from:c.id,to:t.busId,gain:1,enabled:true}))),containsRuntimeHandles:false});}}
export class AudioMonitor{meter(input:Partial<AudioMeter>={}):AudioMeter{return Object.freeze({...silentMeter,...input});} summarize(session:AudioSession):AudioHealth{return new AudioHealthRuntime().summarize(session);}}
export class AudioStatisticsRuntime{collect(session:AudioSession,queuedEffectChanges=0):AudioStatistics{return Object.freeze({channelCount:session.channels.length,busCount:session.buses.length,activeRoutes:session.matrix.routes.filter(r=>r.enabled).length,queuedEffectChanges,processingLoad:Math.min(1,(session.channels.length*0.03)+(session.matrix.routes.length*0.01)),diagnosticsThrottled:session.channels.length>32||queuedEffectChanges>16,prioritizedBuses:['bus:program','bus:master']});}}
export class AudioHealthRuntime{summarize(session:AudioSession):AudioHealth{const statistics=new AudioStatisticsRuntime().collect(session);const latestFailure=session.failures.at(-1);const status:AudioHealthStatus=latestFailure&&!latestFailure.retryable?'critical':statistics.processingLoad>0.8?'degraded':'healthy';return Object.freeze({status,summary:`Audio ${status}: ${statistics.channelCount} channels, ${statistics.activeRoutes} routes`,statistics,...(latestFailure?{latestFailure}: {})});}}
export class AudioRecovery{plan(message:string):AudioFailure{return {code:'AUDIO_RUNTIME_FAILURE',message,retryable:true,occurredAt:now(),ubosFailure:createFailureRecord({category:'EXECUTION_FAILURE',sourceLayer:'execution',subsystem:'audio-runtime',message,recoverable:true,metadata:{runtimeSupervised:true,graphMutationAllowed:false}})};}}
const replay=(type:AudioReplayEvent['type'],targetId:string,payload:Record<string,string|number|boolean>):AudioReplayEvent=>Object.freeze({id:`audio-replay:${type}:${Date.now()}`,timestamp:now(),type,targetId,payload,containsRuntimeHandles:false});
export class AudioMixer{readonly validator=new AudioValidator(); readonly monitor=new AudioMonitor(); readonly matrix=new AudioMatrix(); readonly mixMinus=new MixMinusManager(); readonly queuedEffects:AudioEffect[]=[]; createSession(input:{id:string;graphRevision?:number;channels?:readonly AudioChannel[];env?:Record<string,string|undefined>}):AudioSession{const buses=createDefaultBuses();const matrix:AudioMatrixSnapshot=Object.freeze({routes:(input.channels??[]).flatMap(c=>c.routes.map(to=>({from:c.id,to,gain:c.controls.gain,enabled:!c.controls.mute}))),containsRuntimeHandles:false});return Object.freeze({id:input.id,enabled:isRealAudioEnabled(input.env),mode:isRealAudioEnabled(input.env)?'real':'mock',graphRevision:input.graphRevision??0,buses,channels:input.channels??[],groups:[],matrix,mixMinus:[],replay:[],failures:[],warnings:isRealAudioEnabled(input.env)?[]:['Real audio disabled; using mock audio runtime'],containsRuntimeHandles:false});} setGain(s:AudioSession,id:string,gain:number){if(!this.validator.validateGain(gain))throw new Error('Invalid gain range');return this.patchChannel(s,id,{controls:{...this.mustChannel(s,id).controls,gain}},replay('gain',id,{gain}));} setMute(s:AudioSession,id:string,mute:boolean){return this.patchChannel(s,id,{controls:{...this.mustChannel(s,id).controls,mute}},replay('mute',id,{mute}));} setSolo(s:AudioSession,id:string,solo:boolean){return this.patchChannel(s,id,{controls:{...this.mustChannel(s,id).controls,solo}},replay('solo',id,{solo}));} setDelay(s:AudioSession,id:string,delayMs:number){if(!this.validator.validateDelay(delayMs))throw new Error('Invalid delay range');return this.patchChannel(s,id,{controls:{...this.mustChannel(s,id).controls,delayMs}},replay('delay',id,{delayMs}));} addEffect(s:AudioSession,id:string,effect:AudioEffect){this.queuedEffects.push(effect);return this.patchChannel(s,id,{effects:[...this.mustChannel(s,id).effects,effect]},replay('effect',id,{effectId:effect.id,enabled:effect.enabled}));} route(s:AudioSession,from:string,to:string,gain=1){const matrix=Object.freeze({routes:[...s.matrix.routes,{from,to,gain,enabled:true}],containsRuntimeHandles:false});const check=this.validator.validateRouting(s.buses,s.channels,matrix);if(!check.valid)throw new Error(check.errors.join('; '));return Object.freeze({...s,matrix,replay:[...s.replay,replay('bus_route',from,{to,gain})],containsRuntimeHandles:false});} private mustChannel(s:AudioSession,id:string){const c=s.channels.find(x=>x.id===id);if(!c)throw new Error(`Audio channel ${id} not found`);return c;} private patchChannel(s:AudioSession,id:string,patch:Partial<AudioChannel>,event:AudioReplayEvent){return Object.freeze({...s,channels:s.channels.map(c=>c.id===id?Object.freeze({...c,...patch,containsRuntimeHandles:false}):c),replay:[...s.replay,event],containsRuntimeHandles:false});}}
export class AudioRuntime{readonly mixer=new AudioMixer(); readonly monitor=new AudioMonitor(); readonly statistics=new AudioStatisticsRuntime(); readonly health=new AudioHealthRuntime(); readonly recovery=new AudioRecovery(); readonly validator=new AudioValidator(); readonly supervisor=new RuntimeSupervisor(createProductionRuntime({id:'audio-production-runtime'})); private session?:AudioSession; constructor(private readonly env:Record<string,string|undefined>=typeof process!=='undefined'?process.env:{}){this.supervisor.register(this.subsystem('idle'));} create(input:{id:string;graphRevision?:number;channels?:readonly AudioChannel[]}){this.session=this.mixer.createSession({...input,env:this.env});this.supervisor.register(this.subsystem('ready',this.session));return this.session;} start(){this.supervisor.register(this.subsystem('running',this.session));return this.supervisor.start();} stop(){return this.supervisor.stop();} getSession(){return this.session;} fail(message:string){const f=this.recovery.plan(message);if(this.session)this.session=Object.freeze({...this.session,failures:[...this.session.failures,f],containsRuntimeHandles:false});this.supervisor.failSubsystem('audio-runtime',message);return f;} private subsystem(state:RuntimeSubsystem['state'],session?:AudioSession):RuntimeSubsystem{return {id:'audio-runtime',type:'audio',label:'Professional Audio Mixing Runtime',required:false,state,health:session?.failures.length?'failed':state==='running'||state==='ready'?'healthy':'degraded',degradedModes:[],diagnostics:session?{...this.statistics.collect(session)}:{featureFlag:isRealAudioEnabled(this.env)},...(session?{latestGraphRevision:session.graphRevision}: {})};}}
export { AudioMixer as ProfessionalAudioMixer };
