import { AlertSeverity, HealthStatus, redact } from '../observability/index.js';

export enum ChangeType { ApplicationRelease='application_release', ServiceRelease='service_release', PluginUpdate='plugin_update', ConfigurationChange='configuration_change', SceneChange='scene_change', WorkflowChange='workflow_change', RuleChange='rule_change', AuthorizationChange='authorization_change', InfrastructureChange='infrastructure_change', DatabaseMigration='database_migration', DeviceFirmware='device_firmware', DestinationChange='destination_change', CredentialRotation='credential_rotation', EmergencyFix='emergency_fix', Rollback='rollback' }
export enum ChangeRiskLevel { Low='low', Moderate='moderate', High='high', Critical='critical' }
export enum ChangeStatus { Draft='draft', Submitted='submitted', Assessing='assessing', Testing='testing', AwaitingApproval='awaiting_approval', Approved='approved', Scheduled='scheduled', Deploying='deploying', Validating='validating', Monitoring='monitoring', Completed='completed', Failed='failed', RollingBack='rolling_back', RolledBack='rolled_back', Rejected='rejected', Cancelled='cancelled' }
export enum ReleaseChannel { Development='development', Experimental='experimental', Internal='internal', Beta='beta', ReleaseCandidate='release_candidate', Stable='stable', LongTermSupport='long_term_support', Emergency='emergency' }
export enum ReleaseStatus { Building='building', Validating='validating', Ready='ready', Approved='approved', Deploying='deploying', Active='active', Superseded='superseded', Withdrawn='withdrawn', Failed='failed', RolledBack='rolled_back' }
export enum CompatibilityStatus { Compatible='compatible', CompatibleWithWarnings='compatible_with_warnings', MigrationRequired='migration_required', Incompatible='incompatible', Unknown='unknown' }
export enum RolloutStrategyType { Immediate='immediate', Rolling='rolling', Canary='canary', BlueGreen='blue_green', Shadow='shadow', PercentageBased='percentage_based', SiteBySite='site_by_site', ProductionByProduction='production_by_production', Manual='manual' }
export enum FeatureFlagType { Boolean='boolean', Percentage='percentage', Variant='variant', ProductionScoped='production_scoped', SiteScoped='site_scoped', RoleScoped='role_scoped', EnvironmentScoped='environment_scoped', TimeWindow='time_window', EmergencyKillSwitch='emergency_kill_switch' }
export enum FeatureFlagStatus { Draft='draft', Active='active', Disabled='disabled', Expired='expired', Retired='retired' }
export enum DeploymentGateType { TestResult='test_result', Approval='approval', Health='health', Capacity='capacity', Compatibility='compatibility', Backup='backup', Incident='incident', Schedule='schedule', ManualConfirmation='manual_confirmation', Security='security', Audit='audit' }
export enum DeploymentStatus { Planned='planned', Running='running', Paused='paused', Observing='observing', Completed='completed', Failed='failed', RollingBack='rolling_back', RolledBack='rolled_back' }
export enum PromotionStatus { Requested='requested', Approved='approved', Completed='completed', Rejected='rejected', Failed='failed' }

export interface ChangeComponent { id:string; type:string; version?:string; metadata?:Record<string,unknown>; }
export interface ChangeRequest { id:string; title:string; description:string; type:ChangeType; riskLevel:ChangeRiskLevel; requestedBy:string; requestedAt:number; affectedEnvironments:string[]; affectedProductions?:string[]; affectedComponents:ChangeComponent[]; reason:string; expectedBenefit:string; impactAssessmentId?:string; testPlanId?:string; rollbackPlanId?:string; approvalPolicyId?:string; status:ChangeStatus; scheduledWindowId?:string; releaseId?:string; generation:number; }
export interface ChangeImpactAssessment { id:string; changeRequestId:string; affectedServices:string[]; affectedProductions:string[]; affectedUsers:string[]; affectedSites:string[]; expectedDowntimeMs?:number; expectedDegradation?:string[]; dependencies:string[]; compatibilityRisks:string[]; failureModes:string[]; rollbackFeasibility:string; riskScore:number; confidence:number; assessedBy:string; assessedAt:number; }
export interface ChangeApprovalPolicy { id:string; minimumRiskLevel:ChangeRiskLevel; requiredRoles:string[]; requiredApprovalCount:number; prohibitSelfApproval:boolean; requireTestEvidence:boolean; requireRollbackPlan:boolean; requireImpactAssessment:boolean; }
export interface ChangeApproval { id:string; changeRequestId:string; approverId:string; roles:string[]; approved:boolean; reason?:string; approvedAt:number; }
export interface ChangeTestPlan { id:string; changeRequestId:string; evidenceIds:string[]; requiredEnvironments:string[]; passCriteria:string[]; result:'pending'|'passed'|'failed'; completedAt?:number; }
export interface ReleaseComponent { id:string; name:string; version:string; type:string; hash:string; signature?:string; dependencies?:string[]; }
export interface ReleaseManifest { id:string; version:string; components:ReleaseComponent[]; sourceCommit:string; dependencyVersions:Record<string,string>; schemaRequirements:string[]; migrationIds:string[]; featureFlagIds:string[]; checksums:string[]; signatures:string[]; supportedEnvironments:string[]; rollbackCompatible:boolean; knownIssues:string[]; validationResults:string[]; sbom:string[]; provenance:string; }
export interface Release { id:string; name:string; version:string; channel:ReleaseChannel; components:ReleaseComponent[]; manifestId:string; createdAt:number; createdBy:string; status:ReleaseStatus; changeRequestIds:string[]; }
export interface CompatibilityEntry { component:string; status:CompatibilityStatus; reason:string; }
export interface CompatibilityMatrix { component:string; currentVersion:string; targetVersion:string; compatibleWith:CompatibilityEntry[]; minimumSchemaVersion?:string; maximumSchemaVersion?:string; rollbackSupported:boolean; }
export interface DeploymentWindow { id:string; name:string; startsAt:number; endsAt:number; timezone:string; allowedRiskLevels:ChangeRiskLevel[]; allowedEnvironments:string[]; approvalRequired:boolean; }
export interface ChangeFreeze { id:string; name:string; startsAt:number; endsAt:number; scope:string[]; blockedRiskLevels:ChangeRiskLevel[]; exceptionsRequireApproval:boolean; reason:string; approvedExceptionChangeIds?:string[]; }
export interface DeploymentGate { id:string; name:string; type:DeploymentGateType; required:boolean; evaluation:string; passed?:boolean; evidenceIds?:string[]; }
export interface DeploymentStep { id:string; target:string; action:string; status?:'pending'|'complete'|'failed'|'skipped'; executedAt?:number; }
export interface DeploymentPlan { id:string; releaseId:string; targetEnvironment:string; targetSites:string[]; targetNodes:string[]; strategy:RolloutStrategyType; steps:DeploymentStep[]; gates:DeploymentGate[]; rollbackPlanId:string; estimatedDurationMs?:number; }
export interface DeploymentExecution { id:string; planId:string; status:DeploymentStatus; completedStepIds:string[]; failedStepId?:string; startedAt:number; updatedAt:number; observationUntil?:number; gateResults:DeploymentGate[]; rollbackStarted?:boolean; }
export interface RollbackPlan { id:string; releaseId:string; triggerConditions:string[]; steps:string[]; estimatedDurationMs?:number; dataRecoveryRequired:boolean; validationChecks:string[]; approvalRequired:boolean; compatibleVersions:string[]; }
export interface FeatureFlagRule { scope:Record<string,string>; value:unknown; percentage?:number; startsAt?:number; endsAt?:number; }
export interface FeatureFlag { id:string; name:string; description?:string; type:FeatureFlagType; defaultValue:unknown; rules:FeatureFlagRule[]; riskLevel:ChangeRiskLevel; ownerId:string; createdAt:number; expiresAt?:number; status:FeatureFlagStatus; audit:string[]; lastKnownGood?:unknown; }
export interface EnvironmentPromotion { id:string; releaseId:string; sourceEnvironment:string; targetEnvironment:string; requestedAt:number; requestedBy:string; validationResults:string[]; approvalRequestId?:string; status:PromotionStatus; }
export interface SchemaMigration { id:string; name:string; fromVersion:string; toVersion:string; forwardSteps:string[]; rollbackSteps?:string[]; backwardCompatible:boolean; reversible:boolean; checkpoint?:string; estimatedDurationMs?:number; }
export interface ReleaseEvidence { id:string; releaseId:string; changeRequestIds:string[]; approvalIds:string[]; testEvidenceIds:string[]; gateEvidenceIds:string[]; rollbackActions:string[]; operatorNotes:string[]; finalOutcome:string; }
export interface ConfigurationDrift { sourceEnvironment:string; targetEnvironment:string; differences:string[]; severity:'expected'|'approved'|'temporary'|'unauthorized'|'critical'; detectedAt:number; approvedExceptionId?:string; }
export interface ReleaseReadinessScore { releaseId:string; testScore:number; compatibilityScore:number; securityScore:number; rollbackScore:number; operationalScore:number; overallScore:number; blockers:string[]; warnings:string[]; }
export interface ChangeManagementSnapshot { changes:ChangeRequest[]; releases:Release[]; manifests:ReleaseManifest[]; deployments:DeploymentExecution[]; flags:FeatureFlag[]; freezes:ChangeFreeze[]; promotions:EnvironmentPromotion[]; drift:ConfigurationDrift[]; audit:string[]; health:{status:HealthStatus; score:number; reasons:string[]}; }

const rank:Record<ChangeRiskLevel,number>={[ChangeRiskLevel.Low]:1,[ChangeRiskLevel.Moderate]:2,[ChangeRiskLevel.High]:3,[ChangeRiskLevel.Critical]:4};
const clone=<T>(v:T):T=>structuredClone(v); const freeze=<T>(v:T):T=>Object.freeze(clone(v));
const bounded=(n:number)=>Math.max(0,Math.min(100,n));
function hash(s:string){ let h=2166136261; for(let i=0;i<s.length;i++){ h^=s.charCodeAt(i); h=Math.imul(h,16777619); } return (h>>>0).toString(16); }
function nowFrom(ids:string[], fallback=0){ return ids.reduce((m,x)=>Math.max(m,x.length),fallback); }

export function calculateRiskScore(change:Pick<ChangeRequest,'riskLevel'|'affectedEnvironments'|'affectedComponents'|'type'>, impact?:Pick<ChangeImpactAssessment,'failureModes'|'compatibilityRisks'|'expectedDowntimeMs'|'confidence'>):number{ const base=rank[change.riskLevel]*20; const env=change.affectedEnvironments.includes('production')?15:0; const comp=Math.min(10,change.affectedComponents.length*2); const migration=change.type===ChangeType.DatabaseMigration?15:0; const impactScore=impact?Math.min(25,impact.failureModes.length*4+impact.compatibilityRisks.length*4+(impact.expectedDowntimeMs?8:0)+(impact.confidence<0.8?5:0)):0; return bounded(base+env+comp+migration+impactScore); }
export function evaluateCompatibility(matrix:CompatibilityMatrix):CompatibilityStatus{ if(!matrix.compatibleWith.length) return CompatibilityStatus.Unknown; if(matrix.compatibleWith.some(e=>e.status===CompatibilityStatus.Incompatible||e.status===CompatibilityStatus.Unknown)) return CompatibilityStatus.Incompatible; if(matrix.compatibleWith.some(e=>e.status===CompatibilityStatus.MigrationRequired)) return CompatibilityStatus.MigrationRequired; if(matrix.compatibleWith.some(e=>e.status===CompatibilityStatus.CompatibleWithWarnings)) return CompatibilityStatus.CompatibleWithWarnings; return CompatibilityStatus.Compatible; }
export function validateManifest(manifest:ReleaseManifest):string[]{ const blockers:string[]=[]; if(!manifest.signatures.length) blockers.push('release manifest has no digital signature'); if(!manifest.checksums.length||manifest.components.some(c=>!c.hash)) blockers.push('release artifact integrity hashes are incomplete'); if(!manifest.provenance) blockers.push('build provenance is required'); if(!manifest.rollbackCompatible) blockers.push('rollback compatibility is not declared safe'); return blockers; }

export class ChangeGovernanceEngine { #changes=new Map<string,ChangeRequest>(); #impacts=new Map<string,ChangeImpactAssessment>(); #policies=new Map<string,ChangeApprovalPolicy>(); #approvals=new Map<string,ChangeApproval>(); #tests=new Map<string,ChangeTestPlan>(); #manifests=new Map<string,ReleaseManifest>(); #releases=new Map<string,Release>(); #windows=new Map<string,DeploymentWindow>(); #freezes=new Map<string,ChangeFreeze>(); #plans=new Map<string,DeploymentPlan>(); #deployments=new Map<string,DeploymentExecution>(); #rollbacks=new Map<string,RollbackPlan>(); #flags=new Map<string,FeatureFlag>(); #promotions=new Map<string,EnvironmentPromotion>(); #migrations=new Map<string,SchemaMigration>(); #drift:ConfigurationDrift[]=[]; #audit:string[]=[]; constructor(private readonly maxAudit=20000){}
  createChange(input:ChangeRequest):ChangeRequest{ const existing=this.#changes.get(input.id); if(existing&&input.generation<=existing.generation) throw new Error(`stale change generation: ${input.id}`); const safe={...input,requestedBy:String(redact(input.requestedBy)),affectedComponents:input.affectedComponents.map(c=>({...c,metadata:redact(c.metadata??{}) as Record<string,unknown>})),status:input.status??ChangeStatus.Draft}; this.#changes.set(input.id,freeze(safe)); this.#audit.push(`ChangeRequestCreated:${input.id}`); return clone(safe); }
  submit(changeId:string):ChangeRequest{ return this.#transition(changeId,ChangeStatus.Submitted,'ChangeRequestSubmitted'); }
  assess(assessment:ChangeImpactAssessment):ChangeImpactAssessment{ const c=this.#changes.get(assessment.changeRequestId); if(!c) throw new Error('unknown change for assessment'); const safe={...assessment,assessedBy:String(redact(assessment.assessedBy)),riskScore:calculateRiskScore(c,assessment)}; this.#impacts.set(assessment.id,freeze(safe)); this.#changes.set(c.id,freeze({...c,impactAssessmentId:assessment.id,status:ChangeStatus.Assessing,generation:c.generation+1})); this.#audit.push(`ChangeAssessmentCompleted:${c.id}:${safe.riskScore}`); return clone(safe); }
  registerPolicy(policy:ChangeApprovalPolicy):void{ this.#policies.set(policy.id,freeze(policy)); this.#audit.push(`ChangePolicyRegistered:${policy.id}`); }
  attachTestPlan(plan:ChangeTestPlan):void{ const c=this.#changes.get(plan.changeRequestId); if(!c) throw new Error('unknown change for test plan'); this.#tests.set(plan.id,freeze(plan)); this.#changes.set(c.id,freeze({...c,testPlanId:plan.id,status:ChangeStatus.Testing,generation:c.generation+1})); this.#audit.push(`ChangeTestPlanAttached:${plan.changeRequestId}:${plan.result}`); }
  approve(changeId:string, approval:Omit<ChangeApproval,'changeRequestId'>):ChangeRequest{ const c=this.#changes.get(changeId); if(!c) throw new Error('unknown change'); const policy=c.approvalPolicyId?this.#policies.get(c.approvalPolicyId):undefined; if(policy?.prohibitSelfApproval&&approval.approverId===c.requestedBy) throw new Error('self approval prohibited'); if(policy?.requireImpactAssessment&&!c.impactAssessmentId) throw new Error('impact assessment required'); if(policy?.requireTestEvidence&&this.#tests.get(c.testPlanId??'')?.result!=='passed') throw new Error('passed test evidence required'); if(policy?.requireRollbackPlan&&!c.rollbackPlanId) throw new Error('rollback plan required'); const safe={...approval,changeRequestId:changeId,approverId:String(redact(approval.approverId))}; this.#approvals.set(safe.id,freeze(safe)); const approvals=[...this.#approvals.values()].filter(a=>a.changeRequestId===changeId&&a.approved); const required=policy?.requiredApprovalCount??(rank[c.riskLevel]>=3?2:1); if(approvals.length<required) { this.#audit.push(`ChangeApprovalRecorded:${changeId}:${approvals.length}/${required}`); return clone({...c,status:ChangeStatus.AwaitingApproval}); } this.#changes.set(changeId,freeze({...c,status:ChangeStatus.Approved,generation:c.generation+1})); this.#audit.push(`ChangeApproved:${changeId}`); return clone(this.#changes.get(changeId)!); }
  reject(changeId:string, reason:string):ChangeRequest{ this.#audit.push(`ChangeRejected:${changeId}:${String(redact(reason))}`); return this.#transition(changeId,ChangeStatus.Rejected,'ChangeRejected'); }
  schedule(changeId:string, windowId:string):ChangeRequest{ const c=this.#changes.get(changeId); const w=this.#windows.get(windowId); if(!c||!w) throw new Error('unknown change or deployment window'); if(!w.allowedRiskLevels.includes(c.riskLevel)||!c.affectedEnvironments.every(e=>w.allowedEnvironments.includes(e))) throw new Error('deployment window does not permit change risk or environment'); this.#assertNoFreeze(c, w.startsAt); const scheduled={...c,scheduledWindowId:windowId,status:ChangeStatus.Scheduled,generation:c.generation+1}; this.#changes.set(changeId,freeze(scheduled)); this.#audit.push(`ChangeScheduled:${changeId}:${windowId}`); return clone(scheduled); }
  cancel(changeId:string):ChangeRequest{ return this.#transition(changeId,ChangeStatus.Cancelled,'ChangeCancelled'); }
  registerWindow(window:DeploymentWindow):void{ if(window.endsAt<=window.startsAt) throw new Error('invalid deployment window'); this.#windows.set(window.id,freeze(window)); this.#audit.push(`DeploymentWindowRegistered:${window.id}`); }
  createFreeze(freezeInput:ChangeFreeze):void{ this.#freezes.set(freezeInput.id,freeze(freezeInput)); this.#audit.push(`ChangeFreezeStarted:${freezeInput.id}`); }
  removeFreeze(id:string):void{ this.#freezes.delete(id); this.#audit.push(`ChangeFreezeEnded:${id}`); }
  registerRollback(plan:RollbackPlan):void{ if(plan.approvalRequired&&!plan.validationChecks.length) throw new Error('rollback validation checks required'); this.#rollbacks.set(plan.id,freeze(plan)); this.#audit.push(`RollbackPlanRegistered:${plan.id}`); }
  registerMigration(migration:SchemaMigration):void{ if(!migration.reversible&&!migration.backwardCompatible) this.#audit.push(`IrreversibleMigrationDeclared:${migration.id}`); this.#migrations.set(migration.id,freeze(migration)); }
  createRelease(manifest:ReleaseManifest, release:Release):Release{ const blockers=validateManifest(manifest); if(blockers.length) throw new Error(`release manifest invalid: ${blockers.join('; ')}`); this.#manifests.set(manifest.id,freeze(manifest)); const safe={...release,components:[...release.components].sort((a,b)=>a.id.localeCompare(b.id)),status:ReleaseStatus.Validating}; this.#releases.set(release.id,freeze(safe)); this.#audit.push(`ReleaseCreated:${release.id}:${manifest.version}`); return clone(safe); }
  validateRelease(releaseId:string, matrices:CompatibilityMatrix[]):ReleaseReadinessScore{ const release=this.#releases.get(releaseId); if(!release) throw new Error('unknown release'); const manifest=this.#manifests.get(release.manifestId)!; const blockers=[...validateManifest(manifest)]; for(const m of matrices){ const s=evaluateCompatibility(m); if(s===CompatibilityStatus.Unknown||s===CompatibilityStatus.Incompatible) blockers.push(`unsafe compatibility: ${m.component}`); }
    const score:ReleaseReadinessScore={releaseId,testScore:manifest.validationResults.length?100:50,compatibilityScore:blockers.some(b=>b.includes('compatibility'))?0:100,securityScore:manifest.signatures.length?100:0,rollbackScore:manifest.rollbackCompatible?100:0,operationalScore:manifest.supportedEnvironments.length?100:50,overallScore:0,blockers,warnings:matrices.filter(m=>evaluateCompatibility(m)===CompatibilityStatus.CompatibleWithWarnings).map(m=>m.component)}; score.overallScore=Math.round((score.testScore+score.compatibilityScore+score.securityScore+score.rollbackScore+score.operationalScore)/5); this.#releases.set(releaseId,freeze({...release,status:blockers.length?ReleaseStatus.Failed:ReleaseStatus.Ready})); this.#audit.push(`ReleaseValidated:${releaseId}:${blockers.length?'blocked':'ready'}`); return score; }
  planDeployment(plan:DeploymentPlan):DeploymentPlan{ const release=this.#releases.get(plan.releaseId); if(!release) throw new Error('unknown release'); if(!this.#rollbacks.has(plan.rollbackPlanId)) throw new Error('rollback plan required'); if(release.status!==ReleaseStatus.Ready&&release.status!==ReleaseStatus.Approved) throw new Error('release is not ready for deployment'); this.#plans.set(plan.id,freeze({...plan,steps:plan.steps.map(s=>({...s,status:s.status??'pending'}))})); this.#audit.push(`DeploymentPlanned:${plan.id}:${plan.strategy}`); return clone(this.#plans.get(plan.id)!); }
  executeDeployment(planId:string, at:number):DeploymentExecution{ const plan=this.#plans.get(planId); if(!plan) throw new Error('unknown deployment plan'); if(plan.gates.some(g=>g.required&&!g.passed)) throw new Error('required deployment gate failed'); const completed=plan.steps.filter(s=>s.status==='complete').map(s=>s.id); const next=plan.steps.find(s=>!completed.includes(s.id)); if(!next) throw new Error('deployment has no pending steps'); const steps=plan.steps.map(s=>s.id===next.id?{...s,status:'complete' as const,executedAt:at}:s); this.#plans.set(planId,freeze({...plan,steps})); const exec=this.#deployments.get(planId)??{id:`deployment:${planId}`,planId,status:DeploymentStatus.Running,completedStepIds:[],startedAt:at,updatedAt:at,gateResults:plan.gates}; const done=steps.filter(s=>s.status==='complete').map(s=>s.id); const status=done.length===steps.length?DeploymentStatus.Observing:DeploymentStatus.Running; const updated={...exec,status,completedStepIds:done,updatedAt:at,observationUntil:status===DeploymentStatus.Observing?at+600000:exec.observationUntil}; this.#deployments.set(planId,freeze(updated)); this.#audit.push(`${done.length===1?'DeploymentStarted':'RolloutAdvanced'}:${planId}:${next.id}`); return clone(updated); }
  completeObservation(planId:string, at:number):DeploymentExecution{ const exec=this.#deployments.get(planId); if(!exec) throw new Error('unknown deployment'); if((exec.observationUntil??Infinity)>at) throw new Error('observation window still active'); const updated={...exec,status:DeploymentStatus.Completed,updatedAt:at}; this.#deployments.set(planId,freeze(updated)); this.#audit.push(`DeploymentCompleted:${planId}`); return clone(updated); }
  rollback(planId:string, reason:string):DeploymentExecution{ const exec=this.#deployments.get(planId); if(!exec) throw new Error('unknown deployment'); const updated={...exec,status:DeploymentStatus.RolledBack,rollbackStarted:true,updatedAt:exec.updatedAt+1}; this.#deployments.set(planId,freeze(updated)); this.#audit.push(`RollbackCompleted:${planId}:${String(redact(reason))}`); return clone(updated); }
  createFlag(flag:FeatureFlag):FeatureFlag{ if(!flag.ownerId) throw new Error('feature flag owner required'); const safe={...flag,ownerId:String(redact(flag.ownerId)),audit:[...(flag.audit??[]),`FeatureFlagCreated:${flag.id}`]}; this.#flags.set(flag.id,freeze(safe)); this.#audit.push(`FeatureFlagCreated:${flag.id}`); return clone(safe); }
  evaluateFlag(flagId:string, context:Record<string,string>, at=0):unknown{ const flag=this.#flags.get(flagId); if(!flag) throw new Error('unknown feature flag'); if(flag.status===FeatureFlagStatus.Disabled||flag.status===FeatureFlagStatus.Retired||(flag.expiresAt&&at>flag.expiresAt)) return flag.lastKnownGood??flag.defaultValue; const sorted=[...flag.rules].sort((a,b)=>JSON.stringify(a.scope).localeCompare(JSON.stringify(b.scope))); for(const rule of sorted){ if(rule.startsAt&&at<rule.startsAt) continue; if(rule.endsAt&&at>rule.endsAt) continue; const scopeOk=Object.entries(rule.scope).every(([k,v])=>context[k]===v); if(!scopeOk) continue; if(typeof rule.percentage==='number'){ const bucket=parseInt(hash(`${flag.id}:${JSON.stringify(context)}`).slice(0,8),16)%100; if(bucket>=rule.percentage) continue; } return rule.value; } return flag.lastKnownGood??flag.defaultValue; }
  updateFlag(flagId:string, value:unknown, reason:string):FeatureFlag{ const flag=this.#flags.get(flagId); if(!flag) throw new Error('unknown feature flag'); const updated={...flag,defaultValue:value,lastKnownGood:value,audit:[...flag.audit,`FeatureFlagChanged:${String(redact(reason))}`]}; this.#flags.set(flagId,freeze(updated)); this.#audit.push(`FeatureFlagChanged:${flagId}`); return clone(updated); }
  disableFlag(flagId:string):FeatureFlag{ const flag=this.#flags.get(flagId); if(!flag) throw new Error('unknown feature flag'); const updated={...flag,status:FeatureFlagStatus.Disabled,audit:[...flag.audit,`FeatureFlagDisabled:${flagId}`]}; this.#flags.set(flagId,freeze(updated)); this.#audit.push(`FeatureFlagDisabled:${flagId}`); return clone(updated); }
  retireFlag(flagId:string):FeatureFlag{ const flag=this.#flags.get(flagId); if(!flag) throw new Error('unknown feature flag'); const updated={...flag,status:FeatureFlagStatus.Retired,audit:[...flag.audit,`FeatureFlagRetired:${flagId}`]}; this.#flags.set(flagId,freeze(updated)); return clone(updated); }
  requestPromotion(p:EnvironmentPromotion):EnvironmentPromotion{ this.#promotions.set(p.id,freeze({...p,status:PromotionStatus.Requested})); this.#audit.push(`PromotionRequested:${p.id}`); return clone(this.#promotions.get(p.id)!); }
  approvePromotion(id:string):EnvironmentPromotion{ const p=this.#promotions.get(id); if(!p) throw new Error('unknown promotion'); if(!p.validationResults.length) throw new Error('promotion validation evidence required'); const updated={...p,status:PromotionStatus.Approved}; this.#promotions.set(id,freeze(updated)); this.#audit.push(`PromotionApproved:${id}`); return clone(updated); }
  compareEnvironments(source:string,target:string, sourceState:Record<string,string>, targetState:Record<string,string>):ConfigurationDrift{ const keys=[...new Set([...Object.keys(sourceState),...Object.keys(targetState)])].sort(); const differences=keys.filter(k=>sourceState[k]!==targetState[k]).map(k=>`${k}:${sourceState[k]??'missing'}->${targetState[k]??'missing'}`); const drift={sourceEnvironment:source,targetEnvironment:target,differences,severity:differences.length>5?'critical':differences.length?'unauthorized':'expected',detectedAt:nowFrom(differences)} as ConfigurationDrift; this.#drift.push(freeze(drift)); if(differences.length) this.#audit.push(`ConfigurationDriftDetected:${source}:${target}:${differences.length}`); return clone(drift); }
  health(){ const failed=[...this.#deployments.values()].filter(d=>d.status===DeploymentStatus.Failed).length; const staleFlags=[...this.#flags.values()].filter(f=>f.expiresAt&&f.status===FeatureFlagStatus.Active&&f.expiresAt<0).length; const criticalDrift=this.#drift.filter(d=>d.severity==='critical').length; const reasons=[...(failed?[`${failed} failed deployments`]:[]),...(staleFlags?[`${staleFlags} expired active flags`]:[]),...(criticalDrift?[`${criticalDrift} critical drift findings`]:[])]; return {status:reasons.length?HealthStatus.Warning:HealthStatus.Healthy,score:reasons.length?75:100,reasons}; }
  snapshot():ChangeManagementSnapshot{ return clone({changes:[...this.#changes.values()].sort((a,b)=>a.id.localeCompare(b.id)),releases:[...this.#releases.values()].sort((a,b)=>a.id.localeCompare(b.id)),manifests:[...this.#manifests.values()].sort((a,b)=>a.id.localeCompare(b.id)),deployments:[...this.#deployments.values()].sort((a,b)=>a.id.localeCompare(b.id)),flags:[...this.#flags.values()].sort((a,b)=>a.id.localeCompare(b.id)),freezes:[...this.#freezes.values()].sort((a,b)=>a.id.localeCompare(b.id)),promotions:[...this.#promotions.values()].sort((a,b)=>a.id.localeCompare(b.id)),drift:[...this.#drift],audit:this.#audit.slice(-this.maxAudit),health:this.health()}); }
  #transition(id:string,status:ChangeStatus,event:string):ChangeRequest{ const c=this.#changes.get(id); if(!c) throw new Error('unknown change'); const updated={...c,status,generation:c.generation+1}; this.#changes.set(id,freeze(updated)); this.#audit.push(`${event}:${id}`); return clone(updated); }
  #assertNoFreeze(c:ChangeRequest, at:number):void{ for(const f of this.#freezes.values()){ if(at<f.startsAt||at>f.endsAt) continue; if(!f.blockedRiskLevels.includes(c.riskLevel)) continue; if(f.approvedExceptionChangeIds?.includes(c.id)) continue; if(f.scope.length&& !c.affectedEnvironments.some(e=>f.scope.includes(e))) continue; throw new Error('active change freeze blocks deployment'); } }
}

export function mapChangeSeverity(risk:ChangeRiskLevel):AlertSeverity{ return risk===ChangeRiskLevel.Critical?AlertSeverity.Critical:risk===ChangeRiskLevel.High?AlertSeverity.Major:risk===ChangeRiskLevel.Moderate?AlertSeverity.Warning:AlertSeverity.Info; }
