export enum ExtensionCategory { SourceConnector='source_connector', OutputConnector='output_connector', DeviceDriver='device_driver', GraphicsPackage='graphics_package', AutomationPackage='automation_package', WorkflowTemplate='workflow_template', RulePackage='rule_package', AnalyticsModule='analytics_module', MonitoringAdapter='monitoring_adapter', SocialConnector='social_connector', ChatConnector='chat_connector', CaptioningProvider='captioning_provider', TranslationProvider='translation_provider', AIService='ai_service', ControlSurface='control_surface', ReplayExtension='replay_extension', MediaProcessor='media_processor', StorageProvider='storage_provider', AuthenticationProvider='authentication_provider', UIExtension='ui_extension', Theme='theme', ProductionTemplate='production_template', Integration='integration', Custom='custom' }
export enum ExtensionType { DeclarativePackage='declarative_package', UIExtension='ui_extension', ServicePlugin='service_plugin', DevicePlugin='device_plugin', WorkflowBundle='workflow_bundle', RulesBundle='rules_bundle', RemoteIntegration='remote_integration', MediaPipelinePlugin='media_pipeline_plugin', NativePlugin='native_plugin' }
export enum ExtensionRuntimeType { JavaScript='javascript', TypeScriptCompiled='typescript_compiled', WebAssembly='webassembly', Container='container', RemoteAPI='remote_api', Native='native', Declarative='declarative' }
export enum ExtensionProcessType { UI='ui', Background='background', Device='device', Media='media', Automation='automation', Analytics='analytics', External='external' }
export enum ExtensionRiskLevel { Low='low', Medium='medium', High='high', Critical='critical' }
export enum TenantIsolationMode { SingleTenantInstance='single_tenant_instance', MultiTenantIsolated='multi_tenant_isolated', PlatformSharedNoData='platform_shared_no_data', DedicatedDeployment='dedicated_deployment' }
export enum PluginLifecycleState { Discovered='discovered', Downloading='downloading', Verifying='verifying', Installed='installed', Configuring='configuring', Enabled='enabled', Starting='starting', Running='running', Degraded='degraded', Stopped='stopped', Updating='updating', Suspended='suspended', Disabled='disabled', Failed='failed', Uninstalling='uninstalling', Removed='removed' }
export enum PluginRestartPolicy { Never='never', OnFailure='on_failure', LimitedRetries='limited_retries', Always='always', OperatorApproval='operator_approval' }
export enum CertificationLevel { Community='community', Verified='verified', ProductionReady='production_ready', Broadcast='broadcast', Enterprise='enterprise', Security='security', Official='official' }
export interface CapabilityScope { organizationId?:string; tenantId?:string; workspaceId?:string; productionId?:string; resourceType?:string; resourceId?:string; }
export interface RequestedCapability { capability:string; reason:string; required:boolean; scope?:CapabilityScope; riskLevel:ExtensionRiskLevel; }
export interface ExtensionEntrypoint { id:string; runtime:ExtensionRuntimeType; module:string; processType:ExtensionProcessType; startupMode:'manual'|'automatic'|'on_demand'; }
export interface NetworkRequirement { hostPattern:string; protocol:string; ports:number[]; direction:'outbound'|'inbound'; required:boolean; justification:string; }
export interface ExtensionManifest { id:string; name:string; description:string; publisherId:string; version:string; type:ExtensionType; category:ExtensionCategory; entrypoints:ExtensionEntrypoint[]; capabilities:RequestedCapability[]; supportedUBOSVersions:string; supportedEnvironments:string[]; tenantIsolationMode:TenantIsolationMode; riskLevel:ExtensionRiskLevel; dependencies:string[]; configurationSchema?:Record<string,unknown>; networkRequirements?:NetworkRequirement[]; support:{contact:string; responseTargetHours:number}; license:{model:string; expiresAt?:number}; integrity:{signature:string; sha256:string; signedBy:string}; }
export interface ExtensionIdentity { extensionId:string; installationId:string; publisherId:string; tenantId:string; workspaceId?:string; grantedCapabilities:string[]; credentialId:string; installedAt:number; installedBy:string; status:'active'|'suspended'|'restricted'|'revoked'|'expired'; }
export interface ExtensionHealth { extensionId:string; installationId:string; status:'healthy'|'warning'|'degraded'|'critical'|'unavailable'|'unknown'; failureCount:number; restartCount:number; resourceUsage:{cpuPercent:number; memoryBytes:number; networkBytes:number; storageBytes:number}; updatedAt:number; }
export const forbiddenCapabilities=new Set(['security.role.manage','audit.history.modify','credential.export','tenant.*','database.unrestricted','os.unrestricted']);
export const redact=(value:unknown):unknown=>{ if(typeof value==='string') return /(secret|token|key|password|credential)/i.test(value)?'[REDACTED]':value; if(Array.isArray(value)) return value.map(redact); if(value&&typeof value==='object') return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,/(secret|token|key|password|credential)/i.test(k)?'[REDACTED]':redact(v)])); return value; };
export function validateManifest(m:ExtensionManifest):string[]{ const findings:string[]=[]; if(!/^[a-z0-9]+([.-][a-z0-9]+)+$/.test(m.id)) findings.push('invalid extension id'); if(!/^\d+\.\d+\.\d+$/.test(m.version)) findings.push('invalid semantic version'); if(!m.integrity.signature||!m.integrity.sha256.startsWith('sha256:')) findings.push('missing signed integrity'); for(const c of m.capabilities){ if(forbiddenCapabilities.has(c.capability)||c.capability.includes('*')) findings.push(`forbidden capability:${c.capability}`); if(c.required&&c.reason.length<8) findings.push(`insufficient capability reason:${c.capability}`); } if(m.type===ExtensionType.NativePlugin&&m.riskLevel!==ExtensionRiskLevel.Critical) findings.push('native plugins require critical risk classification'); return findings.sort(); }
export function isCompatible(range:string, ubosVersion:string):boolean{ return range==='*'||range.split(',').map(s=>s.trim()).includes(ubosVersion); }
export function authorizeCapability(identity:ExtensionIdentity, capability:string, scope?:CapabilityScope):boolean{ if(identity.status!=='active') return false; if(!identity.grantedCapabilities.includes(capability)) return false; return !scope?.tenantId||scope.tenantId===identity.tenantId; }
export interface MarketplaceListing { id:string; manifest:ExtensionManifest; publisherVerified:boolean; certificationLevel:CertificationLevel; pricingModel:'free'|'paid'|'subscription'|'usage'|'enterprise'; supportContact:string; publishedAt:number; suspended:boolean; dataHandling:string; }
export interface MarketplaceReview { id:string; listingId:string; tenantId:string; rating:number; title?:string; text?:string; versionUsed:string; verifiedInstallation:boolean; createdAt:number; }
export interface Entitlement { tenantId:string; extensionId:string; status:'active'|'trial'|'expired'|'suspended'; expiresAt?:number; offlineGraceUntil?:number; }
export class MarketplaceCatalog { #listings=new Map<string,MarketplaceListing>(); #reviews=new Map<string,MarketplaceReview>(); #entitlements=new Map<string,Entitlement>(); #audit:string[]=[];
 publish(listing:MarketplaceListing):void{ const findings=validateManifest(listing.manifest); if(findings.length) throw new Error(`listing rejected:${findings.join(',')}`); if(!listing.publisherVerified) throw new Error('publisher not verified'); if(listing.manifest.riskLevel===ExtensionRiskLevel.Critical&&listing.certificationLevel!==CertificationLevel.Enterprise&&listing.certificationLevel!==CertificationLevel.Official) throw new Error('critical listing requires enterprise or official certification'); this.#listings.set(listing.id,structuredClone({...listing,dataHandling:sanitize(listing.dataHandling)})); this.#audit.push(`MarketplaceListingPublished:${listing.id}`); }
 search(query:{category?:ExtensionCategory; text?:string; includeSuspended?:boolean}):MarketplaceListing[]{ const text=query.text?.toLowerCase(); return [...this.#listings.values()].filter(l=>(query.includeSuspended||!l.suspended)&&(!query.category||l.manifest.category===query.category)&&(!text||`${l.manifest.name} ${l.manifest.description}`.toLowerCase().includes(text))).sort((a,b)=>a.manifest.name.localeCompare(b.manifest.name)).map(v=>structuredClone(v)); }
 grantEntitlement(e:Entitlement):void{ this.#entitlements.set(`${e.tenantId}:${e.extensionId}`,structuredClone(e)); this.#audit.push(`ExtensionLicenseActivated:${e.tenantId}:${e.extensionId}:${e.status}`); }
 canInstall(tenantId:string, extensionId:string, at:number):boolean{ const e=this.#entitlements.get(`${tenantId}:${extensionId}`); if(!e) return false; if(e.status==='active'||e.status==='trial') return !e.expiresAt||e.expiresAt>at; return Boolean(e.status==='expired'&&e.offlineGraceUntil&&e.offlineGraceUntil>at); }
 review(r:MarketplaceReview):void{ if(!this.#listings.has(r.listingId)) throw new Error('unknown listing'); if(!r.verifiedInstallation) throw new Error('review requires verified installation'); if(r.rating<1||r.rating>5) throw new Error('rating out of range'); this.#reviews.set(`${r.listingId}:${r.tenantId}`,structuredClone({...r,text:sanitize(r.text??'')})); this.#audit.push(`MarketplaceReviewCreated:${r.listingId}`); }
 suspend(listingId:string, reason:string):void{ const l=this.#listings.get(listingId); if(!l) throw new Error('unknown listing'); this.#listings.set(listingId,{...l,suspended:true}); this.#audit.push(`MarketplaceListingSuspended:${listingId}:${sanitize(reason)}`); }
 snapshot(){ return structuredClone({listings:[...this.#listings.values()],reviews:[...this.#reviews.values()],entitlements:[...this.#entitlements.values()],audit:this.#audit.slice(-1000)}); }}
const sanitize=(s:string)=>s.replace(/(token|secret|password|credential)[^\s]*/gi,'[REDACTED]');
