import type { VideoFrameMetadata } from '../media-runtime/video-decoder.js';
import { createClock, type MediaClock } from '../sync/clock.js';

export type RendererBackend = 'webgpu' | 'fallback';
export type RendererState = 'initialize' | 'ready' | 'rendering' | 'paused' | 'stopped' | 'failed';
export type RendererStatusEventType = 'renderer_created' | 'renderer_initializing' | 'renderer_ready' | 'frame_presented' | 'renderer_paused' | 'renderer_resumed' | 'renderer_stopped' | 'renderer_failed' | 'surface_resized';

export interface RenderSurface { readonly id: string; readonly kind: 'canvas' | 'offscreen' | 'metadata'; readonly width: number; readonly height: number; readonly devicePixelRatio: number; readonly metadataOnly: boolean; readonly containsRuntimeHandle: boolean; }
export interface RenderFrame { readonly id: string; readonly videoFrame: VideoFrameMetadata; readonly layerIndex: 0; readonly sourceWidth: number; readonly sourceHeight: number; readonly presentationTimeMs: number; readonly viewport: { readonly width: number; readonly height: number }; readonly destinationRect: { readonly x: number; readonly y: number; readonly width: number; readonly height: number }; readonly metadataOnly: true; readonly containsMediaPayloads: false; }
export interface RendererStatusEvent { readonly id: string; readonly type: RendererStatusEventType; readonly timestamp: string; readonly state: RendererState; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface RendererSnapshot { readonly id: string; readonly backend: RendererBackend; readonly state: RendererState; readonly surface?: RenderSurface; readonly presentedFrames: number; readonly droppedFrames: number; readonly latestFrame?: RenderFrame; readonly events: readonly RendererStatusEvent[]; readonly metadataFirst: true; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface RenderPipeline { readonly id: string; readonly backend: RendererBackend; initialize(surface: RenderSurface): Promise<RendererSnapshot>; present(frame: RenderFrame): Promise<RendererSnapshot>; resize(width: number, height: number, devicePixelRatio?: number): RendererSnapshot; pause(): RendererSnapshot; resume(): RendererSnapshot; stop(): Promise<RendererSnapshot>; getSnapshot(): RendererSnapshot; onStatus(callback: (event: RendererStatusEvent) => void): () => void; }
export interface Renderer extends RenderPipeline { createFrame(videoFrame: VideoFrameMetadata): RenderFrame; renderDecodedFrame(videoFrame: VideoFrameMetadata): Promise<RendererSnapshot>; }

const eventId = (type: string) => `${type}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
export function createRendererStatusEvent(type: RendererStatusEventType, state: RendererState, message: string, metadata: Record<string, unknown> = {}): RendererStatusEvent { return Object.freeze({ id: eventId(type), type, timestamp: now(), state, message, metadata: Object.freeze(metadata) }); }
export function createRenderSurface(input: Partial<RenderSurface> & { id: string }): RenderSurface { return Object.freeze({ kind: 'metadata', width: 1920, height: 1080, devicePixelRatio: 1, metadataOnly: true, containsRuntimeHandle: false, ...input }); }
export function calculateAspectFit(sourceWidth: number, sourceHeight: number, viewportWidth: number, viewportHeight: number) { const scale = Math.min(viewportWidth / sourceWidth, viewportHeight / sourceHeight); const width = Math.round(sourceWidth * scale); const height = Math.round(sourceHeight * scale); return Object.freeze({ x: Math.round((viewportWidth - width) / 2), y: Math.round((viewportHeight - height) / 2), width, height }); }

abstract class BaseRenderer implements Renderer { readonly id: string; readonly backend: RendererBackend; protected state: RendererState = 'stopped'; protected surface?: RenderSurface; protected presentedFrames = 0; protected droppedFrames = 0; protected latestFrame?: RenderFrame; protected events: RendererStatusEvent[]; protected listeners = new Set<(event: RendererStatusEvent) => void>(); protected clock: MediaClock;
  constructor(options: { id?: string; backend: RendererBackend; clock?: MediaClock }) { this.id = options.id ?? `renderer-${options.backend}-${Date.now()}`; this.backend = options.backend; this.clock = options.clock ?? createClock(); this.events = [createRendererStatusEvent('renderer_created', 'stopped', 'Renderer created', { rendererId: this.id, backend: this.backend })]; }
  async initialize(surface: RenderSurface) { this.state = 'initialize'; this.surface = surface; this.emit('renderer_initializing', 'Renderer initializing', { surfaceId: surface.id }); this.state = 'ready'; if (this.clock.getState().status === 'stopped') this.clock.start(); this.emit('renderer_ready', 'Renderer ready', { surfaceId: surface.id }); return this.getSnapshot(); }
  createFrame(videoFrame: VideoFrameMetadata): RenderFrame { const surface = this.surface ?? createRenderSurface({ id: 'render-surface:default' }); const destinationRect = calculateAspectFit(videoFrame.width, videoFrame.height, surface.width, surface.height); return Object.freeze({ id: `render-frame:${videoFrame.frameIndex}`, videoFrame, layerIndex: 0, sourceWidth: videoFrame.width, sourceHeight: videoFrame.height, presentationTimeMs: videoFrame.scheduledPresentationMs, viewport: { width: surface.width, height: surface.height }, destinationRect, metadataOnly: true, containsMediaPayloads: false }); }
  async renderDecodedFrame(videoFrame: VideoFrameMetadata) { return this.present(this.createFrame(videoFrame)); }
  async present(frame: RenderFrame) { if (this.state === 'paused') { this.droppedFrames += 1; return this.getSnapshot(); } if (this.state !== 'ready' && this.state !== 'rendering') { this.state = 'failed'; this.emit('renderer_failed', 'Renderer is not ready to present', { frameId: frame.id }); return this.getSnapshot(); } const mediaTime = this.clock.getPresentationTimestamp(); if (frame.presentationTimeMs > mediaTime) this.clock.getFrameTimestamp(frame.videoFrame.frameIndex); this.state = 'rendering'; this.latestFrame = frame; this.presentedFrames += 1; this.emit('frame_presented', 'Frame presented', { frameId: frame.id, ptsMs: frame.videoFrame.ptsMs, scheduledPresentationMs: frame.presentationTimeMs, mediaClockTimestamp: mediaTime }); return this.getSnapshot(); }
  resize(width: number, height: number, devicePixelRatio = this.surface?.devicePixelRatio ?? 1) { const current = this.surface ?? createRenderSurface({ id: 'render-surface:default' }); this.surface = createRenderSurface({ ...current, width, height, devicePixelRatio }); if (this.latestFrame) this.latestFrame = this.createFrame(this.latestFrame.videoFrame); this.emit('surface_resized', 'Render surface resized', { width, height, devicePixelRatio }); return this.getSnapshot(); }
  pause() { if (this.state === 'rendering' || this.state === 'ready') { this.state = 'paused'; this.clock.pause(); this.emit('renderer_paused', 'Renderer paused'); } return this.getSnapshot(); }
  resume() { if (this.state === 'paused') { this.state = 'rendering'; this.clock.resume(); this.emit('renderer_resumed', 'Renderer resumed'); } return this.getSnapshot(); }
  async stop() { this.state = 'stopped'; this.clock.stop(); this.emit('renderer_stopped', 'Renderer stopped'); return this.getSnapshot(); }
  getSnapshot(): RendererSnapshot { return Object.freeze({ id: this.id, backend: this.backend, state: this.state, ...(this.surface ? { surface: this.surface } : {}), presentedFrames: this.presentedFrames, droppedFrames: this.droppedFrames, ...(this.latestFrame ? { latestFrame: this.latestFrame } : {}), events: Object.freeze([...this.events]), metadataFirst: true, containsRuntimeHandles: false, containsMediaPayloads: false }); }
  onStatus(callback: (event: RendererStatusEvent) => void) { this.listeners.add(callback); return () => this.listeners.delete(callback); }
  protected emit(type: RendererStatusEventType, message: string, metadata: Record<string, unknown> = {}) { const event = createRendererStatusEvent(type, this.state, message, metadata); this.events = [event, ...this.events].slice(0, 200); this.listeners.forEach((cb) => cb(event)); return event; }
}
export class FallbackRenderer extends BaseRenderer { constructor(options: { id?: string; clock?: MediaClock } = {}) { super({ ...options, backend: 'fallback' }); } }
export class WebGPURenderer extends BaseRenderer { constructor(options: { id?: string; clock?: MediaClock } = {}) { super({ ...options, backend: 'webgpu' }); } async initialize(surface: RenderSurface) { const nav = globalThis.navigator as (Navigator & { gpu?: unknown }) | undefined; if (!nav?.gpu) { this.state = 'failed'; this.surface = surface; this.emit('renderer_failed', 'WebGPU is not supported by this runtime', { surfaceId: surface.id }); return this.getSnapshot(); } return super.initialize(surface); } }
export function createRenderer(options: { id?: string; preferredBackend?: RendererBackend; clock?: MediaClock; webgpuSupported?: boolean } = {}): Renderer { const supported = options.webgpuSupported ?? Boolean((globalThis.navigator as (Navigator & { gpu?: unknown }) | undefined)?.gpu); const rendererOptions = { ...(options.id ? { id: options.id } : {}), ...(options.clock ? { clock: options.clock } : {}) }; if (options.preferredBackend === 'webgpu' && supported) return new WebGPURenderer(rendererOptions); return new FallbackRenderer(rendererOptions); }
