import type { AgentDefinition, AgentObservationContext, AgentSuggestion, BroadcastAgent } from './types.js';
import type { ProductionCommand, ProductionCommandType } from '../production-graph.js';
import { getProductionGraphRevision } from '../production-graph.js';

const command = (ctx: AgentObservationContext, type: ProductionCommandType, payload: Record<string, unknown>, agentId: string, suffix: string): ProductionCommand => ({ id: `${agentId}:${suffix}:${ctx.timestamp}`, type, broadcastSessionId: ctx.graph.broadcastSessionId, actorId: 'operator', actorRole: 'DIRECTOR', timestamp: ctx.timestamp, payload, expectedRevision: getProductionGraphRevision(ctx.graph), metadata: { sourceAgentId: agentId, requiresHumanApproval: true } });
const suggestion = (ctx: AgentObservationContext, def: AgentDefinition, input: { id: string; title: string; recommendation: string; confidence: number; targetType: string; targetId: string; reasoning: Record<string, unknown>; command?: ProductionCommand }): AgentSuggestion => ({ id: `${def.id}:${input.id}`, agentId: def.id, agentName: def.name, title: input.title, recommendation: input.recommendation, confidence: input.confidence, reasoning: input.reasoning, createdAt: ctx.timestamp, status: 'pending', targetType: input.targetType, targetId: input.targetId, ...(input.command ? { command: input.command } : {}), auditTrail: [{ at: ctx.timestamp, action: 'suggested', actorId: def.id, note: input.recommendation }] });

abstract class StaticAgent implements BroadcastAgent { constructor(public definition: AgentDefinition) {} abstract observe(context: AgentObservationContext): AgentSuggestion[]; }
export class DirectorAgent extends StaticAgent { constructor(){super({id:'agent-director',name:'AI Director',version:'18.0.0',capabilities:['active-speaker-detection','scene-recommendation','camera-framing','layout-recommendation','idle-scene-detection','transition-suggestion','guest-spotlight'],subscriptions:['production-graph','guests','timeline'],emittedCommands:['ADD_AGENT_SUGGESTION','SET_PREVIEW_SCENE','AUTO_TRANSITION'],emittedSuggestions:['scene-switch','layout-change','spotlight-guest']});} observe(ctx:AgentObservationContext){const guests=Object.values(ctx.graph.guests).filter(g=>g.status==='on_air'||g.status==='connected'); const scenes=Object.values(ctx.graph.scenes); if(!guests.length||!scenes.length)return []; const target=scenes.find(s=>s.id!==ctx.graph.program.sceneId)??scenes[0]!; return [suggestion(ctx,this.definition,{id:'scene-recommendation',title:'Consider staging active speaker scene',recommendation:`Stage ${target.name} in preview for the current speaker.`,confidence:.76,targetType:'scene',targetId:target.id,reasoning:{activeSpeakerCandidate:guests[0]?.id,autoDirector:ctx.mode==='auto-director'},command:command(ctx,'SET_PREVIEW_SCENE',{sceneId:target.id},this.definition.id,'preview')})];}}
export class AudioEngineerAgent extends StaticAgent { constructor(){super({id:'agent-audio-engineer',name:'AI Audio Engineer',version:'18.0.0',capabilities:['audio-level-analysis','clipping-detection','silence-detection','noise-detection','echo-detection','music-ducking'],subscriptions:['production-graph','audio-levels'],emittedCommands:['ADD_AGENT_SUGGESTION','SET_AUDIO_GAIN','MUTE_AUDIO_CHANNEL'],emittedSuggestions:['gain-adjustment','mute-noisy-mic','duck-music','missing-audio']});} observe(ctx:AgentObservationContext){const ch=Object.values(ctx.graph.audioChannels).find(c=>!c.muted); return ch?[suggestion(ctx,this.definition,{id:`gain-${ch.id}`,title:'Review microphone gain',recommendation:`Verify ${ch.label} gain and clipping headroom before the next transition.`,confidence:.68,targetType:'audio',targetId:ch.id,reasoning:{gain:ch.gain,muted:ch.muted},command:command(ctx,'SET_AUDIO_GAIN',{audioChannelId:ch.id,gain:Math.min(ch.gain,0.85)},this.definition.id,'gain')})]:[];}}
export class GraphicsOperatorAgent extends StaticAgent { constructor(){super({id:'agent-graphics-operator',name:'AI Graphics Operator',version:'18.0.0',capabilities:['lower-third-suggestion','title-update','sponsor-card','qr-code','timer','overlay-trigger'],subscriptions:['production-graph','guests','agenda'],emittedCommands:['ADD_AGENT_SUGGESTION','SET_PANEL_VISIBILITY'],emittedSuggestions:['lower-third','sponsor-card','timer','qr-code']});} observe(ctx:AgentObservationContext){const g=Object.values(ctx.graph.guests).find(x=>x.status==='on_air'||x.pinned); return g?[suggestion(ctx,this.definition,{id:`lower-third-${g.id}`,title:'Prepare lower third',recommendation:`Prepare a lower third for ${g.displayName}.`,confidence:.74,targetType:'graphics',targetId:g.id,reasoning:{guestStatus:g.status,pinned:g.pinned},command:command(ctx,'SET_PANEL_VISIBILITY',{panelId:'graphics-lower-thirds',visible:true},this.definition.id,'lower-third')})]:[];}}
export class ProducerAgent extends StaticAgent { constructor(){super({id:'agent-producer',name:'AI Producer',version:'18.0.0',capabilities:['schedule-monitoring','break-suggestion','checklist-monitoring','show-progress','transition-suggestion'],subscriptions:['production-graph','timeline','health'],emittedCommands:['ADD_AGENT_SUGGESTION'],emittedSuggestions:['schedule-warning','break','checklist']});} observe(ctx:AgentObservationContext){return ctx.graph.status==='live'?[suggestion(ctx,this.definition,{id:'runtime-check',title:'Monitor segment runtime',recommendation:'Check current segment against the running order and prepare a break if overtime.',confidence:.62,targetType:'segment',targetId:'current',reasoning:{broadcastStatus:ctx.graph.status,recording:ctx.graph.recording.status}})]:[];}}
export class ModeratorAgent extends StaticAgent { constructor(){super({id:'agent-moderator',name:'AI Moderator',version:'18.0.0',capabilities:['spam-detection','abuse-detection','question-highlighting','faq-detection'],subscriptions:['chat'],emittedCommands:['ADD_AGENT_SUGGESTION'],emittedSuggestions:['featured-comment','spam-review','faq']});} observe(ctx:AgentObservationContext){const q=ctx.chatMessages?.find(m=>m.text.includes('?')); return q?[suggestion(ctx,this.definition,{id:`question-${q.id}`,title:'Feature viewer question',recommendation:`Consider featuring ${q.author}'s question.`,confidence:.7,targetType:'chat',targetId:q.id,reasoning:{messageLength:q.text.length}})]:[];}}
export const createPhase18Agents=()=>[new DirectorAgent(),new AudioEngineerAgent(),new GraphicsOperatorAgent(),new ProducerAgent(),new ModeratorAgent()];
