export * from './types.js';
export * from './agents.js';
import { applyProductionCommand, type ProductionCommand, type ProductionGraph } from '../production-graph.js';
import { createPhase18Agents } from './agents.js';
import type { AgentObservationContext, AgentRuntimeState, AgentSuggestion, AutomationRule, BroadcastAgent, AnalyticsInsight, AIProvider } from './types.js';

export class AgentRegistry { private agents = new Map<string, BroadcastAgent>(); register(agent: BroadcastAgent){this.agents.set(agent.definition.id, agent); return agent.definition;} get(id:string){return this.agents.get(id);} list(){return [...this.agents.values()].map(a=>a.definition);} }
export class AgentManager { private states = new Map<string, AgentRuntimeState>(); constructor(private registry = new AgentRegistry()){createPhase18Agents().forEach(a=>this.register(a));} register(agent: BroadcastAgent){this.registry.register(agent); this.states.set(agent.definition.id,{definition:agent.definition,lifecycle:'registered',enabled:true,suggestionCount:0,acceptedCount:0,rejectedCount:0,averageConfidence:0,metadata:{}});} enable(id:string){const s=this.states.get(id); if(s)this.states.set(id,{...s,enabled:true,lifecycle:'enabled'});} disable(id:string){const s=this.states.get(id); if(s)this.states.set(id,{...s,enabled:false,lifecycle:'disabled'});} observe(context: AgentObservationContext){const out:AgentSuggestion[]=[]; for(const def of this.registry.list()){const agent=this.registry.get(def.id); const state=this.states.get(def.id); if(!agent||!state?.enabled)continue; const suggestions=agent.observe(context); out.push(...suggestions); const count=state.suggestionCount+suggestions.length; const total=state.averageConfidence*state.suggestionCount+suggestions.reduce((sum,s)=>sum+s.confidence,0); this.states.set(def.id,{...state,lifecycle:'enabled',lastObservedAt:context.timestamp,suggestionCount:count,averageConfidence:count?total/count:0});} return out;} getStates(){return [...this.states.values()];} }
export class SuggestionCenter { private suggestions = new Map<string, AgentSuggestion>(); ingest(items: AgentSuggestion[]){items.forEach(i=>this.suggestions.set(i.id,i)); return this.list();} list(){return [...this.suggestions.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));} accept(id:string, actorId='operator'){const s=this.suggestions.get(id); if(!s)return undefined; const next={...s,status:'accepted' as const,auditTrail:[...s.auditTrail,{at:new Date().toISOString(),action:'accepted',actorId}]}; this.suggestions.set(id,next); return next.command;} reject(id:string, actorId='operator'){this.mark(id,'rejected',actorId);} ignore(id:string, actorId='operator'){this.mark(id,'ignored',actorId);} private mark(id:string,status:'rejected'|'ignored',actorId:string){const s=this.suggestions.get(id); if(s)this.suggestions.set(id,{...s,status,auditTrail:[...s.auditTrail,{at:new Date().toISOString(),action:status,actorId}]});} }
export class AutomationRuleEngine { constructor(private rules: AutomationRule[] = []){} setRules(rules:AutomationRule[]){this.rules=rules;} compile(trigger:string, graph:ProductionGraph, at=new Date().toISOString()):ProductionCommand[]{return this.rules.filter(r=>r.enabled&&r.trigger===trigger).map(r=>({id:`rule:${r.id}:${at}`,type:r.commandTemplate.type,broadcastSessionId:graph.broadcastSessionId,actorId:r.createdBy,actorRole:'PRODUCER',timestamp:at,payload:r.commandTemplate.payload,expectedRevision:graph.metadata.revision,metadata:{automationRuleId:r.id,requiresHumanApproval:false}}));} }
export class ProviderRegistry { private providers=new Map<string,AIProvider>(); register(provider:AIProvider){this.providers.set(provider.id,provider);} list(){return [...this.providers.values()].map(({id,name,supports})=>({id,name,supports}));} get(id:string){return this.providers.get(id);} }
export function createAnalyticsInsights(graph:ProductionGraph):AnalyticsInsight[]{const bad=Object.values(graph.health.metrics).filter(m=>m.status!=='good').length; return [{id:'quality',label:'Broadcast quality score',score:bad?65:92,status:bad?'warning':'good',rationale:`${bad} degraded health metrics`},{id:'workload',label:'Operator workload',score:Object.keys(graph.agentSuggestions).length>5?72:88,status:'good',rationale:'Derived from pending suggestions and graph activity'},{id:'health',label:'Health score',score:graph.health.status==='critical'?35:graph.health.status==='warning'?70:95,status:graph.health.status,rationale:`Production Graph health is ${graph.health.status}`}];}
export function addSuggestionsToGraph(graph:ProductionGraph,suggestions:AgentSuggestion[]){return suggestions.reduce((current,s)=>applyProductionCommand(current,{id:`cmd:add-suggestion:${s.id}`,type:'ADD_AGENT_SUGGESTION',broadcastSessionId:graph.broadcastSessionId,actorId:s.agentId,actorRole:'AI_AGENT',timestamp:s.createdAt,payload:{id:s.id,title:s.title,description:s.recommendation,command:s.command,confidence:s.confidence,reasoning:s.reasoning},expectedRevision:current.metadata.revision}).nextGraph,graph);}
