export enum ExtensionCategory { SourceConnector='source_connector', OutputConnector='output_connector', DeviceDriver='device_driver', GraphicsPackage='graphics_package', AutomationPackage='automation_package', WorkflowTemplate='workflow_template', RulePackage='rule_package', AnalyticsModule='analytics_module', MonitoringAdapter='monitoring_adapter', SocialConnector='social_connector', ChatConnector='chat_connector', CaptioningProvider='captioning_provider', TranslationProvider='translation_provider', AIService='ai_service', ControlSurface='control_surface', ReplayExtension='replay_extension', MediaProcessor='media_processor', StorageProvider='storage_provider', AuthenticationProvider='authentication_provider', UIExtension='ui_extension', Theme='theme', ProductionTemplate='production_template', Integration='integration', Custom='custom' }
export enum ExtensionType { DeclarativePackage='declarative_package', UIExtension='ui_extension', ServicePlugin='service_plugin', DevicePlugin='device_plugin', WorkflowBundle='workflow_bundle', RulesBundle='rules_bundle', RemoteIntegration='remote_integration', MediaPipelinePlugin='media_pipeline_plugin', NativePlugin='native_plugin' }
export enum ExtensionRuntimeType { JavaScript='javascript', TypeScriptCompiled='typescript_compiled', WebAssembly='webassembly', Container='container', RemoteAPI='remote_api', Native='native', Declarative='declarative' }
export enum ExtensionProcessType { UI='ui', Background='background', Device='device', Media='media', Automation='automation', Analytics='analytics', External='external' }
export enum ExtensionRiskLevel { Low='low', Medium='medium', High='high', Critical='critical' }
export enum TenantIsolationMode { SingleTenantInstance='single_tenant_instance', MultiTenantIsolated='multi_tenant_isolated', PlatformSharedNoData='platform_shared_no_data', DedicatedDeployment='dedicated_deployment' }
export enum PluginLifecycleState { Discovered='discovered', Downloading='downloading', Verifying='verifying', Installed='installed', Configuring='configuring', Enabled='enabled', Starting='starting', Running='running', Degraded='degraded', Stopped='stopped', Updating='updating', Suspended='suspended', Disabled='disabled', Failed='failed', Uninstalling='uninstalling', Removed='removed' }
export enum PluginRestartPolicy { Never='never', OnFailure='on_failure', LimitedRetries='limited_retries', Always='always', OperatorApproval='operator_approval' }
export enum CertificationLevel { Community='community', Verified='verified', ProductionReady='production_ready', Broadcast='broadcast', Enterprise='enterprise', Security='security', Official='official' }
export interface CapabilityScope { organizationId?:string; tenantId?:string; workspaceId?:string; productionId?:string; resourceType?:string; resourceId?:string; }
export interface RequestedCapability { capability:string; reason:string; required:boolean; scope?:CapabilityScope; riskLevel:ExtensionRiskLevel; }
export interface ExtensionEntrypoint { id:string; runtime:ExtensionRuntimeType; module:string; processType:ExtensionProcessType; startupMode:'manual'|'automatic'|'on_demand'; }
export interface NetworkRequirement { hostPattern:string; protocol:string; ports:number[]; direction:'outbound'|'inbound'; required:boolean; justification:string; }
export interface ExtensionManifest { id:string; name:string; description:string; publisherId:string; version:string; type:ExtensionType; category:ExtensionCategory; entrypoints:ExtensionEntrypoint[]; capabilities:RequestedCapability[]; supportedUBOSVersions:string; supportedEnvironments:string[]; tenantIsolationMode:TenantIsolationMode; riskLevel:ExtensionRiskLevel; dependencies:string[]; configurationSchema?:Record<string,unknown>; networkRequirements?:NetworkRequirement[]; support:{contact:string; responseTargetHours:number}; license:{model:string; expiresAt?:number}; integrity:{signature:string; sha256:string; signedBy:string}; }
export interface ExtensionIdentity { extensionId:string; installationId:string; publisherId:string; tenantId:string; workspaceId?:string; grantedCapabilities:string[]; credentialId:string; installedAt:number; installedBy:string; status:'active'|'suspended'|'restricted'|'revoked'|'expired'; }
export interface ExtensionHealth { extensionId:string; installationId:string; status:'healthy'|'warning'|'degraded'|'critical'|'unavailable'|'unknown'; failureCount:number; restartCount:number; resourceUsage:{cpuPercent:number; memoryBytes:number; networkBytes:number; storageBytes:number}; updatedAt:number; }
export const forbiddenCapabilities=new Set(['security.role.manage','audit.history.modify','credential.export','tenant.*','database.unrestricted','os.unrestricted']);
export const redact=(value:unknown):unknown=>{ if(typeof value==='string') return /(secret|token|key|password|credential)/i.test(value)?'[REDACTED]':value; if(Array.isArray(value)) return value.map(redact); if(value&&typeof value==='object') return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,/(secret|token|key|password|credential)/i.test(k)?'[REDACTED]':redact(v)])); return value; };
export function validateManifest(m:ExtensionManifest):string[]{ const findings:string[]=[]; if(!/^[a-z0-9]+([.-][a-z0-9]+)+$/.test(m.id)) findings.push('invalid extension id'); if(!/^\d+\.\d+\.\d+$/.test(m.version)) findings.push('invalid semantic version'); if(!m.integrity.signature||!m.integrity.sha256.startsWith('sha256:')) findings.push('missing signed integrity'); for(const c of m.capabilities){ if(forbiddenCapabilities.has(c.capability)||c.capability.includes('*')) findings.push(`forbidden capability:${c.capability}`); if(c.required&&c.reason.length<8) findings.push(`insufficient capability reason:${c.capability}`); } if(m.type===ExtensionType.NativePlugin&&m.riskLevel!==ExtensionRiskLevel.Critical) findings.push('native plugins require critical risk classification'); return findings.sort(); }
export function isCompatible(range:string, ubosVersion:string):boolean{ return range==='*'||range.split(',').map(s=>s.trim()).includes(ubosVersion); }
export function authorizeCapability(identity:ExtensionIdentity, capability:string, scope?:CapabilityScope):boolean{ if(identity.status!=='active') return false; if(!identity.grantedCapabilities.includes(capability)) return false; return !scope?.tenantId||scope.tenantId===identity.tenantId; }
export enum SubmissionStatus { Draft='draft', Uploaded='uploaded', Validating='validating', Testing='testing', SecurityReview='security_review', ManualReview='manual_review', ChangesRequired='changes_required', Approved='approved', Rejected='rejected', Published='published', Withdrawn='withdrawn' }
export interface DeveloperOrganization { id:string; name:string; verified:boolean; suspended:boolean; createdAt:number; }
export interface SigningKey { id:string; developerId:string; publicKey:string; revoked:boolean; createdAt:number; }
export interface ExtensionSubmission { id:string; extensionId:string; version:string; publisherId:string; packageReference:string; submittedAt:number; requestedCertificationLevel:CertificationLevel; status:SubmissionStatus; reviewFindings:string[]; }
export class DeveloperPlatform { #developers=new Map<string,DeveloperOrganization>(); #keys=new Map<string,SigningKey>(); #submissions=new Map<string,ExtensionSubmission>(); #audit:string[]=[];
 createOrganization(o:DeveloperOrganization):void{ if(this.#developers.has(o.id)) throw new Error('developer exists'); this.#developers.set(o.id,{...o,name:safe(o.name)}); this.#audit.push(`DeveloperRegistered:${o.id}`); }
 verifyOrganization(id:string):void{ const d=this.#requireDeveloper(id); this.#developers.set(id,{...d,verified:true}); this.#audit.push(`DeveloperVerified:${id}`); }
 createSigningKey(key:SigningKey):void{ const d=this.#requireDeveloper(key.developerId); if(!d.verified||d.suspended) throw new Error('developer cannot create signing key'); this.#keys.set(key.id,{...key,publicKey:safe(key.publicKey)}); this.#audit.push(`SigningKeyCreated:${key.id}`); }
 revokeSigningKey(id:string):void{ const k=this.#keys.get(id); if(!k) throw new Error('unknown signing key'); this.#keys.set(id,{...k,revoked:true}); this.#audit.push(`SigningKeyRevoked:${id}`); }
 submit(manifest:ExtensionManifest,input:{submissionId:string; packageReference:string; requestedCertificationLevel:CertificationLevel; submittedAt:number}):ExtensionSubmission{ const dev=this.#requireDeveloper(manifest.publisherId); if(!dev.verified||dev.suspended) throw new Error('publisher unavailable'); const findings=validateManifest(manifest); const status=findings.length?SubmissionStatus.ChangesRequired:SubmissionStatus.SecurityReview; const sub={id:input.submissionId,extensionId:manifest.id,version:manifest.version,publisherId:manifest.publisherId,packageReference:safe(input.packageReference),submittedAt:input.submittedAt,requestedCertificationLevel:input.requestedCertificationLevel,status,reviewFindings:findings}; this.#submissions.set(sub.id,sub); this.#audit.push(`ExtensionSubmitted:${manifest.id}:${status}`); return structuredClone(sub); }
 certify(id:string, finding?:string):void{ const s=this.#requireSubmission(id); if(finding){ this.#submissions.set(id,{...s,status:SubmissionStatus.Rejected,reviewFindings:[...s.reviewFindings,safe(finding)]}); this.#audit.push(`ExtensionRejected:${id}`); return; } if(s.reviewFindings.length) throw new Error('cannot certify unresolved findings'); this.#submissions.set(id,{...s,status:SubmissionStatus.Approved}); this.#audit.push(`ExtensionCertified:${id}`); }
 publish(id:string):void{ const s=this.#requireSubmission(id); if(s.status!==SubmissionStatus.Approved) throw new Error('submission not approved'); this.#submissions.set(id,{...s,status:SubmissionStatus.Published}); this.#audit.push(`ExtensionPublished:${id}`); }
 metrics(developerId:string){ return {submissions:[...this.#submissions.values()].filter(s=>s.publisherId===developerId).length,approved:[...this.#submissions.values()].filter(s=>s.publisherId===developerId&&s.status===SubmissionStatus.Approved).length,published:[...this.#submissions.values()].filter(s=>s.publisherId===developerId&&s.status===SubmissionStatus.Published).length}; }
 snapshot(){ return structuredClone({developers:[...this.#developers.values()],keys:[...this.#keys.values()],submissions:[...this.#submissions.values()],audit:this.#audit.slice(-1000)}); }
 #requireDeveloper(id:string){ const d=this.#developers.get(id); if(!d) throw new Error('unknown developer'); return d; } #requireSubmission(id:string){ const s=this.#submissions.get(id); if(!s) throw new Error('unknown submission'); return s; }}
const safe=(s:string)=>s.replace(/(token|secret|password|credential)[^\s]*/gi,'[REDACTED]');
