import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
declare const process: { env: Record<string,string|undefined> };
type ChildProcessWithoutNullStreams = { pid?: number; kill: (signal?: string) => boolean; stdout: { on: (event: string, cb: (d: unknown) => void) => void }; stderr?: { on: (event: string, cb: (d: unknown) => void) => void }; on: (event: string, cb: (...args: unknown[]) => void) => void };
async function loadSpawn(): Promise<(cmd:string,args:readonly string[],opts:Record<string,unknown>)=>ChildProcessWithoutNullStreams> { const mod = await (Function('return import("node:child_process")')() as Promise<{ spawn: (cmd:string,args:readonly string[],opts:Record<string,unknown>)=>ChildProcessWithoutNullStreams }>); return mod.spawn; }

export type FFmpegRuntimeLifecycle = 'planned'|'preparing'|'starting'|'running'|'paused'|'stopping'|'stopped'|'recovering'|'failed';
export type FFmpegRuntimeFailureKind = 'spawn_failure'|'missing_executable'|'permission_denied'|'unexpected_exit'|'crash'|'invalid_command'|'timeout'|'startup_failure'|'security_violation';
export interface FFmpegEnvironment { readonly env: Readonly<Record<string,string>>; readonly featureFlags: { readonly UBOS_ENABLE_REAL_FFMPEG: boolean; readonly NEXT_PUBLIC_UBOS_REAL_FFMPEG: boolean }; }
export interface FFmpegExecutable { readonly path: string; readonly valid: boolean; readonly version?: string; readonly error?: string; }
export interface FFmpegCommand { readonly executable: string; readonly args: readonly string[]; readonly cwd?: string; readonly outputs: readonly string[]; readonly redactedPreview: string; readonly metadata: Readonly<Record<string,unknown>>; }
export interface FFmpegCommandBuilder { buildCommand(input: Partial<FFmpegCommand> & { executable: string; args: readonly string[] }): FFmpegCommand; }
export interface FFmpegRuntimeFailure { readonly kind: FFmpegRuntimeFailureKind; readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly ubosFailure: UBOSFailure; }
export interface FFmpegRuntimeHealth { readonly state: FFmpegRuntimeLifecycle; readonly healthy: boolean; readonly pid?: number; readonly version?: string; readonly executable?: string; readonly featureFlag: boolean; readonly latestFailure?: FFmpegRuntimeFailure; readonly queueDepth: number; readonly processUtilization: number; readonly restartStorm: boolean; readonly slowStartup: boolean; readonly resourcePressure: boolean; }
export interface FFmpegRuntimeStatistics { readonly state: FFmpegRuntimeLifecycle; readonly pid?: number; readonly cpuEstimate: number; readonly memoryEstimateMb: number; readonly startTime?: string; readonly restartCount: number; readonly failureCount: number; readonly queueDepth: number; readonly processUtilization: number; readonly lifecycleEvents: readonly Omit<FFmpegProcessEvent,'pid'>[]; }
export interface FFmpegRuntimeManifest { readonly id: string; readonly generatedAt: string; readonly state: FFmpegRuntimeLifecycle; readonly executable?: string; readonly version?: string; readonly commandPreview?: string; readonly featureFlags: FFmpegEnvironment['featureFlags']; readonly health: FFmpegRuntimeHealth; readonly statistics: FFmpegRuntimeStatistics; readonly containsProcessHandles: false; readonly containsPipes: false; readonly containsMediaPayloads: false; readonly replayStoresPid: false; readonly replayStoresStdout: false; readonly replayStoresStderr: false; }
export interface FFmpegRuntimeCapabilities { readonly realProcessExecution: boolean; readonly mockFallback: boolean; readonly versionProbe: boolean; readonly capabilityProbe: boolean; readonly safeArgumentArrays: boolean; readonly shellExecution: false; readonly supportedLifecycle: readonly FFmpegRuntimeLifecycle[]; }
export interface FFmpegProcessEvent { readonly type: string; readonly timestamp: string; readonly state: FFmpegRuntimeLifecycle; readonly pid?: number; readonly metadata: Readonly<Record<string,unknown>>; }
export interface FFmpegProcess { readonly id: string; readonly command: FFmpegCommand; readonly state: FFmpegRuntimeLifecycle; readonly pid?: number; readonly startedAt?: string; readonly stoppedAt?: string; readonly restartCount: number; readonly failureCount: number; readonly latestFailure?: FFmpegRuntimeFailure; readonly events: readonly FFmpegProcessEvent[]; }
export interface FFmpegProcessManager { start(command: FFmpegCommand): Promise<FFmpegProcess>; stop(): Promise<FFmpegProcess|undefined>; restart(command?: FFmpegCommand): Promise<FFmpegProcess>; kill(signal?: string): Promise<FFmpegProcess|undefined>; cleanup(): Promise<void>; getProcess(): FFmpegProcess|undefined; }
export interface FFmpegRuntime { readonly environment: FFmpegEnvironment; readonly capabilities: FFmpegRuntimeCapabilities; readonly manager: FFmpegProcessManager; createManifest(): FFmpegRuntimeManifest; summarizeHealth(): FFmpegRuntimeHealth; summarizeStatistics(): FFmpegRuntimeStatistics; }
const now=()=>new Date().toISOString();
const lifecycle: FFmpegRuntimeLifecycle[]=['planned','preparing','starting','running','paused','stopping','stopped','recovering','failed'];
const unsafe=/\0|[\n\r`$;&|<>]/;
const allowedOutput=(v:string)=>v==='-'||v==='pipe:null'||v==='null:'||/^rtmps?:\/\//.test(v)||/^srt:\/\//.test(v)||/^[\w./:@%+=,-]+$/.test(v);
export function createFFmpegEnvironment(env:Record<string,string|undefined>={}):FFmpegEnvironment{ const clean=Object.fromEntries(Object.entries(env).filter(([k,v])=>/^UBOS_|^NEXT_PUBLIC_UBOS_|^PATH$|^HOME$|^TMPDIR$/.test(k)&&typeof v==='string'&&!unsafe.test(v))); return { env: clean as Record<string,string>, featureFlags:{ UBOS_ENABLE_REAL_FFMPEG: env.UBOS_ENABLE_REAL_FFMPEG==='true', NEXT_PUBLIC_UBOS_REAL_FFMPEG: env.NEXT_PUBLIC_UBOS_REAL_FFMPEG==='true' } }; }
export function validateExecutable(executable:string):FFmpegExecutable{ if(!executable) return {path:'',valid:false,error:'null executable rejected'}; if(unsafe.test(executable)||executable.includes('..')||executable.includes('/../')||executable.includes('\\..\\')) return {path:executable,valid:false,error:'unsafe executable path rejected'}; return {path:executable,valid:true}; }
export function locateFFmpeg(env:Record<string,string|undefined>={}):string{ return env.UBOS_FFMPEG_PATH ?? 'ffmpeg'; }
export function buildCommand(input:Partial<FFmpegCommand>&{executable:string;args:readonly string[]}):FFmpegCommand{ const exe=validateExecutable(input.executable); if(!exe.valid) throw new Error(exe.error); const args=input.args.map((a)=>{ if(!a||unsafe.test(a)||a.includes('/../')||a.includes('\\..\\')) throw new Error(`unsafe FFmpeg argument rejected: ${a}`); return a; }); const outputs=input.outputs ?? args.filter((a)=>a==='-'||/^(rtmps?|srt):/.test(a)||/\.(mp4|mov|mkv|ts|m3u8)$/i.test(a)); if(outputs.some((o)=>!allowedOutput(o))) throw new Error('non-whitelisted FFmpeg output rejected'); return Object.freeze({ executable: input.executable, args, ...(input.cwd?{cwd:input.cwd}:{}), outputs, redactedPreview:[input.executable,...args].join(' ').replace(/([?&](key|token|secret|password)=)[^&\s]+/gi,'$1<redacted>'), metadata:Object.freeze({...(input.metadata??{}), containsProcessHandles:false}) }); }
export function createFFmpegProcess(command:FFmpegCommand, patch:Partial<FFmpegProcess>={}):FFmpegProcess{ return Object.freeze({ id:patch.id??`ffmpeg-process-${Date.now()}`, command, state:patch.state??'planned', restartCount:patch.restartCount??0, failureCount:patch.failureCount??0, events:patch.events??[], ...(patch.pid?{pid:patch.pid}:{}), ...(patch.startedAt?{startedAt:patch.startedAt}:{}), ...(patch.stoppedAt?{stoppedAt:patch.stoppedAt}:{}), ...(patch.latestFailure?{latestFailure:patch.latestFailure}:{} ) }); }
export function mapFailure(input:{kind:FFmpegRuntimeFailureKind;message:string;retryable?:boolean}):FFmpegRuntimeFailure{ const occurredAt=now(); return { kind:input.kind, code:`FFMPEG_RUNTIME_${input.kind.toUpperCase()}`, message:input.message, retryable: input.retryable ?? !['invalid_command','security_violation','missing_executable'].includes(input.kind), occurredAt, ubosFailure:createFailureRecord({category:'OUTPUT_FAILURE',sourceLayer:'execution',subsystem:'ffmpeg-runtime',message:input.message,recoverable:input.retryable??true,metadata:{runtimeSupervised:true,graphMutationAllowed:false}}) }; }
function event(type:string,state:FFmpegRuntimeLifecycle,pid?:number,metadata:Record<string,unknown>={}):FFmpegProcessEvent{return{type,timestamp:now(),state,...(pid?{pid}:{}),metadata};}
export async function spawnFFmpeg(command:FFmpegCommand, env:FFmpegEnvironment=createFFmpegEnvironment(process.env)):Promise<{process:FFmpegProcess; child?:ChildProcessWithoutNullStreams}>{ if(!env.featureFlags.UBOS_ENABLE_REAL_FFMPEG||!env.featureFlags.NEXT_PUBLIC_UBOS_REAL_FFMPEG) return {process:createFFmpegProcess(command,{state:'running',events:[event('mock_fallback','running',undefined,{featureFlag:false})]})}; const spawn=await loadSpawn(); const child=spawn(command.executable, command.args, {cwd:command.cwd, env:env.env, shell:false, stdio:'pipe'}); const p=createFFmpegProcess(command,{state:'running',...(child.pid?{pid:child.pid}:{}),startedAt:now(),events:[event('started','running',child.pid)]}); return {process:p,child}; }
export async function stopFFmpeg(p:FFmpegProcess, child?:ChildProcessWithoutNullStreams):Promise<FFmpegProcess>{ child?.kill('SIGTERM'); return createFFmpegProcess(p.command,{...p,state:'stopped',stoppedAt:now(),events:[...p.events,event('stopped','stopped')]}); }
export async function killFFmpeg(p:FFmpegProcess, child?:ChildProcessWithoutNullStreams):Promise<FFmpegProcess>{ child?.kill('SIGKILL'); return createFFmpegProcess(p.command,{...p,state:'stopped',stoppedAt:now(),events:[...p.events,event('killed','stopped')]}); }
export async function restartFFmpeg(p:FFmpegProcess, command=p.command):Promise<FFmpegProcess>{ return createFFmpegProcess(command,{state:'recovering',restartCount:p.restartCount+1,failureCount:p.failureCount,events:[...p.events,event('restart','recovering')]}); }
export async function cleanupFFmpeg():Promise<void>{ return; }
export async function probeVersion(executable='ffmpeg'):Promise<string|undefined>{ const spawn=await loadSpawn(); return await new Promise((resolve)=>{ const c=spawn(executable,['-version'],{shell:false,stdio:['ignore','pipe','pipe']}); let out=''; c.stdout.on('data',(d: unknown)=>{out+=String(d);}); c.on('error',()=>resolve(undefined)); c.on('close',()=>resolve(out.match(/ffmpeg version\s+([^\s]+)/i)?.[1])); }); }
export async function probeCapabilities(executable='ffmpeg'):Promise<FFmpegRuntimeCapabilities>{ await probeVersion(executable).catch(()=>undefined); return { realProcessExecution:true,mockFallback:true,versionProbe:true,capabilityProbe:true,safeArgumentArrays:true,shellExecution:false,supportedLifecycle:lifecycle}; }
export function summarizeHealth(p?:FFmpegProcess, env=createFFmpegEnvironment(process.env)):FFmpegRuntimeHealth{ const restartStorm=(p?.restartCount??0)>=3; return { state:p?.state??'planned', healthy:!p?.latestFailure && !restartStorm, ...(p?.pid?{pid:p.pid}:{}), ...(p?.command.executable?{executable:p.command.executable}:{}), featureFlag:env.featureFlags.UBOS_ENABLE_REAL_FFMPEG&&env.featureFlags.NEXT_PUBLIC_UBOS_REAL_FFMPEG, ...(p?.latestFailure?{latestFailure:p.latestFailure}:{}), queueDepth:0, processUtilization:p?.state==='running'?0.5:0, restartStorm, slowStartup:false, resourcePressure:false}; }
export function summarizeStatistics(p?:FFmpegProcess):FFmpegRuntimeStatistics{ return { state:p?.state??'planned', ...(p?.pid?{pid:p.pid}:{}), cpuEstimate:p?.state==='running'?5:0, memoryEstimateMb:p?.state==='running'?64:0, ...(p?.startedAt?{startTime:p.startedAt}:{}), restartCount:p?.restartCount??0, failureCount:p?.failureCount??0, queueDepth:0, processUtilization:p?.state==='running'?0.5:0, lifecycleEvents:(p?.events??[]).map(({pid:_,...e})=>e)}; }
export function createManifest(p?:FFmpegProcess, env=createFFmpegEnvironment(process.env)):FFmpegRuntimeManifest{ const health=summarizeHealth(p,env); const statistics=summarizeStatistics(p); return {id:'ffmpeg-runtime-manifest',generatedAt:now(),state:health.state,...(p?.command.executable?{executable:p.command.executable}:{}),...(p?.command.redactedPreview?{commandPreview:p.command.redactedPreview}:{}),featureFlags:env.featureFlags,health,statistics,containsProcessHandles:false,containsPipes:false,containsMediaPayloads:false,replayStoresPid:false,replayStoresStdout:false,replayStoresStderr:false}; }
export function createFFmpegRuntime(env=createFFmpegEnvironment(process.env)):FFmpegRuntime{ let current:FFmpegProcess|undefined; let child:ChildProcessWithoutNullStreams|undefined; const manager:FFmpegProcessManager={ async start(command){ const r=await spawnFFmpeg(command,env); current=r.process; child=r.child; return current; }, async stop(){ if(!current)return undefined; current=await stopFFmpeg(current,child); child=undefined; return current; }, async restart(command){ current=current?await restartFFmpeg(current,command??current.command):createFFmpegProcess(command??buildCommand({executable:locateFFmpeg(env.env),args:['-version']}),{state:'recovering'}); return current; }, async kill(signal='SIGKILL'){ if(!current)return undefined; child?.kill(signal); current=await killFFmpeg(current,child); child=undefined; return current; }, async cleanup(){ await this.stop(); await cleanupFFmpeg(); }, getProcess(){return current;} }; return { environment:env, capabilities:{realProcessExecution:env.featureFlags.UBOS_ENABLE_REAL_FFMPEG&&env.featureFlags.NEXT_PUBLIC_UBOS_REAL_FFMPEG,mockFallback:true,versionProbe:true,capabilityProbe:true,safeArgumentArrays:true,shellExecution:false,supportedLifecycle:lifecycle}, manager, createManifest(){return createManifest(current,env);}, summarizeHealth(){return summarizeHealth(current,env);}, summarizeStatistics(){return summarizeStatistics(current);} }; }
export const FFmpegRuntimeAdapter=Object.freeze({createFFmpegRuntime,createFFmpegProcess,spawnFFmpeg,stopFFmpeg,restartFFmpeg,killFFmpeg,cleanupFFmpeg,buildCommand,validateExecutable,locateFFmpeg,probeVersion,probeCapabilities,summarizeHealth,summarizeStatistics,createManifest,mapFailure});
