import { locateFFmpeg } from '../../ffmpeg-runtime/index.js';
import { createVideoDecodeSource, MetadataVideoDecoder, RingFrameBuffer, supportedVideoDecodeContainers, type VideoDecodeSource, type VideoDecoderSnapshot, type VideoFrameMetadata } from '../video-decoder.js';

declare const process: { env: Record<string, string | undefined> };
type Spawn = (cmd: string, args: readonly string[], opts: Record<string, unknown>) => { stdout: { on: (e: string, cb: (d: unknown) => void) => void }; stderr?: { on: (e: string, cb: (d: unknown) => void) => void }; on: (e: string, cb: (...args: unknown[]) => void) => void };
async function loadSpawn(): Promise<Spawn> { const mod = await (Function('return import("node:child_process")')() as Promise<{ spawn: Spawn }>); return mod.spawn; }

export interface FFmpegVideoDecoderOptions { readonly id?: string; readonly executable?: string; readonly ffprobeExecutable?: string; readonly env?: Record<string, string | undefined>; readonly dryRun?: boolean; readonly maxFrames?: number; readonly bufferCapacity?: number; }
interface ProbedFrame { readonly ptsMs: number; readonly dtsMs?: number; readonly durationMs: number; readonly width: number; readonly height: number; readonly pixelFormat: string; readonly colorSpace: string; }
const realEnabled = (env: Record<string, string | undefined>) => env.UBOS_ENABLE_REAL_FFMPEG === 'true' && env.NEXT_PUBLIC_UBOS_REAL_FFMPEG === 'true';
const ffprobePath = (options: FFmpegVideoDecoderOptions) => options.ffprobeExecutable ?? (options.executable ? options.executable.replace(/ffmpeg(?:\.exe)?$/i, 'ffprobe') : (options.env?.UBOS_FFPROBE_PATH ?? 'ffprobe'));
const toMs = (value: unknown, fallback = 0) => { const n = Number(value); return Number.isFinite(n) ? Math.round(n * 1000 * 1000) / 1000 : fallback; };

export function buildFFprobeFrameMetadataArgs(source: VideoDecodeSource, maxFrames?: number): readonly string[] { return ['-v', 'error', '-select_streams', 'v:0', '-show_entries', 'frame=pts_time,pkt_dts_time,pkt_duration_time,width,height,pix_fmt,color_space', '-of', 'json', ...(maxFrames ? ['-read_intervals', `%+#${maxFrames}`] : []), source.uri]; }
export function buildFFmpegDecodeMetadataArgs(source: VideoDecodeSource): readonly string[] { return ['-i', source.uri, '-map', '0:v:0', '-f', 'null', '-']; }

export class FFmpegVideoDecoder extends MetadataVideoDecoder { private probedFrames: ProbedFrame[] = []; private options: FFmpegVideoDecoderOptions; constructor(options: FFmpegVideoDecoderOptions = {}) { super({ ...(options.id ? { id: options.id } : {}), backend: 'ffmpeg', ...(options.bufferCapacity ? { buffer: new RingFrameBuffer(options.bufferCapacity) } : {}) }); this.options = options; }
  async open(sourceInput: VideoDecodeSource): Promise<VideoDecoderSnapshot> { const source = createVideoDecodeSource(sourceInput); if (!supportedVideoDecodeContainers.includes(source.container)) throw new Error(`Unsupported video container: ${source.container}`); this.source = source; this.state = 'opening'; this.endOfStream = false; this.frameIndex = 0; this.buffer.clear(); this.emit('decoder_opening', 'Opening FFmpeg video decoder', { source: source.uri, container: source.container }); try { this.probedFrames = await this.probeFrames(source); this.state = 'decoding'; this.clock.start(); this.emit('decoder_opened', 'FFmpeg video decoder opened', { frameCount: this.probedFrames.length, metadataOnly: true }); return this.getSnapshot(); } catch (error) { this.state = 'failed'; this.emit('decoder_failed', 'FFmpeg video decoder failed to open', { error: String(error) }); return this.getSnapshot(); } }
  async decodeNext(): Promise<VideoFrameMetadata | undefined> { if (this.state === 'paused' || this.state === 'failed' || this.endOfStream) return undefined; if (!this.source) throw new Error('Decoder must be opened before decodeNext'); this.state = 'decoding'; const probed = this.probedFrames[this.frameIndex]; if (!probed) { this.endOfStream = true; this.state = 'completed'; this.emit('decoder_completed', 'End of video stream reached', { framesDecoded: this.frameIndex }); return undefined; } const frame = this.attachTiming({ frameIndex: this.frameIndex, ...probed }); this.frameIndex += 1; this.latestFrame = frame; this.buffer.push(frame); this.emit('frame_decoded', 'Decoded video frame metadata', { frameIndex: frame.frameIndex, ptsMs: frame.ptsMs, pixelFormat: frame.pixelFormat }); return frame; }
  private async probeFrames(source: VideoDecodeSource): Promise<ProbedFrame[]> { const env = this.options.env ?? process.env; const dryRun = this.options.dryRun ?? !realEnabled(env); if (dryRun) return this.syntheticFrames(source); const spawn = await loadSpawn(); const args = buildFFprobeFrameMetadataArgs(source, this.options.maxFrames); const executable = ffprobePath(this.options); return await new Promise((resolve, reject) => { let out = ''; let err = ''; const child = spawn(executable, args, { shell: false, stdio: ['ignore', 'pipe', 'pipe'], env }); child.stdout.on('data', (d) => { out += String(d); }); child.stderr?.on('data', (d) => { err += String(d); }); child.on('error', reject); child.on('close', (code) => { if (code !== 0) { reject(new Error(err || `ffprobe exited with code ${String(code)}`)); return; } try { const parsed = JSON.parse(out) as { frames?: Array<Record<string, unknown>> }; resolve((parsed.frames ?? []).map((frame, index, frames) => ({ ptsMs: toMs(frame.pts_time, index * 33.333), ...(frame.pkt_dts_time !== undefined ? { dtsMs: toMs(frame.pkt_dts_time) } : {}), durationMs: toMs(frame.pkt_duration_time, index > 0 ? toMs(frame.pts_time, index * 33.333) - toMs(frames[index - 1]?.pts_time, (index - 1) * 33.333) : 33.333), width: Number(frame.width ?? 0), height: Number(frame.height ?? 0), pixelFormat: String(frame.pix_fmt ?? 'unknown'), colorSpace: String(frame.color_space ?? 'unknown') }))); } catch (error) { reject(error); } }); }); }
  private syntheticFrames(source: VideoDecodeSource): ProbedFrame[] { const frameCount = this.options.maxFrames ?? 5; return Array.from({ length: frameCount }, (_, index) => ({ ptsMs: Math.round(index * 33.333 * 1000) / 1000, dtsMs: Math.round(index * 33.333 * 1000) / 1000, durationMs: 33.333, width: source.container === 'webm' ? 640 : 1280, height: source.container === 'webm' ? 360 : 720, pixelFormat: 'yuv420p', colorSpace: 'bt709' })); }
}
export const createFFmpegVideoDecoder = (options?: FFmpegVideoDecoderOptions) => new FFmpegVideoDecoder(options);
export const createFFmpegDecodeCommandPreview = (source: VideoDecodeSource, options: FFmpegVideoDecoderOptions = {}) => [options.executable ?? locateFFmpeg(options.env ?? process.env), ...buildFFmpegDecodeMetadataArgs(source)].join(' ');
