import { NullWebRTCAdapter, WebRTCRuntime, createGuestRuntimeSnapshot, createWebRTCRuntimeCommand } from './index.js';
function eq(a: unknown, b: unknown) { if (a !== b) throw new Error(`Expected ${String(b)}, received ${String(a)}`); }
function ok(v: unknown) { if (!v) throw new Error('Expected value'); }
const rt = new WebRTCRuntime({}, new NullWebRTCAdapter());
const gid = 'guest-1';
rt.dispatch(createWebRTCRuntimeCommand('CREATE_GUEST_SESSION', { guestId: gid, displayName: 'Guest One' }));
eq(rt.state.sessions[gid]?.displayName, 'Guest One');
rt.dispatch(createWebRTCRuntimeCommand('INVITE_GUEST', { guestId: gid, inviteToken: 'invite-1' }));
eq(rt.state.invitedGuestIds.includes(gid), true);
rt.dispatch(createWebRTCRuntimeCommand('JOIN_GUEST', { guestId: gid }));
eq(rt.state.waitingGuestIds.includes(gid), true);
rt.dispatch(createWebRTCRuntimeCommand('MARK_GUEST_READY', { guestId: gid }));
eq(rt.state.connectedGuestIds.includes(gid), true);
eq(rt.state.sessions[gid]?.camera, 'ready');
eq(rt.state.sessions[gid]?.mic, 'ready');
rt.dispatch(createWebRTCRuntimeCommand('SET_GUEST_CAMERA_STATE', { guestId: gid, mediaState: 'disabled' }));
rt.dispatch(createWebRTCRuntimeCommand('SET_GUEST_MIC_STATE', { guestId: gid, mediaState: 'unavailable' }));
rt.dispatch(createWebRTCRuntimeCommand('SET_GUEST_SCREEN_STATE', { guestId: gid, mediaState: 'ready' }));
eq(rt.state.sessions[gid]?.screen, 'ready');
const beforeDrops = rt.metrics.droppedCommands;
rt.dispatch(createWebRTCRuntimeCommand('SET_GUEST_SCREEN_STATE', { guestId: gid, mediaState: 'bad' as never }));
rt.dispatch({ ...createWebRTCRuntimeCommand('PIN_GUEST', { guestId: gid }), runtimeHandle: undefined } as never);
ok(rt.metrics.droppedCommands >= beforeDrops + 2);
rt.dispatch(createWebRTCRuntimeCommand('ASSIGN_GUEST_TO_SCENE', { guestId: gid, sceneId: 'scene-1' }));
rt.dispatch(createWebRTCRuntimeCommand('ASSIGN_GUEST_TO_SLOT', { guestId: gid, slotId: 'slot-a' }));
eq(rt.state.sessions[gid]?.assignedSceneId, 'scene-1');
eq(rt.state.sessions[gid]?.assignedSlotId, 'slot-a');
rt.dispatch(createWebRTCRuntimeCommand('SEND_GUEST_TO_PREVIEW', { guestId: gid }));
eq(rt.state.sessions[gid]?.inPreview, true);
rt.dispatch(createWebRTCRuntimeCommand('SEND_GUEST_TO_PROGRAM', { guestId: gid }));
eq(rt.state.sessions[gid]?.inProgram, true);
rt.dispatch(createWebRTCRuntimeCommand('PIN_GUEST', { guestId: gid }));
eq(rt.state.sessions[gid]?.pinned, true);
rt.dispatch(createWebRTCRuntimeCommand('UNPIN_GUEST', { guestId: gid }));
eq(rt.state.sessions[gid]?.pinned, false);
rt.dispatch(createWebRTCRuntimeCommand('MUTE_GUEST', { guestId: gid }));
eq(rt.state.sessions[gid]?.muted, true);
rt.dispatch(createWebRTCRuntimeCommand('UNMUTE_GUEST', { guestId: gid }));
eq(rt.state.sessions[gid]?.muted, false);
rt.dispatch(createWebRTCRuntimeCommand('SET_RETURN_FEED', { guestId: gid, returnFeedSourceId: 'program', returnFeedLabel: 'Program clean' }));
eq(rt.state.sessions[gid]?.returnFeed.enabled, true);
rt.dispatch(createWebRTCRuntimeCommand('CLEAR_RETURN_FEED', { guestId: gid }));
eq(rt.state.sessions[gid]?.returnFeed.enabled, false);
rt.dispatch(createWebRTCRuntimeCommand('ENABLE_GUEST_TALLY', { guestId: gid, tallyLabel: 'On Air' }));
eq(rt.state.sessions[gid]?.tally.enabled, true);
rt.dispatch(createWebRTCRuntimeCommand('DISABLE_GUEST_TALLY', { guestId: gid }));
eq(rt.state.sessions[gid]?.tally.enabled, false);
rt.dispatch(createWebRTCRuntimeCommand('MARK_GUEST_DISCONNECTED', { guestId: gid }));
eq(rt.state.disconnectedGuestIds.includes(gid), true);
eq(rt.health.webrtcRuntimeUnavailable, true);
eq(rt.health.guestTransportConnected, false);
eq(rt.health.mediaStreamAvailable, false);
eq(new NullWebRTCAdapter().execute(createWebRTCRuntimeCommand('INVITE_GUEST'), rt.state).unavailable, true);
ok(createGuestRuntimeSnapshot(rt.state, 'validator'));
ok(rt.state.history.length > 0);
rt.session.queue.enqueue(createWebRTCRuntimeCommand('INVITE_GUEST'));
eq(rt.session.queue.size, 1);
rt.session.queue.clear();
eq(rt.session.queue.size, 0);
console.log('Runtime WebRTC validation passed');
