import type { ChatMessage, Destination, Guest, StreamHealth } from '@ubos/shared';
import type { ReactNode } from 'react';

type ButtonVariant = 'primary' | 'secondary' | 'danger';
export function Button({ children, variant = 'primary' }: { children: ReactNode; variant?: ButtonVariant }) { const cls = variant === 'primary' ? 'bg-cyan-400 text-slate-950' : variant === 'danger' ? 'bg-rose-500 text-white' : 'bg-slate-800 text-slate-100'; return <button className={`rounded-xl px-4 py-2 font-semibold ${cls}`}>{children}</button>; }
export function Panel({ title, children }: { title?: string; children: ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5 shadow-2xl shadow-black/20">{title ? <h2 className="mb-4 text-sm font-semibold uppercase tracking-wide text-slate-300">{title}</h2> : null}{children}</section>; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' }) { const cls = tone === 'success' ? 'bg-emerald-400/15 text-emerald-300' : tone === 'warning' ? 'bg-amber-400/15 text-amber-300' : 'bg-slate-700 text-slate-200'; return <span className={`rounded-full px-3 py-1 text-xs ${cls}`}>{children}</span>; }
export function GuestTile({ guest }: { guest: Guest }) { return <div className="rounded-xl bg-slate-800 p-4"><div className="aspect-video rounded-lg bg-gradient-to-br from-slate-700 to-slate-950" /><p className="mt-3 font-medium">{guest.displayName}</p><p className="text-xs text-slate-400">{guest.status}</p></div>; }
export function DestinationToggle({ destination }: { destination: Destination }) { return <div className="flex items-center justify-between rounded-xl bg-slate-800 p-4"><div><p className="font-medium">{destination.label}</p><p className="text-xs text-slate-400">{destination.platform}</p></div><Badge tone={destination.enabled ? 'success' : 'neutral'}>{destination.status}</Badge></div>; }
export function ChatMessageItem({ message }: { message: ChatMessage }) { return <article className="rounded-xl bg-slate-800/80 p-3"><p className="text-xs text-cyan-300">{message.authorName} · {message.platform}</p><p className="text-sm text-slate-100">{message.body}</p></article>; }
export function StreamHealthCard({ health }: { health: StreamHealth }) { return <div className="grid grid-cols-2 gap-3 text-sm"><Metric label="Bitrate" value={`${health.bitrateKbps} kbps`} /><Metric label="Resolution" value={health.resolution} /><Metric label="Dropped" value={`${health.droppedFrames}`} /><Metric label="CPU" value={`${health.cpuPercent}%`} /></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-800 p-3"><p className="text-xs text-slate-400">{label}</p><p className="font-semibold text-slate-100">{value}</p></div>; }
