import { applyProductionCommand, getProductionGraphRevision, type OperatorRole, type ProductionCommand, type ProductionCommandType, type ProductionGraph } from '../production-graph.js';

export type AutomationState = 'Created'|'Ready'|'Waiting'|'Scheduled'|'Triggered'|'Executing'|'Paused'|'Completed'|'Failed'|'Cancelled'|'Archived'|'Disposed';
export type AutomationType = 'Timer'|'Schedule'|'Countdown'|'Clock trigger'|'Manual trigger'|'Rundown trigger'|'Session trigger'|'Device trigger'|'Health trigger'|'Output trigger'|'Input trigger'|'Macro'|'Conditional rule'|'Composite trigger';
export type AutomationActionType = 'Cue next'|'Validate rundown'|'Load session'|'Start recording'|'Stop recording'|'Start streaming'|'Stop streaming'|'Load graphics'|'Fire macro'|'Send notification'|'Change automation state'|'Update metadata'|'Cut to program'|'Take preview'|'Auto transition';
export type TriggerKind = 'time'|'event'|'dependency'|'health'|'operator'|'composite';
export interface AutomationTrigger { readonly id:string; readonly kind:TriggerKind; readonly at?:string; readonly delayMs?:number; readonly eventType?:string; readonly dependencyIds?:readonly string[]; readonly healthStatus?:string; readonly operatorId?:string; readonly children?:readonly AutomationTrigger[]; readonly operator?:'all'|'any'; readonly metadata?:Readonly<Record<string,unknown>>; }
export interface AutomationSchedule { readonly mode:'one-shot'|'repeating'|'cron'|'delayed'; readonly runAt?:string; readonly intervalMs?:number; readonly cron?:string; readonly delayMs?:number; readonly timeoutMs?:number; readonly retryLimit?:number; readonly retryDelayMs?:number; readonly priority?:number; }
export interface AutomationAction { readonly id:string; readonly type:AutomationActionType; readonly productionCommandType?:ProductionCommandType; readonly payload?:Readonly<Record<string,unknown>>; readonly requiresAuthorization?:boolean; readonly metadata?:Readonly<Record<string,unknown>>; }
export interface AutomationDefinition { readonly id:string; readonly name:string; readonly type:AutomationType; readonly sessionId:string; readonly createdBy:string; readonly operatorRole:OperatorRole; readonly triggers:readonly AutomationTrigger[]; readonly actions:readonly AutomationAction[]; readonly dependencies?:readonly string[]; readonly schedule?:AutomationSchedule; readonly requiredDevices?:readonly string[]; readonly requiredOutputs?:readonly string[]; readonly requiredInputs?:readonly string[]; readonly metadata?:Readonly<Record<string,unknown>>; }
export interface AutomationRecord extends AutomationDefinition { readonly state:AutomationState; readonly createdAt:string; readonly updatedAt:string; readonly attempts:number; readonly lastError?:string; readonly nextRunAt?:string; readonly lastTriggeredAt?:string; readonly completedAt?:string; }
export interface AutomationHistoryEntry { readonly automationId:string; readonly at:string; readonly from?:AutomationState; readonly to?:AutomationState; readonly command:string; readonly result:'accepted'|'rejected'|'failed'; readonly message?:string; }
export interface AutomationMetrics { readonly runningAutomations:number; readonly waitingAutomations:number; readonly failures:number; readonly retries:number; readonly averageExecutionDelayMs:number; readonly averageTriggerLatencyMs:number; readonly blockedAutomations:number; }
export interface AutomationHealth { readonly status:'healthy'|'warning'|'critical'; readonly metrics:AutomationMetrics; readonly summary:string; }
export interface AutomationProductionGraphMetadata { readonly automationCount:number; readonly currentAutomation?:string; readonly triggerStatus:Readonly<Record<string,AutomationState>>; readonly executionStatus:Readonly<Record<string,AutomationState>>; readonly lastAutomation?:string; readonly pendingActions:readonly string[]; }
export interface AutomationRuntimeOptions { readonly eventBus?:{ publish(event:Readonly<Record<string,unknown>>):unknown }; readonly healthManager?:{ updateAutomationHealth?(health:AutomationHealth):unknown; updateSubsystem?(id:string, health:string):unknown }; readonly now?:()=>string; }
const transitions:Record<AutomationState, readonly AutomationState[]>={ Created:['Ready','Cancelled','Disposed'], Ready:['Waiting','Scheduled','Triggered','Paused','Cancelled','Disposed'], Waiting:['Triggered','Scheduled','Paused','Cancelled','Failed'], Scheduled:['Triggered','Paused','Cancelled','Failed'], Triggered:['Executing','Paused','Cancelled','Failed'], Executing:['Completed','Failed','Paused','Cancelled'], Paused:['Ready','Waiting','Scheduled','Executing','Cancelled','Disposed'], Completed:['Archived','Ready','Disposed'], Failed:['Ready','Archived','Disposed'], Cancelled:['Archived','Disposed'], Archived:['Disposed'], Disposed:[] };
const commandByAction:Partial<Record<AutomationActionType,ProductionCommandType>>={ 'Start recording':'START_RECORDING','Stop recording':'STOP_RECORDING','Start streaming':'START_BROADCAST','Stop streaming':'STOP_BROADCAST','Cut to program':'CUT_TO_PROGRAM','Take preview':'TAKE_PREVIEW','Auto transition':'AUTO_TRANSITION' };
const runtimeKeys=/handle|streamHandle|socket|dom|canvas|texture|gpu|ffmpeg/i;
const nowIso=()=>new Date().toISOString();
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
function safe(v:unknown):boolean{ if(!v||typeof v!=='object') return true; return Object.entries(v as Record<string,unknown>).every(([k,n])=>!runtimeKeys.test(k)&&safe(n)); }
function due(t:AutomationTrigger, at:string, events:readonly Readonly<Record<string,unknown>>[], completed:Set<string>):boolean{ const ms=Date.parse(at); if(t.kind==='time') return !t.at || Date.parse(t.at)<=ms; if(t.kind==='event') return events.some(e=>e.type===t.eventType); if(t.kind==='dependency') return (t.dependencyIds??[]).every(id=>completed.has(id)); if(t.kind==='health') return events.some(e=>e.type==='HealthChanged' && (!t.healthStatus || JSON.stringify(e).includes(t.healthStatus))); if(t.kind==='operator') return events.some(e=>e.type==='OperatorTrigger' && (!t.operatorId || JSON.stringify(e).includes(t.operatorId))); if(t.kind==='composite'){ const values=(t.children??[]).map(c=>due(c,at,events,completed)); return (t.operator??'all')==='all'?values.every(Boolean):values.some(Boolean); } return false; }
export class AutomationRegistry { private records=new Map<string,AutomationRecord>(); create(input:AutomationDefinition, at=nowIso()){ if(this.records.has(input.id)) throw new Error(`Duplicate automation ${input.id}`); if(!safe(input.metadata)||!input.actions.every(a=>safe(a.metadata)&&safe(a.payload))) throw new Error('Automation metadata cannot contain runtime handles'); const rec=Object.freeze({...clone(input), state:'Created' as const, createdAt:at, updatedAt:at, attempts:0}); this.records.set(input.id,rec); return rec; } get(id:string){ return this.records.get(id); } list(){ return Object.freeze([...this.records.values()]); } set(r:AutomationRecord){ this.records.set(r.id,Object.freeze({...r})); return this.records.get(r.id)!; } delete(id:string){ this.records.delete(id); } }
export class AutomationLifecycleManager { transition(r:AutomationRecord,to:AutomationState,at=nowIso()){ if(!transitions[r.state].includes(to)) throw new Error(`Illegal automation transition ${r.state} -> ${to}`); return Object.freeze({...r,state:to,updatedAt:at,...(to==='Completed'?{completedAt:at}:{}),...(to==='Triggered'?{lastTriggeredAt:at}:{})}); } }
export class AutomationScheduler { next(r:AutomationRecord,at=nowIso()){ const s=r.schedule; if(!s) return r; const base=Date.parse(at); const next=s.runAt ?? (s.delayMs!==undefined?new Date(base+s.delayMs).toISOString():undefined); return Object.freeze(next ? {...r,nextRunAt:next,updatedAt:at} : {...r,updatedAt:at}); } due(r:AutomationRecord,at=nowIso()){ return Boolean(r.nextRunAt && Date.parse(r.nextRunAt)<=Date.parse(at)); } }
export class AutomationTriggerManager { private events:Readonly<Record<string,unknown>>[]=[]; ingest(e:Readonly<Record<string,unknown>>){ this.events=[...this.events,e]; } evaluate(r:AutomationRecord, completed:Set<string>, at=nowIso()){ return r.triggers.length===0 || r.triggers.every(t=>due(t,at,this.events,completed)); } }
export class AutomationMetricsCollector { private delays:number[]=[]; private latencies:number[]=[]; failures=0; retries=0; recordDelay(ms:number){this.delays.push(ms);} recordLatency(ms:number){this.latencies.push(ms);} metrics(records:readonly AutomationRecord[]):AutomationMetrics{ const avg=(a:number[])=>a.length?Math.round(a.reduce((s,n)=>s+n,0)/a.length):0; return { runningAutomations:records.filter(r=>r.state==='Executing').length, waitingAutomations:records.filter(r=>r.state==='Waiting'||r.state==='Scheduled').length, failures:this.failures, retries:this.retries, averageExecutionDelayMs:avg(this.delays), averageTriggerLatencyMs:avg(this.latencies), blockedAutomations:records.filter(r=>r.state==='Failed'||r.lastError).length }; } }
export class AutomationHealthManager { constructor(private metrics:AutomationMetricsCollector){} health(records:readonly AutomationRecord[]):AutomationHealth{ const m=this.metrics.metrics(records); const status=m.failures>0||m.blockedAutomations>0?'warning':'healthy'; return {status,metrics:m,summary:`${m.runningAutomations} executing, ${m.waitingAutomations} waiting, ${m.failures} failures`}; } }
export class AutomationEventAdapter { constructor(private bus?:AutomationRuntimeOptions['eventBus']){} publish(type:string, automation:AutomationRecord, extra:Readonly<Record<string,unknown>>={}){ this.bus?.publish({type,domain:'automation',source:'AutomationRuntimeController',automationId:automation.id,state:automation.state,...extra}); } }
export class AutomationExecutionManager { execute(graph:ProductionGraph,r:AutomationRecord,at=nowIso()){ let next=graph; const events=[] as unknown[]; for(const action of r.actions){ const type=action.productionCommandType ?? commandByAction[action.type]; if(type){ if(action.requiresAuthorization===false) throw new Error('Program-changing actions require ProductionGraph authorization'); const cmd:ProductionCommand={ id:`automation:${r.id}:${action.id}:${r.attempts}`, type, broadcastSessionId:graph.broadcastSessionId, actorId:r.createdBy, actorRole:r.operatorRole, timestamp:at, payload:action.payload??{}, expectedRevision:getProductionGraphRevision(next), metadata:{automationId:r.id,actionId:action.id} }; const tx=applyProductionCommand(next,cmd); events.push(...tx.events); if(!tx.accepted) throw new Error(`ProductionGraph rejected ${type}: ${tx.errors.join(', ')}`); next=tx.nextGraph; } } return {graph:next,events}; } }
export class AutomationRecoveryManager { canRetry(r:AutomationRecord){ return r.attempts < (r.schedule?.retryLimit??0); } }
export class AutomationRuntimeController { readonly registry=new AutomationRegistry(); readonly lifecycle=new AutomationLifecycleManager(); readonly scheduler=new AutomationScheduler(); readonly triggers=new AutomationTriggerManager(); readonly execution=new AutomationExecutionManager(); readonly recovery=new AutomationRecoveryManager(); readonly metrics=new AutomationMetricsCollector(); readonly healthMonitor=new AutomationHealthManager(this.metrics); readonly events:AutomationEventAdapter; private history:AutomationHistoryEntry[]=[]; private graph:ProductionGraph; constructor(graph:ProductionGraph, private options:AutomationRuntimeOptions={}){ this.graph=graph; this.events=new AutomationEventAdapter(options.eventBus); }
createAutomation(input:AutomationDefinition){ const r=this.registry.create(input,this.now()); this.record(r,undefined,'AutomationCreated','accepted'); this.events.publish('AutomationCreated',r); this.report(); return r; }
scheduleAutomation(id:string, schedule?:AutomationSchedule){ let r=this.must(id); if(schedule) r=Object.freeze({...r,schedule}); if(r.state==='Created') r=this.lifecycle.transition(r,'Ready',this.now()); r=this.scheduler.next(r,this.now()); r=this.lifecycle.transition(r,'Scheduled',this.now()); this.registry.set(r); this.record(r,'Ready','AutomationScheduled','accepted'); this.events.publish('AutomationScheduled',r,{nextRunAt:r.nextRunAt}); this.report(); return r; }
pause(id:string){return this.move(id,'Paused','AutomationPaused');} resume(id:string){ let r=this.must(id); if(r.state==='Created'){ r=this.lifecycle.transition(r,'Ready',this.now()); this.registry.set(r); return r; } const to=r.nextRunAt?'Scheduled':'Ready'; return this.move(id,to,'AutomationResumed'); } cancel(id:string){return this.move(id,'Cancelled','AutomationCancelled');} retry(id:string){ let r=this.must(id); if(!this.recovery.canRetry(r)) throw new Error('Retry limit exceeded'); this.metrics.retries++; const { lastError: _lastError, ...retryable } = r; r=Object.freeze({...retryable,attempts:r.attempts+1}); r=this.lifecycle.transition(r,'Ready',this.now()); this.registry.set(r); return r; }
tick(at=this.now()){ const completed=new Set(this.registry.list().filter(r=>r.state==='Completed').map(r=>r.id)); for(const r0 of [...this.registry.list()].sort((a:AutomationRecord,b:AutomationRecord)=>(b.schedule?.priority??0)-(a.schedule?.priority??0)||a.id.localeCompare(b.id))){ if(r0.state==='Scheduled'&&this.scheduler.due(r0,at)) this.trigger(r0.id,at); else if((r0.state==='Ready'||r0.state==='Waiting')&&this.triggers.evaluate(r0,completed,at)) this.trigger(r0.id,at); } return this.registry.list(); }
ingestRuntimeEvent(e:Readonly<Record<string,unknown>>){ this.triggers.ingest(e); }
execute(id:string, at=this.now()){ let r=this.lifecycle.transition(this.must(id),'Executing',at); this.registry.set(r); this.events.publish('AutomationStarted',r); try{ const started=Date.now(); const out=this.execution.execute(this.graph,r,at); this.graph=out.graph; this.metrics.recordDelay(Date.now()-started); r=this.lifecycle.transition(r,'Completed',at); this.registry.set(r); this.record(r,'Executing','AutomationCompleted','accepted'); this.events.publish('AutomationCompleted',r); this.report(); return {automation:r,graph:this.graph,events:out.events}; }catch(e){ this.metrics.failures++; r=Object.freeze({...r,lastError:e instanceof Error?e.message:String(e)}); r=this.lifecycle.transition(r,'Failed',at); this.registry.set(r); this.record(r,'Executing','AutomationFailed','failed',r.lastError); this.events.publish('AutomationFailed',r,{error:r.lastError}); this.report(); return {automation:r,graph:this.graph,events:[]}; } }
listAutomations(){ return this.registry.list(); } getMetrics(){ return this.metrics.metrics(this.registry.list()); } getHealth(){ return this.healthMonitor.health(this.registry.list()); } getHistory(id?:string){ return Object.freeze(this.history.filter(h=>!id||h.automationId===id)); } getProductionGraph(){ return this.graph; } productionGraphMetadata():AutomationProductionGraphMetadata{ const list=this.registry.list(); const currentAutomation=list.find(r=>r.state==='Executing')?.id; const lastAutomation=this.history.at(-1)?.automationId; return { automationCount:list.length, ...(currentAutomation?{currentAutomation}:{}), triggerStatus:Object.fromEntries(list.map(r=>[r.id,r.state])), executionStatus:Object.fromEntries(list.map(r=>[r.id,r.state])), ...(lastAutomation?{lastAutomation}:{}), pendingActions:list.filter(r=>['Ready','Waiting','Scheduled','Triggered'].includes(r.state)).flatMap(r=>r.actions.map(a=>a.id)) }; }
private trigger(id:string,at:string){ let r=this.lifecycle.transition(this.must(id),'Triggered',at); this.registry.set(r); this.record(r,undefined,'AutomationTriggered','accepted'); this.events.publish('AutomationTriggered',r); this.metrics.recordLatency(r.nextRunAt?Math.max(0,Date.parse(at)-Date.parse(r.nextRunAt)):0); return this.execute(id,at); }
private move(id:string,to:AutomationState,event:string){ const before=this.must(id); const r=this.lifecycle.transition(before,to,this.now()); this.registry.set(r); this.record(r,before.state,event,'accepted'); this.events.publish(event,r); this.report(); return r; }
private must(id:string){ const r=this.registry.get(id); if(!r) throw new Error(`Unknown automation ${id}`); return r; } private now(){ return this.options.now?.()??nowIso(); } private record(r:AutomationRecord,from:AutomationState|undefined,command:string,result:AutomationHistoryEntry['result'],message?:string){ const entry={automationId:r.id,at:this.now(),...(from?{from}:{}),to:r.state,command,result,...(message?{message}:{})}; this.history=[...this.history,entry]; } private report(){ const h=this.getHealth(); this.options.healthManager?.updateAutomationHealth?.(h); this.options.healthManager?.updateSubsystem?.('automation-runtime',h.status==='healthy'?'Ready':'Warning'); }}
