const assert = Object.assign((value: unknown, message?: string) => { if (!value) throw new Error(message ?? 'assertion failed'); }, { equal: (a: unknown, b: unknown) => { if (a !== b) throw new Error(`Expected ${String(a)} to equal ${String(b)}`); }, ok: (v: unknown) => { if (!v) throw new Error('Expected truthy value'); }, throws: (fn: () => unknown, re: RegExp) => { try { fn(); } catch (e) { if (re.test(e instanceof Error ? e.message : String(e))) return; throw e; } throw new Error('Expected function to throw'); } });
import { createInitialProductionGraph, type ProductionGraph } from '../production-graph.js';
import { AutomationRuntimeController, type AutomationDefinition } from './index.js';
const graph = (): ProductionGraph => { const g=createInitialProductionGraph({broadcastSessionId:'s1',operatorId:'op1',timestamp:'2026-07-10T00:00:00.000Z'}); return {...g,status:'live',session:{...g.session,status:'live'},scenes:{scene1:{id:'scene1',name:'One',order:1,sourceIds:[],canvasIds:[],overlayIds:[],metadata:{},createdAt:g.createdAt,updatedAt:g.updatedAt}},preview:{sceneId:'scene1'}}; };
const events: unknown[] = []; const health: unknown[] = [];
let now = '2026-07-10T00:00:00.000Z';
const c = new AutomationRuntimeController(graph(), { now:()=>now, eventBus:{publish:e=>events.push(e)}, healthManager:{updateAutomationHealth:h=>health.push(h)} });
const base: AutomationDefinition = { id:'a1', name:'Start rec', type:'Timer', sessionId:'s1', createdBy:'op1', operatorRole:'DIRECTOR', triggers:[{id:'t1',kind:'time',at:'2026-07-10T00:00:01.000Z'}], actions:[{id:'act1',type:'Start recording'}], schedule:{mode:'one-shot',runAt:'2026-07-10T00:00:01.000Z',priority:10,retryLimit:1} };
assert.equal(c.createAutomation(base).state,'Created');
assert.throws(()=>c.createAutomation(base),/Duplicate/);
assert.throws(()=>c.pause('a1'),/Illegal/);
c.scheduleAutomation('a1');
assert.equal(c.listAutomations()[0]!.state,'Scheduled');
now='2026-07-10T00:00:01.000Z'; c.tick(now);
assert.equal(c.listAutomations()[0]!.state,'Completed');
assert.equal(c.getProductionGraph().recording.status,'recording');
assert.ok(events.some(e=>(e as {type?:string}).type==='AutomationCompleted'));
assert.ok(health.length>0);
assert.equal(c.productionGraphMetadata().automationCount,1);
const c2 = new AutomationRuntimeController(graph());
c2.createAutomation({...base,id:'bad',actions:[{id:'bad-act',type:'Cut to program',requiresAuthorization:false}]});
c2.scheduleAutomation('bad'); c2.tick(new Date().toISOString());
assert.equal(c2.listAutomations()[0]!.state,'Failed');
const c3 = new AutomationRuntimeController(graph());
c3.createAutomation({...base,id:'manual',triggers:[{id:'op',kind:'operator',operatorId:'op1'}],actions:[{id:'note',type:'Send notification'}]});
c3.resume('manual'); c3.ingestRuntimeEvent({type:'OperatorTrigger',operatorId:'op1'}); c3.tick();
assert.equal(c3.listAutomations()[0]!.state,'Completed');
assert.throws(()=>c3.createAutomation({...base,id:'unsafe',metadata:{streamHandle:'x'}}),/handle/i);
const c4 = new AutomationRuntimeController(graph());
c4.createAutomation({...base,id:'retry',actions:[{id:'x',type:'Cut to program',payload:{sceneId:'missing'}}]}); c4.scheduleAutomation('retry'); c4.tick(new Date().toISOString());
assert.equal(c4.listAutomations()[0]!.state,'Failed'); c4.retry('retry'); assert.equal(c4.listAutomations()[0]!.attempts,1);
console.log('automation-runtime validation passed');
