import { createFailureRecord, type UBOSFailure, type DegradedMode } from '../../../shared/src/failure-recovery.js';
import type { MediaExecutionIntent, MediaExecutionResult } from '../index.js';

export type RuntimeSubsystemType = 'recording'|'streaming'|'encoder'|'ffmpeg'|'webrtc'|'browser_renderer'|'gpu'|'output'|'routing'|'compositor'|'audio';
export type RuntimeProcessState = 'unregistered'|'idle'|'preparing'|'ready'|'running'|'paused'|'degraded'|'recovering'|'stopping'|'stopped'|'failed'|'unavailable';
export type ProductionRuntimeState = 'idle'|'preparing'|'ready'|'running'|'degraded'|'recovering'|'stopping'|'stopped'|'failed'|'unavailable';
export type RuntimeHealth = 'healthy'|'degraded'|'failed'|'unavailable';
export interface RuntimeFailure { readonly id: string; readonly subsystemId?: string; readonly subsystemType?: RuntimeSubsystemType; readonly message: string; readonly code: string; readonly retryable: boolean; readonly occurredAt: string; readonly ubosFailure: UBOSFailure; }
export interface RuntimeSubsystem { readonly id: string; readonly type: RuntimeSubsystemType; readonly label: string; readonly required: boolean; readonly state: RuntimeProcessState; readonly health: RuntimeHealth; readonly degradedModes: readonly DegradedMode[]; readonly diagnostics: Readonly<Record<string, unknown>>; readonly lastHeartbeatAt?: string; readonly latestFrameId?: number; readonly latestGraphRevision?: number; readonly latestFailure?: RuntimeFailure; }
export interface ProductionRuntimeSession { readonly id: string; readonly runtimeId: string; readonly graphId?: string; readonly broadcastSessionId?: string; readonly state: ProductionRuntimeState; readonly startedAt?: string; readonly stoppedAt?: string; readonly latestFrameId?: number; readonly latestGraphRevision?: number; readonly degradedModes: readonly DegradedMode[]; readonly latestFailure?: RuntimeFailure; }
export interface RuntimeManifest { readonly runtimeId: string; readonly sessionId?: string; readonly generatedAt: string; readonly state: ProductionRuntimeState; readonly subsystemCount: number; readonly requiredSubsystems: readonly RuntimeSubsystemType[]; readonly optionalSubsystems: readonly RuntimeSubsystemType[]; readonly degradedModes: readonly DegradedMode[]; readonly latestFrameId?: number; readonly latestGraphRevision?: number; readonly containsRuntimeHandles: false; readonly notes: readonly string[]; }
export interface RuntimeExecutionResult { readonly success: boolean; readonly runtimeState: ProductionRuntimeState; readonly intentId?: string; readonly subsystemId?: string; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly manifest?: RuntimeManifest; readonly mediaExecutionResult?: MediaExecutionResult; }
export interface ProductionRuntime { readonly id: string; readonly createdAt: string; readonly state: ProductionRuntimeState; readonly session?: ProductionRuntimeSession; readonly subsystems: readonly RuntimeSubsystem[]; readonly latestFailure?: RuntimeFailure; readonly latestFrameId?: number; readonly latestGraphRevision?: number; readonly manifest?: RuntimeManifest; }
export interface ProductionRuntimeService { getRuntime(): ProductionRuntime; register(subsystem: RuntimeSubsystem): ProductionRuntime; unregister(subsystemId: string): ProductionRuntime; start(): RuntimeExecutionResult; stop(): RuntimeExecutionResult; pause(): RuntimeExecutionResult; resume(): RuntimeExecutionResult; restartSubsystem(subsystemId: string): RuntimeExecutionResult; failSubsystem(subsystemId: string, error: Error|string): RuntimeExecutionResult; handleIntent(intent: MediaExecutionIntent): RuntimeExecutionResult; }
const now = () => new Date().toISOString();
const handleKeys = /handle|stream|frame|packet|process|dom|node|gpu|texture|canvas|mediaStream|ffmpeg/i;
export function redactRuntimeDiagnostics<T extends Readonly<Record<string, unknown>>>(input: T) { return Object.freeze(Object.fromEntries(Object.entries(input).filter(([k,v]) => !handleKeys.test(k) && ['string','number','boolean'].includes(typeof v)))); }
export function mapRuntimeFailure(input: { subsystem?: RuntimeSubsystem; message?: string; code?: string; retryable?: boolean; intentId?: string; graphRevision?: number; frameId?: number; }): RuntimeFailure { const message = input.message ?? 'Runtime subsystem failure'; const subsystem = input.subsystem; const category = subsystem?.type === 'recording' ? 'RECORDING_FAILURE' : subsystem?.type === 'streaming' ? 'STREAMING_FAILURE' : subsystem?.type === 'browser_renderer' ? 'RENDERER_FAILURE' : subsystem?.type === 'output' ? 'OUTPUT_FAILURE' : 'EXECUTION_FAILURE'; const occurredAt = now(); return { id: `runtime-failure-${subsystem?.id ?? 'runtime'}-${occurredAt}`, ...(subsystem ? { subsystemId: subsystem.id, subsystemType: subsystem.type } : {}), message, code: input.code ?? `RUNTIME_${(subsystem?.type ?? 'UNKNOWN').toUpperCase()}_FAILURE`, retryable: input.retryable ?? true, occurredAt, ubosFailure: createFailureRecord({ category, sourceLayer: subsystem?.type === 'browser_renderer' ? 'renderer' : subsystem?.type === 'output' ? 'output' : 'execution', subsystem: subsystem?.type ?? 'production-runtime', message, recoverable: input.retryable ?? true, ...(input.intentId ? { intentId: input.intentId } : {}), ...(input.graphRevision !== undefined ? { graphRevision: input.graphRevision } : {}), ...(input.frameId !== undefined ? { frameId: String(input.frameId) } : {}), metadata: { runtimeSupervised: true, graphMutationAllowed: false } }) }; }
export function createProductionRuntimeSession(input: Partial<ProductionRuntimeSession> & { runtimeId: string }): ProductionRuntimeSession { return Object.freeze({ id: input.id ?? `runtime-session-${Date.now()}`, runtimeId: input.runtimeId, state: input.state ?? 'idle', degradedModes: input.degradedModes ?? [], ...(input.graphId ? { graphId: input.graphId } : {}), ...(input.broadcastSessionId ? { broadcastSessionId: input.broadcastSessionId } : {}), ...(input.startedAt ? { startedAt: input.startedAt } : {}), ...(input.stoppedAt ? { stoppedAt: input.stoppedAt } : {}), ...(input.latestFrameId !== undefined ? { latestFrameId: input.latestFrameId } : {}), ...(input.latestGraphRevision !== undefined ? { latestGraphRevision: input.latestGraphRevision } : {}), ...(input.latestFailure ? { latestFailure: input.latestFailure } : {}) }); }
export function createProductionRuntime(input: Partial<ProductionRuntime> = {}): ProductionRuntime { return Object.freeze({ id: input.id ?? `production-runtime-${Date.now()}`, createdAt: input.createdAt ?? now(), state: input.state ?? 'idle', subsystems: input.subsystems ?? [], ...(input.session ? { session: input.session } : {}), ...(input.latestFailure ? { latestFailure: input.latestFailure } : {}), ...(input.latestFrameId !== undefined ? { latestFrameId: input.latestFrameId } : {}), ...(input.latestGraphRevision !== undefined ? { latestGraphRevision: input.latestGraphRevision } : {}), ...(input.manifest ? { manifest: input.manifest } : {}) }); }
const normalizeSubsystem = (s: RuntimeSubsystem): RuntimeSubsystem => Object.freeze({ ...s, diagnostics: redactRuntimeDiagnostics(s.diagnostics) });
function deriveState(subsystems: readonly RuntimeSubsystem[], fallback: ProductionRuntimeState): ProductionRuntimeState { if (subsystems.some((s)=>s.required && s.state === 'unavailable')) return 'unavailable'; if (subsystems.some((s)=>s.required && s.state === 'failed')) return 'failed'; if (subsystems.some((s)=>s.health === 'degraded' || s.state === 'degraded')) return 'degraded'; return fallback; }
function updateRuntime(runtime: ProductionRuntime, patch: Partial<ProductionRuntime>): ProductionRuntime { return createProductionRuntime({ ...runtime, ...patch, subsystems: patch.subsystems ?? runtime.subsystems }); }
export function registerRuntimeSubsystem(runtime: ProductionRuntime, subsystem: RuntimeSubsystem) { const subsystems = [...runtime.subsystems.filter((s)=>s.id !== subsystem.id), normalizeSubsystem(subsystem)]; return updateRuntime(runtime, { subsystems, state: deriveState(subsystems, runtime.state) }); }
export function unregisterRuntimeSubsystem(runtime: ProductionRuntime, subsystemId: string) { return updateRuntime(runtime, { subsystems: runtime.subsystems.filter((s)=>s.id !== subsystemId) }); }
function transition(runtime: ProductionRuntime, state: ProductionRuntimeState): RuntimeExecutionResult { return { success: true, runtimeState: state, warnings: [], errors: [], manifest: createProductionRuntimeManifest(updateRuntime(runtime,{ state })) }; }
export function startProductionRuntime(runtime: ProductionRuntime) { return transition(runtime, deriveState(runtime.subsystems, 'running')); }
export function stopProductionRuntime(runtime: ProductionRuntime) { return transition(runtime, 'stopped'); }
export function pauseProductionRuntime(runtime: ProductionRuntime) { return transition(runtime, 'ready'); }
export function resumeProductionRuntime(runtime: ProductionRuntime) { return startProductionRuntime(runtime); }
export function restartRuntimeSubsystem(runtime: ProductionRuntime, subsystemId: string) { const found = runtime.subsystems.find((s)=>s.id===subsystemId); return { success: Boolean(found), runtimeState: found ? 'recovering' : runtime.state, subsystemId, warnings: found ? [`Restart scheduled for ${subsystemId}`] : [], errors: found ? [] : [`Subsystem ${subsystemId} unavailable`] }; }
export function failRuntimeSubsystem(runtime: ProductionRuntime, subsystemId: string, error: Error|string) { const subsystem = runtime.subsystems.find((s)=>s.id===subsystemId); const failure = mapRuntimeFailure({ ...(subsystem ? { subsystem } : {}), message: typeof error === 'string' ? error : error.message, retryable: !subsystem?.required }); return { success: false, runtimeState: (subsystem?.required ? 'failed' : 'degraded') as ProductionRuntimeState, subsystemId, errors: [failure.message], warnings: subsystem?.required ? [] : ['Optional subsystem degraded'], manifest: createProductionRuntimeManifest(updateRuntime(runtime,{ latestFailure: failure })) }; }
export function summarizeProductionRuntimeHealth(runtime: ProductionRuntime) { const active = runtime.subsystems.filter((s)=>['ready','running','paused'].includes(s.state)); const failed = runtime.subsystems.filter((s)=>s.health === 'failed'); const degraded = runtime.subsystems.filter((s)=>s.health === 'degraded'); const unavailable = runtime.subsystems.filter((s)=>s.health === 'unavailable' || s.state === 'unavailable'); return Object.freeze({ state: runtime.state, health: failed.length ? 'failed' as const : unavailable.some((s)=>s.required) ? 'unavailable' as const : degraded.length || unavailable.length ? 'degraded' as const : 'healthy' as const, activeSubsystems: active.length, subsystemHealth: Object.fromEntries(runtime.subsystems.map((s)=>[s.type, s.health])), degradedModes: [...new Set(runtime.subsystems.flatMap((s)=>s.degradedModes))], latestFailure: runtime.latestFailure, latestFrameId: runtime.latestFrameId, latestGraphRevision: runtime.latestGraphRevision }); }
export function createProductionRuntimeManifest(runtime: ProductionRuntime): RuntimeManifest { return Object.freeze({ runtimeId: runtime.id, ...(runtime.session ? { sessionId: runtime.session.id } : {}), generatedAt: now(), state: runtime.state, subsystemCount: runtime.subsystems.length, requiredSubsystems: runtime.subsystems.filter((s)=>s.required).map((s)=>s.type), optionalSubsystems: runtime.subsystems.filter((s)=>!s.required).map((s)=>s.type), degradedModes: summarizeProductionRuntimeHealth(runtime).degradedModes, ...(runtime.latestFrameId !== undefined ? { latestFrameId: runtime.latestFrameId } : {}), ...(runtime.latestGraphRevision !== undefined ? { latestGraphRevision: runtime.latestGraphRevision } : {}), containsRuntimeHandles: false, notes: ['Production Runtime supervises existing subsystem metadata only', 'Production Graph mutation is not performed by runtime supervision'] }); }
export class RuntimeSupervisor implements ProductionRuntimeService { private runtime: ProductionRuntime; constructor(runtime = createProductionRuntime()) { this.runtime = runtime; } getRuntime() { return this.runtime; } register(s: RuntimeSubsystem) { this.runtime = registerRuntimeSubsystem(this.runtime, s); return this.runtime; } unregister(id: string) { this.runtime = unregisterRuntimeSubsystem(this.runtime, id); return this.runtime; } start() { const r = startProductionRuntime(this.runtime); this.runtime = updateRuntime(this.runtime, { state: r.runtimeState, ...(r.manifest ? { manifest: r.manifest } : {}) }); return r; } stop() { const r = stopProductionRuntime(this.runtime); this.runtime = updateRuntime(this.runtime, { state: r.runtimeState, ...(r.manifest ? { manifest: r.manifest } : {}) }); return r; } pause() { const r = pauseProductionRuntime(this.runtime); this.runtime = updateRuntime(this.runtime, { state: r.runtimeState, ...(r.manifest ? { manifest: r.manifest } : {}) }); return r; } resume() { return this.start(); } restartSubsystem(id: string) { return restartRuntimeSubsystem(this.runtime, id); } failSubsystem(id: string, e: Error|string) { const r = failRuntimeSubsystem(this.runtime, id, e); this.runtime = updateRuntime(this.runtime, { state: r.runtimeState, ...(r.manifest ? { manifest: r.manifest } : {}) }); return r; } handleIntent(intent: MediaExecutionIntent) { const map: Partial<Record<string, () => RuntimeExecutionResult>> = { BUILD_PRODUCTION_RUNTIME: () => ({ success: true, runtimeState: this.runtime.state, intentId: intent.id, warnings: [], errors: [], manifest: createProductionRuntimeManifest(this.runtime) }), START_PRODUCTION_RUNTIME: () => this.start(), STOP_PRODUCTION_RUNTIME: () => this.stop(), PAUSE_PRODUCTION_RUNTIME: () => this.pause(), RESUME_PRODUCTION_RUNTIME: () => this.resume(), RESTART_RUNTIME_SUBSYSTEM: () => this.restartSubsystem(String(intent.payload.subsystemId ?? '')), REPORT_PRODUCTION_RUNTIME_HEALTH: () => ({ success: true, runtimeState: this.runtime.state, intentId: intent.id, warnings: [JSON.stringify(summarizeProductionRuntimeHealth(this.runtime))], errors: [] }), FAIL_PRODUCTION_RUNTIME: () => this.failSubsystem(String(intent.payload.subsystemId ?? ''), String(intent.payload.message ?? 'Production runtime failed')) }; return (map[intent.type] ?? (() => ({ success: false, runtimeState: this.runtime.state, intentId: intent.id, warnings: [], errors: [`Unsupported production runtime intent ${intent.type}`] })))(); } }
