import { CLOUD_ENVIRONMENT_TYPES, CLOUD_REGIONS, DEPLOYMENT_TARGETS, type CloudCluster, type CloudEnvironment, type CloudPlatform, type CloudTopology, type DeploymentManifest, type ResourceQuota } from './types.js';
export type CloudValidationIssue={code:string;message:string;field?:string};
const forbiddenKeyParts=['sdk','aws','azure','googlecloud','gcp','docker','kubernetes','k8s','terraform','ssh','credential','credentials','token','password','privatekey','unsafehandle'];
const forbiddenText=[/aws\s+sdk/i,/azure\s+sdk/i,/google\s+cloud\s+sdk/i,/docker/i,/kubernetes|\bk8s\b/i,/terraform/i,/\bssh\b/i,/credential/i,/secret/i,/password/i,/bearer\s+/i];
export function validateResourceQuota(q:ResourceQuota,field='quota'){const issues:CloudValidationIssue[]=[]; for (const [k,v] of Object.entries(q)) if(!Number.isFinite(v)||v<0) issues.push({code:'NEGATIVE_RESOURCE_QUOTA',message:'Resource quotas must be non-negative finite numbers.',field:field+'.'+k}); return issues;}
function scanForbidden(value:unknown,path='metadata'):CloudValidationIssue[]{const issues:CloudValidationIssue[]=[]; if(value&&typeof value==='object'){ if(Array.isArray(value)) value.forEach((v,i)=>issues.push(...scanForbidden(v,`${path}[${i}]`))); else for(const [k,v] of Object.entries(value as Record<string,unknown>)){const lk=k.toLowerCase().replace(/[_-]/g,''); if(forbiddenKeyParts.some(p=>lk.includes(p))) issues.push({code:'FORBIDDEN_CLOUD_RUNTIME_REFERENCE',message:`Forbidden runtime, credential, cloud SDK, container, IaC, or SSH key rejected: ${k}.`,field:`${path}.${k}`}); issues.push(...scanForbidden(v,`${path}.${k}`));}} else if(typeof value==='string'&&forbiddenText.some(p=>p.test(value))) issues.push({code:'FORBIDDEN_CLOUD_RUNTIME_REFERENCE',message:'Forbidden runtime, credential, cloud SDK, container, IaC, SSH, or secret text rejected.',field:path}); return issues;}
const dup=(xs:{id:string}[],code:string,msg:string)=>{const seen=new Set<string>(), out:CloudValidationIssue[]=[]; for(const x of xs){ if(seen.has(x.id)) out.push({code,message:msg,field:x.id}); seen.add(x.id);} return out;};
export function validateCloudEnvironment(e:CloudEnvironment){const issues:CloudValidationIssue[]=[]; if(!CLOUD_ENVIRONMENT_TYPES.includes(e.type)) issues.push({code:'INVALID_ENVIRONMENT_TYPE',message:'Unknown environment type.',field:'type'}); issues.push(...validateResourceQuota(e.quotas,'environment.quotas'),...scanForbidden(e)); return issues;}
export function validateDeploymentManifest(m:DeploymentManifest){const issues:CloudValidationIssue[]=[]; if(m.containsRuntimeHandles!==false) issues.push({code:'RUNTIME_HANDLES_FORBIDDEN',message:'Deployments must be metadata-only.'}); if(m.containsSecrets!==false) issues.push({code:'SECRETS_FORBIDDEN',message:'Deployments must not contain secrets.'}); for(const t of m.targets){ if(!DEPLOYMENT_TARGETS.includes(t.type)) issues.push({code:'INVALID_DEPLOYMENT_TARGET',message:'Unknown deployment target.',field:t.id}); if(!CLOUD_REGIONS.includes(t.regionId)) issues.push({code:'INVALID_REGION_NAME',message:'Deployment target references invalid region name.',field:t.id}); } return issues.concat(scanForbidden(m));}
export function validateCloudCluster(c:CloudCluster){return validateResourceQuota(c.quotas,'cluster.quotas').concat(c.nodes.flatMap(n=>validateResourceQuota(n.quota,`node.${n.id}.quota`)), scanForbidden(c));}
export function serializeCloudTopology(t:CloudTopology){return JSON.stringify(t);}
export function validateCloudPlatform(p:CloudPlatform){let issues:CloudValidationIssue[]=[]; issues=issues.concat(dup(p.organizations,'DUPLICATE_ORGANIZATION_ID','Organization id must be unique.'), dup(p.deployments,'DUPLICATE_DEPLOYMENT_ID','Deployment id must be unique.')); for(const r of p.regions) if(!CLOUD_REGIONS.includes(r.name)) issues.push({code:'INVALID_REGION_NAME',message:'Region name is not supported.',field:r.id}); p.environments.forEach(e=>issues.push(...validateCloudEnvironment(e))); p.clusters.forEach(c=>issues.push(...validateCloudCluster(c))); p.deployments.forEach(d=>issues.push(...validateDeploymentManifest(d))); return issues.concat(scanForbidden(p));}
export const DeploymentValidator={validateResourceQuota,validateCloudEnvironment,validateDeploymentManifest,validateCloudCluster,validateCloudPlatform,serializeCloudTopology};
