export type RuntimeTransitionType = 'CUT' | 'AUTO' | 'FADE' | 'DISSOLVE' | 'WIPE' | 'SLIDE' | 'PUSH' | 'ZOOM' | 'STINGER';
export type RuntimeCommandType = 'CUT' | 'AUTO' | 'TAKE' | 'PREVIEW' | 'PROGRAM' | 'CLEAR_PREVIEW' | 'SWAP' | 'TRANSITION' | 'UNDO' | 'REDO';
export type RuntimeStatus = 'idle' | 'executing' | 'transition_active' | 'locked' | 'error';
export interface RuntimeComposition { id: string; sceneId: string | null; layerVisibility: Record<string, boolean>; metadata: Record<string, unknown>; }
export interface RuntimeState { currentProgram: string | null; currentPreview: string | null; currentTransition: RuntimeTransitionType; transitionActive: boolean; transitionProgress: number; transitionDuration: number; lastCommand: RuntimeCommandType | null; currentScene: string | null; currentComposition: RuntimeComposition; executionQueue: RuntimeCommand[]; runtimeTimestamp: string; status: RuntimeStatus; }
export interface RuntimeSnapshot { id: string; program: string | null; preview: string | null; layerVisibility: Record<string, boolean>; selectedScene: string | null; composition: RuntimeComposition; timestamp: string; operator: string; command: RuntimeCommandType | 'RESTORE'; }
export interface RuntimeMetrics { runtimeAlive: boolean; queueSize: number; commandsExecuted: number; droppedCommands: number; averageExecuteTimeMs: number; lastRuntimeError: string | null; }
export interface RuntimeHealth extends RuntimeMetrics { status: RuntimeStatus; transitionActive: boolean; locked: boolean; }
export interface RuntimeCommand { id: string; type: RuntimeCommandType; operator: string; sceneId?: string | null; transition?: RuntimeTransitionType; duration?: number; timestamp: string; }
export type RuntimeMutation = (state: RuntimeState, command: RuntimeCommand) => RuntimeState;
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
export const createRuntimeComposition = (sceneId: string | null = null): RuntimeComposition => ({ id: id('composition'), sceneId, layerVisibility: {}, metadata: { gpu: 'unavailable', streaming: 'inactive', recording: 'inactive' } });
export const createRuntimeState = (input: Partial<RuntimeState> = {}): RuntimeState => ({ currentProgram: null, currentPreview: null, currentTransition: 'CUT', transitionActive: false, transitionProgress: 0, transitionDuration: 0, lastCommand: null, currentScene: null, currentComposition: createRuntimeComposition(null), executionQueue: [], runtimeTimestamp: now(), status: 'idle', ...input });
export const createCommand = (type: RuntimeCommandType, operator = 'operator', input: Partial<RuntimeCommand> = {}): RuntimeCommand => ({ id: id(type.toLowerCase()), type, operator, timestamp: now(), ...input });
export const CutCommand = (operator?: string) => createCommand('CUT', operator);
export const AutoCommand = (operator?: string) => createCommand('AUTO', operator);
export const TakeCommand = (operator?: string) => createCommand('TAKE', operator);
export const PreviewCommand = (sceneId: string, operator?: string) => createCommand('PREVIEW', operator, { sceneId });
export const ProgramCommand = (sceneId: string, operator?: string) => createCommand('PROGRAM', operator, { sceneId });
export const ClearPreviewCommand = (operator?: string) => createCommand('CLEAR_PREVIEW', operator);
export const SwapCommand = (operator?: string) => createCommand('SWAP', operator);
export const TransitionCommand = (transition: RuntimeTransitionType, duration = 500, operator?: string) => createCommand('TRANSITION', operator, { transition, duration });
export const UndoCommand = (operator?: string) => createCommand('UNDO', operator);
export const RedoCommand = (operator?: string) => createCommand('REDO', operator);
export class RuntimeClock { now() { return now(); } }
export class RuntimeQueue { private q: RuntimeCommand[] = []; enqueue(c: RuntimeCommand) { this.q.push(c); } dequeue() { return this.q.shift() ?? null; } snapshot() { return [...this.q]; } get size() { return this.q.length; } }
export class RuntimeLockManager { private locks = new Set<string>(); acquire(name: string) { if (this.locks.has(name)) return false; this.locks.add(name); return true; } release(name: string) { this.locks.delete(name); } get locked() { return this.locks.size > 0; } get activeLocks() { return [...this.locks]; } }
export class RuntimeHistory { history: RuntimeSnapshot[] = []; undoStack: RuntimeSnapshot[] = []; redoStack: RuntimeSnapshot[] = []; record(s: RuntimeSnapshot) { this.history.push(s); this.undoStack.push(s); this.redoStack = []; } undo(current: RuntimeSnapshot) { const previous = this.undoStack.length > 1 ? this.undoStack.at(-2)! : null; if (previous) { this.redoStack.push(current); this.undoStack.pop(); } return previous; } redo() { const next = this.redoStack.pop() ?? null; if (next) this.undoStack.push(next); return next; } }
export function snapshotFromState(state: RuntimeState, operator: string, command: RuntimeCommandType | 'RESTORE'): RuntimeSnapshot { return { id: id('snapshot'), program: state.currentProgram, preview: state.currentPreview, layerVisibility: { ...state.currentComposition.layerVisibility }, selectedScene: state.currentScene, composition: { ...state.currentComposition, layerVisibility: { ...state.currentComposition.layerVisibility }, metadata: { ...state.currentComposition.metadata } }, timestamp: state.runtimeTimestamp, operator, command }; }
function restore(state: RuntimeState, snap: RuntimeSnapshot): RuntimeState { return { ...state, currentProgram: snap.program, currentPreview: snap.preview, currentScene: snap.selectedScene, currentComposition: { ...snap.composition, layerVisibility: { ...snap.layerVisibility } }, runtimeTimestamp: now(), status: 'idle', transitionActive: false, transitionProgress: 0, lastCommand: 'UNDO' }; }
export class RuntimeExecutor { execute(state: RuntimeState, command: RuntimeCommand): RuntimeState { const ts = now(); const base = { ...state, lastCommand: command.type, runtimeTimestamp: ts, status: 'executing' as const }; switch (command.type) { case 'PREVIEW': return { ...base, currentPreview: command.sceneId ?? null, currentScene: command.sceneId ?? state.currentScene, status: 'idle' }; case 'PROGRAM': return { ...base, currentProgram: command.sceneId ?? null, currentScene: command.sceneId ?? state.currentScene, currentComposition: createRuntimeComposition(command.sceneId ?? null), status: 'idle' }; case 'CLEAR_PREVIEW': return { ...base, currentPreview: null, status: 'idle' }; case 'SWAP': return { ...base, currentProgram: state.currentPreview, currentPreview: state.currentProgram, currentScene: state.currentPreview, currentComposition: createRuntimeComposition(state.currentPreview), status: 'idle' }; case 'TRANSITION': return { ...base, currentTransition: command.transition ?? state.currentTransition, transitionDuration: command.duration ?? state.transitionDuration, status: 'idle' }; case 'CUT': return { ...base, currentTransition: 'CUT', transitionDuration: 0, currentProgram: state.currentPreview ?? state.currentProgram, currentScene: state.currentPreview ?? state.currentScene, currentComposition: createRuntimeComposition(state.currentPreview ?? state.currentProgram), transitionActive: false, transitionProgress: 1, status: 'idle' }; case 'AUTO': case 'TAKE': { const duration = command.duration ?? (state.transitionDuration || 500); return { ...base, currentTransition: command.type === 'AUTO' ? 'AUTO' : state.currentTransition, transitionDuration: duration, currentProgram: state.currentPreview ?? state.currentProgram, currentScene: state.currentPreview ?? state.currentScene, currentComposition: createRuntimeComposition(state.currentPreview ?? state.currentProgram), transitionActive: false, transitionProgress: 1, status: 'idle' }; } default: return base; } } }
export class RuntimeMetricsStore { metrics: RuntimeMetrics = { runtimeAlive: true, queueSize: 0, commandsExecuted: 0, droppedCommands: 0, averageExecuteTimeMs: 0, lastRuntimeError: null }; record(ms: number, queueSize: number) { const n = this.metrics.commandsExecuted; this.metrics.averageExecuteTimeMs = (this.metrics.averageExecuteTimeMs * n + ms) / (n + 1); this.metrics.commandsExecuted += 1; this.metrics.queueSize = queueSize; } drop(reason: string) { this.metrics.droppedCommands += 1; this.metrics.lastRuntimeError = reason; } }
export class RuntimeDispatcher { constructor(private session: RuntimeSession) {} dispatch(command: RuntimeCommand) { return this.session.dispatch(command); } }
export class RuntimeScheduler { drain(session: RuntimeSession) { let result: RuntimeState | null = null; while (session.queue.size) result = session.executeNext(); return result; } }
export class RuntimeRecoveryManager { constructor(private session: RuntimeSession) {} RestoreLastSnapshot() { return this.session.restoreLastSnapshot(); } Rollback() { return this.session.undo('recovery'); } SafeRestart() { return this.RestoreLastSnapshot() ?? this.session.state; } }
export class RuntimeSession { state: RuntimeState; queue = new RuntimeQueue(); locks = new RuntimeLockManager(); history = new RuntimeHistory(); executor = new RuntimeExecutor(); metrics = new RuntimeMetricsStore(); dispatcher = new RuntimeDispatcher(this); recovery = new RuntimeRecoveryManager(this); constructor(initial: Partial<RuntimeState> = {}) { this.state = createRuntimeState(initial); this.history.record(snapshotFromState(this.state, 'system', 'RESTORE')); } dispatch(c: RuntimeCommand) { if (this.state.transitionActive || this.locks.locked || ((c.type === 'CUT' || c.type === 'AUTO') && this.state.lastCommand === c.type)) { this.metrics.drop(`Rejected ${c.type}: runtime locked, active, or duplicate`); return this.state; } this.queue.enqueue(c); this.state = { ...this.state, executionQueue: this.queue.snapshot(), status: 'executing' }; return this.executeNext(); } executeNext() { const c = this.queue.dequeue(); if (!c) return this.state; if (!this.locks.acquire('runtime')) { this.metrics.drop('Runtime lock unavailable'); return this.state; } const start = Date.now(); try { this.state = this.executor.execute(this.state, c); if (c.type === 'UNDO') return this.undo(c.operator); if (c.type === 'REDO') return this.redo(c.operator); this.history.record(snapshotFromState(this.state, c.operator, c.type)); this.metrics.record(Date.now() - start, this.queue.size); return this.state = { ...this.state, executionQueue: this.queue.snapshot() }; } catch (e) { this.metrics.drop(e instanceof Error ? e.message : String(e)); this.state = { ...this.state, status: 'error' }; return this.state; } finally { this.locks.release('runtime'); } } undo(operator = 'operator') { const snap = this.history.undo(snapshotFromState(this.state, operator, 'UNDO')); if (snap) this.state = { ...restore(this.state, snap), lastCommand: 'UNDO' }; return this.state; } redo(operator = 'operator') { const snap = this.history.redo(); if (snap) this.state = { ...restore(this.state, snap), lastCommand: 'REDO' }; return this.state; } restoreLastSnapshot() { const snap = this.history.history.at(-1); if (!snap) return null; this.state = restore(this.state, snap); return this.state; } health(): RuntimeHealth { return { ...this.metrics.metrics, queueSize: this.queue.size, status: this.state.status, transitionActive: this.state.transitionActive, locked: this.locks.locked }; } }
export class ProductionRuntime { readonly session: RuntimeSession; constructor(initial: Partial<RuntimeState> = {}) { this.session = new RuntimeSession(initial); } dispatch(command: RuntimeCommand) { return this.session.dispatch(command); } get state() { return this.session.state; } get health() { return this.session.health(); } get recovery() { return this.session.recovery; } }
