export type WorkspaceId =
  | 'director' | 'solo-streamer' | 'technical-director' | 'audio-engineer'
  | 'graphics-operator' | 'replay-operator' | 'streaming-operator' | 'monitor-wall' | 'compact';

export type WorkspaceZonePolicy = Readonly<{ visible: boolean; collapsible: boolean; defaultSize: 'compact' | 'standard' | 'expanded' }>;
export type WorkspaceDefinition = Readonly<{
  id: WorkspaceId; name: string; shortName: string; commercialName: string; mission: string; description: string; icon: string;
  category: 'production' | 'engineering' | 'creative' | 'distribution' | 'monitoring';
  primaryRole: string; secondaryRoles: readonly string[]; skillLevel: 'guided' | 'professional' | 'expert'; teamSize: 'solo' | 'small-team' | 'production-team';
  primaryTasks: readonly string[]; quickActions: readonly { id: string; label: string; icon: string; emphasis: 'primary' | 'secondary' | 'danger' | 'neutral' }[];
  zones: Readonly<{ leftDock: WorkspaceZonePolicy; centerStage: WorkspaceZonePolicy; rightDock: WorkspaceZonePolicy; bottomWorkspace: WorkspaceZonePolicy }>;
  defaultPanels: readonly string[]; requiredPanels: readonly string[]; optionalPanels: readonly string[];
  centerEmphasis: 'program' | 'preview' | 'balanced' | 'multiview'; density: 'comfortable' | 'professional' | 'dense';
  statusPriorities: readonly ('program' | 'preview' | 'audio' | 'guests' | 'graphics' | 'recording' | 'streaming' | 'destinations' | 'network' | 'automation' | 'alerts')[];
  accentPolicy: 'neutral' | 'director' | 'audio' | 'graphics' | 'replay' | 'streaming' | 'monitoring';
}>;

const zone = (visible = true, defaultSize: WorkspaceZonePolicy['defaultSize'] = 'standard'): WorkspaceZonePolicy => ({ visible, collapsible: true, defaultSize });
const actions = (items: readonly string[]) => items.map((label, index) => ({ id: label.toLowerCase().replaceAll(' ', '-'), label, icon: ['+', '◉', '✦', '●'][index] ?? '•', emphasis: index === 0 ? 'primary' as const : 'secondary' as const }));
const define = (definition: Omit<WorkspaceDefinition, 'zones' | 'requiredPanels'> & Partial<Pick<WorkspaceDefinition, 'zones' | 'requiredPanels'>>): WorkspaceDefinition => Object.freeze({ ...definition, requiredPanels: definition.requiredPanels ?? ['Program', 'Preview'], zones: definition.zones ?? { leftDock: zone(), centerStage: zone(true, 'expanded'), rightDock: zone(), bottomWorkspace: zone() } });

export const workspaceCatalog: readonly WorkspaceDefinition[] = Object.freeze([
  define({ id: 'director', name: 'Director', shortName: 'DIRECTOR', commercialName: 'UBOS Director', mission: 'Run the live production and make the next on-air decision.', description: 'Program-led switching for a production team.', icon: '◈', category: 'production', primaryRole: 'Director', secondaryRoles: ['Producer', 'Switcher'], skillLevel: 'professional', teamSize: 'production-team', primaryTasks: ['Switch scenes', 'Review readiness'], quickActions: actions(['New Scene', 'Invite Guest', 'Arm Graphics', 'Start Recording']), defaultPanels: ['Scenes', 'Audio Mixer', 'Automation', 'Logs'], optionalPanels: ['Guests', 'Graphics'], centerEmphasis: 'program', density: 'professional', statusPriorities: ['program', 'preview', 'alerts', 'audio', 'graphics'], accentPolicy: 'director' }),
  define({ id: 'solo-streamer', name: 'Solo Streamer', shortName: 'SOLO', commercialName: 'UBOS Solo', mission: 'Operate a polished live show from one focused workspace.', description: 'Guided production controls for a single operator.', icon: '◉', category: 'production', primaryRole: 'Solo Streamer', secondaryRoles: ['Host'], skillLevel: 'guided', teamSize: 'solo', primaryTasks: ['Go live', 'Manage guests'], quickActions: actions(['New Scene', 'Invite Guest', 'Start Recording']), defaultPanels: ['Scenes', 'Chat', 'Audio Mixer', 'Logs'], optionalPanels: ['Graphics'], centerEmphasis: 'balanced', density: 'comfortable', statusPriorities: ['program', 'preview', 'streaming', 'guests'], accentPolicy: 'neutral' }),
  define({ id: 'technical-director', name: 'Technical Director', shortName: 'TECHNICAL DIRECTOR', commercialName: 'UBOS Technical Direction', mission: 'Protect signal flow, routing, and operational readiness.', description: 'Engineering oversight without graph mutation.', icon: '⌘', category: 'engineering', primaryRole: 'Technical Director', secondaryRoles: ['Engineer'], skillLevel: 'expert', teamSize: 'production-team', primaryTasks: ['Review routing', 'Monitor pipeline'], quickActions: actions(['Review Routing', 'Open Pipeline']), defaultPanels: ['Routing', 'Production Graph', 'Pipeline', 'Logs'], optionalPanels: ['Sources'], centerEmphasis: 'multiview', density: 'dense', statusPriorities: ['network', 'destinations', 'alerts', 'program'], accentPolicy: 'neutral' }),
  define({ id: 'audio-engineer', name: 'Audio Engineer', shortName: 'AUDIO', commercialName: 'UBOS Audio', mission: 'Keep every voice intelligible and every mix within spec.', description: 'Metering and mix-focused operational workspace.', icon: '♫', category: 'engineering', primaryRole: 'Audio Engineer', secondaryRoles: ['A1'], skillLevel: 'professional', teamSize: 'small-team', primaryTasks: ['Monitor loudness', 'Review guests'], quickActions: actions(['Open Mixer', 'Check Guests']), defaultPanels: ['Audio Mixer', 'Routing', 'Guests', 'Logs'], optionalPanels: ['Sources'], centerEmphasis: 'preview', density: 'dense', statusPriorities: ['audio', 'guests', 'program', 'alerts'], accentPolicy: 'audio' }),
  define({ id: 'graphics-operator', name: 'Graphics Operator', shortName: 'GRAPHICS', commercialName: 'UBOS Graphics', mission: 'Prepare precise on-air graphics and protect safe areas.', description: 'Creative metadata workspace for graphics operations.', icon: '✦', category: 'creative', primaryRole: 'Graphics Operator', secondaryRoles: ['Designer'], skillLevel: 'professional', teamSize: 'small-team', primaryTasks: ['Arm graphics', 'Review safe areas'], quickActions: actions(['Arm Graphics', 'Open Assets']), defaultPanels: ['Graphics', 'Assets', 'Templates', 'Safe Areas', 'Logs'], optionalPanels: ['Scenes'], centerEmphasis: 'preview', density: 'professional', statusPriorities: ['graphics', 'preview', 'alerts'], accentPolicy: 'graphics' }),
  define({ id: 'replay-operator', name: 'Replay Operator', shortName: 'REPLAY', commercialName: 'UBOS Replay', mission: 'Prepare replay moments with confidence and timing.', description: 'Replay catalog and timeline-focused workspace.', icon: '↶', category: 'creative', primaryRole: 'Replay Operator', secondaryRoles: ['EVS'], skillLevel: 'expert', teamSize: 'small-team', primaryTasks: ['Review clips', 'Prepare replay'], quickActions: actions(['Open Clip Library', 'Mark Replay']), defaultPanels: ['Replay', 'Clip Library', 'Timeline', 'Logs'], optionalPanels: ['Scenes'], centerEmphasis: 'program', density: 'dense', statusPriorities: ['program', 'alerts', 'audio'], accentPolicy: 'replay' }),
  define({ id: 'streaming-operator', name: 'Streaming Operator', shortName: 'STREAMING', commercialName: 'UBOS Distribution', mission: 'Deliver a healthy broadcast to every destination.', description: 'Distribution readiness and output health workspace.', icon: '⇡', category: 'distribution', primaryRole: 'Streaming Operator', secondaryRoles: ['Distribution Engineer'], skillLevel: 'professional', teamSize: 'small-team', primaryTasks: ['Review destinations', 'Monitor network'], quickActions: actions(['Review Destinations', 'Check Network']), defaultPanels: ['Destinations', 'Output Health', 'Network', 'Logs'], optionalPanels: ['Recording'], centerEmphasis: 'program', density: 'professional', statusPriorities: ['destinations', 'streaming', 'network', 'recording'], accentPolicy: 'streaming' }),
  define({ id: 'monitor-wall', name: 'Monitor Wall', shortName: 'MONITOR WALL', commercialName: 'UBOS Monitor Wall', mission: 'Maintain shared awareness across the entire production.', description: 'Multiview status workspace for production monitoring.', icon: '▦', category: 'monitoring', primaryRole: 'Monitoring Operator', secondaryRoles: ['Technical Director'], skillLevel: 'professional', teamSize: 'production-team', primaryTasks: ['Observe signals', 'Escalate alerts'], quickActions: actions(['Review Alerts', 'Open Multiview']), defaultPanels: ['Multiview', 'Alerts', 'Health', 'Logs'], optionalPanels: ['Destinations'], centerEmphasis: 'multiview', density: 'dense', statusPriorities: ['alerts', 'program', 'preview', 'network'], accentPolicy: 'monitoring' }),
  define({ id: 'compact', name: 'Compact', shortName: 'COMPACT', commercialName: 'UBOS Compact', mission: 'Keep essential production decisions visible in constrained space.', description: 'A compact operational workspace for focused production.', icon: '▣', category: 'production', primaryRole: 'Producer', secondaryRoles: ['Director'], skillLevel: 'guided', teamSize: 'solo', primaryTasks: ['Review Program', 'Stage Preview'], quickActions: actions(['New Scene', 'Open Scenes']), defaultPanels: ['Scenes', 'Audio Mixer', 'Logs'], optionalPanels: ['Automation'], centerEmphasis: 'balanced', density: 'comfortable', statusPriorities: ['program', 'preview', 'alerts'], accentPolicy: 'neutral', zones: { leftDock: zone(true, 'compact'), centerStage: zone(true, 'expanded'), rightDock: zone(false, 'compact'), bottomWorkspace: zone(true, 'compact') } }),
]);

export const workspaceById = Object.freeze(Object.fromEntries(workspaceCatalog.map((workspace) => [workspace.id, workspace])) as Record<WorkspaceId, WorkspaceDefinition>);
