'use client';

import { useState, type ReactNode } from 'react';
import { workspaceCatalog, workspaceById, type WorkspaceDefinition, type WorkspaceId } from './workspace-definition';
import './workspace-shell.css';

const menuItems = ['File', 'Workspace', 'Production', 'Scenes', 'Sources', 'Guests', 'Audio', 'Graphics', 'Replay', 'Broadcast', 'Social', 'Automation', 'Monitoring', 'Tools', 'Window', 'Help'];
const navItems = [['⌂', 'Dashboard'], ['◈', 'Control Room'], ['⌘', 'Production Graph'], ['▤', 'Production Scenes'], ['◌', 'Sources'], ['♙', 'Guests'], ['♫', 'Audio'], ['✦', 'Graphics'], ['↶', 'Replay'], ['⇡', 'Broadcast I/O'], ['#', 'Social'], ['⏵', 'Automation'], ['▦', 'Monitor Wall'], ['⚙', 'Settings']] as const;
const categoryNames = { production: 'Production', engineering: 'Engineering', creative: 'Creative', distribution: 'Distribution', monitoring: 'Monitoring' } as const;

export function WorkspacePanelHeader({ title, status, required = false, onClose }: { title: string; status: string; required?: boolean; onClose?: () => void }) {
  return <header className="ws-panel-header"><span aria-hidden="true">▦</span><strong>{title}</strong><span className="ws-panel-status">{status}</span><span className="ws-header-actions"><button title="Collapse panel" aria-label={`Collapse ${title}`}>−</button><button title="Maximize panel" aria-label={`Maximize ${title}`}>□</button><button title="Move panel" aria-label={`Move ${title}`}>↔</button><button title="Detach panel" aria-label={`Detach ${title}`}>↗</button>{!required && <button title="Close panel" aria-label={`Close ${title}`} onClick={onClose}>×</button>}<button title="Panel menu" aria-label={`${title} panel menu`}>•••</button></span></header>;
}

function WorkspaceCatalog({ active, onSelect }: { active: WorkspaceId; onSelect: (id: WorkspaceId) => void }) {
  return <div className="ws-catalog" role="dialog" aria-label="Workspace catalog">{(Object.keys(categoryNames) as Array<keyof typeof categoryNames>).map((category) => <section key={category}><h3>{categoryNames[category]}</h3><div className="ws-catalog-grid">{workspaceCatalog.filter((item) => item.category === category).map((item) => <button key={item.id} type="button" className={`ws-catalog-card ${item.id === active ? 'is-active' : ''}`} onClick={() => onSelect(item.id)}><span className="ws-catalog-icon">{item.icon}</span><span><b>{item.name}{item.id === active && ' · Active'}</b><small>{item.primaryRole} · {item.skillLevel}</small><em>{item.mission}</em><small>Panels: {item.defaultPanels.slice(0, 3).join(' · ')}</small></span></button>)}</div></section>)}</div>;
}

function WorkspaceSelector({ workspace, onSelect }: { workspace: WorkspaceDefinition; onSelect: (id: WorkspaceId) => void }) {
  const [open, setOpen] = useState(false);
  const select = (id: WorkspaceId) => { onSelect(id); setOpen(false); };
  return <div className="ws-selector"><button type="button" title={workspace.mission} aria-expanded={open} onClick={() => setOpen(!open)}><span>{workspace.icon}</span>{workspace.name}<span aria-hidden="true">⌄</span></button>{open && <WorkspaceCatalog active={workspace.id} onSelect={select} />}</div>;
}

function GlobalProductionBar() { return <div className="ws-global-bar"><div><b>UBOS</b><span>Launch Day</span><small>Production · Broadcast A</small></div><div className="ws-global-center"><Status label="LIVE IDLE" tone="neutral" /><Status label="REC ARMED" tone="info" /><Status label="RUN 00:00:02" tone="neutral" /><Status label="REHEARSAL" tone="info" /><Status label="AUTOMATION PAUSED" tone="warning" /></div><div className="ws-global-right"><Status label="READY" tone="good" /><Status label="HEALTHY" tone="good" /><Status label="2 ALERTS" tone="warning" /><span title="Connected operators">♙ 3</span><span>12:42 UTC</span><button aria-label="Account menu">◉</button></div></div>; }
function Status({ label, tone }: { label: string; tone: 'neutral' | 'info' | 'good' | 'warning' }) { return <span className={`ws-status ws-status--${tone}`}>{label}</span>; }
function WorkspaceNavigationRail() { return <nav className="ws-nav" aria-label="Application navigation">{navItems.map(([icon, label], index) => <button key={label} className={index === 1 ? 'is-active' : ''} title={label} aria-label={label}><span>{icon}</span><b>{label}</b>{label === 'Guests' && <i>1</i>}</button>)}</nav>; }
function WorkspaceStatusSummary({ workspace }: { workspace: WorkspaceDefinition }) { const values = workspace.id === 'audio-engineer' ? ['Master −14 LUFS', '0 Clipping', '2 Muted', 'Guest 3 Warning'] : workspace.id === 'graphics-operator' ? ['3 Armed', '1 Live', '2 Safe-Area Warnings'] : workspace.id === 'streaming-operator' ? ['4/5 Live', 'TikTok Degraded', 'Recording Armed', 'Network Stable'] : ['Program Ready', 'Preview Ready', '2 Warnings', 'Next Scene: Product Demo']; return <div className="ws-summary" aria-label={`${workspace.name} status summary`}>{values.map((value, i) => <span key={value} className={i === 2 ? 'is-warning' : ''}>{value}</span>)}</div>; }
function WorkspaceBottomArea({ workspace }: { workspace: WorkspaceDefinition }) { const [tab, setTab] = useState(''); const activeTab = workspace.defaultPanels.includes(tab) ? tab : workspace.defaultPanels[0] ?? 'Workspace'; return <section className="ws-bottom"><div className="ws-bottom-tabs" role="tablist">{workspace.defaultPanels.map((panel) => <button key={panel} role="tab" aria-selected={activeTab === panel} onClick={() => setTab(panel)}>{panel}</button>)}<span /><button title="Collapse workbench">−</button><button title="Maximize workbench">□</button><button title="Pin workbench">⌖</button><button title="Workbench menu">•••</button></div><WorkspacePanelHeader title={activeTab} status={`${workspace.defaultPanels.length} operational panels`} required={workspace.requiredPanels.includes(activeTab)} /><div className="ws-bottom-content"><b>{activeTab} workbench</b><p>Presentation metadata is ready for this workspace. Runtime controls remain safely owned by their dedicated boundaries.</p></div></section>; }

export function WorkspaceShell({ children }: { children: ReactNode }) {
  const [workspaceId, setWorkspaceId] = useState<WorkspaceId>('director'); const [locked, setLocked] = useState(false); const workspace = workspaceById[workspaceId];
  return <main className={`workspace-shell workspace-shell--${workspace.density}`} data-workspace={workspaceId}><GlobalProductionBar /><div className="ws-menu">{menuItems.map((item) => <button key={item}>{item}</button>)}</div><WorkspaceNavigationRail /><section className="ws-main"><header className="ws-identity"><div className="ws-identity-title"><span>{workspace.icon}</span><div><p>{workspace.shortName}</p><h1>{workspace.name}</h1><small>{workspace.mission}</small><em>Role: {workspace.primaryRole} · {workspace.density} density</em></div></div><WorkspaceSelector workspace={workspace} onSelect={setWorkspaceId} /><div className="ws-quick-actions" aria-label="Workspace quick actions">{workspace.quickActions.map((action) => <button key={action.id} className={`is-${action.emphasis}`} title={`${action.label} is a presentation-only action`}><span>{action.icon}</span>{action.label}</button>)}</div><div className="ws-identity-actions"><button onClick={() => setLocked(!locked)}>{locked ? 'Locked' : 'Unlocked'}</button><button>Save</button><button>Reset</button></div></header><WorkspaceStatusSummary workspace={workspace} /><div className="ws-alert-strip"><b>Attention</b><span>2 production warnings require operator review. No runtime action is attached.</span></div><div className="ws-layout"><aside className="ws-dock ws-dock--left"><WorkspacePanelHeader title="Production Scenes" status="8 total · 1 warning" required /><p>Scene catalog and readiness metadata remain available in the workbench.</p></aside><section className="ws-center" aria-label="Program and Preview workspace">{children}</section><aside className="ws-dock ws-dock--right"><WorkspacePanelHeader title="Operational Health" status="Ready · 2 alerts" /><p>Guests · 2 connected</p><p>Graphics · 3 armed</p><p>Streaming · 4/5 destinations</p></aside></div><WorkspaceBottomArea workspace={workspace} /></section></main>;
}

export { WorkspaceCatalog, WorkspaceNavigationRail, GlobalProductionBar, WorkspaceStatusSummary, WorkspaceBottomArea };
