import type { ProductionGraph } from '../../../shared/src/production-graph.js';
import type { MediaExecutionAdapter, MediaExecutionAdapterResponse, MediaExecutionIntent, MediaExecutionIntentType, ExecutionRuntimeMode } from '../index.js';
import { createSceneCompositionFromGraph, type CompositionLayer, type CompositionRenderTarget, type SceneComposition } from '../compositor/index.js';
import type { BrowserMediaSourceManager } from '../adapters/webrtc/source-manager.js';
import type { FrameTickEvent } from '../sync/index.js';

type StreamLike = Pick<MediaStream, 'id' | 'getTracks' | 'getVideoTracks'>;
type CanvasLike = HTMLCanvasElement & { width: number; height: number; getContext(type: '2d'): CanvasRenderingContext2D | null };
type ContextLike = Pick<CanvasRenderingContext2D, 'save'|'restore'|'clearRect'|'fillRect'|'strokeRect'|'fillText'|'drawImage'|'beginPath'|'rect'|'clip'|'translate'|'rotate'|'scale'> & Partial<CanvasRenderingContext2D>;

export type BrowserRenderTarget = CompositionRenderTarget | 'debug_composition_preview';
export type BrowserRendererErrorCode = 'RENDER_TARGET_MISSING'|'CANVAS_CONTEXT_UNAVAILABLE'|'SOURCE_STREAM_MISSING'|'VIDEO_ELEMENT_FAILED'|'UNSUPPORTED_LAYER_TYPE'|'RENDER_LOOP_ERROR';
export interface BrowserRendererError { readonly code: BrowserRendererErrorCode; readonly message: string; readonly layerId?: string; readonly sourceId?: string; }
export interface BrowserRendererStats { readonly frameCount: number; readonly droppedFrames: number; readonly averageRenderTimeMs: number; readonly lastRenderDurationMs: number; readonly estimatedFps: number; readonly targetFps: number; readonly running: boolean; }
export interface BrowserRenderOptions { readonly target?: BrowserRenderTarget; readonly debug?: boolean; }
export interface BrowserRenderResult { readonly success: boolean; readonly target: BrowserRenderTarget; readonly compositionId?: string; readonly timestamp: string; readonly frameId?: number; readonly frameTimestamp?: number; readonly warnings: readonly string[]; readonly errors: readonly BrowserRendererError[]; readonly stats: BrowserRendererStats; }
export interface RenderableSource { readonly sourceId: string; readonly stream?: StreamLike; readonly videoElement?: HTMLVideoElement; readonly kind: 'video'|'placeholder'; readonly warning?: string; }

export type RendererBackendType = 'canvas2d' | 'webgl' | 'webgpu' | 'mock';
export type RendererBackendStatus = 'uninitialized' | 'ready' | 'unavailable' | 'destroyed' | 'error';
export interface RendererBackendCapabilities { readonly supportsGpuTextures: boolean; readonly supportsPerformanceOverlay: boolean; readonly placeholder: boolean; readonly maxTextureSize?: number; readonly reason?: string; }
export interface RendererBackendStats { readonly frameCount: number; readonly lastRenderDurationMs: number; readonly averageRenderTimeMs: number; readonly cacheHitCount: number; readonly cacheMissCount: number; }
export interface RenderFrameContext { readonly frameId: number; readonly frameTimestamp: number; readonly graphRevision: number; readonly compositionId: string; readonly canvas: CanvasLike; readonly layers: readonly CompositionLayer[]; readonly runtimeSources: ReadonlyMap<string, RenderableSource>; readonly debugMode: boolean; readonly renderTarget: BrowserRenderTarget; readonly metadata: Record<string, unknown>; }
export interface RendererBackend { readonly id: string; readonly name: string; readonly type: RendererBackendType; status: RendererBackendStatus; readonly capabilities: RendererBackendCapabilities; initialize(): void | Promise<void>; renderFrame(frameContext: RenderFrameContext): void | Promise<void>; resize(width: number, height: number): void | Promise<void>; destroy(): void | Promise<void>; getStats(): RendererBackendStats; }
export type RenderStageName = 'prepare_frame'|'resolve_sources'|'compute_dirty_layers'|'update_cache'|'draw_background'|'draw_layers'|'draw_overlays'|'draw_guides'|'finalize_frame';
export interface RenderPipelineStage { readonly name: RenderStageName; readonly execute: (context: RenderFrameContext) => void; }
export interface RenderPipeline { readonly stages: readonly RenderPipelineStage[]; readonly executedStages: readonly RenderStageName[]; }
export interface RenderCacheEntry { readonly id: string; readonly kind: 'layer'|'source'|'texture'; readonly revision: number; readonly updatedAt: string; readonly metadata: Record<string, unknown>; }
export interface TextureCacheEntry extends RenderCacheEntry { readonly kind: 'texture'; readonly texture: undefined; }
export interface LayerCacheEntry extends RenderCacheEntry { readonly kind: 'layer'; readonly layerId: string; readonly signature: string; }
export interface SourceCacheEntry extends RenderCacheEntry { readonly kind: 'source'; readonly sourceId: string; readonly available: boolean; }
export interface RenderCache { readonly layers: Map<string, LayerCacheEntry>; readonly sources: Map<string, SourceCacheEntry>; readonly textures: Map<string, TextureCacheEntry>; hits: number; misses: number; }
export interface RenderPerformanceMetrics { readonly targetFps: number; readonly frameBudgetMs: number; readonly renderDurationMs: number; readonly overBudget: boolean; readonly droppedFrameEstimated: boolean; readonly dirtyLayerCount: number; readonly totalLayerCount: number; readonly cacheHitCount: number; readonly cacheMissCount: number; }
export interface RendererHealth { readonly backendType: RendererBackendType; readonly targetFps: number; readonly estimatedFps: number; readonly averageRenderMs: number; readonly p95RenderMs: number | null; readonly droppedFrames: number; readonly overBudgetFrames: number; readonly cacheHitRate: number; readonly activeLayerCount: number; readonly dirtyLayerCount: number; readonly memoryPressure: 'unknown'|'normal'|'high'; readonly isHealthy: boolean; readonly warnings: readonly string[]; }
export type RendererRuntimeMode = 'canvas2d_default'|'canvas2d_performance'|'webgl_preview'|'webgpu_preview';

export function isRendererPerfDiagnosticsEnabled(env: Record<string, string | undefined> = {}) { return env.NEXT_PUBLIC_UBOS_RENDER_PERF_DIAGNOSTICS === 'true'; }
export function getPreferredRendererBackend(env: Record<string, string | undefined> = {}) { return env.NEXT_PUBLIC_UBOS_RENDER_BACKEND ?? 'canvas2d'; }
export function createRenderFrameContext(input: Omit<RenderFrameContext, 'runtimeSources'> & { runtimeSources?: ReadonlyMap<string, RenderableSource> }): RenderFrameContext { return { ...input, runtimeSources: input.runtimeSources ?? new Map() }; }
const stable = (value: unknown) => JSON.stringify(value ?? null);
export function hasTransformChanged(previousLayer?: CompositionLayer, nextLayer?: CompositionLayer) { return stable(previousLayer?.bounds) !== stable(nextLayer?.bounds) || previousLayer?.zIndex !== nextLayer?.zIndex; }
export function hasStyleChanged(previousLayer?: CompositionLayer, nextLayer?: CompositionLayer) { return previousLayer?.opacity !== nextLayer?.opacity || previousLayer?.label !== nextLayer?.label; }
export function hasSourceChanged(previousLayer?: CompositionLayer, nextLayer?: CompositionLayer) { return previousLayer?.sourceId !== nextLayer?.sourceId; }
export function hasVisibilityChanged(previousLayer?: CompositionLayer, nextLayer?: CompositionLayer) { return previousLayer?.visible !== nextLayer?.visible; }
export function hasLayerChanged(previousLayer?: CompositionLayer, nextLayer?: CompositionLayer) { return !previousLayer || !nextLayer || hasTransformChanged(previousLayer,nextLayer) || hasStyleChanged(previousLayer,nextLayer) || hasSourceChanged(previousLayer,nextLayer) || hasVisibilityChanged(previousLayer,nextLayer); }
export function getDirtyLayers(previousComposition?: SceneComposition, nextComposition?: SceneComposition) { if (!nextComposition) return [] as CompositionLayer[]; const previous = new Map((previousComposition?.layers ?? []).map((l)=>[l.id,l])); return nextComposition.layers.filter((layer)=>hasLayerChanged(previous.get(layer.id), layer)); }
export function createRenderCache(): RenderCache { return { layers: new Map(), sources: new Map(), textures: new Map(), hits: 0, misses: 0 }; }
export function getCachedLayer(cache: RenderCache, layerId: string) { const entry = cache.layers.get(layerId); entry ? cache.hits++ : cache.misses++; return entry; }
export function setCachedLayer(cache: RenderCache, entry: LayerCacheEntry) { cache.layers.set(entry.layerId, entry); return entry; }
export function invalidateLayer(cache: RenderCache, layerId: string) { return cache.layers.delete(layerId); }
export function invalidateSource(cache: RenderCache, sourceId: string) { return cache.sources.delete(sourceId); }
export function clearRenderCache(cache: RenderCache) { cache.layers.clear(); cache.sources.clear(); cache.textures.clear(); cache.hits = 0; cache.misses = 0; }
export function summarizeRenderCache(cache: RenderCache) { const total = cache.hits + cache.misses; return { layers: cache.layers.size, sources: cache.sources.size, textures: cache.textures.size, hits: cache.hits, misses: cache.misses, hitRate: total ? Math.round((cache.hits / total) * 100) / 100 : 0 }; }
export function createRenderPipeline(custom: Partial<Record<RenderStageName, (context: RenderFrameContext)=>void>> = {}): RenderPipeline { const names: RenderStageName[] = ['prepare_frame','resolve_sources','compute_dirty_layers','update_cache','draw_background','draw_layers','draw_overlays','draw_guides','finalize_frame']; return { stages: names.map((name)=>({ name, execute: custom[name] ?? (()=>undefined) })), executedStages: [] }; }
export function executeRenderPipeline(pipeline: RenderPipeline, context: RenderFrameContext) { const executed: RenderStageName[] = []; for (const stage of pipeline.stages) { stage.execute(context); executed.push(stage.name); } return { stages: pipeline.stages, executedStages: executed } satisfies RenderPipeline; }
export function summarizeRenderPipeline(pipeline: RenderPipeline) { return { stageCount: pipeline.stages.length, stages: pipeline.stages.map((s)=>s.name), executedStages: pipeline.executedStages }; }
export function calculateFrameBudget(targetFps: number) { return Math.round((1000 / Math.max(1, targetFps)) * 100) / 100; }
export function evaluateRenderPerformance(input: Omit<RenderPerformanceMetrics, 'frameBudgetMs'|'overBudget'|'droppedFrameEstimated'> & { frameBudgetMs?: number }): RenderPerformanceMetrics { const frameBudgetMs = input.frameBudgetMs ?? calculateFrameBudget(input.targetFps); const overBudget = input.renderDurationMs > frameBudgetMs; return { ...input, frameBudgetMs, overBudget, droppedFrameEstimated: input.renderDurationMs > frameBudgetMs * 1.5 }; }
export function summarizeRenderPerformance(m: RenderPerformanceMetrics) { return `${m.renderDurationMs}ms/${m.frameBudgetMs}ms ${m.overBudget ? 'over budget' : 'within budget'} dirty=${m.dirtyLayerCount}/${m.totalLayerCount} cache=${m.cacheHitCount}/${m.cacheMissCount}`; }
export function summarizeRendererHealth(h: RendererHealth) { return `${h.backendType} ${h.isHealthy ? 'healthy' : 'degraded'} fps=${h.estimatedFps}/${h.targetFps} avg=${h.averageRenderMs}ms warnings=${h.warnings.length}`; }

export class Canvas2DRendererBackend implements RendererBackend { readonly id='canvas2d'; readonly name='Canvas2D Renderer Backend'; readonly type='canvas2d' as const; status: RendererBackendStatus='uninitialized'; readonly capabilities={ supportsGpuTextures: false, supportsPerformanceOverlay: true, placeholder: false }; private stats={ frameCount:0, lastRenderDurationMs:0, averageRenderTimeMs:0, cacheHitCount:0, cacheMissCount:0 }; constructor(private readonly draw: (context: RenderFrameContext)=>void) {} initialize(){ this.status='ready'; } renderFrame(frameContext: RenderFrameContext){ if (this.status === 'uninitialized') this.initialize(); const start=Date.now(); this.draw(frameContext); const d=Date.now()-start; this.stats={ ...this.stats, frameCount:this.stats.frameCount+1, lastRenderDurationMs:d, averageRenderTimeMs:Math.round(((this.stats.averageRenderTimeMs*this.stats.frameCount)+d)/(this.stats.frameCount+1)) }; } resize(width:number,height:number){ void width; void height; } destroy(){ this.status='destroyed'; } getStats(){ return this.stats; } }
class PlaceholderRendererBackend implements RendererBackend { status: RendererBackendStatus='unavailable'; readonly capabilities: RendererBackendCapabilities; private stats={ frameCount:0, lastRenderDurationMs:0, averageRenderTimeMs:0, cacheHitCount:0, cacheMissCount:0 }; constructor(readonly id:string, readonly name:string, readonly type: RendererBackendType, reason:string){ this.capabilities={ supportsGpuTextures:false, supportsPerformanceOverlay:false, placeholder:true, reason }; } initialize(){ this.status='unavailable'; } renderFrame(){ throw new Error(`${this.name} is a placeholder and unavailable`); } resize(width:number,height:number){ void width; void height; } destroy(){ this.status='destroyed'; } getStats(){ return this.stats; } }
export class WebGLRendererBackend extends PlaceholderRendererBackend { constructor(){ super('webgl','WebGL Renderer Backend (preview placeholder)','webgl','WebGL production rendering is not implemented in Phase 6.9'); } }
export class WebGPURendererBackend extends PlaceholderRendererBackend { constructor(){ super('webgpu','WebGPU Renderer Backend (preview placeholder)','webgpu','WebGPU production rendering is not implemented in Phase 6.9'); } }
export function selectRendererBackend(backends: readonly RendererBackend[], mode: RendererRuntimeMode | string = 'canvas2d_default') { const wants = mode === 'webgl_preview' ? 'webgl' : mode === 'webgpu_preview' ? 'webgpu' : 'canvas2d'; const selected = backends.find((b)=>b.type === wants && b.status !== 'unavailable') ?? backends.find((b)=>b.type === 'canvas2d'); return { backend: selected, fallback: selected?.type !== wants, requestedType: wants as RendererBackendType, availableBackends: backends.map((b)=>({ id:b.id, type:b.type, status:b.status, capabilities:b.capabilities })) }; }

export function isBrowserRendererEnabled(env: Record<string, string | undefined> = {}) { return env.NEXT_PUBLIC_UBOS_BROWSER_RENDERER === 'true'; }
export function isBrowserRendererSyncEnabled(env: Record<string, string | undefined> = {}) { return env.NEXT_PUBLIC_UBOS_MEDIA_SYNC === 'true'; }
export function createBrowserRendererError(code: BrowserRendererErrorCode, message: string, extra: Partial<BrowserRendererError> = {}): BrowserRendererError { return { code, message, ...extra }; }

export function bindMediaStreamToVideoElement(stream: StreamLike, video: HTMLVideoElement) {
  try { video.srcObject = stream as MediaStream; video.muted = true; video.playsInline = true; video.autoplay = true; void video.play?.().catch?.(() => undefined); return undefined; }
  catch { return createBrowserRendererError('VIDEO_ELEMENT_FAILED', `Unable to bind stream ${stream.id} to video element`, { sourceId: stream.id }); }
}
export function createVideoElementForStream(stream: StreamLike, ownerDocument: Document = document) {
  const video = ownerDocument.createElement('video');
  const error = bindMediaStreamToVideoElement(stream, video);
  return { video, error };
}
export function releaseVideoElement(video?: HTMLVideoElement) { if (!video) return; try { video.pause?.(); video.srcObject = null; video.removeAttribute('src'); video.load?.(); } catch { /* runtime cleanup only */ } }
export function resolveLayerRuntimeSource(layer: CompositionLayer, manager?: BrowserMediaSourceManager): RenderableSource {
  const stream = manager?.getStream(layer.sourceId) as StreamLike | undefined;
  if (!stream) return { sourceId: layer.sourceId, kind: 'placeholder', warning: `SOURCE_STREAM_MISSING:${layer.sourceId}` };
  const base: RenderableSource = { sourceId: layer.sourceId, stream, kind: stream.getVideoTracks().some((track) => track.readyState !== 'ended') ? 'video' : 'placeholder' };
  return stream.getVideoTracks().length ? base : { ...base, warning: `SOURCE_STREAM_MISSING:${layer.sourceId}` };
}
export function getRenderableSourceForLayer(layer: CompositionLayer, manager?: BrowserMediaSourceManager, videos = new Map<string, HTMLVideoElement>(), ownerDocument?: Document): RenderableSource {
  const resolved = resolveLayerRuntimeSource(layer, manager);
  if (!resolved.stream || resolved.kind === 'placeholder') return resolved;
  let video = videos.get(layer.sourceId);
  if (!video && ownerDocument) { const created = createVideoElementForStream(resolved.stream, ownerDocument); video = created.video; videos.set(layer.sourceId, video); if (created.error) return { ...resolved, kind: 'placeholder', warning: created.error.code }; }
  return video ? { ...resolved, videoElement: video } : resolved;
}

export class RenderScheduler {
  private running = false; private targetFps = 30; private timer?: ReturnType<typeof setTimeout>; private frameCount = 0; private droppedFrames = 0; private totalMs = 0; private lastMs = 0; private startedAt = 0;
  constructor(private readonly render: () => BrowserRenderResult) {}
  start() { if (this.running) return; this.running = true; this.startedAt = Date.now(); this.tick(); }
  stop() { this.running = false; if (this.timer) clearTimeout(this.timer); }
  renderFrame() { const start = Date.now(); try { const result = this.render(); this.lastMs = Date.now() - start; this.totalMs += this.lastMs; this.frameCount += 1; return result; } catch { this.droppedFrames += 1; throw createBrowserRendererError('RENDER_LOOP_ERROR', 'Render loop failed'); } }
  setTargetFps(fps: number) { this.targetFps = Math.max(1, Math.min(120, Math.round(fps))); }
  getStats(): BrowserRendererStats { const seconds = this.startedAt ? (Date.now() - this.startedAt) / 1000 : 0; return { frameCount: this.frameCount, droppedFrames: this.droppedFrames, averageRenderTimeMs: this.frameCount ? Math.round(this.totalMs / this.frameCount) : 0, lastRenderDurationMs: this.lastMs, estimatedFps: seconds > 0 ? Math.round(this.frameCount / seconds) : 0, targetFps: this.targetFps, running: this.running }; }
  clearStats() { this.frameCount = 0; this.droppedFrames = 0; this.totalMs = 0; this.lastMs = 0; this.startedAt = this.running ? Date.now() : 0; }
  private tick() { if (!this.running) return; try { this.renderFrame(); } catch { this.droppedFrames += 1; } this.timer = setTimeout(() => this.tick(), 1000 / this.targetFps); }
}

export class BrowserMediaRenderer {
  private composition: SceneComposition | undefined; private previousComposition: SceneComposition | undefined; private target: BrowserRenderTarget = 'preview'; private debug = false; private videos = new Map<string, HTMLVideoElement>(); private scheduler = new RenderScheduler(() => this.renderFrame()); private latestError: BrowserRendererError | undefined; private renderCache = createRenderCache(); private pipeline = createRenderPipeline(); private overBudgetFrames = 0; private dirtyLayerCount = 0; private forceFullRedraw = false; private backend: RendererBackend = new Canvas2DRendererBackend((context) => this.drawFrameContext(context)); private backends: RendererBackend[] = [this.backend, new WebGLRendererBackend(), new WebGPURendererBackend()]; private fallbackStatus = 'canvas2d_default';
  constructor(private readonly options: { canvas?: CanvasLike; sourceManager?: BrowserMediaSourceManager; target?: BrowserRenderTarget; debug?: boolean } = {}) { this.target = options.target ?? 'preview'; this.debug = options.debug ?? false; }
  setCanvas(canvas: CanvasLike) { (this.options as { canvas?: CanvasLike }).canvas = canvas; }
  setComposition(composition: SceneComposition) { this.previousComposition = this.composition; this.composition = composition; }
  setDebug(debug: boolean) { this.debug = debug; }
  start() { this.scheduler.start(); } stop() { this.scheduler.stop(); } setTargetFps(fps: number) { this.scheduler.setTargetFps(fps); } getStats() { return this.scheduler.getStats(); } clearStats() { this.scheduler.clearStats(); this.overBudgetFrames = 0; } clearRenderCache() { clearRenderCache(this.renderCache); } forceFullRender() { this.forceFullRedraw = true; } switchBackend(mode: RendererRuntimeMode | string) { const selected = selectRendererBackend(this.backends, mode); if (selected.backend) this.backend = selected.backend; this.fallbackStatus = selected.fallback ? `fallback:${selected.requestedType}->${this.backend.type}` : `active:${this.backend.type}`; return selected; } getRendererDiagnostics() { const stats = this.getStats(); const backendStats = this.backend.getStats(); const performance = evaluateRenderPerformance({ targetFps: stats.targetFps, renderDurationMs: stats.lastRenderDurationMs, dirtyLayerCount: this.dirtyLayerCount, totalLayerCount: this.composition?.layers.length ?? 0, cacheHitCount: this.renderCache.hits + backendStats.cacheHitCount, cacheMissCount: this.renderCache.misses + backendStats.cacheMissCount }); const health = this.getRendererHealthModel(); return { activeBackend: this.backend.type, availableBackends: this.backends.map((b)=>({ id:b.id, name:b.name, type:b.type, status:b.status, capabilities:b.capabilities })), backendCapabilities: this.backend.capabilities, frameBudget: performance.frameBudgetMs, renderDuration: performance.renderDurationMs, overBudgetFrameCount: this.overBudgetFrames, dirtyLayerCount: this.dirtyLayerCount, cacheSummary: summarizeRenderCache(this.renderCache), pipelineStages: summarizeRenderPipeline(this.pipeline), rendererHealth: health, fallbackStatus: this.fallbackStatus, performanceSummary: summarizeRenderPerformance(performance) }; } getRendererHealthModel(): RendererHealth { const stats = this.getStats(); const cache = summarizeRenderCache(this.renderCache); const warnings = [this.latestError?.code, this.fallbackStatus.startsWith('fallback') ? this.fallbackStatus : undefined].filter(Boolean) as string[]; return { backendType: this.backend.type, targetFps: stats.targetFps, estimatedFps: stats.estimatedFps, averageRenderMs: stats.averageRenderTimeMs, p95RenderMs: null, droppedFrames: stats.droppedFrames, overBudgetFrames: this.overBudgetFrames, cacheHitRate: cache.hitRate, activeLayerCount: this.composition?.layers.filter((l)=>l.visible).length ?? 0, dirtyLayerCount: this.dirtyLayerCount, memoryPressure: 'unknown', isHealthy: warnings.length === 0 && this.overBudgetFrames < 5, warnings }; } getHealth() { return { target: this.target, compositionId: this.composition?.id, layerCount: this.composition?.layers.length ?? 0, runtimeSourceCount: this.options.sourceManager?.listSources().length ?? 0, latestError: this.latestError, stats: this.getStats(), renderer: this.getRendererHealthModel() }; }
  render(composition: SceneComposition, options: BrowserRenderOptions = {}) { this.composition = composition; this.target = options.target ?? this.target; this.debug = options.debug ?? this.debug; return this.renderFrame(); }
  renderFrame(frameTick?: FrameTickEvent): BrowserRenderResult {
    const started = Date.now(); const warnings: string[] = []; const errors: BrowserRendererError[] = []; const composition = this.composition; const canvas = this.options.canvas;
    if (!canvas) errors.push(createBrowserRendererError('RENDER_TARGET_MISSING', 'Browser render target canvas is not registered'));
    const context = canvas?.getContext('2d') as ContextLike | null | undefined;
    if (canvas && !context) errors.push(createBrowserRendererError('CANVAS_CONTEXT_UNAVAILABLE', 'Canvas 2D context is unavailable'));
    if (canvas && context && composition) {
      const dirty = this.forceFullRedraw ? [...composition.layers] : getDirtyLayers(this.previousComposition, composition);
      this.dirtyLayerCount = dirty.length;
      for (const layer of composition.layers) {
        const cached = getCachedLayer(this.renderCache, layer.id);
        const signature = stable(layer);
        if (!cached || cached.signature !== signature || dirty.some((d)=>d.id === layer.id)) setCachedLayer(this.renderCache, { id: `layer:${layer.id}`, kind: 'layer', layerId: layer.id, revision: composition.graphRevision, signature, updatedAt: new Date(started).toISOString(), metadata: {} });
      }
      const renderContext = createRenderFrameContext({ frameId: frameTick?.frameId ?? this.scheduler.getStats().frameCount + 1, frameTimestamp: frameTick?.timestamp ?? started, graphRevision: composition.graphRevision, compositionId: composition.id, canvas, layers: composition.layers, debugMode: this.debug, renderTarget: this.target, metadata: { warnings, composition, context } });
      const pipeline = createRenderPipeline({ draw_background: () => this.backend.renderFrame(renderContext) as void });
      this.pipeline = executeRenderPipeline(pipeline, renderContext);
      this.previousComposition = composition;
      this.forceFullRedraw = false;
    }
    else if (canvas && context) this.drawPlaceholder(context, { x: 0, y: 0, width: canvas.width, height: canvas.height }, 'No active composition');
    const duration = Date.now() - started; if (duration > calculateFrameBudget(this.scheduler.getStats().targetFps)) this.overBudgetFrames += 1;
    this.latestError = errors.at(-1); const stats = this.scheduler.getStats();
    return { success: errors.length === 0, target: this.target, ...(composition ? { compositionId: composition.id } : {}), timestamp: new Date(started).toISOString(), ...(frameTick ? { frameId: frameTick.frameId, frameTimestamp: frameTick.timestamp } : {}), warnings, errors, stats };
  }
  private drawFrameContext(frameContext: RenderFrameContext) { const ctx = frameContext.metadata.context as ContextLike; const warnings = frameContext.metadata.warnings as string[]; const composition = frameContext.metadata.composition as SceneComposition; this.drawComposition(ctx, frameContext.canvas, composition, warnings); if (isRendererPerfDiagnosticsEnabled(typeof globalThis !== 'undefined' && 'process' in globalThis ? ((globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {}) : {}) && frameContext.debugMode) this.drawPerformanceOverlay(ctx); }
  private drawPerformanceOverlay(ctx: ContextLike) { const stats = this.getStats(); ctx.fillStyle = 'rgba(15,23,42,0.82)'; ctx.fillRect(12,12,280,116); ctx.fillStyle = '#67e8f9'; ctx.font = '14px sans-serif'; ctx.fillText(`FPS ${stats.estimatedFps}/${stats.targetFps}`, 24, 36); ctx.fillText(`Render ${stats.lastRenderDurationMs}ms budget ${calculateFrameBudget(stats.targetFps)}ms`, 24, 58); ctx.fillText(`Dirty ${this.dirtyLayerCount} cache ${this.renderCache.hits}/${this.renderCache.misses}`, 24, 80); ctx.fillText(`Backend ${this.backend.type}`, 24, 102); }
  private drawComposition(ctx: ContextLike, canvas: CanvasLike, c: SceneComposition, warnings: string[]) { canvas.width = c.canvas.width; canvas.height = c.canvas.height; ctx.clearRect(0,0,canvas.width,canvas.height); ctx.fillStyle = c.background.color ?? c.canvas.backgroundColor; ctx.fillRect(0,0,canvas.width,canvas.height); const layers = [...c.layers].filter((l)=>l.visible).sort((a,b)=>a.zIndex-b.zIndex || a.id.localeCompare(b.id)); if (!layers.length) this.drawPlaceholder(ctx,{x:0,y:0,width:canvas.width,height:canvas.height},'Empty composition'); for (const layer of layers) this.drawLayer(ctx, layer, warnings); if (this.debug) this.drawGuides(ctx, c); }
  private drawLayer(ctx: ContextLike, layer: CompositionLayer, warnings: string[]) { const source = getRenderableSourceForLayer(layer, this.options.sourceManager, this.videos, this.options.canvas?.ownerDocument); if (source.warning) warnings.push(source.warning); ctx.save(); ctx.globalAlpha = Math.max(0, Math.min(1, layer.opacity)); ctx.beginPath(); ctx.rect(layer.bounds.x, layer.bounds.y, layer.bounds.width, layer.bounds.height); ctx.clip(); if (source.videoElement) ctx.drawImage(source.videoElement, layer.bounds.x, layer.bounds.y, layer.bounds.width, layer.bounds.height); else this.drawPlaceholder(ctx, layer.bounds, layer.label || layer.sourceId); if (this.debug) { ctx.strokeStyle = '#22d3ee'; ctx.lineWidth = 3; ctx.strokeRect(layer.bounds.x, layer.bounds.y, layer.bounds.width, layer.bounds.height); } ctx.restore(); }
  private drawPlaceholder(ctx: ContextLike, b: {x:number;y:number;width:number;height:number}, label: string) { ctx.fillStyle = '#111827'; ctx.fillRect(b.x,b.y,b.width,b.height); ctx.strokeStyle = '#f59e0b'; ctx.strokeRect(b.x,b.y,b.width,b.height); ctx.fillStyle = '#fde68a'; ctx.font = '24px sans-serif'; ctx.fillText(label, b.x + 16, b.y + 36); }
  private drawGuides(ctx: ContextLike, c: SceneComposition) { ctx.strokeStyle = '#a78bfa'; ctx.lineWidth = 2; for (const area of c.safeAreas) ctx.strokeRect(area.bounds.x, area.bounds.y, area.bounds.width, area.bounds.height); }
}

export class BrowserRendererStore { private renderers = new Map<string, BrowserMediaRenderer>(); private canvases = new Map<string, CanvasLike>(); private compositions = new Map<BrowserRenderTarget, SceneComposition>(); private stats = new Map<string, BrowserRendererStats>(); private errors = new Map<string, BrowserRendererError>(); registerRenderer(id: string, renderer: BrowserMediaRenderer, canvas?: CanvasLike) { this.renderers.set(id, renderer); if (canvas) this.canvases.set(id, canvas); return renderer; } unregisterRenderer(id: string) { this.renderers.get(id)?.stop(); this.renderers.delete(id); this.canvases.delete(id); } getRenderer(id: string) { return this.renderers.get(id); } listRenderers() { return [...this.renderers.entries()].map(([id, renderer]) => ({ id, renderer, stats: renderer.getStats() })); } setActiveComposition(target: BrowserRenderTarget, composition: SceneComposition) { this.compositions.set(target, composition); } getActiveComposition(target: BrowserRenderTarget) { return this.compositions.get(target); } setRenderStats(id: string, stats: BrowserRendererStats) { this.stats.set(id, stats); } getRenderStats(id: string) { return this.renderers.get(id)?.getStats() ?? this.stats.get(id); } setLatestError(id: string, error: BrowserRendererError) { this.errors.set(id, error); } getLatestError(id: string) { return this.errors.get(id); } clear() { this.renderers.forEach((r)=>r.stop()); this.renderers.clear(); this.canvases.clear(); this.compositions.clear(); this.stats.clear(); this.errors.clear(); } }

const SUPPORTED = ['RENDER_BROWSER_COMPOSITION','START_BROWSER_RENDERER','STOP_BROWSER_RENDERER','UPDATE_BROWSER_RENDER_TARGET','RENDER_FRAME','SELECT_RENDER_BACKEND','CLEAR_RENDER_CACHE','FORCE_FULL_RENDER','UPDATE_RENDER_PERFORMANCE_MODE','REPORT_RENDER_HEALTH'] as const satisfies readonly MediaExecutionIntentType[];
export class BrowserRendererAdapter implements MediaExecutionAdapter { private last?: MediaExecutionAdapterResponse; constructor(private readonly renderer: BrowserMediaRenderer, private readonly mode: ExecutionRuntimeMode = 'live_ready') {} getName() { return 'BrowserRendererAdapter'; } canHandle(intent: MediaExecutionIntent) { return SUPPORTED.includes(intent.type as (typeof SUPPORTED)[number]); } getCapabilities() { return [...SUPPORTED]; } getHealth() { return this.renderer.getHealth(); } execute(intent: MediaExecutionIntent, graph: ProductionGraph): MediaExecutionAdapterResponse { const start = Date.now(); if (this.mode === 'disabled') return this.respond(start, true, ['Browser renderer disabled'], []); if (this.mode === 'dry_run') return this.respond(start, true, [`Dry run browser render intent ${intent.type}`], []); if (!this.canHandle(intent)) return this.respond(start, false, [], [`UNSUPPORTED_INTENT:${intent.type}`]); try { if (intent.type === 'SELECT_RENDER_BACKEND') { this.renderer.switchBackend(String(intent.payload.mode ?? intent.payload.backend ?? 'canvas2d_default')); } else if (intent.type === 'CLEAR_RENDER_CACHE') { this.renderer.clearRenderCache(); } else if (intent.type === 'FORCE_FULL_RENDER') { this.renderer.forceFullRender(); } else if (intent.type === 'UPDATE_RENDER_PERFORMANCE_MODE') { if (typeof intent.payload.targetFps === 'number') this.renderer.setTargetFps(intent.payload.targetFps); } else if (intent.type === 'REPORT_RENDER_HEALTH') { void this.renderer.getRendererHealthModel(); } else if (intent.type === 'START_BROWSER_RENDERER') { if (!isBrowserRendererSyncEnabled(typeof globalThis !== 'undefined' && 'process' in globalThis ? ((globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {}) : {})) this.renderer.start(); } else if (intent.type === 'STOP_BROWSER_RENDERER') this.renderer.stop(); else { const sceneId = String(intent.payload.sceneId ?? graph.preview.sceneId ?? graph.program.sceneId ?? ''); if (sceneId && !this.renderer.getHealth().compositionId) this.renderer.setComposition(createSceneCompositionFromGraph(graph, sceneId, { target: (intent.payload.target as CompositionRenderTarget) ?? 'preview' })); const result = this.renderer.renderFrame(intent.payload.frameTick as FrameTickEvent | undefined); return this.respond(start, result.success, [...result.warnings], result.errors.map((e)=>`${e.code}:${e.message}`)); } return this.respond(start, true, [], []); } catch { return this.respond(start, false, [], ['RENDER_LOOP_ERROR:Browser renderer execution failed']); } } private respond(start: number, success: boolean, warnings: string[], errors: string[]) { this.last = { adapterName: this.getName(), success, timestamp: new Date().toISOString(), latencyMs: Date.now() - start, warnings, errors }; return this.last; } }
export function createBrowserRendererAdapterMetadata(adapter: BrowserRendererAdapter) { return { id: 'browser-renderer-adapter', name: 'Browser Renderer Adapter', type: 'browser-renderer', status: isBrowserRendererEnabled(typeof globalThis !== 'undefined' && 'process' in globalThis ? ((globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {}) : {}) ? 'enabled' : 'disabled', capabilities: adapter.getCapabilities(), isMock: false, isLive: true } as const; }
