export * from './clock.js';
import { createClock, type MediaClock } from './clock.js';
export interface FrameTickEvent { readonly frameId: number; readonly timestamp: number; readonly broadcastTime: number; readonly expectedNextFrameTime: number; readonly jitterEstimate: number; }
export type MediaSyncEventType = 'FRAME_TICK'|'FRAME_DROPPED'|'DRIFT_DETECTED'|'CLOCK_RESYNC'|'TIMESTAMP_ANOMALY';
export interface MediaSyncEvent<T=Record<string, unknown>> { readonly type: MediaSyncEventType; readonly timestamp: number; readonly payload: T; }
export class MediaSyncBus { private listeners = new Map<MediaSyncEventType, Set<(e: MediaSyncEvent)=>void>>(); private events: MediaSyncEvent[] = []; emit<T extends Record<string, unknown>>(type: MediaSyncEventType, payload: T, timestamp = Date.now()) { const event = { type, timestamp, payload } as MediaSyncEvent; this.events = [...this.events, event]; this.listeners.get(type)?.forEach((cb)=>cb(event)); return event; } on(type: MediaSyncEventType, cb: (e: MediaSyncEvent)=>void) { const set = this.listeners.get(type) ?? new Set(); set.add(cb); this.listeners.set(type,set); return () => set.delete(cb); } listEvents() { return [...this.events]; } clear() { this.events = []; } }
export class FrameScheduler { private timer?: ReturnType<typeof setTimeout>; private callbacks = new Set<(tick: FrameTickEvent)=>void>(); private running=false; private lastTickTime=0; private tickCount=0; private droppedFrames=0; constructor(private clock: MediaClock = createClock(), private bus = new MediaSyncBus()) {} start() { if (this.running) return; this.running = true; if (this.clock.getState().status === 'stopped') this.clock.startClock(); this.schedule(); } stop() { this.running=false; if (this.timer) clearTimeout(this.timer); this.clock.stopClock(); } onTick(callback: (tick: FrameTickEvent)=>void) { this.callbacks.add(callback); return () => this.callbacks.delete(callback); } setFrameRate(_fps: number) { /* clock frame rate is fixed per deterministic clock instance */ } getStats() { return { running: this.running, tickCount: this.tickCount, droppedFrames: this.droppedFrames, lastTickTime: this.lastTickTime }; } private schedule() { if (!this.running) return; const s = this.clock.getState(); const actual = Date.now(); const expected = s.startTime + s.pausedTime + s.currentFrame * s.frameIntervalMs; const tick = { frameId: s.currentFrame, timestamp: this.clock.getFrameTimestamp(s.currentFrame), broadcastTime: s.elapsedTime, expectedNextFrameTime: this.clock.getFrameTimestamp(s.currentFrame + 1), jitterEstimate: this.lastTickTime ? Math.abs(actual - this.lastTickTime - s.frameIntervalMs) : 0 }; this.lastTickTime = actual; this.tickCount += 1; this.bus.emit('FRAME_TICK', tick as unknown as Record<string, unknown>, actual); this.callbacks.forEach((cb)=>cb(tick)); const delay = Math.max(0, s.frameIntervalMs - Math.max(0, Date.now() - expected)); this.timer = setTimeout(()=>this.schedule(), delay); } }
export interface SyncDriftMetrics { readonly renderDriftMs: number; readonly audioDriftMs: number; readonly videoDriftMs: number; readonly outputDriftMs: number; }
export class SyncDriftMonitor { private history: SyncDriftMetrics[] = []; constructor(private bus = new MediaSyncBus(), private thresholdMs = 20) {} record(metrics: SyncDriftMetrics) { this.history = [...this.history, metrics]; (Object.entries(metrics) as [keyof SyncDriftMetrics, number][]).forEach(([key,value]) => { if (Math.abs(value) > this.thresholdMs) { console.warn(`Media sync drift detected: ${key}=${value}ms`); this.bus.emit('DRIFT_DETECTED', { metric: key, value, thresholdMs: this.thresholdMs }); } }); return metrics; } reset() { this.history = []; } getHistory() { return [...this.history]; } getLatest() { return this.history.at(-1) ?? { renderDriftMs: 0, audioDriftMs: 0, videoDriftMs: 0, outputDriftMs: 0 }; } }
export class MediaSyncStore { private frames: FrameTickEvent[] = []; private last?: FrameTickEvent; private drift: SyncDriftMetrics[] = []; constructor(private clock: MediaClock = createClock()) {} recordTick(tick: FrameTickEvent) { this.last = tick; this.frames = [...this.frames.slice(-119), tick]; } recordDrift(metrics: SyncDriftMetrics) { this.drift = [...this.drift.slice(-119), metrics]; } getState() { const latest = this.drift.at(-1) ?? { renderDriftMs: 0, audioDriftMs: 0, videoDriftMs: 0, outputDriftMs: 0 }; const max = Math.max(...Object.values(latest).map(Math.abs), this.last?.jitterEstimate ?? 0); return { clockState: this.clock.getState(), frameHistory: [...this.frames], driftHistory: [...this.drift], lastTickResult: this.last, syncHealthSummary: { currentFrame: this.clock.getCurrentFrame(), fps: this.clock.getState().frameRate, droppedFramesCount: 0, drift: latest, jitterEstimate: this.last?.jitterEstimate ?? 0, healthScore: Math.max(0, Math.round(100 - max)) } }; } }
export function isMediaSyncEnabled(env: Record<string,string|undefined> = {}) { return env.NEXT_PUBLIC_UBOS_MEDIA_SYNC === 'true'; }
