export * from './clock.js';
export * from './timing.js';
import { createClock, type MediaClock, type SupportedFrameRate } from './clock.js';

export type FrameTickClassification = 'on_time' | 'late' | 'dropped' | 'duplicated';
export interface FrameTimingDiagnostics { readonly frameId: number; readonly expectedAtMs: number; readonly actualAtMs: number; readonly latenessMs: number; readonly droppedFrames: number; readonly duplicatedFrames: number; readonly driftMs: number; readonly classification: FrameTickClassification; readonly metadataOnly: true; }
export interface FrameTickEvent { readonly frameId: number; readonly timestamp: number; readonly presentationTimestamp?: number; readonly mediaTimestamp?: number; readonly broadcastTime: number; readonly expectedNextFrameTime: number; readonly jitterEstimate: number; readonly diagnostics?: FrameTimingDiagnostics; readonly containsFrameData?: false; readonly metadataOnly?: true; }
export type MediaSyncEventType = 'FRAME_TICK'|'FRAME_DROPPED'|'FRAME_LATE'|'FRAME_DUPLICATED'|'DRIFT_DETECTED'|'CLOCK_RESYNC'|'TIMESTAMP_ANOMALY';
export interface MediaSyncEvent<T=Record<string, unknown>> { readonly type: MediaSyncEventType; readonly timestamp: number; readonly payload: T; readonly metadataOnly: true; }
export interface SyncReference { readonly id: string; readonly kind: 'audio' | 'video' | 'output' | 'external'; readonly timestampMs: number; readonly frameId?: number; readonly samplePosition?: number; readonly metadataOnly: true; }
export interface SynchronizationTarget { readonly id: string; readonly mediaType: 'audio' | 'video'; readonly clockId: string; readonly offsetMs: number; readonly toleranceMs: number; readonly metadataOnly: true; }

export class MediaSyncBus { private listeners = new Map<MediaSyncEventType, Set<(e: MediaSyncEvent)=>void>>(); private events: MediaSyncEvent[] = []; emit<T extends Record<string, unknown>>(type: MediaSyncEventType, payload: T, timestamp = Date.now()) { const event = { type, timestamp, payload, metadataOnly: true } as MediaSyncEvent; this.events = [...this.events, event]; this.listeners.get(type)?.forEach((cb)=>cb(event)); return event; } on(type: MediaSyncEventType, cb: (e: MediaSyncEvent)=>void) { const set = this.listeners.get(type) ?? new Set(); set.add(cb); this.listeners.set(type,set); return () => set.delete(cb); } listEvents() { return [...this.events]; } clear() { this.events = []; } }

export interface FrameSchedulerConfig { readonly frameRate?: SupportedFrameRate | number; readonly lateThresholdMs?: number; readonly driftThresholdMs?: number; readonly now?: () => number; }
export class FrameScheduler { private timer?: ReturnType<typeof setTimeout>; private callbacks = new Set<(tick: FrameTickEvent)=>void>(); private running=false; private lastTickTime=0; private lastFrameId=-1; private tickCount=0; private droppedFrames=0; private lateFrames=0; private duplicatedFrames=0; private driftEvents=0; constructor(private clock: MediaClock = createClock(), private bus = new MediaSyncBus(), private config: FrameSchedulerConfig = {}) {} start() { if (this.running) return; this.running = true; if (this.clock.getState().status === 'stopped') this.clock.startClock(); this.schedule(); } pause() { this.clock.pauseClock(); } resume() { this.clock.resumeClock(); if (this.running) this.schedule(); } stop() { this.running=false; if (this.timer) clearTimeout(this.timer); this.clock.stopClock(); } reset() { this.lastTickTime=0; this.lastFrameId=-1; this.tickCount=0; this.droppedFrames=0; this.lateFrames=0; this.duplicatedFrames=0; this.driftEvents=0; return this.clock.resetClock(); } onTick(callback: (tick: FrameTickEvent)=>void) { this.callbacks.add(callback); return () => this.callbacks.delete(callback); } setFrameRate(_fps: number) { /* frame rate is fixed per deterministic clock instance */ } getStats() { return { running: this.running, tickCount: this.tickCount, droppedFrames: this.droppedFrames, lateFrames: this.lateFrames, duplicatedFrames: this.duplicatedFrames, driftEvents: this.driftEvents, lastTickTime: this.lastTickTime, metadataOnly: true }; } createTick(actualAtMs = Date.now()): FrameTickEvent { const s = this.clock.getState(); const expectedAtMs = s.startTime + s.pausedTime + s.presentationTimestamp; const latenessMs = Math.round((actualAtMs - expectedAtMs) * 1000) / 1000; const frameDelta = this.lastFrameId < 0 ? 1 : s.currentFrame - this.lastFrameId; const droppedFrames = Math.max(0, frameDelta - 1); const duplicatedFrames = frameDelta === 0 ? 1 : 0; const late = latenessMs > (this.config.lateThresholdMs ?? Math.max(4, s.frameIntervalMs / 2)); const classification: FrameTickClassification = droppedFrames > 0 ? 'dropped' : duplicatedFrames > 0 ? 'duplicated' : late ? 'late' : 'on_time'; const diagnostics = { frameId: s.currentFrame, expectedAtMs, actualAtMs, latenessMs, droppedFrames, duplicatedFrames, driftMs: s.driftMs, classification, metadataOnly: true } as const; const tick: FrameTickEvent = { frameId: s.currentFrame, timestamp: s.presentationTimestamp, presentationTimestamp: s.presentationTimestamp, mediaTimestamp: s.mediaTimestamp, broadcastTime: s.elapsedTime, expectedNextFrameTime: this.clock.getFrameTimestamp(s.currentFrame + 1), jitterEstimate: this.lastTickTime ? Math.abs(actualAtMs - this.lastTickTime - s.frameIntervalMs) : 0, diagnostics, containsFrameData: false, metadataOnly: true };
    this.tickCount += 1; this.droppedFrames += droppedFrames; this.duplicatedFrames += duplicatedFrames; if (late) this.lateFrames += 1; if (Math.abs(s.driftMs) > (this.config.driftThresholdMs ?? s.frameIntervalMs)) this.driftEvents += 1; this.lastTickTime = actualAtMs; this.lastFrameId = s.currentFrame; this.bus.emit('FRAME_TICK', tick as unknown as Record<string, unknown>, actualAtMs); if (droppedFrames) this.bus.emit('FRAME_DROPPED', diagnostics as unknown as Record<string, unknown>, actualAtMs); if (late) this.bus.emit('FRAME_LATE', diagnostics as unknown as Record<string, unknown>, actualAtMs); if (duplicatedFrames) this.bus.emit('FRAME_DUPLICATED', diagnostics as unknown as Record<string, unknown>, actualAtMs); if (Math.abs(s.driftMs) > (this.config.driftThresholdMs ?? s.frameIntervalMs)) this.bus.emit('DRIFT_DETECTED', diagnostics as unknown as Record<string, unknown>, actualAtMs); this.callbacks.forEach((cb)=>cb(tick)); return tick; }
  private schedule() { if (!this.running || this.clock.getState().status === 'paused') return; const tick = this.createTick(); const delay = Math.max(0, tick.expectedNextFrameTime - this.clock.getCurrentBroadcastTime()); this.timer = setTimeout(()=>this.schedule(), delay); } }

export interface SyncDriftMetrics { readonly renderDriftMs: number; readonly audioDriftMs: number; readonly videoDriftMs: number; readonly outputDriftMs: number; }
export class SyncDriftMonitor { private history: SyncDriftMetrics[] = []; constructor(private bus = new MediaSyncBus(), private thresholdMs = 20) {} record(metrics: SyncDriftMetrics) { this.history = [...this.history, metrics]; (Object.entries(metrics) as [keyof SyncDriftMetrics, number][]).forEach(([key,value]) => { if (Math.abs(value) > this.thresholdMs) this.bus.emit('DRIFT_DETECTED', { metric: key, value, thresholdMs: this.thresholdMs }); }); return metrics; } reset() { this.history = []; } getHistory() { return [...this.history]; } getLatest() { return this.history.at(-1) ?? { renderDriftMs: 0, audioDriftMs: 0, videoDriftMs: 0, outputDriftMs: 0 }; } }
export class MediaSyncStore { private frames: FrameTickEvent[] = []; private last?: FrameTickEvent; private drift: SyncDriftMetrics[] = []; constructor(private clock: MediaClock = createClock()) {} recordTick(tick: FrameTickEvent) { this.last = tick; this.frames = [...this.frames.slice(-119), tick]; } recordDrift(metrics: SyncDriftMetrics) { this.drift = [...this.drift.slice(-119), metrics]; } getState() { const latest = this.drift.at(-1) ?? { renderDriftMs: 0, audioDriftMs: 0, videoDriftMs: 0, outputDriftMs: 0 }; const max = Math.max(...Object.values(latest).map(Math.abs), this.last?.jitterEstimate ?? 0); return { clockState: this.clock.getState(), frameHistory: [...this.frames], driftHistory: [...this.drift], lastTickResult: this.last, syncHealthSummary: { currentFrame: this.clock.getCurrentFrame(), fps: this.clock.getState().frameRate, droppedFramesCount: this.frames.reduce((sum, frame) => sum + (frame.diagnostics?.droppedFrames ?? 0), 0), drift: latest, jitterEstimate: this.last?.jitterEstimate ?? 0, healthScore: Math.max(0, Math.round(100 - max)) }, containsRuntimeHandles: false }; } }
export function isMediaSyncEnabled(env: Record<string,string|undefined> = {}) { return env.NEXT_PUBLIC_UBOS_MEDIA_SYNC === 'true'; }
