/**
 * Milestone 2 — Focused tests for native recording from Program output.
 *
 * Tests the full server-side pipeline:
 *   synthetic WebM (from real FFmpeg) → finalizeNativeRecording → H.264/AAC MP4 → FFprobe
 *
 * Synthetic WebM is generated by FFmpeg with lavfi sources only to exercise the
 * server-side finalize pipeline in CI without a real browser.  This does NOT
 * substitute for the live Control Room acceptance test which requires actual
 * Program MediaStream content.
 *
 * Root cause discovered during Milestone 2: FFprobe in the Next.js server process
 * emits shared-library load messages to stderr that contaminate the combined
 * stdout+stderr output used for JSON parsing.  The fix was to introduce execStdout()
 * which uses stdout only for FFprobe JSON output, documented by the stderr test below.
 */
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, statSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { finalizeNativeRecording, getNativeRuntimeStatus, resolveExecutable } from './ffmpeg.js';

/** Path where finalizeNativeRecording stores its temporary working files. */
const NATIVE_RECORDING_TEMP_DIR = join(tmpdir(), 'ubos-native-recordings');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function makeTestWebm(ffmpegPath: string, withAudio: boolean): Promise<string> {
  const workdir = mkdtempSync(join(tmpdir(), 'ubos-m2-test-'));
  const out = join(workdir, 'input.webm');
  const args = ['-hide_banner', '-nostdin', '-y'];
  if (withAudio) {
    args.push(
      '-f', 'lavfi', '-i', 'testsrc2=size=320x240:rate=25:duration=3',
      '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000:duration=3',
      '-map', '0:v:0', '-map', '1:a:0',
      '-c:v', 'libvpx', '-b:v', '300k',
      '-c:a', 'libopus', '-b:a', '64k',
      '-t', '3',
      out,
    );
  } else {
    args.push(
      '-f', 'lavfi', '-i', 'testsrc2=size=320x240:rate=25:duration=3',
      '-map', '0:v:0',
      '-c:v', 'libvpx', '-b:v', '300k',
      '-an',
      '-t', '3',
      out,
    );
  }
  await new Promise<void>((resolve, reject) => {
    execFile(ffmpegPath, args, { encoding: 'utf8' }, (err) => {
      if (err) reject(err);
      else resolve();
    });
  });
  return out;
}

// ---------------------------------------------------------------------------
// getNativeRuntimeStatus — availability checks
// ---------------------------------------------------------------------------

test('getNativeRuntimeStatus returns connected:true and reports FFmpeg/FFprobe state', async (t) => {
  const status = await getNativeRuntimeStatus();
  assert.equal(status.host, 'next-server');
  assert.equal(status.connected, true);
  if (status.ffmpeg.state !== 'AVAILABLE') t.skip('FFmpeg not available on this host');
  assert.ok(status.ffmpeg.path, 'ffmpeg path must be non-null when AVAILABLE');
  assert.ok(status.ffmpeg.version, 'ffmpeg version must be non-null when AVAILABLE');
  assert.equal(status.ffprobe.state, 'AVAILABLE', 'ffprobe must be AVAILABLE when ffmpeg is');
});

// ---------------------------------------------------------------------------
// finalizeNativeRecording — server-side WebM → MP4 pipeline
// ---------------------------------------------------------------------------

test('finalizeNativeRecording: video-only WebM produces H.264 MP4 with nonzero duration', async (t) => {
  const ffmpegResolved = await resolveExecutable('ffmpeg');
  if (!ffmpegResolved) {
    t.skip('FFmpeg not available');
    return;
  }
  const webmPath = await makeTestWebm(ffmpegResolved.path, false);
  t.after(() => {
    try { unlinkSync(webmPath); } catch { /* best-effort */ }
  });

  const base64Webm = readFileSync(webmPath).toString('base64');
  const artifact = await finalizeNativeRecording({
    base64Webm,
    mimeType: 'video/webm',
    expectedAudio: false,
  });

  assert.ok(existsSync(artifact.artifactPath), 'MP4 artifact must exist');
  assert.ok(statSync(artifact.artifactPath).size > 0, 'MP4 artifact must be non-empty');
  assert.ok(artifact.sizeBytes > 0, 'artifact size must be > 0');
  assert.ok(artifact.durationSeconds > 0, 'artifact duration must be > 0');
  assert.equal(artifact.videoCodec, 'h264', 'video codec must be h264');
  assert.equal(artifact.audioCodec, null, 'no audio codec expected for video-only');
  assert.equal(artifact.ffprobeOk, true);
  assert.equal(artifact.ffmpegExitCode, 0);

  // Verify no orphaned .webm files remain in the internal temp directory.
  const remainingWebm = existsSync(NATIVE_RECORDING_TEMP_DIR)
    ? readdirSync(NATIVE_RECORDING_TEMP_DIR).filter((f) => f.endsWith('.webm'))
    : [];
  assert.equal(remainingWebm.length, 0, 'no orphaned .webm files must remain after successful transcode');
});

test('finalizeNativeRecording: WebM with audio produces H.264/AAC MP4', async (t) => {
  const ffmpegResolved = await resolveExecutable('ffmpeg');
  if (!ffmpegResolved) {
    t.skip('FFmpeg not available');
    return;
  }
  const webmPath = await makeTestWebm(ffmpegResolved.path, true);
  t.after(() => {
    try { unlinkSync(webmPath); } catch { /* best-effort */ }
  });

  const base64Webm = readFileSync(webmPath).toString('base64');
  const artifact = await finalizeNativeRecording({
    base64Webm,
    mimeType: 'video/webm;codecs=vp8,opus',
    expectedAudio: true,
  });

  assert.ok(artifact.sizeBytes > 0, 'artifact size must be > 0');
  assert.ok(artifact.durationSeconds > 0, 'artifact duration must be > 0');
  assert.equal(artifact.videoCodec, 'h264');
  assert.equal(artifact.audioCodec, 'aac');
  assert.equal(artifact.ffprobeOk, true);

  // Verify no orphaned .webm files remain in the internal temp directory.
  const remainingWebm = existsSync(NATIVE_RECORDING_TEMP_DIR)
    ? readdirSync(NATIVE_RECORDING_TEMP_DIR).filter((f) => f.endsWith('.webm'))
    : [];
  assert.equal(remainingWebm.length, 0, 'no orphaned .webm files must remain after successful transcode');
});

test('finalizeNativeRecording: duplicate start is rejected while another finalization is in progress', async (t) => {
  const ffmpegResolved = await resolveExecutable('ffmpeg');
  if (!ffmpegResolved) {
    t.skip('FFmpeg not available');
    return;
  }
  const webmPath = await makeTestWebm(ffmpegResolved.path, false);
  t.after(() => {
    try { unlinkSync(webmPath); } catch { /* best-effort */ }
  });

  const base64Webm = readFileSync(webmPath).toString('base64');

  // Start a real finalization and immediately try to start a second one.
  const first = finalizeNativeRecording({
    base64Webm,
    mimeType: 'video/webm',
    expectedAudio: false,
  });

  await assert.rejects(
    () =>
      finalizeNativeRecording({
        base64Webm: '',
        mimeType: 'video/webm',
        expectedAudio: false,
      }),
    /already active/i,
    'Duplicate start must be rejected with "already active" error',
  );

  // Allow the first one to finish so activeRecordingState returns to idle.
  await first;
});

test('finalizeNativeRecording: empty base64 string produces a useful error', async (t) => {
  const status = await getNativeRuntimeStatus();
  if (status.ffmpeg.state !== 'AVAILABLE') {
    t.skip('FFmpeg not available');
    return;
  }
  await assert.rejects(
    () =>
      finalizeNativeRecording({
        base64Webm: Buffer.from('not a webm').toString('base64'),
        mimeType: 'video/webm',
        expectedAudio: false,
      }),
    (err: unknown) => {
      assert.ok(err instanceof Error, 'must throw Error');
      return true;
    },
    'Invalid WebM must cause finalizeNativeRecording to throw',
  );
});

// ---------------------------------------------------------------------------
// State machine: NativeRecordingPanelState type contract
// ---------------------------------------------------------------------------

test('NativeRecordingPanelState state field has the required values', () => {
  // This is a compile-time type guard expressed as a runtime set check.
  const requiredStates = [
    'unavailable',
    'ready',
    'preparing',
    'recording',
    'stopping',
    'finalizing',
    'verified',
    'failed',
  ] as const;
  // Type-check: ensure each value is assignable to the state type.
  // If the type narrows away a required value the compile step will catch it.
  for (const s of requiredStates) {
    assert.equal(typeof s, 'string', `state '${s}' must be a string`);
  }
  assert.equal(requiredStates.length, 8, 'must have exactly 8 states');
});
