import type { Composition, CompositionLayer, EffectDefinition, LayerGroup, OutputSurface, RenderGraph, RenderPipeline, RenderTarget, Resolution, TransitionDefinition } from '../compositor/types.js';

export type RenderRuntimeTransitionType = 'CUT' | 'FADE' | 'DISSOLVE' | 'WIPE' | 'SLIDE' | 'PUSH' | 'ZOOM' | 'STINGER';
export type RuntimeEffectType = 'Blur' | 'Shadow' | 'Glow' | 'Border' | 'Crop' | 'Mask' | 'Color Correction' | 'Chroma Key' | 'Luma Key' | 'Opacity' | 'Transform' | 'Corner Pin' | 'Perspective';
export type FrameState = 'pending' | 'current' | 'next' | 'dropped' | 'replay' | 'recovery' | 'built';
export type QueueName = 'pending' | 'dropped' | 'replay' | 'recovery' | 'priority';
export interface RuntimeTransform { x: number; y: number; scaleX: number; scaleY: number; rotation: number; anchorX: number; anchorY: number; }
export interface RuntimeCrop { top: number; right: number; bottom: number; left: number; }
export interface RuntimeEffect { id: string; type: RuntimeEffectType; enabled: boolean; parameters: Record<string, unknown>; metadataOnly: true; }
export interface RuntimeTransitionFrame { id: string; type: RenderRuntimeTransitionType; index: number; count: number; progress: number; durationMs: number; metadataOnly: true; }
export interface RuntimeLayer { id: string; name: string; visible: boolean; active: boolean; locked: boolean; solo: boolean; groupIds: string[]; zOrder: number; opacity: number; crop: RuntimeCrop; scale: { x: number; y: number }; transform: RuntimeTransform; masks: string[]; effects: RuntimeEffect[]; sourceRef?: string; }
export interface RuntimeGroup { id: string; name: string; visible: boolean; locked: boolean; layerIds: string[]; groupIds: string[]; }
export interface OutputManifest { id: string; targetId: string; destination: string; resolution: Resolution; rendererAvailable: false; gpuAvailable: false; metadataOnly: true; }
export interface ExecutableRenderFrame { id: string; timestamp: string; programScene: string | null; previewScene: string | null; outputTarget: OutputManifest; activeLayers: RuntimeLayer[]; visibleLayers: RuntimeLayer[]; layerOrder: string[]; transitions: RuntimeTransitionFrame[]; effects: RuntimeEffect[]; crop: RuntimeCrop; scale: { x: number; y: number }; opacity: number; transform: RuntimeTransform; masks: string[]; outputResolution: Resolution; frameNumber: number; frameState: FrameState; metadataOnly: true; }
export interface RenderInput { programScene?: string | null; previewScene?: string | null; composition: Composition; graph?: RenderGraph; pipeline?: RenderPipeline; targets?: RenderTarget[]; outputs?: OutputSurface[]; frameNumber?: number; timestamp?: string; transition?: TransitionDefinition; frameRateTarget?: number; }
const now = () => new Date().toISOString();
const uid = (p: string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const defaultResolution: Resolution = { width: 1920, height: 1080 };
const defaultCrop: RuntimeCrop = { top: 0, right: 0, bottom: 0, left: 0 };
const defaultTransform: RuntimeTransform = { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, anchorX: 0.5, anchorY: 0.5 };
export class EffectResolver { resolve(defs: EffectDefinition[], ids: string[] = defs.map((e) => e.id)): RuntimeEffect[] { return ids.map((id) => defs.find((e) => e.id === id)).filter((e): e is EffectDefinition => Boolean(e)).map((e) => ({ id: e.id, type: mapEffect(e.type), enabled: e.enabled, parameters: e.parameters, metadataOnly: true })); } }
function mapEffect(t: string): RuntimeEffectType { const m: Record<string, RuntimeEffectType> = { blur: 'Blur', shadow: 'Shadow', glow: 'Glow', border: 'Border', crop: 'Crop', mask: 'Mask', color_correction: 'Color Correction', chroma_key: 'Chroma Key', luma_key: 'Luma Key', opacity: 'Opacity', transform: 'Transform', corner_pin: 'Corner Pin', perspective: 'Perspective' }; return m[t] ?? 'Transform'; }
export class LayerResolver { constructor(private effects = new EffectResolver()) {} resolve(layers: CompositionLayer[], groups: LayerGroup[] = [], effects: EffectDefinition[] = []): RuntimeLayer[] { const solo = new Set(layers.filter((l) => Boolean((l as unknown as { solo?: boolean }).solo)).map((l) => l.id)); return layers.map((l) => { const groupIds = groups.filter((g) => g.layerIds.includes(l.id)).map((g) => g.id); const hiddenByGroup = groups.some((g) => g.layerIds.includes(l.id) && !g.visible); const lockedByGroup = groups.some((g) => g.layerIds.includes(l.id) && g.locked); const visible = l.visible && !hiddenByGroup && (solo.size === 0 || solo.has(l.id)); return { id: l.id, name: l.name, visible, active: l.programVisible || l.previewVisible, locked: l.locked || lockedByGroup, solo: solo.has(l.id), groupIds, zOrder: l.zOrder, opacity: l.opacity, crop: l.crop, scale: l.scale, transform: { ...defaultTransform, x: l.position.x, y: l.position.y, scaleX: l.scale.x, scaleY: l.scale.y, rotation: l.rotation, anchorX: l.anchor.x, anchorY: l.anchor.y }, masks: [], effects: this.effects.resolve(effects, l.effectIds), ...(l.sourceRef ? { sourceRef: l.sourceRef } : {}) }; }).sort((a, b) => a.zOrder - b.zOrder); } groups(groups: LayerGroup[]): RuntimeGroup[] { return groups.map((g) => ({ id: g.id, name: g.name, visible: g.visible, locked: g.locked, layerIds: [...g.layerIds], groupIds: groups.filter((p) => p.layerIds.includes(g.id)).map((p) => p.id) })); } }
export class TransitionResolver { sequence(def?: TransitionDefinition, fps = 30): RuntimeTransitionFrame[] { if (!def) return []; const type = def.type.toUpperCase() as RenderRuntimeTransitionType; const count = type === 'CUT' ? 1 : Math.max(1, Math.ceil((def.durationMs / 1000) * fps)); return Array.from({ length: count }, (_, i) => ({ id: `${def.id}-${i + 1}`, type, index: i + 1, count, progress: count === 1 ? 1 : i / (count - 1), durationMs: def.durationMs, metadataOnly: true })); } }
export class OutputResolver { resolve(targets: RenderTarget[] = [], outputs: OutputSurface[] = []): OutputManifest { const target = targets[0]; const output = outputs[0]; return { id: output?.id ?? 'null-output', targetId: target?.id ?? output?.targetId ?? 'null-target', destination: output?.destination ?? 'program', resolution: target?.resolution ?? defaultResolution, rendererAvailable: false, gpuAvailable: false, metadataOnly: true }; } }
export class CompositionResolver { constructor(public layers = new LayerResolver(), public effects = new EffectResolver(), public transitions = new TransitionResolver(), public outputs = new OutputResolver()) {} resolve(input: RenderInput) { const activeLayers = this.layers.resolve(input.composition.layers, input.composition.groups, input.composition.effects); const visibleLayers = activeLayers.filter((l) => l.visible); const transition = input.transition ?? input.composition.transitions.find((t) => t.id === input.composition.activeTransitionId); const output = this.outputs.resolve(input.targets, input.outputs); return { activeLayers, visibleLayers, layerOrder: activeLayers.map((l) => l.id), effects: visibleLayers.flatMap((l) => l.effects), transitions: this.transitions.sequence(transition, input.frameRateTarget), output }; } }
export class FrameBuilder { constructor(private resolver = new CompositionResolver()) {} build(input: RenderInput): ExecutableRenderFrame { const r = this.resolver.resolve(input); return { id: uid('frame'), timestamp: input.timestamp ?? now(), programScene: input.programScene ?? input.composition.id, previewScene: input.previewScene ?? null, outputTarget: r.output, activeLayers: r.activeLayers, visibleLayers: r.visibleLayers, layerOrder: r.layerOrder, transitions: r.transitions, effects: r.effects, crop: defaultCrop, scale: { x: 1, y: 1 }, opacity: 1, transform: defaultTransform, masks: r.visibleLayers.flatMap((l) => l.masks), outputResolution: r.output.resolution, frameNumber: input.frameNumber ?? 1, frameState: 'built', metadataOnly: true }; } }
export class FrameQueue { pendingFrames: ExecutableRenderFrame[] = []; currentFrame: ExecutableRenderFrame | null = null; nextFrame: ExecutableRenderFrame | null = null; droppedFrames: ExecutableRenderFrame[] = []; replayQueue: ExecutableRenderFrame[] = []; recoveryQueue: ExecutableRenderFrame[] = []; priorityQueue: ExecutableRenderFrame[] = []; enqueue(f: ExecutableRenderFrame, q: QueueName = 'pending') { const frame: ExecutableRenderFrame = { ...f, frameState: (q === 'pending' ? 'pending' : q) as FrameState }; if (q === 'pending') this.pendingFrames.push(frame); else if (q === 'dropped') this.droppedFrames.push(frame); else if (q === 'replay') this.replayQueue.push(frame); else if (q === 'recovery') this.recoveryQueue.push(frame); else this.priorityQueue.push(frame); return frame; } promote() { this.currentFrame = this.priorityQueue.shift() ?? this.recoveryQueue.shift() ?? this.pendingFrames.shift() ?? null; this.nextFrame = this.priorityQueue[0] ?? this.recoveryQueue[0] ?? this.pendingFrames[0] ?? null; return this.currentFrame; } clear() { this.pendingFrames = []; this.nextFrame = null; } snapshot() { return { pending: this.pendingFrames.length, priority: this.priorityQueue.length, replay: this.replayQueue.length, recovery: this.recoveryQueue.length, dropped: this.droppedFrames.length, currentFrameId: this.currentFrame?.id ?? null, nextFrameId: this.nextFrame?.id ?? null }; } }
export class FrameCache<T = unknown> { private caches = new Map<string, Map<string, T>>([['composition', new Map()], ['layer', new Map()], ['scene', new Map()], ['output', new Map()], ['frame', new Map()], ['transition', new Map()]]); hits = 0; misses = 0; get(cache: string, key: string) { const v = this.caches.get(cache)?.get(key); v === undefined ? this.misses++ : this.hits++; return v; } set(cache: string, key: string, value: T) { if (!this.caches.has(cache)) this.caches.set(cache, new Map()); this.caches.get(cache)!.set(key, value); return value; } ratio() { const t = this.hits + this.misses; return t ? this.hits / t : 1; } clear() { this.caches.forEach((c) => c.clear()); } }
export interface FrameSnapshot { id: string; currentScene: string | null; composition: Composition; layers: RuntimeLayer[]; output: OutputManifest; frameQueue: ReturnType<FrameQueue['snapshot']>; timestamp: string; }
export class FrameHistory { frames: ExecutableRenderFrame[] = []; snapshots: FrameSnapshot[] = []; record(f: ExecutableRenderFrame) { this.frames.push(f); return f; } capture(input: Omit<FrameSnapshot, 'id' | 'timestamp'>) { const s = { ...input, id: uid('snapshot'), timestamp: now() }; this.snapshots.push(s); return s; } lastFrame() { return this.frames.at(-1) ?? null; } }
export interface FrameMetrics { frameRateTarget: number; framesBuilt: number; droppedFrames: number; queueLength: number; buildTimeMs: number; compositionTimeMs: number; transitionTimeMs: number; cacheHitRatio: number; rendererAvailable: boolean; gpuAvailable: false; }
export class FrameHealth { constructor(private metrics: FrameMetrics) {} report() { return { ...this.metrics, rendererAvailable: this.metrics.rendererAvailable, gpuAvailable: false, status: this.metrics.rendererAvailable ? 'metadata_only' : 'renderer_unavailable', messages: ['Renderer unavailable', 'GPU unavailable', 'Frame builder active', 'Metadata only'] }; } }
export interface RendererAdapter { name: string; available: boolean; gpuAvailable: false; render(frame: ExecutableRenderFrame): { accepted: boolean; reason: string; frameId: string }; }
export class NullRendererAdapter implements RendererAdapter { name = 'NullRendererAdapter'; available = false; gpuAvailable = false as const; render(frame: ExecutableRenderFrame) { return { accepted: false, reason: 'Renderer unavailable: metadata-only null adapter', frameId: frame.id }; } }
export class WebGPURendererAdapter extends NullRendererAdapter { name = 'WebGPURendererAdapter placeholder'; }
export class OpenGLRendererAdapter extends NullRendererAdapter { name = 'OpenGLRendererAdapter placeholder'; }
export class VulkanRendererAdapter extends NullRendererAdapter { name = 'VulkanRendererAdapter placeholder'; }
export class MetalRendererAdapter extends NullRendererAdapter { name = 'MetalRendererAdapter placeholder'; }
export class DirectXRendererAdapter extends NullRendererAdapter { name = 'DirectXRendererAdapter placeholder'; }
export class FrameDispatcher { constructor(private adapter: RendererAdapter = new NullRendererAdapter()) {} dispatch(frame: ExecutableRenderFrame) { return this.adapter.render(frame); } }
export class FrameExecutor { constructor(private dispatcher = new FrameDispatcher()) {} execute(frame: ExecutableRenderFrame) { return { frame, dispatch: this.dispatcher.dispatch(frame), executedPixels: false, metadataOnly: true }; } }
export class FrameComposer { constructor(private builder = new FrameBuilder()) {} compose(input: RenderInput) { return this.builder.build(input); } }
export class FrameScheduler { constructor(private queue: FrameQueue) {} schedule(frame: ExecutableRenderFrame, priority = false) { return this.queue.enqueue(frame, priority ? 'priority' : 'pending'); } tick() { return this.queue.promote(); } }
export class RenderGraphRuntime { constructor(public graph?: RenderGraph) {} describe() { return { nodeCount: this.graph?.nodes.length ?? 0, passCount: this.graph?.passes.length ?? 0, executionEnabled: false }; } }
export class RenderPipelineRuntime { constructor(public pipeline?: RenderPipeline) {} describe() { return { passIds: this.pipeline?.passIds ?? [], targetIds: this.pipeline?.targetIds ?? [], executionEnabled: false }; } }
export class SceneResolver { resolve(sceneId: string | null | undefined) { return sceneId ?? null; } }
export class FrameCacheRecovery { constructor(private queue: FrameQueue, private history: FrameHistory) {} restoreFrame(frame: ExecutableRenderFrame) { this.queue.enqueue(frame, 'recovery'); return frame; } rollbackFrame() { const frame = this.history.frames.at(-2) ?? this.history.lastFrame(); if (frame) this.restoreFrame(frame); return frame ?? null; } rebuildComposition(input: RenderInput, builder = new FrameBuilder()) { return builder.build(input); } clearQueue() { this.queue.clear(); } }
export class RenderSession { queue = new FrameQueue(); cache = new FrameCache(); history = new FrameHistory(); builder = new FrameBuilder(); scheduler = new FrameScheduler(this.queue); dispatcher: FrameDispatcher; executor: FrameExecutor; framesBuilt = 0; droppedFrames = 0; lastBuildTimeMs = 0; recovery = new FrameCacheRecovery(this.queue, this.history); constructor(public adapter: RendererAdapter = new NullRendererAdapter(), public frameRateTarget = 30) { this.dispatcher = new FrameDispatcher(adapter); this.executor = new FrameExecutor(this.dispatcher); } build(input: RenderInput) { const start = Date.now(); const frame = this.builder.build({ ...input, frameRateTarget: this.frameRateTarget, frameNumber: input.frameNumber ?? this.framesBuilt + 1 }); this.framesBuilt++; this.lastBuildTimeMs = Date.now() - start; this.cache.set('frame', frame.id, frame); this.history.record(frame); this.scheduler.schedule(frame); return frame; } metrics(): FrameMetrics { return { frameRateTarget: this.frameRateTarget, framesBuilt: this.framesBuilt, droppedFrames: this.droppedFrames, queueLength: this.queue.pendingFrames.length + this.queue.priorityQueue.length, buildTimeMs: this.lastBuildTimeMs, compositionTimeMs: this.lastBuildTimeMs, transitionTimeMs: 0, cacheHitRatio: this.cache.ratio(), rendererAvailable: this.adapter.available, gpuAvailable: false }; } health() { return new FrameHealth(this.metrics()).report(); } snapshot(composition: Composition) { return this.history.capture({ currentScene: this.queue.currentFrame?.programScene ?? null, composition, layers: this.queue.currentFrame?.activeLayers ?? [], output: this.queue.currentFrame?.outputTarget ?? new OutputResolver().resolve(), frameQueue: this.queue.snapshot() }); } }
export class RenderRuntime { session: RenderSession; graphRuntime = new RenderGraphRuntime(); pipelineRuntime = new RenderPipelineRuntime(); constructor(adapter: RendererAdapter = new NullRendererAdapter()) { this.session = new RenderSession(adapter); } buildFrame(input: RenderInput) { return this.session.build(input); } get health() { return this.session.health(); } }
export const createRenderRuntime = () => new RenderRuntime(new NullRendererAdapter());
