const assert = { equal: (a: unknown, b: unknown) => { if (a !== b) throw new Error(`Expected ${String(a)} to equal ${String(b)}`); }, deepEqual: (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw new Error(`Expected ${JSON.stringify(a)} to equal ${JSON.stringify(b)}`); }, ok: (v: unknown) => { if (!v) throw new Error('Expected value to be truthy'); } };
import { createRenderRuntime, FrameBuilder, FrameQueue, NullRendererAdapter, TransitionResolver, EffectResolver } from './index.js';
import type { Composition } from '../compositor/types.js';
const meta = { version: '1', description: 'test', metadataOnly: true as const };
const composition: Composition = { ...meta, id: 'comp', name: 'Comp', renderGraphId: 'graph', activeTransitionId: 'tr', groups: [{ ...meta, id: 'grp', name: 'Group', kind: 'graphics', layerIds: ['b'], locked: false, visible: true }], effects: [{ ...meta, id: 'fx', name: 'Blur', type: 'blur', parameters: { radius: 2 }, enabled: true }], transitions: [{ ...meta, id: 'tr', name: 'Fade', type: 'fade', durationMs: 100, parameters: {} }], layers: [{ ...meta, id: 'b', name: 'B', layerType: 'graphics', visible: true, opacity: 1, blendMode: 'normal', position: { x: 0, y: 0 }, scale: { x: 1, y: 1 }, rotation: 0, crop: { top: 0, right: 0, bottom: 0, left: 0 }, anchor: { x: 0.5, y: 0.5 }, zOrder: 2, locked: false, muted: false, selected: false, programVisible: true, previewVisible: true, effectIds: ['fx'] }, { ...meta, id: 'a', name: 'A', layerType: 'graphics', visible: true, opacity: 1, blendMode: 'normal', position: { x: 0, y: 0 }, scale: { x: 1, y: 1 }, rotation: 0, crop: { top: 0, right: 0, bottom: 0, left: 0 }, anchor: { x: 0.5, y: 0.5 }, zOrder: 1, locked: false, muted: false, selected: false, programVisible: true, previewVisible: false, effectIds: [] }] };
const frame = new FrameBuilder().build({ composition, targets: [{ ...meta, id: 'target', name: 'Target', resolution: { width: 1280, height: 720 }, colorSpace: 'srgb', pixelFormat: 'rgba8' }] });
assert.equal(frame.frameNumber, 1);
assert.deepEqual(frame.layerOrder, ['a', 'b']);
assert.equal(frame.visibleLayers.length, 2);
assert.equal(frame.effects[0]?.type, 'Blur');
assert.equal(frame.outputResolution.width, 1280);
assert.ok(frame.transitions.length > 0);
const q = new FrameQueue(); q.enqueue(frame); assert.equal(q.promote()?.id, frame.id);
const rt = createRenderRuntime(); const built = rt.buildFrame({ composition }); assert.equal((rt.session.cache.get('frame', built.id) as { id: string } | undefined)?.id, built.id);
const snap = rt.session.snapshot(composition); assert.equal(snap.composition.id, 'comp');
rt.session.recovery.rollbackFrame(); rt.session.recovery.clearQueue(); assert.equal(rt.session.queue.pendingFrames.length, 0);
assert.equal(new NullRendererAdapter().render(frame).accepted, false);
assert.equal(new TransitionResolver().sequence(composition.transitions[0], 30)[0]?.metadataOnly, true);
assert.equal(new EffectResolver().resolve(composition.effects)[0]?.metadataOnly, true);
assert.equal(rt.health.gpuAvailable, false);
console.log('runtime-render validation passed');
