import type { ProductionGraph } from '../../../shared/src/production-graph.js';
import type { SceneComposition, SceneCompositor } from '../compositor/index.js';
import type { VideoRoutePlan } from '../routing.js';
import type { AudioRoutePlan } from '../audio-routing/index.js';
import type { FrameTickEvent, MediaClock } from '../sync/index.js';
import type { PreviewOutput, ProgramOutput, OutputRuntimeState } from '../output-pipeline.js';
import type { AudioMixer, AudioMixerSnapshot } from '../media-runtime/audio-mixer.js';
import type { RecordingPipelineV2, RecordingPipelineSnapshot } from '../recording-runtime/index.js';
import type { StreamingPipeline } from '../streaming-runtime/index.js';

export type MultiviewPreset = 'two_view'|'quad'|'six_way'|'eight_way'|'nine_way'|'sixteen_way'|'broadcast_truck'|'dynamic'|'custom_grid';
export type MultiviewTileType = 'program'|'preview'|'scene'|'source'|'camera'|'guest'|'browser'|'media'|'recording'|'streaming'|'clock'|'audio_meter'|'runtime_diagnostics'|'cpu_health'|'gpu_health'|'network_health'|'output_health'|'custom';
export type TileHealth = 'healthy'|'warning'|'degraded'|'critical'|'unavailable'|'unknown';
export type ConfidenceStatus = TileHealth;
export type ConfidenceSignal = 'program'|'preview'|'stream'|'recording'|'guest'|'audio'|'network'|'renderer'|'output'|'diagnostics';
export type TallyState = 'none'|'preview'|'program'|'both';
export type OverlayKind = 'label'|'tally'|'safe_title'|'safe_action'|'audio_meter'|'status'|'diagnostics';
export type MultiviewRuntimeEventType = 'multiview_layout_loaded'|'multiview_tile_updated'|'multiview_snapshot_rendered'|'multiview_diagnostics_updated'|'multiview_warning'|'multiview_error';
export type TileWarning = { readonly code: string; readonly message: string; readonly severity: Exclude<TileHealth, 'healthy'|'unknown'>; };
export type TileSource = { readonly kind: MultiviewTileType; readonly id?: string; readonly label?: string; readonly sourceKind?: 'camera'|'media'|'scene'|'output'|'diagnostics'; };
export interface MultiviewBounds { readonly x: number; readonly y: number; readonly width: number; readonly height: number; }
export interface MultiviewGrid { readonly columns: number; readonly rows: number; readonly gapPx: number; }
export interface SafeAreaOverlays { readonly title: MultiviewBounds; readonly action: MultiviewBounds; readonly enabled: boolean; }
export interface TileOverlay { readonly kind: OverlayKind; readonly enabled: boolean; readonly bounds?: MultiviewBounds; readonly label?: string; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; }
export interface MultiviewLayout { readonly id: string; readonly name: string; readonly preset: MultiviewPreset; readonly width: number; readonly height: number; readonly tileCount: number; readonly grid: MultiviewGrid; readonly safeArea: MultiviewBounds; readonly safeOverlays: SafeAreaOverlays; readonly customTiles?: readonly Pick<MultiviewTile, 'id'|'bounds'>[]; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; }
export interface MultiviewTile { readonly id: string; readonly type: MultiviewTileType; readonly label: string; readonly sourceId?: string; readonly sceneId?: string; readonly routeId?: string; readonly outputId?: string; readonly recordingId?: string; readonly streamId?: string; readonly bounds: MultiviewBounds; readonly status: ConfidenceStatus; readonly health: TileHealth; readonly tally: TallyState; readonly overlays: readonly TileOverlay[]; readonly fps?: number; readonly latencyMs?: number; readonly frameAgeMs?: number; readonly warnings: readonly TileWarning[]; readonly diagnostics: Record<string, unknown>; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface StreamingStatusSnapshot { readonly id?: string; readonly state?: string; readonly jobs?: readonly unknown[]; readonly events?: readonly unknown[]; readonly containsRuntimeHandles?: false; readonly containsMediaPayloads?: false; }
export interface RuntimeDiagnostics { readonly generatedAt: string; readonly preview?: OutputRuntimeState; readonly program?: OutputRuntimeState; readonly audio?: AudioMixerSnapshot; readonly recording?: RecordingPipelineSnapshot; readonly streaming?: StreamingStatusSnapshot; readonly compositor?: ReturnType<SceneCompositor['getSnapshot']>; readonly warnings: readonly string[]; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface MultiviewPlan { readonly id: string; readonly preset: MultiviewPreset; readonly layout: MultiviewLayout; readonly tiles: readonly MultiviewTile[]; readonly graphRevision: number; readonly frameId: number; readonly createdAt: string; readonly integrations: Record<string, string|undefined>; readonly diagnostics?: RuntimeDiagnostics; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface MultiviewSnapshot { readonly id: string; readonly planId: string; readonly preset: MultiviewPreset; readonly graphRevision: number; readonly frameId: number; readonly tiles: readonly MultiviewTile[]; readonly healthSummary: ReturnType<typeof summarizeMultiviewHealth>; readonly diagnostics?: RuntimeDiagnostics; readonly events: readonly MultiviewRuntimeEvent[]; readonly createdAt: string; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface ConfidenceMonitor { readonly id: string; readonly planId?: string; readonly graphRevision: number; readonly frameId: number; readonly signals: Readonly<Record<ConfidenceSignal, ConfidenceStatus>>; readonly updatedAt: string; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface MultiviewRuntimeEvent { readonly id: string; readonly type: MultiviewRuntimeEventType; readonly timestamp: string; readonly planId?: string; readonly tileId?: string; readonly message: string; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; }
export interface MultiviewManagerBindings { readonly previewOutput?: PreviewOutput; readonly programOutput?: ProgramOutput; readonly sceneCompositor?: SceneCompositor; readonly audioMixer?: AudioMixer; readonly recordingPipeline?: RecordingPipelineV2; readonly streamingPipeline?: StreamingPipeline | { getSnapshot(): StreamingStatusSnapshot }; }
export interface MultiviewExecutionResult { readonly success: boolean; readonly plan?: MultiviewPlan; readonly monitor?: ConfidenceMonitor; readonly snapshot?: MultiviewSnapshot; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
const now = () => new Date().toISOString();
const eventId = (type:string)=>`${type}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`;
const rank: Record<ConfidenceStatus, number> = { healthy:0, warning:1, degraded:2, critical:3, unavailable:4, unknown:5 };
const counts: Record<MultiviewPreset, number> = { two_view:2, quad:4, six_way:6, eight_way:8, nine_way:9, sixteen_way:16, broadcast_truck:12, dynamic:0, custom_grid:0 };
const defaultTypes: MultiviewTileType[] = ['program','preview','camera','media','audio_meter','recording','streaming','runtime_diagnostics','scene','source','guest','browser','cpu_health','gpu_health','network_health','output_health'];
const clone = <T>(v:T):T => JSON.parse(JSON.stringify(v));
export function buildTileLayout(preset: MultiviewPreset, index: number, total = counts[preset] || 1, width = 1920, height = 1080, grid?: Partial<MultiviewGrid>): MultiviewBounds { if (preset === 'two_view') return { x: index * width / 2, y: 0, width: width / 2, height }; const cols = grid?.columns ?? (preset === 'broadcast_truck' ? 4 : Math.ceil(Math.sqrt(total))); const rows = grid?.rows ?? Math.ceil(total / cols); const gap = grid?.gapPx ?? 0; const w = (width - gap * (cols - 1)) / cols; const h = (height - gap * (rows - 1)) / rows; return { x: (index % cols) * (w + gap), y: Math.floor(index / cols) * (h + gap), width: w, height: h }; }
export function createMultiviewLayout(input: { id?: string; name?: string; preset?: MultiviewPreset; width?: number; height?: number; tileCount?: number; grid?: Partial<MultiviewGrid>; safeArea?: MultiviewBounds; customTiles?: readonly Pick<MultiviewTile,'id'|'bounds'>[]; metadata?: Record<string, unknown>; } = {}): MultiviewLayout { const preset = input.preset ?? 'quad'; const tileCount = input.tileCount ?? (preset === 'dynamic' || preset === 'custom_grid' ? Math.max(1, input.customTiles?.length ?? 4) : counts[preset]); const width = input.width ?? 1920; const height = input.height ?? 1080; const safeArea = input.safeArea ?? { x: width*.05, y: height*.05, width: width*.9, height: height*.9 }; return Object.freeze({ id: input.id ?? `multiview-layout:${preset}:${tileCount}`, name: input.name ?? `${preset.replace('_',' ')} multiview`, preset, width, height, tileCount, grid: Object.freeze({ columns: input.grid?.columns ?? Math.ceil(Math.sqrt(tileCount)), rows: input.grid?.rows ?? Math.ceil(tileCount / Math.ceil(Math.sqrt(tileCount))), gapPx: input.grid?.gapPx ?? 8 }), safeArea, safeOverlays: Object.freeze({ enabled:true, title:{x:safeArea.x,y:safeArea.y,width:safeArea.width,height:safeArea.height*.8}, action:{x:safeArea.x,y:safeArea.y+safeArea.height*.1,width:safeArea.width,height:safeArea.height*.8} }), ...(input.customTiles ? { customTiles: input.customTiles } : {}), metadata: input.metadata ?? {}, containsRuntimeHandles:false }); }
const overlays = (label:string,tally:TallyState): readonly TileOverlay[] => Object.freeze([{kind:'label',enabled:true,label,metadata:{},containsRuntimeHandles:false},{kind:'tally',enabled:tally!=='none',label:tally,metadata:{},containsRuntimeHandles:false},{kind:'safe_title',enabled:true,metadata:{},containsRuntimeHandles:false},{kind:'safe_action',enabled:true,metadata:{},containsRuntimeHandles:false}]);
function tileHealth(type:MultiviewTileType, graph:ProductionGraph, diagnostics?:RuntimeDiagnostics): {health:TileHealth; warnings:TileWarning[]} { const warnings:TileWarning[]=[]; let health:TileHealth='healthy'; if(type==='streaming' && diagnostics?.streaming?.state === 'failed') health='critical'; else if(type==='recording' && diagnostics?.recording?.state === 'failed') health='critical'; else if(type==='audio_meter' && diagnostics?.audio?.state === 'failed') health='critical'; else if(type==='streaming' && !Object.values(graph.destinations).some(d=>d.enabled)) health='warning'; if(health!=='healthy') warnings.push({code:`MULTIVIEW_${type.toUpperCase()}_${health.toUpperCase()}`,message:`${type} confidence tile is ${health}`,severity:health as Exclude<TileHealth,'healthy'|'unknown'>}); return {health,warnings}; }
function makeTile(type: MultiviewTileType, index: number, layout: MultiviewLayout, graph: ProductionGraph, sources: readonly TileSource[] = [], diagnostics?: RuntimeDiagnostics): MultiviewTile { const source = sources[index]; const tileType = source?.kind ?? type; const { health, warnings } = tileHealth(tileType, graph, diagnostics); const tally:TallyState = tileType==='program'?'program':tileType==='preview'?'preview':'none'; const label = source?.label ?? tileType.replace('_',' ').toUpperCase(); return Object.freeze({ id:`multiview-tile:${tileType}:${index}`, type: tileType, label, ...(source?.id ? { sourceId: source.id } : {}), ...(tileType === 'program' ? { sceneId: graph.program.sceneId, ...(diagnostics?.program?.id ? { outputId: diagnostics.program.id } : {}) } : {}), ...(tileType === 'preview' ? { sceneId: graph.preview.sceneId, ...(diagnostics?.preview?.id ? { outputId: diagnostics.preview.id } : {}) } : {}), bounds: layout.customTiles?.[index]?.bounds ?? buildTileLayout(layout.preset, index, layout.tileCount, layout.width, layout.height, layout.grid), status: health, health, tally, overlays: overlays(label,tally), fps: tileType==='program'?diagnostics?.program?.renderState.videoFrame?.frameId ? 30 : 0 : 30, latencyMs: index * 3, frameAgeMs: index * 16, warnings, diagnostics: diagnosticFor(tileType, diagnostics), metadata: { backendIndependent:true, containsMediaPayloads:false }, containsRuntimeHandles:false, containsMediaPayloads:false }); }
const diagnosticFor = (type:MultiviewTileType,d?:RuntimeDiagnostics):Record<string,unknown> => type==='audio_meter'?clone(d?.audio?.levels ?? {}):type==='recording'?clone(d?.recording ?? {}):type==='streaming'?clone((d?.streaming ?? {}) as Record<string, unknown>):type==='runtime_diagnostics'?clone(d ?? {}):{};
export function collectRuntimeDiagnostics(bindings: MultiviewManagerBindings = {}): RuntimeDiagnostics { const warnings:string[]=[]; const safe = <T>(fn:()=>T|undefined,label:string) => { try { return fn(); } catch(e) { warnings.push(`${label}: ${e instanceof Error ? e.message : String(e)}`); return undefined; } }; const preview=safe(()=>bindings.previewOutput?.getRuntimeState(),'preview'); const program=safe(()=>bindings.programOutput?.getRuntimeState(),'program'); const audio=safe(()=>bindings.audioMixer?.getSnapshot(),'audio'); const recording=safe(()=>bindings.recordingPipeline?.getSnapshot(),'recording'); const streaming=safe(()=> 'getSnapshot' in (bindings.streamingPipeline ?? {}) ? (bindings.streamingPipeline as {getSnapshot(): StreamingStatusSnapshot}).getSnapshot() : bindings.streamingPipeline ? { id:'streaming-runtime', state:'available', jobs:(bindings.streamingPipeline as StreamingPipeline).sessions.list(), containsRuntimeHandles:false as const, containsMediaPayloads:false as const } : undefined,'streaming'); const compositor=safe(()=>bindings.sceneCompositor?.getSnapshot(),'compositor'); return Object.freeze({ generatedAt:now(), ...(preview ? { preview } : {}), ...(program ? { program } : {}), ...(audio ? { audio } : {}), ...(recording ? { recording } : {}), ...(streaming ? { streaming } : {}), ...(compositor ? { compositor } : {}), warnings, containsRuntimeHandles:false, containsMediaPayloads:false }); }
export function createMultiviewPlan(input: { graph: ProductionGraph; preset?: MultiviewPreset; layout?: MultiviewLayout; sources?: readonly TileSource[]; compositions?: readonly SceneComposition[]; videoRoutePlan?: VideoRoutePlan; audioRoutePlan?: AudioRoutePlan; mediaClock?: MediaClock; frame?: FrameTickEvent; frameId?: number; metadata?: Record<string, unknown>; bindings?: MultiviewManagerBindings; diagnostics?: RuntimeDiagnostics; }): MultiviewPlan { const diagnostics = input.diagnostics ?? collectRuntimeDiagnostics(input.bindings); const layout = input.layout ?? createMultiviewLayout({ preset: input.preset ?? 'quad', ...(input.preset === 'dynamic' ? { tileCount: Math.max(1, input.sources?.length ?? 4) } : {}) }); const tiles = Array.from({ length: layout.tileCount }, (_, i) => makeTile(defaultTypes[i] ?? 'custom', i, layout, input.graph, input.sources, diagnostics)); const frameId = input.frame?.frameId ?? input.frameId ?? input.mediaClock?.getCurrentFrame() ?? diagnostics.program?.renderState.frameId ?? 0; return Object.freeze({ id:`multiview-plan:${input.graph.metadata.revision}:${frameId}`, preset: layout.preset, layout, tiles, graphRevision: input.graph.metadata.revision, frameId, createdAt: now(), integrations:{ previewOutput:diagnostics.preview?.id, programOutput:diagnostics.program?.id, sceneCompositor:diagnostics.compositor?.id ?? input.compositions?.at(0)?.id, audioMixer:diagnostics.audio?.id, recordingPipeline:diagnostics.recording?.id, streamingPipeline:diagnostics.streaming?.id, videoRoutePlan: input.videoRoutePlan?.id, audioRoutePlan: input.audioRoutePlan?.id }, diagnostics, warnings: diagnostics.warnings, metadata: input.metadata ?? {}, containsRuntimeHandles:false, containsMediaPayloads:false }); }
export function validateMultiviewPlan(plan: MultiviewPlan) { const errors:string[]=[]; const warnings:string[]=[]; if (!plan.tiles.length) errors.push('Multiview plan requires at least one tile'); if (new Set(plan.tiles.map(t=>t.id)).size !== plan.tiles.length) errors.push('Duplicate tile ids'); for (const t of plan.tiles) { if (t.bounds.width <=0 || t.bounds.height <=0) errors.push(`Invalid bounds for ${t.id}`); if (t.overlays.some(o=>o.containsRuntimeHandles!==false)) errors.push(`Runtime handle overlay rejected for ${t.id}`); const meta = JSON.stringify({m:t.metadata,d:t.diagnostics}); if (/MediaStream|HTMLCanvasElement|HTMLVideoElement|AudioNode|Encoded|packet|rawFrame/i.test(meta)) errors.push(`Raw media-like metadata is not allowed in ${t.id}`); } if (/MediaStream|HTMLCanvasElement|HTMLVideoElement|AudioNode|Encoded|packet|rawFrame/i.test(JSON.stringify(plan.metadata))) errors.push('Raw media-like plan metadata is not allowed'); if (plan.containsRuntimeHandles !== false || plan.containsMediaPayloads !== false) errors.push('Multiview plan must remain backend independent and metadata only'); return { valid: errors.length===0, warnings, errors }; }
export const updateMultiviewTile = (plan: MultiviewPlan, tileId: string, patch: Partial<MultiviewTile>): MultiviewPlan => ({ ...plan, tiles: plan.tiles.map(t => t.id === tileId ? { ...t, ...patch, id:t.id, metadata:{...t.metadata, ...(patch.metadata ?? {})}, containsRuntimeHandles:false, containsMediaPayloads:false } : t), containsRuntimeHandles:false, containsMediaPayloads:false });
export const removeMultiviewTile = (plan: MultiviewPlan, tileId: string): MultiviewPlan => ({ ...plan, tiles: plan.tiles.filter(t=>t.id!==tileId), layout:{ ...plan.layout, tileCount: plan.tiles.filter(t=>t.id!==tileId).length } });
export function summarizeMultiviewHealth(plan: MultiviewPlan) { const unhealthyTiles = plan.tiles.filter(t=>!['healthy','unknown'].includes(t.health)); const warnings = [...plan.warnings, ...plan.tiles.flatMap(t=>t.warnings.map(w=>`${t.label}: ${w.message}`))]; const worst = plan.tiles.map(t=>t.health as ConfidenceStatus).sort((a,b)=>rank[b]-rank[a])[0] ?? 'unknown'; return { status: worst, tileCount: plan.tiles.length, unhealthyTiles: unhealthyTiles.length, warnings }; }
export function createMultiviewSnapshot(plan: MultiviewPlan, events: readonly MultiviewRuntimeEvent[] = []): MultiviewSnapshot { return Object.freeze({ id:`multiview-snapshot:${plan.id}:${plan.frameId}`, planId:plan.id, preset:plan.preset, graphRevision:plan.graphRevision, frameId:plan.frameId, tiles: plan.tiles.map(t=>({ ...t, metadata:{...t.metadata, containsMediaPayloads:false}, containsRuntimeHandles:false as const, containsMediaPayloads:false as const })), healthSummary:summarizeMultiviewHealth(plan), ...(plan.diagnostics ? { diagnostics: plan.diagnostics } : {}), events, createdAt:now(), containsRuntimeHandles:false, containsMediaPayloads:false }); }
export function createConfidenceMonitor(input: { plan?: MultiviewPlan; graphRevision?: number; frameId?: number; signals?: Partial<Record<ConfidenceSignal, ConfidenceStatus>>; metadata?: Record<string, unknown>; }): ConfidenceMonitor { const base: Record<ConfidenceSignal, ConfidenceStatus> = { program:'healthy', preview:'healthy', stream:'healthy', recording:'healthy', guest:'healthy', audio:'healthy', network:'healthy', renderer:'healthy', output:'healthy', diagnostics:'healthy' }; return { id:`confidence-monitor:${input.graphRevision ?? input.plan?.graphRevision ?? 0}:${input.frameId ?? input.plan?.frameId ?? 0}`, ...(input.plan ? { planId: input.plan.id } : {}), graphRevision: input.graphRevision ?? input.plan?.graphRevision ?? 0, frameId: input.frameId ?? input.plan?.frameId ?? 0, signals:{ ...base, ...(input.signals ?? {}) }, updatedAt:now(), warnings: input.plan?.warnings ?? [], metadata: input.metadata ?? {} }; }
export function validateConfidenceSignals(monitor: ConfidenceMonitor) { const errors:string[]=[]; (Object.entries(monitor.signals) as [ConfidenceSignal, ConfidenceStatus][]).forEach(([k,v])=>{ if (!(k in monitor.signals) || !(v in rank)) errors.push(`Invalid confidence signal ${k}`); }); return { valid: errors.length===0, warnings: monitor.warnings, errors }; }
export function summarizeConfidenceStatus(monitor: ConfidenceMonitor) { const entries = Object.entries(monitor.signals) as [ConfidenceSignal, ConfidenceStatus][]; const worst = entries.map(([,s])=>s).sort((a,b)=>rank[b]-rank[a])[0] ?? 'unknown'; return { status: worst, healthySignals: entries.filter(([,s])=>s==='healthy').length, warningSignals: entries.filter(([,s])=>s==='warning').length, degradedSignals: entries.filter(([,s])=>s==='degraded').length, criticalSignals: entries.filter(([,s])=>s==='critical').length, unavailableSignals: entries.filter(([,s])=>s==='unavailable').length, warnings: monitor.warnings }; }
export class MultiviewStore { private plan: MultiviewPlan | undefined; private monitor: ConfidenceMonitor | undefined; setMultiviewPlan(plan: MultiviewPlan){ this.plan = plan; return plan; } getMultiviewPlan(){ return this.plan; } listMultiviewTiles(){ return [...(this.plan?.tiles ?? [])]; } getTileById(id:string){ return this.plan?.tiles.find(t=>t.id===id); } getTilesByType(type:MultiviewTileType){ return this.listMultiviewTiles().filter(t=>t.type===type); } setConfidenceMonitor(monitor: ConfidenceMonitor){ this.monitor = monitor; return monitor; } getConfidenceMonitor(){ return this.monitor; } clearMultiview(){ this.plan = undefined; this.monitor = undefined; } }
export class MultiviewManager { readonly store = new MultiviewStore(); private bindings: MultiviewManagerBindings = {}; private events: MultiviewRuntimeEvent[] = []; private listeners = new Set<(event:MultiviewRuntimeEvent)=>void>(); constructor(bindings: MultiviewManagerBindings = {}) { this.bindings = bindings; } bind(bindings: MultiviewManagerBindings){ this.bindings = { ...this.bindings, ...bindings }; this.emit('multiview_diagnostics_updated','Multiview runtime bindings updated'); return this.bindings; } loadLayout(graph:ProductionGraph, layout:MultiviewLayout, sources:readonly TileSource[] = []) { const plan = createMultiviewPlan({ graph, layout, sources, bindings:this.bindings }); this.store.setMultiviewPlan(plan); this.store.setConfidenceMonitor(createConfidenceMonitor({ plan })); this.emit('multiview_layout_loaded',`Loaded multiview layout ${layout.name}`,{planId:plan.id}); return plan; } renderSnapshot(graph?:ProductionGraph) { let plan = this.store.getMultiviewPlan(); if (!plan && graph) plan = createMultiviewPlan({ graph, preset:'quad', bindings:this.bindings }); if (!plan) throw new Error('No multiview plan loaded'); const next = graph ? createMultiviewPlan({ graph, layout:plan.layout, sources:plan.tiles.map(t=>({kind:t.type,label:t.label,...(t.sourceId ? { id:t.sourceId } : {})})), bindings:this.bindings }) : { ...plan, diagnostics: collectRuntimeDiagnostics(this.bindings) }; this.store.setMultiviewPlan(next); const snapshot = createMultiviewSnapshot(next, this.events); this.emit('multiview_snapshot_rendered',`Rendered multiview snapshot ${snapshot.id}`,{planId:next.id, tileCount:next.tiles.length}); return snapshot; } updateTile(tileId:string, patch:Partial<MultiviewTile>) { const plan = this.store.getMultiviewPlan(); if(!plan) throw new Error('No multiview plan loaded'); const next = updateMultiviewTile(plan,tileId,patch); this.store.setMultiviewPlan(next); this.emit('multiview_tile_updated',`Updated tile ${tileId}`,{tileId}); return next; } getEvents(){ return Object.freeze([...this.events]); } onRuntimeEvent(callback:(event:MultiviewRuntimeEvent)=>void){ this.listeners.add(callback); return ()=>this.listeners.delete(callback); } private emit(type:MultiviewRuntimeEventType,message:string,metadata:Record<string,unknown>={}){ const event = Object.freeze({id:eventId(type),type,timestamp:now(),...(metadata.planId?{planId:String(metadata.planId)}:{}),...(metadata.tileId?{tileId:String(metadata.tileId)}:{}),message,metadata,containsRuntimeHandles:false}); this.events.unshift(event); this.listeners.forEach(l=>l(event)); return event; } }
export function executeMockMultiview(plan: MultiviewPlan): MultiviewExecutionResult { const validation = validateMultiviewPlan(plan); const monitor = createConfidenceMonitor({ plan }); return { success: validation.valid, plan, monitor, snapshot: createMultiviewSnapshot(plan), warnings: validation.warnings, errors: validation.errors }; }
export async function createDemoMultiviewLayout() { const layout = createMultiviewLayout({ id:'multiview-layout:demo:2.15', name:'UBOS 2.15 Demo Multiview', preset:'custom_grid', tileCount:8, grid:{columns:4,rows:2,gapPx:10}, metadata:{phase:'2.15'} }); const sources: readonly TileSource[] = [{kind:'program',label:'PROGRAM'},{kind:'preview',label:'PREVIEW'},{kind:'camera',id:'camera-1',label:'CAM 1'},{kind:'camera',id:'camera-2',label:'CAM 2'},{kind:'media',id:'media-rundown',label:'MEDIA'},{kind:'audio_meter',label:'AUDIO'},{kind:'recording',label:'REC'},{kind:'streaming',label:'STREAM'}]; return { layout, sources, description:'Configurable metadata-only multiview with program, preview, cameras, media, audio, recording, and streaming confidence tiles.' }; }
