import type { ProductionGraph } from '../../../shared/src/production-graph.js';
import type { SceneComposition } from '../compositor/index.js';
import type { VideoRoutePlan } from '../routing.js';
import type { AudioRoutePlan } from '../audio-routing/index.js';
import type { FrameTickEvent, MediaClock } from '../sync/index.js';

export type MultiviewPreset = 'two_view'|'quad'|'six_way'|'eight_way'|'nine_way'|'sixteen_way'|'broadcast_truck'|'dynamic';
export type MultiviewTileType = 'program'|'preview'|'scene'|'source'|'guest'|'browser'|'media'|'recording'|'streaming'|'clock'|'audio_meter'|'cpu_health'|'gpu_health'|'network_health'|'output_health'|'custom';
export type TileHealth = 'healthy'|'warning'|'degraded'|'critical'|'unavailable'|'unknown';
export type ConfidenceStatus = 'healthy'|'warning'|'degraded'|'critical'|'unavailable'|'unknown';
export type ConfidenceSignal = 'program'|'preview'|'stream'|'recording'|'guest'|'audio'|'network'|'renderer'|'output';
export type TileWarning = { readonly code: string; readonly message: string; readonly severity: Exclude<TileHealth, 'healthy'|'unknown'>; };
export type TileSource = { readonly kind: MultiviewTileType; readonly id?: string; readonly label?: string; };
export interface MultiviewBounds { readonly x: number; readonly y: number; readonly width: number; readonly height: number; }
export interface MultiviewLayout { readonly preset: MultiviewPreset; readonly width: number; readonly height: number; readonly tileCount: number; readonly safeArea: MultiviewBounds; readonly metadata: Record<string, unknown>; }
export interface MultiviewTile { readonly id: string; readonly type: MultiviewTileType; readonly label: string; readonly sourceId?: string; readonly sceneId?: string; readonly routeId?: string; readonly outputId?: string; readonly recordingId?: string; readonly streamId?: string; readonly bounds: MultiviewBounds; readonly status: ConfidenceStatus; readonly health: TileHealth; readonly fps?: number; readonly latencyMs?: number; readonly frameAgeMs?: number; readonly warnings: readonly TileWarning[]; readonly metadata: Record<string, unknown>; }
export interface MultiviewPlan { readonly id: string; readonly preset: MultiviewPreset; readonly layout: MultiviewLayout; readonly tiles: readonly MultiviewTile[]; readonly graphRevision: number; readonly frameId: number; readonly createdAt: string; readonly integrations: Record<string, string|undefined>; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface MultiviewSnapshot { readonly id: string; readonly planId: string; readonly preset: MultiviewPreset; readonly graphRevision: number; readonly frameId: number; readonly tiles: readonly MultiviewTile[]; readonly healthSummary: ReturnType<typeof summarizeMultiviewHealth>; readonly createdAt: string; readonly containsMediaPayloads: false; }
export interface ConfidenceMonitor { readonly id: string; readonly planId?: string; readonly graphRevision: number; readonly frameId: number; readonly signals: Readonly<Record<ConfidenceSignal, ConfidenceStatus>>; readonly updatedAt: string; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface MultiviewExecutionResult { readonly success: boolean; readonly plan?: MultiviewPlan; readonly monitor?: ConfidenceMonitor; readonly snapshot?: MultiviewSnapshot; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
const now = () => new Date().toISOString();
const rank: Record<ConfidenceStatus, number> = { healthy:0, warning:1, degraded:2, critical:3, unavailable:4, unknown:5 };
const counts: Record<MultiviewPreset, number> = { two_view:2, quad:4, six_way:6, eight_way:8, nine_way:9, sixteen_way:16, broadcast_truck:12, dynamic:0 };
const defaultTypes: MultiviewTileType[] = ['program','preview','streaming','recording','audio_meter','network_health','output_health','clock','scene','source','guest','browser','cpu_health','gpu_health','media','custom'];
export function buildTileLayout(preset: MultiviewPreset, index: number, total = counts[preset] || 1, width = 1920, height = 1080): MultiviewBounds {
  if (preset === 'two_view') return { x: index * width / 2, y: 0, width: width / 2, height };
  const cols = preset === 'broadcast_truck' ? 4 : Math.ceil(Math.sqrt(total)); const rows = Math.ceil(total / cols);
  return { x: (index % cols) * width / cols, y: Math.floor(index / cols) * height / rows, width: width / cols, height: height / rows };
}
function makeTile(type: MultiviewTileType, index: number, total: number, preset: MultiviewPreset, graph: ProductionGraph, sources: readonly TileSource[] = []): MultiviewTile { const source = sources[index]; const tileType = source?.kind ?? type; const warnings: TileWarning[] = []; const health: TileHealth = tileType === 'streaming' && !Object.values(graph.destinations).some(d=>d.enabled) ? 'warning' : 'healthy'; if (health === 'warning') warnings.push({ code:'MOCK_NO_ACTIVE_STREAM', message:'No enabled destination for stream confidence tile', severity:'warning' }); return { id:`multiview-tile:${tileType}:${index}`, type: tileType, label: source?.label ?? tileType.replace('_',' ').toUpperCase(), ...(source?.id ? { sourceId: source.id } : {}), ...(tileType === 'program' ? { sceneId: graph.program.sceneId } : {}), ...(tileType === 'preview' ? { sceneId: graph.preview.sceneId } : {}), bounds: buildTileLayout(preset, index, total), status: health, health, fps: 30, latencyMs: index * 3, frameAgeMs: index * 16, warnings, metadata: { simulated:true, containsMediaPayloads:false } }; }
export function createMultiviewPlan(input: { graph: ProductionGraph; preset?: MultiviewPreset; sources?: readonly TileSource[]; compositions?: readonly SceneComposition[]; videoRoutePlan?: VideoRoutePlan; audioRoutePlan?: AudioRoutePlan; mediaClock?: MediaClock; frame?: FrameTickEvent; frameId?: number; metadata?: Record<string, unknown>; }): MultiviewPlan { const preset = input.preset ?? 'quad'; const total = preset === 'dynamic' ? Math.max(1, input.sources?.length ?? 4) : counts[preset]; const tiles = Array.from({ length: total }, (_, i) => makeTile(defaultTypes[i] ?? 'custom', i, total, preset, input.graph, input.sources)); const createdAt = now(); return { id:`multiview-plan:${input.graph.metadata.revision}:${input.frame?.frameId ?? input.frameId ?? 0}`, preset, layout:{ preset, width:1920, height:1080, tileCount:tiles.length, safeArea:{x:96,y:54,width:1728,height:972}, metadata:{ renderer:'browser-composition-architecture' } }, tiles, graphRevision: input.graph.metadata.revision, frameId: input.frame?.frameId ?? input.frameId ?? input.mediaClock?.getCurrentFrame() ?? 0, createdAt, integrations:{ sceneCompositor: input.compositions?.at(0)?.id, videoRoutePlan: input.videoRoutePlan?.id, audioRoutePlan: input.audioRoutePlan?.id, browserRenderer:'existing-browser-renderer', recordingEngine:'metadata-only', streamingEngine:'metadata-only' }, warnings: [], metadata: input.metadata ?? {} }; }
export function validateMultiviewPlan(plan: MultiviewPlan) { const errors:string[]=[]; const warnings:string[]=[]; if (!plan.tiles.length) errors.push('Multiview plan requires at least one tile'); if (new Set(plan.tiles.map(t=>t.id)).size !== plan.tiles.length) errors.push('Duplicate tile ids'); for (const t of plan.tiles) { if (t.bounds.width <=0 || t.bounds.height <=0) errors.push(`Invalid bounds for ${t.id}`); const meta = JSON.stringify(t.metadata); if (/MediaStream|HTMLCanvasElement|HTMLVideoElement|AudioNode|Encoded|packet|rawFrame/i.test(meta)) errors.push(`Raw media-like metadata is not allowed in ${t.id}`); } if (plan.metadata && /MediaStream|HTMLCanvasElement|rawFrame|packet/i.test(JSON.stringify(plan.metadata))) errors.push('Raw media-like plan metadata is not allowed'); return { valid: errors.length===0, warnings, errors }; }
export const updateMultiviewTile = (plan: MultiviewPlan, tileId: string, patch: Partial<MultiviewTile>): MultiviewPlan => ({ ...plan, tiles: plan.tiles.map(t => t.id === tileId ? { ...t, ...patch, id:t.id, metadata:{...t.metadata, ...(patch.metadata ?? {})} } : t) });
export const removeMultiviewTile = (plan: MultiviewPlan, tileId: string): MultiviewPlan => ({ ...plan, tiles: plan.tiles.filter(t=>t.id!==tileId), layout:{ ...plan.layout, tileCount: plan.tiles.filter(t=>t.id!==tileId).length } });
export function summarizeMultiviewHealth(plan: MultiviewPlan) { const unhealthyTiles = plan.tiles.filter(t=>!['healthy','unknown'].includes(t.health)); const warnings = plan.tiles.flatMap(t=>t.warnings.map(w=>`${t.label}: ${w.message}`)); const worst = plan.tiles.map(t=>t.health as ConfidenceStatus).sort((a,b)=>rank[b]-rank[a])[0] ?? 'unknown'; return { status: worst, tileCount: plan.tiles.length, unhealthyTiles: unhealthyTiles.length, warnings }; }
export function createMultiviewSnapshot(plan: MultiviewPlan): MultiviewSnapshot { return { id:`multiview-snapshot:${plan.id}:${plan.frameId}`, planId:plan.id, preset:plan.preset, graphRevision:plan.graphRevision, frameId:plan.frameId, tiles: plan.tiles.map(t=>({ ...t, metadata:{...t.metadata, containsMediaPayloads:false} })), healthSummary:summarizeMultiviewHealth(plan), createdAt:now(), containsMediaPayloads:false }; }
export function createConfidenceMonitor(input: { plan?: MultiviewPlan; graphRevision?: number; frameId?: number; signals?: Partial<Record<ConfidenceSignal, ConfidenceStatus>>; metadata?: Record<string, unknown>; }): ConfidenceMonitor { const base: Record<ConfidenceSignal, ConfidenceStatus> = { program:'healthy', preview:'healthy', stream:'healthy', recording:'healthy', guest:'healthy', audio:'healthy', network:'healthy', renderer:'healthy', output:'healthy' }; return { id:`confidence-monitor:${input.graphRevision ?? input.plan?.graphRevision ?? 0}:${input.frameId ?? input.plan?.frameId ?? 0}`, ...(input.plan ? { planId: input.plan.id } : {}), graphRevision: input.graphRevision ?? input.plan?.graphRevision ?? 0, frameId: input.frameId ?? input.plan?.frameId ?? 0, signals:{ ...base, ...(input.signals ?? {}) }, updatedAt:now(), warnings:[], metadata: input.metadata ?? {} }; }
export function validateConfidenceSignals(monitor: ConfidenceMonitor) { const errors:string[]=[]; (Object.entries(monitor.signals) as [ConfidenceSignal, ConfidenceStatus][]).forEach(([k,v])=>{ if (!['program','preview','stream','recording','guest','audio','network','renderer','output'].includes(k) || !(v in rank)) errors.push(`Invalid confidence signal ${k}`); }); return { valid: errors.length===0, warnings: monitor.warnings, errors }; }
export function summarizeConfidenceStatus(monitor: ConfidenceMonitor) { const entries = Object.entries(monitor.signals) as [ConfidenceSignal, ConfidenceStatus][]; const worst = entries.map(([,s])=>s).sort((a,b)=>rank[b]-rank[a])[0] ?? 'unknown'; return { status: worst, healthySignals: entries.filter(([,s])=>s==='healthy').length, warningSignals: entries.filter(([,s])=>s==='warning').length, degradedSignals: entries.filter(([,s])=>s==='degraded').length, criticalSignals: entries.filter(([,s])=>s==='critical').length, unavailableSignals: entries.filter(([,s])=>s==='unavailable').length, warnings: monitor.warnings }; }
export class MultiviewStore { private plan: MultiviewPlan | undefined; private monitor: ConfidenceMonitor | undefined; setMultiviewPlan(plan: MultiviewPlan){ this.plan = plan; return plan; } getMultiviewPlan(){ return this.plan; } listMultiviewTiles(){ return [...(this.plan?.tiles ?? [])]; } getTileById(id:string){ return this.plan?.tiles.find(t=>t.id===id); } getTilesByType(type:MultiviewTileType){ return this.listMultiviewTiles().filter(t=>t.type===type); } setConfidenceMonitor(monitor: ConfidenceMonitor){ this.monitor = monitor; return monitor; } getConfidenceMonitor(){ return this.monitor; } clearMultiview(){ this.plan = undefined; this.monitor = undefined; } }
export function executeMockMultiview(plan: MultiviewPlan): MultiviewExecutionResult { const validation = validateMultiviewPlan(plan); const monitor = createConfidenceMonitor({ plan }); return { success: validation.valid, plan, monitor, snapshot: createMultiviewSnapshot(plan), warnings: validation.warnings, errors: validation.errors }; }
