export enum ExtensionCategory { SourceConnector='source_connector', OutputConnector='output_connector', DeviceDriver='device_driver', GraphicsPackage='graphics_package', AutomationPackage='automation_package', WorkflowTemplate='workflow_template', RulePackage='rule_package', AnalyticsModule='analytics_module', MonitoringAdapter='monitoring_adapter', SocialConnector='social_connector', ChatConnector='chat_connector', CaptioningProvider='captioning_provider', TranslationProvider='translation_provider', AIService='ai_service', ControlSurface='control_surface', ReplayExtension='replay_extension', MediaProcessor='media_processor', StorageProvider='storage_provider', AuthenticationProvider='authentication_provider', UIExtension='ui_extension', Theme='theme', ProductionTemplate='production_template', Integration='integration', Custom='custom' }
export enum ExtensionType { DeclarativePackage='declarative_package', UIExtension='ui_extension', ServicePlugin='service_plugin', DevicePlugin='device_plugin', WorkflowBundle='workflow_bundle', RulesBundle='rules_bundle', RemoteIntegration='remote_integration', MediaPipelinePlugin='media_pipeline_plugin', NativePlugin='native_plugin' }
export enum ExtensionRuntimeType { JavaScript='javascript', TypeScriptCompiled='typescript_compiled', WebAssembly='webassembly', Container='container', RemoteAPI='remote_api', Native='native', Declarative='declarative' }
export enum ExtensionProcessType { UI='ui', Background='background', Device='device', Media='media', Automation='automation', Analytics='analytics', External='external' }
export enum ExtensionRiskLevel { Low='low', Medium='medium', High='high', Critical='critical' }
export enum TenantIsolationMode { SingleTenantInstance='single_tenant_instance', MultiTenantIsolated='multi_tenant_isolated', PlatformSharedNoData='platform_shared_no_data', DedicatedDeployment='dedicated_deployment' }
export enum PluginLifecycleState { Discovered='discovered', Downloading='downloading', Verifying='verifying', Installed='installed', Configuring='configuring', Enabled='enabled', Starting='starting', Running='running', Degraded='degraded', Stopped='stopped', Updating='updating', Suspended='suspended', Disabled='disabled', Failed='failed', Uninstalling='uninstalling', Removed='removed' }
export enum PluginRestartPolicy { Never='never', OnFailure='on_failure', LimitedRetries='limited_retries', Always='always', OperatorApproval='operator_approval' }
export enum CertificationLevel { Community='community', Verified='verified', ProductionReady='production_ready', Broadcast='broadcast', Enterprise='enterprise', Security='security', Official='official' }
export interface CapabilityScope { organizationId?:string; tenantId?:string; workspaceId?:string; productionId?:string; resourceType?:string; resourceId?:string; }
export interface RequestedCapability { capability:string; reason:string; required:boolean; scope?:CapabilityScope; riskLevel:ExtensionRiskLevel; }
export interface ExtensionEntrypoint { id:string; runtime:ExtensionRuntimeType; module:string; processType:ExtensionProcessType; startupMode:'manual'|'automatic'|'on_demand'; }
export interface NetworkRequirement { hostPattern:string; protocol:string; ports:number[]; direction:'outbound'|'inbound'; required:boolean; justification:string; }
export interface ExtensionManifest { id:string; name:string; description:string; publisherId:string; version:string; type:ExtensionType; category:ExtensionCategory; entrypoints:ExtensionEntrypoint[]; capabilities:RequestedCapability[]; supportedUBOSVersions:string; supportedEnvironments:string[]; tenantIsolationMode:TenantIsolationMode; riskLevel:ExtensionRiskLevel; dependencies:string[]; configurationSchema?:Record<string,unknown>; networkRequirements?:NetworkRequirement[]; support:{contact:string; responseTargetHours:number}; license:{model:string; expiresAt?:number}; integrity:{signature:string; sha256:string; signedBy:string}; }
export interface ExtensionIdentity { extensionId:string; installationId:string; publisherId:string; tenantId:string; workspaceId?:string; grantedCapabilities:string[]; credentialId:string; installedAt:number; installedBy:string; status:'active'|'suspended'|'restricted'|'revoked'|'expired'; }
export interface ExtensionHealth { extensionId:string; installationId:string; status:'healthy'|'warning'|'degraded'|'critical'|'unavailable'|'unknown'; failureCount:number; restartCount:number; resourceUsage:{cpuPercent:number; memoryBytes:number; networkBytes:number; storageBytes:number}; updatedAt:number; }
export const forbiddenCapabilities=new Set(['security.role.manage','audit.history.modify','credential.export','tenant.*','database.unrestricted','os.unrestricted']);
export const redact=(value:unknown):unknown=>{ if(typeof value==='string') return /(secret|token|key|password|credential)/i.test(value)?'[REDACTED]':value; if(Array.isArray(value)) return value.map(redact); if(value&&typeof value==='object') return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,/(secret|token|key|password|credential)/i.test(k)?'[REDACTED]':redact(v)])); return value; };
export function validateManifest(m:ExtensionManifest):string[]{ const findings:string[]=[]; if(!/^[a-z0-9]+([.-][a-z0-9]+)+$/.test(m.id)) findings.push('invalid extension id'); if(!/^\d+\.\d+\.\d+$/.test(m.version)) findings.push('invalid semantic version'); if(!m.integrity.signature||!m.integrity.sha256.startsWith('sha256:')) findings.push('missing signed integrity'); for(const c of m.capabilities){ if(forbiddenCapabilities.has(c.capability)||c.capability.includes('*')) findings.push(`forbidden capability:${c.capability}`); if(c.required&&c.reason.length<8) findings.push(`insufficient capability reason:${c.capability}`); } if(m.type===ExtensionType.NativePlugin&&m.riskLevel!==ExtensionRiskLevel.Critical) findings.push('native plugins require critical risk classification'); return findings.sort(); }
export function isCompatible(range:string, ubosVersion:string):boolean{ return range==='*'||range.split(',').map(s=>s.trim()).includes(ubosVersion); }
export function authorizeCapability(identity:ExtensionIdentity, capability:string, scope?:CapabilityScope):boolean{ if(identity.status!=='active') return false; if(!identity.grantedCapabilities.includes(capability)) return false; return !scope?.tenantId||scope.tenantId===identity.tenantId; }
export interface SandboxLimits { maximumMemoryMb:number; maximumCPUPercent:number; maximumThreads:number; maximumOpenFiles:number; networkPolicyId:string; executionTimeoutMs?:number; restartPolicy:PluginRestartPolicy; }
export interface Installation { manifest:ExtensionManifest; identity:ExtensionIdentity; state:PluginLifecycleState; limits:SandboxLimits; approvedBy:string; createdAt:number; lastError?:string; }
export class PluginRuntime { #installations=new Map<string,Installation>(); #health=new Map<string,ExtensionHealth>(); #audit:string[]=[]; constructor(readonly ubosVersion='v5.11'){}
 install(manifest:ExtensionManifest,input:{tenantId:string; workspaceId?:string; installedBy:string; approvedBy:string; capabilities:string[]; limits:SandboxLimits; at:number}):Installation{ const findings=validateManifest(manifest); if(findings.length) throw new Error(`manifest rejected:${findings.join(',')}`); if(!isCompatible(manifest.supportedUBOSVersions,this.ubosVersion)) throw new Error('incompatible UBOS version'); if(manifest.riskLevel===ExtensionRiskLevel.Critical&&input.approvedBy===input.installedBy) throw new Error('critical extension requires elevated approval'); const id=`inst:${manifest.id}:${input.tenantId}`; const identity:ExtensionIdentity={extensionId:manifest.id,installationId:id,publisherId:manifest.publisherId,tenantId:input.tenantId,grantedCapabilities:input.capabilities.filter(c=>manifest.capabilities.some(r=>r.capability===c)),credentialId:`cred:${id}`,installedAt:input.at,installedBy:input.installedBy,status:'active', ...(input.workspaceId ? {workspaceId: input.workspaceId} : {})}; const installed={manifest:{...manifest,description:String(redact(manifest.description))},identity,state:PluginLifecycleState.Installed,limits:input.limits,approvedBy:input.approvedBy,createdAt:input.at}; this.#installations.set(id,installed); this.#audit.push(`ExtensionInstalled:${manifest.id}:${input.tenantId}`); return structuredClone(installed); }
 enable(id:string,at:number):void{ const i=this.#require(id); this.#installations.set(id,{...i,state:PluginLifecycleState.Running}); this.#health.set(id,{extensionId:i.identity.extensionId,installationId:id,status:'healthy',failureCount:0,restartCount:0,resourceUsage:{cpuPercent:0,memoryBytes:0,networkBytes:0,storageBytes:0},updatedAt:at}); this.#audit.push(`ExtensionEnabled:${id}`); }
 execute(id:string,capability:string,scope:{tenantId?:string},payloadBytes=0):boolean{ const i=this.#require(id); if(i.state!==PluginLifecycleState.Running) throw new Error('extension is not running'); if(payloadBytes>64_000) throw new Error('message size exceeded'); const allowed=authorizeCapability(i.identity,capability,scope); this.#audit.push(`${allowed?'ExtensionCommandAllowed':'ExtensionCommandDenied'}:${id}:${capability}`); return allowed; }
 recordCrash(id:string,reason:string,at:number):void{ const i=this.#require(id); const h=this.#health.get(id)??{extensionId:i.identity.extensionId,installationId:id,status:'unknown' as const,failureCount:0,restartCount:0,resourceUsage:{cpuPercent:0,memoryBytes:0,networkBytes:0,storageBytes:0},updatedAt:at}; const failures=h.failureCount+1; const suspend=failures>=5||i.limits.restartPolicy===PluginRestartPolicy.Never; this.#installations.set(id,{...i,state:suspend?PluginLifecycleState.Suspended:PluginLifecycleState.Degraded,lastError:String(redact(reason))}); this.#health.set(id,{...h,status:suspend?'critical':'degraded',failureCount:failures,restartCount:h.restartCount+(suspend?0:1),updatedAt:at}); this.#audit.push(`ExtensionCrashed:${id}:${suspend?'suspended':'contained'}`); }
 uninstall(id:string,at:number):void{ const i=this.#require(id); this.#installations.set(id,{...i,state:PluginLifecycleState.Removed,identity:{...i.identity,status:'revoked'}}); this.#audit.push(`ExtensionUninstalled:${id}:${at}`); }
 snapshot(){ return structuredClone({installations:[...this.#installations.values()].sort((a,b)=>a.identity.installationId.localeCompare(b.identity.installationId)),health:[...this.#health.values()],audit:this.#audit.slice(-1000)}); }
 #require(id:string){ const i=this.#installations.get(id); if(!i) throw new Error('unknown installation'); return i; }}
