export type ClusterRole = 'controller' | 'render_node' | 'media_node' | 'audio_node' | 'recording_node' | 'streaming_node' | 'replay_node' | 'standby_node' | 'observer_node';
export type ClusterNodeState = 'online' | 'offline' | 'standby' | 'degraded' | 'recovering' | 'unavailable';
export type ClusterCommandType = 'REGISTER_NODE' | 'REMOVE_NODE' | 'ASSIGN_NODE_ROLE' | 'MARK_NODE_ONLINE' | 'MARK_NODE_OFFLINE' | 'CREATE_REDUNDANCY_GROUP' | 'ACTIVATE_FAILOVER' | 'CANCEL_FAILOVER' | 'PROMOTE_STANDBY' | 'DEMOTE_NODE' | 'CREATE_CLUSTER_SNAPSHOT' | 'RESTORE_CLUSTER_SNAPSHOT';
export type NodeCapability = 'control' | 'render' | 'media' | 'audio' | 'recording' | 'streaming' | 'replay' | 'standby' | 'observe';
export interface ClusterNode { id: string; name: string; roles: ClusterRole[]; state: ClusterNodeState; capabilities: NodeCapability[]; site?: string; metadataOnly: true; registeredAt: string; updatedAt: string; runtimeHandle?: never; socket?: never; ipAddress?: never; credentials?: never; }
export interface NodeAssignment { id: string; nodeId: string; role: ClusterRole; sessionId?: string; active: boolean; metadataOnly: true; }
export interface RedundancyGroup { id: string; name: string; nodeIds: string[]; activeNodeId?: string; standbyNodeIds: string[]; policyId?: string; metadataOnly: true; }
export interface FailoverPolicy { id: string; name: string; requiresStandby: true; automatic: boolean; maxPromotions: number; metadataOnly: true; }
export interface FailoverPlan { id: string; name: string; groupId: string; failedNodeId: string; standbyNodeId: string; policyId?: string; status: 'planned' | 'active' | 'cancelled' | 'completed' | 'rejected'; reason?: string; metadataOnly: true; createdAt: string; updatedAt: string; }
export interface ClusterTopology { id: string; controllerNodeId?: string; nodeIds: string[]; assignments: NodeAssignment[]; redundancyGroupIds: string[]; metadataOnly: true; }
export interface ClusterHealth { status: 'healthy' | 'degraded' | 'failover_active' | 'offline'; nodeCount: number; onlineNodes: number; standbyNodes: number; degradedNodes: number; unavailableNodes: number; activeControllerId: string | null; failoverStatus: 'idle' | 'active'; messages: string[]; metadataOnly: true; }
export interface ClusterEvent { id: string; type: ClusterCommandType | 'VALIDATION_REJECTED'; message: string; timestamp: string; nodeId?: string; metadataOnly: true; }
export interface ClusterSnapshot { id: string; session: ClusterSession; timestamp: string; metadataOnly: true; }
export interface ClusterHistory { events: ClusterEvent[]; snapshots: ClusterSnapshot[]; metadataOnly: true; }
export interface ClusterSession { id: string; name: string; nodes: ClusterNode[]; topology: ClusterTopology; redundancyGroups: RedundancyGroup[]; failoverPolicies: FailoverPolicy[]; failoverPlans: FailoverPlan[]; queue: ClusterCommand[]; history: ClusterHistory; metadataOnly: true; }
export interface ClusterManifest { version: '1'; session: ClusterSession; supportedRoles: ClusterRole[]; supportedCommands: ClusterCommandType[]; networkingEnabled: false; cloudDependencyEnabled: false; metadataOnly: true; }
export type ClusterCommand = { type: ClusterCommandType; payload: Record<string, unknown>; id?: string; timestamp?: string };
const roles: ClusterRole[] = ['controller', 'render_node', 'media_node', 'audio_node', 'recording_node', 'streaming_node', 'replay_node', 'standby_node', 'observer_node'];
const commands: ClusterCommandType[] = ['REGISTER_NODE', 'REMOVE_NODE', 'ASSIGN_NODE_ROLE', 'MARK_NODE_ONLINE', 'MARK_NODE_OFFLINE', 'CREATE_REDUNDANCY_GROUP', 'ACTIVATE_FAILOVER', 'CANCEL_FAILOVER', 'PROMOTE_STANDBY', 'DEMOTE_NODE', 'CREATE_CLUSTER_SNAPSHOT', 'RESTORE_CLUSTER_SNAPSHOT'];
const now = () => new Date().toISOString();
const uid = (p: string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
function rejectUnsafe(payload: Record<string, unknown>) { for (const key of ['runtimeHandle', 'socket', 'ipAddress', 'credentials', 'connection', 'url']) if (key in payload) throw new Error(`Unsafe runtime field rejected: ${key}`); }
function validRole(role: unknown): role is ClusterRole { return typeof role === 'string' && roles.includes(role as ClusterRole); }
export function createClusterSession(name = 'Cluster Session'): ClusterSession { return { id: uid('cluster'), name, nodes: [], topology: { id: uid('topology'), nodeIds: [], assignments: [], redundancyGroupIds: [], metadataOnly: true }, redundancyGroups: [], failoverPolicies: [{ id: 'policy-manual-standby', name: 'Manual standby promotion', requiresStandby: true, automatic: false, maxPromotions: 1, metadataOnly: true }], failoverPlans: [], queue: [], history: { events: [], snapshots: [], metadataOnly: true }, metadataOnly: true }; }
export function createClusterManifest(session = createClusterSession()): ClusterManifest { return { version: '1', session, supportedRoles: roles, supportedCommands: commands, networkingEnabled: false, cloudDependencyEnabled: false, metadataOnly: true }; }
export class ClusterRuntime { constructor(public session: ClusterSession = createClusterSession()) {} private event(type: ClusterEvent['type'], message: string, nodeId?: string) { const e: ClusterEvent = { id: uid('event'), type, message, timestamp: now(), ...(nodeId ? { nodeId } : {}), metadataOnly: true }; this.session.history.events.push(e); return e; } health(): ClusterHealth { const n = this.session.nodes; const activePlan = this.session.failoverPlans.find((p) => p.status === 'active'); const controller = n.find((x) => x.roles.includes('controller') && x.state === 'online'); const degraded = n.filter((x) => x.state === 'degraded').length; const unavailable = n.filter((x) => x.state === 'unavailable' || x.state === 'offline').length; const online = n.filter((x) => x.state === 'online').length; const standby = n.filter((x) => x.state === 'standby' || x.roles.includes('standby_node')).length; const status = activePlan ? 'failover_active' : n.length === 0 || online === 0 ? 'offline' : degraded || unavailable ? 'degraded' : 'healthy'; return { status, nodeCount: n.length, onlineNodes: online, standbyNodes: standby, degradedNodes: degraded, unavailableNodes: unavailable, activeControllerId: controller?.id ?? null, failoverStatus: activePlan ? 'active' : 'idle', messages: ['Metadata-only cluster runtime', 'Networking disabled', 'Cloud APIs disabled'], metadataOnly: true }; }
  registerNode(input: Omit<ClusterNode, 'metadataOnly' | 'registeredAt' | 'updatedAt'>) { rejectUnsafe(input as Record<string, unknown>); if (this.session.nodes.some((n) => n.id === input.id)) throw new Error(`Duplicate node id: ${input.id}`); input.roles.forEach((r) => { if (!validRole(r)) throw new Error(`Invalid node role: ${r}`); }); const node: ClusterNode = { ...input, metadataOnly: true, registeredAt: now(), updatedAt: now() }; this.session.nodes.push(node); this.session.topology.nodeIds.push(node.id); this.event('REGISTER_NODE', `Registered ${node.name}`, node.id); return node; }
  removeNode(nodeId: string) { this.session.nodes = this.session.nodes.filter((n) => n.id !== nodeId); this.session.topology.nodeIds = this.session.topology.nodeIds.filter((id) => id !== nodeId); this.session.redundancyGroups = this.session.redundancyGroups.map((g) => ({ ...g, nodeIds: g.nodeIds.filter((id) => id !== nodeId), standbyNodeIds: g.standbyNodeIds.filter((id) => id !== nodeId) })); this.event('REMOVE_NODE', `Removed ${nodeId}`, nodeId); }
  assignRole(nodeId: string, role: ClusterRole) { if (!validRole(role)) throw new Error(`Invalid node role: ${role}`); const node = this.mustNode(nodeId); if (!node.roles.includes(role)) node.roles.push(role); node.updatedAt = now(); const a: NodeAssignment = { id: uid('assign'), nodeId, role, active: true, metadataOnly: true }; this.session.topology.assignments.push(a); this.event('ASSIGN_NODE_ROLE', `Assigned ${role}`, nodeId); return a; }
  mark(nodeId: string, state: ClusterNodeState) { const node = this.mustNode(nodeId); node.state = state; node.updatedAt = now(); this.event(state === 'online' ? 'MARK_NODE_ONLINE' : 'MARK_NODE_OFFLINE', `Marked ${state}`, nodeId); return node; }
  createRedundancyGroup(input: Omit<RedundancyGroup, 'metadataOnly'>) { if (input.nodeIds.length < 2) throw new Error('Redundancy groups require at least two nodes'); input.nodeIds.forEach((id) => this.mustNode(id)); const g = { ...input, metadataOnly: true as const }; this.session.redundancyGroups.push(g); this.session.topology.redundancyGroupIds.push(g.id); this.event('CREATE_REDUNDANCY_GROUP', `Created ${g.name}`); return g; }
  activateFailover(groupId: string, failedNodeId: string, standbyNodeId?: string) { const g = this.session.redundancyGroups.find((x) => x.id === groupId); if (!g) throw new Error(`Unknown redundancy group: ${groupId}`); const standby = standbyNodeId ?? g.standbyNodeIds[0]; if (!standby) throw new Error('Failover requires standby node'); const node = this.mustNode(standby); if (!(node.state === 'standby' || node.roles.includes('standby_node'))) throw new Error('Failover requires standby node'); const plan: FailoverPlan = { id: uid('failover'), name: `Failover ${failedNodeId} to ${standby}`, groupId, failedNodeId, standbyNodeId: standby, status: 'active', metadataOnly: true, createdAt: now(), updatedAt: now() }; this.session.failoverPlans.push(plan); this.event('ACTIVATE_FAILOVER', plan.name, failedNodeId); return plan; }
  cancelFailover(planId: string) { const p = this.mustPlan(planId); p.status = 'cancelled'; p.updatedAt = now(); this.event('CANCEL_FAILOVER', `Cancelled ${planId}`); return p; }
  promoteStandby(nodeId: string) { const node = this.mustNode(nodeId); if (!(node.state === 'standby' || node.roles.includes('standby_node'))) throw new Error('Only standby nodes can be promoted'); node.state = 'online'; this.assignRole(nodeId, 'controller'); this.event('PROMOTE_STANDBY', `Promoted ${nodeId}`, nodeId); return node; }
  demoteNode(nodeId: string) { const node = this.mustNode(nodeId); node.roles = node.roles.filter((r) => r !== 'controller'); node.state = 'standby'; this.event('DEMOTE_NODE', `Demoted ${nodeId}`, nodeId); return node; }
  snapshot() { const snap: ClusterSnapshot = { id: uid('cluster-snapshot'), session: JSON.parse(JSON.stringify(this.session)) as ClusterSession, timestamp: now(), metadataOnly: true }; this.session.history.snapshots.push(snap); this.event('CREATE_CLUSTER_SNAPSHOT', `Created ${snap.id}`); return snap; }
  restore(snapshot: ClusterSnapshot) { this.session = JSON.parse(JSON.stringify(snapshot.session)) as ClusterSession; this.event('RESTORE_CLUSTER_SNAPSHOT', `Restored ${snapshot.id}`); return this.session; }
  enqueue(command: ClusterCommand) { if (!commands.includes(command.type)) throw new Error(`Unsupported command: ${command.type}`); rejectUnsafe(command.payload); this.session.queue.push({ ...command, id: command.id ?? uid('cmd'), timestamp: command.timestamp ?? now() }); return this.session.queue.at(-1); }
  private mustNode(id: string) { const node = this.session.nodes.find((n) => n.id === id); if (!node) throw new Error(`Unknown node: ${id}`); return node; } private mustPlan(id: string) { const plan = this.session.failoverPlans.find((p) => p.id === id); if (!plan) throw new Error(`Unknown failover plan: ${id}`); return plan; }}
