import { ClusterRuntime, createClusterManifest } from './index.js';
const assert = { equal: (a: unknown, b: unknown) => { if (a !== b) throw new Error(`Expected ${String(a)} to equal ${String(b)}`); }, ok: (v: unknown) => { if (!v) throw new Error('Expected value to be truthy'); }, throws: (fn: () => unknown) => { let threw = false; try { fn(); } catch { threw = true; } if (!threw) throw new Error('Expected function to throw'); } };
const runtime = new ClusterRuntime();
const controller = runtime.registerNode({ id: 'controller-1', name: 'Controller', roles: ['controller'], state: 'online', capabilities: ['control'] });
const standby = runtime.registerNode({ id: 'standby-1', name: 'Standby', roles: ['standby_node'], state: 'standby', capabilities: ['standby'] });
runtime.registerNode({ id: 'render-1', name: 'Render', roles: ['render_node'], state: 'online', capabilities: ['render'] });
assert.equal(controller.id, 'controller-1');
assert.throws(() => runtime.registerNode({ id: 'controller-1', name: 'Dup', roles: ['observer_node'], state: 'offline', capabilities: ['observe'] }));
assert.throws(() => runtime.registerNode({ id: 'unsafe', name: 'Unsafe', roles: ['observer_node'], state: 'offline', capabilities: ['observe'], runtimeHandle: {} } as never));
runtime.assignRole('render-1', 'media_node');
assert.ok(runtime.session.nodes.find((n) => n.id === 'render-1')?.roles.includes('media_node'));
runtime.mark('render-1', 'offline'); assert.equal(runtime.session.nodes.find((n) => n.id === 'render-1')?.state, 'offline');
assert.throws(() => runtime.createRedundancyGroup({ id: 'bad', name: 'Bad', nodeIds: ['controller-1'], standbyNodeIds: [] }));
const group = runtime.createRedundancyGroup({ id: 'rg-1', name: 'Controller Pair', nodeIds: ['controller-1', 'standby-1'], activeNodeId: 'controller-1', standbyNodeIds: ['standby-1'] });
assert.equal(group.nodeIds.length, 2);
const plan = runtime.activateFailover('rg-1', 'controller-1'); assert.equal(plan.status, 'active');
runtime.promoteStandby(standby.id); assert.ok(runtime.session.nodes.find((n) => n.id === standby.id)?.roles.includes('controller'));
const snap = runtime.snapshot(); assert.ok(snap.session.nodes.length >= 2);
assert.ok(runtime.session.history.events.length >= 7);
runtime.removeNode('render-1'); assert.equal(runtime.session.nodes.some((n) => n.id === 'render-1'), false);
assert.equal(createClusterManifest(runtime.session).networkingEnabled, false);
assert.equal(runtime.health().metadataOnly, true);
console.log('runtime-cluster validation passed');
