import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
import type { MediaExecutionIntent } from '../index.js';
export type GpuBackendType = 'Mock'|'WebGPU'|'OpenGL'|'DirectX'|'Metal'|'Vulkan'|'Software'|'Null';
export type GpuRuntimeState = 'planned'|'initializing'|'ready'|'rendering'|'paused'|'recovering'|'degraded'|'failed'|'shutdown';
export type GpuCompositionStage = 'AcquireSurface'|'PrepareFrame'|'UploadResources'|'ComposeLayers'|'ApplyEffects'|'CompositeFrame'|'PresentFrame'|'Cleanup';
export type GpuFailureKind = 'backend unavailable'|'device unavailable'|'surface lost'|'resource exhausted'|'pipeline invalid'|'shader unavailable'|'driver unavailable'|'context lost';
export interface GpuAdapter { readonly id: string; readonly name: string; readonly backendType: GpuBackendType; readonly vendor?: string; readonly device?: string; readonly metadata: Record<string, unknown>; }
export interface GpuDevice { readonly id: string; readonly adapterId: string; readonly label: string; readonly backendType: GpuBackendType; readonly metadata: Record<string, unknown>; }
export interface GpuBackend { readonly id: string; readonly type: GpuBackendType; readonly label: string; readonly available: boolean; readonly reason?: string; readonly metadata: Record<string, unknown>; }
export interface GpuSurface { readonly id: string; readonly target: string; readonly width: number; readonly height: number; readonly format: string; readonly graphRevision: number; readonly metadata: Record<string, unknown>; }
export interface GpuTextureReference { readonly id: string; readonly kind: 'texture'; readonly label?: string; readonly width?: number; readonly height?: number; readonly format?: string; readonly metadata: Record<string, unknown>; }
export interface GpuBufferReference { readonly id: string; readonly kind: 'buffer'; readonly label?: string; readonly byteLength?: number; readonly usage?: string; readonly metadata: Record<string, unknown>; }
export type GpuResourceReference = GpuTextureReference | GpuBufferReference;
export interface GpuFrame { readonly frameId: number; readonly graphRevision: number; readonly executionBatchId: string; readonly mediaClockTimestamp: number; readonly compositionPlanId?: string; readonly resources: readonly GpuResourceReference[]; readonly metadata: Record<string, unknown>; }
export interface GpuPipeline { readonly id: string; readonly backendType: GpuBackendType; readonly stages: readonly GpuCompositionStage[]; readonly surfaceId?: string; readonly graphRevision: number; readonly metadata: Record<string, unknown>; }
export interface GpuRenderPass { readonly id: string; readonly pipelineId: string; readonly surfaceId: string; readonly frame: GpuFrame; readonly stages: readonly GpuCompositionStage[]; readonly metadata: Record<string, unknown>; }
export interface GpuCapabilities { readonly enabled: boolean; readonly mockMode: boolean; readonly backendTypes: readonly GpuBackendType[]; readonly maxTextureSize?: number; readonly supportsExternalTextures: boolean; readonly supportsPresentation: boolean; readonly supportsShaderCompilation: boolean; readonly metadataOnly: true; }
export interface GpuStatistics { readonly queueDepth: number; readonly pendingFrames: number; readonly resourcePressure: 'low'|'medium'|'high'; readonly frameLatencyMs: number; readonly presentationLatencyMs: number; readonly uploadLatencyMs: number; readonly pipelineBacklog: number; readonly renderedFrames: number; readonly droppedFrames: number; }
export interface GpuFailure { readonly kind: GpuFailureKind; readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly ubosFailure: UBOSFailure; }
export interface GpuHealth { readonly status: 'healthy'|'degraded'|'failed'|'shutdown'; readonly state: GpuRuntimeState; readonly backend: GpuBackendType; readonly queueDepth: number; readonly resourcePressure: GpuStatistics['resourcePressure']; readonly degraded: boolean; readonly latestFailure?: GpuFailure; readonly warnings: readonly string[]; }
export interface GpuSession { readonly id: string; readonly state: GpuRuntimeState; readonly backend: GpuBackend; readonly adapter: GpuAdapter; readonly device: GpuDevice; readonly pipeline: GpuPipeline; readonly surfaces: readonly GpuSurface[]; readonly frame?: GpuFrame; readonly statistics: GpuStatistics; readonly failures: readonly GpuFailure[]; readonly metadata: Record<string, unknown>; }
export interface GpuManifest { readonly id: string; readonly name: 'GPU Composition Runtime Foundation'; readonly version: '8.9'; readonly capabilities: GpuCapabilities; readonly diagnostics: { readonly gpuEnabled: boolean; readonly backend: GpuBackendType; readonly runtimeState: GpuRuntimeState; readonly pipeline: GpuPipeline; readonly surface?: GpuSurface; readonly frameId?: number; readonly queueDepth: number; readonly latency: Pick<GpuStatistics,'frameLatencyMs'|'presentationLatencyMs'|'uploadLatencyMs'>; readonly resourceUsage: { readonly resourceCount: number }; readonly pressure: GpuStatistics['resourcePressure']; readonly health: GpuHealth; readonly failure?: GpuFailure; readonly capabilities: GpuCapabilities; }; }
export interface GpuExecutionResult { readonly success: boolean; readonly state: GpuRuntimeState; readonly renderPass?: GpuRenderPass; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly manifest: GpuManifest; }
export interface GpuRuntime { readonly session: GpuSession; readonly manifest: GpuManifest; execute(intent: MediaExecutionIntent, frame?: GpuFrame): GpuExecutionResult; }
const iso = () => new Date().toISOString();
export const gpuCompositionStages: readonly GpuCompositionStage[] = ['AcquireSurface','PrepareFrame','UploadResources','ComposeLayers','ApplyEffects','CompositeFrame','PresentFrame','Cleanup'];
const enabled = (env: Record<string,string|undefined> = {}) => env.NEXT_PUBLIC_UBOS_GPU_RUNTIME === 'true' || env.UBOS_ENABLE_GPU_RUNTIME === 'true';
const stats = (s: Partial<GpuStatistics> = {}): GpuStatistics => ({ queueDepth:0,pendingFrames:0,resourcePressure:'low',frameLatencyMs:0,presentationLatencyMs:0,uploadLatencyMs:0,pipelineBacklog:0,renderedFrames:0,droppedFrames:0,...s });
export function createGpuSurface(input: Partial<GpuSurface> & { id: string }): GpuSurface { return { target:'Preview', width:1920, height:1080, format:'rgba8unorm-metadata', graphRevision:0, metadata:{}, ...input }; }
export function createGpuPipeline(input: Partial<GpuPipeline> & { id: string }): GpuPipeline { return { backendType:'Mock', stages:gpuCompositionStages, graphRevision:0, metadata:{ metadataOnly:true, storesShaders:false }, ...input }; }
export function createGpuRenderPass(input: Partial<GpuRenderPass> & { id: string; pipelineId: string; surfaceId: string; frame: GpuFrame }): GpuRenderPass { return { stages:gpuCompositionStages, metadata:{}, ...input }; }
export function createGpuSession(input: Partial<GpuSession> & { pipeline?: GpuPipeline; surfaces?: readonly GpuSurface[] } = {}, env: Record<string,string|undefined> = {}): GpuSession { const mock = !enabled(env); const backendType = mock ? 'Mock' : (input.backend?.type ?? input.pipeline?.backendType ?? 'Mock'); const pipeline = input.pipeline ?? createGpuPipeline({ id:'gpu-pipeline:default', backendType }); const surfaces = input.surfaces ?? [createGpuSurface({ id:'gpu-surface:preview', graphRevision:pipeline.graphRevision })]; const backend = input.backend ?? { id:`gpu-backend:${backendType}`, type:backendType, label:`${backendType} metadata backend`, available:true, metadata:{ mockMode:mock } }; const adapter = input.adapter ?? { id:`gpu-adapter:${backendType}`, name:`${backendType} metadata adapter`, backendType, metadata:{} }; const device = input.device ?? { id:`gpu-device:${backendType}`, adapterId:adapter.id, label:`${backendType} metadata device`, backendType, metadata:{ runtimeOnly:false } }; return { id: input.id ?? 'gpu-session:default', state: input.state ?? 'planned', backend, adapter, device, pipeline, surfaces, statistics: input.statistics ?? stats(), failures: input.failures ?? [], metadata: { runtimeOnlyObjectsInGraph:false, replayStoresHandles:false, mockMode:mock, ...(input.metadata ?? {}) }, ...(input.frame ? { frame: input.frame } : {}) }; }
export function validateGpuPipeline(p: GpuPipeline) { const errors: string[] = []; const warnings: string[] = []; const serialized = JSON.stringify(p); if (!p.id) errors.push('Missing pipeline id'); if (!p.stages.length) errors.push('Pipeline has no stages'); if (serialized.match(/GPUDevice|GPUTexture|WebGL|VkImage|MTLTexture|ID3D/) || serialized.match(/"runtimeOnly":true/) || serialized.match(/"serializable":false/)) errors.push('Pipeline contains forbidden GPU runtime object marker'); if (!p.stages.includes('PresentFrame')) warnings.push('Pipeline does not include PresentFrame'); return { valid: errors.length === 0, warnings, errors }; }
export function validateGpuCapabilities(c: GpuCapabilities) { const warnings = c.mockMode ? ['GPU runtime is in mock mode'] : []; const errors = c.metadataOnly !== true ? ['GPU capabilities must remain metadata-only'] : []; return { valid: errors.length === 0, warnings, errors }; }
export function mapGpuFailure(input: { kind: GpuFailureKind; message?: string; intentId?: string; frameId?: number; graphRevision?: number }): GpuFailure { const retryable = !['resource exhausted','pipeline invalid','driver unavailable'].includes(input.kind); const message = input.message ?? input.kind; return { kind:input.kind, code:`GPU_${input.kind.toUpperCase().replaceAll(' ','_')}`, message, retryable, occurredAt:iso(), ubosFailure:createFailureRecord({ category:'RENDERER_FAILURE', sourceLayer:'renderer', subsystem:'gpu-runtime', ...(input.intentId ? { intentId: input.intentId } : {}), ...(input.frameId !== undefined ? { frameId:String(input.frameId) } : {}), ...(input.graphRevision !== undefined ? { graphRevision: input.graphRevision } : {}), message, recoverable:retryable, metadata:{ graphMutationAllowed:false, runtimeOnly:true } }) }; }
export function summarizeGpuStatistics(s: GpuStatistics) { return `queue=${s.queueDepth} pending=${s.pendingFrames} pressure=${s.resourcePressure} frame=${s.frameLatencyMs}ms present=${s.presentationLatencyMs}ms upload=${s.uploadLatencyMs}ms backlog=${s.pipelineBacklog}`; }
export function summarizeGpuHealth(session: GpuSession): GpuHealth { const latestFailure = session.failures.at(-1); const degraded = session.state === 'degraded' || session.statistics.resourcePressure === 'high' || session.statistics.queueDepth > 2 || Boolean(latestFailure); const status = session.state === 'shutdown' ? 'shutdown' : session.state === 'failed' || (latestFailure && !latestFailure.retryable) ? 'failed' : degraded ? 'degraded' : 'healthy'; return { status, state:session.state, backend:session.backend.type, queueDepth:session.statistics.queueDepth, resourcePressure:session.statistics.resourcePressure, degraded, ...(latestFailure ? { latestFailure } : {}), warnings: degraded ? [summarizeGpuStatistics(session.statistics)] : [] }; }
export function createGpuManifest(session: GpuSession, env: Record<string,string|undefined> = {}): GpuManifest { const on = enabled(env); const capabilities: GpuCapabilities = { enabled:on, mockMode:!on || session.backend.type === 'Mock', backendTypes:['Mock','WebGPU','OpenGL','DirectX','Metal','Vulkan','Software','Null'], supportsExternalTextures:false, supportsPresentation:true, supportsShaderCompilation:false, metadataOnly:true }; const health = summarizeGpuHealth(session); return { id:'gpu-runtime-foundation', name:'GPU Composition Runtime Foundation', version:'8.9', capabilities, diagnostics:{ gpuEnabled:on, backend:session.backend.type, runtimeState:session.state, pipeline:session.pipeline, ...(session.surfaces[0] ? { surface:session.surfaces[0] } : {}), ...(session.frame ? { frameId:session.frame.frameId } : {}), queueDepth:session.statistics.queueDepth, latency:{ frameLatencyMs:session.statistics.frameLatencyMs, presentationLatencyMs:session.statistics.presentationLatencyMs, uploadLatencyMs:session.statistics.uploadLatencyMs }, resourceUsage:{ resourceCount:session.frame?.resources.length ?? 0 }, pressure:session.statistics.resourcePressure, health, ...(health.latestFailure ? { failure:health.latestFailure } : {}), capabilities } }; }
export function redactGpuDiagnostics(d: GpuManifest['diagnostics']): GpuManifest['diagnostics'] { return { ...d, pipeline:{ ...d.pipeline, metadata:{ redacted:true } }, ...(d.surface ? { surface:{ ...d.surface, metadata:{ redacted:true } } } : {}) }; }
export function createGpuRuntime(session = createGpuSession(), env: Record<string,string|undefined> = {}): GpuRuntime { return { session, manifest:createGpuManifest(session, env), execute(intent, frame) { const nextState: GpuRuntimeState = intent.type === 'STOP_GPU_RUNTIME' ? 'shutdown' : intent.type === 'FAIL_GPU_RUNTIME' ? 'failed' : intent.type === 'START_GPU_RUNTIME' ? 'rendering' : 'ready'; const next = { ...session, state: nextState, ...(frame ? { frame } : {}) }; return { success: nextState !== 'failed', state: nextState, warnings: [], errors: nextState === 'failed' ? ['GPU runtime failed by intent'] : [], manifest:createGpuManifest(next, env), ...(frame ? { renderPass:createGpuRenderPass({ id:`gpu-pass:${frame.frameId}`, pipelineId:session.pipeline.id, surfaceId:session.surfaces[0]?.id ?? 'none', frame }) } : {}) }; } }; }
export const createGpuContext = () => ({ runtimeOnly:true, serializable:false });
export const destroyGpuContext = () => ({ success:true });
export const allocateTexture = (ref: GpuTextureReference) => ({ ref, runtimeOnly:true, serializable:false });
export const releaseTexture = () => ({ success:true });
export const allocateBuffer = (ref: GpuBufferReference) => ({ ref, runtimeOnly:true, serializable:false });
export const releaseBuffer = () => ({ success:true });
export const compileShader = (id = 'shader:metadata') => ({ id, runtimeOnly:true, serializable:false, binary:undefined });
export const destroyShader = () => ({ success:true });
export const presentFrame = (frame: GpuFrame) => ({ success:true, frameId:frame.frameId });
export const cleanupGpu = (session: GpuSession): GpuSession => ({ ...session, state:'shutdown', statistics:stats() });
