import { BroadcastOrchestrator, type BroadcastOrchestratorSnapshot } from '../broadcast-orchestrator/index.js';
import { RuntimeSupervisor, type RuntimeSubsystem, type RuntimeSubsystemType, type RuntimeHealth } from '../production-runtime/index.js';

declare const process: { env: Record<string, string | undefined> } | undefined;
const now = () => new Date().toISOString();
const handlePattern = /handle|stream|process|socket|fd|file|texture|canvas|context|dom|mediaStream|peerConnection|audioNode|gpuDevice/i;
export const isHighAvailabilityEnabled = (env: Record<string,string|undefined> = typeof process !== 'undefined' ? process.env : {}) => env.UBOS_ENABLE_HIGH_AVAILABILITY === 'true' && env.NEXT_PUBLIC_UBOS_HIGH_AVAILABILITY === 'true';

export type NodeRole = 'primary'|'secondary'|'backup'|'standby';
export type StandbyMode = 'hot'|'warm'|'cold';
export type NodeState = 'joining'|'healthy'|'degraded'|'failed'|'recovering'|'promoted'|'demoted'|'offline';
export type LeaderState = 'leader'|'follower'|'candidate'|'unavailable';
export type HealthSignalType = 'heartbeat'|'cpu'|'memory'|'gpu'|'disk'|'network'|'encoder'|'streaming'|'recording'|'audio'|'browser_renderer'|'webrtc';
export type RecoveryAction = 'restart_subsystem'|'restart_encoder'|'restart_ffmpeg'|'restart_recording'|'restart_streaming'|'restart_renderer'|'restart_webrtc'|'restart_audio'|'restart_node'|'restart_cluster'|'promote_standby'|'migrate_pipeline'|'migrate_session'|'confirm_recovery'|'stabilize_health';
export interface ClusterNode { readonly id:string; readonly role:NodeRole; readonly standbyMode?:StandbyMode; readonly state:NodeState; readonly leaderState:LeaderState; readonly priority:number; readonly startedAt:string; readonly lastHeartbeatAt?:string; readonly activeSessions:readonly string[]; readonly subsystems:readonly RuntimeSubsystem[]; readonly metadata:Readonly<Record<string,string|number|boolean>>; readonly containsRuntimeHandles:false; }
export interface Cluster { readonly id:string; readonly nodes:readonly ClusterNode[]; readonly leaderNodeId?:string; readonly createdAt:string; readonly graphRevision?:number; readonly containsRuntimeHandles:false; }
export interface HealthSnapshot { readonly id:string; readonly nodeId:string; readonly timestamp:string; readonly signal:HealthSignalType; readonly status:RuntimeHealth; readonly value:number|string|boolean; readonly threshold?:number; readonly message?:string; readonly containsRuntimeHandles:false; }
export interface HealthStatistics { readonly nodeId:string; readonly healthy:number; readonly degraded:number; readonly failed:number; readonly unavailable:number; readonly lastUpdatedAt?:string; readonly score:number; readonly signals:Readonly<Record<HealthSignalType, RuntimeHealth>>; }
export interface HealthHistory { readonly snapshots:readonly HealthSnapshot[]; readonly containsRuntimeHandles:false; }
export interface Heartbeat { readonly id:string; readonly nodeId:string; readonly timestamp:string; readonly sequence:number; readonly state:NodeState; readonly leaderState:LeaderState; readonly health:RuntimeHealth; readonly containsRuntimeHandles:false; }
export interface RestartPolicy { readonly maxRestarts:number; readonly windowMs:number; readonly cooldownMs:number; readonly priority:readonly RecoveryAction[]; }
export interface RetryPolicy { readonly maxRetries:number; readonly baseDelayMs:number; readonly maxDelayMs:number; readonly backoff:'fixed'|'linear'|'exponential'; }
export interface CircuitBreaker { readonly id:string; readonly status:'closed'|'open'|'half_open'; readonly failureCount:number; readonly threshold:number; readonly openedAt?:string; readonly cooldownMs:number; }
export interface RecoveryStep { readonly id:string; readonly action:RecoveryAction; readonly targetId:string; readonly subsystemType?:RuntimeSubsystemType; readonly order:number; readonly dependsOn:readonly string[]; readonly priority:number; readonly safe:boolean; }
export interface RecoveryManifest { readonly id:string; readonly clusterId:string; readonly generatedAt:string; readonly steps:readonly RecoveryStep[]; readonly restartPolicy:RestartPolicy; readonly retryPolicy:RetryPolicy; readonly containsRuntimeHandles:false; }
export interface RecoveryDiagnostics { readonly manifestId:string; readonly progress:number; readonly currentStep?:string; readonly timeline:readonly HAEvent[]; readonly subsystemStatus:Readonly<Record<string, RuntimeHealth>>; readonly errors:readonly string[]; readonly containsRuntimeHandles:false; }
export interface HAEvent { readonly id:string; readonly timestamp:string; readonly type:'health'|'heartbeat'|'failover'|'recovery'|'cluster'|'election'; readonly message:string; readonly metadata:Readonly<Record<string,string|number|boolean>>; readonly containsRuntimeHandles:false; }
export interface HADashboard { readonly clusterHealth:RuntimeHealth; readonly leader?:string; readonly standby:readonly string[]; readonly heartbeat:readonly Heartbeat[]; readonly recoveryTimeline:readonly string[]; readonly subsystemStatus:Readonly<Record<string,RuntimeHealth>>; readonly failoverEvents:readonly HAEvent[]; }
export interface HASnapshot { readonly cluster:Cluster; readonly statistics:readonly HealthStatistics[]; readonly healthHistory:HealthHistory; readonly heartbeats:readonly Heartbeat[]; readonly events:readonly HAEvent[]; readonly dashboard:HADashboard; readonly orchestrator?:BroadcastOrchestratorSnapshot; readonly containsRuntimeHandles:false; }

const ev = (type:HAEvent['type'], message:string, metadata:Readonly<Record<string,string|number|boolean>>={}):HAEvent => Object.freeze({ id:`ha-${type}-${Date.now()}-${Math.random().toString(16).slice(2)}`, timestamp:now(), type, message, metadata, containsRuntimeHandles:false });
const sanitize = (m:Readonly<Record<string, unknown>>={}) => Object.freeze(Object.fromEntries(Object.entries(m).filter(([k,v]) => !handlePattern.test(k) && ['string','number','boolean'].includes(typeof v)))) as Readonly<Record<string,string|number|boolean>>;
export function createClusterNode(input: Partial<ClusterNode> & { id:string; role:NodeRole }):ClusterNode { return Object.freeze({ id:input.id, role:input.role, ...(input.standbyMode ? { standbyMode:input.standbyMode } : {}), state:input.state ?? 'joining', leaderState:input.leaderState ?? 'follower', priority:input.priority ?? (input.role==='primary'?100:input.role==='secondary'?75:50), startedAt:input.startedAt ?? now(), ...(input.lastHeartbeatAt ? { lastHeartbeatAt:input.lastHeartbeatAt } : {}), activeSessions:input.activeSessions ?? [], subsystems:input.subsystems ?? [], metadata:sanitize(input.metadata), containsRuntimeHandles:false }); }
export class ClusterManager { validate(cluster:Cluster){ const errors:string[]=[]; if (!cluster.nodes.length) errors.push('cluster requires at least one node'); if (cluster.nodes.filter(n=>n.leaderState==='leader').length > 1) errors.push('multiple leaders rejected'); if (cluster.nodes.some(n=>n.containsRuntimeHandles !== false || handlePattern.test(JSON.stringify(n.metadata)))) errors.push('cluster must be metadata-only'); if (cluster.leaderNodeId && !cluster.nodes.some(n=>n.id===cluster.leaderNodeId)) errors.push('leader must exist in cluster'); return errors; } create(id:string,nodes:readonly ClusterNode[], graphRevision?:number):Cluster { const leader = nodes.find(n=>n.leaderState==='leader'); const cluster = Object.freeze({ id,nodes, ...(leader?{leaderNodeId:leader.id}:{}), createdAt:now(), ...(graphRevision!==undefined?{graphRevision}:{}), containsRuntimeHandles:false as const }); const errors=this.validate(cluster); if(errors.length) throw new Error(errors.join('; ')); return cluster; } }
export class NodeManager { promote(n:ClusterNode):ClusterNode { return createClusterNode({...n, role:'primary', state:'promoted', leaderState:'leader'}); } demote(n:ClusterNode):ClusterNode { return createClusterNode({...n, role:n.role==='primary'?'secondary':n.role, state:'demoted', leaderState:'follower'}); } fail(n:ClusterNode):ClusterNode { return createClusterNode({...n,state:'failed',leaderState:'unavailable'}); } }
export class HealthMonitor { record(history:HealthHistory, snapshot:HealthSnapshot):HealthHistory { return Object.freeze({ snapshots:[...history.snapshots, Object.freeze({...snapshot, containsRuntimeHandles:false as const})], containsRuntimeHandles:false }); } statistics(node:ClusterNode, snapshots:readonly HealthSnapshot[]):HealthStatistics { const mine=snapshots.filter(s=>s.nodeId===node.id); const signals=Object.fromEntries(mine.map(s=>[s.signal,s.status])) as Record<HealthSignalType,RuntimeHealth>; const failed=mine.filter(s=>s.status==='failed').length, degraded=mine.filter(s=>s.status==='degraded').length, unavailable=mine.filter(s=>s.status==='unavailable').length, healthy=mine.filter(s=>s.status==='healthy').length; return Object.freeze({ nodeId:node.id, healthy, degraded, failed, unavailable, ...(mine.at(-1)?.timestamp ? { lastUpdatedAt: mine.at(-1)!.timestamp } : {}), score:Math.max(0,100-failed*40-degraded*15-unavailable*30), signals }); } }
export class HeartbeatManager { beat(node:ClusterNode, sequence:number, health:RuntimeHealth='healthy'):Heartbeat { return Object.freeze({ id:`heartbeat-${node.id}-${sequence}`, nodeId:node.id, timestamp:now(), sequence, state:node.state, leaderState:node.leaderState, health, containsRuntimeHandles:false }); } expired(heartbeat:Heartbeat|undefined, timeoutMs=30_000){ return !heartbeat || Date.now()-Date.parse(heartbeat.timestamp)>timeoutMs; } }
export class Watchdog { inspect(cluster:Cluster, heartbeats:readonly Heartbeat[], timeoutMs=30_000){ const hb=new HeartbeatManager(); return cluster.nodes.filter(n=>hb.expired(heartbeats.filter(h=>h.nodeId===n.id).at(-1), timeoutMs)).map(n=>ev('health',`Node ${n.id} heartbeat expired`,{nodeId:n.id})); } }
export class ElectionManager { elect(nodes:readonly ClusterNode[]):ClusterNode|undefined { return nodes.filter(n=>n.state!=='failed'&&n.state!=='offline').sort((a,b)=>b.priority-a.priority || a.startedAt.localeCompare(b.startedAt))[0]; } apply(cluster:Cluster):Cluster { const winner=this.elect(cluster.nodes); if(!winner) throw new Error('invalid failover: no electable node'); return new ClusterManager().create(cluster.id, cluster.nodes.map(n=>createClusterNode({...n, leaderState:n.id===winner.id?'leader':'follower', role:n.id===winner.id?'primary':(n.role==='primary'?'secondary':n.role), state:n.id===winner.id?'promoted':n.state})), cluster.graphRevision); } }
export class StandbyManager { candidates(cluster:Cluster, mode?:StandbyMode){ return cluster.nodes.filter(n=>['secondary','backup','standby'].includes(n.role) && (!mode || n.standbyMode===mode) && n.state!=='failed'); } best(cluster:Cluster){ return this.candidates(cluster).sort((a,b)=>b.priority-a.priority)[0]; } }
export class FailoverManager { constructor(private readonly election=new ElectionManager(), private readonly standby=new StandbyManager()){} failover(cluster:Cluster, failedNodeId:string){ if(!cluster.nodes.some(n=>n.id===failedNodeId)) throw new Error('invalid failover: missing failed node'); const failed=cluster.nodes.map(n=>n.id===failedNodeId?new NodeManager().fail(n):n); const promoted=this.standby.best({...cluster,nodes:failed}); if(!promoted) throw new Error('invalid failover: no standby available'); const elected=this.election.apply({...cluster,nodes:failed.map(n=>n.id===promoted.id?new NodeManager().promote(n):n)}); return { cluster:elected, events:[ev('failover',`Promoted ${promoted.id} after ${failedNodeId} failure`,{failedNodeId,promotedNodeId:promoted.id}), ev('recovery','Pipeline and session migration scheduled',{promotedNodeId:promoted.id})] as const }; } }
export class RecoveryPlanner { plan(cluster:Cluster, targetId:string, actions:readonly RecoveryAction[], restartPolicy:RestartPolicy=defaultRestartPolicy, retryPolicy:RetryPolicy=defaultRetryPolicy):RecoveryManifest { const steps=actions.map((action,i):RecoveryStep=>Object.freeze({ id:`recovery-${targetId}-${action}-${i}`, action, targetId, order:i, dependsOn:i?[`recovery-${targetId}-${actions[i-1]}-${i-1}`]:[], priority:actions.length-i, safe:!['restart_cluster','restart_node'].includes(action) || cluster.nodes.some(n=>n.id===targetId) })); const manifest=Object.freeze({ id:`recovery-manifest-${Date.now()}`, clusterId:cluster.id, generatedAt:now(), steps, restartPolicy, retryPolicy, containsRuntimeHandles:false as const }); const errors=this.validate(manifest); if(errors.length) throw new Error(errors.join('; ')); return manifest; } validate(m:RecoveryManifest){ const errors:string[]=[]; const ids=new Set(m.steps.map(s=>s.id)); for(const s of m.steps){ if(!s.safe) errors.push(`unsafe restart plan for ${s.targetId}`); if(s.dependsOn.some(d=>!ids.has(d))) errors.push(`missing recovery dependency ${s.id}`); if(s.dependsOn.includes(s.id)) errors.push('circular recovery rejected'); } return errors; } }
export class AutomaticRecovery { execute(manifest:RecoveryManifest):RecoveryDiagnostics { return Object.freeze({ manifestId:manifest.id, progress:manifest.steps.length?100:0, ...(manifest.steps.at(-1)?.id ? { currentStep: manifest.steps.at(-1)!.id } : {}), timeline:manifest.steps.map(s=>ev('recovery',`Recovery ${s.action} planned`,{targetId:s.targetId,order:s.order})), subsystemStatus:Object.fromEntries(manifest.steps.map(s=>[s.targetId,'healthy' as RuntimeHealth])), errors:[], containsRuntimeHandles:false }); } }
export const defaultRestartPolicy:RestartPolicy = Object.freeze({ maxRestarts:3, windowMs:300_000, cooldownMs:30_000, priority:['restart_encoder','restart_ffmpeg','restart_recording','restart_streaming','restart_renderer','restart_webrtc','restart_audio','restart_node','restart_cluster'] as const });
export const defaultRetryPolicy:RetryPolicy = Object.freeze({ maxRetries:3, baseDelayMs:500, maxDelayMs:30_000, backoff:'exponential' });
export function tripCircuitBreaker(b:CircuitBreaker):CircuitBreaker { const failureCount=b.failureCount+1; return Object.freeze({...b,failureCount,status:failureCount>=b.threshold?'open':b.status, ...(failureCount>=b.threshold?{openedAt:now()}: {})}); }
export class HighAvailabilityRuntime { readonly clusterManager=new ClusterManager(); readonly health=new HealthMonitor(); readonly heartbeat=new HeartbeatManager(); readonly watchdog=new Watchdog(); readonly failover=new FailoverManager(); readonly planner=new RecoveryPlanner(); readonly recovery=new AutomaticRecovery(); private cluster:Cluster; private history:HealthHistory=Object.freeze({snapshots:[],containsRuntimeHandles:false}); private heartbeats:Heartbeat[]=[]; private events:HAEvent[]=[]; constructor(nodes:readonly ClusterNode[], private readonly supervisor=new RuntimeSupervisor(), private readonly orchestrator=new BroadcastOrchestrator({UBOS_ENABLE_ORCHESTRATOR:'true',NEXT_PUBLIC_UBOS_ORCHESTRATOR:'true'}, supervisor), private readonly env:Record<string,string|undefined> = typeof process !== 'undefined' ? process.env : {}) { this.cluster=this.clusterManager.create('ha-cluster', nodes); }
  getCluster(){ return this.cluster; }
  recordHealth(nodeId:string, signal:HealthSignalType, status:RuntimeHealth, value:number|string|boolean, message?:string){ const snapshot:HealthSnapshot=Object.freeze({id:`health-${nodeId}-${signal}-${Date.now()}`,nodeId,timestamp:now(),signal,status,value,...(message?{message}:{}),containsRuntimeHandles:false}); this.history=this.health.record(this.history,snapshot); this.events.push(ev('health',message??`${signal} ${status}`,{nodeId,signal,status})); return snapshot; }
  beat(nodeId:string, health:RuntimeHealth='healthy'){ const node=this.cluster.nodes.find(n=>n.id===nodeId); if(!node) throw new Error(`unknown node ${nodeId}`); const hb=this.heartbeat.beat(node,this.heartbeats.filter(h=>h.nodeId===nodeId).length+1,health); this.heartbeats.push(hb); this.events.push(ev('heartbeat',`Heartbeat from ${nodeId}`,{nodeId,sequence:hb.sequence})); return hb; }
  recover(targetId:string, actions:readonly RecoveryAction[]){ const manifest=this.planner.plan(this.cluster,targetId,actions); const diagnostics=this.recovery.execute(manifest); this.events.push(...diagnostics.timeline); return {manifest,diagnostics}; }
  failoverPrimary(failedNodeId=this.cluster.leaderNodeId ?? this.cluster.nodes.find(n=>n.role==='primary')?.id ?? ''){ const result=this.failover.failover(this.cluster,failedNodeId); this.cluster=result.cluster; this.events.push(...result.events); return result; }
  snapshot():HASnapshot { const statistics=this.cluster.nodes.map(n=>this.health.statistics(n,this.history.snapshots)); const status:RuntimeHealth=statistics.some(s=>s.failed||s.unavailable)?'failed':statistics.some(s=>s.degraded)?'degraded':'healthy'; const subsystemStatus=Object.fromEntries(this.cluster.nodes.flatMap(n=>n.subsystems.map(s=>[s.id,s.health]))); const dashboard:HADashboard=Object.freeze({ clusterHealth:status, ...(this.cluster.leaderNodeId ? { leader:this.cluster.leaderNodeId } : {}), standby:this.cluster.nodes.filter(n=>n.role==='standby'||n.role==='backup'||n.role==='secondary').map(n=>n.id), heartbeat:this.heartbeats.slice(-20), recoveryTimeline:this.events.filter(e=>e.type==='recovery').map(e=>e.message), subsystemStatus, failoverEvents:this.events.filter(e=>e.type==='failover') }); return Object.freeze({ cluster:this.cluster, statistics, healthHistory:this.history, heartbeats:this.heartbeats, events:this.events, dashboard, orchestrator:this.orchestrator.snapshot(), containsRuntimeHandles:false }); }
  enabled(){ return isHighAvailabilityEnabled(this.env); }
}
