import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
import { createFFmpegRuntime, buildCommand, locateFFmpeg, type FFmpegRuntime } from '../ffmpeg-runtime/index.js';
import { createProductionRuntime, RuntimeSupervisor, type RuntimeSubsystem } from '../production-runtime/index.js';
import { sanitizeStreamingUrl, redactStreamingDiagnostics } from '../streaming/ffmpeg/index.js';
import type { StreamingHealth as BaseStreamingHealth } from '../streaming/index.js';
import { createClock } from '../sync/clock.js';
import { FrameScheduler } from '../sync/index.js';

declare const process: { env: Record<string,string|undefined> };
const now=()=>new Date().toISOString();
export type StreamingProtocol='rtmp'|'rtmps';
export type StreamingPlatform='youtube_live'|'facebook_live'|'twitch'|'kick'|'custom_rtmp';
export type StreamingLifecycle='created'|'validated'|'prepared'|'connecting'|'connected'|'publishing'|'reconnecting'|'paused'|'stopping'|'stopped'|'disconnected'|'cleaned_up'|'failed'|'queued';
export interface StreamingDestination { readonly id:string; readonly name:string; readonly platform:StreamingPlatform; readonly protocol:StreamingProtocol; readonly url:string; readonly sanitizedUrl:string; readonly enabled:boolean; readonly streamKeyRef?:string; readonly metadata:Readonly<Record<string,unknown>>; }
export interface StreamingStatistics { readonly bitrateKbps:number; readonly fps:number; readonly droppedFrames:number; readonly reconnectCount:number; readonly latencyMs:number; readonly durationMs:number; readonly bytesSent:number; readonly encoderStatus:'idle'|'starting'|'running'|'paused'|'stopped'|'failed'; }
export interface StreamingHealth { readonly connectionState:StreamingLifecycle; readonly status:BaseStreamingHealth; readonly bitrateKbps:number; readonly fps:number; readonly droppedFrames:number; readonly reconnectCount:number; readonly latencyMs:number; readonly durationMs:number; readonly bytesSent:number; readonly encoderStatus:StreamingStatistics['encoderStatus']; readonly warnings:readonly string[]; }
export interface StreamingFailure { readonly kind:'validation'|'auth'|'transport'|'encoder'|'ffmpeg'|'reconnect_exhausted'|'backpressure'|'security'; readonly message:string; readonly retryable:boolean; readonly occurredAt:string; readonly ubosFailure:UBOSFailure; }
export interface StreamingReplayRecord { readonly type:'command'|'lifecycle'|'state'|'health'|'failure'; readonly timestamp:string; readonly jobId:string; readonly data:Readonly<Record<string,string|number|boolean>>; }
export interface StreamingJob { readonly id:string; readonly graphRevision:number; readonly lifecycle:StreamingLifecycle; readonly destination:StreamingDestination; readonly createdAt:string; readonly startedAt?:string; readonly stoppedAt?:string; readonly statistics:StreamingStatistics; readonly health:StreamingHealth; readonly reconnectPolicy:{ readonly immediateRetry:boolean; readonly baseDelayMs:number; readonly maxDelayMs:number; readonly maxRetries:number; readonly circuitBreakerThreshold:number; readonly operatorNotification:boolean; }; readonly nextReconnectAt?:string; readonly latestFailure?:StreamingFailure; readonly replay:readonly StreamingReplayRecord[]; readonly runtime:'ffmpeg'|'mock'; readonly protocol:StreamingProtocol; readonly containsRuntimeHandles:false; readonly containsMediaPayloads:false; }
export interface StreamingManifest { readonly id:string; readonly jobId:string; readonly generatedAt:string; readonly destination:Pick<StreamingDestination,'id'|'name'|'platform'|'protocol'|'sanitizedUrl'|'enabled'>; readonly lifecycle:StreamingLifecycle; readonly statistics:StreamingStatistics; readonly health:StreamingHealth; readonly replaySafe:true; readonly containsMediaPayloads:false; readonly containsEncodedPackets:false; readonly containsProcessHandles:false; readonly containsStreamKeys:false; }
export interface StreamingPipelineOptions { readonly graphRevision?:number; readonly destination:{ readonly id?:string; readonly name:string; readonly platform:StreamingPlatform; readonly url:string; readonly streamKeyRef?:string; readonly enabled?:boolean; readonly metadata?:Record<string,unknown> }; readonly scheduleAt?:string; readonly env?:Record<string,string|undefined>; readonly maxConcurrentPublishers?:number; readonly reconnectPolicy?:Partial<StreamingJob['reconnectPolicy']>; }
const defaults={immediateRetry:true,baseDelayMs:500,maxDelayMs:30_000,maxRetries:3,circuitBreakerThreshold:3,operatorNotification:true};
const emptyStats=():StreamingStatistics=>({bitrateKbps:0,fps:0,droppedFrames:0,reconnectCount:0,latencyMs:0,durationMs:0,bytesSent:0,encoderStatus:'idle'});
const rec=(type:StreamingReplayRecord['type'],jobId:string,data:Record<string,string|number|boolean>):StreamingReplayRecord=>Object.freeze({type,timestamp:now(),jobId,data});
export function isRealStreamingEnabled(env:Record<string,string|undefined>=process.env){ return env.UBOS_ENABLE_REAL_STREAMING==='true'&&env.NEXT_PUBLIC_UBOS_REAL_STREAMING==='true'; }
export function validateStreamingDestination(input:StreamingPipelineOptions['destination']):StreamingDestination{ const sanitizedUrl=sanitizeStreamingUrl(input.url); const protocol=sanitizedUrl.startsWith('rtmps://')?'rtmps':sanitizedUrl.startsWith('rtmp://')?'rtmp':undefined; if(!protocol) throw new Error('Only RTMP and RTMPS destinations are supported'); if(/[\0\n\r`$;&|<>]/.test(input.url)||input.url.includes('/../')||input.url.includes('..\\')) throw new Error('Malformed or unsafe stream URL rejected'); if(sanitizedUrl.includes('..')) throw new Error('Path injection rejected'); return Object.freeze({id:input.id??`stream-destination-${Date.now()}`,name:input.name,platform:input.platform,protocol,url:sanitizedUrl,sanitizedUrl,enabled:input.enabled??true,...(input.streamKeyRef?{streamKeyRef:input.streamKeyRef}:{}),metadata:Object.freeze({...(input.metadata??{}),redacted:true})}); }
function failure(kind:StreamingFailure['kind'],message:string,retryable=true):StreamingFailure{ return {kind,message:redactStreamingDiagnostics(message),retryable,occurredAt:now(),ubosFailure:createFailureRecord({category:'STREAMING_FAILURE',sourceLayer:'execution',subsystem:'streaming-runtime',message:redactStreamingDiagnostics(message),recoverable:retryable,metadata:{runtimeSupervised:true,graphMutationAllowed:false}})}; }
function health(lifecycle:StreamingLifecycle, s=emptyStats(), warnings:readonly string[]=[]):StreamingHealth{ const status:BaseStreamingHealth = lifecycle==='failed'?'critical': lifecycle==='reconnecting'||warnings.length?'degraded': lifecycle==='publishing'?'healthy':'warning'; return {connectionState:lifecycle,status,bitrateKbps:s.bitrateKbps,fps:s.fps,droppedFrames:s.droppedFrames,reconnectCount:s.reconnectCount,latencyMs:s.latencyMs,durationMs:s.durationMs,bytesSent:s.bytesSent,encoderStatus:s.encoderStatus,warnings}; }
export class StreamingValidator { validateDestination=validateStreamingDestination; validateJob(job:StreamingJob){ const errors:string[]=[]; if(job.containsRuntimeHandles!==false) errors.push('Runtime handles are forbidden'); if(JSON.stringify(job).includes('SUPER_STREAM_KEY')) errors.push('Stream key leaked'); return {valid:errors.length===0,errors,warnings:job.health.warnings}; } }
export class StreamingScheduler { queue:StreamingJob[]=[]; active=new Set<string>(); constructor(private readonly maxConcurrent=2){} enqueue(j:StreamingJob){this.queue.push(j);return this.queue.length;} canStart(){return this.active.size<this.maxConcurrent;} markStarted(id:string){this.active.add(id);} markStopped(id:string){this.active.delete(id);return this.queue.shift();} diagnostics(){return {queueDepth:this.queue.length,activePublishers:this.active.size,maxConcurrentPublishers:this.maxConcurrent};} }
export class StreamingSessionManager { private jobs=new Map<string,StreamingJob>(); upsert(j:StreamingJob){this.jobs.set(j.id,j);return j;} get(id:string){return this.jobs.get(id);} list(){return [...this.jobs.values()];} delete(id:string){return this.jobs.delete(id);} cleanup(){this.jobs.clear();} }
export class StreamingRecovery { scheduleReconnect(job:StreamingJob){ const attempt=job.statistics.reconnectCount+1; if(attempt>job.reconnectPolicy.maxRetries) return {...job,lifecycle:'failed' as const,latestFailure:failure('reconnect_exhausted','Maximum stream reconnect attempts exhausted',false),health:health('failed',job.statistics),replay:[...job.replay,rec('failure',job.id,{reconnectExhausted:true})]}; const delay=attempt===1&&job.reconnectPolicy.immediateRetry?0:Math.min(job.reconnectPolicy.maxDelayMs,job.reconnectPolicy.baseDelayMs*2**(attempt-1)); const stats={...job.statistics,reconnectCount:attempt,encoderStatus:'starting' as const}; return {...job,lifecycle:'reconnecting' as const,statistics:stats,health:health('reconnecting',stats,[`Reconnect scheduled in ${delay}ms`]),nextReconnectAt:new Date(Date.now()+delay).toISOString(),replay:[...job.replay,rec('lifecycle',job.id,{reconnectAttempt:attempt,delayMs:delay})]}; } }
export function createStreamingRuntimeManifest(job:StreamingJob):StreamingManifest{ return Object.freeze({id:`streaming-manifest-${job.id}`,jobId:job.id,generatedAt:now(),destination:{id:job.destination.id,name:job.destination.name,platform:job.destination.platform,protocol:job.destination.protocol,sanitizedUrl:job.destination.sanitizedUrl,enabled:job.destination.enabled},lifecycle:job.lifecycle,statistics:job.statistics,health:job.health,replaySafe:true,containsMediaPayloads:false,containsEncodedPackets:false,containsProcessHandles:false,containsStreamKeys:false}); }
export class StreamingPipeline { readonly sessions=new StreamingSessionManager(); readonly scheduler:StreamingScheduler; readonly recovery=new StreamingRecovery(); readonly validator=new StreamingValidator(); readonly supervisor:RuntimeSupervisor; readonly ffmpeg:FFmpegRuntime; constructor(private readonly env:Record<string,string|undefined>=process.env, maxConcurrent=2){ this.scheduler=new StreamingScheduler(maxConcurrent); this.supervisor=new RuntimeSupervisor(createProductionRuntime({id:'streaming-production-runtime'})); this.ffmpeg=createFFmpegRuntime({env:{} as Record<string,string>,featureFlags:{UBOS_ENABLE_REAL_FFMPEG:isRealStreamingEnabled(env),NEXT_PUBLIC_UBOS_REAL_FFMPEG:isRealStreamingEnabled(env)}}); this.supervisor.register(this.subsystem('idle')); }
  private subsystem(state:RuntimeSubsystem['state'],job?:StreamingJob):RuntimeSubsystem{ return {id:'streaming-runtime',type:'streaming',label:'Streaming Runtime',required:false,state,health:job?.latestFailure?'failed':state==='running'?'healthy':'degraded',degradedModes:job?.latestFailure?['output_disabled_mode']:[],diagnostics:job?{jobId:job.id,destination:job.destination.name,status:job.lifecycle,bitrateKbps:job.statistics.bitrateKbps,fps:job.statistics.fps,latencyMs:job.statistics.latencyMs,reconnects:job.statistics.reconnectCount,health:job.health.status,runtime:job.runtime,protocol:job.protocol,queueDepth:this.scheduler.diagnostics().queueDepth}: {featureFlag:isRealStreamingEnabled(this.env)}}; }
  create(options:StreamingPipelineOptions){ const destination=this.validator.validateDestination(options.destination); const id=`streaming-job-${Date.now()}`; const policy={...defaults,...(options.reconnectPolicy??{})}; const stats=emptyStats(); const job=Object.freeze({id,graphRevision:options.graphRevision??0,lifecycle:'created',destination,createdAt:now(),statistics:stats,health:health('created',stats),reconnectPolicy:policy,replay:[rec('command',id,{command:'create',graphRevision:options.graphRevision??0})],runtime:isRealStreamingEnabled(options.env??this.env)?'ffmpeg':'mock',protocol:destination.protocol,containsRuntimeHandles:false,containsMediaPayloads:false} satisfies StreamingJob); return this.sessions.upsert(job); }
  validate(id:string){ const j=this.must(id); return this.patch(j,{lifecycle:'validated',health:health('validated',j.statistics),replay:[...j.replay,rec('lifecycle',id,{validated:true})]}); }
  prepare(id:string){ const j=this.must(id); return this.patch(j,{lifecycle:'prepared',health:health('prepared',j.statistics),replay:[...j.replay,rec('lifecycle',id,{prepared:true})]}); }
  connect(id:string){ const j=this.must(id); return this.patch(j,{lifecycle:'connected',health:health('connected',j.statistics),replay:[...j.replay,rec('lifecycle',id,{connected:true})]}); }
  async startPublishing(id:string){ let j=this.must(id); if(!this.scheduler.canStart()){this.scheduler.enqueue(j); return this.patch(j,{lifecycle:'queued',replay:[...j.replay,rec('command',id,{queued:true})]});} this.scheduler.markStarted(id); const startedAt=now(); const stats={...j.statistics,bitrateKbps:4500,fps:30,encoderStatus:'running' as const,bytesSent:1024}; if(isRealStreamingEnabled(this.env)){ const args=['-hide_banner','-nostdin','-re','-f','lavfi','-i','testsrc2=size=1280x720:rate=30','-f','lavfi','-i','sine=frequency=1000:sample_rate=48000','-c:v','libx264','-c:a','aac','-f','flv',j.destination.sanitizedUrl]; await this.ffmpeg.manager.start(buildCommand({executable:locateFFmpeg(this.env),args,outputs:[j.destination.sanitizedUrl],metadata:{streamingJobId:j.id}})); }
    j=this.patch(j,{lifecycle:'publishing',startedAt,statistics:stats,health:health('publishing',stats),replay:[...j.replay,rec('lifecycle',id,{publishing:true})]}); this.supervisor.register(this.subsystem('running',j)); return j; }
  reconnect(id:string){ const j=this.recovery.scheduleReconnect(this.must(id)); if(j.lifecycle==='failed') this.supervisor.failSubsystem('streaming-runtime',j.latestFailure?.message??'stream reconnect exhausted'); return this.patch(this.must(id),j); }
  pause(id:string){const j=this.must(id); const s={...j.statistics,encoderStatus:'paused' as const}; return this.patch(j,{lifecycle:'paused',statistics:s,health:health('paused',s),replay:[...j.replay,rec('state',id,{paused:true})]});}
  resume(id:string){const j=this.must(id); const s={...j.statistics,encoderStatus:'running' as const}; return this.patch(j,{lifecycle:'publishing',statistics:s,health:health('publishing',s),replay:[...j.replay,rec('state',id,{resumed:true})]});}
  async stop(id:string){ let j=this.must(id); await this.ffmpeg.manager.stop(); this.scheduler.markStopped(id); const s={...j.statistics,encoderStatus:'stopped' as const,durationMs:j.startedAt?Date.now()-Date.parse(j.startedAt):j.statistics.durationMs}; j=this.patch(j,{lifecycle:'stopped',stoppedAt:now(),statistics:s,health:health('stopped',s),replay:[...j.replay,rec('lifecycle',id,{stopped:true})]}); this.supervisor.register(this.subsystem('stopped',j)); return j; }
  disconnect(id:string){const j=this.must(id); return this.patch(j,{lifecycle:'disconnected',health:health('disconnected',j.statistics),replay:[...j.replay,rec('lifecycle',id,{disconnected:true})]});}
  cleanup(id:string){const j=this.patch(this.must(id),{lifecycle:'cleaned_up',replay:[...this.must(id).replay,rec('lifecycle',id,{cleanup:true})]}); this.sessions.delete(id); return j;}
  fail(id:string,kind:StreamingFailure['kind'],message:string,retryable=true){ const j=this.must(id); const f=failure(kind,message,retryable); this.supervisor.failSubsystem('streaming-runtime',f.message); return this.patch(j,{lifecycle:retryable?'reconnecting':'failed',latestFailure:f,health:health(retryable?'reconnecting':'failed',j.statistics,[f.message]),replay:[...j.replay,rec('failure',id,{failed:true,retryable})]}); }
  manifest(id:string){return createStreamingRuntimeManifest(this.must(id));} diagnostics(id:string){const j=this.must(id); return {destination:j.destination.name,status:j.lifecycle,bitrate:j.statistics.bitrateKbps,fps:j.statistics.fps,latency:j.statistics.latencyMs,reconnects:j.statistics.reconnectCount,health:j.health.status,runtime:j.runtime,protocol:j.protocol,supervisor:this.supervisor.getRuntime().state,backpressure:this.scheduler.diagnostics()};}
  private patch(j:StreamingJob,p:Partial<StreamingJob>){ const n=Object.freeze({...j,...p,containsRuntimeHandles:false,containsMediaPayloads:false}) as StreamingJob; this.sessions.upsert(n); return n;} private must(id:string){ const j=this.sessions.get(id); if(!j) throw new Error(`Streaming job ${id} not found`); return j; }
}
export { StreamingPipeline as StreamingJobRuntime };

// UBOS 2.0 Phase 2.14 Streaming Pipeline Foundation
export type StreamingEndpointKind = 'rtmp' | 'rtmps' | 'custom';
export type StreamingProvider = 'youtube' | 'twitch' | 'facebook' | 'linkedin' | 'tiktok' | 'custom';
export type StreamingSessionLifecycle = 'idle' | 'preparing' | 'connecting' | 'streaming' | 'reconnecting' | 'stopped' | 'failed';
export type StreamingRuntimeEventType = 'streaming_session_created' | 'streaming_preparing' | 'streaming_connecting' | 'streaming_started' | 'streaming_video_published' | 'streaming_audio_published' | 'streaming_reconnecting' | 'streaming_stopped' | 'streaming_failed';
export interface StreamingProviderModel { readonly id: StreamingProvider; readonly label: string; readonly defaultProtocol: Exclude<StreamingEndpointKind, 'custom'>; readonly supportsAuthFlow: false; readonly supportsMultistreaming: false; readonly supportsAdaptiveBitrate: false; }
export interface StreamingDestinationModel { readonly id: string; readonly kind: StreamingEndpointKind; readonly provider: StreamingProvider; readonly label: string; readonly endpointUrl: string; readonly sanitizedUrl: string; readonly streamKeyRef?: string; readonly metadata: Readonly<Record<string, unknown>>; readonly containsStreamKeys: false; readonly containsAuthTokens: false; }
export interface StreamingSessionMetadata { readonly bitrateKbps: number; readonly droppedFrames: number; readonly reconnectCount: number; readonly durationMs: number; readonly latencyEstimateMs: number; readonly videoFramesPublished: number; readonly audioSamplesPublished: number; }
export interface StreamingSourceBinding { readonly programOutputId: string; readonly audioMixerId: string; readonly videoSurfaceId?: string; readonly audioBusId?: string; readonly containsRuntimeHandles: false; }
export interface StreamingSession { readonly id: string; readonly state: StreamingSessionLifecycle; readonly destination: StreamingDestinationModel; readonly source: StreamingSourceBinding; readonly createdAt: string; readonly startedAt?: string; readonly stoppedAt?: string; readonly clock: ReturnType<import('../sync/clock.js').MediaClock['getState']>; readonly scheduler: ReturnType<import('../sync/index.js').FrameScheduler['getStats']>; readonly metadata: StreamingSessionMetadata; readonly events: readonly StreamingRuntimeEvent[]; readonly backend: StreamingBackendDescriptor; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; readonly containsEncodedPackets: false; }
export interface StreamingRuntimeEvent { readonly id: string; readonly type: StreamingRuntimeEventType; readonly timestamp: string; readonly sessionId: string; readonly state: StreamingSessionLifecycle; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface StreamingBackendDescriptor { readonly id: string; readonly name: string; readonly mode: 'metadata_only' | 'future_transport'; readonly protocols: readonly StreamingEndpointKind[]; readonly transmitsNetworkPackets: false; readonly supportsSrt: false; readonly supportsRist: false; readonly supportsAdaptiveBitrate: false; readonly supportsAuthenticationFlow: false; readonly supportsMultistreaming: false; }
export interface StreamingPipelineSnapshot { readonly id: string; readonly state: StreamingSessionLifecycle; readonly sessions: readonly StreamingSession[]; readonly activeSessionId?: string; readonly events: readonly StreamingRuntimeEvent[]; readonly providers: readonly StreamingProviderModel[]; readonly backend: StreamingBackendDescriptor; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; readonly containsEncodedPackets: false; }
export interface StreamingPipelineV2 { readonly id: string; createSession(input: CreateStreamingSessionInput): StreamingSession; prepare(sessionId: string): StreamingSession; connect(sessionId: string): StreamingSession; start(sessionId: string): StreamingSession; publishProgramFrame(sessionId: string, tick?: import('../sync/index.js').FrameTickEvent): StreamingSession; publishAudioFrame(sessionId: string, samples?: number, tick?: import('../sync/index.js').FrameTickEvent): StreamingSession; reconnect(sessionId: string, reason?: string): StreamingSession; stop(sessionId: string): StreamingSession; fail(sessionId: string, message: string): StreamingSession; getSession(sessionId: string): StreamingSession | undefined; getSnapshot(): StreamingPipelineSnapshot; getEvents(): readonly StreamingRuntimeEvent[]; onRuntimeEvent(callback: (event: StreamingRuntimeEvent) => void): () => void; }
export interface CreateStreamingSessionInput { readonly id?: string; readonly destination: Omit<StreamingDestinationModel, 'id' | 'sanitizedUrl' | 'containsStreamKeys' | 'containsAuthTokens' | 'metadata'> & { readonly id?: string; readonly metadata?: Readonly<Record<string, unknown>> }; readonly programOutput: import('../output-pipeline.js').ProgramOutput; readonly audioMixer: import('../media-runtime/audio-mixer.js').AudioMixer; readonly mediaClock?: import('../sync/clock.js').MediaClock; readonly frameScheduler?: import('../sync/index.js').FrameScheduler; readonly targetBitrateKbps?: number; readonly latencyEstimateMs?: number; readonly metadata?: Readonly<Record<string, unknown>>; }

export const streamingProviders: readonly StreamingProviderModel[] = Object.freeze([
  { id: 'youtube', label: 'YouTube Live', defaultProtocol: 'rtmps', supportsAuthFlow: false, supportsMultistreaming: false, supportsAdaptiveBitrate: false },
  { id: 'twitch', label: 'Twitch', defaultProtocol: 'rtmp', supportsAuthFlow: false, supportsMultistreaming: false, supportsAdaptiveBitrate: false },
  { id: 'facebook', label: 'Facebook Live', defaultProtocol: 'rtmps', supportsAuthFlow: false, supportsMultistreaming: false, supportsAdaptiveBitrate: false },
  { id: 'linkedin', label: 'LinkedIn Live', defaultProtocol: 'rtmps', supportsAuthFlow: false, supportsMultistreaming: false, supportsAdaptiveBitrate: false },
  { id: 'tiktok', label: 'TikTok Live', defaultProtocol: 'rtmps', supportsAuthFlow: false, supportsMultistreaming: false, supportsAdaptiveBitrate: false },
  { id: 'custom', label: 'Custom endpoint', defaultProtocol: 'rtmp', supportsAuthFlow: false, supportsMultistreaming: false, supportsAdaptiveBitrate: false },
]);
const streamingBackend: StreamingBackendDescriptor = Object.freeze({ id: 'streaming-backend:metadata-only', name: 'Metadata-only streaming backend', mode: 'metadata_only', protocols: ['rtmp', 'rtmps', 'custom'] as const, transmitsNetworkPackets: false, supportsSrt: false, supportsRist: false, supportsAdaptiveBitrate: false, supportsAuthenticationFlow: false, supportsMultistreaming: false });
const emptyStreamingMetadata = (bitrateKbps = 4500, latencyEstimateMs = 0): StreamingSessionMetadata => Object.freeze({ bitrateKbps, droppedFrames: 0, reconnectCount: 0, durationMs: 0, latencyEstimateMs, videoFramesPublished: 0, audioSamplesPublished: 0 });
const seid = (type: string) => `${type}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
function createStreamingDestination(input: CreateStreamingSessionInput['destination']): StreamingDestinationModel { const sanitizedUrl = input.kind === 'custom' ? input.endpointUrl.replace(/[\0\n\r`$;&|<>]/g, '') : sanitizeStreamingUrl(input.endpointUrl); const kind = input.kind === 'custom' ? 'custom' : sanitizedUrl.startsWith('rtmps://') ? 'rtmps' : sanitizedUrl.startsWith('rtmp://') ? 'rtmp' : input.kind; if (!['rtmp','rtmps','custom'].includes(kind)) throw new Error(`Unsupported streaming destination ${kind}`); if (kind !== 'custom' && !sanitizedUrl.startsWith(`${kind}://`)) throw new Error(`Destination URL does not match ${kind.toUpperCase()} protocol`); return Object.freeze({ id: input.id ?? `streaming-destination:${Date.now()}`, kind, provider: input.provider, label: input.label, endpointUrl: sanitizedUrl, sanitizedUrl, ...(input.streamKeyRef ? { streamKeyRef: input.streamKeyRef } : {}), metadata: Object.freeze({ ...input.metadata, redacted: true }), containsStreamKeys: false, containsAuthTokens: false }); }

export class MetadataStreamingPipeline implements StreamingPipelineV2 {
  private sessions = new Map<string, StreamingSession>(); private events: StreamingRuntimeEvent[] = []; private listeners = new Set<(event: StreamingRuntimeEvent) => void>(); private state: StreamingSessionLifecycle = 'idle'; private activeSessionId: string | undefined;
  constructor(readonly id = 'streaming-pipeline:program', private readonly backend: StreamingBackendDescriptor = streamingBackend) {}
  createSession(input: CreateStreamingSessionInput): StreamingSession { const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const scheduler = input.frameScheduler ?? new FrameScheduler(clock); const destination = createStreamingDestination(input.destination); const outputState = input.programOutput.getRuntimeState(); const sessionId = input.id ?? `streaming-session:${Date.now()}`; const session: StreamingSession = Object.freeze({ id: sessionId, state: 'idle', destination, source: Object.freeze({ programOutputId: input.programOutput.id, audioMixerId: input.audioMixer.id, videoSurfaceId: outputState.videoSurface.id, audioBusId: outputState.audioBus.mixerBusId, containsRuntimeHandles: false }), createdAt: now(), clock: clock.getState(), scheduler: scheduler.getStats(), metadata: emptyStreamingMetadata(input.targetBitrateKbps, input.latencyEstimateMs), events: [], backend: this.backend, containsRuntimeHandles: false, containsMediaPayloads: false, containsEncodedPackets: false }); this.sessions.set(sessionId, this.withEvent(session, 'streaming_session_created', 'Streaming session created', input.metadata)); return this.must(sessionId); }
  prepare(id: string) { this.state = 'preparing'; return this.patch(this.must(id), { state: 'preparing' }, 'streaming_preparing', 'Streaming pipeline preparing'); }
  connect(id: string) { this.state = 'connecting'; return this.patch(this.must(id), { state: 'connecting' }, 'streaming_connecting', 'Streaming pipeline connecting'); }
  start(id: string) { this.state = 'streaming'; this.activeSessionId = id; const s = this.must(id); return this.patch(s, { state: 'streaming', startedAt: s.startedAt ?? now() }, 'streaming_started', 'Streaming synchronized Program video and AudioMixer output'); }
  publishProgramFrame(id: string, tick?: import('../sync/index.js').FrameTickEvent) { const s = this.must(id); if (s.state !== 'streaming') return s; const durationMs = tick?.presentationTimestamp ?? tick?.timestamp ?? s.metadata.durationMs; const dropped = tick?.diagnostics?.droppedFrames ?? 0; return this.patch(s, { metadata: Object.freeze({ ...s.metadata, durationMs: Math.max(s.metadata.durationMs, durationMs), droppedFrames: s.metadata.droppedFrames + dropped, videoFramesPublished: s.metadata.videoFramesPublished + 1 }) }, 'streaming_video_published', 'Program video frame published to streaming pipeline', { frameId: tick?.frameId, droppedFrames: dropped }); }
  publishAudioFrame(id: string, samples = 480, tick?: import('../sync/index.js').FrameTickEvent) { const s = this.must(id); if (s.state !== 'streaming') return s; const durationMs = tick?.presentationTimestamp ?? tick?.timestamp ?? s.metadata.durationMs; return this.patch(s, { metadata: Object.freeze({ ...s.metadata, durationMs: Math.max(s.metadata.durationMs, durationMs), audioSamplesPublished: s.metadata.audioSamplesPublished + samples }) }, 'streaming_audio_published', 'Audio mixer frame published to streaming pipeline', { samples, frameId: tick?.frameId }); }
  reconnect(id: string, reason = 'metadata-only reconnect requested') { this.state = 'reconnecting'; const s = this.must(id); return this.patch(s, { state: 'reconnecting', metadata: Object.freeze({ ...s.metadata, reconnectCount: s.metadata.reconnectCount + 1 }) }, 'streaming_reconnecting', reason); }
  stop(id: string) { this.state = 'stopped'; this.activeSessionId = undefined; return this.patch(this.must(id), { state: 'stopped', stoppedAt: now() }, 'streaming_stopped', 'Streaming stopped'); }
  fail(id: string, message: string) { this.state = 'failed'; return this.patch(this.must(id), { state: 'failed' }, 'streaming_failed', message); }
  getSession(id: string) { return this.sessions.get(id); }
  getSnapshot(): StreamingPipelineSnapshot { return Object.freeze({ id: this.id, state: this.state, sessions: Object.freeze([...this.sessions.values()]), ...(this.activeSessionId ? { activeSessionId: this.activeSessionId } : {}), events: Object.freeze([...this.events]), providers: streamingProviders, backend: this.backend, containsRuntimeHandles: false, containsMediaPayloads: false, containsEncodedPackets: false }); }
  getEvents() { return Object.freeze([...this.events]); }
  onRuntimeEvent(callback: (event: StreamingRuntimeEvent) => void) { this.listeners.add(callback); return () => this.listeners.delete(callback); }
  private patch(s: StreamingSession, patch: Partial<StreamingSession>, type: StreamingRuntimeEventType, message: string, metadata: Record<string, unknown> = {}) { const next = Object.freeze({ ...s, ...patch, events: s.events, containsRuntimeHandles: false, containsMediaPayloads: false, containsEncodedPackets: false }) as StreamingSession; this.sessions.set(s.id, this.withEvent(next, type, message, metadata)); return this.must(s.id); }
  private withEvent(s: StreamingSession, type: StreamingRuntimeEventType, message: string, metadata: Readonly<Record<string, unknown>> = {}) { const event: StreamingRuntimeEvent = Object.freeze({ id: seid(type), type, timestamp: now(), sessionId: s.id, state: s.state, message, metadata: Object.freeze({ ...metadata, backend: this.backend.id, provider: s.destination.provider }) }); this.events = [event, ...this.events].slice(0, 250); this.listeners.forEach((cb) => cb(event)); return Object.freeze({ ...s, events: Object.freeze([event, ...s.events].slice(0, 250)) }) as StreamingSession; }
  private must(id: string) { const s = this.sessions.get(id); if (!s) throw new Error(`Streaming session ${id} not found`); return s; }
}

export const createStreamingPipeline = (input: { id?: string; backend?: StreamingBackendDescriptor } = {}): StreamingPipelineV2 => new MetadataStreamingPipeline(input.id, input.backend);
export async function createDemoStreamingSession(input: { programOutput: import('../output-pipeline.js').ProgramOutput; audioMixer: import('../media-runtime/audio-mixer.js').AudioMixer; mediaClock?: import('../sync/clock.js').MediaClock; frameScheduler?: import('../sync/index.js').FrameScheduler }) { const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const scheduler = input.frameScheduler ?? new FrameScheduler(clock); const pipeline = createStreamingPipeline({ id: 'streaming-pipeline:demo' }); const session = pipeline.createSession({ id: 'streaming-session:demo', destination: { kind: 'rtmps', provider: 'youtube', label: 'Demo YouTube RTMPS', endpointUrl: 'rtmps://a.rtmps.youtube.com/live2/STREAM_KEY', streamKeyRef: 'secret://youtube/demo' }, programOutput: input.programOutput, audioMixer: input.audioMixer, mediaClock: clock, frameScheduler: scheduler, targetBitrateKbps: 4500, latencyEstimateMs: 2500, metadata: { demo: true } }); pipeline.prepare(session.id); pipeline.connect(session.id); pipeline.start(session.id); const tick = scheduler.createTick(); pipeline.publishProgramFrame(session.id, tick); pipeline.publishAudioFrame(session.id, 480, tick); pipeline.reconnect(session.id, 'Demo reconnect metadata event'); pipeline.stop(session.id); return { pipeline: pipeline.getSnapshot(), session: pipeline.getSession(session.id)!, events: pipeline.getEvents() }; }
