import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
declare const process: { env: Record<string, string | undefined> } | undefined;

export type WebRTCRole = 'host' | 'guest' | 'producer' | 'operator' | 'observer';
export type WebRTCPeerConnectionState = 'idle' | 'planned' | 'signaling' | 'connecting' | 'connected' | 'reconnecting' | 'disconnected' | 'failed' | 'closed' | 'unavailable';
export type WebRTCTrackKind = 'audio' | 'video';
export type WebRTCSignalMessageType = 'offer' | 'answer' | 'ice_candidate' | 'peer_joined' | 'peer_left' | 'reconnect_requested' | 'connection_failed';
export type WebRTCHealthStatus = 'healthy' | 'degraded' | 'critical' | 'unavailable';
export interface WebRTCIceServerConfig { readonly urls: readonly string[]; readonly username?: string; readonly credential?: string; readonly credentialType?: 'password' | 'oauth' | 'placeholder'; readonly kind?: 'stun' | 'turn'; }
export interface WebRTCMediaTrackRef { readonly peerId: string; readonly trackId: string; readonly kind: WebRTCTrackKind; readonly sourceId?: string; readonly guestId?: string; readonly muted: boolean; readonly enabled: boolean; readonly connectionState: WebRTCPeerConnectionState; readonly frameId?: number; readonly graphRevision?: number; readonly pressure?: 'normal' | 'elevated' | 'overloaded'; readonly metadata: Record<string, unknown>; }
export interface WebRTCPeer { readonly id: string; readonly role: WebRTCRole; readonly displayName?: string; readonly connectionState: WebRTCPeerConnectionState; readonly signalingState?: string; readonly iceState?: string; readonly localTrackRefs: readonly WebRTCMediaTrackRef[]; readonly remoteTrackRefs: readonly WebRTCMediaTrackRef[]; readonly joinedAt: string; readonly updatedAt: string; readonly latestFailure?: WebRTCFailure; readonly metadata: Record<string, unknown>; }
export interface WebRTCTransportPlan { readonly id: string; readonly enabled: boolean; readonly runtimeMode: 'mock' | 'browser'; readonly sessionId: string; readonly role: WebRTCRole; readonly iceServers: readonly WebRTCIceServerConfig[]; readonly peers: readonly WebRTCPeer[]; readonly graphRevision?: number; readonly createdAt: string; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface WebRTCSession { readonly id: string; readonly planId: string; readonly status: WebRTCPeerConnectionState; readonly role: WebRTCRole; readonly peers: readonly WebRTCPeer[]; readonly localTrackRefs: readonly WebRTCMediaTrackRef[]; readonly remoteTrackRefs: readonly WebRTCMediaTrackRef[]; readonly startedAt?: string; readonly updatedAt: string; readonly failures: readonly WebRTCFailure[]; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface WebRTCConnectionHealth { readonly status: WebRTCHealthStatus; readonly peerCount: number; readonly connectedPeers: number; readonly disconnectedPeers: number; readonly localTracks: number; readonly remoteTracks: number; readonly iceState: string; readonly signalingState: string; readonly latestFailure?: WebRTCFailure; readonly degradedModes: readonly string[]; readonly summary: string; }
export interface WebRTCSignalMessage { readonly id: string; readonly type: WebRTCSignalMessageType; readonly sessionId: string; readonly peerId?: string; readonly targetPeerId?: string; readonly timestamp: string; readonly payload: Record<string, unknown>; readonly graphRevision?: number; }
export interface WebRTCFailure { readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly classification: 'ice' | 'peer_disconnect' | 'signaling' | 'media_track' | 'browser_unavailable' | 'unknown'; readonly ubosFailure: UBOSFailure; }
export interface WebRTCExecutionResult { readonly success: boolean; readonly session?: WebRTCSession; readonly plan?: WebRTCTransportPlan; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
export interface WebRTCManifest { readonly id: string; readonly sessionId: string; readonly planId: string; readonly createdAt: string; readonly peers: readonly Pick<WebRTCPeer, 'id' | 'role' | 'connectionState'>[]; readonly trackRefs: readonly WebRTCMediaTrackRef[]; readonly signalEvents: readonly WebRTCSignalMessage[]; readonly replayable: boolean; readonly notes: readonly string[]; }
type PC = { close?: () => void; addTrack?: (track: unknown, stream?: unknown) => unknown; removeTrack?: (sender: unknown) => void; createOffer?: (options?: unknown) => Promise<unknown>; createAnswer?: (options?: unknown) => Promise<unknown>; setRemoteDescription?: (description: unknown) => Promise<void>; addIceCandidate?: (candidate: unknown) => Promise<void>; addEventListener?: (type: string, cb: (event: unknown) => void) => void; };
const now = () => new Date().toISOString();
const defaultIce: readonly WebRTCIceServerConfig[] = [{ kind: 'stun', urls: ['stun:stun.example.invalid:3478'] }];
export function isWebRTCRuntimeEnabled(env: Record<string, string | undefined> = typeof process !== 'undefined' ? process.env : {}) { return env.UBOS_ENABLE_WEBRTC_RUNTIME === 'true' || env.NEXT_PUBLIC_UBOS_WEBRTC_RUNTIME === 'true'; }
export function createWebRTCTransportPlan(input: { sessionId: string; role: WebRTCRole; peers?: readonly WebRTCPeer[]; iceServers?: readonly WebRTCIceServerConfig[]; graphRevision?: number; env?: Record<string, string | undefined>; now?: string; metadata?: Record<string, unknown> }): WebRTCTransportPlan { const enabled = isWebRTCRuntimeEnabled(input.env); return { id: `webrtc-plan:${input.sessionId}:${input.graphRevision ?? 0}`, enabled, runtimeMode: enabled ? 'browser' : 'mock', sessionId: input.sessionId, role: input.role, iceServers: input.iceServers?.length ? input.iceServers : defaultIce, peers: input.peers ?? [], ...(input.graphRevision !== undefined ? { graphRevision: input.graphRevision } : {}), createdAt: input.now ?? now(), warnings: enabled ? [] : ['WebRTC runtime disabled; using metadata-only mock plan'], metadata: input.metadata ?? {} }; }
export function validateWebRTCTransportPlan(plan: WebRTCTransportPlan) { const errors: string[] = []; const warnings = [...plan.warnings]; if (!plan.sessionId) errors.push('Missing WebRTC sessionId'); if (!plan.iceServers.length) warnings.push('Missing ICE servers; peer connectivity may be limited'); if (plan.iceServers.some((server) => server.kind === 'turn' && (!server.username || !server.credential))) warnings.push('TURN server uses placeholder or missing credentials'); return { valid: errors.length === 0, warnings, errors }; }
export function createWebRTCSession(plan: WebRTCTransportPlan): WebRTCSession { return { id: `webrtc-session:${plan.sessionId}`, planId: plan.id, status: plan.enabled ? 'planned' : 'idle', role: plan.role, peers: plan.peers, localTrackRefs: [], remoteTrackRefs: plan.peers.flatMap((peer) => peer.remoteTrackRefs), updatedAt: now(), failures: [], warnings: plan.warnings, metadata: { graphRevision: plan.graphRevision, runtimeMode: plan.runtimeMode } }; }
export const addWebRTCPeer = (session: WebRTCSession, peer: WebRTCPeer): WebRTCSession => ({ ...session, peers: [...session.peers.filter((p) => p.id !== peer.id), peer], updatedAt: now() });
export const removeWebRTCPeer = (session: WebRTCSession, peerId: string): WebRTCSession => ({ ...session, peers: session.peers.filter((peer) => peer.id !== peerId), remoteTrackRefs: session.remoteTrackRefs.filter((track) => track.peerId !== peerId), updatedAt: now() });
export const updateWebRTCPeerState = (session: WebRTCSession, peerId: string, state: WebRTCPeerConnectionState, extra: Partial<WebRTCPeer> = {}): WebRTCSession => ({ ...session, peers: session.peers.map((peer) => peer.id === peerId ? { ...peer, ...extra, connectionState: state, updatedAt: now() } : peer), status: state === 'failed' ? 'failed' : session.status, updatedAt: now() });
export function createWebRTCMediaTrackRef(input: Omit<WebRTCMediaTrackRef, 'metadata'> & { metadata?: Record<string, unknown> }): WebRTCMediaTrackRef { return { ...input, metadata: input.metadata ?? {} }; }
export function createWebRTCPeer(input: { id: string; role: WebRTCRole; displayName?: string; state?: WebRTCPeerConnectionState; localTrackRefs?: readonly WebRTCMediaTrackRef[]; remoteTrackRefs?: readonly WebRTCMediaTrackRef[]; metadata?: Record<string, unknown> }): WebRTCPeer { const timestamp = now(); return { id: input.id, role: input.role, ...(input.displayName ? { displayName: input.displayName } : {}), connectionState: input.state ?? 'planned', localTrackRefs: input.localTrackRefs ?? [], remoteTrackRefs: input.remoteTrackRefs ?? [], joinedAt: timestamp, updatedAt: timestamp, metadata: input.metadata ?? {} }; }
export function summarizeWebRTCHealth(session: WebRTCSession): WebRTCConnectionHealth { const connectedPeers = session.peers.filter((peer) => peer.connectionState === 'connected').length; const disconnectedPeers = session.peers.filter((peer) => ['disconnected', 'failed', 'closed', 'unavailable'].includes(peer.connectionState)).length; const latestFailure = session.failures.at(-1) ?? session.peers.map((peer) => peer.latestFailure).filter((failure): failure is WebRTCFailure => Boolean(failure)).at(-1); const status: WebRTCHealthStatus = session.status === 'unavailable' ? 'unavailable' : latestFailure && !latestFailure.retryable ? 'critical' : disconnectedPeers > 0 ? 'degraded' : 'healthy'; return { status, peerCount: session.peers.length, connectedPeers, disconnectedPeers, localTracks: session.localTrackRefs.length, remoteTracks: session.remoteTrackRefs.length, iceState: session.peers.map((peer) => peer.iceState).filter(Boolean).join(',') || 'unknown', signalingState: session.peers.map((peer) => peer.signalingState).filter(Boolean).join(',') || 'unknown', ...(latestFailure ? { latestFailure } : {}), degradedModes: disconnectedPeers ? ['audio_only', 'reduced_diagnostics', 'disabled_preview'] : [], summary: `WebRTC ${status}: ${connectedPeers}/${session.peers.length} peers connected` }; }
export const createWebRTCManifest = (session: WebRTCSession, signals: readonly WebRTCSignalMessage[] = []): WebRTCManifest => ({ id: `webrtc-manifest:${session.id}`, sessionId: session.id, planId: session.planId, createdAt: now(), peers: session.peers.map(({ id, role, connectionState }) => ({ id, role, connectionState })), trackRefs: [...session.localTrackRefs, ...session.remoteTrackRefs], signalEvents: signals, replayable: true, notes: ['Replay metadata only; live peer connections and tracks are never reconnected.'] });
export function redactWebRTCDiagnostics<T>(value: T): T { return JSON.parse(JSON.stringify(value, (key, item) => key.toLowerCase().includes('credential') || key.toLowerCase().includes('password') ? '[REDACTED]' : item)) as T; }
export function mapWebRTCErrorToFailure(error: { code?: string; message?: string; retryable?: boolean; classification?: WebRTCFailure['classification']; intentId?: string }): WebRTCFailure { const message = String(error.message ?? 'WebRTC failure'); const classification = error.classification ?? (/ice/i.test(message) ? 'ice' : /signal/i.test(message) ? 'signaling' : /track|media/i.test(message) ? 'media_track' : /disconnect/i.test(message) ? 'peer_disconnect' : 'unknown'); const retryable = error.retryable ?? classification !== 'media_track'; return { code: error.code ?? `WEBRTC_${classification.toUpperCase()}_FAILURE`, message: redactWebRTCDiagnostics(message), retryable, occurredAt: now(), classification, ubosFailure: createFailureRecord({ category: classification === 'signaling' ? 'WEBSOCKET_FAILURE' : 'MEDIA_SOURCE_FAILURE', sourceLayer: classification === 'signaling' ? 'websocket' : 'execution', subsystem: 'webrtc', ...(error.intentId ? { intentId: error.intentId } : {}), message, recoverable: retryable, metadata: { classification } }) }; }
export function validateWebRTCSignalMessage(message: WebRTCSignalMessage) { const errors: string[] = []; if (!['offer', 'answer', 'ice_candidate', 'peer_joined', 'peer_left', 'reconnect_requested', 'connection_failed'].includes(message.type)) errors.push('Unsupported signal type'); if (!message.sessionId) errors.push('Missing signal sessionId'); if ((message.type === 'offer' || message.type === 'answer') && !message.payload.description) errors.push('Missing session description metadata'); return { valid: errors.length === 0, warnings: [], errors }; }
export function createPeerConnection(config: { iceServers?: readonly WebRTCIceServerConfig[]; env?: Record<string, string | undefined> } = {}): WebRTCExecutionResult & { peerConnection?: PC } { if (!isWebRTCRuntimeEnabled(config.env)) return { success: true, warnings: ['WebRTC runtime disabled; peer connection not created'], errors: [] }; const Ctor = (globalThis as unknown as { RTCPeerConnection?: new (config: unknown) => PC }).RTCPeerConnection; if (!Ctor) return { success: false, warnings: [], errors: ['RTCPeerConnection unavailable'] }; return { success: true, peerConnection: new Ctor({ iceServers: redactWebRTCDiagnostics(config.iceServers ?? defaultIce) }), warnings: [], errors: [] }; }
export const closePeerConnection = (pc?: PC) => { pc?.close?.(); return { success: true, warnings: [], errors: [] }; };
export function attachLocalTrack(pc: PC | undefined, track: unknown, stream?: unknown) { if (!pc?.addTrack) return { success: false, warnings: [], errors: ['PeerConnection addTrack unavailable'] }; return { success: true, sender: pc.addTrack(track, stream), warnings: [], errors: [] }; }
export function detachLocalTrack(pc: PC | undefined, sender: unknown) { if (!pc?.removeTrack) return { success: false, warnings: [], errors: ['PeerConnection removeTrack unavailable'] }; pc.removeTrack(sender); return { success: true, warnings: [], errors: [] }; }
export function handleRemoteTrack(peerId: string, event: { track?: { id?: string; kind?: string; enabled?: boolean; muted?: boolean } }) { const track = event.track; return createWebRTCMediaTrackRef({ peerId, trackId: track?.id ?? `remote:${peerId}`, kind: track?.kind === 'audio' ? 'audio' : 'video', enabled: track?.enabled ?? true, muted: track?.muted ?? false, connectionState: 'connected' }); }
export const createOffer = (pc?: PC, options?: unknown) => pc?.createOffer ? pc.createOffer(options) : Promise.reject(new Error('createOffer unavailable'));
export const createAnswer = (pc?: PC, options?: unknown) => pc?.createAnswer ? pc.createAnswer(options) : Promise.reject(new Error('createAnswer unavailable'));
export const applyRemoteDescription = (pc: PC | undefined, description: unknown) => pc?.setRemoteDescription ? pc.setRemoteDescription(description) : Promise.reject(new Error('setRemoteDescription unavailable'));
export const addIceCandidate = (pc: PC | undefined, candidate: unknown) => pc?.addIceCandidate ? pc.addIceCandidate(candidate) : Promise.reject(new Error('addIceCandidate unavailable'));
export function collectIceCandidate(pc: PC | undefined, cb: (candidate: unknown) => void) { pc?.addEventListener?.('icecandidate', (event) => cb((event as { candidate?: unknown }).candidate)); return { success: Boolean(pc?.addEventListener), warnings: pc?.addEventListener ? [] : ['ICE candidate collection unavailable'], errors: [] }; }
export const cleanupWebRTCPeer = (pc?: PC) => { closePeerConnection(pc); return { success: true, warnings: ['Runtime-only peer objects cleaned up'], errors: [] }; };
export const WebRTCRuntime = Object.freeze({ createWebRTCTransportPlan, validateWebRTCTransportPlan, createWebRTCSession, addWebRTCPeer, removeWebRTCPeer, updateWebRTCPeerState, createWebRTCMediaTrackRef, summarizeWebRTCHealth, createWebRTCManifest, redactWebRTCDiagnostics, mapWebRTCErrorToFailure, createPeerConnection });
