import { createFailureRecord, type UBOSFailure } from '../../../shared/src/failure-recovery.js';
declare const process: { env: Record<string, string | undefined> } | undefined;

export type WebRTCRole = 'host' | 'guest' | 'producer' | 'operator' | 'observer';
export type WebRTCPeerConnectionState = 'idle' | 'planned' | 'signaling' | 'connecting' | 'connected' | 'reconnecting' | 'disconnected' | 'failed' | 'closed' | 'unavailable';
export type WebRTCTrackKind = 'audio' | 'video';
export type WebRTCSignalMessageType = 'offer' | 'answer' | 'ice_candidate' | 'peer_joined' | 'peer_left' | 'reconnect_requested' | 'connection_failed';
export type WebRTCHealthStatus = 'healthy' | 'degraded' | 'critical' | 'unavailable';
export interface WebRTCIceServerConfig { readonly urls: readonly string[]; readonly username?: string; readonly credential?: string; readonly credentialType?: 'password' | 'oauth' | 'placeholder'; readonly kind?: 'stun' | 'turn'; }
export interface WebRTCMediaTrackRef { readonly peerId: string; readonly trackId: string; readonly kind: WebRTCTrackKind; readonly sourceId?: string; readonly guestId?: string; readonly muted: boolean; readonly enabled: boolean; readonly connectionState: WebRTCPeerConnectionState; readonly frameId?: number; readonly graphRevision?: number; readonly pressure?: 'normal' | 'elevated' | 'overloaded'; readonly metadata: Record<string, unknown>; }
export interface WebRTCPeer { readonly id: string; readonly role: WebRTCRole; readonly displayName?: string; readonly connectionState: WebRTCPeerConnectionState; readonly signalingState?: string; readonly iceState?: string; readonly localTrackRefs: readonly WebRTCMediaTrackRef[]; readonly remoteTrackRefs: readonly WebRTCMediaTrackRef[]; readonly joinedAt: string; readonly updatedAt: string; readonly latestFailure?: WebRTCFailure; readonly metadata: Record<string, unknown>; }
export interface WebRTCTransportPlan { readonly id: string; readonly enabled: boolean; readonly runtimeMode: 'mock' | 'browser'; readonly sessionId: string; readonly role: WebRTCRole; readonly iceServers: readonly WebRTCIceServerConfig[]; readonly peers: readonly WebRTCPeer[]; readonly graphRevision?: number; readonly createdAt: string; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface WebRTCSession { readonly id: string; readonly planId: string; readonly status: WebRTCPeerConnectionState; readonly role: WebRTCRole; readonly peers: readonly WebRTCPeer[]; readonly localTrackRefs: readonly WebRTCMediaTrackRef[]; readonly remoteTrackRefs: readonly WebRTCMediaTrackRef[]; readonly startedAt?: string; readonly updatedAt: string; readonly failures: readonly WebRTCFailure[]; readonly warnings: readonly string[]; readonly metadata: Record<string, unknown>; }
export interface WebRTCConnectionHealth { readonly status: WebRTCHealthStatus; readonly peerCount: number; readonly connectedPeers: number; readonly disconnectedPeers: number; readonly localTracks: number; readonly remoteTracks: number; readonly iceState: string; readonly signalingState: string; readonly latestFailure?: WebRTCFailure; readonly degradedModes: readonly string[]; readonly summary: string; }
export interface WebRTCSignalMessage { readonly id: string; readonly type: WebRTCSignalMessageType; readonly sessionId: string; readonly peerId?: string; readonly targetPeerId?: string; readonly timestamp: string; readonly payload: Record<string, unknown>; readonly graphRevision?: number; }
export interface WebRTCFailure { readonly code: string; readonly message: string; readonly retryable: boolean; readonly occurredAt: string; readonly classification: 'ice' | 'peer_disconnect' | 'signaling' | 'media_track' | 'browser_unavailable' | 'unknown'; readonly ubosFailure: UBOSFailure; }
export interface WebRTCExecutionResult { readonly success: boolean; readonly session?: WebRTCSession; readonly plan?: WebRTCTransportPlan; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
export interface WebRTCManifest { readonly id: string; readonly sessionId: string; readonly planId: string; readonly createdAt: string; readonly peers: readonly Pick<WebRTCPeer, 'id' | 'role' | 'connectionState'>[]; readonly trackRefs: readonly WebRTCMediaTrackRef[]; readonly signalEvents: readonly WebRTCSignalMessage[]; readonly replayable: boolean; readonly notes: readonly string[]; }
type PC = { close?: () => void; addTrack?: (track: unknown, stream?: unknown) => unknown; removeTrack?: (sender: unknown) => void; createOffer?: (options?: unknown) => Promise<unknown>; createAnswer?: (options?: unknown) => Promise<unknown>; setRemoteDescription?: (description: unknown) => Promise<void>; addIceCandidate?: (candidate: unknown) => Promise<void>; addEventListener?: (type: string, cb: (event: unknown) => void) => void; };
const now = () => new Date().toISOString();
const defaultIce: readonly WebRTCIceServerConfig[] = [{ kind: 'stun', urls: ['stun:stun.example.invalid:3478'] }];
export function isWebRTCRuntimeEnabled(env: Record<string, string | undefined> = typeof process !== 'undefined' ? process.env : {}) { return env.UBOS_ENABLE_WEBRTC_RUNTIME === 'true' || env.NEXT_PUBLIC_UBOS_WEBRTC_RUNTIME === 'true' || env.UBOS_ENABLE_REAL_WEBRTC === 'true' || env.NEXT_PUBLIC_UBOS_REAL_WEBRTC === 'true'; }
export function createWebRTCTransportPlan(input: { sessionId: string; role: WebRTCRole; peers?: readonly WebRTCPeer[]; iceServers?: readonly WebRTCIceServerConfig[]; graphRevision?: number; env?: Record<string, string | undefined>; now?: string; metadata?: Record<string, unknown> }): WebRTCTransportPlan { const enabled = isWebRTCRuntimeEnabled(input.env); return { id: `webrtc-plan:${input.sessionId}:${input.graphRevision ?? 0}`, enabled, runtimeMode: enabled ? 'browser' : 'mock', sessionId: input.sessionId, role: input.role, iceServers: input.iceServers?.length ? input.iceServers : defaultIce, peers: input.peers ?? [], ...(input.graphRevision !== undefined ? { graphRevision: input.graphRevision } : {}), createdAt: input.now ?? now(), warnings: enabled ? [] : ['WebRTC runtime disabled; using metadata-only mock plan'], metadata: input.metadata ?? {} }; }
export function validateWebRTCTransportPlan(plan: WebRTCTransportPlan) { const errors: string[] = []; const warnings = [...plan.warnings]; if (!plan.sessionId) errors.push('Missing WebRTC sessionId'); if (!plan.iceServers.length) warnings.push('Missing ICE servers; peer connectivity may be limited'); if (plan.iceServers.some((server) => server.kind === 'turn' && (!server.username || !server.credential))) warnings.push('TURN server uses placeholder or missing credentials'); return { valid: errors.length === 0, warnings, errors }; }
export function createWebRTCSession(plan: WebRTCTransportPlan): WebRTCSession { return { id: `webrtc-session:${plan.sessionId}`, planId: plan.id, status: plan.enabled ? 'planned' : 'idle', role: plan.role, peers: plan.peers, localTrackRefs: [], remoteTrackRefs: plan.peers.flatMap((peer) => peer.remoteTrackRefs), updatedAt: now(), failures: [], warnings: plan.warnings, metadata: { graphRevision: plan.graphRevision, runtimeMode: plan.runtimeMode } }; }
export const addWebRTCPeer = (session: WebRTCSession, peer: WebRTCPeer): WebRTCSession => ({ ...session, peers: [...session.peers.filter((p) => p.id !== peer.id), peer], updatedAt: now() });
export const removeWebRTCPeer = (session: WebRTCSession, peerId: string): WebRTCSession => ({ ...session, peers: session.peers.filter((peer) => peer.id !== peerId), remoteTrackRefs: session.remoteTrackRefs.filter((track) => track.peerId !== peerId), updatedAt: now() });
export const updateWebRTCPeerState = (session: WebRTCSession, peerId: string, state: WebRTCPeerConnectionState, extra: Partial<WebRTCPeer> = {}): WebRTCSession => ({ ...session, peers: session.peers.map((peer) => peer.id === peerId ? { ...peer, ...extra, connectionState: state, updatedAt: now() } : peer), status: state === 'failed' ? 'failed' : session.status, updatedAt: now() });
export function createWebRTCMediaTrackRef(input: Omit<WebRTCMediaTrackRef, 'metadata'> & { metadata?: Record<string, unknown> }): WebRTCMediaTrackRef { return { ...input, metadata: input.metadata ?? {} }; }
export function createWebRTCPeer(input: { id: string; role: WebRTCRole; displayName?: string; state?: WebRTCPeerConnectionState; localTrackRefs?: readonly WebRTCMediaTrackRef[]; remoteTrackRefs?: readonly WebRTCMediaTrackRef[]; metadata?: Record<string, unknown> }): WebRTCPeer { const timestamp = now(); return { id: input.id, role: input.role, ...(input.displayName ? { displayName: input.displayName } : {}), connectionState: input.state ?? 'planned', localTrackRefs: input.localTrackRefs ?? [], remoteTrackRefs: input.remoteTrackRefs ?? [], joinedAt: timestamp, updatedAt: timestamp, metadata: input.metadata ?? {} }; }
export function summarizeWebRTCHealth(session: WebRTCSession): WebRTCConnectionHealth { const connectedPeers = session.peers.filter((peer) => peer.connectionState === 'connected').length; const disconnectedPeers = session.peers.filter((peer) => ['disconnected', 'failed', 'closed', 'unavailable'].includes(peer.connectionState)).length; const latestFailure = session.failures.at(-1) ?? session.peers.map((peer) => peer.latestFailure).filter((failure): failure is WebRTCFailure => Boolean(failure)).at(-1); const status: WebRTCHealthStatus = session.status === 'unavailable' ? 'unavailable' : latestFailure && !latestFailure.retryable ? 'critical' : disconnectedPeers > 0 ? 'degraded' : 'healthy'; return { status, peerCount: session.peers.length, connectedPeers, disconnectedPeers, localTracks: session.localTrackRefs.length, remoteTracks: session.remoteTrackRefs.length, iceState: session.peers.map((peer) => peer.iceState).filter(Boolean).join(',') || 'unknown', signalingState: session.peers.map((peer) => peer.signalingState).filter(Boolean).join(',') || 'unknown', ...(latestFailure ? { latestFailure } : {}), degradedModes: disconnectedPeers ? ['audio_only', 'reduced_diagnostics', 'disabled_preview'] : [], summary: `WebRTC ${status}: ${connectedPeers}/${session.peers.length} peers connected` }; }
export const createWebRTCManifest = (session: WebRTCSession, signals: readonly WebRTCSignalMessage[] = []): WebRTCManifest => ({ id: `webrtc-manifest:${session.id}`, sessionId: session.id, planId: session.planId, createdAt: now(), peers: session.peers.map(({ id, role, connectionState }) => ({ id, role, connectionState })), trackRefs: [...session.localTrackRefs, ...session.remoteTrackRefs], signalEvents: signals, replayable: true, notes: ['Replay metadata only; live peer connections and tracks are never reconnected.'] });
export function redactWebRTCDiagnostics<T>(value: T): T { return JSON.parse(JSON.stringify(value, (key, item) => key.toLowerCase().includes('credential') || key.toLowerCase().includes('password') ? '[REDACTED]' : item)) as T; }
export function mapWebRTCErrorToFailure(error: { code?: string; message?: string; retryable?: boolean; classification?: WebRTCFailure['classification']; intentId?: string }): WebRTCFailure { const message = String(error.message ?? 'WebRTC failure'); const classification = error.classification ?? (/ice/i.test(message) ? 'ice' : /signal/i.test(message) ? 'signaling' : /track|media/i.test(message) ? 'media_track' : /disconnect/i.test(message) ? 'peer_disconnect' : 'unknown'); const retryable = error.retryable ?? classification !== 'media_track'; return { code: error.code ?? `WEBRTC_${classification.toUpperCase()}_FAILURE`, message: redactWebRTCDiagnostics(message), retryable, occurredAt: now(), classification, ubosFailure: createFailureRecord({ category: classification === 'signaling' ? 'WEBSOCKET_FAILURE' : 'MEDIA_SOURCE_FAILURE', sourceLayer: classification === 'signaling' ? 'websocket' : 'execution', subsystem: 'webrtc', ...(error.intentId ? { intentId: error.intentId } : {}), message, recoverable: retryable, metadata: { classification } }) }; }
export function validateWebRTCSignalMessage(message: WebRTCSignalMessage) { const errors: string[] = []; if (!['offer', 'answer', 'ice_candidate', 'peer_joined', 'peer_left', 'reconnect_requested', 'connection_failed'].includes(message.type)) errors.push('Unsupported signal type'); if (!message.sessionId) errors.push('Missing signal sessionId'); if ((message.type === 'offer' || message.type === 'answer') && !message.payload.description) errors.push('Missing session description metadata'); return { valid: errors.length === 0, warnings: [], errors }; }
export function createPeerConnection(config: { iceServers?: readonly WebRTCIceServerConfig[]; env?: Record<string, string | undefined> } = {}): WebRTCExecutionResult & { peerConnection?: PC } { if (!isWebRTCRuntimeEnabled(config.env)) return { success: true, warnings: ['WebRTC runtime disabled; peer connection not created'], errors: [] }; const Ctor = (globalThis as unknown as { RTCPeerConnection?: new (config: unknown) => PC }).RTCPeerConnection; if (!Ctor) return { success: false, warnings: [], errors: ['RTCPeerConnection unavailable'] }; return { success: true, peerConnection: new Ctor({ iceServers: redactWebRTCDiagnostics(config.iceServers ?? defaultIce) }), warnings: [], errors: [] }; }
export const closePeerConnection = (pc?: PC) => { pc?.close?.(); return { success: true, warnings: [], errors: [] }; };
export function attachLocalTrack(pc: PC | undefined, track: unknown, stream?: unknown) { if (!pc?.addTrack) return { success: false, warnings: [], errors: ['PeerConnection addTrack unavailable'] }; return { success: true, sender: pc.addTrack(track, stream), warnings: [], errors: [] }; }
export function detachLocalTrack(pc: PC | undefined, sender: unknown) { if (!pc?.removeTrack) return { success: false, warnings: [], errors: ['PeerConnection removeTrack unavailable'] }; pc.removeTrack(sender); return { success: true, warnings: [], errors: [] }; }
export function handleRemoteTrack(peerId: string, event: { track?: { id?: string; kind?: string; enabled?: boolean; muted?: boolean } }) { const track = event.track; return createWebRTCMediaTrackRef({ peerId, trackId: track?.id ?? `remote:${peerId}`, kind: track?.kind === 'audio' ? 'audio' : 'video', enabled: track?.enabled ?? true, muted: track?.muted ?? false, connectionState: 'connected' }); }
export const createOffer = (pc?: PC, options?: unknown) => pc?.createOffer ? pc.createOffer(options) : Promise.reject(new Error('createOffer unavailable'));
export const createAnswer = (pc?: PC, options?: unknown) => pc?.createAnswer ? pc.createAnswer(options) : Promise.reject(new Error('createAnswer unavailable'));
export const applyRemoteDescription = (pc: PC | undefined, description: unknown) => pc?.setRemoteDescription ? pc.setRemoteDescription(description) : Promise.reject(new Error('setRemoteDescription unavailable'));
export const addIceCandidate = (pc: PC | undefined, candidate: unknown) => pc?.addIceCandidate ? pc.addIceCandidate(candidate) : Promise.reject(new Error('addIceCandidate unavailable'));
export function collectIceCandidate(pc: PC | undefined, cb: (candidate: unknown) => void) { pc?.addEventListener?.('icecandidate', (event) => cb((event as { candidate?: unknown }).candidate)); return { success: Boolean(pc?.addEventListener), warnings: pc?.addEventListener ? [] : ['ICE candidate collection unavailable'], errors: [] }; }
export const cleanupWebRTCPeer = (pc?: PC) => { closePeerConnection(pc); return { success: true, warnings: ['Runtime-only peer objects cleaned up'], errors: [] }; };
export const WebRTCRuntime = Object.freeze({ createWebRTCTransportPlan, validateWebRTCTransportPlan, createWebRTCSession, addWebRTCPeer, removeWebRTCPeer, updateWebRTCPeerState, createWebRTCMediaTrackRef, summarizeWebRTCHealth, createWebRTCManifest, redactWebRTCDiagnostics, mapWebRTCErrorToFailure, createPeerConnection });

export type WebRTCParticipantKind = 'host' | 'guest' | 'producer' | 'operator' | 'remote_camera' | 'remote_screen_share' | 'audio_only';
export type WebRTCMediaSourceKind = 'camera' | 'microphone' | 'screen' | 'window' | 'tab' | 'virtual_camera';
export type WebRTCNegotiationState = 'idle' | 'offer_created' | 'answer_created' | 'ice_gathering' | 'connected' | 'restarting' | 'failed';
export interface WebRTCQualityMetrics { readonly bitrateKbps: number; readonly packetLossRatio: number; readonly latencyMs: number; readonly jitterMs: number; readonly reconnects: number; }
export interface WebRTCBackpressureState { readonly maxConcurrentNegotiations: number; readonly activeNegotiations: number; readonly queuedNegotiations: number; readonly queuedIceRestarts: number; readonly reconnectsInWindow: number; readonly throttled: boolean; readonly warnings: readonly string[]; }
export interface WebRTCSessionDiagnostics { readonly sessionId: string; readonly peerId: string; readonly role: WebRTCRole; readonly participantKind: WebRTCParticipantKind; readonly iceState: string; readonly dtlsState: string; readonly signalingState: string; readonly connectionQuality: WebRTCHealthStatus; readonly bitrateKbps: number; readonly latencyMs: number; readonly packetLossRatio: number; readonly tracks: readonly WebRTCMediaTrackRef[]; readonly reconnectCount: number; readonly browser: string; readonly device: string; }
export interface WebRTCReplayEvent { readonly id: string; readonly type: 'lifecycle' | 'negotiation' | 'track' | 'mute' | 'health' | 'failure'; readonly sessionId: string; readonly peerId?: string; readonly timestamp: string; readonly payload: Record<string, unknown>; readonly containsRuntimeHandles: false; }
export interface WebRTCOfferMetadata { readonly type: 'offer'; readonly sessionId: string; readonly peerId: string; readonly revision: number; readonly media: readonly WebRTCMediaSourceKind[]; readonly redacted: true; readonly description?: { readonly type: 'offer'; readonly fingerprint?: string }; }
export interface WebRTCAnswerMetadata { readonly type: 'answer'; readonly sessionId: string; readonly peerId: string; readonly revision: number; readonly redacted: true; readonly description?: { readonly type: 'answer'; readonly fingerprint?: string }; }
export interface WebRTCIceMetadata { readonly type: 'ice'; readonly sessionId: string; readonly peerId: string; readonly candidateId: string; readonly protocol?: string; readonly relayProtocol?: string; readonly redacted: true; }

type RuntimePeerHandle = { pc?: PC; senders: Map<string, unknown>; tracks: Map<string, unknown>; dataChannels: Map<string, unknown> };
const peerIdPattern = /^[A-Za-z0-9._:-]{1,128}$/;
const forbiddenSignalKeys = /sdp|candidate|ice|credential|password|ufrag|pwd/i;
export function isRealWebRTCEnabled(env: Record<string, string | undefined> = typeof process !== 'undefined' ? process.env : {}) { return isWebRTCRuntimeEnabled(env) || env.UBOS_ENABLE_REAL_WEBRTC === 'true' || env.NEXT_PUBLIC_UBOS_REAL_WEBRTC === 'true'; }
export function validateWebRTCPeerId(peerId: string) { return peerIdPattern.test(peerId); }
export function sanitizeSignalingPayload(payload: Record<string, unknown>): Record<string, unknown> { return JSON.parse(JSON.stringify(payload, (key, value) => forbiddenSignalKeys.test(key) ? '[REDACTED]' : typeof value === 'string' && /a=|v=0|candidate:/i.test(value) ? '[REDACTED]' : value)) as Record<string, unknown>; }
export function createOfferMetadata(input: { sessionId: string; peerId: string; revision?: number; media?: readonly WebRTCMediaSourceKind[] }): WebRTCOfferMetadata { return { type: 'offer', sessionId: input.sessionId, peerId: input.peerId, revision: input.revision ?? 0, media: input.media ?? [], redacted: true, description: { type: 'offer' } }; }
export function createAnswerMetadata(input: { sessionId: string; peerId: string; revision?: number }): WebRTCAnswerMetadata { return { type: 'answer', sessionId: input.sessionId, peerId: input.peerId, revision: input.revision ?? 0, redacted: true, description: { type: 'answer' } }; }
export function createIceMetadata(input: { sessionId: string; peerId: string; candidateId?: string; protocol?: string; relayProtocol?: string }): WebRTCIceMetadata { return { type: 'ice', sessionId: input.sessionId, peerId: input.peerId, candidateId: input.candidateId ?? `ice:${input.peerId}:${Date.now()}`, ...(input.protocol ? { protocol: input.protocol } : {}), ...(input.relayProtocol ? { relayProtocol: input.relayProtocol } : {}), redacted: true }; }
export function validateWebRTCSignalingMetadata(message: WebRTCSignalMessage, ownerPeerIds: readonly string[] = []) { const base = validateWebRTCSignalMessage({ ...message, payload: sanitizeSignalingPayload(message.payload) }); const errors = [...base.errors]; if (message.peerId && !validateWebRTCPeerId(message.peerId)) errors.push('Invalid peer ID'); if (message.targetPeerId && !validateWebRTCPeerId(message.targetPeerId)) errors.push('Invalid target peer ID'); if (ownerPeerIds.length && message.peerId && !ownerPeerIds.includes(message.peerId)) errors.push('Signal peer does not belong to session'); if (JSON.stringify(message.payload).match(/\r\n|a=|v=0|candidate:/i)) errors.push('Raw SDP or ICE candidate payloads are not accepted by the metadata plane'); return { valid: errors.length === 0, warnings: base.warnings, errors };
}
export function createReplayEvent(input: Omit<WebRTCReplayEvent, 'id' | 'timestamp' | 'containsRuntimeHandles'> & { id?: string; timestamp?: string }): WebRTCReplayEvent { return { ...input, id: input.id ?? `webrtc-replay:${input.type}:${Date.now()}`, timestamp: input.timestamp ?? now(), containsRuntimeHandles: false, payload: sanitizeSignalingPayload(input.payload) }; }
export function calculateBackpressure(input: Partial<WebRTCBackpressureState> = {}): WebRTCBackpressureState { const max = input.maxConcurrentNegotiations ?? 2; const active = input.activeNegotiations ?? 0; const queued = input.queuedNegotiations ?? 0; const restarts = input.queuedIceRestarts ?? 0; const storms = input.reconnectsInWindow ?? 0; const warnings = [...(input.warnings ?? [])]; if (active >= max) warnings.push('Negotiation concurrency limit reached'); if (storms > 3) warnings.push('Reconnect storm throttled'); return { maxConcurrentNegotiations: max, activeNegotiations: active, queuedNegotiations: queued, queuedIceRestarts: restarts, reconnectsInWindow: storms, throttled: active >= max || storms > 3 || queued + restarts > 10, warnings };
}
export function collectWebRTCStatistics(input: Partial<WebRTCQualityMetrics> = {}): WebRTCQualityMetrics { return { bitrateKbps: input.bitrateKbps ?? 0, packetLossRatio: input.packetLossRatio ?? 0, latencyMs: input.latencyMs ?? 0, jitterMs: input.jitterMs ?? 0, reconnects: input.reconnects ?? 0 }; }
export function summarizeConnectionQuality(metrics: WebRTCQualityMetrics): WebRTCHealthStatus { return metrics.packetLossRatio > 0.15 || metrics.latencyMs > 1000 ? 'critical' : metrics.packetLossRatio > 0.05 || metrics.latencyMs > 350 ? 'degraded' : 'healthy'; }
export function planWebRTCRecovery(input: { sessionId: string; peerId: string; reason: string; attempt?: number; baseDelayMs?: number }) { const attempt = input.attempt ?? 1; return { action: /ice/i.test(input.reason) ? 'ice_restart' as const : 'automatic_reconnect' as const, sessionId: input.sessionId, peerId: input.peerId, backoffMs: Math.min((input.baseDelayMs ?? 500) * 2 ** Math.max(0, attempt - 1), 30_000), timeoutMs: 15_000, notifySupervisor: true, failure: mapWebRTCErrorToFailure({ message: input.reason, classification: /ice/i.test(input.reason) ? 'ice' : 'peer_disconnect' }) };
}

export class PeerConnectionManager { private readonly handles = new Map<string, RuntimePeerHandle>(); create(peerId: string, config: { iceServers?: readonly WebRTCIceServerConfig[]; env?: Record<string, string | undefined> } = {}) { const result = createPeerConnection({ ...config, env: config.env ?? { UBOS_ENABLE_REAL_WEBRTC: 'true' } }); this.handles.set(peerId, { ...(result.peerConnection ? { pc: result.peerConnection } : {}), senders: new Map(), tracks: new Map(), dataChannels: new Map() }); return result; } get(peerId: string) { return this.handles.get(peerId); } close(peerId: string) { closePeerConnection(this.handles.get(peerId)?.pc); this.handles.delete(peerId); return { success: true, warnings: ['Peer runtime handles disposed'], errors: [] }; } cleanup() { for (const peerId of [...this.handles.keys()]) this.close(peerId); } }
export class MediaTrackManager { addTrack(session: WebRTCSession, ref: WebRTCMediaTrackRef) { const tracks = ref.peerId === 'local' ? { localTrackRefs: [...session.localTrackRefs, ref] } : { remoteTrackRefs: [...session.remoteTrackRefs, ref] }; return { ...session, ...tracks, updatedAt: now() }; } removeTrack(session: WebRTCSession, trackId: string) { return { ...session, localTrackRefs: session.localTrackRefs.filter((t)=>t.trackId!==trackId), remoteTrackRefs: session.remoteTrackRefs.filter((t)=>t.trackId!==trackId), updatedAt: now() }; } mute(session: WebRTCSession, trackId: string, muted = true) { const update = (t: WebRTCMediaTrackRef) => t.trackId === trackId ? { ...t, muted, enabled: !muted } : t; return { ...session, localTrackRefs: session.localTrackRefs.map(update), remoteTrackRefs: session.remoteTrackRefs.map(update), updatedAt: now() }; } replaceTrack(session: WebRTCSession, oldTrackId: string, next: WebRTCMediaTrackRef) { return this.addTrack(this.removeTrack(session, oldTrackId), next); } }
export class ICEManager { private queuedRestarts: string[] = []; metadata(input: { sessionId: string; peerId: string; candidateId?: string }) { return createIceMetadata(input); } queueRestart(peerId: string) { this.queuedRestarts.push(peerId); return calculateBackpressure({ queuedIceRestarts: this.queuedRestarts.length }); } drainRestarts() { const drained = [...this.queuedRestarts]; this.queuedRestarts = []; return drained; } }
export class SignalingManager { createMessage(input: Omit<WebRTCSignalMessage, 'id' | 'timestamp' | 'payload'> & { id?: string; timestamp?: string; payload: Record<string, unknown> }): WebRTCSignalMessage { return { ...input, id: input.id ?? `signal:${input.type}:${Date.now()}`, timestamp: input.timestamp ?? now(), payload: sanitizeSignalingPayload(input.payload) }; } validate(message: WebRTCSignalMessage, owners: readonly string[] = []) { return validateWebRTCSignalingMetadata(message, owners); } }
export class ConnectionHealth { summarize(session: WebRTCSession, metrics: WebRTCQualityMetrics = collectWebRTCStatistics()) { const health = summarizeWebRTCHealth(session); return { ...health, status: health.status === 'healthy' ? summarizeConnectionQuality(metrics) : health.status, metrics }; } }
export class WebRTCStatistics { collect(input: Partial<WebRTCQualityMetrics> = {}) { return collectWebRTCStatistics(input); } }
export class WebRTCRecovery { plan(input: { sessionId: string; peerId: string; reason: string; attempt?: number }) { return planWebRTCRecovery(input); } }
export class WebRTCValidator { validateSignal(message: WebRTCSignalMessage, owners: readonly string[] = []) { return validateWebRTCSignalingMetadata(message, owners); } validatePlan(plan: WebRTCTransportPlan) { return validateWebRTCTransportPlan(plan); } }
export class WebRTCSessionManager { private session?: WebRTCSession; constructor(private readonly plan: WebRTCTransportPlan) {} create() { this.session = createWebRTCSession(this.plan); return this.session; } get() { return this.session; } addPeer(peer: WebRTCPeer) { this.session = addWebRTCPeer(this.session ?? this.create(), peer); return this.session; } disconnect(peerId: string) { this.session = updateWebRTCPeerState(this.session ?? this.create(), peerId, 'disconnected'); return this.session; } cleanup() { this.session = this.session ? { ...this.session, status: 'closed', updatedAt: now() } : this.create(); return this.session; } }
export class RealWebRTCRuntime { readonly peerConnections = new PeerConnectionManager(); readonly tracks = new MediaTrackManager(); readonly ice = new ICEManager(); readonly signaling = new SignalingManager(); readonly health = new ConnectionHealth(); readonly statistics = new WebRTCStatistics(); readonly recovery = new WebRTCRecovery(); readonly validator = new WebRTCValidator(); private manager?: WebRTCSessionManager; createSession(plan: WebRTCTransportPlan) { this.manager = new WebRTCSessionManager(plan); return this.manager.create(); } offer(sessionId: string, peerId: string, revision = 0) { return createOfferMetadata({ sessionId, peerId, revision }); } answer(sessionId: string, peerId: string, revision = 0) { return createAnswerMetadata({ sessionId, peerId, revision }); } cleanup() { this.peerConnections.cleanup(); return this.manager?.cleanup(); } }
export const WebRTCSessionManagerFactory = (plan: WebRTCTransportPlan) => new WebRTCSessionManager(plan);
export const PeerConnectionManagerFactory = () => new PeerConnectionManager();
export const WebRTCStatisticsRuntime = Object.freeze({ collectWebRTCStatistics, summarizeConnectionQuality });
export const WebRTCRecoveryRuntime = Object.freeze({ planWebRTCRecovery });
export const WebRTCValidatorRuntime = Object.freeze({ validateWebRTCSignalingMetadata, validateWebRTCPeerId });
