import { HealthStatus, redact } from '../observability/index.js';

export enum PolicyCategory { Production='production', Security='security', Privacy='privacy', DataRetention='data_retention', Recording='recording', Streaming='streaming', Content='content', Social='social', Accessibility='accessibility', Emergency='emergency', Operational='operational', ChangeManagement='change_management', IncidentResponse='incident_response', Backup='backup', DisasterRecovery='disaster_recovery', Vendor='vendor', Financial='financial', Contractual='contractual', Regulatory='regulatory', AI='ai', Custom='custom' }
export enum PolicyStatus { Draft='draft', InReview='in_review', Approved='approved', Scheduled='scheduled', Active='active', Suspended='suspended', Superseded='superseded', Retired='retired' }
export enum PolicyEnforcementMode { DocumentOnly='document_only', Observe='observe', Warn='warn', RequireAcknowledgement='require_acknowledgement', RequireApproval='require_approval', Block='block', AutomaticRemediation='automatic_remediation' }
export enum RequirementSeverity { Advisory='advisory', Low='low', Moderate='moderate', High='high', Critical='critical' }
export enum ControlCategory { Preventive='preventive', Detective='detective', Corrective='corrective', Directive='directive', Recovery='recovery', Compensating='compensating' }
export enum ControlImplementationType { Technical='technical', Procedural='procedural', Administrative='administrative', Physical='physical', Contractual='contractual', Hybrid='hybrid' }
export enum ControlFrequency { Continuous='continuous', PerProduction='per_production', Daily='daily', Weekly='weekly', Monthly='monthly', Quarterly='quarterly', Annual='annual', OnChange='on_change', OnIncident='on_incident' }
export enum ControlAutomationLevel { Manual='manual', Assisted='assisted', SemiAutomated='semi_automated', Automated='automated', Continuous='continuous' }
export enum ControlStatus { Planned='planned', Implemented='implemented', Operating='operating', Degraded='degraded', Failed='failed', Suspended='suspended', Retired='retired' }
export enum ControlTestMethod { AutomatedQuery='automated_query', StateValidation='state_validation', ConfigurationInspection='configuration_inspection', SyntheticTest='synthetic_test', EvidenceReview='evidence_review', OperatorAttestation='operator_attestation', ManualInspection='manual_inspection', ExternalVerification='external_verification' }
export enum ControlTestStatus { Passed='passed', PassedWithWarnings='passed_with_warnings', Failed='failed', NotApplicable='not_applicable', Inconclusive='inconclusive', NotTested='not_tested' }
export enum EvidenceType { AuditRecord='audit_record', Metric='metric', Log='log', Trace='trace', ConfigurationSnapshot='configuration_snapshot', ApprovalRecord='approval_record', RecordingManifest='recording_manifest', BackupVerification='backup_verification', IncidentRecord='incident_record', AccessReview='access_review', PolicyAttestation='policy_attestation', Screenshot='screenshot', ExternalReport='external_report', ManualDocument='manual_document' }
export enum EvidenceStatus { Current='current', Expiring='expiring', Expired='expired', Invalid='invalid', Missing='missing', UnderReview='under_review' }
export enum AttestationStatus { Draft='draft', Submitted='submitted', Approved='approved', Rejected='rejected', Expired='expired', Revoked='revoked' }
export enum ComplianceStatus { Compliant='compliant', CompliantWithExceptions='compliant_with_exceptions', PartiallyCompliant='partially_compliant', NonCompliant='non_compliant', NotApplicable='not_applicable', Unknown='unknown' }
export enum FindingStatus { Open='open', Assigned='assigned', Remediating='remediating', Monitoring='monitoring', Resolved='resolved', Accepted='accepted', Closed='closed' }
export enum RiskCategory { Operational='operational', Security='security', Privacy='privacy', Financial='financial', Legal='legal', Vendor='vendor', Reputation='reputation', Safety='safety', Compliance='compliance', Technical='technical' }
export enum RiskStatus { Identified='identified', Assessed='assessed', Treating='treating', Accepted='accepted', Monitoring='monitoring', Closed='closed' }
export enum RiskTreatmentType { Avoid='avoid', Mitigate='mitigate', Transfer='transfer', Accept='accept', Monitor='monitor' }
export enum ExceptionStatus { Requested='requested', Approved='approved', Rejected='rejected', Active='active', Expired='expired', Revoked='revoked' }
export enum CorrectiveActionStatus { Open='open', InProgress='in_progress', Verification='verification', Closed='closed', Overdue='overdue' }
export enum FrameworkStatus { Draft='draft', Active='active', Superseded='superseded', Retired='retired' }
export enum MappingType { Full='full', Partial='partial', Supporting='supporting', Compensating='compensating', NotApplicable='not_applicable' }
export enum ObligationStatus { Pending='pending', Active='active', Completed='completed', Overdue='overdue', Waived='waived', Cancelled='cancelled' }
export enum GovernanceGateDecision { Allow='allow', Warn='warn', RequireAcknowledgement='require_acknowledgement', RequireApproval='require_approval', Block='block', Remediate='remediate' }

export interface PolicyApplicability { organizationIds?:string[]; customerIds?:string[]; productionIds?:string[]; productionTypes?:string[]; environments?:string[]; siteIds?:string[]; regions?:string[]; destinationTypes?:string[]; contentClassifications?:string[]; operatorRoleIds?:string[]; contractIds?:string[]; effectiveConditions?: { field:string; equals?:unknown; includes?:unknown }[]; }
export interface PolicySubject { subjectType:string; subjectId:string; organizationId?:string; customerId?:string; productionId?:string; productionType?:string; environment?:string; siteId?:string; region?:string; destinationType?:string; contentClassification?:string; operatorRoleId?:string; contractId?:string; attributes?:Record<string,unknown>; }
export interface EvidenceRequirement { type:EvidenceType; maximumAgeMs?:number; minimumCount?:number; integrityRequired:boolean; approvalRequired?:boolean; }
export interface PolicyRequirement { id:string; name:string; description:string; controlIds:string[]; severity:RequirementSeverity; required:boolean; exceptionAllowed:boolean; evidenceRequirements?:EvidenceRequirement[]; }
export interface GovernancePolicy { id:string; name:string; description:string; category:PolicyCategory; ownerId:string; status:PolicyStatus; priority:number; applicability:PolicyApplicability; requirements:PolicyRequirement[]; enforcementMode:PolicyEnforcementMode; effectiveFrom:number; effectiveTo?:number; version:number; createdAt:number; updatedAt:number; previousVersion?:number; approvedBy?:string; }
export interface GovernanceControl { id:string; name:string; description:string; category:ControlCategory; ownerId:string; implementationType:ControlImplementationType; frequency:ControlFrequency; automationLevel:ControlAutomationLevel; testIds:string[]; evidenceSources:string[]; status:ControlStatus; version:number; customerId?:string; }
export interface ControlTest { id:string; controlId:string; name:string; description:string; method:ControlTestMethod; schedule?:string; expectedResult:string; failureSeverity:RequirementSeverity; enabled:boolean; }
export interface ControlTestResult { id:string; controlId:string; testId:string; status:ControlTestStatus; testedAt:number; testedBy?:string; evidenceIds:string[]; findings:string[]; confidence:number; nextTestAt?:number; }
export interface ControlEvidence { id:string; controlId:string; type:EvidenceType; source:string; collectedAt:number; periodStart?:number; periodEnd?:number; referenceId?:string; integrityHash?:string; status:EvidenceStatus; metadata?:Record<string,unknown>; customerId?:string; }
export interface ControlAttestation { id:string; controlId:string; attestedBy:string; attestedAt:number; statement:string; periodStart:number; periodEnd:number; evidenceIds:string[]; status:AttestationStatus; }
export interface FrameworkRequirement { id:string; reference:string; title:string; description:string; controlIds:string[]; evidenceRequirements?:EvidenceRequirement[]; }
export interface ComplianceFramework { id:string; name:string; description?:string; issuer?:string; version:string; requirements:FrameworkRequirement[]; effectiveFrom?:number; effectiveTo?:number; status:FrameworkStatus; }
export interface FrameworkMapping { controlId:string; frameworkId:string; requirementIds:string[]; mappingType:MappingType; notes?:string; verifiedBy?:string; verifiedAt?:number; }
export interface ComplianceFinding { id:string; requirementId:string; controlId?:string; severity:RequirementSeverity; title:string; description:string; detectedAt:number; status:FindingStatus; ownerId?:string; correctiveActionIds:string[]; exceptionId?:string; }
export interface ComplianceEvaluationResult { id:string; subjectType:string; subjectId:string; policyId?:string; frameworkId?:string; status:ComplianceStatus; score:number; confidence:number; evaluatedAt:number; passedRequirementIds:string[]; failedRequirementIds:string[]; exceptionIds:string[]; missingEvidenceIds:string[]; findings:ComplianceFinding[]; }
export interface RiskAssessment { likelihood:number; impact:number; inherentScore:number; residualScore:number; assessedAt:number; assessedBy:string; }
export interface GovernanceRisk { id:string; title:string; description:string; category:RiskCategory; ownerId:string; status:RiskStatus; subjectType?:string; subjectId?:string; assessment:RiskAssessment; appetiteThreshold:number; treatment?:RiskTreatmentType; acceptedBy?:string; acceptedUntil?:number; evidenceIds:string[]; }
export interface ExceptionRequest { id:string; policyId:string; requirementId:string; subjectType:string; subjectId:string; requestedBy:string; reason:string; riskScore:number; compensatingControlIds:string[]; requestedAt:number; expiresAt:number; approvedBy?:string; status:ExceptionStatus; }
export interface GovernanceCorrectiveAction { id:string; title:string; description:string; sourceType:string; sourceId:string; ownerId:string; priority:string; dueAt?:number; verificationCriteria:string[]; evidenceIds:string[]; status:CorrectiveActionStatus; }
export interface GovernanceObligation { id:string; sourceType:string; sourceId:string; triggerCondition:string; action:string; dueAfterMs:number; ownerRoleIds:string[]; status:ObligationStatus; triggeredAt?:number; dueAt?:number; }
export interface GovernanceGateResult { decision:GovernanceGateDecision; subjectId:string; evaluatedAt:number; evaluationIds:string[]; rationale:string[]; requiredApprovalIds:string[]; correctiveActionIds:string[]; }
export interface GovernanceSnapshot { policies:GovernancePolicy[]; controls:GovernanceControl[]; tests:ControlTest[]; testResults:ControlTestResult[]; evidence:ControlEvidence[]; attestations:ControlAttestation[]; frameworks:ComplianceFramework[]; mappings:FrameworkMapping[]; evaluations:ComplianceEvaluationResult[]; risks:GovernanceRisk[]; exceptions:ExceptionRequest[]; correctiveActions:GovernanceCorrectiveAction[]; obligations:GovernanceObligation[]; audit:string[]; health:{status:HealthStatus; score:number; reasons:string[]}; telemetry:{activePolicies:number; failedControls:number; openFindings:number; highRisks:number; activeExceptions:number; complianceScore:number}; }

const severityRank:Record<RequirementSeverity,number>={[RequirementSeverity.Advisory]:10,[RequirementSeverity.Low]:25,[RequirementSeverity.Moderate]:50,[RequirementSeverity.High]:75,[RequirementSeverity.Critical]:100};
const clone=<T>(value:T):T=>structuredClone(value); const freeze=<T>(value:T):T=>Object.freeze(clone(value)); const bounded=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const matches=(allowed:string[]|undefined, value:string|undefined)=>!allowed?.length || (value!==undefined && allowed.includes(value));
export function policyApplies(policy:GovernancePolicy, subject:PolicySubject, at:number):boolean{ if(policy.status!==PolicyStatus.Active && policy.status!==PolicyStatus.Approved) return false; if(policy.effectiveFrom>at || (policy.effectiveTo!==undefined && policy.effectiveTo<at)) return false; const a=policy.applicability; if(!matches(a.organizationIds,subject.organizationId)||!matches(a.customerIds,subject.customerId)||!matches(a.productionIds,subject.productionId)||!matches(a.productionTypes,subject.productionType)||!matches(a.environments,subject.environment)||!matches(a.siteIds,subject.siteId)||!matches(a.regions,subject.region)||!matches(a.destinationTypes,subject.destinationType)||!matches(a.contentClassifications,subject.contentClassification)||!matches(a.operatorRoleIds,subject.operatorRoleId)||!matches(a.contractIds,subject.contractId)) return false; return (a.effectiveConditions??[]).every(c=> c.equals!==undefined ? subject.attributes?.[c.field]===c.equals : Array.isArray(subject.attributes?.[c.field]) && (subject.attributes?.[c.field] as unknown[]).includes(c.includes)); }
export function scoreRisk(likelihood:number, impact:number):number{ return bounded((Math.max(1,Math.min(5,likelihood))*Math.max(1,Math.min(5,impact)))*4); }
export class GovernanceRiskComplianceEngine { #policies=new Map<string,GovernancePolicy>(); #controls=new Map<string,GovernanceControl>(); #tests=new Map<string,ControlTest>(); #results:ControlTestResult[]=[]; #evidence=new Map<string,ControlEvidence>(); #attestations=new Map<string,ControlAttestation>(); #frameworks=new Map<string,ComplianceFramework>(); #mappings:FrameworkMapping[]=[]; #evaluations:ComplianceEvaluationResult[]=[]; #risks=new Map<string,GovernanceRisk>(); #exceptions=new Map<string,ExceptionRequest>(); #actions=new Map<string,GovernanceCorrectiveAction>(); #obligations=new Map<string,GovernanceObligation>(); #audit:string[]=[]; constructor(private readonly maxHistory=20000){}
  registerPolicy(policy:GovernancePolicy):GovernancePolicy{ const existing=this.#policies.get(policy.id); if(existing && policy.version<=existing.version) throw new Error('policy version must increase'); const safe={...policy,name:String(redact(policy.name)),description:String(redact(policy.description)),ownerId:String(redact(policy.ownerId)),approvedBy:policy.approvedBy?String(redact(policy.approvedBy)):undefined}; this.#policies.set(policy.id,freeze(safe)); this.#audit.push(`PolicyRegistered:${policy.id}:v${policy.version}:${policy.status}`); return clone(safe); }
  activatePolicy(id:string, at:number, approvedBy:string):GovernancePolicy{ const p=this.#policies.get(id); if(!p) throw new Error('unknown policy'); if(p.status!==PolicyStatus.Approved && p.status!==PolicyStatus.Scheduled) throw new Error('only approved policy versions can activate'); const updated={...p,status:PolicyStatus.Active,updatedAt:at,approvedBy:String(redact(approvedBy))}; this.#policies.set(id,freeze(updated)); this.#audit.push(`PolicyActivated:${id}:v${p.version}`); return clone(updated); }
  suspendPolicy(id:string, at:number, reason:string):GovernancePolicy{ const p=this.#policies.get(id); if(!p) throw new Error('unknown policy'); const updated={...p,status:PolicyStatus.Suspended,updatedAt:at,description:`${p.description} | suspension: ${String(redact(reason))}`}; this.#policies.set(id,freeze(updated)); this.#audit.push(`PolicySuspended:${id}`); return clone(updated); }
  registerControl(control:GovernanceControl):void{ this.#controls.set(control.id,freeze({...control,name:String(redact(control.name)),description:String(redact(control.description)),ownerId:String(redact(control.ownerId))})); this.#audit.push(`ControlRegistered:${control.id}:${control.status}`); }
  registerTest(test:ControlTest):void{ if(!this.#controls.has(test.controlId)) throw new Error('unknown control'); this.#tests.set(test.id,freeze(test)); this.#audit.push(`ControlTestRegistered:${test.id}:${test.method}`); }
  recordTestResult(result:ControlTestResult):void{ if(!this.#controls.has(result.controlId)||!this.#tests.has(result.testId)) throw new Error('unknown control test'); this.#results.push(freeze(result)); this.#results=this.#results.slice(-this.maxHistory); this.#audit.push(`ControlTestResult:${result.testId}:${result.status}`); }
  collectEvidence(evidence:ControlEvidence):ControlEvidence{ if(this.#evidence.has(evidence.id)) throw new Error('evidence is immutable'); const safe={...evidence,source:String(redact(evidence.source)),referenceId:evidence.referenceId?String(redact(evidence.referenceId)):undefined,metadata:redact(evidence.metadata??{}) as Record<string,unknown>}; this.#evidence.set(evidence.id,freeze(safe)); this.#audit.push(`EvidenceCollected:${evidence.id}:${evidence.status}`); return clone(safe); }
  attest(attestation:ControlAttestation):void{ if(!this.#controls.has(attestation.controlId)) throw new Error('unknown control'); this.#attestations.set(attestation.id,freeze({...attestation,attestedBy:String(redact(attestation.attestedBy)),statement:String(redact(attestation.statement))})); this.#audit.push(`ControlAttested:${attestation.id}:${attestation.status}`); }
  registerFramework(framework:ComplianceFramework):void{ this.#frameworks.set(framework.id,freeze(framework)); this.#audit.push(`FrameworkRegistered:${framework.id}:${framework.version}`); }
  mapFramework(mapping:FrameworkMapping):void{ if(!this.#controls.has(mapping.controlId)||!this.#frameworks.has(mapping.frameworkId)) throw new Error('unknown framework mapping target'); this.#mappings.push(freeze({...mapping,notes:mapping.notes?String(redact(mapping.notes)):undefined,verifiedBy:mapping.verifiedBy?String(redact(mapping.verifiedBy)):undefined})); this.#audit.push(`FrameworkMapped:${mapping.controlId}:${mapping.frameworkId}:${mapping.mappingType}`); }
  assessRisk(risk:GovernanceRisk):GovernanceRisk{ const inherent=scoreRisk(risk.assessment.likelihood,risk.assessment.impact); const residual=bounded(risk.assessment.residualScore || inherent); const safe={...risk, title:String(redact(risk.title)), description:String(redact(risk.description)), ownerId:String(redact(risk.ownerId)), assessment:{...risk.assessment,inherentScore:inherent,residualScore:residual,assessedBy:String(redact(risk.assessment.assessedBy))}}; this.#risks.set(risk.id,freeze(safe)); this.#audit.push(`RiskAssessed:${risk.id}:${residual}`); return clone(safe); }
  requestException(request:ExceptionRequest):ExceptionRequest{ if(request.approvedBy && request.approvedBy===request.requestedBy && request.riskScore>=75) throw new Error('high-risk exception cannot be self-approved'); const safe={...request,requestedBy:String(redact(request.requestedBy)),approvedBy:request.approvedBy?String(redact(request.approvedBy)):undefined,reason:String(redact(request.reason))}; this.#exceptions.set(request.id,freeze(safe)); this.#audit.push(`ExceptionRecorded:${request.id}:${request.status}`); return clone(safe); }
  expireExceptions(at:number):number{ let count=0; for(const [id,e] of this.#exceptions) if((e.status===ExceptionStatus.Active||e.status===ExceptionStatus.Approved)&&e.expiresAt<=at){ this.#exceptions.set(id,freeze({...e,status:ExceptionStatus.Expired})); count++; } if(count) this.#audit.push(`ExceptionsExpired:${count}`); return count; }
  createCorrectiveAction(action:GovernanceCorrectiveAction):void{ this.#actions.set(action.id,freeze({...action,title:String(redact(action.title)),description:String(redact(action.description)),ownerId:String(redact(action.ownerId))})); this.#audit.push(`CorrectiveActionCreated:${action.id}:${action.status}`); }
  registerObligation(obligation:GovernanceObligation):void{ this.#obligations.set(obligation.id,freeze(obligation)); this.#audit.push(`ObligationRegistered:${obligation.id}:${obligation.status}`); }
  evaluate(subject:PolicySubject, at:number):ComplianceEvaluationResult[]{ this.expireExceptions(at); const applicable=[...this.#policies.values()].filter(p=>policyApplies(p,subject,at)).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id)); return applicable.map(policy=>this.#evaluatePolicy(policy,subject,at)); }
  gate(subject:PolicySubject, at:number):GovernanceGateResult{ const evals=this.evaluate(subject,at); const rationale:string[]=[]; let decision=GovernanceGateDecision.Allow; for(const e of evals){ if(e.status===ComplianceStatus.NonCompliant||e.status===ComplianceStatus.PartiallyCompliant||e.status===ComplianceStatus.Unknown){ const p=this.#policies.get(e.policyId??''); if(p?.enforcementMode===PolicyEnforcementMode.Block) decision=GovernanceGateDecision.Block; else if(p?.enforcementMode===PolicyEnforcementMode.RequireApproval) decision=decision===GovernanceGateDecision.Block?decision:GovernanceGateDecision.RequireApproval; else if(p?.enforcementMode===PolicyEnforcementMode.RequireAcknowledgement) decision=decision===GovernanceGateDecision.Allow?GovernanceGateDecision.RequireAcknowledgement:decision; else if(p?.enforcementMode===PolicyEnforcementMode.Warn) decision=decision===GovernanceGateDecision.Allow?GovernanceGateDecision.Warn:decision; rationale.push(`${e.policyId}:${e.status}:${e.failedRequirementIds.join(',')}`); } }
    const highRisks=[...this.#risks.values()].filter(r=>r.subjectId===subject.subjectId&&r.status!==RiskStatus.Closed&&r.assessment.residualScore>r.appetiteThreshold); if(highRisks.length && decision!==GovernanceGateDecision.Block) decision=GovernanceGateDecision.RequireApproval; return {decision,subjectId:subject.subjectId,evaluatedAt:at,evaluationIds:evals.map(e=>e.id),rationale:[...rationale,...highRisks.map(r=>`risk-above-appetite:${r.id}`)],requiredApprovalIds:highRisks.map(r=>r.id),correctiveActionIds:[...this.#actions.values()].filter(a=>a.status!==CorrectiveActionStatus.Closed).map(a=>a.id)}; }
  snapshot():GovernanceSnapshot{ return clone({policies:[...this.#policies.values()].sort((a,b)=>a.id.localeCompare(b.id)),controls:[...this.#controls.values()].sort((a,b)=>a.id.localeCompare(b.id)),tests:[...this.#tests.values()].sort((a,b)=>a.id.localeCompare(b.id)),testResults:[...this.#results],evidence:[...this.#evidence.values()].sort((a,b)=>a.id.localeCompare(b.id)),attestations:[...this.#attestations.values()].sort((a,b)=>a.id.localeCompare(b.id)),frameworks:[...this.#frameworks.values()].sort((a,b)=>a.id.localeCompare(b.id)),mappings:[...this.#mappings],evaluations:[...this.#evaluations].slice(-this.maxHistory),risks:[...this.#risks.values()].sort((a,b)=>a.id.localeCompare(b.id)),exceptions:[...this.#exceptions.values()].sort((a,b)=>a.id.localeCompare(b.id)),correctiveActions:[...this.#actions.values()].sort((a,b)=>a.id.localeCompare(b.id)),obligations:[...this.#obligations.values()].sort((a,b)=>a.id.localeCompare(b.id)),audit:this.#audit.slice(-this.maxHistory),health:this.health(),telemetry:this.telemetry()}); }
  health(){ const t=this.telemetry(); const reasons=[...(t.failedControls?[`${t.failedControls} failed controls`]:[]),...(t.highRisks?[`${t.highRisks} risks above appetite`]:[]),...(t.openFindings?[`${t.openFindings} open findings`]:[])]; return {status:reasons.length?HealthStatus.Warning:HealthStatus.Healthy,score:reasons.length?bounded(100-reasons.length*15):100,reasons}; }
  telemetry(){ const latest=this.#evaluations.slice(-100); const failedControls=[...this.#controls.values()].filter(c=>c.status===ControlStatus.Failed).length; const openFindings=latest.flatMap(e=>e.findings).filter(f=>f.status!==FindingStatus.Closed&&f.status!==FindingStatus.Resolved).length; const highRisks=[...this.#risks.values()].filter(r=>r.status!==RiskStatus.Closed&&r.assessment.residualScore>r.appetiteThreshold).length; const score=latest.length?bounded(latest.reduce((s,e)=>s+e.score,0)/latest.length):100; return {activePolicies:[...this.#policies.values()].filter(p=>p.status===PolicyStatus.Active).length,failedControls,openFindings,highRisks,activeExceptions:[...this.#exceptions.values()].filter(e=>e.status===ExceptionStatus.Active||e.status===ExceptionStatus.Approved).length,complianceScore:score}; }
  #evaluatePolicy(policy:GovernancePolicy, subject:PolicySubject, at:number):ComplianceEvaluationResult{ const passed:string[]=[]; const failed:string[]=[]; const exceptionIds:string[]=[]; const missingEvidenceIds:string[]=[]; const findings:ComplianceFinding[]=[]; let score=100; let confidence=100; for(const req of policy.requirements){ const controls=req.controlIds.map(id=>this.#controls.get(id)).filter((c):c is GovernanceControl=>Boolean(c)); const activeException=[...this.#exceptions.values()].find(e=>e.policyId===policy.id&&e.requirementId===req.id&&e.subjectId===subject.subjectId&&(e.status===ExceptionStatus.Active||e.status===ExceptionStatus.Approved)&&e.expiresAt>at); const controlsOk=controls.length>0 && controls.every(c=>c.status===ControlStatus.Operating||c.status===ControlStatus.Implemented); const testsOk=controls.every(c=>this.#latestResult(c.id)?.status===ControlTestStatus.Passed || this.#latestResult(c.id)?.status===ControlTestStatus.PassedWithWarnings); const evidenceOk=(req.evidenceRequirements??[]).every(er=>this.#evidenceFor(controls.map(c=>c.id),er,at).length >= (er.minimumCount??1)); if(controlsOk && testsOk && evidenceOk){ passed.push(req.id); continue; } if(activeException&&req.exceptionAllowed){ exceptionIds.push(activeException.id); score-=Math.max(5,severityRank[req.severity]*0.1); confidence-=10; continue; } failed.push(req.id); const missingId=`missing:${policy.id}:${req.id}`; missingEvidenceIds.push(missingId); const finding={id:`finding:${policy.id}:${req.id}:${at}`,requirementId:req.id,controlId:req.controlIds[0],severity:req.severity,title:`Requirement not satisfied: ${req.name}`,description:req.description,detectedAt:at,status:FindingStatus.Open,correctiveActionIds:[]}; findings.push(finding); score-=severityRank[req.severity]; confidence-=25; }
    const status=failed.some(id=>policy.requirements.find(r=>r.id===id)?.severity===RequirementSeverity.Critical)?ComplianceStatus.NonCompliant:failed.length?ComplianceStatus.PartiallyCompliant:exceptionIds.length?ComplianceStatus.CompliantWithExceptions:ComplianceStatus.Compliant; const result={id:`eval:${policy.id}:${subject.subjectId}:${at}`,subjectType:subject.subjectType,subjectId:subject.subjectId,policyId:policy.id,status,score:bounded(score),confidence:bounded(confidence),evaluatedAt:at,passedRequirementIds:passed,failedRequirementIds:failed,exceptionIds,missingEvidenceIds,findings}; this.#evaluations.push(freeze(result)); this.#evaluations=this.#evaluations.slice(-this.maxHistory); this.#audit.push(`PolicyEvaluated:${policy.id}:${subject.subjectId}:${status}`); return clone(result); }
  #latestResult(controlId:string):ControlTestResult|undefined{ return [...this.#results].filter(r=>r.controlId===controlId).sort((a,b)=>b.testedAt-a.testedAt||b.id.localeCompare(a.id))[0]; }
  #evidenceFor(controlIds:string[], requirement:EvidenceRequirement, at:number):ControlEvidence[]{ return [...this.#evidence.values()].filter(e=>controlIds.includes(e.controlId)&&e.type===requirement.type&&e.status===EvidenceStatus.Current&&(!requirement.integrityRequired||Boolean(e.integrityHash))&&(requirement.maximumAgeMs===undefined||at-e.collectedAt<=requirement.maximumAgeMs)); }
}
