/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
const assert={ok(v:any,m='assert'){if(!v)throw new Error(m)},equal(a:any,b:any,m=''){if(a!==b)throw new Error(`${m} ${a} !== ${b}`)},throws(fn:any,m='expected throw'){let t=false;try{fn()}catch{t=true}if(!t)throw new Error(m)},deepEqual(a:any,b:any,m=''){const ja=JSON.stringify(a),jb=JSON.stringify(b);if(ja!==jb)throw new Error(`${m} ${ja} !== ${jb}`)}};
import { AudioLoudnessMeteringProcessor, createAudioLoudnessMeteringEngine, createSyntheticAudioMeteringBackend, AUDIO_METERING_COMMAND_TYPES } from './audio-loudness-metering.js';
const target=(type:string,id:string,gen=1)=>({targetType:type,targetId:id,targetGeneration:gen,safeMetadata:{}});
const meter=(id:string,type:string,t:any)=>({meterId:id,meterType:type,target:t,measurementWindow:{type:'PER_BLOCK'},clipThreshold:.98,silenceThreshold:.00001,lowLevelThreshold:.02,weightingPolicy:'NONE'});
const make=()=>{const e=createAudioLoudnessMeteringEngine('validation');e.registerBackend(createSyntheticAudioMeteringBackend());return e};
const req=(e:any,id='req1',block=1,targets=[target('PROGRAM_BUS','program'),target('PREVIEW_BUS','preview')])=>({requestId:id,runtimeFrame:String(block),blockSequence:block,samplePosition:block*480,sampleCount:480,targetReferences:targets,inputBufferSummaries:[],outputBufferSummaries:[],expectedMeterGenerations:Object.fromEntries([...e.meters.values()].map((m:any)=>[m.meterId,m.meterGeneration])),expectedTargetGenerations:Object.fromEntries(targets.map((t:any)=>[t.targetId,t.targetGeneration])),expectedMixerGeneration:1,expectedEqDynamicsGeneration:1,expectedRoutingGeneration:1,expectedBackendGeneration:1,deadlineNs:'0',safeMetadata:{}});

for(let i=1;i<=135;i++){
 const e=make(); assert.ok(e.snapshot().events.includes('AudioMeteringEngineCreated'),'engine creation'); assert.throws(()=>e.registerBackend(createSyntheticAudioMeteringBackend()),'duplicate backend rejection');
 const program=target('PROGRAM_BUS','program'), preview=target('PREVIEW_BUS','preview'), aux=target('AUX_BUS','aux'), clean=target('CLEAN_FEED_BUS','clean'), mon=target('MONITOR_BUS','monitor'), rec=target('RECORD_BUS','record'), stream=target('STREAM_BUS','stream'), chan=target('CHANNEL','channel-1'), neg=target('PROGRAM_BUS','phase-negative-program');
 const defs=[meter('peak','SAMPLE_PEAK',program),meter('held','HELD_PEAK',program),meter('rms','RMS',program),meter('avg','AVERAGE_LEVEL',program),meter('mom','MOMENTARY_LOUDNESS',program),meter('st','SHORT_TERM_LOUDNESS',program),meter('int','INTEGRATED_LOUDNESS_FOUNDATION',program),meter('lra','LOUDNESS_RANGE_FOUNDATION',program),meter('tp','TRUE_PEAK_METADATA',program),meter('clip','CLIPPING',program),meter('sil','SILENCE',program),meter('low','LOW_LEVEL',program),meter('dc','DC_OFFSET_METADATA',program),meter('phase','PHASE_CORRELATION',neg),meter('corr','CHANNEL_CORRELATION',neg),meter('mono','MONO_COMPATIBILITY_METADATA',program),meter('gr','GAIN_REDUCTION',program),meter('gate','GATE_STATE',program),meter('comp','COMPRESSOR_ACTIVITY',program),meter('lim','LIMITER_ACTIVITY',program),meter('act','CHANNEL_ACTIVITY',chan),meter('prev','SAMPLE_PEAK',preview),meter('aux','RMS',aux),meter('clean','RMS',clean),meter('mon','RMS',mon),meter('rec','RMS',rec),meter('stream','RMS',stream)];
 defs.forEach(d=>e.registerMeter(d as any)); assert.throws(()=>e.registerMeter(defs[0] as any),'duplicate meter'); assert.ok(Object.isFrozen(e.meters.get('peak')),'meter immutable');
 const old=e.meters.get('peak'); const upd=e.updateMeter('peak',{expectedGeneration:old.meterGeneration,displayName:'Peak 2',measurementWindow:{type:'FIXED_SAMPLE_COUNT',sampleCount:480},clipThreshold:.98,silenceThreshold:.00001,lowLevelThreshold:.02}); assert.equal(upd.meterGeneration,2,'generation update'); assert.throws(()=>e.updateMeter('peak',{expectedGeneration:1,clipThreshold:.5,silenceThreshold:.1,lowLevelThreshold:.2,measurementWindow:{type:'PER_BLOCK'}}),'stale update rejection');
 assert.throws(()=>e.registerMeter({...meter('bad-window','RMS',program),measurementWindow:{type:'HIDDEN'}} as any),'invalid window'); assert.throws(()=>e.registerMeter({...meter('bad-thresh','RMS',program),silenceThreshold:.5,lowLevelThreshold:.1} as any),'invalid threshold');
 e.createSession({sessionId:'s1',target:program,profile:i%3===0?'EBU_R128_FOUNDATION':i%3===1?'ATSC_A85_FOUNDATION':'ITU_R_BS_1770_FOUNDATION'}); e.setSessionState('s1','RUNNING',0); e.setSessionState('s1','PAUSED',480); e.setSessionState('s1','RUNNING',960); e.setSessionState('s1','COMPLETED',1440); e.setSessionState('s1','RESET',1440);
 const r=e.processBlock(req(e,'r1',1,[program,preview,aux,clean,mon,rec,stream,chan,neg])); assert.equal(r.status,'COMPLETED','process request'); assert.ok(r.programMeterSummary.target.targetId==='program','program meter'); assert.ok(r.previewMeterSummary.target.targetId==='preview','preview meter'); assert.ok(r.programMeterSummary!==r.previewMeterSummary,'program preview isolation'); assert.ok(r.realPeakMeasurement&&r.realRmsMeasurement&&!r.realLoudnessMeasurement&&!r.realTruePeakMeasurement,'measurement flags'); assert.ok(r.metadataOnlyMeterIds.includes('tp'),'true peak metadata boundary'); assert.ok(!r.loudnessSummary.complianceClaim,'no compliance claim'); assert.ok(e.states.get('rms').currentValues.some((v:any)=>v.unit==='DBFS'&&Number.isFinite(v.dBFSValue)),'dbfs conversion'); assert.ok(e.states.get('phase').phaseCorrelationState.warning,'negative correlation warning'); assert.throws(()=>e.processBlock(req(e,'r1',2,[program])),'duplicate request'); assert.throws(()=>e.processBlock(req(e,'r2',1,[program])),'duplicate block'); assert.throws(()=>e.processBlock({...req(e,'stale',3,[program]),expectedMeterGenerations:{...req(e,'x',3,[program]).expectedMeterGenerations,peak:999}}),'stale meter generation'); assert.throws(()=>e.processBlock({...req(e,'stale-target',4,[program]),expectedTargetGenerations:{program:999}}),'stale target generation');
 e.configureMonitor({selectedSource:{sourceId:'preview',sourceType:'PREVIEW',sourceGeneration:1,targetBusOrChannelId:'preview',channelSelection:['L','R'],priority:5,enabled:true,safeMetadata:{}},activePflSources:[{sourceId:'pfl',sourceType:'CHANNEL_PFL',sourceGeneration:1,targetBusOrChannelId:'channel-1',channelSelection:['L'],priority:2,enabled:true,safeMetadata:{}}],monitorMute:i%2===0,monitorDim:true,monitorMono:true}); const mr=e.resolveMonitor('1'); assert.equal(mr.effectiveSource.sourceId,'pfl','monitor priority pfl'); assert.ok(mr.realMonitorProcessingApplied===false,'metadata only monitor'); const pre=e.snapshot().states.find((s:any)=>s.meterId==='peak'); e.resetMeter('peak'); assert.ok(!e.states.has('peak'),'held peak reset');
 const tx=e.transaction({transactionId:'tx1',meterUpdates:[],thresholdUpdates:[],monitorSourceUpdates:[],monitorControlUpdates:[],scheduledSamplePosition:999,scheduledRuntimeFrame:'9'}); assert.equal(tx.state,'CREATED','transaction'); assert.equal(e.commitTransaction('tx1').state,'COMMITTED','commit exactly once');
 e.assertInvariants(); const sg=e.sourceGraphMetadata(); assert.ok(!JSON.stringify(sg).match(/pcm|secret|nativeHandle/),'source graph redacted'); const a=JSON.stringify(e.snapshot()); const e2=make(); defs.forEach(d=>e2.registerMeter(d as any)); e2.processBlock(req(e2,'r1',1,[program,preview,aux,clean,mon,rec,stream,chan,neg])); const b=JSON.stringify(e2.snapshot().states); assert.ok(b.length>0&&a.length>0,'determinism snapshots');
 if(i===115){for(let n=0;n<10_000;n++){const en=make(); en.registerMeter(meter('p','SAMPLE_PEAK',program) as any); en.processBlock(req(en,`p${n}`,n+10,[program])); en.assertInvariants();}}
 if(i===120){const procEngine=make(); procEngine.registerMeter(meter('proc','RMS',program) as any); const p=new AudioLoudnessMeteringProcessor(procEngine); assert.equal(p.order,580,'processor order'); for(let n=0;n<100_000;n++)procEngine.processBlock(req(procEngine,`tick${n}`,n+1000,[program])); assert.ok(procEngine.telemetry().blocksCompleted===100000,'processor ticks');}
 const h=e.health(), t=e.telemetry(); assert.ok(h.temporaryBytes===0&&t.temporaryBytes===0,'zero temporary leak'); e.shutdown(); e.shutdown(); assert.equal(e.snapshot().states.length,0,'shutdown clears states'); assert.throws(()=>e.processBlock(req(e,'after-shutdown',999,[program])),'no command after shutdown');
}
assert.ok(AUDIO_METERING_COMMAND_TYPES.length>=30,'commands exported');
console.log('UBOS v5.6.4 loudness/metering/audio monitoring validation passed');
