import { AutomationTriggerSchedulingEngine } from './automation-triggering-scheduling.js';
const assertEqual=(actual:unknown,expected:unknown)=>{ if(actual!==expected) throw new Error(`Expected ${String(expected)} but received ${String(actual)}`); };
const assertThrows=(fn:()=>unknown,pattern:RegExp)=>{ try{ fn(); } catch(error){ if(pattern.test(String(error))) return; throw error; } throw new Error('Expected function to throw'); };
const engine=new AutomationTriggerSchedulingEngine();
const tick=(frameNumber:bigint)=>({frameNumber,startedAtNs:0n,deadlineAtNs:0n,scheduledTimeNs:0n,actualTimeNs:0n,presentationTimeNs:0n,frameDurationNs:0n,driftNs:0n,latenessNs:0n,late:false,missedFrames:0n,discontinuity:false});
engine.registerRule({ruleId:'rule1',generation:1,cueId:'c1',priority:10,metadata:{secretToken:'nope',safe:'ok'},triggers:[{triggerId:'clock',generation:1,kind:'CLOCK',fireAtFrame:10,metadata:{}},{triggerId:'evt',generation:1,kind:'EVENT',eventType:'RundownAdvanced',conditions:[{field:'cueId',operator:'EQUALS',value:'c1'}],metadata:{path:'/tmp/nope'}}]});
assertEqual(engine.snapshot().rules[0]?.metadata.secretToken,undefined);
assertEqual(engine.processFrame(tick(9n)).results[0]?.state,'WAITING');
engine.ingestEvent({eventId:'e1',type:'RundownAdvanced',frame:9,fields:{cueId:'c1',password:'nope'}});
assertEqual(engine.processFrame(tick(10n)).results[0]?.state,'FIRED');
assertEqual(engine.snapshot().telemetry.metadataOnly,true);
assertEqual(engine.snapshot().telemetry.realNetworkControl,false);
assertEqual(engine.ack('rule1').state,'ACKNOWLEDGED');
assertThrows(()=>engine.registerRule({ruleId:'rule1',generation:1,cueId:'c1',priority:1,metadata:{},triggers:[]}),/stale/);
engine.registerRule({ruleId:'rule2',generation:1,cueId:'c2',priority:1,metadata:{},triggers:[{triggerId:'health',generation:1,kind:'HEALTH',eventType:'HealthChanged',conditions:[{field:'status',operator:'EQUALS',value:'warning'}],metadata:{}}]});
engine.ingestEvent({eventId:'e2',type:'HealthChanged',frame:11,fields:{status:'warning'}});
assertEqual(engine.evaluate(11).results.find(r=>r.ruleId==='rule2')?.state,'FIRED');
for(let i=0;i<10000;i++) engine.processFrame(tick(BigInt(12+i)));
assertEqual(engine.snapshot().health.firedCount,2);
console.log('UBOS v5.10.2 automation triggering/scheduling validation passed');
