import { createAutomationRecoveryReplayAuditEngine, createAutomationRecoveryReplayAuditProcessor, AutomationRecoveryReplayAuditError } from './automation-recovery-replay-audit.js';
const assert={equal:(a:unknown,b:unknown)=>{if(a!==b) throw new Error(`Expected ${String(b)} but received ${String(a)}`);},deepEqual:(a:unknown,b:unknown)=>{if(JSON.stringify(a)!==JSON.stringify(b)) throw new Error('Expected values to be deeply equal');},throws:(fn:()=>unknown,errorType:unknown)=>{try{fn();}catch(e){if(e instanceof (errorType as typeof Error)) return; throw e;} throw new Error('Expected function to throw');}};
const tick=(frameNumber:bigint)=>({frameNumber,startedAtNs:0n,deadlineAtNs:0n,scheduledTimeNs:0n,actualTimeNs:0n,presentationTimeNs:0n,frameDurationNs:0n,driftNs:0n,latenessNs:0n,late:false,missedFrames:0n,discontinuity:false});

const engine=createAutomationRecoveryReplayAuditEngine();
engine.recordAuditEvent({eventId:'evt-1',generation:1,frame:10,kind:'CUE',subjectId:'cue-a',actorId:'op-a',action:'TAKE',metadata:{label:'open',token:'redacted'}});
engine.recordAuditEvent({eventId:'evt-2',generation:1,frame:12,kind:'ACTION',subjectId:'action-a',actorId:'system',action:'DISPATCH',metadata:{url:'redacted',role:'pgm'}});
assert.equal(engine.snapshot().auditEvents[0]?.metadata.token,undefined);
assert.throws(()=>engine.recordAuditEvent({eventId:'evt-1',generation:1,frame:10,kind:'CUE',subjectId:'cue-a',actorId:'op-a',action:'TAKE',metadata:{}}),AutomationRecoveryReplayAuditError);
const hash=engine.expectedRecoveryHash('rp-1',10,['evt-1']);
engine.registerRecoveryPoint({recoveryPointId:'rp-1',generation:1,frame:10,kind:'CHECKPOINT',sourceEventIds:['evt-1'],stateHash:hash,metadata:{label:'pre-roll'}});
assert.throws(()=>engine.registerRecoveryPoint({recoveryPointId:'rp-bad',generation:1,frame:10,kind:'SNAPSHOT',sourceEventIds:['evt-1'],stateHash:'bad',metadata:{}}),AutomationRecoveryReplayAuditError);
engine.requestReplay({replayId:'replay-1',generation:1,requestedFrame:20,fromRecoveryPointId:'rp-1',toFrame:12,operatorId:'op-a',requireStepAck:true,metadata:{reason:'operator recovery'}});
let snap=engine.advance(21);
assert.equal(snap.replays[0]?.state,'WAITING_ACK');
assert.deepEqual(snap.replays[0]?.exactOnceReplayDispatches,{'evt-1':1});
engine.advance(22);
assert.deepEqual(engine.snapshot().replays[0]?.exactOnceReplayDispatches,{'evt-1':1});
engine.ackReplayStep('replay-1','evt-1',23);
engine.advance(24);
engine.ackReplayStep('replay-1','evt-2',25);
snap=engine.advance(26);
assert.equal(snap.replays[0]?.state,'COMPLETED');
assert.deepEqual(snap.sourceGraph.replayIds,['replay-1']);
const failed=createAutomationRecoveryReplayAuditEngine();
failed.recordAuditEvent({eventId:'evt-f',generation:1,frame:1,kind:'SYSTEM',subjectId:'sys',actorId:'system',action:'RECOVER',metadata:{}});
failed.registerRecoveryPoint({recoveryPointId:'rp-f',generation:1,frame:1,kind:'SNAPSHOT',sourceEventIds:['evt-f'],stateHash:failed.expectedRecoveryHash('rp-f',1,['evt-f']),metadata:{}});
failed.requestReplay({replayId:'replay-f',generation:1,requestedFrame:2,fromRecoveryPointId:'rp-f',toFrame:1,operatorId:'op',requireStepAck:true,metadata:{}});
failed.advance(3);
failed.failReplayStep('replay-f','evt-f','operator-abort',4);
assert.equal(failed.snapshot().health.failedReplayCount,1);
const processor=createAutomationRecoveryReplayAuditProcessor(engine);
assert.equal(processor.initialize().status,'READY');
for(let i=0;i<1000;i++) processor.processTick(tick(BigInt(30+i)));
assert.equal(processor.shutdown().status,'STOPPED');
console.log('automation recovery replay audit validation passed');
