import { AutomationMacroOperatorOverrideEngine, AutomationMacroOperatorOverrideError, AutomationMacroOperatorOverrideProcessor } from './automation-macro-operator-override.js';
const assertEqual=(actual:unknown,expected:unknown)=>{ if(actual!==expected) throw new Error(`Expected ${String(expected)} but received ${String(actual)}`); };
const assertDeepEqual=(actual:unknown,expected:unknown)=>{ if(JSON.stringify(actual)!==JSON.stringify(expected)) throw new Error('Expected values to be deeply equal'); };
const assertThrows=(fn:()=>unknown,errorType:unknown)=>{ try{ fn(); } catch(error){ if(error instanceof (errorType as typeof Error)) return; throw error; } throw new Error('Expected function to throw'); };
const tick=(frameNumber:bigint)=>({frameNumber,startedAtNs:0n,deadlineAtNs:0n,scheduledTimeNs:0n,actualTimeNs:0n,presentationTimeNs:0n,frameDurationNs:0n,driftNs:0n,latenessNs:0n,late:false,missedFrames:0n,discontinuity:false});
const macro={macroId:'opening-macro',generation:1,priority:10,metadata:{label:'Opening',secretToken:'redacted'},steps:[{stepId:'take-open',kind:'SHOW_CONTROL_ACTION' as const,targetRef:'take-main',delayFrames:0,metadata:{note:'safe'}},{stepId:'notify-director',kind:'NOTIFY' as const,targetRef:'director',delayFrames:0,metadata:{password:'hidden'}}]};
const request={runId:'run-1',macroId:'opening-macro',generation:1,queuedFrame:1,operatorId:'td',payload:{source:'panel',credential:'hidden'}};
const engine=new AutomationMacroOperatorOverrideEngine();
engine.registerMacro(macro);
engine.queueMacro(request);
let snapshot=engine.advance(1);
assertEqual(snapshot.runs[0]?.state,'WAITING_ACK');
assertEqual(snapshot.runs[0]?.exactOnceStepDispatches['take-open'],1);
assertEqual(snapshot.macros[0]?.metadata.secretToken,undefined);
assertEqual(snapshot.runs[0]?.payload.credential,undefined);
snapshot=engine.advance(2);
assertEqual(snapshot.runs[0]?.exactOnceStepDispatches['take-open'],1);
engine.ackStep('run-1','take-open',3);
assertEqual(engine.snapshot().runs[0]?.currentStepIndex,1);
engine.ackStep('run-1','notify-director',4);
assertEqual(engine.snapshot().runs[0]?.state,'COMPLETED');
assertThrows(()=>engine.registerMacro({...macro,generation:1}),AutomationMacroOperatorOverrideError);
assertThrows(()=>engine.queueMacro({...request,runId:'stale',generation:0}),AutomationMacroOperatorOverrideError);
const held=new AutomationMacroOperatorOverrideEngine();
held.registerMacro(macro);
held.queueMacro({...request,runId:'run-held'});
held.setOverride({overrideId:'hold-1',mode:'HOLD',scope:'RUN',targetId:'run-held',operatorId:'td',generation:1,reason:'line-check',setFrame:1});
assertEqual(held.advance(1).runs[0]?.state,'BLOCKED');
held.releaseOverride('hold-1');
assertEqual(held.advance(2).runs[0]?.state,'WAITING_ACK');
const bypass=new AutomationMacroOperatorOverrideEngine();
bypass.registerMacro(macro);
bypass.queueMacro({...request,runId:'run-bypass'});
bypass.setOverride({overrideId:'bypass-1',mode:'BYPASS',scope:'MACRO',targetId:'opening-macro',operatorId:'producer',generation:1,reason:'manual-roll',setFrame:1});
assertEqual(bypass.advance(1).runs[0]?.currentStepIndex,1);
const cancelled=new AutomationMacroOperatorOverrideEngine();
cancelled.registerMacro(macro);
cancelled.queueMacro({...request,runId:'run-cancel'});
cancelled.setOverride({overrideId:'cancel-1',mode:'CANCEL',scope:'GLOBAL',targetId:'all',operatorId:'producer',generation:1,reason:'stop-show',setFrame:1});
assertEqual(cancelled.advance(1).runs[0]?.state,'CANCELLED');
const processorEngine=new AutomationMacroOperatorOverrideEngine();
processorEngine.registerMacro(macro);
processorEngine.queueMacro({...request,runId:'run-processor'});
const processor=new AutomationMacroOperatorOverrideProcessor(processorEngine);
processor.initialize();
processor.processTick(tick(1n));
assertEqual(processorEngine.snapshot().runs[0]?.state,'WAITING_ACK');
processor.shutdown();
const replayA=new AutomationMacroOperatorOverrideEngine();
const replayB=new AutomationMacroOperatorOverrideEngine();
for(const replay of [replayA,replayB]){replay.registerMacro(macro);replay.queueMacro({...request,runId:'run-replay'});replay.advance(1);}
assertDeepEqual(replayA.snapshot().runs,replayB.snapshot().runs);
for(let i=0;i<10000;i++) replayA.processFrame(tick(BigInt(i+10)));
assertEqual(replayA.snapshot().telemetry.realDeviceControl,false);
assertEqual(replayA.snapshot().sourceGraph.metadataOnly,true);
console.log('automation-macro-operator-override validation passed');
