import { DeviceRuntimeAdapter, BrowserMediaDeviceDiscoveryProvider, ScreenCaptureDiscoveryProvider, NetworkSourceDiscoveryProvider, NativeDesktopDiscoveryProvider, CaptureCardDiscoveryProvider, PTZDiscoveryProvider, DeviceDiscoveryManager, DeviceRegistry } from './device-platform.js';
export type RuntimeLifecycleState = 'uninitialized' | 'initializing' | 'initialized' | 'configuring' | 'configured' | 'preparing' | 'prepared' | 'standby' | 'ready' | 'starting' | 'running' | 'pausing' | 'paused' | 'resuming' | 'stopping' | 'stopped' | 'recovering' | 'disposing' | 'disposed' | 'failed';
export type RuntimeHealthStatus = 'Ready' | 'Initializing' | 'Running' | 'Warning' | 'Error' | 'Offline';
export type RuntimeDomain = 'production' | 'device' | 'session' | 'scene' | 'switching' | 'recording' | 'streaming' | 'graphics' | 'replay' | 'audio' | 'automation' | 'health' | 'scheduler' | 'controller';
export type RuntimeCommand = 'initialize' | 'configure' | 'prepare' | 'standby' | 'ready' | 'start' | 'pause' | 'resume' | 'stop' | 'recover' | 'dispose';
export interface RuntimeEvent<T extends string = string, P extends Readonly<Record<string, unknown>> = Readonly<Record<string, unknown>>> { readonly id: string; readonly type: T; readonly domain: RuntimeDomain; readonly timestamp: string; readonly source: string; readonly sequence: number; readonly payload: P; }
export interface RuntimeStateTransition { readonly from: RuntimeLifecycleState; readonly command: RuntimeCommand; readonly to: RuntimeLifecycleState; }
export interface RuntimeSubsystemRegistration { readonly subsystemId: string; readonly domain: RuntimeDomain; readonly dependencies: readonly string[]; readonly startupPriority: number; readonly shutdownPriority: number; readonly healthSource: string; }
export interface RuntimeSubsystemSnapshot { readonly id: string; readonly domain: RuntimeDomain; readonly state: RuntimeLifecycleState; readonly health: RuntimeHealthStatus; readonly revision: number; readonly updatedAt: string; readonly metadata: Readonly<Record<string, string | number | boolean>>; }
export interface RuntimeSubsystem { readonly id: string; readonly domain: RuntimeDomain; readonly registration?: RuntimeSubsystemRegistration | undefined; initialize(): RuntimeSubsystemSnapshot; configure?(): RuntimeSubsystemSnapshot; prepare?(): RuntimeSubsystemSnapshot; standby?(): RuntimeSubsystemSnapshot; ready?(): RuntimeSubsystemSnapshot; start(): RuntimeSubsystemSnapshot; pause(): RuntimeSubsystemSnapshot; resume(): RuntimeSubsystemSnapshot; stop(): RuntimeSubsystemSnapshot; recover?(): RuntimeSubsystemSnapshot; dispose(): RuntimeSubsystemSnapshot; getSnapshot(): RuntimeSubsystemSnapshot; onRecover?(): void; onRestart?(): void; onHealthChange?(health: RuntimeHealthStatus): void; }
export interface RuntimeControllerSnapshot { readonly id: string; readonly state: RuntimeLifecycleState; readonly revision: number; readonly subsystems: readonly RuntimeSubsystemSnapshot[]; readonly registrations: readonly RuntimeSubsystemRegistration[]; readonly dependencyGraph: Readonly<Record<string, readonly string[]>>; readonly startupOrder: readonly string[]; readonly shutdownOrder: readonly string[]; readonly runtimeHealth: RuntimeHealthStatus; readonly startupDurationMs: number; readonly shutdownDurationMs: number; readonly queuedEvents: number; readonly eventCount: number; readonly containsRuntimeHandles: false; }
const now = () => new Date().toISOString();
const targets: Readonly<Record<RuntimeCommand, RuntimeLifecycleState>> = Object.freeze({ initialize: 'initialized', configure: 'configured', prepare: 'prepared', standby: 'standby', ready: 'ready', start: 'running', pause: 'paused', resume: 'running', stop: 'stopped', recover: 'recovering', dispose: 'disposed' });
const allowed: Readonly<Record<RuntimeCommand, readonly RuntimeLifecycleState[]>> = Object.freeze({ initialize: ['uninitialized', 'stopped', 'disposed', 'failed'], configure: ['initialized', 'configured'], prepare: ['configured', 'prepared'], standby: ['prepared', 'ready', 'paused'], ready: ['standby', 'prepared', 'ready'], start: ['ready', 'initialized', 'stopped', 'paused', 'prepared'], pause: ['running'], resume: ['paused'], stop: ['running', 'paused', 'initialized', 'configured', 'prepared', 'standby', 'ready', 'failed'], recover: ['failed', 'stopped', 'paused'], dispose: ['initialized', 'configured', 'prepared', 'standby', 'ready', 'stopped', 'failed', 'uninitialized'] });
function eventId(type: string, sequence: number) { return `runtime:${type}:${sequence}`; }
function assertTransition(state: RuntimeLifecycleState, command: RuntimeCommand, id: string) { if (!allowed[command].includes(state)) throw new Error(`Invalid ${command} transition for ${id} from ${state}`); return targets[command]; }
function sanitize(input: Readonly<Record<string, unknown>> = {}) { return Object.freeze(Object.fromEntries(Object.entries(input).filter(([key, value]) => !/handle|stream|dom|node|socket|process|device|canvas|texture/i.test(key) && ['string', 'number', 'boolean'].includes(typeof value))) as Readonly<Record<string, string | number | boolean>>); }
function healthFor(state: RuntimeLifecycleState): RuntimeHealthStatus { if (state === 'failed') return 'Error'; if (state === 'uninitialized' || state === 'stopped' || state === 'disposed') return 'Offline'; if (state === 'initializing' || state === 'configuring' || state === 'preparing' || state === 'recovering') return 'Initializing'; if (state === 'running') return 'Running'; return 'Ready'; }
export class RuntimeEventBus { private sequence = 0; private events: RuntimeEvent[] = []; private listeners = new Set<(event: RuntimeEvent) => void>(); publish<T extends string>(input: Omit<RuntimeEvent<T>, 'id' | 'timestamp' | 'sequence'>) { const event = Object.freeze({ ...input, id: eventId(input.type, ++this.sequence), timestamp: now(), sequence: this.sequence }); this.events = [...this.events, event]; this.listeners.forEach((listener) => listener(event)); return event; } subscribe(listener: (event: RuntimeEvent) => void) { this.listeners.add(listener); return () => this.listeners.delete(listener); } replay() { return Object.freeze([...this.events]); } get count() { return this.events.length; } }
export class HealthManager { readonly id = 'health-manager'; readonly domain = 'health' as const; private state: RuntimeLifecycleState = 'uninitialized'; private revision = 0; private updatedAt = now(); private health = new Map<string, RuntimeHealthStatus>(); constructor(private readonly bus: RuntimeEventBus) {} initialize() { return this.transition('initialize'); } configure() { return this.transition('configure'); } prepare() { return this.transition('prepare'); } standby() { return this.transition('standby'); } ready() { return this.transition('ready'); } start() { return this.transition('start'); } pause() { return this.transition('pause'); } resume() { return this.transition('resume'); } stop() { return this.transition('stop'); } recover() { return this.transition('recover'); } dispose() { return this.transition('dispose'); } updateSubsystem(id: string, health: RuntimeHealthStatus) { this.health.set(id, health); this.bus.publish({ type: 'HealthChanged', domain: 'health', source: this.id, payload: { subsystemId: id, health } }); } getRuntimeHealth(): RuntimeHealthStatus { const values = [...this.health.values()]; if (values.includes('Error')) return 'Error'; if (values.includes('Warning')) return 'Warning'; if (values.includes('Initializing')) return 'Initializing'; if (values.includes('Running')) return 'Running'; if (values.includes('Ready')) return 'Ready'; return healthFor(this.state); } getSnapshot(): RuntimeSubsystemSnapshot { return Object.freeze({ id: this.id, domain: this.domain, state: this.state, health: this.getRuntimeHealth(), revision: this.revision, updatedAt: this.updatedAt, metadata: Object.freeze({ trackedSubsystems: this.health.size }) }); } private transition(command: RuntimeCommand) { const from = this.state; this.state = assertTransition(from, command, this.id); this.revision += 1; this.updatedAt = now(); const snapshot = this.getSnapshot(); this.bus.publish({ type: `runtime.health.${command}`, domain: 'health', source: this.id, payload: { from, to: this.state, revision: this.revision } }); return snapshot; } }
export class RuntimeStateMachine implements RuntimeSubsystem { private state: RuntimeLifecycleState = 'uninitialized'; private revision = 0; private updatedAt = now(); constructor(readonly id: string, readonly domain: RuntimeDomain, private readonly bus: RuntimeEventBus, private readonly metadata: Readonly<Record<string, unknown>> = {}, readonly registration?: RuntimeSubsystemRegistration) {} initialize() { return this.transition('initialize'); } configure() { return this.transition('configure'); } prepare() { return this.transition('prepare'); } standby() { return this.transition('standby'); } ready() { return this.transition('ready'); } start() { return this.transition('start'); } pause() { return this.transition('pause'); } resume() { return this.transition('resume'); } stop() { return this.transition('stop'); } recover() { this.onRecover?.(); return this.transition('recover'); } dispose() { return this.transition('dispose'); } onRecover?(): void; onRestart?(): void; onHealthChange?(health: RuntimeHealthStatus): void; getSnapshot(): RuntimeSubsystemSnapshot { return Object.freeze({ id: this.id, domain: this.domain, state: this.state, health: healthFor(this.state), revision: this.revision, updatedAt: this.updatedAt, metadata: sanitize(this.metadata) }); } private transition(command: RuntimeCommand) { const from = this.state; const to = assertTransition(from, command, this.id); this.state = to; this.revision += 1; this.updatedAt = now(); const snapshot = this.getSnapshot(); this.bus.publish({ type: `runtime.${this.domain}.${command}`, domain: this.domain, source: this.id, payload: { from, to, revision: this.revision } }); return snapshot; } }
export class RuntimeIntegrationAdapter extends RuntimeStateMachine { constructor(registration: RuntimeSubsystemRegistration, bus: RuntimeEventBus, metadata: Readonly<Record<string, unknown>> = {}) { super(registration.subsystemId, registration.domain, bus, { adapter: true, ...metadata }, registration); } }
const registration = (subsystemId: string, domain: RuntimeDomain, dependencies: readonly string[], startupPriority: number, shutdownPriority: number): RuntimeSubsystemRegistration => Object.freeze({ subsystemId, domain, dependencies, startupPriority, shutdownPriority, healthSource: `${subsystemId}:health` });
export class RecordingRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('recording-runtime', 'recording', ['replay-runtime'], 50, 20), bus); } }
export class StreamingRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('streaming-runtime', 'streaming', ['recording-runtime'], 60, 10), bus); } }
export class GraphicsRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('graphics-runtime', 'graphics', ['production-graph-runtime'], 30, 50), bus); } }
export class ReplayRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('replay-runtime', 'replay', ['graphics-runtime', 'audio-runtime'], 40, 30), bus); } }
export class AudioRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('audio-runtime', 'audio', ['production-graph-runtime'], 25, 60), bus); } }
export class ProductionGraphRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('production-graph-runtime', 'production', [], 10, 70), bus); } }
export class AutomationRuntimeAdapter extends RuntimeIntegrationAdapter { constructor(bus: RuntimeEventBus) { super(registration('automation-runtime', 'automation', ['production-graph-runtime'], 35, 40), bus); } }
export class SessionManager extends RuntimeStateMachine { constructor(bus: RuntimeEventBus, id = 'session-manager') { super(id, 'session', bus); } }
export class DeviceManager extends RuntimeStateMachine { readonly platform: DeviceRuntimeAdapter; constructor(private readonly deviceBus: RuntimeEventBus, id = 'device-manager') { const registry = new DeviceRegistry(); super(id, 'device', deviceBus, { hardwarePlatform: 'v4.3', metadataOnly: true }); this.platform = new DeviceRuntimeAdapter(registry, new DeviceDiscoveryManager([new BrowserMediaDeviceDiscoveryProvider(), new ScreenCaptureDiscoveryProvider(), new NetworkSourceDiscoveryProvider(), new NativeDesktopDiscoveryProvider(), new CaptureCardDiscoveryProvider(), new PTZDiscoveryProvider()], registry)); } initialize() { this.platform.discovery.initialize(); return super.initialize(); } start() { const snapshot = super.start(); for (const device of this.platform.refreshDiscovery()) this.deviceBus.publish({ type: 'DeviceDiscovered', domain: 'device', source: this.id, payload: { deviceId: device.deviceId, deviceType: device.deviceType, displayName: device.displayName, connectionState: device.connectionState } }); return snapshot; } pause() { return super.pause(); } resume() { this.platform.refreshDiscovery(); return super.resume(); } stop() { this.platform.discovery.stop(); return super.stop(); } dispose() { this.platform.discovery.dispose(); return super.dispose(); } }
export class RuntimeScheduler extends RuntimeStateMachine { private queue: RuntimeCommand[] = []; constructor(bus: RuntimeEventBus, id = 'runtime-scheduler') { super(id, 'scheduler', bus); } schedule(command: RuntimeCommand) { this.queue = [...this.queue, command]; return Object.freeze([...this.queue]); } drain() { const drained = Object.freeze([...this.queue]); this.queue = []; return drained; } get depth() { return this.queue.length; } }
export class RuntimeController { private state: RuntimeLifecycleState = 'uninitialized'; private revision = 0; private startupDurationMs = 0; private shutdownDurationMs = 0; readonly bus: RuntimeEventBus; readonly scheduler: RuntimeScheduler; readonly sessionManager: SessionManager; readonly deviceManager: DeviceManager; readonly healthManager: HealthManager; private subsystems: RuntimeSubsystem[]; constructor(readonly id = 'broadcast-runtime-core', bus = new RuntimeEventBus()) { this.bus = bus; this.scheduler = new RuntimeScheduler(bus); this.sessionManager = new SessionManager(bus); this.deviceManager = new DeviceManager(bus); this.healthManager = new HealthManager(bus); this.subsystems = [new ProductionGraphRuntimeAdapter(bus), new AudioRuntimeAdapter(bus), new GraphicsRuntimeAdapter(bus), new AutomationRuntimeAdapter(bus), new ReplayRuntimeAdapter(bus), new RecordingRuntimeAdapter(bus), new StreamingRuntimeAdapter(bus), this.deviceManager, this.sessionManager, this.healthManager, this.scheduler]; this.validateDependencies(); }
  register(subsystem: RuntimeSubsystem) { if (this.subsystems.some((s) => s.id === subsystem.id)) throw new Error(`Duplicate runtime subsystem ${subsystem.id}`); this.subsystems = [...this.subsystems, subsystem]; this.validateDependencies(); this.bus.publish({ type: 'runtime.controller.register', domain: 'controller', source: this.id, payload: { subsystemId: subsystem.id, domain: subsystem.domain } }); return this.snapshot(); }
  initialize() { return this.run('initialize'); } configure() { return this.run('configure'); } prepare() { return this.run('prepare'); } standby() { return this.run('standby'); } ready() { return this.run('ready'); } start() { return this.run('start'); } pause() { return this.run('pause'); } resume() { return this.run('resume'); } stop() { return this.run('stop'); } recover() { return this.run('recover'); } dispose() { return this.run('dispose'); }
  getStartupOrder() { return Object.freeze([...this.ordered('startup')].map((s) => s.id)); } getShutdownOrder() { return Object.freeze([...this.ordered('shutdown')].map((s) => s.id)); }
  validateDependencies() { const ids = new Set(this.subsystems.map((s) => s.id)); for (const subsystem of this.subsystems) for (const dependency of subsystem.registration?.dependencies ?? []) if (!ids.has(dependency)) throw new Error(`Runtime subsystem ${subsystem.id} depends on missing ${dependency}`); this.ordered('startup'); return true; }
  snapshot(): RuntimeControllerSnapshot { const registrations = this.subsystems.map((s) => s.registration).filter((r): r is RuntimeSubsystemRegistration => Boolean(r)); return Object.freeze({ id: this.id, state: this.state, revision: this.revision, subsystems: this.subsystems.map((s) => s.getSnapshot()), registrations, dependencyGraph: Object.freeze(Object.fromEntries(registrations.map((r) => [r.subsystemId, r.dependencies]))), startupOrder: this.getStartupOrder(), shutdownOrder: this.getShutdownOrder(), runtimeHealth: this.healthManager.getRuntimeHealth(), startupDurationMs: this.startupDurationMs, shutdownDurationMs: this.shutdownDurationMs, queuedEvents: this.scheduler.depth, eventCount: this.bus.count, containsRuntimeHandles: false }); }
  private ordered(mode: 'startup' | 'shutdown') { const registered = this.subsystems.filter((s) => s.registration); const byId = new Map(registered.map((s) => [s.id, s])); const visited = new Set<string>(); const visiting = new Set<string>(); const result: RuntimeSubsystem[] = []; const visit = (s: RuntimeSubsystem) => { if (visited.has(s.id)) return; if (visiting.has(s.id)) throw new Error(`Invalid runtime dependency graph: cycle at ${s.id}`); visiting.add(s.id); for (const dep of s.registration?.dependencies ?? []) visit(byId.get(dep)!); visiting.delete(s.id); visited.add(s.id); result.push(s); }; [...registered].sort((a, b) => (a.registration!.startupPriority - b.registration!.startupPriority) || a.id.localeCompare(b.id)).forEach(visit); const unregistered = this.subsystems.filter((s) => !s.registration); return mode === 'startup' ? [...result, ...unregistered] : [...result].sort((a, b) => (a.registration!.shutdownPriority - b.registration!.shutdownPriority) || a.id.localeCompare(b.id)).concat(unregistered); }
  private run(command: RuntimeCommand) { const started = Date.now(); const from = this.state; this.state = assertTransition(from, command, this.id); this.revision += 1; this.scheduler.schedule(command); this.bus.publish({ type: `runtime.controller.${command}.scheduled`, domain: 'controller', source: this.id, payload: { from, to: this.state, revision: this.revision } }); const sequence = command === 'stop' || command === 'dispose' ? this.ordered('shutdown') : this.ordered('startup'); for (const subsystem of sequence) { const runner = subsystem[command] ?? (command === 'start' ? subsystem.start : undefined); if (runner) { const snapshot = runner.call(subsystem); this.healthManager.updateSubsystem(subsystem.id, snapshot.health); subsystem.onHealthChange?.(snapshot.health); } } this.scheduler.drain(); const duration = Date.now() - started; if (command === 'start') this.startupDurationMs = duration; if (command === 'stop') this.shutdownDurationMs = duration; this.bus.publish({ type: `runtime.controller.${command}.completed`, domain: 'controller', source: this.id, payload: { state: this.state, revision: this.revision, durationMs: duration } }); return this.snapshot(); }
}
export const createBroadcastRuntimeCore = (id?: string) => new RuntimeController(id);
