import type { FrameTick, ProcessorRuntimeContext, RuntimeCommand, RuntimeCommandHandler, RuntimeContext, TickProcessor, TickProcessorDescriptor } from './execution-engine.js';
import type { GraphicsTemplatePublication } from './graphics-template-engine.js';

export const BROADCAST_GRAPHICS_FOUNDATION_VERSION = '5.9.3';
export const BROADCAST_GRAPHICS_PROCESSOR_ORDER = 1220;
export const BROADCAST_GRAPHICS_COMMAND_TYPES = ['CREATE_LOWER_THIRD','UPDATE_LOWER_THIRD','SHOW_LOWER_THIRD','HIDE_LOWER_THIRD','CLEAR_LOWER_THIRD','CREATE_SCOREBUG','UPDATE_SCOREBUG','SHOW_SCOREBUG','HIDE_SCOREBUG','CREATE_TICKER','UPDATE_TICKER','SHOW_TICKER','STOP_TICKER','CREATE_TITLE','SHOW_TITLE','CLEAR_TITLE','CREATE_TIMER','UPDATE_TIMER','START_TIMER','STOP_TIMER','CREATE_STATUS_GRAPHIC','UPDATE_STATUS_GRAPHIC','SHOW_STATUS_GRAPHIC','HIDE_STATUS_GRAPHIC'] as const;
export type BroadcastGraphicsCommandType = (typeof BROADCAST_GRAPHICS_COMMAND_TYPES)[number];
export type BroadcastGraphicsKind = 'LOWER_THIRD' | 'TITLE' | 'SCOREBUG' | 'TICKER' | 'TIMER' | 'STATUS_GRAPHIC' | 'INFORMATION_PANEL';
export type BroadcastGraphicsLifecycle = 'CREATED' | 'PREPARED' | 'QUEUED' | 'READY' | 'VISIBLE' | 'UPDATED' | 'HIDDEN' | 'CLEARED' | 'DESTROYED';
export type BroadcastGraphicsRole = 'PROGRAM' | 'PREVIEW' | 'CLEAN_FEED' | 'AUX' | 'ISO' | 'HORIZONTAL' | 'VERTICAL' | 'SQUARE';
export type BroadcastGraphicsWatchdogIncident = 'DUPLICATE_GRAPHICS' | 'STALE_GENERATION' | 'INVALID_LIFECYCLE' | 'MISSING_TEMPLATE' | 'MISSING_BINDINGS' | 'INVALID_SCORE_UPDATE' | 'TIMER_REGRESSION' | 'DUPLICATE_OUTPUT_PUBLICATION' | 'ROLE_COLLISION' | 'INVARIANT_FAILURE';
type Json = string | number | boolean | null | readonly Json[] | { readonly [key: string]: Json };
type SafeMetadata = Readonly<Record<string, unknown>>;
const forbidden = /secret|token|password|credential|html|css|svg|javascript|script|sql|http|url|path|payload|bytes|native|gpu|raster|canvas/i;
const safe = (m: SafeMetadata = {}) => Object.freeze(Object.fromEntries(Object.entries(m).filter(([k]) => !forbidden.test(k)).slice(0, 64)));
const deepFreeze = <T>(v: T): Readonly<T> => { if (v && typeof v === 'object' && !Object.isFrozen(v)) { Object.freeze(v); for (const c of Object.values(v as Record<string, unknown>)) deepFreeze(c); } return v as Readonly<T>; };
const cloneFreeze = <T>(v: T): Readonly<T> => deepFreeze(structuredClone(v));
const tickFrame = (tick?: FrameTick, fallback = 0) => String(tick?.frameNumber ?? BigInt(fallback));

export interface BroadcastGraphicsDefinition { readonly id: string; readonly generation: number; readonly kind: BroadcastGraphicsKind; readonly packageType: string; readonly templateId: string; readonly templateGeneration: number; readonly outputRole: BroadcastGraphicsRole; readonly variant: BroadcastGraphicsRole; readonly lifecycle: BroadcastGraphicsLifecycle; readonly fields: Readonly<Record<string, Json>>; readonly bindings: Readonly<Record<string, Json>>; readonly templatePublication?: Readonly<GraphicsTemplatePublication>; readonly metadataOnly: true; readonly realRendering: false; readonly safeMetadata: SafeMetadata; }
export interface BroadcastGraphicsTimer { readonly id: string; readonly mode: 'COUNT_UP' | 'COUNT_DOWN' | 'MATCH_CLOCK' | 'STOPWATCH' | 'WALL_CLOCK' | 'SEGMENT_TIMER' | 'COMMERCIAL_TIMER'; readonly generation: number; readonly running: boolean; readonly currentMs: number; readonly previousMs: number; readonly metadataOnly: true; }
export interface BroadcastGraphicsSnapshot { readonly activeGraphics: readonly BroadcastGraphicsDefinition[]; readonly preparedGraphics: readonly BroadcastGraphicsDefinition[]; readonly visibleGraphics: readonly BroadcastGraphicsDefinition[]; readonly queuedGraphics: readonly BroadcastGraphicsDefinition[]; readonly timers: readonly BroadcastGraphicsTimer[]; readonly scorebugs: readonly BroadcastGraphicsDefinition[]; readonly tickers: readonly BroadcastGraphicsDefinition[]; readonly lowerThirds: readonly BroadcastGraphicsDefinition[]; readonly titleMetadata: readonly BroadcastGraphicsDefinition[]; readonly statusGraphics: readonly BroadcastGraphicsDefinition[]; readonly outputRoleSummaries: readonly { readonly role: BroadcastGraphicsRole; readonly graphicsIds: readonly string[] }[]; readonly health: BroadcastGraphicsHealth; readonly telemetry: BroadcastGraphicsTelemetry; readonly watchdog: readonly BroadcastGraphicsWatchdogIncident[]; readonly sourceGraph: BroadcastGraphicsSourceGraph; }
export interface BroadcastGraphicsHealth { readonly activeGraphics: number; readonly queuedGraphics: number; readonly hiddenGraphics: number; readonly duplicateGraphics: number; readonly staleGenerations: number; readonly rejectedCommands: number; readonly activeTimers: number; readonly activeTickers: number; readonly outputRoleCounts: Readonly<Record<string, number>>; readonly processorHealth: 'HEALTHY' | 'DEGRADED'; }
export interface BroadcastGraphicsTelemetry { readonly ticksProcessed: number; readonly creations: number; readonly updates: number; readonly removals: number; readonly visibilityChanges: number; readonly bindingResolutions: number; readonly timerUpdates: number; readonly scoreUpdates: number; readonly tickerUpdates: number; readonly duplicateRequests: number; readonly staleRequests: number; readonly watchdogIncidents: number; readonly metadataOnly: true; readonly realRendering: false; }
export interface BroadcastGraphicsSourceGraph { readonly graphicsIds: readonly string[]; readonly templateIds: readonly string[]; readonly outputRoles: readonly BroadcastGraphicsRole[]; readonly visiblePublications: readonly { readonly id: string; readonly role: BroadcastGraphicsRole; readonly templateId: string }[]; readonly metadataOnly: true; readonly realRendering: false; }
export class BroadcastGraphicsError extends Error { constructor(readonly code: BroadcastGraphicsWatchdogIncident | string, message: string) { super(message); this.name = code; } }

export class BroadcastGraphicsEngine {
  private graphics = new Map<string, Readonly<BroadcastGraphicsDefinition>>(); private timers = new Map<string, Readonly<BroadcastGraphicsTimer>>(); private incidents: BroadcastGraphicsWatchdogIncident[] = []; private ticks = 0; private telemetry = { creations:0, updates:0, removals:0, visibilityChanges:0, bindingResolutions:0, timerUpdates:0, scoreUpdates:0, tickerUpdates:0, duplicateRequests:0, staleRequests:0 };
  create(def: BroadcastGraphicsDefinition) { if (this.graphics.has(def.id)) return this.incident('DUPLICATE_GRAPHICS', `duplicate graphics ${def.id}`); const n = this.normalize(def, 'CREATED'); this.graphics.set(n.id, n); this.telemetry.creations++; this.telemetry.bindingResolutions += Object.keys(n.bindings).length; if (n.kind === 'TIMER') this.timers.set(n.id, cloneFreeze({ id:n.id, mode:(n.fields.mode as BroadcastGraphicsTimer['mode']) ?? 'COUNT_UP', generation:n.generation, running:false, currentMs:Number(n.fields.currentMs ?? 0), previousMs:Number(n.fields.currentMs ?? 0), metadataOnly:true })); return n; }
  update(id: string, generation: number, fields: Readonly<Record<string, Json>> = {}) { const cur = this.must(id); if (generation <= cur.generation) return this.incident('STALE_GENERATION', `stale update ${id}`); if (cur.kind === 'SCOREBUG' && (fields.homeScore !== undefined || fields.awayScore !== undefined) && Object.values(fields).some((v)=>typeof v === 'number' && v < 0)) return this.incident('INVALID_SCORE_UPDATE', `invalid score ${id}`); const n = cloneFreeze({ ...cur, generation, fields: { ...cur.fields, ...fields }, lifecycle: 'UPDATED' as const }); this.graphics.set(id, n); this.telemetry.updates++; if (cur.kind === 'SCOREBUG') this.telemetry.scoreUpdates++; if (cur.kind === 'TICKER') this.telemetry.tickerUpdates++; if (cur.kind === 'TIMER') this.updateTimer(id, generation, Number(fields.currentMs ?? this.timers.get(id)?.currentMs ?? 0), this.timers.get(id)?.running ?? false); return n; }
  show(id: string, generation: number) { return this.lifecycle(id, generation, 'VISIBLE'); } hide(id: string, generation: number) { return this.lifecycle(id, generation, 'HIDDEN'); } clear(id: string, generation: number) { const n = this.lifecycle(id, generation, 'CLEARED'); this.telemetry.removals++; return n; } destroy(id: string, generation: number) { const n = this.lifecycle(id, generation, 'DESTROYED'); this.graphics.delete(id); this.timers.delete(id); this.telemetry.removals++; return n; }
  startTimer(id: string, generation: number) { const t = this.timers.get(id); if (!t) throw new BroadcastGraphicsError('INVARIANT_FAILURE', `unknown timer ${id}`); this.updateTimer(id, generation, t.currentMs, true); return this.lifecycle(id, generation, 'VISIBLE'); } stopTimer(id: string, generation: number) { const t = this.timers.get(id); if (!t) throw new BroadcastGraphicsError('INVARIANT_FAILURE', `unknown timer ${id}`); this.updateTimer(id, generation, t.currentMs, false); return this.lifecycle(id, generation, 'HIDDEN'); }
  processFrame(tick?: FrameTick, publishSnapshot = true) { this.ticks++; for (const g of this.graphics.values()) if (!g.templateId) this.incidents.push('MISSING_TEMPLATE'); return publishSnapshot ? this.snapshot(tickFrame(tick, this.ticks)) : undefined; }
  snapshot(_lastFrame = String(this.ticks)): Readonly<BroadcastGraphicsSnapshot> { const all = [...this.graphics.values()]; const roles = [...new Set(all.map((g)=>g.outputRole))] as BroadcastGraphicsRole[]; const outputRoleCounts = Object.fromEntries(roles.map((r)=>[r, all.filter((g)=>g.outputRole===r).length])); const visible = all.filter((g)=>g.lifecycle==='VISIBLE'); const timers = [...this.timers.values()]; return cloneFreeze({ activeGraphics: all.filter((g)=>!['CLEARED','DESTROYED'].includes(g.lifecycle)), preparedGraphics: all.filter((g)=>['CREATED','PREPARED','READY','UPDATED'].includes(g.lifecycle)), visibleGraphics: visible, queuedGraphics: all.filter((g)=>g.lifecycle==='QUEUED'), timers, scorebugs: all.filter((g)=>g.kind==='SCOREBUG'), tickers: all.filter((g)=>g.kind==='TICKER'), lowerThirds: all.filter((g)=>g.kind==='LOWER_THIRD'), titleMetadata: all.filter((g)=>g.kind==='TITLE'), statusGraphics: all.filter((g)=>g.kind==='STATUS_GRAPHIC'), outputRoleSummaries: roles.map((role)=>({ role, graphicsIds: all.filter((g)=>g.outputRole===role).map((g)=>g.id) })), health: { activeGraphics: all.filter((g)=>g.lifecycle==='VISIBLE').length, queuedGraphics: all.filter((g)=>g.lifecycle==='QUEUED').length, hiddenGraphics: all.filter((g)=>g.lifecycle==='HIDDEN').length, duplicateGraphics: this.incidents.filter((i)=>i==='DUPLICATE_GRAPHICS').length, staleGenerations: this.incidents.filter((i)=>i==='STALE_GENERATION').length, rejectedCommands: this.incidents.length, activeTimers: timers.filter((t)=>t.running).length, activeTickers: all.filter((g)=>g.kind==='TICKER'&&g.lifecycle==='VISIBLE').length, outputRoleCounts, processorHealth: this.incidents.length ? 'DEGRADED' : 'HEALTHY' }, telemetry: { ticksProcessed:this.ticks, ...this.telemetry, watchdogIncidents:this.incidents.length, metadataOnly:true, realRendering:false }, watchdog: this.incidents, sourceGraph: { graphicsIds: all.map((g)=>g.id), templateIds: [...new Set(all.map((g)=>g.templateId))], outputRoles: roles, visiblePublications: visible.map((g)=>({ id:g.id, role:g.outputRole, templateId:g.templateId })), metadataOnly:true, realRendering:false } }); }
  reset() { this.graphics.clear(); this.timers.clear(); this.incidents=[]; }
  commandHandlers(): Record<BroadcastGraphicsCommandType, RuntimeCommandHandler> { const h = (fn:(p: Record<string, unknown>)=>unknown): RuntimeCommandHandler => (cmd: RuntimeCommand) => { fn((cmd.payload ?? {}) as Record<string, unknown>); }; const createKind = (kind: BroadcastGraphicsKind) => h((p)=>this.create({ ...(p.definition as BroadcastGraphicsDefinition), kind })); const update = h((p)=>this.update(String(p.id), Number(p.generation), p.fields as Record<string, Json>)); const show = h((p)=>this.show(String(p.id), Number(p.generation))); const hide = h((p)=>this.hide(String(p.id), Number(p.generation))); const clear = h((p)=>this.clear(String(p.id), Number(p.generation))); return { CREATE_LOWER_THIRD:createKind('LOWER_THIRD'), UPDATE_LOWER_THIRD:update, SHOW_LOWER_THIRD:show, HIDE_LOWER_THIRD:hide, CLEAR_LOWER_THIRD:clear, CREATE_SCOREBUG:createKind('SCOREBUG'), UPDATE_SCOREBUG:update, SHOW_SCOREBUG:show, HIDE_SCOREBUG:hide, CREATE_TICKER:createKind('TICKER'), UPDATE_TICKER:update, SHOW_TICKER:show, STOP_TICKER:hide, CREATE_TITLE:createKind('TITLE'), SHOW_TITLE:show, CLEAR_TITLE:clear, CREATE_TIMER:createKind('TIMER'), UPDATE_TIMER:update, START_TIMER:h((p)=>this.startTimer(String(p.id), Number(p.generation))), STOP_TIMER:h((p)=>this.stopTimer(String(p.id), Number(p.generation))), CREATE_STATUS_GRAPHIC:createKind('STATUS_GRAPHIC'), UPDATE_STATUS_GRAPHIC:update, SHOW_STATUS_GRAPHIC:show, HIDE_STATUS_GRAPHIC:hide }; }
  private normalize(def: BroadcastGraphicsDefinition, lifecycle = def.lifecycle) { if (!def.templateId) throw new BroadcastGraphicsError('MISSING_TEMPLATE', 'templateId is required'); if (def.generation < 1) throw new BroadcastGraphicsError('STALE_GENERATION', 'positive generation required'); return cloneFreeze({ ...def, lifecycle, metadataOnly:true as const, realRendering:false as const, safeMetadata:safe(def.safeMetadata), fields: cloneFreeze(def.fields), bindings: cloneFreeze(def.bindings) }) as Readonly<BroadcastGraphicsDefinition>; }
  private must(id: string) { const cur = this.graphics.get(id); if (!cur) throw new BroadcastGraphicsError('INVARIANT_FAILURE', `unknown graphics ${id}`); return cur; }
  private lifecycle(id: string, generation: number, lifecycle: BroadcastGraphicsLifecycle) { const cur = this.must(id); if (generation < cur.generation) return this.incident('STALE_GENERATION', `stale lifecycle ${id}`); const n = cloneFreeze({ ...cur, generation, lifecycle }); this.graphics.set(id, n); this.telemetry.visibilityChanges++; return n; }
  private updateTimer(id: string, generation: number, currentMs: number, running: boolean) { const prev = this.timers.get(id); if (prev && currentMs < prev.currentMs && prev.mode !== 'COUNT_DOWN') return this.incident('TIMER_REGRESSION', `timer regression ${id}`); this.timers.set(id, cloneFreeze({ id, mode: prev?.mode ?? 'COUNT_UP', generation, running, currentMs, previousMs: prev?.currentMs ?? currentMs, metadataOnly:true })); this.telemetry.timerUpdates++; }
  private incident(i: BroadcastGraphicsWatchdogIncident, m: string): never { this.incidents.push(i); if (i === 'DUPLICATE_GRAPHICS') this.telemetry.duplicateRequests++; if (i === 'STALE_GENERATION') this.telemetry.staleRequests++; throw new BroadcastGraphicsError(i, m); }
}
export const createBroadcastGraphicsEngine = () => new BroadcastGraphicsEngine();
export const createBroadcastGraphicsCommandHandlers = (engine: BroadcastGraphicsEngine) => engine.commandHandlers();
export class BroadcastGraphicsProcessor implements TickProcessor { readonly descriptor: TickProcessorDescriptor = { id:'broadcast-graphics-processor', name:'BroadcastGraphicsProcessor', version:BROADCAST_GRAPHICS_FOUNDATION_VERSION, order:BROADCAST_GRAPHICS_PROCESSOR_ORDER, phase:'GRAPHICS', workloadClass:'BEST_EFFORT', enabledByDefault:true, dependencies:['graphics-template-processor','graphics-foundation-processor'], optionalCapabilities:['broadcast-graphics-metadata','output-role-variants','source-graph-metadata'], estimatedBudgetNs:500000n, maximumBudgetNs:2000000n, timeoutNs:5000000n, maySkipUnderLoad:false, failurePolicy:'DEGRADE_PROCESSOR', criticality:'OPERATIONAL', supportsHotDisable:true, supportsHotEnable:true, supportsHotReplacement:true, statePersistencePolicy:'RETAIN_UNTIL_SHUTDOWN', metadata:{ metadataOnly:true, realRendering:false } }; constructor(readonly engine = createBroadcastGraphicsEngine()) {} initialize() { return { status:'READY' as const, state:this.engine.snapshot() }; } processTick(tick: FrameTick, context?: RuntimeContext | ProcessorRuntimeContext) { const snapshot = this.engine.processFrame(tick); context && 'outputs' in context && context.outputs?.publish(this.descriptor.id, 'broadcast-graphics-foundation', snapshot, 'BORROWED'); return { status:'SUCCEEDED' as const, value:snapshot, metadata:{ metadataOnly:true, realRendering:false } }; } shutdown() { this.engine.reset(); return { status:'STOPPED' as const, metadata:{ cleanup:'complete' } }; } }
export const createBroadcastGraphicsProcessor = (engine?: BroadcastGraphicsEngine) => new BroadcastGraphicsProcessor(engine);
