export type RuntimeLifecycleState = 'uninitialized' | 'initializing' | 'initialized' | 'starting' | 'running' | 'pausing' | 'paused' | 'resuming' | 'stopping' | 'stopped' | 'disposing' | 'disposed' | 'failed';
export type RuntimeDomain = 'production' | 'device' | 'session' | 'scene' | 'switching' | 'recording' | 'streaming' | 'health' | 'scheduler' | 'controller';
export type RuntimeCommand = 'initialize' | 'start' | 'pause' | 'resume' | 'stop' | 'dispose';
export interface RuntimeEvent<T extends string = string, P extends Readonly<Record<string, unknown>> = Readonly<Record<string, unknown>>> { readonly id: string; readonly type: T; readonly domain: RuntimeDomain; readonly timestamp: string; readonly source: string; readonly sequence: number; readonly payload: P; }
export interface RuntimeStateTransition { readonly from: RuntimeLifecycleState; readonly command: RuntimeCommand; readonly to: RuntimeLifecycleState; }
export interface RuntimeSubsystemSnapshot { readonly id: string; readonly domain: RuntimeDomain; readonly state: RuntimeLifecycleState; readonly revision: number; readonly updatedAt: string; readonly metadata: Readonly<Record<string, string | number | boolean>>; }
export interface RuntimeSubsystem { readonly id: string; readonly domain: RuntimeDomain; initialize(): RuntimeSubsystemSnapshot; start(): RuntimeSubsystemSnapshot; pause(): RuntimeSubsystemSnapshot; resume(): RuntimeSubsystemSnapshot; stop(): RuntimeSubsystemSnapshot; dispose(): RuntimeSubsystemSnapshot; getSnapshot(): RuntimeSubsystemSnapshot; }
export interface RuntimeControllerSnapshot { readonly id: string; readonly state: RuntimeLifecycleState; readonly revision: number; readonly subsystems: readonly RuntimeSubsystemSnapshot[]; readonly queuedEvents: number; readonly eventCount: number; readonly containsRuntimeHandles: false; }
const now = () => new Date().toISOString();
const transitions: Readonly<Record<RuntimeCommand, readonly RuntimeLifecycleState[]>> = Object.freeze({ initialize: ['uninitialized', 'stopped', 'disposed', 'failed'], start: ['initialized', 'stopped', 'paused'], pause: ['running'], resume: ['paused'], stop: ['running', 'paused', 'initialized', 'failed'], dispose: ['initialized', 'stopped', 'failed', 'uninitialized'] });
const targets: Readonly<Record<RuntimeCommand, RuntimeLifecycleState>> = Object.freeze({ initialize: 'initialized', start: 'running', pause: 'paused', resume: 'running', stop: 'stopped', dispose: 'disposed' });
function eventId(type: string, sequence: number) { return `runtime:${type}:${sequence}`; }
function assertTransition(state: RuntimeLifecycleState, command: RuntimeCommand, id: string) { if (!transitions[command].includes(state)) throw new Error(`Invalid ${command} transition for ${id} from ${state}`); return targets[command]; }
function sanitize(input: Readonly<Record<string, unknown>> = {}) { return Object.freeze(Object.fromEntries(Object.entries(input).filter(([key, value]) => !/handle|stream|dom|node|socket|process|device|canvas|texture/i.test(key) && ['string', 'number', 'boolean'].includes(typeof value))) as Readonly<Record<string, string | number | boolean>>); }
export class RuntimeEventBus { private sequence = 0; private events: RuntimeEvent[] = []; private listeners = new Set<(event: RuntimeEvent) => void>(); publish<T extends string>(input: Omit<RuntimeEvent<T>, 'id' | 'timestamp' | 'sequence'>) { const event = Object.freeze({ ...input, id: eventId(input.type, ++this.sequence), timestamp: now(), sequence: this.sequence }); this.events = [...this.events, event]; this.listeners.forEach((listener) => listener(event)); return event; } subscribe(listener: (event: RuntimeEvent) => void) { this.listeners.add(listener); return () => this.listeners.delete(listener); } replay() { return Object.freeze([...this.events]); } get count() { return this.events.length; } }
export class RuntimeStateMachine implements RuntimeSubsystem { private state: RuntimeLifecycleState = 'uninitialized'; private revision = 0; private updatedAt = now(); constructor(readonly id: string, readonly domain: RuntimeDomain, private readonly bus: RuntimeEventBus, private readonly metadata: Readonly<Record<string, unknown>> = {}) {} initialize() { return this.transition('initialize'); } start() { return this.transition('start'); } pause() { return this.transition('pause'); } resume() { return this.transition('resume'); } stop() { return this.transition('stop'); } dispose() { return this.transition('dispose'); } getSnapshot(): RuntimeSubsystemSnapshot { return Object.freeze({ id: this.id, domain: this.domain, state: this.state, revision: this.revision, updatedAt: this.updatedAt, metadata: sanitize(this.metadata) }); } private transition(command: RuntimeCommand) { const from = this.state; const to = assertTransition(from, command, this.id); this.state = to; this.revision += 1; this.updatedAt = now(); const snapshot = this.getSnapshot(); this.bus.publish({ type: `runtime.${this.domain}.${command}`, domain: this.domain, source: this.id, payload: { from, to, revision: this.revision } }); return snapshot; } }
export class SessionManager extends RuntimeStateMachine { constructor(bus: RuntimeEventBus, id = 'session-manager') { super(id, 'session', bus); } }
export class DeviceManager extends RuntimeStateMachine { constructor(bus: RuntimeEventBus, id = 'device-manager') { super(id, 'device', bus); } }
export class HealthManager extends RuntimeStateMachine { constructor(bus: RuntimeEventBus, id = 'health-manager') { super(id, 'health', bus); } }
export class RuntimeScheduler extends RuntimeStateMachine { private queue: RuntimeCommand[] = []; constructor(bus: RuntimeEventBus, id = 'runtime-scheduler') { super(id, 'scheduler', bus); } schedule(command: RuntimeCommand) { this.queue = [...this.queue, command]; return Object.freeze([...this.queue]); } drain() { const drained = Object.freeze([...this.queue]); this.queue = []; return drained; } get depth() { return this.queue.length; } }
export class RuntimeController { private state: RuntimeLifecycleState = 'uninitialized'; private revision = 0; readonly bus: RuntimeEventBus; readonly scheduler: RuntimeScheduler; readonly sessionManager: SessionManager; readonly deviceManager: DeviceManager; readonly healthManager: HealthManager; private subsystems: RuntimeSubsystem[]; constructor(readonly id = 'broadcast-runtime-core', bus = new RuntimeEventBus()) { this.bus = bus; this.scheduler = new RuntimeScheduler(bus); this.sessionManager = new SessionManager(bus); this.deviceManager = new DeviceManager(bus); this.healthManager = new HealthManager(bus); this.subsystems = [new RuntimeStateMachine('production-lifecycle', 'production', bus), this.deviceManager, this.sessionManager, new RuntimeStateMachine('scene-lifecycle', 'scene', bus), new RuntimeStateMachine('switching-lifecycle', 'switching', bus), new RuntimeStateMachine('recording-lifecycle', 'recording', bus), new RuntimeStateMachine('streaming-lifecycle', 'streaming', bus), this.healthManager, this.scheduler]; }
  register(subsystem: RuntimeSubsystem) { if (this.subsystems.some((s) => s.id === subsystem.id)) throw new Error(`Duplicate runtime subsystem ${subsystem.id}`); this.subsystems = [...this.subsystems, subsystem]; this.bus.publish({ type: 'runtime.controller.register', domain: 'controller', source: this.id, payload: { subsystemId: subsystem.id, domain: subsystem.domain } }); return this.snapshot(); }
  initialize() { return this.run('initialize'); } start() { return this.run('start'); } pause() { return this.run('pause'); } resume() { return this.run('resume'); } stop() { return this.run('stop'); } dispose() { return this.run('dispose'); }
  snapshot(): RuntimeControllerSnapshot { return Object.freeze({ id: this.id, state: this.state, revision: this.revision, subsystems: this.subsystems.map((s) => s.getSnapshot()), queuedEvents: this.scheduler.depth, eventCount: this.bus.count, containsRuntimeHandles: false }); }
  private run(command: RuntimeCommand) { const from = this.state; this.state = assertTransition(from, command, this.id); this.revision += 1; this.scheduler.schedule(command); this.bus.publish({ type: `runtime.controller.${command}.scheduled`, domain: 'controller', source: this.id, payload: { from, to: this.state, revision: this.revision } }); for (const subsystem of this.subsystems) subsystem[command](); this.scheduler.drain(); this.bus.publish({ type: `runtime.controller.${command}.completed`, domain: 'controller', source: this.id, payload: { state: this.state, revision: this.revision } }); return this.snapshot(); }
}
export const createBroadcastRuntimeCore = (id?: string) => new RuntimeController(id);
