import type { FrameTick, ProcessorRuntimeContext, RuntimeCommand, RuntimeCommandHandler, RuntimeContext, TickProcessor, TickProcessorDescriptor } from './execution-engine.js';

export const CAPTION_ACCESSIBILITY_GRAPHICS_VERSION = '5.9.4';
export const CAPTION_ACCESSIBILITY_PROCESSOR_ORDER = 1230;
export const CAPTION_ACCESSIBILITY_COMMAND_TYPES = ['CREATE_CAPTION_TRACK','UPDATE_CAPTION_TRACK','ADD_CAPTION_CUE','SHOW_CAPTION_CUE','HIDE_CAPTION_CUE','EXPIRE_CAPTION_CUE','CREATE_SUBTITLE_TRACK','UPDATE_ACCESSIBILITY_GRAPHIC','CLEAR_CAPTION_TRACK'] as const;
export type CaptionAccessibilityCommandType = (typeof CAPTION_ACCESSIBILITY_COMMAND_TYPES)[number];
export type CaptionTrackKind = 'CLOSED_CAPTION' | 'OPEN_CAPTION' | 'SUBTITLE' | 'SDH' | 'DESCRIPTIVE_TEXT' | 'ACCESSIBILITY_OVERLAY';
export type CaptionCueLifecycle = 'CREATED' | 'QUEUED' | 'VISIBLE' | 'HIDDEN' | 'EXPIRED' | 'CLEARED';
export type CaptionOutputRole = 'PROGRAM' | 'PREVIEW' | 'CLEAN_FEED' | 'AUX' | 'ISO' | 'HORIZONTAL' | 'VERTICAL' | 'SQUARE';
export type CaptionWatchdogIncident = 'DUPLICATE_TRACK' | 'DUPLICATE_CUE' | 'STALE_GENERATION' | 'INVALID_TIMING' | 'READING_SPEED_EXCEEDED' | 'OVERFLOW_RISK' | 'ROLE_COLLISION' | 'UNSAFE_METADATA' | 'INVARIANT_FAILURE';
type SafeMetadata = Readonly<Record<string, unknown>>;
const forbidden = /secret|token|password|credential|html|css|svg|javascript|script|sql|http|url|path|payload|bytes|native|gpu|raster|canvas|speech|translate/i;
const safe = (m: SafeMetadata = {}) => Object.freeze(Object.fromEntries(Object.entries(m).filter(([k]) => !forbidden.test(k)).slice(0, 64)));
const deepFreeze = <T>(v: T): Readonly<T> => { if (v && typeof v === 'object' && !Object.isFrozen(v)) { Object.freeze(v); for (const c of Object.values(v as Record<string, unknown>)) deepFreeze(c); } return v as Readonly<T>; };
const cloneFreeze = <T>(v: T): Readonly<T> => deepFreeze(structuredClone(v));

export interface CaptionRegion { readonly id: string; readonly anchor: 'LOWER' | 'UPPER' | 'CENTER' | 'CUSTOM'; readonly outputRole: CaptionOutputRole; readonly maxLines: number; readonly maxCharsPerLine: number; readonly safeArea: 'CAPTION_SAFE' | 'LOWER_THIRD_SAFE' | 'CUSTOM'; readonly metadataOnly: true; }
export interface CaptionTrack { readonly id: string; readonly generation: number; readonly kind: CaptionTrackKind; readonly language: string; readonly outputRole: CaptionOutputRole; readonly region: CaptionRegion; readonly lifecycle: 'CREATED' | 'ACTIVE' | 'SUSPENDED' | 'CLEARED'; readonly metadataOnly: true; readonly realEncoding: false; readonly safeMetadata: SafeMetadata; }
export interface CaptionCue { readonly id: string; readonly trackId: string; readonly generation: number; readonly startNs: bigint; readonly endNs: bigint; readonly text: string; readonly speakerLabel?: string; readonly nonSpeechDescription?: string; readonly readingSpeedCps: number; readonly lifecycle: CaptionCueLifecycle; readonly overflow: 'NONE' | 'LINE_WRAP_RISK' | 'REGION_OVERFLOW_RISK'; readonly metadataOnly: true; readonly realRendering: false; readonly safeMetadata: SafeMetadata; }
export interface AccessibilityGraphic { readonly id: string; readonly generation: number; readonly kind: 'SPEAKER_LABEL' | 'NON_SPEECH_DESCRIPTION' | 'WARNING_BANNER' | 'ACCESSIBILITY_NOTICE' | 'LANGUAGE_IDENTIFIER'; readonly outputRole: CaptionOutputRole; readonly text: string; readonly regionId: string; readonly metadataOnly: true; readonly realRendering: false; readonly safeMetadata: SafeMetadata; }
export interface CaptionAccessibilitySnapshot { readonly tracks: readonly CaptionTrack[]; readonly cues: readonly CaptionCue[]; readonly visibleCues: readonly CaptionCue[]; readonly accessibilityGraphics: readonly AccessibilityGraphic[]; readonly outputRoleSummaries: readonly { readonly role: CaptionOutputRole; readonly trackIds: readonly string[]; readonly visibleCueIds: readonly string[] }[]; readonly health: CaptionAccessibilityHealth; readonly telemetry: CaptionAccessibilityTelemetry; readonly watchdog: readonly CaptionWatchdogIncident[]; readonly sourceGraph: CaptionAccessibilitySourceGraph; }
export interface CaptionAccessibilityHealth { readonly activeTracks: number; readonly visibleCues: number; readonly expiredCues: number; readonly rejectedCommands: number; readonly readingSpeedWarnings: number; readonly overflowWarnings: number; readonly processorHealth: 'HEALTHY' | 'DEGRADED'; }
export interface CaptionAccessibilityTelemetry { readonly ticksProcessed: number; readonly tracksCreated: number; readonly cuesCreated: number; readonly visibilityChanges: number; readonly expiredCues: number; readonly accessibilityUpdates: number; readonly watchdogIncidents: number; readonly metadataOnly: true; readonly realRendering: false; readonly realCaptionEncoding: false; }
export interface CaptionAccessibilitySourceGraph { readonly trackIds: readonly string[]; readonly cueIds: readonly string[]; readonly outputRoles: readonly CaptionOutputRole[]; readonly visiblePublications: readonly { readonly cueId: string; readonly trackId: string; readonly role: CaptionOutputRole; readonly language: string }[]; readonly metadataOnly: true; readonly realRendering: false; readonly realCaptionEncoding: false; }
export class CaptionAccessibilityError extends Error { constructor(readonly code: CaptionWatchdogIncident | string, message: string) { super(message); this.name = code; } }

export class CaptionAccessibilityEngine {
  private tracks = new Map<string, Readonly<CaptionTrack>>(); private cues = new Map<string, Readonly<CaptionCue>>(); private graphics = new Map<string, Readonly<AccessibilityGraphic>>(); private incidents: CaptionWatchdogIncident[] = []; private ticks = 0; private telemetry = { tracksCreated:0, cuesCreated:0, visibilityChanges:0, expiredCues:0, accessibilityUpdates:0 };
  createTrack(track: CaptionTrack) { if (this.tracks.has(track.id)) return this.incident('DUPLICATE_TRACK', `duplicate track ${track.id}`); if (track.generation < 1) return this.incident('STALE_GENERATION', 'positive generation required'); const n = cloneFreeze({ ...track, safeMetadata:safe(track.safeMetadata), metadataOnly:true as const, realEncoding:false as const }); this.tracks.set(n.id, n); this.telemetry.tracksCreated++; return n; }
  updateTrack(id: string, generation: number, patch: Partial<CaptionTrack>) { const cur = this.mustTrack(id); if (generation <= cur.generation) return this.incident('STALE_GENERATION', `stale track ${id}`); const n = cloneFreeze({ ...cur, ...patch, id, generation, safeMetadata:safe(patch.safeMetadata ?? cur.safeMetadata), metadataOnly:true as const, realEncoding:false as const }); this.tracks.set(id, n); return n; }
  addCue(cue: CaptionCue) { if (!this.tracks.has(cue.trackId)) return this.incident('INVARIANT_FAILURE', `unknown track ${cue.trackId}`); if (this.cues.has(cue.id)) return this.incident('DUPLICATE_CUE', `duplicate cue ${cue.id}`); if (cue.endNs <= cue.startNs) return this.incident('INVALID_TIMING', `invalid timing ${cue.id}`); const assessed = this.assessCue(cue); this.cues.set(assessed.id, assessed); this.telemetry.cuesCreated++; return assessed; }
  showCue(id: string, generation: number) { return this.lifecycle(id, generation, 'VISIBLE'); } hideCue(id: string, generation: number) { return this.lifecycle(id, generation, 'HIDDEN'); } expireCue(id: string, generation: number) { const n = this.lifecycle(id, generation, 'EXPIRED'); this.telemetry.expiredCues++; return n; }
  updateAccessibilityGraphic(graphic: AccessibilityGraphic) { const cur = this.graphics.get(graphic.id); if (cur && graphic.generation <= cur.generation) return this.incident('STALE_GENERATION', `stale graphic ${graphic.id}`); const n = cloneFreeze({ ...graphic, safeMetadata:safe(graphic.safeMetadata), metadataOnly:true as const, realRendering:false as const }); this.graphics.set(n.id, n); this.telemetry.accessibilityUpdates++; return n; }
  clearTrack(id: string, generation: number) { const cur = this.mustTrack(id); if (generation <= cur.generation) return this.incident('STALE_GENERATION', `stale clear ${id}`); const n = cloneFreeze({ ...cur, generation, lifecycle:'CLEARED' as const }); this.tracks.set(id, n); for (const cue of this.cues.values()) if (cue.trackId === id) this.cues.set(cue.id, cloneFreeze({ ...cue, lifecycle:'CLEARED' as const })); return n; }
  processFrame(tick?: FrameTick, publishSnapshot = true) { this.ticks++; const now = tick?.presentationTimeNs; if (now !== undefined) for (const cue of this.cues.values()) if (cue.lifecycle === 'VISIBLE' && cue.endNs <= now) this.expireCue(cue.id, cue.generation + 1); return publishSnapshot ? this.snapshot() : undefined; }
  snapshot(): Readonly<CaptionAccessibilitySnapshot> { const tracks=[...this.tracks.values()], cues=[...this.cues.values()], visible=cues.filter((c)=>c.lifecycle==='VISIBLE'), roles=[...new Set(tracks.map((t)=>t.outputRole))] as CaptionOutputRole[]; return cloneFreeze({ tracks, cues, visibleCues:visible, accessibilityGraphics:[...this.graphics.values()], outputRoleSummaries:roles.map((role)=>({ role, trackIds:tracks.filter((t)=>t.outputRole===role).map((t)=>t.id), visibleCueIds:visible.filter((c)=>this.tracks.get(c.trackId)?.outputRole===role).map((c)=>c.id) })), health:{ activeTracks:tracks.filter((t)=>t.lifecycle==='ACTIVE').length, visibleCues:visible.length, expiredCues:cues.filter((c)=>c.lifecycle==='EXPIRED').length, rejectedCommands:this.incidents.length, readingSpeedWarnings:this.incidents.filter((i)=>i==='READING_SPEED_EXCEEDED').length, overflowWarnings:this.incidents.filter((i)=>i==='OVERFLOW_RISK').length, processorHealth:this.incidents.length?'DEGRADED':'HEALTHY' }, telemetry:{ ticksProcessed:this.ticks, ...this.telemetry, watchdogIncidents:this.incidents.length, metadataOnly:true, realRendering:false, realCaptionEncoding:false }, watchdog:this.incidents, sourceGraph:{ trackIds:tracks.map((t)=>t.id), cueIds:cues.map((c)=>c.id), outputRoles:roles, visiblePublications:visible.map((c)=>({ cueId:c.id, trackId:c.trackId, role:this.tracks.get(c.trackId)?.outputRole ?? 'PROGRAM', language:this.tracks.get(c.trackId)?.language ?? 'und' })), metadataOnly:true, realRendering:false, realCaptionEncoding:false } }); }
  reset() { this.tracks.clear(); this.cues.clear(); this.graphics.clear(); this.incidents=[]; }
  commandHandlers(): Record<CaptionAccessibilityCommandType, RuntimeCommandHandler> { const h = (fn:(p:Record<string, unknown>)=>unknown): RuntimeCommandHandler => (cmd: RuntimeCommand) => { fn((cmd.payload ?? {}) as Record<string, unknown>); }; return { CREATE_CAPTION_TRACK:h((p)=>this.createTrack(p.track as CaptionTrack)), UPDATE_CAPTION_TRACK:h((p)=>this.updateTrack(String(p.id), Number(p.generation), p.patch as Partial<CaptionTrack>)), ADD_CAPTION_CUE:h((p)=>this.addCue(p.cue as CaptionCue)), SHOW_CAPTION_CUE:h((p)=>this.showCue(String(p.id), Number(p.generation))), HIDE_CAPTION_CUE:h((p)=>this.hideCue(String(p.id), Number(p.generation))), EXPIRE_CAPTION_CUE:h((p)=>this.expireCue(String(p.id), Number(p.generation))), CREATE_SUBTITLE_TRACK:h((p)=>this.createTrack({ ...(p.track as CaptionTrack), kind:'SUBTITLE' })), UPDATE_ACCESSIBILITY_GRAPHIC:h((p)=>this.updateAccessibilityGraphic(p.graphic as AccessibilityGraphic)), CLEAR_CAPTION_TRACK:h((p)=>this.clearTrack(String(p.id), Number(p.generation))) }; }
  private assessCue(cue: CaptionCue) { const track = this.mustTrack(cue.trackId); const durationSeconds = Math.max(1, Number(cue.endNs - cue.startNs) / 1_000_000_000); const readingSpeedCps = cue.text.length / durationSeconds; const overflow: CaptionCue['overflow'] = cue.text.length > track.region.maxLines * track.region.maxCharsPerLine ? 'REGION_OVERFLOW_RISK' : cue.text.split('\n').some((l)=>l.length > track.region.maxCharsPerLine) ? 'LINE_WRAP_RISK' : 'NONE'; if (readingSpeedCps > 21) this.incidents.push('READING_SPEED_EXCEEDED'); if (overflow !== 'NONE') this.incidents.push('OVERFLOW_RISK'); return cloneFreeze({ ...cue, readingSpeedCps, overflow, safeMetadata:safe(cue.safeMetadata), metadataOnly:true as const, realRendering:false as const }); }
  private lifecycle(id: string, generation: number, lifecycle: CaptionCueLifecycle) { const cur = this.mustCue(id); if (generation < cur.generation) return this.incident('STALE_GENERATION', `stale cue ${id}`); const n = cloneFreeze({ ...cur, generation, lifecycle }); this.cues.set(id, n); this.telemetry.visibilityChanges++; return n; }
  private mustTrack(id: string) { const t = this.tracks.get(id); if (!t) throw new CaptionAccessibilityError('INVARIANT_FAILURE', `unknown track ${id}`); return t; }
  private mustCue(id: string) { const c = this.cues.get(id); if (!c) throw new CaptionAccessibilityError('INVARIANT_FAILURE', `unknown cue ${id}`); return c; }
  private incident(i: CaptionWatchdogIncident, m: string): never { this.incidents.push(i); throw new CaptionAccessibilityError(i, m); }
}
export const createCaptionAccessibilityEngine = () => new CaptionAccessibilityEngine();
export const createCaptionAccessibilityCommandHandlers = (engine: CaptionAccessibilityEngine) => engine.commandHandlers();
export class CaptionAccessibilityProcessor implements TickProcessor { readonly descriptor: TickProcessorDescriptor = { id:'caption-accessibility-graphics-processor', name:'CaptionAccessibilityGraphicsProcessor', version:CAPTION_ACCESSIBILITY_GRAPHICS_VERSION, order:CAPTION_ACCESSIBILITY_PROCESSOR_ORDER, phase:'GRAPHICS', workloadClass:'BEST_EFFORT', enabledByDefault:true, dependencies:['broadcast-graphics-processor','graphics-template-processor','graphics-foundation-processor'], optionalCapabilities:['caption-metadata','accessibility-graphics','source-graph-metadata'], estimatedBudgetNs:500000n, maximumBudgetNs:2000000n, timeoutNs:5000000n, maySkipUnderLoad:false, failurePolicy:'DEGRADE_PROCESSOR', criticality:'OPERATIONAL', supportsHotDisable:true, supportsHotEnable:true, supportsHotReplacement:true, statePersistencePolicy:'RETAIN_UNTIL_SHUTDOWN', metadata:{ metadataOnly:true, realRendering:false, realCaptionEncoding:false } }; constructor(readonly engine = createCaptionAccessibilityEngine()) {} initialize() { return { status:'READY' as const, state:this.engine.snapshot() }; } processTick(tick: FrameTick, context?: RuntimeContext | ProcessorRuntimeContext) { const snapshot=this.engine.processFrame(tick); context && 'outputs' in context && context.outputs?.publish(this.descriptor.id, 'caption-accessibility-graphics', snapshot, 'BORROWED'); return { status:'SUCCEEDED' as const, value:snapshot, metadata:{ metadataOnly:true, realRendering:false, realCaptionEncoding:false } }; } shutdown() { this.engine.reset(); return { status:'STOPPED' as const, metadata:{ cleanup:'complete' } }; } }
export const createCaptionAccessibilityProcessor = (engine?: CaptionAccessibilityEngine) => new CaptionAccessibilityProcessor(engine);
