export type DeviceType = 'video-camera' | 'microphone' | 'audio-interface' | 'screen-capture-device' | 'capture-card' | 'sdi-input' | 'hdmi-input' | 'ndi-source' | 'srt-source' | 'rtsp-source' | 'webrtc-source' | 'ptz-camera' | 'virtual-camera' | 'virtual-microphone' | 'playback-deck' | 'timecode-source' | 'control-surface' | 'unknown-device' | (string & {});
export type DeviceConnectionType = 'browser-media' | 'screen-capture' | 'network' | 'native-desktop' | 'capture-card' | 'ptz' | 'virtual' | 'unknown';
export type DeviceConnectionState = 'unknown' | 'discovered' | 'permission-required' | 'connecting' | 'connected' | 'ready' | 'in-use' | 'degraded' | 'reconnecting' | 'disconnected' | 'unavailable' | 'failed' | 'disposed';
export type DeviceHealthState = 'healthy' | 'warning' | 'degraded' | 'error' | 'offline' | 'unavailable' | 'unknown';
export type RecoveryPolicyKind = 'none' | 'manual' | 'immediate-retry' | 'fixed-interval' | 'exponential-backoff';
export interface DeviceFormat { readonly kind: 'video' | 'audio' | 'data'; readonly width?: number; readonly height?: number; readonly frameRate?: number; readonly aspectRatio?: string; readonly pixelFormat?: string; readonly colorSpace?: string; readonly hdr?: boolean; readonly scan?: 'interlaced' | 'progressive'; readonly sampleRate?: number; readonly bitDepth?: number; readonly channels?: number; readonly layout?: string; readonly latencyClass?: 'realtime' | 'low' | 'standard' | 'buffered' | 'unknown'; }
export interface DeviceCapabilities { readonly video?: readonly DeviceFormat[]; readonly audio?: readonly DeviceFormat[]; readonly data?: readonly string[]; readonly canRouteToProgram?: boolean; readonly canRouteToPreview?: boolean; readonly metadataOnly?: boolean; }
export interface DeviceHealthMetadata { readonly state: DeviceHealthState; readonly availability: 'available' | 'unavailable' | 'permission-required' | 'unknown'; readonly connectionState: DeviceConnectionState; readonly permissionState?: 'granted' | 'denied' | 'prompt' | 'unknown'; readonly droppedFrames?: number | 'unavailable'; readonly packetLoss?: number | 'unavailable'; readonly latencyMs?: number | 'unavailable'; readonly jitterMs?: number | 'unavailable'; readonly signalStatus?: 'present' | 'missing' | 'unknown'; readonly formatMismatch?: boolean | 'unknown'; readonly reconnectCount?: number; readonly lastSuccessfulSampleAt?: string; readonly lastError?: string; readonly providerAvailability?: 'available' | 'not-installed' | 'unsupported-platform' | 'provider-unavailable' | 'metadata-only' | 'unknown'; }
export interface DeviceMetadata { readonly deviceId: string; readonly persistentId?: string; readonly displayName: string; readonly manufacturer?: string; readonly model?: string; readonly serialNumber?: string; readonly deviceType: DeviceType; readonly connectionType: DeviceConnectionType; readonly capabilities: DeviceCapabilities; readonly supportedFormats: readonly DeviceFormat[]; readonly selectedFormat?: DeviceFormat; readonly sampleRates: readonly number[]; readonly channelCounts: readonly number[]; readonly frameRates: readonly number[]; readonly resolutions: readonly { readonly width: number; readonly height: number }[]; readonly colorFormats: readonly string[]; readonly transport?: string; readonly latencyEstimateMs?: number | 'unknown' | 'unavailable'; readonly health: DeviceHealthMetadata; readonly connectionState: DeviceConnectionState; readonly lastSeenAt: string; readonly lastConnectedAt?: string; readonly firmware?: Readonly<Record<string, string>>; readonly runtimeAdapterId: string; readonly productionGraphNodeId?: string; }
export interface DiscoveryProviderSnapshot { readonly providerId: string; readonly available: boolean; readonly state: 'idle' | 'initialized' | 'scanning' | 'paused' | 'stopped' | 'disposed' | 'unavailable'; readonly reason?: string; }
export interface DeviceDiscoveryProvider { readonly providerId: string; initialize(): DiscoveryProviderSnapshot; scan(): readonly DeviceMetadata[]; refresh(): readonly DeviceMetadata[]; pause?(): DiscoveryProviderSnapshot; resume?(): DiscoveryProviderSnapshot; stop(): DiscoveryProviderSnapshot; dispose(): DiscoveryProviderSnapshot; getAvailability(): DiscoveryProviderSnapshot; }
const now = () => new Date().toISOString();
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
const illegalKeys = /handle|stream|track|usb|hid|serial|peer|audiocontext|socket|domNode|processHandle/i;
export function assertMetadataSafe(value: unknown): true { const walk = (v: unknown, path: string): void => { if (typeof v === 'function' || typeof v === 'symbol' || typeof v === 'bigint') throw new Error(`Unsafe device metadata at ${path}`); if (v && typeof v === 'object') for (const [k, nested] of Object.entries(v as Record<string, unknown>)) { if (illegalKeys.test(k) && nested !== false) throw new Error(`Unsafe device metadata key ${path}.${k}`); walk(nested, `${path}.${k}`); } }; walk(value, 'metadata'); return true; }
export const DEVICE_TRANSITIONS: Readonly<Record<DeviceConnectionState, readonly DeviceConnectionState[]>> = Object.freeze({ unknown: ['discovered', 'unavailable', 'failed', 'disposed'], discovered: ['permission-required', 'connecting', 'unavailable', 'disposed'], 'permission-required': ['connecting', 'unavailable', 'failed', 'disposed'], connecting: ['connected', 'failed', 'disconnected', 'disposed'], connected: ['ready', 'degraded', 'disconnected', 'disposed'], ready: ['in-use', 'degraded', 'disconnected', 'disposed'], 'in-use': ['ready', 'degraded', 'reconnecting', 'disconnected', 'disposed'], degraded: ['ready', 'reconnecting', 'failed', 'disconnected', 'disposed'], reconnecting: ['connected', 'ready', 'failed', 'disconnected', 'disposed'], disconnected: ['reconnecting', 'connecting', 'unavailable', 'disposed'], unavailable: ['discovered', 'disposed'], failed: ['reconnecting', 'disconnected', 'disposed'], disposed: [] });
function identity(input: Pick<DeviceMetadata, 'persistentId' | 'deviceId' | 'connectionType' | 'deviceType' | 'displayName'>) { return input.persistentId || `${input.connectionType}:${input.deviceType}:${input.deviceId || input.displayName}`.toLowerCase().replace(/\s+/g, '-'); }
export class DeviceRegistry { private devices = new Map<string, DeviceMetadata>(); private aliases = new Map<string, string>(); register(input: DeviceMetadata) { assertMetadataSafe(input); const key = identity(input); const existing = this.aliases.get(key); const deviceId = existing ?? input.deviceId; const device = Object.freeze({ ...clone(input), deviceId, lastSeenAt: input.lastSeenAt || now() }); this.devices.set(deviceId, device); this.aliases.set(key, deviceId); return device; } remove(deviceId: string) { return this.devices.delete(deviceId); } get(deviceId: string) { const d = this.devices.get(deviceId); return d && clone(d); } list() { return Object.freeze([...this.devices.values()].map(clone)); } update(deviceId: string, patch: Partial<DeviceMetadata>) { const current = this.devices.get(deviceId); if (!current) throw new Error(`Unknown device ${deviceId}`); return this.register({ ...current, ...patch, deviceId }); } transition(deviceId: string, to: DeviceConnectionState) { const current = this.devices.get(deviceId); if (!current) throw new Error(`Unknown device ${deviceId}`); if (!DEVICE_TRANSITIONS[current.connectionState].includes(to)) throw new Error(`Illegal device transition ${current.connectionState} -> ${to}`); return this.update(deviceId, { connectionState: to, health: { ...current.health, connectionState: to } }); } }
export class DeviceConnectionManager { constructor(private readonly registry: DeviceRegistry) {} transition(deviceId: string, to: DeviceConnectionState) { return this.registry.transition(deviceId, to); } }
export class DeviceCapabilityResolver { select(device: DeviceMetadata, requested?: DeviceFormat, defaults?: DeviceFormat) { const supported = device.supportedFormats; const candidates = [requested, defaults, supported[0]].filter(Boolean) as DeviceFormat[]; for (const candidate of candidates) { const match = supported.find((f) => Object.entries(candidate).every(([k, v]) => v === undefined || (f as unknown as Record<string, unknown>)[k] === v)); if (match) return { selectedFormat: clone(match), fallbackReason: candidate === requested ? undefined : requested ? 'requested-format-unsupported' : 'production-default-or-first-supported' }; } return { selectedFormat: undefined, fallbackReason: 'no-supported-format' }; } }
export interface DeviceProfile { readonly version: 1; readonly deviceId: string; readonly preferredDisplayName?: string; readonly preferredFormat?: DeviceFormat; readonly preferredAudioMapping?: readonly string[]; readonly preferredLatencyMode?: string; readonly preferredReconnectPolicy?: RecoveryPolicy; readonly preferredProductionGraphRole?: string; readonly sourceLabels?: readonly string[]; readonly colorMetadata?: Readonly<Record<string, string | number | boolean>>; readonly ptzConfiguration?: Readonly<Record<string, string | number | boolean>>; readonly controlSurfaceMappings?: Readonly<Record<string, string>>; readonly operatorNotes?: string; }
export class DeviceProfileManager { private profiles = new Map<string, DeviceProfile>(); load(profile: unknown) { if (!profile || typeof profile !== 'object' || (profile as DeviceProfile).version !== 1 || typeof (profile as DeviceProfile).deviceId !== 'string') return { ok: false as const, reason: 'malformed-or-unsupported-profile' }; assertMetadataSafe(profile); const p = clone(profile as DeviceProfile); this.profiles.set(p.deviceId, p); return { ok: true as const, profile: p }; } get(deviceId: string) { const p = this.profiles.get(deviceId); return p && clone(p); } }
export interface RecoveryPolicy { readonly kind: RecoveryPolicyKind; readonly maximumAttempts: number; readonly retryDelayMs: number; readonly cooldownMs: number; readonly operatorAcknowledgementRequired: boolean; readonly fallbackDevice?: Pick<DeviceMetadata, 'deviceId' | 'displayName' | 'deviceType'>; }
export class DeviceHealthMonitor { private health = new Map<string, DeviceHealthMetadata>(); update(deviceId: string, health: DeviceHealthMetadata) { assertMetadataSafe(health); this.health.set(deviceId, clone(health)); return this.get(deviceId)!; } get(deviceId: string) { const h = this.health.get(deviceId); return h && clone(h); } }
export class DeviceDiscoveryManager { private previous = new Set<string>(); constructor(private readonly providers: readonly DeviceDiscoveryProvider[], private readonly registry: DeviceRegistry) {} initialize() { return this.providers.map((p) => p.initialize()); } scan() { const found = this.providers.flatMap((p) => p.scan()); const added: DeviceMetadata[] = []; for (const d of found) { const before = this.registry.get(d.deviceId); const registered = this.registry.register(d); if (!before) added.push(registered); } this.previous = new Set(this.registry.list().map((d) => d.deviceId)); return Object.freeze(added); } refresh() { return this.scan(); } stop() { return this.providers.map((p) => p.stop()); } dispose() { return this.providers.map((p) => p.dispose()); } availability() { return this.providers.map((p) => p.getAvailability()); } }
function health(state: DeviceConnectionState, providerAvailability: DeviceHealthMetadata['providerAvailability'] = 'available'): DeviceHealthMetadata { return { state: state === 'unavailable' ? 'unavailable' : state === 'disconnected' ? 'offline' : 'unknown', availability: state === 'unavailable' ? 'unavailable' : 'unknown', connectionState: state, providerAvailability }; }
export class StaticDiscoveryProvider implements DeviceDiscoveryProvider { private state: DiscoveryProviderSnapshot['state'] = 'idle'; constructor(readonly providerId: string, private readonly devices: readonly DeviceMetadata[] = [], private readonly available = true, private readonly reason?: string) {} initialize() { this.state = this.available ? 'initialized' : 'unavailable'; return this.getAvailability(); } scan() { this.state = this.available ? 'scanning' : 'unavailable'; return this.available ? this.devices.map(clone) : []; } refresh() { return this.scan(); } pause() { this.state = 'paused'; return this.getAvailability(); } resume() { this.state = this.available ? 'initialized' : 'unavailable'; return this.getAvailability(); } stop() { this.state = 'stopped'; return this.getAvailability(); } dispose() { this.state = 'disposed'; return this.getAvailability(); } getAvailability(): DiscoveryProviderSnapshot { return Object.freeze({ providerId: this.providerId, available: this.available, state: this.state, ...(this.reason ? { reason: this.reason } : {}) }); } }
export class BrowserMediaDeviceDiscoveryProvider extends StaticDiscoveryProvider { constructor(devices: readonly DeviceMetadata[] = []) { super('browser-media-devices', devices); } }
export class ScreenCaptureDiscoveryProvider extends StaticDiscoveryProvider { constructor() { super('screen-capture', [{ deviceId: 'screen-capture:operator-select', displayName: 'Operator selected screen', deviceType: 'screen-capture-device', connectionType: 'screen-capture', capabilities: { video: [], metadataOnly: true }, supportedFormats: [], sampleRates: [], channelCounts: [], frameRates: [], resolutions: [], colorFormats: [], health: health('permission-required'), connectionState: 'permission-required', lastSeenAt: now(), runtimeAdapterId: 'screen-capture-adapter' }]); } }
export class NetworkSourceDiscoveryProvider extends StaticDiscoveryProvider { constructor(devices: readonly DeviceMetadata[] = []) { super('network-sources', devices); } }
export class NativeDesktopDiscoveryProvider extends StaticDiscoveryProvider { constructor() { super('native-desktop', [], false, 'provider-unavailable'); } }
export class CaptureCardDiscoveryProvider extends StaticDiscoveryProvider { constructor() { super('capture-card', [], false, 'metadata-only'); } }
export class PTZDiscoveryProvider extends StaticDiscoveryProvider { constructor() { super('ptz', [], false, 'metadata-only'); } }
export const createPlaceholderHardwareAdapter = (adapterId: string, reason: DeviceHealthMetadata['providerAvailability']) => Object.freeze({ adapterId, status: reason, supportsRuntimeTransport: false, metadataOnly: true });
export const nativeHardwareAdapters = Object.freeze(['DeckLinkAdapter','NDIDeviceAdapter','SDICaptureAdapter','HDMICaptureAdapter','VISCAAdapter','ONVIFAdapter','ASIOAdapter','CoreAudioAdapter','WASAPIAdapter','VirtualCameraAdapter','VirtualMicrophoneAdapter'].map((id) => createPlaceholderHardwareAdapter(id, 'metadata-only')));
export class DeviceEventAdapter { toRuntimeEvent(type: string, device: DeviceMetadata) { assertMetadataSafe(device); return Object.freeze({ type, domain: 'device' as const, source: 'device-manager', payload: { device: clone(device) } }); } }
export class DeviceRuntimeAdapter { constructor(readonly registry = new DeviceRegistry(), readonly discovery = new DeviceDiscoveryManager([], registry), readonly profiles = new DeviceProfileManager(), readonly capabilities = new DeviceCapabilityResolver(), readonly healthMonitor = new DeviceHealthMonitor()) {} listDevices() { return this.registry.list(); } getDevice(id: string) { return this.registry.get(id); } refreshDiscovery() { return this.discovery.refresh(); } getCapabilities(id: string) { return this.registry.get(id)?.capabilities; } getSelectedFormat(id: string) { return this.registry.get(id)?.selectedFormat; } getHealth(id: string) { return this.registry.get(id)?.health ?? this.healthMonitor.get(id); } getConnectionHistory(_id: string) { return [] as const; } getRecoveryState(_id: string) { return { active: false, attempts: 0 } as const; } getProductionGraphLinkage(id: string) { const d = this.registry.get(id); return d && { deviceId: id, productionGraphNodeId: d.productionGraphNodeId }; } getProviderAvailability() { return this.discovery.availability(); } }
export function mapDeviceToProductionGraphMetadata(device: DeviceMetadata, lastEvent?: string) { return Object.freeze({ nodeId: device.productionGraphNodeId ?? `device:${device.deviceId}`, kind: 'device-metadata', deviceIdentity: { deviceId: device.deviceId, persistentId: device.persistentId, displayName: device.displayName, deviceType: device.deviceType }, capabilitySummary: { formats: device.supportedFormats.length, routeEligibility: { program: Boolean(device.capabilities.canRouteToProgram), preview: Boolean(device.capabilities.canRouteToPreview) } }, selectedFormat: device.selectedFormat, connectionStatus: device.connectionState, health: device.health.state, routeEligibility: { program: Boolean(device.capabilities.canRouteToProgram), preview: Boolean(device.capabilities.canRouteToPreview) }, runtimeAdapter: device.runtimeAdapterId, lastEvent, latencyEstimateMs: device.latencyEstimateMs ?? 'unknown', containsRuntimeHandles: false }); }
export function calculateRecoveryDelay(policy: RecoveryPolicy, attempt: number) { if (policy.kind === 'none' || policy.kind === 'manual') return undefined; if (attempt > policy.maximumAttempts) return undefined; if (policy.kind === 'immediate-retry') return 0; if (policy.kind === 'fixed-interval') return policy.retryDelayMs; return Math.min(policy.retryDelayMs * 2 ** Math.max(0, attempt - 1), policy.cooldownMs || Number.MAX_SAFE_INTEGER); }
