// @ts-nocheck
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createEffectChainBuiltInPresets, createEffectChainDefinition, createEffectChainEngine, createEffectChainInstance, createEffectChainNode, EffectChainProcessor, type EffectChainExecutionRequest } from './effect-chain-engine.js';
import type { FrameTick, ProcessorRuntimeContext } from './execution-engine.js';
const assert=(c:unknown,m:string)=>{ if(!c) throw new Error(m); };
const tick=(n:number):FrameTick=>({frameNumber:BigInt(n),startedAtNs:BigInt(n),deadlineAtNs:BigInt(n),scheduledTimeNs:BigInt(n),actualTimeNs:BigInt(n),presentationTimeNs:BigInt(n),frameDurationNs:333n,driftNs:0n,latenessNs:0n,late:false,missedFrames:0n,discontinuity:false});
const input={frameId:'f0',format:'RGBA8',colorMetadata:'SRGB',alphaMode:'PREMULTIPLIED',memoryDomain:'CPU',generation:1,storageGeneration:1,timestampNs:'0',sourceIdentity:'src'};
const base=()=>createEffectChainDefinition({chainId:'chain.a',nodes:[createEffectChainNode({nodeId:'key',nodeType:'KEYING'}),createEffectChainNode({nodeId:'mask',nodeType:'MASKING',dependencies:['key']}),createEffectChainNode({nodeId:'blur',nodeType:'BLUR_SHARPEN',dependencies:['mask'],parameters:{radius:2}})]});
const engine=createEffectChainEngine();
assert(engine.health().registeredChainCount===0,'engine creation');
try{ engine.registerAdapter({adapterId:'KEYING',nodeType:'KEYING',engineId:'x',generation:1}); assert(false,'duplicate adapter rejection'); }catch{}
const d=base(); engine.registerChain(d); assert(engine.snapshot().definitions.length===1,'chain registration');
try{ engine.registerChain(d); assert(false,'duplicate chain rejection'); }catch{}
try{ (d.nodes as any).push(createEffectChainNode({nodeId:'x',nodeType:'PASSTHROUGH'})); }catch{} assert(engine.snapshot().definitions[0].nodes.length===3,'chain immutability');
const d2=createEffectChainDefinition({...base(),chainGeneration:2,nodes:[...base().nodes,createEffectChainNode({nodeId:'color',nodeType:'COLOR_EFFECTS',dependencies:['blur']})]}); engine.updateChain('chain.a',1,d2); assert(engine.snapshot().definitions[0].chainGeneration===2,'chain update generation increment');
try{ engine.updateChain('chain.a',1,d2); assert(false,'stale update rejection'); }catch{}
const inst=createEffectChainInstance({instanceId:'inst.a',chainId:'chain.a',chainVersion:1,chainGeneration:2}); engine.createInstance(inst); try{ engine.createInstance(inst); assert(false,'duplicate instance rejection'); }catch{}
engine.transition('inst.a','ACTIVE'); assert(engine.snapshot().instances[0].activationState==='ACTIVE','activation'); engine.transition('inst.a','SUSPENDED'); engine.transition('inst.a','ACTIVE'); engine.transition('inst.a','INACTIVE'); engine.transition('inst.a','ACTIVE');
const req=(id:string,n=1,extra={}):EffectChainExecutionRequest=>({requestId:id,instanceId:'inst.a',expectedChainVersion:1,expectedChainGeneration:2,expectedInstanceGeneration:engine.snapshot().instances[0].instanceGeneration,runtimeFrameNumber:String(n),frameTick:tick(n),inputFrameReference:input,outputContract:d.outputContract,...extra});
let r=engine.execute(req('r1')); assert(r.status==='COMPLETED'&&r.executedNodeIds.length===4,'multi-node execution distinct output'); assert(r.outputFrameReference.frameId!==input.frameId,'distinct output identity'); assert(input.frameId==='f0','input remains unchanged'); assert(r.outputFrameReference.timestampNs==='0'&&r.outputFrameReference.sourceIdentity==='src','timestamp/source preserved');
let dup=engine.execute(req('r1',2)); assert(dup.status==='REJECTED','duplicate request rejection'); let same=engine.execute(req('r2',1)); assert(same.status==='REJECTED','duplicate same-instance same-tick rejection');
const passEngine=createEffectChainEngine(); const pass=createEffectChainDefinition({chainId:'pass',nodes:[createEffectChainNode({nodeId:'p',nodeType:'PASSTHROUGH'})]}); passEngine.registerChain(pass); passEngine.createInstance(createEffectChainInstance({instanceId:'pi',chainId:'pass',chainVersion:1,chainGeneration:1,activationState:'ACTIVE'})); const pr=passEngine.execute({requestId:'p1',instanceId:'pi',expectedChainVersion:1,expectedChainGeneration:1,expectedInstanceGeneration:1,runtimeFrameNumber:'1',frameTick:tick(1),inputFrameReference:input,outputContract:pass.outputContract}); assert(pr.status==='PASSED_THROUGH'&&pr.outputFrameReference.frameId==='f0','whole-chain pass-through preserves identity');
const cond=createEffectChainDefinition({chainId:'cond',nodes:[createEffectChainNode({nodeId:'opt',nodeType:'IMAGE_EFFECTS',required:false,condition:{type:'NEVER'}}),createEffectChainNode({nodeId:'bar',nodeType:'BARRIER'}),createEffectChainNode({nodeId:'noop',nodeType:'COLOR_EFFECTS',parameters:{neutral:true}})]}); passEngine.registerChain(cond); passEngine.createInstance(createEffectChainInstance({instanceId:'ci',chainId:'cond',chainVersion:1,chainGeneration:1,activationState:'ACTIVE'})); const cr=passEngine.execute({requestId:'c1',instanceId:'ci',expectedChainVersion:1,expectedChainGeneration:1,expectedInstanceGeneration:1,runtimeFrameNumber:'2',frameTick:tick(2),inputFrameReference:input,outputContract:cond.outputContract}); assert(cr.bypassedNodeIds.includes('opt')&&cr.eliminatedNodeIds.includes('noop'),'conditional bypass and no-op elimination');
try{ passEngine.registerChain(createEffectChainDefinition({chainId:'cycle',nodes:[createEffectChainNode({nodeId:'a',nodeType:'KEYING',dependencies:['b']}),createEffectChainNode({nodeId:'b',nodeType:'MASKING',dependencies:['a']})]})); assert(false,'cycle rejection'); }catch{}
try{ passEngine.registerChain(createEffectChainDefinition({chainId:'unsafe',nodes:[createEffectChainNode({nodeId:'img',nodeType:'IMAGE_EFFECTS'}),createEffectChainNode({nodeId:'key',nodeType:'KEYING',dependencies:['img']})]})); assert(false,'unsafe order rejection'); }catch{}
try{ passEngine.registerChain(createEffectChainDefinition({chainId:'custom',nodes:[createEffectChainNode({nodeId:'custom',nodeType:'CUSTOM_APPROVED',engineReference:'missing'})]})); assert(false,'adapter unavailable'); }catch{}
const presets=createEffectChainBuiltInPresets(); assert(presets.length===16&&JSON.stringify(presets)===JSON.stringify(createEffectChainBuiltInPresets()),'built-in preset determinism');
const orderA=createEffectChainDefinition({chainId:'oa',nodes:[createEffectChainNode({nodeId:'b',nodeType:'MASKING',dependencies:['a']}),createEffectChainNode({nodeId:'a',nodeType:'KEYING'})]}); const orderB=createEffectChainDefinition({chainId:'ob',nodes:[createEffectChainNode({nodeId:'a',nodeType:'KEYING'}),createEffectChainNode({nodeId:'b',nodeType:'MASKING',dependencies:['a']})]}); const e2=createEffectChainEngine(); e2.registerChain(orderA); e2.registerChain(orderB); e2.createInstance(createEffectChainInstance({instanceId:'ia',chainId:'oa',chainVersion:1,chainGeneration:1,activationState:'ACTIVE'})); e2.createInstance(createEffectChainInstance({instanceId:'ib',chainId:'ob',chainVersion:1,chainGeneration:1,activationState:'ACTIVE'})); const pa=e2.plan({requestId:'oa',instanceId:'ia',expectedChainVersion:1,expectedChainGeneration:1,expectedInstanceGeneration:1,runtimeFrameNumber:'1',frameTick:tick(1),inputFrameReference:input,outputContract:orderA.outputContract}).orderedNodeExecutionList.map(n=>n.nodeId).join(','); const pb=e2.plan({requestId:'ob',instanceId:'ib',expectedChainVersion:1,expectedChainGeneration:1,expectedInstanceGeneration:1,runtimeFrameNumber:'1',frameTick:tick(1),inputFrameReference:input,outputContract:orderB.outputContract}).orderedNodeExecutionList.map(n=>n.nodeId).join(','); assert(pa===pb,'registration-order permutation stable topological order');
const published:string[]=[]; const proc=new EffectChainProcessor(e2); proc.processTick(tick(3),{outputs:{publish:(_p:string,k:string)=>published.push(k),read:()=>undefined}} as unknown as ProcessorRuntimeContext); assert(published.includes('effectChain.results')&&published.includes('effectChain.health'),'processor publishes atomic registry outputs');
for(let i=0;i<10000;i++) e2.plan({requestId:`lp${i}`,instanceId:'ia',expectedChainVersion:1,expectedChainGeneration:1,expectedInstanceGeneration:1,runtimeFrameNumber:String(i+10),frameTick:tick(i+10),inputFrameReference:input,outputContract:orderA.outputContract,configurationGeneration:i%3});
for(let i=0;i<10000;i++){ const ee=createEffectChainEngine(); const cd=createEffectChainDefinition({chainId:`x${i}`,nodes:[createEffectChainNode({nodeId:'p',nodeType:'PASSTHROUGH'})]}); ee.registerChain(cd); ee.createInstance(createEffectChainInstance({instanceId:'i',chainId:`x${i}`,chainVersion:1,chainGeneration:1,activationState:'ACTIVE'})); const rr=ee.execute({requestId:'r',instanceId:'i',expectedChainVersion:1,expectedChainGeneration:1,expectedInstanceGeneration:1,runtimeFrameNumber:'1',frameTick:tick(1),inputFrameReference:input,outputContract:cd.outputContract}); assert(rr.status==='PASSED_THROUGH','synthetic execution'); }
for(let i=0;i<100000;i++) proc.processTick(tick(i+1000),{outputs:{publish:()=>{},read:()=>undefined}} as unknown as ProcessorRuntimeContext);
assert(e2.assertInvariants(),'invariants'); e2.shutdown(); assert(e2.snapshot().planCacheSize===0&&e2.snapshot().instances.length===0,'shutdown idempotent clean'); e2.shutdown();
console.log('UBOS v5.4.9 Effect Chain validation PASS');
