// @ts-nocheck
/* eslint-disable @typescript-eslint/no-explicit-any */
import { RuntimeEngineError, type FrameTick, type ProcessorRuntimeContext, type TickProcessor } from './execution-engine.js';

export const EFFECT_CHAIN_VERSION = '5.4.9' as const;
export const EFFECT_CHAIN_OUTPUT_KEYS = Object.freeze({ definitions:'effectChain.definitions', instances:'effectChain.instances', requests:'effectChain.requests', plans:'effectChain.plans', results:'effectChain.results', outputFrames:'effectChain.output.frames', passThrough:'effectChain.passThrough.references', failed:'effectChain.failed.results', activeSummaries:'effectChain.active.summaries', health:'effectChain.health', telemetry:'effectChain.telemetry', nodeHealth:'effectChain.node.health' });
export const EFFECT_CHAIN_COMMAND_TYPES = Object.freeze(['EFFECT_CHAIN_REGISTER','EFFECT_CHAIN_UNREGISTER','EFFECT_CHAIN_UPDATE','EFFECT_CHAIN_CREATE_INSTANCE','EFFECT_CHAIN_DESTROY_INSTANCE','EFFECT_CHAIN_ACTIVATE','EFFECT_CHAIN_DEACTIVATE','EFFECT_CHAIN_SUSPEND','EFFECT_CHAIN_RESUME','EFFECT_CHAIN_SET_NODE_PARAMETERS','EFFECT_CHAIN_ENABLE_NODE','EFFECT_CHAIN_DISABLE_NODE','EFFECT_CHAIN_REORDER_NODE','EFFECT_CHAIN_SET_FAILURE_POLICY','EFFECT_CHAIN_SET_QUALITY','EFFECT_CHAIN_BIND_TARGET','EFFECT_CHAIN_UNBIND_TARGET','EFFECT_CHAIN_EXECUTE','EFFECT_CHAIN_CANCEL','EFFECT_CHAIN_CLEAR_PLAN_CACHE','EFFECT_CHAIN_VALIDATE','EFFECT_CHAIN_SHUTDOWN'] as const);
export const EFFECT_CHAIN_WATCHDOG_INCIDENTS = Object.freeze(['EFFECT_CHAIN_ENGINE_STALLED','EFFECT_CHAIN_EXECUTION_TIMEOUT','EFFECT_CHAIN_DUPLICATE_REQUEST','EFFECT_CHAIN_INVALID_GRAPH','EFFECT_CHAIN_DEPENDENCY_CYCLE','EFFECT_CHAIN_ORDER_CONFLICT','EFFECT_CHAIN_ENGINE_UNAVAILABLE','EFFECT_CHAIN_PARAMETER_INVALID','EFFECT_CHAIN_COMPATIBILITY_FAILED','EFFECT_CHAIN_NODE_FAILED','EFFECT_CHAIN_REQUIRED_NODE_SKIPPED','EFFECT_CHAIN_FALSE_PASSTHROUGH','EFFECT_CHAIN_INTERMEDIATE_LEAK','EFFECT_CHAIN_OUTPUT_MISMATCH','EFFECT_CHAIN_TEMP_MEMORY_PRESSURE','EFFECT_CHAIN_ACTIVE_INSTANCE_LIMIT','EFFECT_CHAIN_GPU_RESOURCE_LOST','EFFECT_CHAIN_STALE_GENERATION','EFFECT_CHAIN_PLAN_CACHE_INVALID','EFFECT_CHAIN_OUTPUT_REGISTRY_MISMATCH','EFFECT_CHAIN_GRAPH_MISMATCH','EFFECT_CHAIN_INVARIANT_FAILURE'] as const);
export type EffectChainNodeType='KEYING'|'MASKING'|'BLUR_SHARPEN'|'COLOR_EFFECTS'|'AI_BACKGROUND_PROCESSING'|'IMAGE_EFFECTS'|'PASSTHROUGH'|'BARRIER'|'GROUP'|'OPTIONAL_GROUP'|'CUSTOM_APPROVED';
export type EffectChainActivationState='CREATED'|'ACTIVATING'|'ACTIVE'|'SUSPENDED'|'DEACTIVATING'|'INACTIVE'|'FAILED'|'DESTROYED';
export type EffectChainStatus='COMPLETED'|'PASSED_THROUGH'|'DEGRADED'|'PARTIAL'|'DROPPED'|'CANCELLED'|'FAILED'|'REJECTED';
export type EffectChainFailurePolicy='FAIL_CHAIN'|'DROP_FRAME'|'STOP_AT_FAILED_NODE'|'SKIP_OPTIONAL_NODE'|'BYPASS_OPTIONAL_NODE'|'RETURN_LAST_SUCCESSFUL_INTERMEDIATE'|'PASS_THROUGH_ORIGINAL_IF_SAFE'|'DEGRADE_CHAIN'|'REQUEST_FALLBACK_ADAPTER'|'DISABLE_CHAIN'|'REQUEST_OPERATOR_INTERVENTION';
export type EffectChainParameterSource='STATIC'|'INSTANCE_OVERRIDE'|'MOTION_RESOLVED'|'SOURCE_METADATA'|'SCENE_PARAMETER'|'PIP_SLOT_PARAMETER'|'OUTPUT_ROLE_PARAMETER'|'CUSTOM_TYPED_PROVIDER';
export type EffectChainConditionType='ALWAYS'|'NEVER'|'SOURCE_AVAILABLE'|'SOURCE_HEALTHY'|'MASK_AVAILABLE'|'KEY_MATTE_AVAILABLE'|'BACKGROUND_AVAILABLE'|'OUTPUT_ROLE_MATCHES'|'FRAME_NUMBER_RANGE'|'EXPLICIT_BOOLEAN_PARAMETER'|'CUSTOM_TYPED_CONDITION';
export const EFFECT_CHAIN_STAGE_ORDER: Record<string,number> = { KEYING:1, MASKING:2, BLUR_SHARPEN:3, COLOR_EFFECTS:4, AI_BACKGROUND_PROCESSING:5, IMAGE_EFFECTS:6, PASSTHROUGH:0, BARRIER:0, GROUP:0, OPTIONAL_GROUP:0, CUSTOM_APPROVED:7 };
export class EffectChainError extends RuntimeEngineError { constructor(code:string,msg:string,details:Record<string,unknown>={}){ super(code,msg,details); } }
export const EffectChainErrors = ['EffectChainEngineNotReady','EffectChainNotFound','DuplicateEffectChain','EffectChainInvalid','EffectChainDependencyCycle','EffectChainOrderConflict','EffectChainNodeInvalid','EffectChainNodeNotFound','EffectChainAdapterNotFound','EffectChainCompatibilityFailed','EffectChainInstanceNotFound','DuplicateEffectChainInstance','EffectChainStateTransitionInvalid','EffectChainGenerationMismatch','EffectChainTargetNotFound','EffectChainTargetGenerationMismatch','EffectChainParameterInvalid','EffectChainDuplicateRequest','EffectChainInputInvalid','EffectChainOutputInvalid','EffectChainResourceBudgetExceeded','EffectChainNodeFailed','EffectChainExecutionTimeout','EffectChainCancelled','EffectChainOwnershipViolation','EffectChainInvariantViolation','EffectChainShutdownError'] as const;
export interface EffectChainNode { nodeId:string; nodeType:EffectChainNodeType; engineReference?:string; engineVersionRequirement?:string; parameterSource?:EffectChainParameterSource; parameters?:Record<string,unknown>; motionBindings?:Record<string,string>; required?:boolean; enabled?:boolean; bypassPolicy?:string; failurePolicy?:string; timeoutNs?:string|bigint; qualityTier?:string; resourceBudget?:Record<string,number>; dependencies?:string[]; before?:string[]; after?:string[]; groupId?:string; priority?:number; condition?:{type:EffectChainConditionType; value?:unknown}; safeMetadata?:Record<string,unknown>; }
export interface EffectChainInputContract { acceptedFrameFormats:string[]; acceptedColorMetadata:string[]; acceptedAlphaModes:string[]; acceptedMemoryDomains:string[]; acceptedSourceCategories:string[]; requiresKeyMatte?:boolean; requiresMask?:boolean; requiresBackgroundReference?:boolean; requiresMotionSnapshot?:boolean; minimumGenerationRequirements?:Record<string,number>; safeMetadata?:Record<string,unknown>; }
export interface EffectChainOutputContract { expectedFormat:string; expectedColorMetadata:string; expectedAlphaMode:string; expectedMemoryDomain:string; requiredMetadata?:string[]; preserveSourceIdentity?:boolean; preserveTimestamp?:boolean; routingEligibility?:string[]; safeMetadata?:Record<string,unknown>; }
export interface EffectChainDefinition { chainId:string; chainVersion:number; chainGeneration:number; displayName:string; nodes:EffectChainNode[]; dependencyEdges?:{from:string;to:string;type?:string}[]; inputContract:EffectChainInputContract; outputContract:EffectChainOutputContract; activationPolicy?:string; failurePolicy:EffectChainFailurePolicy; resourceBudget?:Record<string,number>; qualityPolicy?:string; passThroughPolicy?:string; fusionPolicy?:string; compatibilityPolicy?:string; tags?:string[]; safeMetadata?:Record<string,unknown>; createdAtNs:string; updatedAtNs:string; }
export interface EffectChainInstance { instanceId:string; chainId:string; chainVersion:number; chainGeneration:number; instanceGeneration:number; targetBinding?:{type:string;targetId:string;generation:number;role?:string}; activationState:EffectChainActivationState; nodeOverrides?:Record<string,Partial<EffectChainNode>>; parameterOverrides?:Record<string,Record<string,unknown>>; qualityOverride?:string; failurePolicyOverride?:EffectChainFailurePolicy; currentRuntimeFrame?:string; lastPlanId?:string; lastSuccessfulResultSummary?:unknown; healthState?:string; safeMetadata?:Record<string,unknown>; }
export interface EffectChainPlan { planId:string; chainId:string; chainVersion:number; chainGeneration:number; instanceId:string; instanceGeneration:number; runtimeFrameNumber:string; inputDescriptorSummary:Record<string,unknown>; outputContract:EffectChainOutputContract; orderedNodeExecutionList:EffectChainNode[]; resolvedNodeParameters:Record<string,Record<string,unknown>>; dependencyGraphSummary:unknown; conditionalEnablementResults:Record<string,boolean>; bypassedNodes:string[]; eliminatedNoOpNodes:string[]; fusedNodeMetadata:any[]; barrierPositions:number[]; intermediateFrameRequirements:unknown; temporaryResourceEstimates:Record<string,number>; outputByteEstimate:number; operationEstimate:number; selectedQuality:string; selectedFailurePolicy:EffectChainFailurePolicy; passThroughEligible:boolean; requiresNewOutput:boolean; deterministicScore:string; warnings:string[]; safeMetadata?:Record<string,unknown>; }
export interface EffectChainExecutionRequest { requestId:string; instanceId:string; expectedChainVersion:number; expectedChainGeneration:number; expectedInstanceGeneration:number; runtimeFrameNumber:string|bigint; frameTick:FrameTick; inputFrameReference:any; inputLease?:any; expectedFrameGeneration?:number; expectedStorageGeneration?:number; sourceIdentity?:string; maskReference?:any; keyMatteReference?:any; backgroundReference?:any; motionSnapshot?:any; sceneParameters?:Record<string,unknown>; pipSlotParameters?:Record<string,unknown>; outputRoleParameters?:Record<string,unknown>; outputContract:EffectChainOutputContract; deadlineNs?:bigint|string; cancellation?:{cancelled?:boolean}; correlationId?:string; configurationGeneration?:number; safeMetadata?:Record<string,unknown>; }
export interface EffectChainExecutionResult { requestId:string; planId:string; chainId:string; chainVersion:number; chainGeneration:number; instanceId:string; instanceGeneration:number; runtimeFrameNumber:string; status:EffectChainStatus; inputFrameId:string; outputFrameReference?:any; passThrough:boolean; executedNodeIds:string[]; bypassedNodeIds:string[]; eliminatedNodeIds:string[]; failedNodeId?:string; fusedGroupSummaries:any[]; intermediateFrameCount:number; temporaryBytes:number; outputBytes:number; nodeDurationSummaries:any[]; totalDurationNs:string; warnings:string[]; failureReason?:string; ownershipTransfer:string; completedAtNs:string; }
export interface EffectChainNodeAdapter { adapterId:string; nodeType:EffectChainNodeType; engineId:string; generation:number; validateParameters?(p:any):boolean; isNeutral?(p:any,n:EffectChainNode):boolean; execute?(ctx:any):any; health?():unknown; release?():void; }
const clone = <T>(v:T):T => Object.freeze(JSON.parse(JSON.stringify(v)));
const err=(c:string,m:string,d={})=>new EffectChainError(c,m,d);
export class EffectChainEngine { definitions=new Map<string,EffectChainDefinition>(); instances=new Map<string,EffectChainInstance>(); adapters=new Map<string,EffectChainNodeAdapter>(); presets=new Map<string,EffectChainDefinition>(); planCache=new Map<string,EffectChainPlan>(); requests=new Set<string>(); executedTick=new Set<string>(); shutdownFlag=false; counters:any={ registrations:0, updates:0, removals:0, instances:0, executions:0, completed:0, passThrough:0, failed:0, rejected:0, duplicateRequests:0, staleGenerationRejects:0, planCreations:0, planCacheHits:0, nodesExecuted:0, nodesBypassed:0, noopEliminated:0, fusionGroupsPlanned:0, intermediateCreated:0, intermediateReleased:0, compatibilityFailures:0, timeouts:0, overloads:0 };
  constructor(readonly max={chains:256,nodes:64,depth:8,fanOut:16,instances:1024,cache:256}){ this.registerBuiltIns(); }
  registerAdapter(a:EffectChainNodeAdapter){ if(this.adapters.has(a.adapterId)) throw err('DuplicateEffectChainAdapter','duplicate adapter'); this.adapters.set(a.adapterId, clone(a)); }
  registerBuiltIns(){ for(const t of ['KEYING','MASKING','BLUR_SHARPEN','COLOR_EFFECTS','AI_BACKGROUND_PROCESSING','IMAGE_EFFECTS','PASSTHROUGH','BARRIER'] as EffectChainNodeType[]) this.adapters.set(t, Object.freeze({adapterId:t,nodeType:t,engineId:t,generation:1,validateParameters:()=>true,isNeutral:(p:any,n:any)=>t==='PASSTHROUGH'||t==='BARRIER'||p?.neutral===true||n.enabled===false,execute:({input,node})=>({frame:{...input, frameId:`${input?.frameId ?? 'frame'}:${node.nodeId}`}})})); }
  validateDefinition(d:EffectChainDefinition){ if(!d.chainId) throw err('EffectChainInvalid','missing chain id'); if(d.nodes.length>this.max.nodes) throw err('EffectChainInvalid','node bound exceeded'); const ids=new Set<string>(); for(const n of d.nodes){ if(ids.has(n.nodeId)) throw err('EffectChainNodeInvalid','duplicate node id'); ids.add(n.nodeId); if(!EFFECT_CHAIN_STAGE_ORDER[n.nodeType]) { if(!['PASSTHROUGH','BARRIER','GROUP','OPTIONAL_GROUP'].includes(n.nodeType)) throw err('EffectChainNodeInvalid','unsupported node type'); } const ref=n.engineReference??n.nodeType; if(n.nodeType==='CUSTOM_APPROVED'&&!this.adapters.has(ref)) throw err('EffectChainAdapterNotFound','custom adapter missing'); if(!['GROUP','OPTIONAL_GROUP'].includes(n.nodeType)&&!this.adapters.has(ref)) throw err('EffectChainAdapterNotFound','adapter missing'); }
    const edges=[...(d.dependencyEdges??[]),...d.nodes.flatMap(n=>(n.dependencies??[]).map(x=>({from:x,to:n.nodeId}))),...d.nodes.flatMap(n=>(n.before??[]).map(x=>({from:n.nodeId,to:x}))),...d.nodes.flatMap(n=>(n.after??[]).map(x=>({from:x,to:n.nodeId})))]; const indeg=new Map([...ids].map(id=>[id,0])); const adj=new Map([...ids].map(id=>[id,[]])); for(const e of edges){ if(!ids.has(e.from)||!ids.has(e.to)) throw err('EffectChainInvalid','edge references missing node'); adj.get(e.from).push(e.to); indeg.set(e.to,indeg.get(e.to)+1); }
    const q=[...ids].filter(id=>indeg.get(id)===0).sort(); let seen=0; while(q.length){ const id=q.shift(); seen++; for(const to of adj.get(id).sort()){ indeg.set(to,indeg.get(to)-1); if(indeg.get(to)===0) q.push(to), q.sort(); } } if(seen!==ids.size) throw err('EffectChainDependencyCycle','cycle rejected'); const order=this.topo(d).orderedNodeExecutionList; for(let i=1;i<order.length;i++){ const a=EFFECT_CHAIN_STAGE_ORDER[order[i-1].nodeType]??7,b=EFFECT_CHAIN_STAGE_ORDER[order[i].nodeType]??7; if(a>b && !d.compatibilityPolicy?.includes('ALLOW_UNSAFE_ORDER')) throw err('EffectChainOrderConflict','unsafe stage order'); } return true; }
  registerChain(d:EffectChainDefinition){ if(this.shutdownFlag) throw err('EffectChainShutdownError','shutdown'); if(this.definitions.has(d.chainId)) throw err('DuplicateEffectChain','duplicate chain'); if(this.definitions.size>=this.max.chains) throw err('EffectChainInvalid','chain bound exceeded'); this.validateDefinition(d); this.definitions.set(d.chainId, clone(d)); this.counters.registrations++; }
  updateChain(id:string, expectedGen:number, next:EffectChainDefinition){ const cur=this.definitions.get(id); if(!cur) throw err('EffectChainNotFound','missing chain'); if(cur.chainGeneration!==expectedGen) {this.counters.staleGenerationRejects++; throw err('EffectChainGenerationMismatch','stale chain');} if(next.chainGeneration<=cur.chainGeneration) throw err('EffectChainGenerationMismatch','generation did not advance'); this.validateDefinition(next); this.definitions.set(id, clone(next)); [...this.planCache.keys()].filter(k=>k.includes(id)).forEach(k=>this.planCache.delete(k)); this.counters.updates++; }
  unregisterChain(id:string){ if(!this.definitions.delete(id)) throw err('EffectChainNotFound','missing chain'); this.counters.removals++; }
  createInstance(i:EffectChainInstance){ if(this.instances.has(i.instanceId)) throw err('DuplicateEffectChainInstance','duplicate instance'); const c=this.definitions.get(i.chainId); if(!c) throw err('EffectChainNotFound','missing chain'); this.instances.set(i.instanceId, clone(i)); this.counters.instances++; }
  transition(id:string,to:EffectChainActivationState){ const i=this.instances.get(id); if(!i) throw err('EffectChainInstanceNotFound','missing instance'); const ok:any={CREATED:['ACTIVE','INACTIVE','DESTROYED'],ACTIVE:['SUSPENDED','INACTIVE','FAILED','DESTROYED'],SUSPENDED:['ACTIVE','INACTIVE','DESTROYED'],INACTIVE:['ACTIVE','DESTROYED'],FAILED:['INACTIVE','DESTROYED']}; if(!(ok[i.activationState]??[]).includes(to)) throw err('EffectChainStateTransitionInvalid','invalid transition'); this.instances.set(id, clone({...i,activationState:to,instanceGeneration:i.instanceGeneration+1})); }
  topo(d:EffectChainDefinition, req?:EffectChainExecutionRequest):EffectChainPlan{ const ids=new Set(d.nodes.map(n=>n.nodeId)); const edges=[...(d.dependencyEdges??[]),...d.nodes.flatMap(n=>(n.dependencies??[]).map(x=>({from:x,to:n.nodeId}))),...d.nodes.flatMap(n=>(n.before??[]).map(x=>({from:n.nodeId,to:x}))),...d.nodes.flatMap(n=>(n.after??[]).map(x=>({from:x,to:n.nodeId})))]; const indeg=new Map([...ids].map(id=>[id,0])); const adj=new Map([...ids].map(id=>[id,[]])); edges.forEach(e=>{adj.get(e.from)?.push(e.to); indeg.set(e.to,(indeg.get(e.to)??0)+1);}); const byId=new Map(d.nodes.map(n=>[n.nodeId,n])); const sort=(a:string,b:string)=> (byId.get(a).groupId??'').localeCompare(byId.get(b).groupId??'') || ((byId.get(a).priority??0)-(byId.get(b).priority??0)) || ((EFFECT_CHAIN_STAGE_ORDER[byId.get(a).nodeType]??7)-(EFFECT_CHAIN_STAGE_ORDER[byId.get(b).nodeType]??7)) || a.localeCompare(b) || (byId.get(a).engineReference??'').localeCompare(byId.get(b).engineReference??''); let q=[...ids].filter(id=>indeg.get(id)===0).sort(sort), out=[]; while(q.length){ const id=q.shift(); out.push(byId.get(id)); for(const to of (adj.get(id)??[]).sort(sort)){ indeg.set(to,indeg.get(to)-1); if(indeg.get(to)===0) q.push(to), q.sort(sort); } } const cond:any={}, bypass:string[]=[], elim:string[]=[], params:any={}; for(const n of out){ cond[n.nodeId]=this.condition(n,req); params[n.nodeId]={...(n.parameters??{})}; const ad=this.adapters.get(n.engineReference??n.nodeType); if(!cond[n.nodeId]||n.enabled===false) { if(n.required) throw err('EffectChainNodeInvalid','required node disabled'); bypass.push(n.nodeId); } else if(ad?.isNeutral?.(params[n.nodeId],n)) elim.push(n.nodeId); }
    const active=out.filter(n=>cond[n.nodeId]&&n.enabled!==false&&!elim.includes(n.nodeId)&&!['PASSTHROUGH','BARRIER','GROUP','OPTIONAL_GROUP'].includes(n.nodeType)); const pass=active.length===0; return clone({planId:`plan:${d.chainId}:${d.chainGeneration}:${req?.runtimeFrameNumber??0}:${out.map(n=>n.nodeId).join('.')}`,chainId:d.chainId,chainVersion:d.chainVersion,chainGeneration:d.chainGeneration,instanceId:req?.instanceId??'',instanceGeneration:req?.expectedInstanceGeneration??0,runtimeFrameNumber:String(req?.runtimeFrameNumber??0),inputDescriptorSummary:{format:req?.inputFrameReference?.format,color:req?.inputFrameReference?.colorMetadata,alpha:req?.inputFrameReference?.alphaMode,memory:req?.inputFrameReference?.memoryDomain},outputContract:d.outputContract,orderedNodeExecutionList:out,resolvedNodeParameters:params,dependencyGraphSummary:{nodes:out.map(n=>n.nodeId),edges},conditionalEnablementResults:cond,bypassedNodes:bypass,eliminatedNoOpNodes:elim,fusedNodeMetadata:d.fusionPolicy==='DISABLED'?[]:[{category:'metadata-only',nodeIds:active.map(n=>n.nodeId)}].filter(x=>x.nodeIds.length>1),barrierPositions:out.map((n,i)=>n.nodeType==='BARRIER'?i:-1).filter(i=>i>=0),intermediateFrameRequirements:{maximum:active.length},temporaryResourceEstimates:{intermediateFrames:active.length},outputByteEstimate:req?.inputFrameReference?.byteLength??0,operationEstimate:active.length,selectedQuality:'DEFAULT',selectedFailurePolicy:d.failurePolicy,passThroughEligible:pass,requiresNewOutput:!pass,deterministicScore:`${out.length}:${edges.length}:${active.length}`,warnings:[]}); }
  condition(n:EffectChainNode, r?:EffectChainExecutionRequest){ const c=n.condition; if(!c||c.type==='ALWAYS') return true; if(c.type==='NEVER') return false; if(c.type==='MASK_AVAILABLE') return !!r?.maskReference; if(c.type==='KEY_MATTE_AVAILABLE') return !!r?.keyMatteReference; if(c.type==='BACKGROUND_AVAILABLE') return !!r?.backgroundReference; if(c.type==='OUTPUT_ROLE_MATCHES') return r?.outputRoleParameters?.role===c.value; if(c.type==='FRAME_NUMBER_RANGE'){ const [a,b]=c.value as any; const f=Number(r?.runtimeFrameNumber??0); return f>=a&&f<=b;} if(c.type==='EXPLICIT_BOOLEAN_PARAMETER') return !!n.parameters?.[String(c.value)]; return true; }
  plan(req:EffectChainExecutionRequest){ const i=this.instances.get(req.instanceId); if(!i) throw err('EffectChainInstanceNotFound','missing instance'); const d=this.definitions.get(i.chainId); if(!d) throw err('EffectChainNotFound','missing chain'); if(d.chainGeneration!==req.expectedChainGeneration||i.instanceGeneration!==req.expectedInstanceGeneration) throw err('EffectChainGenerationMismatch','stale generation'); if(d.inputContract.requiresMotionSnapshot && String(req.motionSnapshot?.runtimeFrameNumber)!==String(req.runtimeFrameNumber)) throw err('EffectChainInputInvalid','stale motion snapshot'); const key=JSON.stringify([d.chainId,d.chainVersion,d.chainGeneration,i.instanceGeneration,req.inputFrameReference?.format,req.inputFrameReference?.colorMetadata,req.inputFrameReference?.alphaMode,req.inputFrameReference?.memoryDomain,req.motionSnapshot?.generation,req.outputRoleParameters?.role,req.configurationGeneration]); if(this.planCache.has(key)){this.counters.planCacheHits++; return this.planCache.get(key);} const p=this.topo(d,req); if(this.planCache.size>=this.max.cache) this.planCache.delete([...this.planCache.keys()].sort()[0]); this.planCache.set(key,p); this.counters.planCreations++; return p; }
  execute(req:EffectChainExecutionRequest):EffectChainExecutionResult{ try{ if(this.requests.has(req.requestId)){this.counters.duplicateRequests++; throw err('EffectChainDuplicateRequest','duplicate request');} this.requests.add(req.requestId); const key=`${req.instanceId}:${req.runtimeFrameNumber}`; if(this.executedTick.has(key)) throw err('EffectChainDuplicateRequest','duplicate same tick'); const i=this.instances.get(req.instanceId); if(!i||i.activationState!=='ACTIVE') throw err('EffectChainInstanceNotFound','inactive instance'); const p=this.plan(req); if(req.cancellation?.cancelled) throw err('EffectChainCancelled','cancelled'); let cur=req.inputFrameReference, executed=[]; if(p.passThroughEligible){ this.executedTick.add(key); this.counters.passThrough++; return this.result(req,p,'PASSED_THROUGH',cur,[],true); } for(const n of p.orderedNodeExecutionList){ if(req.cancellation?.cancelled) throw err('EffectChainCancelled','cancelled'); if(p.bypassedNodes.includes(n.nodeId)||p.eliminatedNoOpNodes.includes(n.nodeId)||['GROUP','OPTIONAL_GROUP','BARRIER','PASSTHROUGH'].includes(n.nodeType)) continue; const ad=this.adapters.get(n.engineReference??n.nodeType); if(!ad) throw err('EffectChainAdapterNotFound','adapter unavailable'); const out=ad.execute?.({input:cur,node:n,request:req,parameters:p.resolvedNodeParameters[n.nodeId]})?.frame ?? {...cur,frameId:`${cur.frameId}:${n.nodeId}`}; cur=out; executed.push(n.nodeId); this.counters.nodesExecuted++; }
      this.executedTick.add(key); this.counters.completed++; return this.result(req,p,'COMPLETED',cur,executed,false); } catch(e:any){ this.counters.failed++; return {requestId:req.requestId,planId:'',chainId:'',chainVersion:req.expectedChainVersion,chainGeneration:req.expectedChainGeneration,instanceId:req.instanceId,instanceGeneration:req.expectedInstanceGeneration,runtimeFrameNumber:String(req.runtimeFrameNumber),status:e.code==='EffectChainDuplicateRequest'?'REJECTED':e.code==='EffectChainCancelled'?'CANCELLED':'FAILED',inputFrameId:String(req.inputFrameReference?.frameId??''),passThrough:false,executedNodeIds:[],bypassedNodeIds:[],eliminatedNodeIds:[],fusedGroupSummaries:[],intermediateFrameCount:0,temporaryBytes:0,outputBytes:0,nodeDurationSummaries:[],totalDurationNs:'0',warnings:[],failureReason:e.message,ownershipTransfer:'NONE',completedAtNs:String(req.frameTick?.actualTimeNs??0)}; } }
  result(req,p,status,out,executed,pass):EffectChainExecutionResult{ return clone({requestId:req.requestId,planId:p.planId,chainId:p.chainId,chainVersion:p.chainVersion,chainGeneration:p.chainGeneration,instanceId:req.instanceId,instanceGeneration:req.expectedInstanceGeneration,runtimeFrameNumber:String(req.runtimeFrameNumber),status,inputFrameId:String(req.inputFrameReference?.frameId??''),outputFrameReference:out,passThrough:pass,executedNodeIds:executed,bypassedNodeIds:p.bypassedNodes,eliminatedNodeIds:p.eliminatedNoOpNodes,fusedGroupSummaries:p.fusedNodeMetadata,intermediateFrameCount:executed.length,temporaryBytes:0,outputBytes:out?.byteLength??0,nodeDurationSummaries:executed.map((nodeId:string)=>({nodeId,durationNs:'0'})),totalDurationNs:'0',warnings:p.warnings,ownershipTransfer:pass?'PRESERVED':'TRANSFERRED',completedAtNs:String(req.frameTick.actualTimeNs)}); }
  snapshot(){ return clone({version:EFFECT_CHAIN_VERSION,definitions:[...this.definitions.values()].sort((a,b)=>a.chainId.localeCompare(b.chainId)),instances:[...this.instances.values()].sort((a,b)=>a.instanceId.localeCompare(b.instanceId)),planCacheSize:this.planCache.size,health:this.health(),telemetry:this.telemetry()}); }
  health(){ return clone({engineState:this.shutdownFlag?'SHUTDOWN':'READY',healthState:this.counters.failed?'degraded':'healthy',registeredChainCount:this.definitions.size,presetCount:this.presets.size,activeInstanceCount:[...this.instances.values()].filter(i=>i.activationState==='ACTIVE').length,activeExecutionCount:0,planCacheSize:this.planCache.size,totalExecutionCount:this.counters.completed+this.counters.failed+this.counters.passThrough,completedCount:this.counters.completed,passThroughCount:this.counters.passThrough,degradedCount:0,partialCount:0,droppedCount:0,cancelledCount:0,failedCount:this.counters.failed,rejectedCount:this.counters.rejected,duplicateRequestCount:this.counters.duplicateRequests,staleGenerationRejectionCount:this.counters.staleGenerationRejects,invalidGraphCount:0,compatibilityFailureCount:this.counters.compatibilityFailures,parameterResolutionFailureCount:0,nodeFailureCount:0,timeoutCount:this.counters.timeouts,overloadCount:this.counters.overloads,gpuLossCount:0,intermediateFrameCount:0,temporaryBytes:0,peakTemporaryBytes:0,maximumActiveInstancesObserved:this.instances.size,lastSuccess:undefined,lastFailure:undefined,updatedAtNs:String(Date.now()*1000000)}); }
  telemetry(){ return clone({...this.counters,currentRequestIds:[...this.requests].slice(-32),activeInstanceIds:[...this.instances.values()].filter(i=>i.activationState==='ACTIVE').map(i=>i.instanceId).sort(),lastChainEvent:'snapshot'}); }
  assertInvariants(){ for(const d of this.definitions.values()) this.validateDefinition(d); if(this.definitions.size>this.max.chains||this.instances.size>this.max.instances||this.planCache.size>this.max.cache) throw err('EffectChainInvariantViolation','bounded registry exceeded'); return true; }
  shutdown(){ this.instances.clear(); this.planCache.clear(); this.requests.clear(); this.executedTick.clear(); this.adapters.forEach(a=>a.release?.()); this.shutdownFlag=true; return this.assertInvariants(); }
}
export const createEffectChainEngine=()=>new EffectChainEngine();
export const createEffectChainDefinition=(d:Partial<EffectChainDefinition>):EffectChainDefinition=>clone({chainVersion:1,chainGeneration:1,displayName:d.chainId??'chain',nodes:[],dependencyEdges:[],inputContract:{acceptedFrameFormats:['RGBA8'],acceptedColorMetadata:['SRGB'],acceptedAlphaModes:['PREMULTIPLIED'],acceptedMemoryDomains:['CPU'],acceptedSourceCategories:['CAMERA']},outputContract:{expectedFormat:'RGBA8',expectedColorMetadata:'SRGB',expectedAlphaMode:'PREMULTIPLIED',expectedMemoryDomain:'CPU',preserveSourceIdentity:true,preserveTimestamp:true},failurePolicy:'FAIL_CHAIN',createdAtNs:'0',updatedAtNs:'0',...d});
export const createEffectChainNode=(n:Partial<EffectChainNode>&{nodeId:string;nodeType:EffectChainNodeType}):EffectChainNode=>clone({required:true,enabled:true,parameterSource:'STATIC',parameters:{},dependencies:[],before:[],after:[],priority:0,...n});
export const createEffectChainInstance=(i:Partial<EffectChainInstance>&{instanceId:string;chainId:string;chainVersion:number;chainGeneration:number}):EffectChainInstance=>clone({instanceGeneration:1,activationState:'CREATED',...i});
export const createEffectChainBuiltInPresets=()=> ['CLEAN_CAMERA','GREEN_SCREEN_PRESENTER','REMOTE_GUEST_CLEANUP','PODCAST_HOST','PODCAST_GUEST','SOCIAL_LIVE_RELAY','PRESENTATION_CAMERA','CINEMATIC_CAMERA','VIRTUAL_BACKGROUND','SOFT_PORTRAIT','HIGH_CONTRAST_MONO','SPORTS_CAMERA','GAMING_FACE_CAM','LOWER_THIRD_SOURCE','PIP_GUEST_CARD','CUSTOM'].map((id,i)=>createEffectChainDefinition({chainId:`preset.${id}`,chainVersion:1,chainGeneration:1,displayName:id,nodes:[createEffectChainNode({nodeId:'passthrough',nodeType:'PASSTHROUGH'})],tags:[id],createdAtNs:String(i),updatedAtNs:String(i)}));
export class EffectChainProcessor implements TickProcessor { id='effect-chain-processor'; order=547; constructor(readonly engine:EffectChainEngine){} initialize(){} shutdown(){ this.engine.shutdown(); } processTick(tick:FrameTick, context:ProcessorRuntimeContext){ const results=[]; for(const inst of [...this.engine.instances.values()].filter(i=>i.activationState==='ACTIVE').sort((a,b)=>a.instanceId.localeCompare(b.instanceId))){ const req:any=context.outputs?.read?.(this.id,`${EFFECT_CHAIN_OUTPUT_KEYS.requests}.${inst.instanceId}`); if(req) results.push(this.engine.execute(req)); } context.outputs?.publish?.(this.id,EFFECT_CHAIN_OUTPUT_KEYS.results,results,{kind:'DERIVED',ownerProcessorId:this.id,description:'atomic effect chain results'}); context.outputs?.publish?.(this.id,EFFECT_CHAIN_OUTPUT_KEYS.health,this.engine.health(),{kind:'DERIVED',ownerProcessorId:this.id,description:'effect chain health'}); context.outputs?.publish?.(this.id,EFFECT_CHAIN_OUTPUT_KEYS.telemetry,this.engine.telemetry(),{kind:'DERIVED',ownerProcessorId:this.id,description:'effect chain telemetry'}); }}
