import type { FrameTick, ProcessorRuntimeContext, RuntimeCommand, RuntimeCommandHandler, RuntimeContext, TickProcessor, TickProcessorDescriptor } from './execution-engine.js';

export const GRAPHICS_ANIMATION_CUEING_VERSION = '5.9.5';
export const GRAPHICS_ANIMATION_CUEING_PROCESSOR_ORDER = 1240;
export const GRAPHICS_ANIMATION_CUEING_COMMAND_TYPES = ['CREATE_ANIMATION','UPDATE_ANIMATION','CUE_ANIMATION','START_ANIMATION','HOLD_ANIMATION','COMPLETE_ANIMATION','CANCEL_ANIMATION','CREATE_CUE_STACK','ADVANCE_CUE_STACK','COORDINATE_TRANSITION','CLEAR_ANIMATION'] as const;
export type GraphicsAnimationCueingCommandType = (typeof GRAPHICS_ANIMATION_CUEING_COMMAND_TYPES)[number];
export type GraphicsAnimationKind = 'FADE' | 'SLIDE' | 'WIPE' | 'SCALE' | 'STINGER' | 'TICKER_ROLL' | 'SCOREBUG_UPDATE' | 'CAPTION_REVEAL' | 'CUSTOM_METADATA';
export type GraphicsAnimationLifecycle = 'CREATED' | 'CUED' | 'READY' | 'RUNNING' | 'HELD' | 'COMPLETED' | 'CANCELLED' | 'CLEARED';
export type GraphicsAnimationRole = 'PROGRAM' | 'PREVIEW' | 'CLEAN_FEED' | 'AUX' | 'ISO' | 'HORIZONTAL' | 'VERTICAL' | 'SQUARE';
export type GraphicsAnimationWatchdogIncident = 'DUPLICATE_ANIMATION' | 'DUPLICATE_CUE_STACK' | 'STALE_GENERATION' | 'INVALID_TIMING' | 'INVALID_LIFECYCLE' | 'MISSING_TARGET' | 'OVERLAP_COLLISION' | 'UNSAFE_METADATA' | 'INVARIANT_FAILURE';
type SafeMetadata = Readonly<Record<string, unknown>>;
const forbidden = /secret|token|password|credential|html|css|svg|javascript|script|sql|http|url|path|payload|bytes|native|gpu|raster|canvas|shader|timeline-bytes/i;
const safe = (m: SafeMetadata = {}) => Object.freeze(Object.fromEntries(Object.entries(m).filter(([k]) => !forbidden.test(k)).slice(0, 64)));
const deepFreeze = <T>(v: T): Readonly<T> => { if (v && typeof v === 'object' && !Object.isFrozen(v)) { Object.freeze(v); for (const c of Object.values(v as Record<string, unknown>)) deepFreeze(c); } return v as Readonly<T>; };
const cloneFreeze = <T>(v: T): Readonly<T> => deepFreeze(structuredClone(v));

export interface GraphicsAnimationDefinition { readonly id: string; readonly generation: number; readonly kind: GraphicsAnimationKind; readonly targetId: string; readonly targetType: 'GRAPHICS' | 'CAPTION' | 'ACCESSIBILITY_GRAPHIC' | 'OUTPUT_ROLE'; readonly outputRole: GraphicsAnimationRole; readonly durationNs: bigint; readonly delayNs: bigint; readonly easing: 'LINEAR' | 'EASE_IN' | 'EASE_OUT' | 'EASE_IN_OUT' | 'STEP'; readonly lifecycle: GraphicsAnimationLifecycle; readonly metadataOnly: true; readonly realRendering: false; readonly safeMetadata: SafeMetadata; }
export interface GraphicsCueStack { readonly id: string; readonly generation: number; readonly cueIds: readonly string[]; readonly currentIndex: number; readonly armed: boolean; readonly outputRole: GraphicsAnimationRole; readonly metadataOnly: true; }
export interface GraphicsTransitionCoordination { readonly id: string; readonly generation: number; readonly fromTargetId: string; readonly toTargetId: string; readonly animationIds: readonly string[]; readonly outputRole: GraphicsAnimationRole; readonly state: 'PLANNED' | 'COORDINATED' | 'RUNNING' | 'COMPLETE' | 'CANCELLED'; readonly metadataOnly: true; readonly realRendering: false; readonly safeMetadata: SafeMetadata; }
export interface GraphicsAnimationSnapshot { readonly animations: readonly GraphicsAnimationDefinition[]; readonly runningAnimations: readonly GraphicsAnimationDefinition[]; readonly cuedAnimations: readonly GraphicsAnimationDefinition[]; readonly cueStacks: readonly GraphicsCueStack[]; readonly transitions: readonly GraphicsTransitionCoordination[]; readonly outputRoleSummaries: readonly { readonly role: GraphicsAnimationRole; readonly animationIds: readonly string[]; readonly runningIds: readonly string[] }[]; readonly health: GraphicsAnimationHealth; readonly telemetry: GraphicsAnimationTelemetry; readonly watchdog: readonly GraphicsAnimationWatchdogIncident[]; readonly sourceGraph: GraphicsAnimationSourceGraph; }
export interface GraphicsAnimationHealth { readonly animations: number; readonly runningAnimations: number; readonly cuedAnimations: number; readonly cueStacks: number; readonly transitions: number; readonly rejectedCommands: number; readonly processorHealth: 'HEALTHY' | 'DEGRADED'; }
export interface GraphicsAnimationTelemetry { readonly ticksProcessed: number; readonly animationsCreated: number; readonly cuesArmed: number; readonly starts: number; readonly completions: number; readonly cancellations: number; readonly cueStackAdvances: number; readonly transitionCoordinations: number; readonly watchdogIncidents: number; readonly metadataOnly: true; readonly realRendering: false; }
export interface GraphicsAnimationSourceGraph { readonly animationIds: readonly string[]; readonly targetIds: readonly string[]; readonly outputRoles: readonly GraphicsAnimationRole[]; readonly runningPublications: readonly { readonly id: string; readonly targetId: string; readonly role: GraphicsAnimationRole; readonly kind: GraphicsAnimationKind }[]; readonly metadataOnly: true; readonly realRendering: false; }
export class GraphicsAnimationCueingError extends Error { constructor(readonly code: GraphicsAnimationWatchdogIncident | string, message: string) { super(message); this.name = code; } }

export class GraphicsAnimationCueingEngine {
  private animations = new Map<string, Readonly<GraphicsAnimationDefinition>>(); private stacks = new Map<string, Readonly<GraphicsCueStack>>(); private transitions = new Map<string, Readonly<GraphicsTransitionCoordination>>(); private incidents: GraphicsAnimationWatchdogIncident[] = []; private ticks = 0; private telemetry = { animationsCreated:0, cuesArmed:0, starts:0, completions:0, cancellations:0, cueStackAdvances:0, transitionCoordinations:0 };
  createAnimation(def: GraphicsAnimationDefinition) { if (this.animations.has(def.id)) return this.incident('DUPLICATE_ANIMATION', `duplicate animation ${def.id}`); if (!def.targetId) return this.incident('MISSING_TARGET', 'targetId is required'); if (def.generation < 1 || def.durationNs <= 0n || def.delayNs < 0n) return this.incident('INVALID_TIMING', `invalid animation timing ${def.id}`); const n = cloneFreeze({ ...def, safeMetadata:safe(def.safeMetadata), metadataOnly:true as const, realRendering:false as const }); this.animations.set(n.id, n); this.telemetry.animationsCreated++; return n; }
  updateAnimation(id: string, generation: number, patch: Partial<GraphicsAnimationDefinition>) { const cur = this.mustAnimation(id); if (generation <= cur.generation) return this.incident('STALE_GENERATION', `stale animation ${id}`); const n = cloneFreeze({ ...cur, ...patch, id, generation, safeMetadata:safe(patch.safeMetadata ?? cur.safeMetadata), metadataOnly:true as const, realRendering:false as const }); this.animations.set(id, n); return n; }
  cueAnimation(id: string, generation: number) { this.telemetry.cuesArmed++; return this.lifecycle(id, generation, 'CUED'); }
  startAnimation(id: string, generation: number) { const cur = this.mustAnimation(id); if (!['CUED','READY','HELD'].includes(cur.lifecycle)) return this.incident('INVALID_LIFECYCLE', `animation ${id} is not cue-ready`); this.telemetry.starts++; return this.lifecycle(id, generation, 'RUNNING'); }
  holdAnimation(id: string, generation: number) { return this.lifecycle(id, generation, 'HELD'); }
  completeAnimation(id: string, generation: number) { this.telemetry.completions++; return this.lifecycle(id, generation, 'COMPLETED'); }
  cancelAnimation(id: string, generation: number) { this.telemetry.cancellations++; return this.lifecycle(id, generation, 'CANCELLED'); }
  clearAnimation(id: string, generation: number) { return this.lifecycle(id, generation, 'CLEARED'); }
  createCueStack(stack: GraphicsCueStack) { if (this.stacks.has(stack.id)) return this.incident('DUPLICATE_CUE_STACK', `duplicate cue stack ${stack.id}`); for (const cueId of stack.cueIds) if (!this.animations.has(cueId)) return this.incident('MISSING_TARGET', `unknown cue ${cueId}`); const n = cloneFreeze({ ...stack, currentIndex:Math.max(0, stack.currentIndex), metadataOnly:true as const }); this.stacks.set(n.id, n); return n; }
  advanceCueStack(id: string, generation: number) { const cur = this.mustStack(id); if (generation <= cur.generation) return this.incident('STALE_GENERATION', `stale stack ${id}`); const nextIndex = Math.min(cur.cueIds.length, cur.currentIndex + 1); const cueId = cur.cueIds[cur.currentIndex]; if (cueId) this.cueAnimation(cueId, this.mustAnimation(cueId).generation + 1); const n = cloneFreeze({ ...cur, generation, currentIndex:nextIndex, armed:nextIndex < cur.cueIds.length }); this.stacks.set(id, n); this.telemetry.cueStackAdvances++; return n; }
  coordinateTransition(t: GraphicsTransitionCoordination) { if (t.generation < 1 || !t.fromTargetId || !t.toTargetId) return this.incident('MISSING_TARGET', `invalid transition ${t.id}`); for (const animationId of t.animationIds) if (!this.animations.has(animationId)) return this.incident('MISSING_TARGET', `unknown transition animation ${animationId}`); const n = cloneFreeze({ ...t, state:'COORDINATED' as const, safeMetadata:safe(t.safeMetadata), metadataOnly:true as const, realRendering:false as const }); this.transitions.set(n.id, n); this.telemetry.transitionCoordinations++; return n; }
  processFrame(tick?: FrameTick, publishSnapshot = true) { this.ticks++; const now = tick?.presentationTimeNs; if (now !== undefined) for (const a of this.animations.values()) if (a.lifecycle === 'RUNNING' && a.delayNs + a.durationNs <= now) this.completeAnimation(a.id, a.generation + 1); return publishSnapshot ? this.snapshot() : undefined; }
  snapshot(): Readonly<GraphicsAnimationSnapshot> { const animations=[...this.animations.values()], running=animations.filter((a)=>a.lifecycle==='RUNNING'), cued=animations.filter((a)=>a.lifecycle==='CUED'), roles=[...new Set(animations.map((a)=>a.outputRole))] as GraphicsAnimationRole[]; return cloneFreeze({ animations, runningAnimations:running, cuedAnimations:cued, cueStacks:[...this.stacks.values()], transitions:[...this.transitions.values()], outputRoleSummaries:roles.map((role)=>({ role, animationIds:animations.filter((a)=>a.outputRole===role).map((a)=>a.id), runningIds:running.filter((a)=>a.outputRole===role).map((a)=>a.id) })), health:{ animations:animations.length, runningAnimations:running.length, cuedAnimations:cued.length, cueStacks:this.stacks.size, transitions:this.transitions.size, rejectedCommands:this.incidents.length, processorHealth:this.incidents.length?'DEGRADED':'HEALTHY' }, telemetry:{ ticksProcessed:this.ticks, ...this.telemetry, watchdogIncidents:this.incidents.length, metadataOnly:true, realRendering:false }, watchdog:this.incidents, sourceGraph:{ animationIds:animations.map((a)=>a.id), targetIds:[...new Set(animations.map((a)=>a.targetId))], outputRoles:roles, runningPublications:running.map((a)=>({ id:a.id, targetId:a.targetId, role:a.outputRole, kind:a.kind })), metadataOnly:true, realRendering:false } }); }
  reset() { this.animations.clear(); this.stacks.clear(); this.transitions.clear(); this.incidents=[]; }
  commandHandlers(): Record<GraphicsAnimationCueingCommandType, RuntimeCommandHandler> { const h = (fn:(p:Record<string, unknown>)=>unknown): RuntimeCommandHandler => (cmd: RuntimeCommand) => { fn((cmd.payload ?? {}) as Record<string, unknown>); }; return { CREATE_ANIMATION:h((p)=>this.createAnimation(p.animation as GraphicsAnimationDefinition)), UPDATE_ANIMATION:h((p)=>this.updateAnimation(String(p.id), Number(p.generation), p.patch as Partial<GraphicsAnimationDefinition>)), CUE_ANIMATION:h((p)=>this.cueAnimation(String(p.id), Number(p.generation))), START_ANIMATION:h((p)=>this.startAnimation(String(p.id), Number(p.generation))), HOLD_ANIMATION:h((p)=>this.holdAnimation(String(p.id), Number(p.generation))), COMPLETE_ANIMATION:h((p)=>this.completeAnimation(String(p.id), Number(p.generation))), CANCEL_ANIMATION:h((p)=>this.cancelAnimation(String(p.id), Number(p.generation))), CREATE_CUE_STACK:h((p)=>this.createCueStack(p.stack as GraphicsCueStack)), ADVANCE_CUE_STACK:h((p)=>this.advanceCueStack(String(p.id), Number(p.generation))), COORDINATE_TRANSITION:h((p)=>this.coordinateTransition(p.transition as GraphicsTransitionCoordination)), CLEAR_ANIMATION:h((p)=>this.clearAnimation(String(p.id), Number(p.generation))) }; }
  private mustAnimation(id: string) { const a = this.animations.get(id); if (!a) throw new GraphicsAnimationCueingError('INVARIANT_FAILURE', `unknown animation ${id}`); return a; }
  private mustStack(id: string) { const s = this.stacks.get(id); if (!s) throw new GraphicsAnimationCueingError('INVARIANT_FAILURE', `unknown cue stack ${id}`); return s; }
  private lifecycle(id: string, generation: number, lifecycle: GraphicsAnimationLifecycle) { const cur = this.mustAnimation(id); if (generation < cur.generation) return this.incident('STALE_GENERATION', `stale animation ${id}`); const n = cloneFreeze({ ...cur, generation, lifecycle }); this.animations.set(id, n); return n; }
  private incident(i: GraphicsAnimationWatchdogIncident, m: string): never { this.incidents.push(i); throw new GraphicsAnimationCueingError(i, m); }
}
export const createGraphicsAnimationCueingEngine = () => new GraphicsAnimationCueingEngine();
export const createGraphicsAnimationCueingCommandHandlers = (engine: GraphicsAnimationCueingEngine) => engine.commandHandlers();
export class GraphicsAnimationCueingProcessor implements TickProcessor { readonly descriptor: TickProcessorDescriptor = { id:'graphics-animation-cueing-processor', name:'GraphicsAnimationCueingProcessor', version:GRAPHICS_ANIMATION_CUEING_VERSION, order:GRAPHICS_ANIMATION_CUEING_PROCESSOR_ORDER, phase:'GRAPHICS', workloadClass:'BEST_EFFORT', enabledByDefault:true, dependencies:['caption-accessibility-graphics-processor','broadcast-graphics-processor','graphics-template-processor','graphics-foundation-processor'], optionalCapabilities:['graphics-cueing','animation-coordination','transition-metadata','source-graph-metadata'], estimatedBudgetNs:500000n, maximumBudgetNs:2000000n, timeoutNs:5000000n, maySkipUnderLoad:false, failurePolicy:'DEGRADE_PROCESSOR', criticality:'OPERATIONAL', supportsHotDisable:true, supportsHotEnable:true, supportsHotReplacement:true, statePersistencePolicy:'RETAIN_UNTIL_SHUTDOWN', metadata:{ metadataOnly:true, realRendering:false } }; constructor(readonly engine = createGraphicsAnimationCueingEngine()) {} initialize() { return { status:'READY' as const, state:this.engine.snapshot() }; } processTick(tick: FrameTick, context?: RuntimeContext | ProcessorRuntimeContext) { const snapshot=this.engine.processFrame(tick); context && 'outputs' in context && context.outputs?.publish(this.descriptor.id, 'graphics-animation-cueing', snapshot, 'BORROWED'); return { status:'SUCCEEDED' as const, value:snapshot, metadata:{ metadataOnly:true, realRendering:false } }; } shutdown() { this.engine.reset(); return { status:'STOPPED' as const, metadata:{ cleanup:'complete' } }; } }
export const createGraphicsAnimationCueingProcessor = (engine?: GraphicsAnimationCueingEngine) => new GraphicsAnimationCueingProcessor(engine);
