import { createRenderLayer, type RenderLayer, type SceneCompositor } from './compositor/index.js';
import type { GpuRuntime } from './gpu-runtime/index.js';
import type { PreviewOutput, ProgramOutput } from './output-pipeline.js';

export type GraphicsObjectType = 'text' | 'image' | 'rectangle' | 'circle' | 'svg';
export type OverlayType = 'lower_third' | 'name_strap' | 'logo' | 'watermark' | 'qr_code' | 'countdown_timer';
export type GraphicsEventType = 'graphics_engine_created' | 'object_added' | 'object_updated' | 'object_removed' | 'overlay_added' | 'overlay_removed' | 'overlay_rendered';
export interface GraphicsTransform { readonly position: { readonly x: number; readonly y: number }; readonly size: { readonly width: number; readonly height: number }; readonly opacity: number; readonly rotation: number; readonly visible: boolean; readonly zOrder: number; }
export interface GraphicsObject { readonly id: string; readonly type: GraphicsObjectType; readonly label: string; readonly transform: GraphicsTransform; readonly content: Record<string, unknown>; readonly metadata: Record<string, unknown>; }
export interface Overlay { readonly id: string; readonly type: OverlayType; readonly label: string; readonly objectIds: readonly string[]; readonly visible: boolean; readonly metadata: Record<string, unknown>; }
export interface GraphicsRuntimeEvent { readonly id: string; readonly type: GraphicsEventType; readonly timestamp: string; readonly message: string; readonly objectId?: string; readonly overlayId?: string; readonly metadata: Record<string, unknown>; }
export interface GraphicsEngineSnapshot { readonly id: string; readonly objects: readonly GraphicsObject[]; readonly overlays: readonly Overlay[]; readonly events: readonly GraphicsRuntimeEvent[]; readonly rendererBackend?: string; readonly outputIds: { readonly preview?: string; readonly program?: string }; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export type GraphicsObjectPatch = Partial<Omit<GraphicsObject, 'id' | 'transform'>> & { readonly transform?: Partial<GraphicsTransform> };
export interface GraphicsEngine { readonly id: string; addObject(object: GraphicsObject): GraphicsObject; updateObject(id: string, patch: GraphicsObjectPatch): GraphicsObject; removeObject(id: string): boolean; addOverlay(overlay: Overlay): Overlay; removeOverlay(id: string): boolean; renderOverlay(id: string, compositor?: SceneCompositor): readonly RenderLayer[]; getSnapshot(): GraphicsEngineSnapshot; getRuntimeEvents(): readonly GraphicsRuntimeEvent[]; onRuntimeEvent(callback: (event: GraphicsRuntimeEvent) => void): () => void; }

const now = () => new Date().toISOString();
const eid = (type: GraphicsEventType) => `${type}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const clamp = (value: number) => Math.max(0, Math.min(1, Number.isFinite(value) ? value : 1));
export const defaultGraphicsTransform = (patch: Partial<GraphicsTransform> = {}): GraphicsTransform => ({ position: { x: 0, y: 0, ...(patch.position ?? {}) }, size: { width: 320, height: 120, ...(patch.size ?? {}) }, opacity: clamp(patch.opacity ?? 1), rotation: patch.rotation ?? 0, visible: patch.visible ?? true, zOrder: patch.zOrder ?? 1000 });
export function createGraphicsObject(input: Partial<GraphicsObject> & { id: string; type: GraphicsObjectType }): GraphicsObject { return Object.freeze({ ...input, label: input.label ?? input.id, transform: defaultGraphicsTransform(input.transform), content: clone(input.content ?? {}), metadata: clone(input.metadata ?? {}) }); }
export function createOverlay(input: Partial<Overlay> & { id: string; type: OverlayType; objectIds: readonly string[] }): Overlay { return Object.freeze({ ...input, label: input.label ?? input.id, visible: input.visible ?? true, objectIds: Object.freeze([...input.objectIds]), metadata: clone(input.metadata ?? {}) }); }
export function graphicsObjectToRenderLayer(object: GraphicsObject, overlay?: Overlay): RenderLayer { return createRenderLayer({ id: `graphics:${object.id}`, label: object.label, source: { type: 'graphics', sourceId: object.id, label: object.label, metadata: { objectType: object.type, content: clone(object.content), ...(overlay ? { overlayId: overlay.id, overlayType: overlay.type } : {}) } }, position: object.transform.position, size: object.transform.size, rotation: object.transform.rotation, opacity: object.transform.opacity, visible: object.transform.visible && (overlay?.visible ?? true), enabled: true, locked: false, zIndex: object.transform.zOrder, metadata: { graphicsObjectId: object.id, objectType: object.type, ...(overlay ? { overlayId: overlay.id, overlayType: overlay.type } : {}), ...clone(object.metadata) } }); }
export function createGraphicsEngine(input: { id?: string; compositor?: SceneCompositor; renderer?: GpuRuntime; previewOutput?: PreviewOutput; programOutput?: ProgramOutput; objects?: readonly GraphicsObject[]; overlays?: readonly Overlay[]; metadata?: Record<string, unknown> } = {}): GraphicsEngine {
  const id = input.id ?? 'graphics-engine:default'; const objects = new Map(input.objects?.map((o) => [o.id, createGraphicsObject(o)]) ?? []); const overlays = new Map(input.overlays?.map((o) => [o.id, createOverlay(o)]) ?? []); let events: GraphicsRuntimeEvent[] = []; const listeners = new Set<(event: GraphicsRuntimeEvent) => void>();
  const emit = (type: GraphicsEventType, message: string, extra: Partial<GraphicsRuntimeEvent> = {}) => { const event = Object.freeze({ id: eid(type), type, timestamp: now(), message, metadata: clone(extra.metadata ?? {}), ...(extra.objectId ? { objectId: extra.objectId } : {}), ...(extra.overlayId ? { overlayId: extra.overlayId } : {}) }); events = [event, ...events].slice(0, 200); listeners.forEach((cb) => cb(event)); return event; };
  emit('graphics_engine_created', `Graphics engine ${id} created`, { metadata: input.metadata ?? {} });
  return { id, addObject(object) { const next = createGraphicsObject(object); objects.set(next.id, next); emit('object_added', `Graphics object ${next.id} added`, { objectId: next.id }); return next; }, updateObject(objectId, patch) { const current = objects.get(objectId); if (!current) throw new Error(`Unknown graphics object ${objectId}`); const next = createGraphicsObject({ ...current, ...patch, id: objectId, type: patch.type ?? current.type, transform: defaultGraphicsTransform({ ...current.transform, ...(patch.transform ?? {}) }), content: patch.content ?? current.content, metadata: patch.metadata ?? current.metadata }); objects.set(objectId, next); emit('object_updated', `Graphics object ${objectId} updated`, { objectId }); return next; }, removeObject(objectId) { const removed = objects.delete(objectId); if (removed) emit('object_removed', `Graphics object ${objectId} removed`, { objectId }); return removed; }, addOverlay(overlay) { const next = createOverlay(overlay); overlays.set(next.id, next); emit('overlay_added', `Overlay ${next.id} added`, { overlayId: next.id }); return next; }, removeOverlay(overlayId) { const removed = overlays.delete(overlayId); if (removed) emit('overlay_removed', `Overlay ${overlayId} removed`, { overlayId }); return removed; }, renderOverlay(overlayId, compositor = input.compositor) { const overlay = overlays.get(overlayId); if (!overlay) throw new Error(`Unknown overlay ${overlayId}`); const layers = overlay.objectIds.map((objectId) => objects.get(objectId)).filter(Boolean).map((object) => graphicsObjectToRenderLayer(object!, overlay)); layers.forEach((layer) => compositor?.addLayer(layer)); emit('overlay_rendered', `Overlay ${overlayId} rendered`, { overlayId, metadata: { layerCount: layers.length, rendererBackend: input.renderer?.manifest.diagnostics.backend } }); return Object.freeze(layers); }, getSnapshot() { return Object.freeze({ id, objects: Object.freeze([...objects.values()]), overlays: Object.freeze([...overlays.values()]), events: Object.freeze([...events]), ...(input.renderer ? { rendererBackend: input.renderer.manifest.diagnostics.backend } : {}), outputIds: { ...(input.previewOutput ? { preview: input.previewOutput.id } : {}), ...(input.programOutput ? { program: input.programOutput.id } : {}) }, containsRuntimeHandles: false, containsMediaPayloads: false }); }, getRuntimeEvents: () => Object.freeze([...events]), onRuntimeEvent(callback) { listeners.add(callback); return () => listeners.delete(callback); } };
}
export function createGraphicsOverlayDemo() { const lower = createGraphicsObject({ id: 'lower-third-title', type: 'text', label: 'Lower third title', transform: defaultGraphicsTransform({ position: { x: 120, y: 820 }, size: { width: 900, height: 90 }, zOrder: 2000 }), content: { text: 'Alex Rivera', fontSize: 48 } }); const logo = createGraphicsObject({ id: 'show-logo', type: 'image', label: 'Show logo', transform: defaultGraphicsTransform({ position: { x: 1660, y: 60 }, size: { width: 180, height: 90 }, zOrder: 2100 }), content: { uri: 'asset://logos/ubos-live.png' } }); const qr = createGraphicsObject({ id: 'viewer-qr', type: 'svg', label: 'Viewer QR code', transform: defaultGraphicsTransform({ position: { x: 1600, y: 760 }, size: { width: 220, height: 220 }, zOrder: 2200 }), content: { purpose: 'qr_code', value: 'https://ubos.example/live' } }); const countdown = createGraphicsObject({ id: 'countdown', type: 'text', label: 'Countdown timer', transform: defaultGraphicsTransform({ position: { x: 860, y: 80 }, size: { width: 220, height: 80 }, zOrder: 2300 }), content: { secondsRemaining: 300, format: 'mm:ss' } }); const overlay = createOverlay({ id: 'demo-graphics-package', type: 'lower_third', label: 'Demo lower third, logo, QR, countdown', objectIds: [lower.id, logo.id, qr.id, countdown.id], metadata: { includes: ['lower_third', 'logo', 'qr_code', 'countdown_timer'] } }); const engine = createGraphicsEngine({ objects: [lower, logo, qr, countdown], overlays: [overlay], metadata: { phase: '2.16' } }); return { engine, overlay, objects: [lower, logo, qr, countdown], layers: engine.renderOverlay(overlay.id) }; }
