import type { SceneCompositor } from './compositor/index.js';
import type { ProductionSwitcher } from './production-switcher.js';
import type { RecordingPipelineV2 } from './recording-runtime/index.js';
import type { StreamingPipelineV2 } from './streaming-runtime/index.js';

const now = () => new Date().toISOString();
const eventId = (type: string) => `${type}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

export type HardwareDeviceCategory = 'production_switcher' | 'ptz_camera' | 'capture_device' | 'audio_interface' | 'control_surface';
export type HardwareIntegrationVendor = 'blackmagic_atem' | 'ross' | 'vizrt' | 'sony' | 'panasonic' | 'ptzoptics' | 'birddog' | 'stream_deck' | 'x_keys';
export type HardwareDeviceLifecycle = 'discovered' | 'connecting' | 'connected' | 'disconnected' | 'failed';
export type HardwareIntegrationHealth = 'healthy' | 'degraded' | 'unreachable' | 'failed';
export type HardwareConnectionKind = 'mock_network' | 'mock_usb' | 'mock_hid' | 'metadata_only';
export type HardwareRuntimeEventType = 'hardware_adapter_registered' | 'hardware_discovery_started' | 'hardware_device_discovered' | 'hardware_device_connecting' | 'hardware_device_connected' | 'hardware_device_disconnected' | 'hardware_device_failed' | 'hardware_heartbeat' | 'hardware_bindings_updated' | 'hardware_command_planned';

export interface DeviceCapabilities { readonly inputs: number; readonly outputs: number; readonly supportsTally: boolean; readonly supportsPtz: boolean; readonly supportsAudioMeters: boolean; readonly supportsMacros: boolean; readonly supportsButtons: boolean; readonly supportsEncoders: boolean; readonly supportsCapture: boolean; readonly protocols: readonly string[]; readonly metadata: Readonly<Record<string, unknown>>; readonly backendIndependent: true; }
export interface HardwareConnectionStatus { readonly lifecycle: HardwareDeviceLifecycle; readonly connected: boolean; readonly lastChangedAt: string; readonly message: string; }
export interface HardwareHeartbeat { readonly lastSeenAt?: string; readonly intervalMs: number; readonly missedCount: number; }
export interface HardwareDevice { readonly id: string; readonly label: string; readonly vendor: HardwareIntegrationVendor; readonly category: HardwareDeviceCategory; readonly model: string; readonly firmwareVersion?: string; readonly capabilities: DeviceCapabilities; readonly connection: HardwareConnectionStatus; readonly health: HardwareIntegrationHealth; readonly heartbeat: HardwareHeartbeat; readonly adapterId?: string; readonly metadata: Readonly<Record<string, unknown>>; readonly containsRuntimeHandles: false; readonly containsDeviceHandles: false; }
export interface HardwareRuntimeEvent { readonly id: string; readonly type: HardwareRuntimeEventType; readonly timestamp: string; readonly deviceId?: string; readonly adapterId?: string; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; readonly containsRuntimeHandles: false; readonly containsDeviceHandles: false; }
export interface HardwareAdapter { readonly id: string; readonly label: string; readonly vendors: readonly HardwareIntegrationVendor[]; readonly categories: readonly HardwareDeviceCategory[]; discover(): Promise<readonly HardwareDevice[]> | readonly HardwareDevice[]; connect(device: HardwareDevice): Promise<HardwareDevice> | HardwareDevice; disconnect(device: HardwareDevice): Promise<HardwareDevice> | HardwareDevice; heartbeat?(device: HardwareDevice): Promise<HardwareDevice> | HardwareDevice; }
export interface HardwareManagerBindings { readonly productionSwitcher?: ProductionSwitcher; readonly sceneCompositor?: SceneCompositor; readonly remoteProductionManager?: { readonly id?: string; getSnapshot?(): unknown }; readonly transportManager?: { readonly id?: string; diagnostics?(): unknown; getSnapshot?(): unknown }; readonly streamingPipeline?: StreamingPipelineV2 | { readonly sessions?: { list(): unknown[] }; getSnapshot?(): unknown }; readonly recordingPipeline?: RecordingPipelineV2; }
export interface HardwareManagerSnapshot { readonly id: string; readonly devices: readonly HardwareDevice[]; readonly adapters: readonly Pick<HardwareAdapter, 'id' | 'label' | 'vendors' | 'categories'>[]; readonly bindings: Readonly<Record<string, string | boolean>>; readonly events: readonly HardwareRuntimeEvent[]; readonly containsRuntimeHandles: false; readonly containsDeviceHandles: false; }

export const supportedHardwareIntegrationVendors: readonly HardwareIntegrationVendor[] = Object.freeze(['blackmagic_atem','ross','vizrt','sony','panasonic','ptzoptics','birddog','stream_deck','x_keys']);
export const supportedHardwareCategories: readonly HardwareDeviceCategory[] = Object.freeze(['production_switcher','ptz_camera','capture_device','audio_interface','control_surface']);

export function createDeviceCapabilities(input: Partial<DeviceCapabilities> = {}): DeviceCapabilities { return Object.freeze({ inputs: input.inputs ?? 0, outputs: input.outputs ?? 0, supportsTally: input.supportsTally ?? false, supportsPtz: input.supportsPtz ?? false, supportsAudioMeters: input.supportsAudioMeters ?? false, supportsMacros: input.supportsMacros ?? false, supportsButtons: input.supportsButtons ?? false, supportsEncoders: input.supportsEncoders ?? false, supportsCapture: input.supportsCapture ?? false, protocols: Object.freeze([...(input.protocols ?? ['metadata'])]), metadata: Object.freeze(clone(input.metadata ?? {})), backendIndependent: true }); }
export function createHardwareIntegrationDevice(input: { id: string; label: string; vendor: HardwareIntegrationVendor; category: HardwareDeviceCategory; model: string; firmwareVersion?: string; capabilities?: Partial<DeviceCapabilities>; adapterId?: string; metadata?: Record<string, unknown>; lifecycle?: HardwareDeviceLifecycle; health?: HardwareIntegrationHealth; }): HardwareDevice { const lifecycle = input.lifecycle ?? 'discovered'; return Object.freeze({ id: input.id, label: input.label, vendor: input.vendor, category: input.category, model: input.model, ...(input.firmwareVersion ? { firmwareVersion: input.firmwareVersion } : {}), capabilities: createDeviceCapabilities(input.capabilities), connection: Object.freeze({ lifecycle, connected: lifecycle === 'connected', lastChangedAt: now(), message: lifecycle }), health: input.health ?? (lifecycle === 'failed' ? 'failed' : 'healthy'), heartbeat: Object.freeze({ intervalMs: 5000, missedCount: 0 }), ...(input.adapterId ? { adapterId: input.adapterId } : {}), metadata: Object.freeze(clone(input.metadata ?? {})), containsRuntimeHandles: false, containsDeviceHandles: false }); }
function patchDevice(device: HardwareDevice, patch: Partial<HardwareDevice>, message = patch.connection?.message ?? device.connection.message): HardwareDevice { const lifecycle = patch.connection?.lifecycle ?? device.connection.lifecycle; return Object.freeze({ ...device, ...patch, connection: Object.freeze({ lifecycle, connected: lifecycle === 'connected', lastChangedAt: now(), message }), capabilities: patch.capabilities ?? device.capabilities, heartbeat: patch.heartbeat ?? device.heartbeat, metadata: Object.freeze(clone({ ...device.metadata, ...(patch.metadata ?? {}) })), containsRuntimeHandles: false, containsDeviceHandles: false }); }

export class MetadataHardwareAdapter implements HardwareAdapter { constructor(readonly id = 'hardware-adapter:metadata-demo', readonly label = 'Metadata-only Hardware Adapter', private readonly seedDevices: readonly HardwareDevice[] = demoHardwareDevices(id)) {} readonly vendors = supportedHardwareIntegrationVendors; readonly categories = supportedHardwareCategories; discover() { return this.seedDevices.map((device) => patchDevice(device, { adapterId: this.id, connection: { ...device.connection, lifecycle: 'discovered' } }, 'Discovered by metadata adapter')); } connect(device: HardwareDevice) { return patchDevice(device, { adapterId: this.id, connection: { ...device.connection, lifecycle: 'connected' }, health: 'healthy' }, 'Connected metadata-only device'); } disconnect(device: HardwareDevice) { return patchDevice(device, { connection: { ...device.connection, lifecycle: 'disconnected' }, health: 'unreachable' }, 'Disconnected metadata-only device'); } heartbeat(device: HardwareDevice) { return patchDevice(device, { heartbeat: { ...device.heartbeat, lastSeenAt: now(), missedCount: 0 }, health: device.connection.connected ? 'healthy' : device.health }, 'Heartbeat recorded'); } }

export class HardwareManager { private adapters = new Map<string, HardwareAdapter>(); private devices = new Map<string, HardwareDevice>(); private events: HardwareRuntimeEvent[] = []; private listeners = new Set<(event: HardwareRuntimeEvent) => void>(); private bindings: HardwareManagerBindings = {}; constructor(readonly id = 'hardware-manager:program', bindings: HardwareManagerBindings = {}) { this.bind(bindings); }
  registerAdapter(adapter: HardwareAdapter) { this.adapters.set(adapter.id, adapter); this.emit('hardware_adapter_registered', `Registered ${adapter.label}`, { adapterId: adapter.id, metadata: { vendors: adapter.vendors, categories: adapter.categories } }); return adapter; }
  bind(bindings: HardwareManagerBindings) { this.bindings = { ...this.bindings, ...bindings }; this.emit('hardware_bindings_updated', 'Hardware runtime bindings updated', { metadata: this.bindingSummary() }); return this.bindingSummary(); }
  async discover() { this.emit('hardware_discovery_started', 'Hardware discovery started'); const discovered: HardwareDevice[] = []; for (const adapter of this.adapters.values()) for (const device of await adapter.discover()) { this.devices.set(device.id, device); discovered.push(device); this.emit('hardware_device_discovered', `Discovered ${device.label}`, { deviceId: device.id, adapterId: adapter.id, metadata: { vendor: device.vendor, category: device.category } }); } return discovered; }
  async connect(deviceId: string) { const current = this.must(deviceId); const adapter = this.adapterFor(current); const connecting = patchDevice(current, { connection: { ...current.connection, lifecycle: 'connecting' } }, 'Connecting metadata-only device'); this.devices.set(deviceId, connecting); this.emit('hardware_device_connecting', `Connecting ${connecting.label}`, { deviceId, adapterId: adapter.id }); const connected = await adapter.connect(connecting); this.devices.set(deviceId, connected); this.emit('hardware_device_connected', `Connected ${connected.label}`, { deviceId, adapterId: adapter.id, metadata: this.integrationMetadata(connected) }); return connected; }
  async disconnect(deviceId: string) { const current = this.must(deviceId); const adapter = this.adapterFor(current); const disconnected = await adapter.disconnect(current); this.devices.set(deviceId, disconnected); this.emit('hardware_device_disconnected', `Disconnected ${disconnected.label}`, { deviceId, adapterId: adapter.id }); return disconnected; }
  fail(deviceId: string, message: string) { const failed = patchDevice(this.must(deviceId), { connection: { ...this.must(deviceId).connection, lifecycle: 'failed' }, health: 'failed' }, message); this.devices.set(deviceId, failed); this.emit('hardware_device_failed', message, { deviceId, metadata: { health: failed.health } }); return failed; }
  async heartbeat(deviceId: string) { const current = this.must(deviceId); const adapter = this.adapterFor(current); const next = adapter.heartbeat ? await adapter.heartbeat(current) : patchDevice(current, { heartbeat: { ...current.heartbeat, lastSeenAt: now() } }, 'Heartbeat recorded'); this.devices.set(deviceId, next); this.emit('hardware_heartbeat', `Heartbeat ${next.label}`, { deviceId, adapterId: adapter.id, metadata: { health: next.health } }); return next; }
  planCommand(deviceId: string, command: string, metadata: Record<string, unknown> = {}) { const device = this.must(deviceId); return this.emit('hardware_command_planned', `Planned ${command} for ${device.label}`, { deviceId, metadata: { command, category: device.category, vendor: device.vendor, ...metadata, backendIndependent: true } }); }
  getDevice(id: string) { return this.devices.get(id); } listDevices() { return Object.freeze([...this.devices.values()]); } getEvents() { return Object.freeze([...this.events]); } onRuntimeEvent(callback: (event: HardwareRuntimeEvent) => void) { this.listeners.add(callback); return () => this.listeners.delete(callback); }
  getSnapshot(): HardwareManagerSnapshot { return Object.freeze({ id: this.id, devices: this.listDevices(), adapters: [...this.adapters.values()].map(({ id, label, vendors, categories }) => ({ id, label, vendors, categories })), bindings: Object.freeze(this.bindingSummary()), events: this.getEvents(), containsRuntimeHandles: false, containsDeviceHandles: false }); }
  private must(id: string) { const device = this.devices.get(id); if (!device) throw new Error(`Hardware device ${id} not found`); return device; } private adapterFor(device: HardwareDevice) { const adapter = this.adapters.get(device.adapterId ?? '') ?? [...this.adapters.values()].find((a) => a.vendors.includes(device.vendor) && a.categories.includes(device.category)); if (!adapter) throw new Error(`No hardware adapter registered for ${device.vendor}/${device.category}`); return adapter; }
  private bindingSummary() { return { productionSwitcher: Boolean(this.bindings.productionSwitcher), productionSwitcherId: this.bindings.productionSwitcher?.id ?? '', sceneCompositor: Boolean(this.bindings.sceneCompositor), sceneCompositorId: this.bindings.sceneCompositor?.id ?? '', remoteProductionManager: Boolean(this.bindings.remoteProductionManager), remoteProductionManagerId: this.bindings.remoteProductionManager?.id ?? '', transportManager: Boolean(this.bindings.transportManager), transportManagerId: this.bindings.transportManager?.id ?? '', streamingPipeline: Boolean(this.bindings.streamingPipeline), streamingPipelineId: this.bindings.streamingPipeline && 'id' in this.bindings.streamingPipeline ? String(this.bindings.streamingPipeline.id) : '', recordingPipeline: Boolean(this.bindings.recordingPipeline), recordingPipelineId: this.bindings.recordingPipeline?.id ?? '' }; }
  private integrationMetadata(device: HardwareDevice) { return { bindings: this.bindingSummary(), deviceCategory: device.category, integrationMode: 'metadata_only', controlsRealHardware: false }; }
  private emit(type: HardwareRuntimeEventType, message: string, extra: Partial<HardwareRuntimeEvent> = {}) { const event = Object.freeze({ id: eventId(type), type, timestamp: now(), ...(extra.deviceId ? { deviceId: extra.deviceId } : {}), ...(extra.adapterId ? { adapterId: extra.adapterId } : {}), message, metadata: Object.freeze(clone(extra.metadata ?? {})), containsRuntimeHandles: false, containsDeviceHandles: false }); this.events.unshift(event); this.listeners.forEach((listener) => listener(event)); return event; }
}

export function demoHardwareDevices(adapterId = 'hardware-adapter:metadata-demo') { return Object.freeze([
  createHardwareIntegrationDevice({ id: 'hardware-device:atem:mini-extreme', label: 'ATEM Mini Extreme', vendor: 'blackmagic_atem', category: 'production_switcher', model: 'ATEM Mini Extreme ISO', firmwareVersion: 'metadata-9.5', adapterId, capabilities: { inputs: 8, outputs: 2, supportsTally: true, supportsMacros: true, protocols: ['atem-metadata'] } }),
  createHardwareIntegrationDevice({ id: 'hardware-device:ptzoptics:studio-a', label: 'PTZOptics Studio A', vendor: 'ptzoptics', category: 'ptz_camera', model: 'Move 4K', firmwareVersion: 'metadata-1.2', adapterId, capabilities: { inputs: 1, outputs: 1, supportsPtz: true, protocols: ['visca-metadata'] } }),
  createHardwareIntegrationDevice({ id: 'hardware-device:streamdeck:director', label: 'Director Stream Deck', vendor: 'stream_deck', category: 'control_surface', model: 'Stream Deck XL', firmwareVersion: 'metadata-6.0', adapterId, capabilities: { supportsButtons: true, supportsMacros: true, protocols: ['hid-metadata'] } }),
  createHardwareIntegrationDevice({ id: 'hardware-device:sony:capture-a', label: 'Sony Capture Input A', vendor: 'sony', category: 'capture_device', model: 'Metadata Capture Bridge', firmwareVersion: 'metadata-2.0', adapterId, capabilities: { inputs: 1, outputs: 1, supportsCapture: true, protocols: ['sdi-metadata'] } }),
  createHardwareIntegrationDevice({ id: 'hardware-device:ross:audio-a', label: 'Ross Audio Interface A', vendor: 'ross', category: 'audio_interface', model: 'Metadata Audio I/O', firmwareVersion: 'metadata-3.1', adapterId, capabilities: { inputs: 16, outputs: 16, supportsAudioMeters: true, protocols: ['audio-metadata'] } }),
]); }
export function createHardwareManager(input: { id?: string; bindings?: HardwareManagerBindings; adapters?: readonly HardwareAdapter[] } = {}) { const manager = new HardwareManager(input.id, input.bindings); (input.adapters ?? [new MetadataHardwareAdapter()]).forEach((adapter) => manager.registerAdapter(adapter)); return manager; }
export async function createHardwareIntegrationDemo(bindings: HardwareManagerBindings = {}) { const manager = createHardwareManager({ id: 'hardware-manager:demo', bindings }); const devices = await manager.discover(); const connected = await manager.connect(devices[0]!.id); await manager.heartbeat(connected.id); manager.planCommand(connected.id, 'preview-input', { input: 1 }); await manager.disconnect(connected.id); return { manager: manager.getSnapshot(), connectedDevice: connected, events: manager.getEvents(), description: 'HardwareManager models metadata-only broadcast devices, lifecycle, health, heartbeat, and runtime bindings without USB/HID/SDK access.' }; }
