import type { ProductionGraph, SourceNode } from '../../shared/src/production-graph.js';
import type { RuntimeEventBus, RuntimeHealthStatus, RuntimeLifecycleState, RuntimeSubsystem, RuntimeSubsystemRegistration, RuntimeSubsystemSnapshot } from './broadcast-runtime-core.js';

const now = () => new Date().toISOString();
export type PipelineSourceType = 'Camera'|'Browser'|'Media File'|'Screen'|'Replay'|'Graphics'|'NDI'|'SRT'|'RTSP'|'WebRTC'|'Capture Card'|'Image Sequence'|'Audio Input'|'Playlist'|'Virtual Camera'|'Unknown';
export type PipelineState = 'Created'|'Initializing'|'Ready'|'Waiting'|'Running'|'Paused'|'Recovering'|'Stopping'|'Stopped'|'Failed'|'Disposed';
export type RecoveryStrategy = 'restart'|'reinitialize'|'fallback'|'manual'|'backoff';
export interface PipelineFormat { readonly resolution?: string; readonly frameRate?: number; readonly pixelFormat?: string; readonly colorSpace?: string; readonly hdrMetadata?: Readonly<Record<string, string|number|boolean>>; readonly sampleRate?: number; readonly channelLayout?: string; }
export interface PipelineHealth { readonly latencyMs: number; readonly bufferUtilization: number; readonly frameAvailable: boolean; readonly audioAvailable: boolean; readonly frameDrops: number; readonly packetLoss: number; readonly decoderState: 'idle'|'initializing'|'ready'|'decoding'|'stalled'|'failed'|'not_applicable'; readonly recoveryAttempts: number; readonly status: RuntimeHealthStatus; }
export interface PipelineMetrics { readonly startupTimeMs: number; readonly shutdownTimeMs: number; readonly latencyMs: number; readonly bufferDepth: number; readonly uptimeMs: number; readonly restarts: number; readonly failures: number; readonly recoveries: number; }
export interface PipelineRegistration { readonly pipelineId: string; readonly sourceId: string; readonly deviceId?: string; readonly sourceType: PipelineSourceType; readonly runtimeAdapter: string; readonly mediaAdapter: string; readonly productionGraphNodeId: string; readonly healthProvider: string; readonly selectedFormat: PipelineFormat; readonly priority: number; readonly recoveryStrategy?: RecoveryStrategy; readonly metadata?: Readonly<Record<string, string|number|boolean>>; }
export interface IngestPipeline { readonly registration: PipelineRegistration; readonly state: PipelineState; readonly health: PipelineHealth; readonly metrics: PipelineMetrics; readonly createdAt: string; readonly updatedAt: string; readonly runtimeOwner: string; readonly containsMediaHandles: false; }
export interface PipelineAdapter { readonly id: string; readonly sourceTypes: readonly PipelineSourceType[]; create(registration: PipelineRegistration, runtimeOwner: string): IngestPipeline; }
const emptyHealth = (status: RuntimeHealthStatus = 'Ready'): PipelineHealth => Object.freeze({ latencyMs:0, bufferUtilization:0, frameAvailable:false, audioAvailable:false, frameDrops:0, packetLoss:0, decoderState:'idle', recoveryAttempts:0, status });
const emptyMetrics = (): PipelineMetrics => Object.freeze({ startupTimeMs:0, shutdownTimeMs:0, latencyMs:0, bufferDepth:0, uptimeMs:0, restarts:0, failures:0, recoveries:0 });
const transitions: Readonly<Record<PipelineState, readonly PipelineState[]>> = Object.freeze({ Created:['Initializing','Disposed'], Initializing:['Ready','Waiting','Failed','Disposed'], Ready:['Running','Waiting','Stopping','Disposed'], Waiting:['Initializing','Running','Stopping','Failed','Disposed'], Running:['Paused','Recovering','Stopping','Failed'], Paused:['Running','Recovering','Stopping','Disposed'], Recovering:['Initializing','Running','Failed','Stopping'], Stopping:['Stopped','Failed'], Stopped:['Initializing','Disposed'], Failed:['Recovering','Initializing','Disposed'], Disposed:[] });
export function assertPipelineTransition(from: PipelineState, to: PipelineState) { if (!transitions[from].includes(to)) throw new Error(`Invalid pipeline transition from ${from} to ${to}`); return to; }
export class MetadataPipelineAdapter implements PipelineAdapter { constructor(readonly id: string, readonly sourceTypes: readonly PipelineSourceType[]) {} create(registration: PipelineRegistration, runtimeOwner: string): IngestPipeline { return Object.freeze({ registration, state:'Created', health: emptyHealth(), metrics: emptyMetrics(), createdAt: now(), updatedAt: now(), runtimeOwner, containsMediaHandles:false }); } }
export class PipelineFactory { private adapters = new Map<PipelineSourceType, PipelineAdapter>(); constructor(adapters: readonly PipelineAdapter[] = defaultPipelineAdapters()) { adapters.forEach((a)=>this.registerAdapter(a)); } registerAdapter(adapter: PipelineAdapter) { adapter.sourceTypes.forEach((type)=>this.adapters.set(type, adapter)); return this; } selectAdapter(type: PipelineSourceType) { return this.adapters.get(type) ?? this.adapters.get('Unknown')!; } create(registration: PipelineRegistration, owner: string) { return this.selectAdapter(registration.sourceType).create(registration, owner); } }
export function defaultPipelineAdapters() { return [new MetadataPipelineAdapter('camera-adapter',['Camera','Capture Card','Virtual Camera']), new MetadataPipelineAdapter('browser-adapter',['Browser']), new MetadataPipelineAdapter('file-adapter',['Media File','Image Sequence','Playlist']), new MetadataPipelineAdapter('screen-adapter',['Screen']), new MetadataPipelineAdapter('render-adapter',['Replay','Graphics']), new MetadataPipelineAdapter('network-adapter',['NDI','SRT','RTSP','WebRTC']), new MetadataPipelineAdapter('audio-adapter',['Audio Input']), new MetadataPipelineAdapter('unknown-adapter',['Unknown'])]; }
export class PipelineStateStore { private pipelines = new Map<string, IngestPipeline>(); list(){ return Object.freeze([...this.pipelines.values()]); } get(id:string){ return this.pipelines.get(id); } set(p:IngestPipeline){ this.pipelines.set(p.registration.pipelineId, Object.freeze(p)); return this.get(p.registration.pipelineId)!; } delete(id:string){ return this.pipelines.delete(id); } }
export class PipelineRegistry { constructor(private store = new PipelineStateStore()) {} register(pipeline: IngestPipeline) { const r = pipeline.registration; if (this.store.get(r.pipelineId)) throw new Error(`Duplicate pipeline registration ${r.pipelineId}`); if (this.list().some((p)=>p.registration.sourceId===r.sourceId && p.registration.productionGraphNodeId===r.productionGraphNodeId)) throw new Error(`Duplicate pipeline source registration ${r.sourceId}`); return this.store.set(pipeline); } list(){ return this.store.list(); } get(id:string){ return this.store.get(id); } update(p:IngestPipeline){ if (!this.store.get(p.registration.pipelineId)) throw new Error(`Unknown pipeline ${p.registration.pipelineId}`); return this.store.set(p); } remove(id:string){ return this.store.delete(id); } }
export class PipelineLifecycleManager { transition(p:IngestPipeline, to:PipelineState): IngestPipeline { assertPipelineTransition(p.state,to); const metrics = { ...p.metrics, startupTimeMs: to==='Running' && p.metrics.startupTimeMs===0 ? 1 : p.metrics.startupTimeMs, shutdownTimeMs: to==='Stopped' ? Math.max(1,p.metrics.shutdownTimeMs) : p.metrics.shutdownTimeMs, uptimeMs: to==='Running' ? p.metrics.uptimeMs + 1 : p.metrics.uptimeMs }; return Object.freeze({ ...p, state:to, metrics:Object.freeze(metrics), updatedAt:now() }); } }
export class PipelineHealthMonitor { update(p:IngestPipeline, health:Partial<PipelineHealth>) { const next = Object.freeze({ ...p.health, ...health }); return Object.freeze({ ...p, health:next, metrics:Object.freeze({ ...p.metrics, latencyMs: next.latencyMs, bufferDepth: next.bufferUtilization }), updatedAt:now() }); } }
export class PipelineMetricsCollector { collect(p:IngestPipeline){ return p.metrics; } markFailure(p:IngestPipeline){ return Object.freeze({ ...p, metrics:Object.freeze({ ...p.metrics, failures:p.metrics.failures+1 }), updatedAt:now() }); } markRestart(p:IngestPipeline){ return Object.freeze({ ...p, metrics:Object.freeze({ ...p.metrics, restarts:p.metrics.restarts+1 }), updatedAt:now() }); } }
export class PipelineRecoveryManager { calculateDelay(attempts:number, strategy:RecoveryStrategy='backoff') { if (strategy==='manual') return Number.POSITIVE_INFINITY; if (strategy==='restart') return 0; if (strategy==='reinitialize') return 250; if (strategy==='fallback') return 500; return Math.min(30000, 1000 * 2 ** Math.max(0, attempts-1)); } recover(p:IngestPipeline) { return Object.freeze({ ...p, state:'Recovering' as const, health:Object.freeze({ ...p.health, recoveryAttempts:p.health.recoveryAttempts+1, status:'Initializing' as RuntimeHealthStatus }), metrics:Object.freeze({ ...p.metrics, recoveries:p.metrics.recoveries+1 }), updatedAt:now() }); } }
export class PipelineCapabilityResolver { resolve(requested: Partial<PipelineFormat>, supported: readonly PipelineFormat[] = []) { return Object.freeze({ ...(supported[0] ?? {}), ...requested }); } }
export class PipelineEventAdapter { constructor(private bus: RuntimeEventBus, private source='ingest-runtime') {} publish(type: string, pipeline: IngestPipeline, extra: Record<string, unknown> = {}) { return this.bus.publish({ type, domain:'controller', source:this.source, payload:{ pipelineId:pipeline.registration.pipelineId, sourceId:pipeline.registration.sourceId, sourceType:pipeline.registration.sourceType, state:pipeline.state, ...extra } }); } }
export class IngestRuntimeController implements RuntimeSubsystem { readonly id='ingest-runtime-controller'; readonly domain='controller' as const; readonly registration: RuntimeSubsystemRegistration = Object.freeze({ subsystemId:this.id, domain:this.domain, dependencies:['production-graph-runtime'], startupPriority:20, shutdownPriority:65, healthSource:'ingest-runtime:health' }); private state: RuntimeLifecycleState='uninitialized'; private revision=0; readonly registry = new PipelineRegistry(); readonly lifecycle = new PipelineLifecycleManager(); readonly healthMonitor = new PipelineHealthMonitor(); readonly metricsCollector = new PipelineMetricsCollector(); readonly recovery = new PipelineRecoveryManager(); readonly capabilityResolver = new PipelineCapabilityResolver(); readonly events: PipelineEventAdapter; constructor(private bus:RuntimeEventBus, readonly factory = new PipelineFactory()) { this.events = new PipelineEventAdapter(bus, this.id); }
  registerPipeline(reg:PipelineRegistration){ const p=this.registry.register(this.factory.create(reg,this.id)); this.events.publish('PipelineCreated',p); return p; }
  listPipelines(){ return this.registry.list(); } getPipeline(id:string){ return this.registry.get(id); } getPipelineHealth(id:string){ return this.registry.get(id)?.health; } getPipelineMetrics(id:string){ return this.registry.get(id)?.metrics; } listPipelineEvents(){ return this.bus.replay().filter((e)=>e.type.startsWith('Pipeline')); }
  transitionPipeline(id:string,to:PipelineState){ const p=this.must(id); const n=this.registry.update(this.lifecycle.transition(p,to)); const event = ({Running:'PipelineStarted',Paused:'PipelinePaused',Stopped:'PipelineStopped',Failed:'PipelineFailed',Disposed:'PipelineDisposed'} as Record<string,string>)[to]; if (event) this.events.publish(event,n); return n; }
  updateHealth(id:string,health:Partial<PipelineHealth>){ const n=this.registry.update(this.healthMonitor.update(this.must(id),health)); this.events.publish('PipelineHealthChanged',n,{ health:n.health }); if (health.latencyMs!==undefined) this.events.publish('PipelineLatencyChanged',n,{ latencyMs:health.latencyMs }); return n; }
  updateFormat(id:string,format:Partial<PipelineFormat>){ const p=this.must(id); const registration = Object.freeze({ ...p.registration, selectedFormat:this.capabilityResolver.resolve(format,[p.registration.selectedFormat]) }); const n=this.registry.update(Object.freeze({ ...p, registration, updatedAt:now() })); this.events.publish('PipelineFormatChanged',n,{ format:n.registration.selectedFormat }); return n; }
  restartMetadata(id:string){ const p=this.metricsCollector.markRestart(this.recovery.recover(this.must(id))); const n=this.registry.update(p); this.events.publish('PipelineRecovered',n,{ delayMs:this.recovery.calculateDelay(n.health.recoveryAttempts,n.registration.recoveryStrategy) }); return n; } refresh(){ return this.listPipelines(); }
  initialize(){return this.snap('initialized');} configure(){return this.snap('configured');} prepare(){return this.snap('prepared');} standby(){return this.snap('standby');} ready(){return this.snap('ready');} start(){return this.snap('running');} pause(){return this.snap('paused');} resume(){return this.snap('running');} stop(){return this.snap('stopped');} recover(){return this.snap('recovering');} dispose(){return this.snap('disposed');}
  getSnapshot(): RuntimeSubsystemSnapshot { return Object.freeze({ id:this.id, domain:this.domain, state:this.state, health:this.listPipelines().some((p)=>p.health.status==='Error')?'Error':'Ready', revision:this.revision, updatedAt:now(), metadata:Object.freeze({ pipelines:this.registry.list().length, metadataOnly:true }) }); }
  private snap(state:RuntimeLifecycleState){ this.state=state; this.revision+=1; return this.getSnapshot(); } private must(id:string){ const p=this.registry.get(id); if(!p) throw new Error(`Unknown pipeline ${id}`); return p; }
}
export function mapPipelineToProductionGraphSource(p: IngestPipeline): SourceNode { return { id:p.registration.productionGraphNodeId, name:p.registration.sourceId, type: sourceTypeToGraphType(p.registration.sourceType), enabled:p.state!=='Disposed', muted:false, metadata:{ pipelineId:p.registration.pipelineId, pipelineState:p.state, health:p.health.status, sourceId:p.registration.sourceId, deviceId:p.registration.deviceId, format:p.registration.selectedFormat, latencyMs:p.health.latencyMs, recoveryAttempts:p.health.recoveryAttempts, runtimeOwner:p.runtimeOwner, containsMediaHandles:false } }; }
export function attachPipelineMetadataToGraph(graph:ProductionGraph, pipeline:IngestPipeline): ProductionGraph { return { ...graph, sources:{ ...graph.sources, [pipeline.registration.productionGraphNodeId]: mapPipelineToProductionGraphSource(pipeline) }, metadata:{ ...graph.metadata, updatedAt:now(), revision:graph.metadata.revision+1 } }; }
function sourceTypeToGraphType(t:PipelineSourceType): SourceNode['type'] { if (t==='Camera'||t==='Capture Card'||t==='Virtual Camera') return 'camera'; if (t==='Screen') return 'screen'; if (t==='Browser') return 'browser'; if (t==='Audio Input') return 'audio'; if (t==='Graphics'||t==='Replay') return 'overlay'; if (t==='Media File'||t==='Image Sequence'||t==='Playlist') return 'media'; return 'placeholder'; }
