import { RuntimeEngineError, type RuntimeCommand, type RuntimeCommandHandler, type TypedRuntimeCommandHandler } from './execution-engine.js';
import type { FrameLease, FrameMemoryManager, FrameMemoryDomain, VideoFrameFormat } from './frame-memory.js';
import type { VideoFramePipelineStage, VideoPipelineFrameReference, VideoPipelineStageDescriptor, VideoPipelineStageInput, VideoPipelineStageResult, VideoPipelineStageRuntimeContext } from './video-frame-pipeline.js';

type Json = string | number | boolean | null | readonly Json[] | { readonly [k: string]: Json };
const redact = /token|secret|password|credential|cookie|url|path|handle|pointer|native|gpu|device|endpoint/i;
const safe = (v: unknown, d = 0): Json => { if (d > 4) return '[Truncated]'; if (v == null || typeof v === 'boolean') return v as Json; if (typeof v === 'number') return Number.isFinite(v) ? v : String(v); if (typeof v === 'string') return v.length > 256 ? `${v.slice(0,256)}…` : v; if (typeof v === 'bigint') return v.toString(); if (Array.isArray(v)) return v.slice(0,64).map(x => safe(x,d+1)); if (typeof v === 'object') return Object.fromEntries(Object.entries(v as Record<string, unknown>).slice(0,64).map(([k,val]) => [k, redact.test(k) ? '[REDACTED]' : safe(val,d+1)])); return String(v); };
const freeze = <T>(v:T): Readonly<T> => { if (v && typeof v === 'object' && !Object.isFrozen(v)) { Object.freeze(v); for (const x of Object.values(v as Record<string, unknown>)) freeze(x); } return v as Readonly<T>; };
const clone = <T>(v:T): Readonly<T> => freeze(structuredClone(v));
const now = () => BigInt(Date.now()) * 1_000_000n;
const finite = (n: number) => Number.isFinite(n);

export type MaskType = 'RECTANGLE'|'ROUNDED_RECTANGLE'|'ELLIPSE'|'CIRCLE'|'POLYGON'|'SOURCE_ALPHA'|'KEY_MATTE'|'EXTERNAL_MATTE'|'PATH_REFERENCE'|'FULL_FRAME'|'EMPTY'|'CUSTOM';
export type MaskCoordinateSpace = 'SOURCE_PIXELS'|'SOURCE_NORMALIZED'|'FRAME_PIXELS'|'FRAME_NORMALIZED'|'CANVAS_PIXELS'|'CANVAS_NORMALIZED'|'CUSTOM';
export type MaskFillRule = 'NON_ZERO'|'EVEN_ODD';
export type MaskCombineMode = 'REPLACE'|'ADD'|'INTERSECT'|'SUBTRACT'|'XOR'|'MULTIPLY'|'MIN'|'MAX'|'INVERT'|'CUSTOM';
export type MaskOutputMode = 'MASKED_FRAME'|'MASK_ONLY'|'ALPHA_ONLY'|'PREMULTIPLIED'|'STRAIGHT_ALPHA'|'PASS_THROUGH'|'DIAGNOSTIC_MASK_VIEW';
export type MaskingBackendType = 'GPU_COMPUTE'|'GPU_FRAGMENT'|'CPU_SIMD'|'CPU_REFERENCE'|'PLATFORM_NATIVE'|'SYNTHETIC';
export type MaskingStatus = 'COMPLETED'|'PASSED_THROUGH'|'FAILED'|'CANCELLED'|'REJECTED';
export interface MaskPoint { readonly x:number; readonly y:number; }
export interface MaskRectangleShape { readonly x:number; readonly y:number; readonly width:number; readonly height:number; readonly radius?: number; }
export interface MaskEllipseShape { readonly centerX:number; readonly centerY:number; readonly radiusX:number; readonly radiusY:number; }
export interface MaskCircleShape { readonly centerX:number; readonly centerY:number; readonly radius:number; }
export interface MaskPolygonShape { readonly points: readonly MaskPoint[]; readonly closed: boolean; readonly fillRule: MaskFillRule; readonly allowSelfIntersection?: boolean; }
export interface MaskReferenceShape { readonly referenceId: string; readonly sourceId?: string; readonly streamId?: string; readonly generation?: bigint; readonly metadata?: Readonly<Record<string, unknown>>; }
export interface MaskTransform { readonly translateX?:number; readonly translateY?:number; readonly scaleX?:number; readonly scaleY?:number; readonly rotationDegrees?:number; readonly anchorX?:number; readonly anchorY?:number; readonly pivotX?:number; readonly pivotY?:number; readonly flipX?:boolean; readonly flipY?:boolean; }
export interface MaskParameters { readonly opacity:number; readonly featherRadiusPx:number; readonly expandPx:number; readonly contractPx:number; readonly enabled:boolean; readonly rejectInvalid:boolean; }
export interface MaskStackEntry { readonly entryId:string; readonly type:MaskType; readonly coordinateSpace:MaskCoordinateSpace; readonly combineMode:MaskCombineMode; readonly order:number; readonly shape?: MaskRectangleShape|MaskEllipseShape|MaskCircleShape|MaskPolygonShape|MaskReferenceShape; readonly transform?: MaskTransform; readonly parameters: MaskParameters; readonly metadata?: Readonly<Record<string, unknown>>; }
export interface MaskStack { readonly stackId:string; readonly entries: readonly Readonly<MaskStackEntry>[]; readonly createdAtNs:string; }
export interface MaskingPlanRequest { readonly requestId:string; readonly stack: MaskStack; readonly inputFrame: Readonly<VideoPipelineFrameReference>; readonly outputMode: MaskOutputMode; readonly width:number; readonly height:number; readonly format: VideoFrameFormat; readonly outputMemoryDomain?: FrameMemoryDomain; readonly cancellationSignal?: AbortSignal; readonly metadata?: Readonly<Record<string,unknown>>; }
export interface MaskingPlan { readonly planId:string; readonly backendId:string; readonly requestSignature:string; readonly outputMode:MaskOutputMode; readonly passThroughEligible:boolean; readonly estimatedCost:number; readonly warnings: readonly string[]; readonly effectiveStack: MaskStack; readonly createdAtNs:string; }
export interface MaskingBackendDescriptor { readonly backendId:string; readonly backendType:MaskingBackendType; readonly displayName:string; readonly version:string; readonly deterministic:boolean; readonly usesGpu:boolean; }
export interface MaskingBackendCapabilities { readonly maskTypes: readonly MaskType[]; readonly combineModes: readonly MaskCombineMode[]; readonly outputModes: readonly MaskOutputMode[]; readonly maxStackDepth:number; readonly maxPolygonPoints:number; readonly maxFeatherRadiusPx:number; readonly maxMorphologyPx:number; }
export interface MaskingBackendResult { readonly status: MaskingStatus; readonly operationSignature:string; readonly warnings: readonly string[]; readonly durationNs: bigint; }
export interface MaskingBackend { readonly descriptor: MaskingBackendDescriptor; readonly capabilities: MaskingBackendCapabilities; plan(r: MaskingPlanRequest): MaskingPlan; execute(plan: MaskingPlan, r: MaskingPlanRequest): Promise<MaskingBackendResult>|MaskingBackendResult; shutdown(): Promise<void>|void; }
export interface MaskingResult { readonly requestId:string; readonly status: MaskingStatus; readonly planId?:string; readonly backendId?:string; readonly inputFrameId:string; readonly outputFrame?: Readonly<VideoPipelineFrameReference>; readonly maskOnlyFrame?: Readonly<VideoPipelineFrameReference>; readonly passThrough:boolean; readonly applied:boolean; readonly effectiveStack?: MaskStack; readonly warnings: readonly string[]; readonly durationNs: bigint; readonly completedAtNs:string; readonly metadata: Readonly<Record<string, Json>>; }
export interface MaskingTelemetrySnapshot { readonly totalPlans:number; readonly cacheHits:number; readonly totalRequests:number; readonly completed:number; readonly passThrough:number; readonly failed:number; readonly cancelled:number; readonly allocationFailures:number; readonly lastEvent?:string; }
export interface MaskingHealthSnapshot { readonly engineState:string; readonly healthState:string; readonly backendCount:number; readonly planCacheSize:number; readonly updatedAtNs:string; }
export const MASKING_COMMAND_TYPES = freeze({ PLAN:'MASKING_PLAN', EXECUTE:'MASKING_EXECUTE', CLEAR_PLAN_CACHE:'MASKING_CLEAR_PLAN_CACHE', SNAPSHOT:'MASKING_SNAPSHOT', SHUTDOWN:'MASKING_SHUTDOWN' });
export const MASKING_OUTPUT_KEYS = freeze({ REQUEST:'masking.request', PLAN:'masking.plan', RESULT:'masking.result', MASKED_FRAME:'masking.maskedFrame', MASK_ONLY:'masking.maskOnly', PASS_THROUGH:'masking.passThrough', FAILURE:'masking.failure', HEALTH:'masking.health', TELEMETRY:'masking.telemetry' });
export const MASKING_WATCHDOG_INCIDENTS = freeze({ STALLED:'MASKING_STALLED', BACKEND:'MASKING_BACKEND_FAILURE', TIMEOUT:'MASKING_TIMEOUT', PARAMETER:'MASKING_PARAMETER_INVALID', TYPE:'MASKING_TYPE_UNSUPPORTED', POLYGON:'MASKING_POLYGON_INVALID', EXTERNAL_MATTE:'MASKING_EXTERNAL_MATTE_INVALID', KEY_MATTE:'MASKING_KEY_MATTE_INVALID', STACK:'MASKING_STACK_INVALID', TEMP_MEMORY:'MASKING_TEMP_MEMORY_EXCEEDED', GPU:'MASKING_GPU_LOSS', ALLOCATION:'MASKING_ALLOCATION_FAILURE', STALE:'MASKING_STALE_GENERATION', CACHE:'MASKING_CACHE_INVARIANT', GRAPH:'MASKING_GRAPH_METADATA_INVALID', INVARIANT:'MASKING_INVARIANT' });
export class MaskingError extends RuntimeEngineError {}
export class DuplicateMaskingBackend extends MaskingError { constructor(id:string){ super('DuplicateMaskingBackend', `Duplicate masking backend ${id}`, { id }); } }
export const defaultMaskParameters = (p: Partial<MaskParameters> = {}) => freeze({ opacity:1, featherRadiusPx:0, expandPx:0, contractPx:0, enabled:true, rejectInvalid:true, ...p });
export const createMaskStack = (stackId:string, entries: readonly Omit<MaskStackEntry,'parameters'>[]|readonly MaskStackEntry[]) => { const ids = new Set<string>(); const out = entries.map((e) => { if (ids.has(e.entryId)) throw new MaskingError('DuplicateMaskStackEntry', `Duplicate mask entry ${e.entryId}`); ids.add(e.entryId); return { ...e, parameters: defaultMaskParameters((e as MaskStackEntry).parameters ?? {}) } as MaskStackEntry; }).sort((a,b)=>a.order-b.order || a.entryId.localeCompare(b.entryId)); return freeze({ stackId, entries: out, createdAtNs: now().toString() }); };
const validateEntry = (e: MaskStackEntry, cap?: MaskingBackendCapabilities) => { const p=e.parameters; if (e.type==='CUSTOM') throw new MaskingError('UnsupportedCustomMask','CUSTOM masks require an explicit backend contract'); if (!finite(p.opacity)||p.opacity<0||p.opacity>1||!finite(p.featherRadiusPx)||p.featherRadiusPx<0||!finite(p.expandPx)||!finite(p.contractPx)||p.expandPx<0||p.contractPx<0|| (p.expandPx>0&&p.contractPx>0)) throw new MaskingError('InvalidMaskParameters',`Invalid parameters for ${e.entryId}`); if (cap && (p.featherRadiusPx>cap.maxFeatherRadiusPx || p.expandPx>cap.maxMorphologyPx || p.contractPx>cap.maxMorphologyPx)) throw new MaskingError('MaskParametersExceedBackendCapabilities', e.entryId); const t=e.transform; if (t) { for (const n of Object.values(t)) if (typeof n==='number' && !finite(n)) throw new MaskingError('InvalidMaskTransform', e.entryId); if (t.scaleX===0 || t.scaleY===0 || (t.scaleX ?? 1)<0 || (t.scaleY ?? 1)<0) throw new MaskingError('InvalidMaskTransformScale', e.entryId); } if ((e.type==='KEY_MATTE'||e.type==='EXTERNAL_MATTE'||e.type==='PATH_REFERENCE') && !(e.shape as MaskReferenceShape|undefined)?.referenceId) throw new MaskingError('MissingMaskReference', e.entryId); if (e.type==='POLYGON') { const poly=e.shape as MaskPolygonShape|undefined; if (!poly || !poly.closed || poly.points.length<3 || (cap && poly.points.length>cap.maxPolygonPoints)) throw new MaskingError('InvalidMaskPolygon', e.entryId); for (const pt of poly.points) if (!finite(pt.x)||!finite(pt.y)) throw new MaskingError('InvalidMaskPolygonPoint', e.entryId); if (!poly.allowSelfIntersection && selfIntersects(poly.points)) throw new MaskingError('SelfIntersectingMaskPolygon', e.entryId); } };
const selfIntersects = (pts: readonly MaskPoint[]) => { const ccw=(a:MaskPoint,b:MaskPoint,c:MaskPoint)=> (c.y-a.y)*(b.x-a.x) > (b.y-a.y)*(c.x-a.x); for(let i=0;i<pts.length;i++) for(let j=i+1;j<pts.length;j++){ if (Math.abs(i-j)<=1 || (i===0&&j===pts.length-1)) continue; const a=pts[i]!, b=pts[(i+1)%pts.length]!, c=pts[j]!, d=pts[(j+1)%pts.length]!; if (ccw(a,c,d)!==ccw(b,c,d) && ccw(a,b,c)!==ccw(a,b,d)) return true; } return false; };
export function validateMaskStack(stack: MaskStack, cap?: MaskingBackendCapabilities) { if (stack.entries.length > (cap?.maxStackDepth ?? 32)) throw new MaskingError('MaskStackDepthExceeded', stack.stackId); const ids=new Set<string>(); for (const e of stack.entries) { if (ids.has(e.entryId)) throw new MaskingError('DuplicateMaskStackEntry', e.entryId); ids.add(e.entryId); validateEntry(e, cap); } return freeze({ valid:true, stackId: stack.stackId, entryCount: stack.entries.length }); }
const sig = (r: MaskingPlanRequest) => JSON.stringify(safe({ stack:r.stack, mode:r.outputMode, w:r.width, h:r.height, fmt:r.format }));
const isPass = (r: MaskingPlanRequest) => r.outputMode==='PASS_THROUGH' || r.stack.entries.length===0 || r.stack.entries.every(e=>!e.parameters.enabled || e.type==='EMPTY' || e.type==='FULL_FRAME');
export class SyntheticMaskingBackend implements MaskingBackend { readonly descriptor=freeze({ backendId:'synthetic-masking', backendType:'SYNTHETIC' as const, displayName:'Synthetic Masking Backend', version:'5.4.2', deterministic:true, usesGpu:false }); readonly capabilities=freeze({ maskTypes:['RECTANGLE','ROUNDED_RECTANGLE','ELLIPSE','CIRCLE','POLYGON','SOURCE_ALPHA','KEY_MATTE','EXTERNAL_MATTE','PATH_REFERENCE','FULL_FRAME','EMPTY'] as MaskType[], combineModes:['REPLACE','ADD','INTERSECT','SUBTRACT','XOR','MULTIPLY','MIN','MAX','INVERT'] as MaskCombineMode[], outputModes:['MASKED_FRAME','MASK_ONLY','ALPHA_ONLY','PREMULTIPLIED','STRAIGHT_ALPHA','PASS_THROUGH','DIAGNOSTIC_MASK_VIEW'] as MaskOutputMode[], maxStackDepth:32, maxPolygonPoints:512, maxFeatherRadiusPx:256, maxMorphologyPx:128 }); plan(r:MaskingPlanRequest):MaskingPlan { validateMaskStack(r.stack,this.capabilities); const s=sig(r); const warnings=r.stack.entries.some(e=>e.parameters.featherRadiusPx>0)?['SYNTHETIC_FEATHER_METADATA_ONLY']:[]; return freeze({ planId:`mask-plan-${this.descriptor.backendId}-${hash(s)}`, backendId:this.descriptor.backendId, requestSignature:s, outputMode:r.outputMode, passThroughEligible:isPass(r), estimatedCost:r.stack.entries.length*10+r.width*r.height/1_000_000, warnings, effectiveStack: clone(r.stack), createdAtNs: now().toString() }); } execute(plan:MaskingPlan,r:MaskingPlanRequest):MaskingBackendResult { if (r.cancellationSignal?.aborted) return freeze({ status:'CANCELLED', operationSignature:plan.requestSignature, warnings:['CANCELLED'], durationNs:0n }); const md=r.metadata??{}; if (md.syntheticFailure) throw new MaskingError('SyntheticMaskingFailure','Synthetic masking failure hook'); if (md.syntheticGpuLoss) throw new MaskingError('SyntheticMaskingGpuLoss','Synthetic GPU loss hook'); return freeze({ status:'COMPLETED', operationSignature:plan.requestSignature, warnings: plan.warnings, durationNs: 1_000_000n }); } shutdown(){} }
const hash=(s:string)=>{ let h=2166136261; for (let i=0;i<s.length;i++) h=Math.imul(h^s.charCodeAt(i),16777619); return (h>>>0).toString(16); };
export class MaskingEngine { private backends=new Map<string,MaskingBackend>(); private cache=new Map<string,MaskingPlan>(); private tel: MaskingTelemetrySnapshot={ totalPlans:0, cacheHits:0, totalRequests:0, completed:0, passThrough:0, failed:0, cancelled:0, allocationFailures:0 }; private state='CREATED'; constructor(private frameMemory?: FrameMemoryManager, private maxCache=256, backends: readonly MaskingBackend[]=[new SyntheticMaskingBackend()]) { backends.forEach(b=>this.registerBackend(b)); } registerBackend(b:MaskingBackend){ if(this.backends.has(b.descriptor.backendId)) throw new DuplicateMaskingBackend(b.descriptor.backendId); this.backends.set(b.descriptor.backendId,b); this.bump('BackendRegistered'); } unregisterBackend(id:string){ this.backends.delete(id); for (const [k,p] of this.cache) if (p.backendId===id) this.cache.delete(k); this.bump('BackendUnregistered'); } private bump(e:string){ this.tel=freeze({...this.tel,lastEvent:e}); } plan(r:MaskingPlanRequest){ const key=sig(r); const hit=this.cache.get(key); if(hit){ this.tel=freeze({...this.tel,cacheHits:this.tel.cacheHits+1,lastEvent:'PlanCacheHit'}); return hit; } const candidates=[...this.backends.values()].sort((a,b)=>a.descriptor.backendId.localeCompare(b.descriptor.backendId)); const b=candidates[0]!; if(!b) throw new MaskingError('NoMaskingBackend','No masking backends registered'); const p=b.plan(r); this.cache.set(key,p); while(this.cache.size>this.maxCache) this.cache.delete([...this.cache.keys()].sort()[0]!); this.tel=freeze({...this.tel,totalPlans:this.tel.totalPlans+1,lastEvent:'PlanCreated'}); return p; } async execute(r:MaskingPlanRequest): Promise<MaskingResult> { const start=now(); this.tel=freeze({...this.tel,totalRequests:this.tel.totalRequests+1,lastEvent:'RequestStarted'}); let lease:FrameLease|undefined; try { if(r.cancellationSignal?.aborted) { this.tel=freeze({...this.tel,cancelled:this.tel.cancelled+1,lastEvent:'Cancelled'}); return freeze({ requestId:r.requestId,status:'CANCELLED',inputFrameId:r.inputFrame.frameId,passThrough:false,applied:false,warnings:['CANCELLED'],durationNs:now()-start,completedAtNs:now().toString(),metadata:{} }); } const plan=this.plan(r); if(plan.passThroughEligible){ this.tel=freeze({...this.tel,completed:this.tel.completed+1,passThrough:this.tel.passThrough+1,lastEvent:'PassThrough'}); return freeze({ requestId:r.requestId,status:'PASSED_THROUGH',planId:plan.planId,backendId:plan.backendId,inputFrameId:r.inputFrame.frameId,outputFrame:r.inputFrame,passThrough:true,applied:false,effectiveStack:plan.effectiveStack,warnings:plan.warnings,durationNs:now()-start,completedAtNs:now().toString(),metadata:{outputMode:r.outputMode} }); } if(this.frameMemory){ lease=await this.frameMemory.allocate({ width:r.width,height:r.height,format:r.format,memoryDomain:r.outputMemoryDomain??'SYNTHETIC',usageFlags:['PROCESSING_OUTPUT'],accessMode:'WRITE_ONLY',ownerId:'masking-engine',correlationId:r.requestId,metadata:{masking:true} }); }
 const backend=this.backends.get(plan.backendId); if(!backend) throw new MaskingError('MaskingBackendMissing',plan.backendId); const br=await backend.execute(plan,r); if(br.status==='CANCELLED') { lease?.release(); this.tel=freeze({...this.tel,cancelled:this.tel.cancelled+1,lastEvent:'Cancelled'}); return freeze({ requestId:r.requestId,status:'CANCELLED',planId:plan.planId,backendId:plan.backendId,inputFrameId:r.inputFrame.frameId,passThrough:false,applied:false,warnings:br.warnings,durationNs:now()-start,completedAtNs:now().toString(),metadata:{} }); } const out=lease ? frameRefFromLease(lease,r.inputFrame,r.width,r.height,r.format,r.outputMemoryDomain??'SYNTHETIC') : {...r.inputFrame, frameId:`${r.inputFrame.frameId}:masked:${hash(plan.planId)}`, leaseId:`synthetic-${hash(plan.planId)}`, metadata:freeze({...r.inputFrame.metadata, maskingApplied:true})}; this.tel=freeze({...this.tel,completed:this.tel.completed+1,lastEvent:'Completed'}); return freeze({ requestId:r.requestId,status:'COMPLETED',planId:plan.planId,backendId:plan.backendId,inputFrameId:r.inputFrame.frameId,outputFrame:out,...(r.outputMode==='MASK_ONLY'?{maskOnlyFrame:out}:{}),passThrough:false,applied:true,effectiveStack:plan.effectiveStack,warnings:[...plan.warnings,...br.warnings],durationNs:now()-start,completedAtNs:now().toString(),metadata:{operationSignature:br.operationSignature,outputMode:r.outputMode} }); } catch (e) { lease?.release(); this.tel=freeze({...this.tel,failed:this.tel.failed+1,lastEvent:'Failed'}); throw e; } } getTelemetry(){ return clone(this.tel); } getHealth(): MaskingHealthSnapshot { return freeze({ engineState:this.state, healthState:this.tel.failed?'DEGRADED':'HEALTHY', backendCount:this.backends.size, planCacheSize:this.cache.size, updatedAtNs:now().toString() }); } getSnapshot(){ return freeze({ health:this.getHealth(), telemetry:this.getTelemetry(), plans:[...this.cache.values()] }); } clearPlanCache(){ this.cache.clear(); this.bump('PlanCacheCleared'); } assertInvariants(){ if(this.cache.size>this.maxCache) throw new MaskingError('MaskingInvariantViolation','Unbounded plan cache'); for (const p of this.cache.values()) if(!this.backends.has(p.backendId)) throw new MaskingError('MaskingInvariantViolation','Cached plan references stale backend'); } async shutdown(){ if(this.state==='SHUTDOWN') return; this.state='SHUTDOWN'; await Promise.all([...this.backends.values()].map(b=>b.shutdown())); this.cache.clear(); this.bump('Shutdown'); } }
const frameRefFromLease=(l:FrameLease,i:Readonly<VideoPipelineFrameReference>,w:number,h:number,f:VideoFrameFormat,d:FrameMemoryDomain):Readonly<VideoPipelineFrameReference>=>freeze({...i,frameId:l.frameId,leaseId:l.leaseId,ownerId:l.ownerId,frameGeneration:l.generation,storageGeneration:l.generation,format:{...i.format,width:w,height:h,pixelFormat:f},memoryDomain:d==='GPU_LOCAL'?'GPU':d==='CPU_HEAP'?'CPU':'OPAQUE',state:'LEASED',metadata:{...i.metadata,maskingApplied:true}} as VideoPipelineFrameReference);
export const createMaskingEngine=(frameMemory?:FrameMemoryManager, backends?:readonly MaskingBackend[])=>new MaskingEngine(frameMemory,256,backends??[new SyntheticMaskingBackend()]);
export function createMaskingCommandHandlers(engine: MaskingEngine): readonly RuntimeCommandHandler[] { const h=(commandType:string,fn:(p:unknown)=>unknown):TypedRuntimeCommandHandler<unknown,unknown>=>({ commandType, execute:async(c:RuntimeCommand)=>({status:'SUCCEEDED',value:await fn(c.payload)}) }); return [h(MASKING_COMMAND_TYPES.PLAN,p=>engine.plan(p as MaskingPlanRequest)), h(MASKING_COMMAND_TYPES.EXECUTE,p=>engine.execute(p as MaskingPlanRequest)), h(MASKING_COMMAND_TYPES.CLEAR_PLAN_CACHE,()=>engine.clearPlanCache()), h(MASKING_COMMAND_TYPES.SNAPSHOT,()=>engine.getSnapshot()), h(MASKING_COMMAND_TYPES.SHUTDOWN,()=>engine.shutdown())]; }
export function createSourceGraphMaskingMetadata(r: MaskingResult){ return freeze({ enabled:true, stackId:r.effectiveStack?.stackId, stackEntryCount:r.effectiveStack?.entries.length??0, maskTypes:r.effectiveStack?.entries.map(e=>e.type)??[], outputMode:r.metadata.outputMode, status:r.status, health:r.status==='COMPLETED'||r.status==='PASSED_THROUGH'?'HEALTHY':'DEGRADED', runtimeFrame:r.outputFrame?.runtimeFrameNumber?.toString(), backendClass:r.backendId?.split('-')[0]??'none', passThrough:r.passThrough }); }
export class MaskingPipelineStage implements VideoFramePipelineStage { readonly descriptor: VideoPipelineStageDescriptor; constructor(private engine: MaskingEngine=createMaskingEngine(), private stack: MaskStack=createMaskStack('default-masking-stack', [])){ this.descriptor=freeze({ stageId:'masking', stageKind:'CUSTOM', displayName:'Masking Engine', version:'5.4.2', phase:'TRANSFORM', order:542, dependencies:['keying'], optionalDependencies:['color-correction'], requiredInputMediaKinds:['VIDEO'], supportedInputFormats:['RGBA8','BGRA8','RGB24','BGR24','RGBA16F','RGBA32F','NV12','P010','I420','YUV420','YUV422','YUV444'], supportedOutputFormats:['RGBA8','BGRA8','RGB24','BGR24','RGBA16F','RGBA32F','NV12','P010','I420','YUV420','YUV422','YUV444'], inputMemoryDomains:['OPAQUE','CPU','GPU','DMA','HARDWARE'], outputMemoryDomains:['OPAQUE','CPU','GPU','DMA','HARDWARE'], canPassThrough:true, requiresGpu:false, mutatesPixels:true, producesNewFrame:true, preservesTimestamp:true, preservesSourceIdentity:true, criticality:'IMPORTANT', enabled:true, optional:false, timeoutNs:5_000_000n, budgetNs:5_000_000n, maximumInFlight:1, metadata:{ kind:'MASKING', executesBefore:['geometry','layer-compositor'], backendNeutral:true } } as VideoPipelineStageDescriptor); } initialize(){ return { status:'READY' as const }; } async process(input:VideoPipelineStageInput, context:VideoPipelineStageRuntimeContext): Promise<VideoPipelineStageResult>{ const f=input.inputFrame; const r=await this.engine.execute({ requestId:`${context.requestId}:masking`, stack:this.stack, inputFrame:f, outputMode:this.stack.entries.length?'MASKED_FRAME':'PASS_THROUGH', width:Number(f.format.width??1), height:Number(f.format.height??1), format:(f.format.pixelFormat??f.format.format??'RGBA8') as VideoFrameFormat, ...(context.cancellationSignal ? { cancellationSignal: context.cancellationSignal } : {}) }); const o=r.outputFrame??f; return { status:r.passThrough?'PASSED_THROUGH':'COMPLETED', output:freeze({ stageId:this.descriptor.stageId, status:r.passThrough?'PASSED_THROUGH':'COMPLETED', inputFrameId:f.frameId, outputFrameId:o.frameId, outputLeaseId:o.leaseId, outputGeneration:o.frameGeneration, passThrough:r.passThrough, producedNewFrame:!r.passThrough, timestampPreserved:true, sourceIdentityPreserved:true, durationNs:r.durationNs, warnings:r.warnings.map(w=>({code:'MASKING_WARNING',message:w})), metadata:{ planId:r.planId ?? '', backendId:r.backendId ?? '', maskingApplied:r.applied, outputMode:r.metadata.outputMode ?? '' } }) }; } shutdown(){ return this.engine.shutdown(); } }
export const createMaskingPipelineStage=(engine?:MaskingEngine, stack?:MaskStack)=>new MaskingPipelineStage(engine,stack);
