const assert=Object.assign((c:unknown,m?:string)=>{if(!c)throw new Error(m??'assert');},{equal(a:unknown,b:unknown,m?:string){if(a!==b)throw new Error(m??`${a} !== ${b}`);},throws(fn:()=>unknown,re:RegExp){let t=false;try{fn();}catch(e){t=true;if(!re.test(String(e)))throw e;}if(!t)throw new Error('expected throw');}});
import { NDI_OUTPUT_PROCESSOR_ORDER, createNdiOutputEngine, createNdiOutputProcessor, createNdiSourceGraphSnapshot, type NdiDestination, type NdiOutputProfile, type NdiSendRequest, type NdiSenderSession } from './ndi-output-foundation.js';
const compat={protocolGeneration:'NDI_METADATA_5',videoSupport:true,audioSupport:true,metadataSupport:true,tallySupport:true,ptzSupport:true,bandwidthCompatibility:['HIGHEST','HIGH','MEDIUM','LOW','LOWEST','AUDIO_ONLY','METADATA_ONLY','CUSTOM'] as const,formatCompatibility:['UYVY_METADATA','PCM_METADATA'],compatible:true,safeMetadata:{}};
const profile: NdiOutputProfile={profileId:'ndi-profile',generation:1,outputMode:'PROGRAM',senderType:'AUDIO_VIDEO',bandwidthProfile:'HIGH',discoveryMode:'AUTOMATIC_METADATA',streamName:'UBOS Program',groupName:'UBOS',deviceName:'UBOS Device',friendlyName:'UBOS Program Friendly',instanceId:'ndi-instance-1',outputRole:'PROGRAM',safeMetadata:{synthetic:true}};
const destination: NdiDestination={destinationId:'ndi-dest',generation:1,enabled:true,receiverGroup:'UBOS',requiredBandwidth:'HIGH',compatibility:compat,safeMetadata:{metadataOnly:true}};
const session: NdiSenderSession={sessionId:'ndi-session',generation:1,profileId:'ndi-profile',profileGeneration:1,destinationId:'ndi-dest',destinationGeneration:1,senderId:'sender-1',streamingSessionId:'streaming-ndi-1',lifecycle:'CREATED',safeMetadata:{}};
const frame=(i:number):NdiSendRequest=>({requestId:`ndi-req-${i}`,sessionId:'ndi-session',frameId:`ndi-frame-${i}`,sequence:i,generation:1,timestampNs:i*33366666,mediaType:i%10===0?'METADATA':'VIDEO',ownership:'BORROWED_READ_ONLY',safeMetadata:{summary:`frame-${i}`}});
function scenario(){const e=createNdiOutputEngine(); e.registerProfile(profile); e.registerDestination(destination); e.createSession(session); e.updateDiscovery('ndi-session',{advertisedName:'UBOS Program v2'}); e.updateTally('ndi-session','PREVIEW'); e.updateTally('ndi-session','PROGRAM'); e.updatePtz('ndi-session',{pan:1,tilt:2,zoom:1.5,focus:.5,presetRecall:1}); for(let i=0;i<10000;i++){e.updateMetadata('ndi-session',{index:i}); e.submitFrame(frame(i));} for(let i=0;i<100000;i++)e.processTick(); return e;}
const e=scenario(), s=e.snapshot(); assert.equal(s.version,'5.7.6'); assert.equal(s.health.senderCount,1); assert.equal(s.health.activeStreams,1); assert.equal(s.telemetry.streamPublications,10000); assert.equal(s.telemetry.metadataUpdates,10000); assert.equal(s.telemetry.tallyUpdates,2); assert.equal(s.telemetry.ptzUpdates,1); assert.equal(e.tickCount,100000); assert.equal(s.results.every(r=>!r.realNdiTransport&&!r.realNetworkDiscovery&&!r.realSocket&&!r.realPacketSerialization),true); assert.equal(s.validation.valid,true); assert.equal(createNdiSourceGraphSnapshot(e).realNdiTransport,false); assert.equal(NDI_OUTPUT_PROCESSOR_ORDER,1064); const proc=createNdiOutputProcessor(e); assert.equal(proc.initialize().status,'READY'); assert.throws(()=>e.submitFrame(frame(1)),/Duplicate|Sequence/); assert.throws(()=>e.submitFrame({...frame(10001),generation:0}),/Stale/); assert.throws(()=>e.submitFrame({...frame(10001),ownership:'RELEASED'}),/Ownership/); const a=JSON.stringify(scenario().snapshot()), b=JSON.stringify(scenario().snapshot()); assert.equal(a,b,'deterministic replay'); e.drain('ndi-session'); e.shutdownEngine(); const shut=e.snapshot(); assert.equal(shut.sessions.length,0); assert.equal(shut.advertisements.length,0); assert.equal(shut.plans.length,0); assert.equal(shut.validation.valid,true); console.log('UBOS v5.7.6 NDI output foundation validation passed');
