/* eslint-disable @typescript-eslint/no-explicit-any */
import { RuntimeEngineError, type TypedRuntimeCommandHandler } from './execution-engine.js';
import type { MediaSource, SourceDescriptor, SourceMediaKind, SourceOperationResult, SourceProvider, SourceProviderContext, SourceRuntimeContext, SourceSampleBatch, VideoFrameEnvelope, AudioBufferEnvelope, MetadataSampleEnvelope } from './source-acquisition.js';

export type NetworkSourceProtocol = 'SRT'|'RTMP'|'RTMPS'|'NDI'|'NDI_HX'|'RTP'|'RTP_UDP'|'RIST'|'WEBRTC_CONTRIBUTION'|'MPEG_TS_UDP'|'MPEG_TS_TCP'|'HLS_PULL'|'DASH_PULL'|'CUSTOM_TCP'|'CUSTOM_UDP'|'SYNTHETIC_NETWORK'|'CUSTOM_NETWORK';
export type NetworkConnectionMode = 'CALLER'|'LISTENER'|'RENDEZVOUS'|'PULL'|'PUSH_RECEIVER'|'DISCOVERY_BASED'|'SESSION_NEGOTIATED';
export type NetworkConnectionState = 'REGISTERED'|'RESOLVING'|'BINDING'|'LISTENING'|'CONNECTING'|'HANDSHAKING'|'AUTHENTICATING'|'NEGOTIATING'|'CONNECTED'|'BUFFERING'|'RECEIVING'|'RECONNECTING'|'FAILING_OVER'|'REMOTE_CLOSED'|'TIMED_OUT'|'DISCONNECTING'|'DISCONNECTED'|'FAILED';
export type NetworkPacketOwnership = 'OWNED_BY_BACKEND'|'OWNED_BY_SOURCE'|'OWNED_BY_RUNTIME'|'BORROWED'|'EXTERNAL_HANDLE'|'RELEASED';
export type NetworkPacketOverflowPolicy = 'DROP_OLDEST'|'DROP_NEWEST'|'REJECT'|'FAIL_SOURCE'|'SIGNAL_DISCONTINUITY';
export type NetworkCommandType = 'NETWORK_REGISTER'|'NETWORK_CONNECT'|'NETWORK_START'|'NETWORK_STOP'|'NETWORK_DISCONNECT'|'NETWORK_RECONNECT'|'NETWORK_SET_ENDPOINT'|'NETWORK_SET_CREDENTIAL_PROFILE'|'NETWORK_SET_ENCRYPTION_PROFILE'|'NETWORK_SET_LATENCY'|'NETWORK_SET_JITTER_BUFFER'|'NETWORK_SELECT_STREAMS'|'NETWORK_ENABLE_FAILOVER'|'NETWORK_DISABLE_FAILOVER'|'NETWORK_ENABLE'|'NETWORK_DISABLE'|'NETWORK_REFRESH_STREAMS';
export const NETWORK_COMMAND_TYPES = Object.freeze(['NETWORK_REGISTER','NETWORK_CONNECT','NETWORK_START','NETWORK_STOP','NETWORK_DISCONNECT','NETWORK_RECONNECT','NETWORK_SET_ENDPOINT','NETWORK_SET_CREDENTIAL_PROFILE','NETWORK_SET_ENCRYPTION_PROFILE','NETWORK_SET_LATENCY','NETWORK_SET_JITTER_BUFFER','NETWORK_SELECT_STREAMS','NETWORK_ENABLE_FAILOVER','NETWORK_DISABLE_FAILOVER','NETWORK_ENABLE','NETWORK_DISABLE','NETWORK_REFRESH_STREAMS'] as const);
export const NETWORK_EVENT_TYPES = Object.freeze(['NetworkSourceRegistered','NetworkResolving','NetworkResolved','NetworkResolutionFailed','NetworkBinding','NetworkListening','NetworkConnecting','NetworkHandshakeStarted','NetworkAuthenticated','NetworkConnected','NetworkConnectionFailed','NetworkReceivingStarted','NetworkReceivingStopped','NetworkPacketReceived','NetworkPacketDropped','NetworkPacketDuplicate','NetworkPacketOutOfOrder','NetworkPacketLate','NetworkPacketRecovered','NetworkJitterBufferPressure','NetworkStreamDiscovered','NetworkStreamChanged','NetworkStreamSelected','NetworkRemoteClosed','NetworkDisconnected','NetworkReconnecting','NetworkReconnected','NetworkReconnectFailed','NetworkFailoverStarted','NetworkFailoverCompleted','NetworkFailoverFailed','NetworkAuthenticationFailed','NetworkEncryptionFailed','NetworkBackendFailed','NetworkHealthChanged'] as const);
export const NETWORK_WATCHDOG_INCIDENTS = Object.freeze(['NETWORK_NO_PACKETS','NETWORK_RECEIVE_STALLED','NETWORK_ENDPOINT_UNREACHABLE','NETWORK_ADDRESS_POLICY_DENIED','NETWORK_AUTHENTICATION_FAILED','NETWORK_ENCRYPTION_FAILED','NETWORK_HANDSHAKE_FAILED','NETWORK_PACKET_LOSS_HIGH','NETWORK_JITTER_HIGH','NETWORK_LATENCY_HIGH','NETWORK_QUEUE_OVERFLOW','NETWORK_REORDER_WINDOW_EXCEEDED','NETWORK_DUPLICATE_RATE_HIGH','NETWORK_TIMESTAMP_UNSTABLE','NETWORK_CLOCK_DRIFT_HIGH','NETWORK_REMOTE_CLOSED','NETWORK_RECONNECT_EXHAUSTED','NETWORK_FAILOVER_EXHAUSTED','NETWORK_BACKEND_FAILED','NETWORK_GRAPH_MISMATCH','NETWORK_SECRET_LEAK_RISK','NETWORK_INVARIANT_FAILURE'] as const);

const now = () => BigInt(Date.now()) * 1_000_000n;
export const networkDeepFreeze = <T>(v:T): Readonly<T> => { if (v && typeof v === 'object') { Object.freeze(v); for (const x of Object.values(v as Record<string, unknown>)) networkDeepFreeze(x); } return v as Readonly<T>; };
export const redactNetworkValue = (v: unknown): unknown => typeof v === 'string' ? v.replace(/([^\s:@/?#]+):([^\s@]+)@/g,'<redacted>@').replace(/(token|secret|key|passphrase|password|stream_key)=([^&\s]+)/gi,'$1=<redacted>').replace(/([a-z][a-z0-9+.-]*:\/\/[^\s/?#]+)([^\s]*)/gi,'$1/<redacted>') : v;
const safeMeta = (m: Readonly<Record<string, unknown>> = {}) => Object.fromEntries(Object.entries(m).slice(0,32).map(([k,v])=>[/secret|token|key|pass|credential|url/i.test(k)?[k,'<redacted>']:[k,redactNetworkValue(v)]]));
const id = (s:string)=>s.replace(/[^a-zA-Z0-9._:-]/g,'_').slice(0,128);

export class NetworkSourceError extends RuntimeEngineError { constructor(code:string,msg:string,details:Record<string,unknown>={}){ super(code,msg,safeMeta(details)); }}
export class NetworkSourceNotFound extends NetworkSourceError{constructor(sourceId:string){super('NetworkSourceNotFound',`Network source ${sourceId} was not found`,{sourceId});}}
export class DuplicateNetworkSource extends NetworkSourceError{constructor(sourceId:string){super('DuplicateNetworkSource',`Duplicate network source ${sourceId}`,{sourceId});}}
export class NetworkEndpointInvalid extends NetworkSourceError{constructor(reason:string){super('NetworkEndpointInvalid',reason);}}
export class NetworkAddressPolicyDenied extends NetworkSourceError{constructor(target:string){super('NetworkAddressPolicyDenied','Network address policy denied endpoint',{target});}}
export class NetworkAlreadyConnected extends NetworkSourceError{constructor(sourceId:string){super('NetworkAlreadyConnected',`Network source ${sourceId} is already connected`,{sourceId});}}
export class NetworkNotConnected extends NetworkSourceError{constructor(sourceId:string){super('NetworkNotConnected',`Network source ${sourceId} is not connected`,{sourceId});}}
export class NetworkAlreadyReceiving extends NetworkSourceError{constructor(sourceId:string){super('NetworkAlreadyReceiving',`Network source ${sourceId} is already receiving`,{sourceId});}}
export class NetworkOwnershipViolation extends NetworkSourceError{constructor(handleId:string){super('NetworkOwnershipViolation','Network packet ownership violation',{handleId});}}

export interface NetworkEndpointReference { readonly endpointReferenceId:string; readonly kind:'HOST_PORT'|'LISTENER_BINDING_PROFILE'|'NAMED_CONNECTION_PROFILE'|'DISCOVERY_SERVICE'|'FAILOVER_SET'|'SYNTHETIC'; readonly scheme?:string; readonly host?:string; readonly port?:number; readonly bindingProfileId?:string; readonly credentialRef?:string; readonly encryptionProfileRef?:string; readonly safeSummary:string; readonly metadata?:Readonly<Record<string,unknown>>; }
export interface NetworkAddressPolicy { readonly allowedDomains?:readonly string[]; readonly deniedDomains?:readonly string[]; readonly allowedCidrs?:readonly string[]; readonly deniedCidrs?:readonly string[]; readonly allowPrivateNetwork:boolean; readonly allowLocalhost:boolean; readonly allowLinkLocal:boolean; readonly allowMulticast:boolean; readonly allowBroadcast:boolean; readonly allowBindAllInterfaces:boolean; readonly interfaceAllowlist?:readonly string[]; readonly interfaceDenylist?:readonly string[]; readonly dnsResolutionLimit:number; readonly maximumResolvedAddresses:number; readonly preferredAddressFamily?:'IPV4'|'IPV6'|'ANY'; }
export const DEFAULT_NETWORK_ADDRESS_POLICY: NetworkAddressPolicy = networkDeepFreeze({ allowPrivateNetwork:false, allowLocalhost:false, allowLinkLocal:false, allowMulticast:false, allowBroadcast:false, allowBindAllInterfaces:false, dnsResolutionLimit:4, maximumResolvedAddresses:8, preferredAddressFamily:'ANY' });
export interface NetworkPacketBufferConfiguration { readonly maximumPackets:number; readonly maximumBytes:number; readonly maximumBufferedDurationNs:bigint; readonly highWaterMark:number; readonly lowWaterMark:number; readonly overflowPolicy:NetworkPacketOverflowPolicy; readonly maximumPacketAgeNs:bigint; readonly releaseDroppedPackets:boolean; }
export const DEFAULT_NETWORK_PACKET_BUFFER_CONFIG: NetworkPacketBufferConfiguration = networkDeepFreeze({ maximumPackets:128, maximumBytes:8_388_608, maximumBufferedDurationNs:2_000_000_000n, highWaterMark:96, lowWaterMark:32, overflowPolicy:'DROP_OLDEST', maximumPacketAgeNs:5_000_000_000n, releaseDroppedPackets:true });
export interface NetworkJitterBufferConfiguration { readonly targetLatencyNs:bigint; readonly minimumLatencyNs:bigint; readonly maximumLatencyNs:bigint; readonly reorderingWindow:number; readonly latePacketPolicy:'DROP'|'KEEP_WITH_DISCONTINUITY'; readonly duplicatePolicy:'DROP'|'MARK'; readonly lossPolicy:'MARK_DISCONTINUITY'|'DEGRADE'|'FAIL_SOURCE'; readonly adaptive:boolean; }
export const DEFAULT_NETWORK_JITTER_BUFFER_CONFIG: NetworkJitterBufferConfiguration = networkDeepFreeze({ targetLatencyNs:120_000_000n, minimumLatencyNs:20_000_000n, maximumLatencyNs:1_000_000_000n, reorderingWindow:32, latePacketPolicy:'DROP', duplicatePolicy:'DROP', lossPolicy:'MARK_DISCONTINUITY', adaptive:false });
export interface NetworkReconnectPolicy { readonly maximumAttempts:number; readonly initialDelayNs:bigint; readonly backoffMultiplier:number; readonly maximumDelayNs:bigint; readonly cooldownNs:bigint; readonly resetAfterHealthyNs:bigint; readonly reResolveEndpoint:boolean; readonly reResolveCredentials:boolean; readonly reconnectOnRemoteClose:boolean; readonly reconnectOnTimeout:boolean; readonly reconnectOnAuthFailure:boolean; readonly jitterSeed:number; }
export interface NetworkFailoverPolicy { readonly enabled:boolean; readonly orderedEndpointReferenceIds:readonly string[]; readonly failoverDelayNs:bigint; readonly maximumSwitchesPerWindow:number; readonly switchWindowNs:bigint; readonly sticky:boolean; readonly manualOverrideEndpointReferenceId?:string; }
export interface NetworkProtocolCapabilities { readonly supportsCaller:boolean; readonly supportsListener:boolean; readonly supportsRendezvous:boolean; readonly supportsDiscovery:boolean; readonly supportsEncryption:boolean; readonly supportsAuthentication:boolean; readonly supportsMultiplexedAudioVideo:boolean; readonly supportsMetadata:boolean; readonly supportsReliableDelivery:boolean; readonly supportsPacketRecovery:boolean; readonly supportsCongestionControl:boolean; readonly supportsLatencyConfiguration:boolean; readonly supportsTimecode:boolean; readonly supportsHardwareTimestamps:boolean; readonly supportsMulticast:boolean; readonly supportsFailover:boolean; readonly supportsStreamSelection:boolean; readonly supportsDynamicFormatChange:boolean; }
export const syntheticNetworkCapabilities: NetworkProtocolCapabilities = networkDeepFreeze({ supportsCaller:true,supportsListener:true,supportsRendezvous:false,supportsDiscovery:true,supportsEncryption:true,supportsAuthentication:true,supportsMultiplexedAudioVideo:true,supportsMetadata:true,supportsReliableDelivery:false,supportsPacketRecovery:true,supportsCongestionControl:false,supportsLatencyConfiguration:true,supportsTimecode:true,supportsHardwareTimestamps:false,supportsMulticast:false,supportsFailover:true,supportsStreamSelection:true,supportsDynamicFormatChange:true });
export interface NetworkSourceIdentity { readonly sourceId:string; readonly providerId:string; readonly protocol:NetworkSourceProtocol; readonly connectionMode:NetworkConnectionMode; readonly endpointReferenceId:string; readonly safeEndpointSummary:string; readonly persistentIdentity:string; readonly sessionIdentity:string; readonly remotePeerIdentityRef?:string; readonly localBindingProfileId?:string; readonly streamIdentity?:string; readonly failoverGroupId?:string; readonly createdAtNs:string; readonly updatedAtNs:string; readonly tags:readonly string[]; readonly metadata:Readonly<Record<string,unknown>>; }
export interface NetworkSourceDescriptor extends SourceDescriptor { readonly networkIdentity: NetworkSourceIdentity; readonly protocol:NetworkSourceProtocol; readonly connectionMode:NetworkConnectionMode; readonly endpoint:NetworkEndpointReference; readonly supportedTransportFeatures:NetworkProtocolCapabilities; readonly encryptionSupport:boolean; readonly authenticationSupport:boolean; readonly reconnectCapability:boolean; readonly failoverCapability:boolean; readonly discoverySupport:boolean; readonly latencyMode:'LOW_LATENCY'|'STANDARD'|'BUFFERED'; readonly expectedLatencyRangeNs: readonly [bigint,bigint]; readonly jitterBufferPolicy:NetworkJitterBufferConfiguration; readonly packetOrderingPolicy:'STRICT'|'REORDER_WITHIN_WINDOW'|'ARRIVAL'; readonly timestampSourcePolicy:'SENDER'|'MEDIA_CLOCK'|'ARRIVAL_FALLBACK'|'UNKNOWN'; }
export interface NetworkConnectRequest { readonly endpoint:NetworkEndpointReference; readonly connectionMode:NetworkConnectionMode; readonly timeoutNs:bigint; readonly handshakeTimeoutNs:bigint; readonly authenticationTimeoutNs:bigint; readonly credentialRef?:string; readonly encryptionProfileRef?:string; readonly latencyMode?:NetworkSourceDescriptor['latencyMode']; readonly requestedLatencyNs?:bigint; readonly jitterBuffer?:NetworkJitterBufferConfiguration; readonly packetBuffer?:NetworkPacketBufferConfiguration; readonly localBindingProfileId?:string; readonly addressPolicy?:NetworkAddressPolicy; readonly reconnectPolicy?:NetworkReconnectPolicy; readonly failoverPolicy?:NetworkFailoverPolicy; readonly expectedProtocol?:NetworkSourceProtocol; readonly expectedMediaKinds?:readonly SourceMediaKind[]; readonly expectedStreamIdentity?:string; readonly correlationId?:string; readonly metadata?:Readonly<Record<string,unknown>>; }
export type NetworkReconnectRequest = NetworkConnectRequest;
export interface NetworkOperationResult { readonly ok:boolean; readonly sourceId:string; readonly connectionState:NetworkConnectionState; readonly generation:number; readonly error?:{readonly code:string; readonly message:string}; readonly metadata?:Readonly<Record<string,unknown>>; }
export type NetworkConnectResult = NetworkOperationResult & { readonly connected:boolean; readonly sessionId?:string };
export type NetworkReconnectResult = NetworkConnectResult & { readonly attempts:number };
export interface NetworkProviderContext extends SourceProviderContext {}
export interface NetworkConnectionContext { readonly nowNs:()=>bigint; readonly signal?:AbortSignal; }
export interface NetworkReceiveContext extends NetworkConnectionContext {}
export interface NetworkStreamDescriptor { readonly streamId:string; readonly mediaKind:'VIDEO'|'AUDIO'|'METADATA'|'DATA'|'TIMECODE'|'CAPTION'; readonly codec:Readonly<Record<string,unknown>>; readonly timebase:{readonly numerator:number;readonly denominator:number}; readonly language?:string; readonly channelLayout?:string; readonly dimensions?:{readonly width:number;readonly height:number}; readonly frameRate?:{readonly numerator:number;readonly denominator:number}; readonly sampleRate?:number; readonly encrypted:boolean; readonly selected:boolean; readonly default:boolean; readonly metadata:Readonly<Record<string,unknown>>; }
export interface NetworkPacketEnvelope { readonly sourceId:string; readonly sessionId:string; readonly streamId?:string; readonly protocol:NetworkSourceProtocol; readonly sequenceNumber:number; readonly extendedSequenceNumber?:number; readonly sourceTimestampNs?:bigint; readonly arrivalTimestampNs:bigint; readonly normalizedTimestampNs?:bigint; readonly payloadType:string; readonly mediaKind?:SourceMediaKind; readonly packetSize:number; readonly markerFlags:readonly string[]; readonly discontinuity:boolean; readonly corrupted:boolean; readonly encrypted:boolean; readonly recovered:boolean; readonly retransmitted:boolean; readonly duplicate:boolean; readonly outOfOrder:boolean; readonly generation:number; readonly backendId:string; readonly payload:{readonly handleId:string; readonly byteLength:number}; readonly ownership:NetworkPacketOwnership; readonly metadata:Readonly<Record<string,unknown>>; }
export interface NetworkBackendHealthSnapshot { readonly backendId:string; readonly healthy:boolean; readonly activeSessions:number; readonly retainedHandles:number; readonly lastError?:string; readonly updatedAtNs:string; }
export interface NetworkTelemetrySnapshot { readonly registeredNetworkSourceCount:number; readonly connectedNetworkSourceCount:number; readonly activeNetworkSourceCount:number; readonly totalNetworkPacketsReceived:number; readonly totalNetworkPacketsDropped:number; readonly totalNetworkPacketsDuplicate:number; readonly totalNetworkPacketsOutOfOrder:number; readonly totalNetworkPacketsLate:number; readonly totalNetworkBytesReceived:number; readonly totalNetworkVideoFramesPublished:number; readonly totalNetworkAudioBuffersPublished:number; readonly totalNetworkMetadataSamplesPublished:number; readonly totalNetworkConnectAttempts:number; readonly successfulNetworkConnections:number; readonly failedNetworkConnections:number; readonly totalNetworkReconnectAttempts:number; readonly currentNetworkSourceIds:readonly string[]; readonly lastNetworkEvent?:string; readonly networkHealthSummary:Readonly<Record<string,number>>; }
export interface NetworkSourceHealthSnapshot { readonly sourceId:string; readonly lifecycleState:string; readonly connectionState:NetworkConnectionState; readonly healthState:'UNKNOWN'|'HEALTHY'|'DEGRADED'|'UNHEALTHY'|'RECONNECTING'|'UNAVAILABLE'|'FAILED'; readonly protocol:NetworkSourceProtocol; readonly connectionMode:NetworkConnectionMode; readonly connected:boolean; readonly active:boolean; readonly available:boolean; readonly authenticated:boolean; readonly encrypted:boolean; readonly safeEndpointSummary:string; readonly backendId:string; readonly sessionGeneration:number; readonly selectedStreams:readonly string[]; readonly lastPacketReceivedNs?:string; readonly lastSamplePublishedNs?:string; readonly packetQueueDepth:number; readonly packetQueueBytes:number; readonly jitterBufferDepth:number; readonly jitterBufferDurationNs:string; readonly duplicateRate:number; readonly outOfOrderRate:number; readonly latePacketRate:number; readonly missingPacketCount:number; readonly reconnectAttempts:number; readonly failoverSwitches:number; readonly discontinuities:number; readonly consecutiveFailures:number; readonly lastError?:string; readonly updatedAtNs:string; }
export type NetworkSourceSnapshot = Readonly<{ descriptor:NetworkSourceDescriptor; connection:NetworkConnectionState; health:NetworkSourceHealthSnapshot; streams:readonly NetworkStreamDescriptor[]; }>;
export type NetworkConnectionSnapshot = Readonly<{ sourceId:string; state:NetworkConnectionState; sessionId?:string; generation:number; connected:boolean; receiving:boolean; }>;
export type NetworkEndpointSnapshot = Readonly<NetworkEndpointReference>;
export type NetworkPacketQueueSnapshot = Readonly<{ depth:number; bytes:number; dropped:number; highWater:boolean; }>;
export type NetworkJitterBufferSnapshot = Readonly<{ depth:number; durationNs:string; duplicates:number; late:number; gaps:number; }>;
export type NetworkStreamSnapshot = Readonly<NetworkStreamDescriptor>;
export type NetworkProviderSnapshot = Readonly<{ providerId:string; sourceCount:number; backend:NetworkBackendHealthSnapshot; }>;
export type NetworkFailoverSnapshot = Readonly<{ enabled:boolean; switches:number; activeEndpointReferenceId?:string; }>;

export const validateNetworkEndpointReference = (e: NetworkEndpointReference) => { if (!e.endpointReferenceId || !e.kind) throw new NetworkEndpointInvalid('endpoint reference id and kind are required'); if (e.scheme && !['srt','rtmp','rtmps','udp','tcp','ndi','http','https','synthetic'].includes(e.scheme)) throw new NetworkEndpointInvalid('unsupported endpoint scheme'); if (e.host && /@/.test(e.host)) throw new NetworkEndpointInvalid('URL userinfo is rejected'); if (e.safeSummary && /(token|secret|password|passphrase|stream_key)=/i.test(e.safeSummary)) throw new NetworkEndpointInvalid('secret query parameter is rejected'); return true; };
const isPrivate = (h:string)=>/^(127\.|10\.|192\.168\.|169\.254\.|0\.0\.0\.0|255\.255\.255\.255|::1|fe80:|169\.254\.169\.254)/.test(h);
export const evaluateNetworkAddressPolicy = (endpoint:NetworkEndpointReference, policy:NetworkAddressPolicy=DEFAULT_NETWORK_ADDRESS_POLICY) => { validateNetworkEndpointReference(endpoint); const h=endpoint.host; if (!h) return true; if (policy.deniedDomains?.includes(h)) throw new NetworkAddressPolicyDenied(h); if (policy.allowedDomains?.length && !policy.allowedDomains.includes(h)) throw new NetworkAddressPolicyDenied(h); if (!policy.allowBindAllInterfaces && ['0.0.0.0','::'].includes(h)) throw new NetworkAddressPolicyDenied(h); if (!policy.allowLocalhost && /^(localhost|127\.|::1)/.test(h)) throw new NetworkAddressPolicyDenied(h); if (!policy.allowLinkLocal && /^(169\.254\.|fe80:)/.test(h)) throw new NetworkAddressPolicyDenied(h); if (!policy.allowPrivateNetwork && isPrivate(h)) throw new NetworkAddressPolicyDenied(h); return true; };

export class NetworkPacketHandleTracker { private owners=new Map<string,NetworkPacketOwnership>(); private released=new Set<string>(); track(h:string,o:NetworkPacketOwnership){ if(this.owners.has(h)) throw new NetworkOwnershipViolation(h); this.owners.set(h,o); } transfer(h:string,o:NetworkPacketOwnership){ if(!this.owners.has(h)||this.released.has(h)) throw new NetworkOwnershipViolation(h); this.owners.set(h,o); } release(h:string){ if(this.released.has(h)) throw new NetworkOwnershipViolation(h); this.released.add(h); this.owners.set(h,'RELEASED'); } retained(){ return [...this.owners.values()].filter(v=>v!=='RELEASED').length; } assertNoLeaks(){ if(this.retained()) throw new NetworkOwnershipViolation('retained'); return true; }}
export class NetworkPacketQueue { private q:NetworkPacketEnvelope[]=[]; private bytes=0; dropped=0; constructor(readonly config:NetworkPacketBufferConfiguration=DEFAULT_NETWORK_PACKET_BUFFER_CONFIG, private readonly release?:(p:NetworkPacketEnvelope)=>void){} enqueue(p:NetworkPacketEnvelope){ if(p.packetSize>this.config.maximumBytes){ this.dropped++; this.release?.(p); return false;} const would=()=>this.q.length>=this.config.maximumPackets || this.bytes+p.packetSize>this.config.maximumBytes; if(would()){ if(this.config.overflowPolicy==='REJECT'||this.config.overflowPolicy==='FAIL_SOURCE'){this.dropped++;this.release?.(p);return false;} if(this.config.overflowPolicy==='DROP_NEWEST'){this.dropped++;this.release?.(p);return true;} while(would()&&this.q.length){ const old=this.q.shift()!; this.bytes-=old.packetSize; this.dropped++; this.release?.(old);} } this.q.push(networkDeepFreeze({...p, metadata:safeMeta(p.metadata)})); this.bytes+=p.packetSize; return true;} dequeue(){ const p=this.q.shift(); if(p) this.bytes-=p.packetSize; return p;} clear(){ for(const p of this.q)this.release?.(p); this.q=[]; this.bytes=0;} snapshot():NetworkPacketQueueSnapshot{return networkDeepFreeze({depth:this.q.length,bytes:this.bytes,dropped:this.dropped,highWater:this.q.length>=this.config.highWaterMark});}}
export class NetworkJitterBuffer { private bySeq=new Map<number,NetworkPacketEnvelope>(); private seen=new Set<number>(); duplicates=0; late=0; gaps=0; expected:number|undefined=undefined; constructor(readonly config:NetworkJitterBufferConfiguration=DEFAULT_NETWORK_JITTER_BUFFER_CONFIG, private readonly release?:(p:NetworkPacketEnvelope)=>void){} push(p:NetworkPacketEnvelope){ if(this.seen.has(p.sequenceNumber)){this.duplicates++;this.release?.(p);return [];} this.seen.add(p.sequenceNumber); if(this.expected!==undefined && p.sequenceNumber<this.expected){this.late++;this.release?.(p);return [];} this.bySeq.set(p.sequenceNumber,p); const out:NetworkPacketEnvelope[]=[]; if(this.expected===undefined)this.expected=Math.min(...this.bySeq.keys()); while(this.bySeq.has(this.expected)){ out.push(this.bySeq.get(this.expected)!); this.bySeq.delete(this.expected); this.expected++; } if(this.bySeq.size>this.config.reorderingWindow && this.expected!==undefined){this.gaps++; this.expected=Math.min(...this.bySeq.keys());} return out;} clear(){for(const p of this.bySeq.values())this.release?.(p);this.bySeq.clear();this.seen.clear();this.expected=undefined;} snapshot():NetworkJitterBufferSnapshot{return networkDeepFreeze({depth:this.bySeq.size,durationNs:String(BigInt(this.bySeq.size)*this.config.targetLatencyNs),duplicates:this.duplicates,late:this.late,gaps:this.gaps});}}
export interface NetworkDemuxAdapter { pushPacket(packet:NetworkPacketEnvelope, context:Readonly<Record<string,unknown>>): NetworkDemuxResult|Promise<NetworkDemuxResult>; flush(reason:string):void; getStreams():readonly NetworkStreamDescriptor[]; }
export interface NetworkDecodeAdapter { decode(sample:NetworkElementarySample, context:Readonly<Record<string,unknown>>): SourceSampleBatch|Promise<SourceSampleBatch>; }
export interface NetworkElementarySample { readonly sourceId:string; readonly streamId:string; readonly mediaKind:'VIDEO'|'AUDIO'|'METADATA'; readonly sequenceNumber:bigint; readonly timestampNs:bigint; readonly durationNs:bigint; readonly generation:number; readonly payload:{readonly handleId:string}; readonly metadata:Readonly<Record<string,unknown>>; }
export interface NetworkDemuxResult { readonly samples: readonly NetworkElementarySample[]; readonly streams: readonly NetworkStreamDescriptor[]; readonly discontinuity:boolean; }
export class SyntheticNetworkDemuxAdapter implements NetworkDemuxAdapter { private streams:NetworkStreamDescriptor[]; constructor(streams:readonly NetworkStreamDescriptor[]){this.streams=[...streams];} pushPacket(p:NetworkPacketEnvelope):NetworkDemuxResult{const mk=(p.mediaKind==='AUDIO'?'AUDIO':p.mediaKind==='DATA'?'METADATA':'VIDEO') as 'VIDEO'|'AUDIO'|'METADATA'; return {samples:[{sourceId:p.sourceId,streamId:p.streamId??`${p.sourceId}:${mk.toLowerCase()}:0`,mediaKind:mk,sequenceNumber:BigInt(p.sequenceNumber),timestampNs:p.normalizedTimestampNs??p.sourceTimestampNs??p.arrivalTimestampNs,durationNs:33_333_333n,generation:p.generation,payload:p.payload,metadata:safeMeta(p.metadata)}],streams:this.streams,discontinuity:p.discontinuity};} flush(){} getStreams(){return this.streams.map(s=>networkDeepFreeze({...s}));}}
export class SyntheticNetworkDecodeAdapter implements NetworkDecodeAdapter { constructor(private readonly videoFormat:any, private readonly audioFormat:any){} decode(s:NetworkElementarySample):SourceSampleBatch{ const batch: any={videoFrames:[],audioBuffers:[],metadataSamples:[]}; if(s.mediaKind==='VIDEO') batch.videoFrames.push({sourceId:s.sourceId,streamId:s.streamId,sequenceNumber:s.sequenceNumber,sourceTimestampNs:s.timestampNs,normalizedTimestampNs:s.timestampNs,durationNs:s.durationNs,presentationTimestampNs:s.timestampNs,format:this.videoFormat,keyFrame:true,discontinuity:false,corrupted:false,droppedBefore:0,memoryDomain:'OPAQUE',payload:{handleId:s.payload.handleId,kind:'OPAQUE_TEST_HANDLE'},metadata:safeMeta(s.metadata)} satisfies VideoFrameEnvelope); else if(s.mediaKind==='AUDIO') batch.audioBuffers.push({sourceId:s.sourceId,streamId:s.streamId,sequenceNumber:s.sequenceNumber,sourceTimestampNs:s.timestampNs,normalizedTimestampNs:s.timestampNs,durationNs:s.durationNs,sampleCount:1600,format:this.audioFormat,discontinuity:false,corrupted:false,droppedBefore:0,payload:{handleId:s.payload.handleId,kind:'OPAQUE_TEST_HANDLE'},metadata:safeMeta(s.metadata)} satisfies AudioBufferEnvelope); else batch.metadataSamples.push({sourceId:s.sourceId,streamId:s.streamId,sequenceNumber:s.sequenceNumber,sourceTimestampNs:s.timestampNs,normalizedTimestampNs:s.timestampNs,payload:{contentType:'application/vnd.ubos.synthetic',handleId:s.payload.handleId,metadata:safeMeta(s.metadata)}} satisfies MetadataSampleEnvelope); return networkDeepFreeze(batch) as SourceSampleBatch; }}
export interface NetworkReceiveBackend { readonly backendId:string; resolve?(request:Readonly<Record<string,unknown>>, context:Readonly<Record<string,unknown>>):Promise<Readonly<Record<string,unknown>>>; connect(request:Readonly<Record<string,unknown>>, context:Readonly<Record<string,unknown>>):Promise<Readonly<Record<string,unknown>>>; start(onPacket:(packet:NetworkPacketEnvelope)=>void,onStreamDiscovered:(stream:NetworkStreamDescriptor)=>void,onStateChanged:(state:NetworkConnectionState)=>void,onError:(error:NetworkSourceError)=>void,context:Readonly<Record<string,unknown>>):Promise<void>; stop(context:Readonly<Record<string,unknown>>):Promise<void>; disconnect(context:Readonly<Record<string,unknown>>):Promise<void>; getStatistics?():Promise<Readonly<Record<string,unknown>>>; }
export class SyntheticNetworkBackend implements NetworkReceiveBackend { readonly backendId:string; private active=false; constructor(readonly scenario:{readonly backendId?:string; readonly packets?:number; readonly fail?:'connect'|'handshake'|'authentication'|'encryption'|'remote-close'; readonly streams?:readonly NetworkStreamDescriptor[]}={}){this.backendId=scenario.backendId??'synthetic-network-backend';} async connect(){ if(this.scenario.fail) throw new NetworkSourceError(`Network${this.scenario.fail}Failed`,'Synthetic network failure'); return {sessionId:`session:${this.backendId}`};} async start(onPacket:(p:NetworkPacketEnvelope)=>void,onStream:(s:NetworkStreamDescriptor)=>void,onState:(s:NetworkConnectionState)=>void){this.active=true; for(const s of this.scenario.streams??[]) onStream(s); onState('RECEIVING'); const n=this.scenario.packets??0; for(let i=0;i<n && this.active;i++) onPacket(createSyntheticNetworkPacket({sequenceNumber:i,backendId:this.backendId})); if(this.scenario.fail==='remote-close') onState('REMOTE_CLOSED');} async stop(_context:Readonly<Record<string,unknown>>={}){this.active=false;} async disconnect(_context:Readonly<Record<string,unknown>>={}){this.active=false;} getHealth():NetworkBackendHealthSnapshot{return networkDeepFreeze({backendId:this.backendId,healthy:true,activeSessions:this.active?1:0,retainedHandles:0,updatedAtNs:String(now())});}}
export const createSyntheticNetworkStream = (sourceId:string, mediaKind:'VIDEO'|'AUDIO'|'METADATA'='VIDEO', index=0):NetworkStreamDescriptor=>networkDeepFreeze({streamId:`${id(sourceId)}:${mediaKind.toLowerCase()}:${index}`,mediaKind,codec:{name:mediaKind==='VIDEO'?'synthetic-video':mediaKind==='AUDIO'?'synthetic-audio':'synthetic-data'},timebase:{numerator:1,denominator:1_000_000_000},...(mediaKind==='VIDEO'?{dimensions:{width:1280,height:720},frameRate:{numerator:30,denominator:1}}:{}),...(mediaKind==='AUDIO'?{sampleRate:48000,channelLayout:'stereo'}:{}),encrypted:false,selected:true,default:index===0,metadata:{synthetic:true}});
export const createNetworkIdentity = (p:{sourceId:string;providerId?:string;protocol?:NetworkSourceProtocol;connectionMode?:NetworkConnectionMode;endpoint?:NetworkEndpointReference;nowNs?:bigint}):NetworkSourceIdentity=>{const t=String(p.nowNs??0n);return networkDeepFreeze({sourceId:p.sourceId,providerId:p.providerId??'synthetic-network-provider',protocol:p.protocol??'SYNTHETIC_NETWORK',connectionMode:p.connectionMode??'CALLER',endpointReferenceId:p.endpoint?.endpointReferenceId??`endpoint:${p.sourceId}`,safeEndpointSummary:p.endpoint?.safeSummary??'synthetic network endpoint',persistentIdentity:`network:${id(p.sourceId)}`,sessionIdentity:`network-session:${id(p.sourceId)}:${t}`,createdAtNs:t,updatedAtNs:t,tags:['network'],metadata:{synthetic:p.protocol==='SYNTHETIC_NETWORK'}});};
export const createNetworkDescriptor = (sourceId:string, partial:Partial<NetworkSourceDescriptor>={}):NetworkSourceDescriptor=>{const endpoint=partial.endpoint??networkDeepFreeze({endpointReferenceId:`endpoint:${sourceId}`,kind:'SYNTHETIC',scheme:'synthetic',safeSummary:'synthetic network endpoint'}); const identity=partial.networkIdentity??createNetworkIdentity({sourceId,endpoint,...(partial.protocol ? {protocol:partial.protocol} : {})}); return networkDeepFreeze({id:sourceId,providerId:identity.providerId,type:'SRT',displayName:`Network Source ${sourceId}`,mediaKinds:['VIDEO'],capabilities:{network:true,protocol:identity.protocol},supportedFormats:[],availability:'AVAILABLE',persistent:true,reconnectable:true,discoverable:true,virtual:true,requiresPermission:false,permissionState:'NOT_REQUIRED',supportsVideo:true,supportsAudio:false,supportsMetadata:true,supportsSeeking:false,supportsLooping:false,supportsDynamicFormatChange:true,estimatedLatencyClass:'LOW',clockDomain:'NETWORK_SENDER',acquisitionMode:'PUSH',tags:['network'],metadata:{endpoint:identity.safeEndpointSummary},networkIdentity:identity,protocol:identity.protocol,connectionMode:identity.connectionMode,endpoint,supportedTransportFeatures:syntheticNetworkCapabilities,encryptionSupport:true,authenticationSupport:true,reconnectCapability:true,failoverCapability:true,discoverySupport:true,latencyMode:'LOW_LATENCY',expectedLatencyRangeNs:[20_000_000n,1_000_000_000n],jitterBufferPolicy:DEFAULT_NETWORK_JITTER_BUFFER_CONFIG,packetOrderingPolicy:'REORDER_WITHIN_WINDOW',timestampSourcePolicy:'SENDER',...partial});};
export const createSyntheticNetworkPacket=(p:Partial<NetworkPacketEnvelope>={}):NetworkPacketEnvelope=>networkDeepFreeze({sourceId:p.sourceId??'network:synthetic',sessionId:p.sessionId??'session:synthetic',protocol:p.protocol??'SYNTHETIC_NETWORK',sequenceNumber:p.sequenceNumber??0,arrivalTimestampNs:p.arrivalTimestampNs??BigInt(p.sequenceNumber??0)*33_333_333n,sourceTimestampNs:p.sourceTimestampNs??BigInt(p.sequenceNumber??0)*33_333_333n,normalizedTimestampNs:p.normalizedTimestampNs??BigInt(p.sequenceNumber??0)*33_333_333n,payloadType:p.payloadType??'synthetic',mediaKind:p.mediaKind??'VIDEO',packetSize:p.packetSize??1024,markerFlags:p.markerFlags??[],discontinuity:p.discontinuity??false,corrupted:p.corrupted??false,encrypted:p.encrypted??false,recovered:p.recovered??false,retransmitted:p.retransmitted??false,duplicate:p.duplicate??false,outOfOrder:p.outOfOrder??false,generation:p.generation??1,backendId:p.backendId??'synthetic-network-backend',payload:p.payload??{handleId:`packet:${p.sequenceNumber??0}`,byteLength:p.packetSize??1024},ownership:p.ownership??'OWNED_BY_BACKEND',metadata:safeMeta(p.metadata)});
export class DefaultNetworkMediaSource implements MediaSource { readonly descriptor:NetworkSourceDescriptor; private state:NetworkConnectionState='REGISTERED'; private generation=0; private sessionId?:string; private streams:NetworkStreamDescriptor[]=[]; private tracker=new NetworkPacketHandleTracker(); private packetQueue:NetworkPacketQueue; private jitter:NetworkJitterBuffer; private decoded:SourceSampleBatch={videoFrames:[],audioBuffers:[],metadataSamples:[]}; constructor(descriptor:NetworkSourceDescriptor, private readonly backend:NetworkReceiveBackend=new SyntheticNetworkBackend(), private readonly demux:NetworkDemuxAdapter=new SyntheticNetworkDemuxAdapter([createSyntheticNetworkStream(descriptor.id)]), private readonly decoder:NetworkDecodeAdapter=new SyntheticNetworkDecodeAdapter({kind:'VIDEO',id:'synthetic-video',width:1280,height:720,frameRate:{numerator:30,denominator:1},pixelFormat:'opaque',colorSpace:'bt709',colorRange:'limited',transferCharacteristic:'bt709',chromaSubsampling:'4:2:0',scan:'PROGRESSIVE',fieldOrder:'NONE',aspectRatio:'16:9',alpha:false,bitDepth:8,rotation:0,memoryDomain:'OPAQUE',hardwareAcceleration:'NONE',latencyClass:'LOW'},{kind:'AUDIO',id:'synthetic-audio',sampleRate:48000,channelCount:2,channelLayout:'stereo',sampleFormat:'f32',planar:false,bitDepth:32,clockDomain:'NETWORK_SENDER',framesPerBuffer:1600,latencyHint:'LOW'})){this.descriptor=descriptor; this.packetQueue=new NetworkPacketQueue(descriptor.jitterBufferPolicy?DEFAULT_NETWORK_PACKET_BUFFER_CONFIG:DEFAULT_NETWORK_PACKET_BUFFER_CONFIG,p=>this.safeRelease(p)); this.jitter=new NetworkJitterBuffer(descriptor.jitterBufferPolicy,p=>this.safeRelease(p));}
  async initialize():Promise<SourceOperationResult>{this.state='REGISTERED';return {ok:true,sourceId:this.descriptor.id,state:'READY'};} async connect(c:SourceRuntimeContext):Promise<SourceOperationResult>{const r=await this.connectNetwork({endpoint:this.descriptor.endpoint,connectionMode:this.descriptor.connectionMode,timeoutNs:1_000_000_000n,handshakeTimeoutNs:1_000_000_000n,authenticationTimeoutNs:1_000_000_000n},{nowNs:c.nowNs});return {ok:r.ok,sourceId:this.descriptor.id,state:r.ok?'CONNECTED' as const:'FAILED' as const};} async activate(c:SourceRuntimeContext):Promise<SourceOperationResult>{const r=await this.startReceiving({nowNs:c.nowNs});return {ok:r.ok,sourceId:this.descriptor.id,state:r.ok?'ACTIVE' as const:'FAILED' as const};} async deactivate(c:SourceRuntimeContext):Promise<SourceOperationResult>{const r=await this.stopReceiving({nowNs:c.nowNs});return {ok:r.ok,sourceId:this.descriptor.id,state:'CONNECTED' as const};} async disconnect(c:SourceRuntimeContext):Promise<SourceOperationResult>{const r=await this.disconnectNetwork({nowNs:c.nowNs});return {ok:r.ok,sourceId:this.descriptor.id,state:'DISCONNECTED' as const};} async shutdown(c:SourceRuntimeContext):Promise<SourceOperationResult>{await this.stopReceiving({nowNs:c.nowNs}); await this.disconnectNetwork({nowNs:c.nowNs}); this.packetQueue.clear(); this.jitter.clear(); return {ok:true,sourceId:this.descriptor.id,state:'STOPPED' as const};} async pull():Promise<SourceSampleBatch>{const out=this.decoded; this.decoded={videoFrames:[],audioBuffers:[],metadataSamples:[]}; return networkDeepFreeze(out);} async connectNetwork(request:NetworkConnectRequest, context:NetworkConnectionContext):Promise<NetworkConnectResult>{ if(this.state==='CONNECTED'||this.state==='RECEIVING') throw new NetworkAlreadyConnected(this.descriptor.id); evaluateNetworkAddressPolicy(request.endpoint,request.addressPolicy); this.state='CONNECTING'; this.generation++; const res=await this.backend.connect(request as any,context as any); this.sessionId=String((res as any).sessionId??`session:${this.descriptor.id}:${this.generation}`); this.state='CONNECTED'; return networkDeepFreeze({ok:true,sourceId:this.descriptor.id,connectionState:this.state,generation:this.generation,connected:true,sessionId:this.sessionId});}
  async startReceiving(context:NetworkReceiveContext):Promise<NetworkOperationResult>{ if(this.state==='RECEIVING') throw new NetworkAlreadyReceiving(this.descriptor.id); if(this.state!=='CONNECTED') throw new NetworkNotConnected(this.descriptor.id); await this.backend.start(p=>void this.acceptPacket(p),s=>{this.streams=[...this.streams.filter(x=>x.streamId!==s.streamId),s].sort((a,b)=>a.streamId.localeCompare(b.streamId));},s=>{this.state=s;},()=>{this.state='FAILED';},context as any); const callbackState=this.state as NetworkConnectionState; if(callbackState!=='REMOTE_CLOSED'&&callbackState!=='FAILED') this.state='RECEIVING'; this.drainPackets(); return networkDeepFreeze({ok:true,sourceId:this.descriptor.id,connectionState:this.state,generation:this.generation});}
  async stopReceiving(context:NetworkReceiveContext):Promise<NetworkOperationResult>{ await this.backend.stop(context as any); if(this.state==='RECEIVING'||this.state==='REMOTE_CLOSED') this.state='CONNECTED'; this.packetQueue.clear(); this.jitter.clear(); return networkDeepFreeze({ok:true,sourceId:this.descriptor.id,connectionState:this.state,generation:this.generation});}
  async reconnect(request:NetworkReconnectRequest, context:NetworkConnectionContext):Promise<NetworkReconnectResult>{ await this.disconnectNetwork(context); const r=await this.connectNetwork(request,context); return {...r,attempts:1};}
  async disconnectNetwork(context:NetworkConnectionContext):Promise<NetworkOperationResult>{ await this.backend.disconnect(context as any); this.packetQueue.clear(); this.jitter.clear(); this.state='DISCONNECTED'; return networkDeepFreeze({ok:true,sourceId:this.descriptor.id,connectionState:this.state,generation:this.generation});}
  private acceptPacket(packet:NetworkPacketEnvelope){ if(this.state!=='RECEIVING'&&this.state!=='CONNECTED') {this.safeRelease(packet); return;} if(packet.generation!==this.generation && packet.generation!==1){this.safeRelease(packet);return;} this.tracker.track(packet.payload.handleId,packet.ownership); this.tracker.transfer(packet.payload.handleId,'OWNED_BY_SOURCE'); this.packetQueue.enqueue({...packet,sourceId:this.descriptor.id,sessionId:this.sessionId??packet.sessionId,generation:this.generation,ownership:'OWNED_BY_SOURCE'}); }
  private drainPackets(){ let p:NetworkPacketEnvelope|undefined; while((p=this.packetQueue.dequeue())) for(const ordered of this.jitter.push(p)) { const res=this.demux.pushPacket(ordered,{} ) as NetworkDemuxResult; for(const s of res.samples){ const b=this.decoder.decode(s,{}) as SourceSampleBatch; this.decoded={videoFrames:[...this.decoded.videoFrames,...b.videoFrames],audioBuffers:[...this.decoded.audioBuffers,...b.audioBuffers],metadataSamples:[...this.decoded.metadataSamples,...b.metadataSamples],}; } } }
  private safeRelease(p:NetworkPacketEnvelope){ try{this.tracker.release(p.payload.handleId);}catch{ /* duplicate drops are reported by invariants */ } }
  snapshot():NetworkSourceSnapshot{return networkDeepFreeze({descriptor:this.descriptor,connection:this.state,health:this.health(),streams:this.streams});} health():NetworkSourceHealthSnapshot{return networkDeepFreeze({sourceId:this.descriptor.id,lifecycleState:this.state,connectionState:this.state,healthState:this.state==='FAILED'?'FAILED':this.state==='RECEIVING'?'HEALTHY':'UNKNOWN',protocol:this.descriptor.protocol,connectionMode:this.descriptor.connectionMode,connected:['CONNECTED','RECEIVING','REMOTE_CLOSED'].includes(this.state),active:this.state==='RECEIVING',available:this.state!=='FAILED',authenticated:false,encrypted:false,safeEndpointSummary:this.descriptor.endpoint.safeSummary,backendId:this.backend.backendId,sessionGeneration:this.generation,selectedStreams:this.streams.filter(s=>s.selected).map(s=>s.streamId),packetQueueDepth:this.packetQueue.snapshot().depth,packetQueueBytes:this.packetQueue.snapshot().bytes,jitterBufferDepth:this.jitter.snapshot().depth,jitterBufferDurationNs:this.jitter.snapshot().durationNs,duplicateRate:0,outOfOrderRate:0,latePacketRate:0,missingPacketCount:this.jitter.gaps,reconnectAttempts:0,failoverSwitches:0,discontinuities:0,consecutiveFailures:0,updatedAtNs:String(now())});} assertInvariants(){ if(this.packetQueue.snapshot().depth>DEFAULT_NETWORK_PACKET_BUFFER_CONFIG.maximumPackets) throw new NetworkSourceError('NetworkInvariantViolation','packet queue bound exceeded'); return networkDeepFreeze({ok:true,sourceId:this.descriptor.id,retainedHandles:this.tracker.retained()});}}
export interface NetworkMediaSource extends MediaSource { readonly descriptor:NetworkSourceDescriptor; connectNetwork(request:NetworkConnectRequest,context:NetworkConnectionContext):Promise<NetworkConnectResult>; startReceiving(context:NetworkReceiveContext):Promise<NetworkOperationResult>; stopReceiving(context:NetworkReceiveContext):Promise<NetworkOperationResult>; reconnect(request:NetworkReconnectRequest,context:NetworkConnectionContext):Promise<NetworkReconnectResult>; disconnectNetwork(context:NetworkConnectionContext):Promise<NetworkOperationResult>; snapshot():NetworkSourceSnapshot; assertInvariants():Readonly<Record<string,unknown>>; }
export interface NetworkSourceDiscoveryRequest { readonly providerId?:string; readonly protocols?:readonly NetworkSourceProtocol[]; readonly modes?:readonly NetworkConnectionMode[]; readonly metadata?:Readonly<Record<string,unknown>>; }
export interface NetworkSourceDiscoveryResult { readonly descriptors:readonly NetworkSourceDescriptor[]; readonly warnings:readonly string[]; readonly durationNs:string; }
export interface NetworkSourceProvider extends SourceProvider { discoverNetworkSources?(request:NetworkSourceDiscoveryRequest, context:NetworkProviderContext):Promise<NetworkSourceDiscoveryResult>; createNetworkSource(descriptor:NetworkSourceDescriptor, context:NetworkProviderContext):Promise<NetworkMediaSource>; getBackendHealth():Readonly<NetworkBackendHealthSnapshot>; }
export class SyntheticNetworkSourceProvider implements NetworkSourceProvider { readonly descriptor={id:'synthetic-network-provider',displayName:'Synthetic Network Source Provider',version:'5.2.9',sourceTypes:['SRT','RTMP','NDI','WEBRTC','CUSTOM'] as any,acquisitionModes:['PUSH','HYBRID'] as any}; private backend=new SyntheticNetworkBackend({streams:[createSyntheticNetworkStream('synthetic-network')]}); async discoverNetworkSources(_request:NetworkSourceDiscoveryRequest={},{nowNs:_nowNs}:NetworkProviderContext={nowNs:now}){return networkDeepFreeze({descriptors:[createNetworkDescriptor('synthetic-network')],warnings:[],durationNs:'0'});} async discover(_request:any={}, _context:SourceProviderContext={nowNs:now}){const r=await this.discoverNetworkSources(); return {descriptors:r.descriptors,unavailable:[],warnings:r.warnings,providerErrors:[],durationNs:r.durationNs,partial:false};} async createNetworkSource(d:NetworkSourceDescriptor, _context:NetworkProviderContext={nowNs:now}):Promise<NetworkMediaSource>{return new DefaultNetworkMediaSource(d,this.backend);} async createSource(d:SourceDescriptor, _context:SourceProviderContext={nowNs:now}):Promise<MediaSource>{return this.createNetworkSource(d as NetworkSourceDescriptor, {nowNs:now});} async shutdown(_context:SourceProviderContext={nowNs:now}){await this.backend.disconnect({});} getBackendHealth(){return this.backend.getHealth();}}
export class NetworkSourceRegistry { private providers=new Map<string,NetworkSourceProvider>(); private sources=new Map<string,NetworkMediaSource>(); registerProvider(p:NetworkSourceProvider){ if(this.providers.has(p.descriptor.id)) throw new DuplicateNetworkSource(p.descriptor.id); this.providers.set(p.descriptor.id,p);} async registerSource(d:NetworkSourceDescriptor, providerId=d.providerId){ if(this.sources.has(d.id)) throw new DuplicateNetworkSource(d.id); const p=this.providers.get(providerId); if(!p) throw new NetworkSourceNotFound(providerId); validateNetworkEndpointReference(d.endpoint); const s=await p.createNetworkSource(d,{nowNs:now}); this.sources.set(d.id,s); return s;} get(sourceId:string){const s=this.sources.get(sourceId); if(!s) throw new NetworkSourceNotFound(sourceId); return s;} snapshot():NetworkTelemetrySnapshot{return networkDeepFreeze({registeredNetworkSourceCount:this.sources.size,connectedNetworkSourceCount:[...this.sources.values()].filter(s=>s.snapshot().health.connected).length,activeNetworkSourceCount:[...this.sources.values()].filter(s=>s.snapshot().health.active).length,totalNetworkPacketsReceived:0,totalNetworkPacketsDropped:0,totalNetworkPacketsDuplicate:0,totalNetworkPacketsOutOfOrder:0,totalNetworkPacketsLate:0,totalNetworkBytesReceived:0,totalNetworkVideoFramesPublished:0,totalNetworkAudioBuffersPublished:0,totalNetworkMetadataSamplesPublished:0,totalNetworkConnectAttempts:0,successfulNetworkConnections:0,failedNetworkConnections:0,totalNetworkReconnectAttempts:0,currentNetworkSourceIds:[...this.sources.keys()].sort(),networkHealthSummary:{}});} assertInvariants(){return [...this.sources.values()].map(s=>s.assertInvariants());}}
export const createNetworkSourceRegistry=()=>new NetworkSourceRegistry();
export function createNetworkCommandHandlers(registry:NetworkSourceRegistry): Readonly<Record<NetworkCommandType, TypedRuntimeCommandHandler<any>>> { const h=(type:NetworkCommandType,fn:(p:any)=>Promise<unknown>|unknown):TypedRuntimeCommandHandler<any>=>({commandType:type,idempotent:true,async execute(c){return {status:'SUCCEEDED',value:await fn(c.payload)}}}); return { NETWORK_REGISTER:h('NETWORK_REGISTER',(p)=>registry.registerSource(p.descriptor)), NETWORK_CONNECT:h('NETWORK_CONNECT',(p)=>registry.get(p.sourceId).connectNetwork(p.request,{nowNs:now})), NETWORK_START:h('NETWORK_START',(p)=>registry.get(p.sourceId).startReceiving({nowNs:now})), NETWORK_STOP:h('NETWORK_STOP',(p)=>registry.get(p.sourceId).stopReceiving({nowNs:now})), NETWORK_DISCONNECT:h('NETWORK_DISCONNECT',(p)=>registry.get(p.sourceId).disconnectNetwork({nowNs:now})), NETWORK_RECONNECT:h('NETWORK_RECONNECT',(p)=>registry.get(p.sourceId).reconnect(p.request,{nowNs:now})), NETWORK_SET_ENDPOINT:h('NETWORK_SET_ENDPOINT',()=>({ok:true,redacted:true})), NETWORK_SET_CREDENTIAL_PROFILE:h('NETWORK_SET_CREDENTIAL_PROFILE',()=>({ok:true,redacted:true})), NETWORK_SET_ENCRYPTION_PROFILE:h('NETWORK_SET_ENCRYPTION_PROFILE',()=>({ok:true,redacted:true})), NETWORK_SET_LATENCY:h('NETWORK_SET_LATENCY',()=>({ok:true})), NETWORK_SET_JITTER_BUFFER:h('NETWORK_SET_JITTER_BUFFER',()=>({ok:true})), NETWORK_SELECT_STREAMS:h('NETWORK_SELECT_STREAMS',()=>({ok:true})), NETWORK_ENABLE_FAILOVER:h('NETWORK_ENABLE_FAILOVER',()=>({ok:true})), NETWORK_DISABLE_FAILOVER:h('NETWORK_DISABLE_FAILOVER',()=>({ok:true})), NETWORK_ENABLE:h('NETWORK_ENABLE',()=>({ok:true})), NETWORK_DISABLE:h('NETWORK_DISABLE',()=>({ok:true})), NETWORK_REFRESH_STREAMS:h('NETWORK_REFRESH_STREAMS',()=>({ok:true})) }; }
