import type { ProductionGraph } from '../../shared/src/production-graph.js';
import type { MediaExecutionAdapter, MediaExecutionAdapterResponse, MediaExecutionIntent, MediaExecutionIntentType } from './index.js';
import type { MediaClock } from './sync/clock.js';

export const MOCK_ORCHESTRATION_MODE = true;
export type MediaIntentKind = 'video' | 'audio' | 'render' | 'output' | 'sync';
export type TargetSubsystem = 'video' | 'audio' | 'render' | 'output' | 'sync';
export type OrchestrationEventType = 'ORCHESTRATION_INTENT_RECEIVED'|'ORCHESTRATION_PLAN_CREATED'|'ORCHESTRATION_PLAN_EXECUTED'|'ORCHESTRATION_CONFLICT_DETECTED'|'ORCHESTRATION_DEPENDENCY_RESOLVED'|'ORCHESTRATION_FRAME_COMPLETE';
export interface MediaTimingConstraint { readonly earliestFrameTimestamp?: number; readonly deadlineFrameTimestamp?: number; readonly requestedFrameTimestamp?: number; }
export interface MediaIntent<TPayload = Record<string, unknown>> { readonly id: string; readonly type: MediaIntentKind; readonly executionType: MediaExecutionIntentType; readonly sourceGraphRevision: number; readonly dependencies: readonly string[]; readonly priority: number; readonly targetSubsystem: TargetSubsystem; readonly payload: Readonly<TPayload>; readonly timingConstraint: MediaTimingConstraint; readonly submittedAt: string; }
export interface MediaIntentGraph { readonly revision: number; readonly intents: readonly MediaIntent[]; readonly edges: readonly { from: string; to: string }[]; }
export interface MediaFramePlan { readonly id: string; readonly frameTimestamp: number; readonly orderedExecutionSteps: readonly MediaIntent[]; readonly subsystemBatches: { readonly videoOps: readonly MediaIntent[]; readonly audioOps: readonly MediaIntent[]; readonly renderOps: readonly MediaIntent[]; readonly outputOps: readonly MediaIntent[]; readonly syncOps: readonly MediaIntent[]; }; readonly conflicts: readonly OrchestrationConflict[]; }
export interface OrchestrationConflict { readonly id: string; readonly intentIds: readonly string[]; readonly type: 'circular_dependency'|'priority'|'timestamp'|'validation'; readonly message: string; }
export interface OrchestrationEvent { readonly id: string; readonly type: OrchestrationEventType; readonly timestamp: string; readonly frameTimestamp?: number; readonly intentId?: string; readonly payload: Readonly<Record<string, unknown>>; }
export interface SubsystemExecutionCoordinator { canExecute(intent: MediaIntent): boolean; validate(intent: MediaIntent): readonly string[]; execute(intent: MediaIntent, graph?: ProductionGraph): Promise<MediaExecutionAdapterResponse>|MediaExecutionAdapterResponse; }

let seq = 0;
const videoTypes = new Set<MediaExecutionIntentType>(['BUILD_VIDEO_ROUTE_PLAN','UPDATE_VIDEO_ROUTE','ACTIVATE_VIDEO_ROUTE','DEACTIVATE_VIDEO_ROUTE','ROUTE_PROGRAM_VIDEO','ROUTE_PREVIEW_VIDEO','ROUTE_MULTIVIEW_VIDEO','ROUTE_RECORDING_VIDEO','ROUTE_STREAM_VIDEO']);
const audioTypes = new Set<MediaExecutionIntentType>(['BUILD_AUDIO_ROUTE_PLAN','UPDATE_AUDIO_ROUTE','ACTIVATE_AUDIO_ROUTE','DEACTIVATE_AUDIO_ROUTE','MUTE_AUDIO_ROUTE','UNMUTE_AUDIO_ROUTE','SET_AUDIO_ROUTE_GAIN','BUILD_PROGRAM_MIX','BUILD_STREAM_MIX','BUILD_RECORDING_MIX','BUILD_MONITOR_MIX','BUILD_GUEST_RETURN_MIX','UPDATE_AUDIO_MIX']);
const renderTypes = new Set<MediaExecutionIntentType>(['BUILD_SCENE_COMPOSITION','UPDATE_SCENE_COMPOSITION','RENDER_PROGRAM_COMPOSITION','RENDER_PREVIEW_COMPOSITION','RENDER_MULTIVIEW_COMPOSITION','RENDER_BROWSER_COMPOSITION','START_BROWSER_RENDERER','STOP_BROWSER_RENDERER','UPDATE_BROWSER_RENDER_TARGET','RENDER_FRAME','SELECT_RENDER_BACKEND','CLEAR_RENDER_CACHE','FORCE_FULL_RENDER','UPDATE_RENDER_PERFORMANCE_MODE','REPORT_RENDER_HEALTH','APPLY_LAYOUT']);
const outputTypes = new Set<MediaExecutionIntentType>(['START_STREAM','STOP_STREAM','START_RECORDING','STOP_RECORDING','UPDATE_DESTINATION']);
const executionOrder: readonly MediaExecutionIntentType[] = ['ROUTE_PROGRAM_VIDEO','ROUTE_PREVIEW_VIDEO','BUILD_VIDEO_ROUTE_PLAN','BUILD_AUDIO_ROUTE_PLAN','UPDATE_AUDIO_MIX','UPDATE_SCENE_COMPOSITION','BUILD_SCENE_COMPOSITION','UPDATE_DESTINATION','ROUTE_STREAM_VIDEO','RENDER_BROWSER_COMPOSITION','RENDER_FRAME'];
function defaultPriority(type: MediaExecutionIntentType) { const index = executionOrder.indexOf(type); return index === -1 ? 0 : 1000 - index; }
export function subsystemForExecutionType(type: MediaExecutionIntentType): TargetSubsystem { if (videoTypes.has(type)) return 'video'; if (audioTypes.has(type)) return 'audio'; if (renderTypes.has(type)) return 'render'; if (outputTypes.has(type)) return 'output'; return 'sync'; }
export function toMediaIntent(intent: MediaExecutionIntent): MediaIntent { const targetSubsystem = subsystemForExecutionType(intent.type); return { id: intent.id, type: targetSubsystem, executionType: intent.type, sourceGraphRevision: intent.graphRevision, dependencies: (intent.payload.dependencies as string[]|undefined) ?? [], priority: Number(intent.payload.priority ?? defaultPriority(intent.type)), targetSubsystem, payload: intent.payload, timingConstraint: typeof intent.payload.frameTimestamp === 'number' ? { requestedFrameTimestamp: intent.payload.frameTimestamp } : {}, submittedAt: intent.timestamp }; }
export function toExecutionIntent(intent: MediaIntent, frameTimestamp: number): MediaExecutionIntent { return { id: intent.id, type: intent.executionType, timestamp: new Date(frameTimestamp).toISOString(), graphRevision: intent.sourceGraphRevision, payload: { ...intent.payload, frameTimestamp, orchestrationSubsystem: intent.targetSubsystem } }; }

export class AdapterBackedCoordinator implements SubsystemExecutionCoordinator { constructor(private subsystem: TargetSubsystem, private adapter?: MediaExecutionAdapter) {} canExecute(intent: MediaIntent) { return intent.targetSubsystem === this.subsystem; } validate(intent: MediaIntent) { return this.canExecute(intent) ? [] : [`Intent ${intent.id} targets ${intent.targetSubsystem}, not ${this.subsystem}`]; } execute(intent: MediaIntent, graph?: ProductionGraph) { if (MOCK_ORCHESTRATION_MODE || !this.adapter) return { adapterName: `${this.subsystem}-orchestration-mock`, success: true, timestamp: new Date().toISOString(), latencyMs: 0, warnings: [`Mock orchestration executed ${intent.executionType}`], errors: [] }; return this.adapter.execute(toExecutionIntent(intent, intent.timingConstraint.requestedFrameTimestamp ?? 0), graph as ProductionGraph); } }
export class VideoExecutionCoordinator extends AdapterBackedCoordinator { constructor(adapter?: MediaExecutionAdapter) { super('video', adapter); } }
export class AudioExecutionCoordinator extends AdapterBackedCoordinator { constructor(adapter?: MediaExecutionAdapter) { super('audio', adapter); } }
export class RenderExecutionCoordinator extends AdapterBackedCoordinator { constructor(adapter?: MediaExecutionAdapter) { super('render', adapter); } }
export class OutputExecutionCoordinator extends AdapterBackedCoordinator { constructor(adapter?: MediaExecutionAdapter) { super('output', adapter); } }

export class MediaOrchestrationEngine {
  private intentQueue: MediaIntent[] = []; private activeFramePlans = new Map<number, MediaFramePlan>(); private dependencyGraphCache?: MediaIntentGraph; private lastExecutionState: Record<string, unknown> = {}; private subsystemStateSnapshot: Record<TargetSubsystem, string> = { video:'idle', audio:'idle', render:'idle', output:'idle', sync:'idle' }; private events: OrchestrationEvent[] = []; private conflicts: OrchestrationConflict[] = [];
  constructor(private clock: MediaClock, private coordinators: readonly SubsystemExecutionCoordinator[] = [new VideoExecutionCoordinator(), new AudioExecutionCoordinator(), new RenderExecutionCoordinator(), new OutputExecutionCoordinator(), new AdapterBackedCoordinator('sync')]) {}
  submitIntent(intent: MediaIntent) { this.intentQueue = [...this.intentQueue, intent].sort(compareIntents); this.emit('ORCHESTRATION_INTENT_RECEIVED', { intentType: intent.executionType }, undefined, intent.id); return intent; }
  buildDependencyGraph(intents = this.intentQueue): MediaIntentGraph { return { revision: Math.max(0, ...intents.map((i)=>i.sourceGraphRevision)), intents: [...intents].sort(compareIntents), edges: intents.flatMap((i)=>i.dependencies.map((from)=>({ from, to: i.id }))).sort((a,b)=>`${a.from}:${a.to}`.localeCompare(`${b.from}:${b.to}`)) }; }
  resolveIntentGraph() { const graph = this.buildDependencyGraph(); this.dependencyGraphCache = graph; this.conflicts = [...this.detectCircularDependencies(graph), ...this.resolvePriorityConflicts(graph), ...this.resolveTimestampConflicts(graph)]; this.conflicts.forEach((c)=>this.emit('ORCHESTRATION_CONFLICT_DETECTED', { conflict: c })); this.emit('ORCHESTRATION_DEPENDENCY_RESOLVED', { edgeCount: graph.edges.length, intentCount: graph.intents.length }); return graph; }
  topologicalSortIntents(graph = this.resolveIntentGraph()) { const indegree = new Map(graph.intents.map((i)=>[i.id,0])); graph.edges.forEach((e)=>indegree.set(e.to,(indegree.get(e.to)??0)+1)); const byId = new Map(graph.intents.map((i)=>[i.id,i])); const ready = graph.intents.filter((i)=>indegree.get(i.id)===0).sort(compareIntents); const out: MediaIntent[] = []; while (ready.length) { const next = ready.shift()!; out.push(next); graph.edges.filter((e)=>e.from===next.id).sort((a,b)=>a.to.localeCompare(b.to)).forEach((e)=>{ indegree.set(e.to,(indegree.get(e.to)??0)-1); if (indegree.get(e.to)===0 && byId.get(e.to)) ready.push(byId.get(e.to)!); ready.sort(compareIntents); }); } return out.length === graph.intents.length ? out : [...graph.intents].sort(compareIntents); }
  detectCircularDependencies(graph = this.buildDependencyGraph()) { const sorted = this.topologicalSortAcyclic(graph); return sorted.length === graph.intents.length ? [] : [{ id:`conflict-${++seq}`, intentIds: graph.intents.map((i)=>i.id), type:'circular_dependency' as const, message:'Circular dependency detected in media intent graph' }]; }
  resolvePriorityConflicts(graph = this.buildDependencyGraph()) { return graph.intents.flatMap((a, idx)=>graph.intents.slice(idx+1).filter((b)=>a.priority===b.priority && a.targetSubsystem===b.targetSubsystem && a.id!==b.id).map((b)=>({ id:`conflict-${++seq}`, intentIds:[a.id,b.id], type:'priority' as const, message:'Equal priority resolved deterministically by id' }))).slice(0,10); }
  resolveTimestampConflicts(graph = this.buildDependencyGraph()) { return graph.intents.filter((i)=>i.timingConstraint.deadlineFrameTimestamp !== undefined && i.timingConstraint.deadlineFrameTimestamp < this.clock.getState().elapsedTime).map((i)=>({ id:`conflict-${++seq}`, intentIds:[i.id], type:'timestamp' as const, message:'Intent deadline is before current MediaClock time' })); }
  detectConflicts() { return [...this.conflicts]; }
  planExecutionFrame(frameTimestamp: number): MediaFramePlan { const graph = this.resolveIntentGraph(); const frame = Math.max(frameTimestamp, this.clock.getFrameTimestamp(this.clock.getCurrentFrame())); const eligible: MediaIntent[] = this.topologicalSortIntents(graph).filter((i: MediaIntent)=>(i.timingConstraint.earliestFrameTimestamp ?? 0) <= frame && (i.timingConstraint.requestedFrameTimestamp ?? frame) <= frame); const batches = { videoOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='video'), audioOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='audio'), renderOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='render'), outputOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='output'), syncOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='sync') }; const plan: MediaFramePlan = { id:`frame-plan-${frame}-${graph.revision}`, frameTimestamp: frame, orderedExecutionSteps: eligible, subsystemBatches: batches, conflicts: this.conflicts }; this.activeFramePlans.set(frame, plan); this.intentQueue = this.intentQueue.filter((i)=>!eligible.some((e: MediaIntent)=>e.id===i.id)); this.emit('ORCHESTRATION_PLAN_CREATED', { stepCount: eligible.length }, frame); return plan; }
  async executeFramePlan(plan?: MediaFramePlan, graph?: ProductionGraph) { const active = plan ?? [...this.activeFramePlans.values()].at(-1); if (!active) return []; const responses: MediaExecutionAdapterResponse[] = []; for (const intent of active.orderedExecutionSteps) { const c = this.coordinators.find((coordinator)=>coordinator.canExecute(intent)); const validation = c?.validate(intent) ?? ['No coordinator available']; if (!c || validation.length) { this.conflicts.push({ id:`conflict-${++seq}`, intentIds:[intent.id], type:'validation', message: validation.join('; ') }); continue; } responses.push(await c.execute({ ...intent, timingConstraint: { ...intent.timingConstraint, requestedFrameTimestamp: active.frameTimestamp } }, graph)); this.subsystemStateSnapshot[intent.targetSubsystem] = 'executed'; } this.lastExecutionState = { frameTimestamp: active.frameTimestamp, responseCount: responses.length }; this.emit('ORCHESTRATION_PLAN_EXECUTED', { responseCount: responses.length }, active.frameTimestamp); this.emit('ORCHESTRATION_FRAME_COMPLETE', { queuedIntentCount: this.intentQueue.length }, active.frameTimestamp); return responses; }
  reconcileSubsystemState() { return { ...this.subsystemStateSnapshot }; }
  rollbackFramePlan(frameTimestamp?: number) { const key = frameTimestamp ?? [...this.activeFramePlans.keys()].at(-1); if (key !== undefined) this.activeFramePlans.delete(key); return true; }
  getDiagnostics() { return { activeIntents: [...this.intentQueue], activeFramePlans: [...this.activeFramePlans.values()], dependencyGraph: this.dependencyGraphCache, conflicts: [...this.conflicts], events: this.events.slice(-50), lastExecutionState: this.lastExecutionState, subsystemStateSnapshot: this.reconcileSubsystemState(), frameAlignmentStatus: this.clock.getState().status === 'running' ? 'aligned' : 'queued', droppedOrQueuedIntents: this.intentQueue.length }; }
  private topologicalSortAcyclic(graph: MediaIntentGraph) { const indegree = new Map(graph.intents.map((i)=>[i.id,0])); graph.edges.forEach((e)=>indegree.set(e.to,(indegree.get(e.to)??0)+1)); const ready = graph.intents.filter((i)=>indegree.get(i.id)===0); const out: MediaIntent[] = []; while (ready.length) { const next = ready.shift()!; out.push(next); graph.edges.filter((e)=>e.from===next.id).forEach((e)=>{ indegree.set(e.to,(indegree.get(e.to)??0)-1); const found = graph.intents.find((i)=>i.id===e.to); if (indegree.get(e.to)===0 && found) ready.push(found); }); } return out; }
  private emit(type: OrchestrationEventType, payload: Record<string, unknown>, frameTimestamp?: number, intentId?: string) { const event = { id:`orch-event-${++seq}`, type, timestamp:new Date().toISOString(), ...(frameTimestamp !== undefined ? { frameTimestamp } : {}), ...(intentId ? { intentId } : {}), payload }; this.events = [...this.events, event]; return event; }
}
function compareIntents(a: MediaIntent,b: MediaIntent) { return b.priority - a.priority || a.sourceGraphRevision - b.sourceGraphRevision || a.targetSubsystem.localeCompare(b.targetSubsystem) || a.id.localeCompare(b.id); }
