import type { MediaClock } from './sync/clock.js';

export type MediaIntentKind = 'video' | 'audio' | 'render' | 'output' | 'sync';
export type TargetSubsystem = 'video' | 'audio' | 'render' | 'output' | 'sync';
export type OrchestrationEventType = 'ORCHESTRATION_INTENT_RECEIVED'|'ORCHESTRATION_PLAN_CREATED'|'ORCHESTRATION_CONFLICT_DETECTED'|'ORCHESTRATION_DEPENDENCY_RESOLVED';
export interface MediaTimingConstraint { readonly earliestFrameTimestamp?: number; readonly deadlineFrameTimestamp?: number; readonly requestedFrameTimestamp?: number; }
export interface MediaIntent<TPayload = Record<string, unknown>> { readonly id: string; readonly type: MediaIntentKind; readonly executionType: string; readonly sourceGraphRevision: number; readonly dependencies: readonly string[]; readonly priority: number; readonly targetSubsystem: TargetSubsystem; readonly payload: Readonly<TPayload>; readonly timingConstraint: MediaTimingConstraint; readonly submittedAt: string; }
export interface MediaIntentGraph { readonly revision: number; readonly intents: readonly MediaIntent[]; readonly edges: readonly { from: string; to: string }[]; }
export interface MediaClockTick { readonly frameTimestamp: number; readonly currentFrame?: number; readonly elapsedTime?: number; }
export type MediaSubsystemStateSnapshot = Readonly<Record<TargetSubsystem, string>>;
export interface MediaExecutionPort { submitVideoOps(plan: MediaFramePlan): Promise<unknown>|unknown; submitAudioOps(plan: MediaFramePlan): Promise<unknown>|unknown; submitRenderOps(plan: MediaFramePlan): Promise<unknown>|unknown; submitOutputOps(plan: MediaFramePlan): Promise<unknown>|unknown; getSubsystemState(): MediaSubsystemStateSnapshot; }
export interface MediaFramePlan { readonly id: string; readonly frameTimestamp: number; readonly orderedExecutionSteps: readonly MediaIntent[]; readonly subsystemBatches: { readonly videoOps: readonly MediaIntent[]; readonly audioOps: readonly MediaIntent[]; readonly renderOps: readonly MediaIntent[]; readonly outputOps: readonly MediaIntent[]; readonly syncOps: readonly MediaIntent[]; }; readonly conflicts: readonly OrchestrationConflict[]; }
export interface OrchestrationConflict { readonly id: string; readonly intentIds: readonly string[]; readonly type: 'circular_dependency'|'priority'|'timestamp'|'validation'; readonly message: string; }
export interface OrchestrationEvent { readonly id: string; readonly type: OrchestrationEventType; readonly timestamp: string; readonly frameTimestamp?: number; readonly intentId?: string; readonly payload: Readonly<Record<string, unknown>>; }

let seq = 0;
export class MediaOrchestrationEngine {
  private intentQueue: MediaIntent[] = []; private activeFramePlans = new Map<number, MediaFramePlan>(); private dependencyGraphCache?: MediaIntentGraph; private subsystemStateSnapshot: MediaSubsystemStateSnapshot = { video:'idle', audio:'idle', render:'idle', output:'idle', sync:'idle' }; private events: OrchestrationEvent[] = []; private conflicts: OrchestrationConflict[] = [];
  constructor(private clock: MediaClock) {}
  submitIntent(intent: MediaIntent) { this.intentQueue = [...this.intentQueue, intent].sort(compareIntents); this.emit('ORCHESTRATION_INTENT_RECEIVED', { intentType: intent.executionType }, undefined, intent.id); return intent; }
  buildDependencyGraph(intents = this.intentQueue): MediaIntentGraph { return { revision: Math.max(0, ...intents.map((i)=>i.sourceGraphRevision)), intents: [...intents].sort(compareIntents), edges: intents.flatMap((i)=>i.dependencies.map((from)=>({ from, to: i.id }))).sort((a,b)=>`${a.from}:${a.to}`.localeCompare(`${b.from}:${b.to}`)) }; }
  resolveIntentGraph() { const graph = this.buildDependencyGraph(); this.dependencyGraphCache = graph; this.conflicts = [...this.detectCircularDependencies(graph), ...this.resolvePriorityConflicts(graph), ...this.resolveTimestampConflicts(graph)]; this.conflicts.forEach((c)=>this.emit('ORCHESTRATION_CONFLICT_DETECTED', { conflict: c })); this.emit('ORCHESTRATION_DEPENDENCY_RESOLVED', { edgeCount: graph.edges.length, intentCount: graph.intents.length }); return graph; }
  topologicalSortIntents(graph = this.resolveIntentGraph()) { const indegree = new Map(graph.intents.map((i)=>[i.id,0])); graph.edges.forEach((e)=>indegree.set(e.to,(indegree.get(e.to)??0)+1)); const byId = new Map(graph.intents.map((i)=>[i.id,i])); const ready = graph.intents.filter((i)=>indegree.get(i.id)===0).sort(compareIntents); const out: MediaIntent[] = []; while (ready.length) { const next = ready.shift()!; out.push(next); graph.edges.filter((e)=>e.from===next.id).sort((a,b)=>a.to.localeCompare(b.to)).forEach((e)=>{ indegree.set(e.to,(indegree.get(e.to)??0)-1); if (indegree.get(e.to)===0 && byId.get(e.to)) ready.push(byId.get(e.to)!); ready.sort(compareIntents); }); } return out.length === graph.intents.length ? out : [...graph.intents].sort(compareIntents); }
  detectCircularDependencies(graph = this.buildDependencyGraph()) { const sorted = this.topologicalSortAcyclic(graph); return sorted.length === graph.intents.length ? [] : [{ id:`conflict-circular-${graph.intents.map((i)=>i.id).join('-')}`, intentIds: graph.intents.map((i)=>i.id), type:'circular_dependency' as const, message:'Circular dependency detected in media intent graph' }]; }
  resolvePriorityConflicts(graph = this.buildDependencyGraph()) { return graph.intents.flatMap((a, idx)=>graph.intents.slice(idx+1).filter((b)=>a.priority===b.priority && a.targetSubsystem===b.targetSubsystem && a.id!==b.id).map((b)=>({ id:`conflict-priority-${a.id}-${b.id}`, intentIds:[a.id,b.id], type:'priority' as const, message:'Equal priority resolved deterministically by id' }))).slice(0,10); }
  resolveTimestampConflicts(graph = this.buildDependencyGraph(), elapsedTime = this.clock.getState().elapsedTime) { return graph.intents.filter((i)=>i.timingConstraint.deadlineFrameTimestamp !== undefined && i.timingConstraint.deadlineFrameTimestamp < elapsedTime).map((i)=>({ id:`conflict-timestamp-${i.id}`, intentIds:[i.id], type:'timestamp' as const, message:'Intent deadline is before current MediaClock time' })); }
  detectConflicts() { return [...this.conflicts]; }
  planFrame(graph: MediaIntentGraph, tick: MediaClockTick, subsystemState: MediaSubsystemStateSnapshot = this.subsystemStateSnapshot): MediaFramePlan { const frame = tick.frameTimestamp; const conflicts = [...this.detectCircularDependencies(graph), ...this.resolvePriorityConflicts(graph), ...this.resolveTimestampConflicts(graph, tick.elapsedTime ?? this.clock.getState().elapsedTime)]; const eligible: MediaIntent[] = this.topologicalSortIntents(graph).filter((i: MediaIntent)=>(i.timingConstraint.earliestFrameTimestamp ?? 0) <= frame && (i.timingConstraint.requestedFrameTimestamp ?? frame) <= frame); const batches = { videoOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='video'), audioOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='audio'), renderOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='render'), outputOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='output'), syncOps: eligible.filter((i: MediaIntent)=>i.targetSubsystem==='sync') }; return { id:`frame-plan-${frame}-${graph.revision}`, frameTimestamp: frame, orderedExecutionSteps: eligible, subsystemBatches: batches, conflicts: conflicts.map((conflict)=>({ ...conflict, message: `${conflict.message}${subsystemState ? '' : ''}` })) }; }
  planExecutionFrame(frameTimestamp: number, subsystemState: MediaSubsystemStateSnapshot = this.subsystemStateSnapshot): MediaFramePlan { const graph = this.resolveIntentGraph(); const frame = Math.max(frameTimestamp, this.clock.getFrameTimestamp(this.clock.getCurrentFrame())); const plan = this.planFrame(graph, { frameTimestamp: frame, elapsedTime: this.clock.getState().elapsedTime, currentFrame: this.clock.getCurrentFrame() }, subsystemState); this.conflicts = [...plan.conflicts]; this.activeFramePlans.set(frame, plan); this.intentQueue = this.intentQueue.filter((i)=>!plan.orderedExecutionSteps.some((e: MediaIntent)=>e.id===i.id)); this.emit('ORCHESTRATION_PLAN_CREATED', { stepCount: plan.orderedExecutionSteps.length }, frame); return plan; }
  reconcileSubsystemState() { return { ...this.subsystemStateSnapshot }; }
  rollbackFramePlan(frameTimestamp?: number) { const key = frameTimestamp ?? [...this.activeFramePlans.keys()].at(-1); if (key !== undefined) this.activeFramePlans.delete(key); return true; }
  getDiagnostics() { return { activeIntents: [...this.intentQueue], activeFramePlans: [...this.activeFramePlans.values()], dependencyGraph: this.dependencyGraphCache, conflicts: [...this.conflicts], events: this.events.slice(-50), subsystemStateSnapshot: this.reconcileSubsystemState(), frameAlignmentStatus: this.clock.getState().status === 'running' ? 'aligned' : 'queued', droppedOrQueuedIntents: this.intentQueue.length }; }
  private topologicalSortAcyclic(graph: MediaIntentGraph) { const indegree = new Map(graph.intents.map((i)=>[i.id,0])); graph.edges.forEach((e)=>indegree.set(e.to,(indegree.get(e.to)??0)+1)); const ready = graph.intents.filter((i)=>indegree.get(i.id)===0); const out: MediaIntent[] = []; while (ready.length) { const next = ready.shift()!; out.push(next); graph.edges.filter((e)=>e.from===next.id).forEach((e)=>{ indegree.set(e.to,(indegree.get(e.to)??0)-1); const found = graph.intents.find((i)=>i.id===e.to); if (indegree.get(e.to)===0 && found) ready.push(found); }); } return out; }
  private emit(type: OrchestrationEventType, payload: Record<string, unknown>, frameTimestamp?: number, intentId?: string) { const event = { id:`orch-event-${++seq}`, type, timestamp:new Date().toISOString(), ...(frameTimestamp !== undefined ? { frameTimestamp } : {}), ...(intentId ? { intentId } : {}), payload }; this.events = [...this.events, event]; return event; }
}
function compareIntents(a: MediaIntent,b: MediaIntent) { return b.priority - a.priority || a.sourceGraphRevision - b.sourceGraphRevision || a.targetSubsystem.localeCompare(b.targetSubsystem) || a.id.localeCompare(b.id); }
