import type { DestinationNode, ProductionGraph } from '../../shared/src/production-graph.js';
import type { RuntimeEventBus, RuntimeHealthStatus, RuntimeLifecycleState, RuntimeSubsystem, RuntimeSubsystemRegistration, RuntimeSubsystemSnapshot } from './broadcast-runtime-core.js';

const now = () => new Date().toISOString();
export type OutputType = 'Program'|'Preview'|'Aux'|'Clean Feed'|'Multiview'|'Streaming'|'Recording'|'NDI'|'SRT'|'RTMP'|'RTSP'|'WebRTC'|'SDI'|'HDMI'|'Virtual Output'|'Monitoring'|'Unknown';
export type OutputState = 'Created'|'Initializing'|'Ready'|'Running'|'Paused'|'Recovering'|'Stopping'|'Stopped'|'Failed'|'Disposed';
export type OutputRouteSource = 'Program'|'Preview'|'Aux'|'Multiview'|'Clean Feed';
export type OutputRecoveryStrategy = 'restart'|'retry'|'fallback'|'manual'|'backoff';
export interface OutputRouteMetadata { readonly source: OutputRouteSource; readonly productionGraphSourceId?: string; readonly auxId?: string; readonly deterministicRouteKey: string; readonly changedAt: string; readonly containsMediaHandles: false; }
export interface OutputHealth { readonly latencyMs: number; readonly bitrateKbps: number; readonly frameRate: number; readonly resolution: string; readonly packetLoss: number; readonly encoderStatus: 'idle'|'initializing'|'ready'|'encoding'|'paused'|'failed'|'not_applicable'; readonly connectionStatus: 'disconnected'|'connecting'|'connected'|'reconnecting'|'failed'|'not_applicable'; readonly uptimeMs: number; readonly retryCount: number; readonly status: RuntimeHealthStatus; }
export interface OutputMetrics { readonly uptimeMs: number; readonly framesSent: number; readonly bytesSent: number; readonly bandwidthKbps: number; readonly latencyMs: number; readonly errors: number; readonly restarts: number; readonly recoveries: number; }
export interface OutputRegistration { readonly outputId: string; readonly outputType: OutputType; readonly destination: string; readonly encoder: string; readonly transport: string; readonly healthProvider: string; readonly runtimeOwner: string; readonly priority: number; readonly productionGraphSource: OutputRouteSource; readonly productionGraphNodeId?: string; readonly recoveryStrategy?: OutputRecoveryStrategy; readonly metadata?: Readonly<Record<string, string|number|boolean>>; }
export interface OutputNode { readonly registration: OutputRegistration; readonly state: OutputState; readonly route: OutputRouteMetadata; readonly health: OutputHealth; readonly metrics: OutputMetrics; readonly createdAt: string; readonly updatedAt: string; readonly containsMediaHandles: false; readonly containsMediaPayloads: false; }
const emptyHealth = (status: RuntimeHealthStatus = 'Ready'): OutputHealth => Object.freeze({ latencyMs:0, bitrateKbps:0, frameRate:0, resolution:'unknown', packetLoss:0, encoderStatus:'idle', connectionStatus:'disconnected', uptimeMs:0, retryCount:0, status });
const emptyMetrics = (): OutputMetrics => Object.freeze({ uptimeMs:0, framesSent:0, bytesSent:0, bandwidthKbps:0, latencyMs:0, errors:0, restarts:0, recoveries:0 });
const routeKey = (source: OutputRouteSource, outputId: string, sourceId = source.toLowerCase()) => `${source}:${sourceId}->${outputId}`;
const transitions: Readonly<Record<OutputState, readonly OutputState[]>> = Object.freeze({ Created:['Initializing','Disposed'], Initializing:['Ready','Failed','Disposed'], Ready:['Running','Stopping','Disposed'], Running:['Paused','Recovering','Stopping','Failed'], Paused:['Running','Recovering','Stopping','Disposed'], Recovering:['Initializing','Running','Failed','Stopping'], Stopping:['Stopped','Failed'], Stopped:['Initializing','Disposed'], Failed:['Recovering','Initializing','Disposed'], Disposed:[] });
export function assertOutputTransition(from: OutputState, to: OutputState) { if (!transitions[from].includes(to)) throw new Error(`Invalid output transition from ${from} to ${to}`); return to; }
export class OutputStateStore { private outputs = new Map<string, OutputNode>(); list(){ return Object.freeze([...this.outputs.values()]); } get(id:string){ return this.outputs.get(id); } set(o:OutputNode){ this.outputs.set(o.registration.outputId, Object.freeze(o)); return this.get(o.registration.outputId)!; } delete(id:string){ return this.outputs.delete(id); } }
export class OutputRegistry { constructor(private store = new OutputStateStore()) {} register(output: OutputNode) { const r = output.registration; if (this.store.get(r.outputId)) throw new Error(`Duplicate output registration ${r.outputId}`); if (this.list().some((o)=>o.registration.destination===r.destination && o.registration.transport===r.transport)) throw new Error(`Duplicate output destination registration ${r.destination}`); return this.store.set(output); } list(){ return this.store.list(); } get(id:string){ return this.store.get(id); } update(output:OutputNode){ if(!this.store.get(output.registration.outputId)) throw new Error(`Unknown output ${output.registration.outputId}`); return this.store.set(output); } remove(id:string){ return this.store.delete(id); } }
export class OutputCapabilityResolver { create(registration: OutputRegistration): OutputNode { const sourceId = registration.productionGraphNodeId ?? registration.productionGraphSource.toLowerCase(); return Object.freeze({ registration, state:'Created', route:Object.freeze({ source:registration.productionGraphSource, productionGraphSourceId:sourceId, deterministicRouteKey:routeKey(registration.productionGraphSource, registration.outputId, sourceId), changedAt:now(), containsMediaHandles:false }), health:emptyHealth(), metrics:emptyMetrics(), createdAt:now(), updatedAt:now(), containsMediaHandles:false, containsMediaPayloads:false }); } resolveRoute(output:OutputNode, route: Partial<OutputRouteMetadata>) { const source = route.source ?? output.route.source; const sourceId = route.productionGraphSourceId ?? output.route.productionGraphSourceId ?? source.toLowerCase(); return Object.freeze({ ...output.route, ...route, source, productionGraphSourceId:sourceId, deterministicRouteKey:routeKey(source, output.registration.outputId, sourceId), changedAt:now(), containsMediaHandles:false }); } }
export class OutputLifecycleManager { transition(o:OutputNode,to:OutputState):OutputNode { assertOutputTransition(o.state,to); const metrics = { ...o.metrics, uptimeMs: to==='Running' ? o.metrics.uptimeMs+1 : o.metrics.uptimeMs }; return Object.freeze({ ...o, state:to, metrics:Object.freeze(metrics), updatedAt:now() }); } }
export class OutputHealthMonitor { update(o:OutputNode, health:Partial<OutputHealth>) { const next=Object.freeze({ ...o.health, ...health }); return Object.freeze({ ...o, health:next, metrics:Object.freeze({ ...o.metrics, latencyMs:next.latencyMs, bandwidthKbps:next.bitrateKbps, uptimeMs:next.uptimeMs }), updatedAt:now() }); } }
export class OutputMetricsCollector { collect(o:OutputNode){ return o.metrics; } update(o:OutputNode, metrics:Partial<OutputMetrics>){ return Object.freeze({ ...o, metrics:Object.freeze({ ...o.metrics, ...metrics }), updatedAt:now() }); } markFailure(o:OutputNode){ return this.update(o,{ errors:o.metrics.errors+1 }); } markRestart(o:OutputNode){ return this.update(o,{ restarts:o.metrics.restarts+1 }); } }
export class OutputRecoveryManager { calculateDelay(attempts:number,strategy:OutputRecoveryStrategy='backoff'){ if(strategy==='manual') return Number.POSITIVE_INFINITY; if(strategy==='restart'||strategy==='retry') return 0; if(strategy==='fallback') return 500; return Math.min(30000,1000*2**Math.max(0,attempts-1)); } recover(o:OutputNode){ return Object.freeze({ ...o, state:'Recovering' as const, health:Object.freeze({ ...o.health, retryCount:o.health.retryCount+1, status:'Initializing' as RuntimeHealthStatus }), metrics:Object.freeze({ ...o.metrics, recoveries:o.metrics.recoveries+1 }), updatedAt:now() }); } }
export class OutputEventAdapter { constructor(private bus:RuntimeEventBus, private source='output-runtime-controller') {} publish(type:string, output:OutputNode, extra:Record<string,unknown>={}){ return this.bus.publish({ type, domain:'controller', source:this.source, payload:{ outputId:output.registration.outputId, outputType:output.registration.outputType, destination:output.registration.destination, state:output.state, route:output.route, ...extra } }); } }
export class OutputRuntimeController implements RuntimeSubsystem { readonly id='output-runtime-controller'; readonly domain='controller' as const; readonly registration: RuntimeSubsystemRegistration = Object.freeze({ subsystemId:this.id, domain:this.domain, dependencies:['production-graph-runtime'], startupPriority:25, shutdownPriority:60, healthSource:'output-runtime:health' }); private state:RuntimeLifecycleState='uninitialized'; private revision=0; readonly registry=new OutputRegistry(); readonly lifecycle=new OutputLifecycleManager(); readonly healthMonitor=new OutputHealthMonitor(); readonly metricsCollector=new OutputMetricsCollector(); readonly recovery=new OutputRecoveryManager(); readonly capabilityResolver=new OutputCapabilityResolver(); readonly events:OutputEventAdapter; constructor(private bus:RuntimeEventBus){ this.events=new OutputEventAdapter(bus,this.id); }
  registerOutput(reg:OutputRegistration){ const o=this.registry.register(this.capabilityResolver.create(reg)); this.events.publish('OutputCreated',o); return o; }
  listOutputs(){ return this.registry.list(); } getOutput(id:string){ return this.registry.get(id); } getOutputStatus(id:string){ return this.registry.get(id)?.state; } getOutputHealth(id:string){ return this.registry.get(id)?.health; } getOutputMetrics(id:string){ return this.registry.get(id)?.metrics; } getRoutingMetadata(id:string){ return this.registry.get(id)?.route; } listOutputEvents(){ return this.bus.replay().filter((e)=>e.type.startsWith('Output')); }
  transitionOutput(id:string,to:OutputState){ const n=this.registry.update(this.lifecycle.transition(this.must(id),to)); const event=({Running:'OutputStarted',Paused:'OutputPaused',Stopped:'OutputStopped',Failed:'OutputFailed',Disposed:'OutputDisposed'} as Record<string,string>)[to]; if(event) this.events.publish(event,n); return n; }
  updateRoute(id:string, route:Partial<OutputRouteMetadata>){ const o=this.must(id); const n=this.registry.update(Object.freeze({ ...o, route:this.capabilityResolver.resolveRoute(o,route), updatedAt:now() })); this.events.publish('OutputRouteChanged',n,{ route:n.route }); return n; }
  updateHealth(id:string, health:Partial<OutputHealth>){ const n=this.registry.update(this.healthMonitor.update(this.must(id),health)); this.events.publish('OutputHealthChanged',n,{ health:n.health }); return n; }
  updateMetrics(id:string, metrics:Partial<OutputMetrics>){ const n=this.registry.update(this.metricsCollector.update(this.must(id),metrics)); return n; }
  restartMetadata(id:string){ const n=this.registry.update(this.metricsCollector.markRestart(this.recovery.recover(this.must(id)))); this.events.publish('OutputRecovered',n,{ delayMs:this.recovery.calculateDelay(n.health.retryCount,n.registration.recoveryStrategy), programRouteUnchanged:true }); return n; }
  initialize(){return this.snap('initialized');} configure(){return this.snap('configured');} prepare(){return this.snap('prepared');} standby(){return this.snap('standby');} ready(){return this.snap('ready');} start(){return this.snap('running');} pause(){return this.snap('paused');} resume(){return this.snap('running');} stop(){return this.snap('stopped');} recover(){return this.snap('recovering');} dispose(){return this.snap('disposed');}
  getSnapshot():RuntimeSubsystemSnapshot{ return Object.freeze({ id:this.id, domain:this.domain, state:this.state, health:this.listOutputs().some((o)=>o.health.status==='Error'||o.state==='Failed')?'Error':'Ready', revision:this.revision, updatedAt:now(), metadata:Object.freeze({ outputs:this.registry.list().length, metadataOnly:true, noEncoding:true, noMediaPipelines:true }) }); }
  private snap(state:RuntimeLifecycleState){ this.state=state; this.revision+=1; return this.getSnapshot(); } private must(id:string){ const o=this.registry.get(id); if(!o) throw new Error(`Unknown output ${id}`); return o; }
}
export function mapOutputToProductionGraphDestination(o:OutputNode):DestinationNode{ return { id:o.registration.productionGraphNodeId ?? `output:${o.registration.outputId}`, name:o.registration.outputId, platform:o.registration.outputType, enabled:o.state!=='Disposed', status:o.state==='Running'?'live':o.state==='Failed'?'error':o.state==='Stopped'||o.state==='Disposed'?'disabled':'ready', metadata:{ outputId:o.registration.outputId, outputType:o.registration.outputType, destination:o.registration.destination, encoder:o.registration.encoder, transport:o.registration.transport, health:o.health, route:o.route, state:o.state, metrics:o.metrics, runtimeOwner:o.registration.runtimeOwner, priority:o.registration.priority, containsMediaHandles:false, containsMediaPayloads:false } }; }
export function attachOutputMetadataToGraph(graph:ProductionGraph, output:OutputNode):ProductionGraph{ const node=mapOutputToProductionGraphDestination(output); return { ...graph, destinations:{ ...graph.destinations, [node.id]:node }, metadata:{ ...graph.metadata, updatedAt:now(), revision:graph.metadata.revision+1 } }; }
