const assert = { equal(actual: unknown, expected: unknown) { if (actual !== expected) throw new Error(`expected ${String(expected)} got ${String(actual)}`); }, ok(value: unknown) { if (!value) throw new Error('expected truthy'); }, throws(fn: () => unknown, predicate: (error: unknown) => boolean) { try { fn(); } catch (error) { if (predicate(error)) return; throw error; } throw new Error('expected throw'); } };
import { createReplayClipAssemblyEngine, createSyntheticReplayClipAssemblyBackend, REPLAY_CLIP_ASSEMBLY_OUTPUT_KEYS, type ReplayClipDefinition, type ReplayClipSegment, type ReplayClipAudioPolicy, type ReplayClipTransitionPolicy, type ReplayClipGraphicsPolicy, type ReplayPlaylistDefinition, type ReplayPlaylistEntry, type ReplayHighlightDefinition, type ReplayClipAssemblyRequest, type ReplayPlaylistAdvanceRequest } from './replay-playlist-highlight-clip-assembly-foundation.js';

const ns=1; const ref=(id:string,generation=1)=>({id,generation});
const audio:ReplayClipAudioPolicy={policyId:'audio:follow',policyGeneration:1,type:'FOLLOW_SEGMENT_AUDIO',metadataOnly:true,safeMetadata:{}};
const transition:ReplayClipTransitionPolicy={policyId:'tx:cut',policyGeneration:1,perSegmentOverrides:{},transitionDurationNs:100,overlapPolicy:'METADATA_OVERLAP',audioCrossfadeMetadataRequired:false,rendererRequired:false,metadataOnly:true,safeMetadata:{}};
const graphics:ReplayClipGraphicsPolicy={policyId:'gfx:none',policyGeneration:1,perSegmentGraphicReferences:{},lowerThirdMetadataReferences:[],rendererRequired:false,metadataOnly:true,safeMetadata:{}};
const playlist=(id='pl',type:ReplayPlaylistDefinition['playlistType']='MANUAL_ORDER'):ReplayPlaylistDefinition=>({playlistId:id,playlistVersion:'5.8.4',playlistGeneration:1,displayName:id,playlistType:type,orderedEntryIds:[],defaultOutputRole:'PROGRAM',defaultAudioPolicy:audio,advancementPolicy:'OPERATOR_ADVANCE',interruptionPolicy:'OPERATOR_REQUIRED',resumePolicy:'OPERATOR_REQUIRED',completionPolicy:'STOP',loopPolicyMetadata:{automaticLoop:false},maximumEntryCount:10,enabled:true,safeMetadata:{},createdAtNs:ns,updatedAtNs:ns});
const entry=(id:string,pos:number,pl='pl',required=true):ReplayPlaylistEntry=>({entryId:id,entryVersion:'5.8.4',entryGeneration:1,playlistRef:ref(pl),replayItemRef:ref(`item:${id}`),sourceRef:ref(`source:${id}`),rangeRef:ref(`range:${id}`),position:pos,priority:pos,enabled:true,required,skipPolicy:'ALLOW_SKIP_METADATA',audioPolicy:audio,cueMetadata:{},safeMetadata:{}});
const clip=(id='clip',aspect:ReplayClipDefinition['outputAspectRatioRole']='HORIZONTAL_16_9'):ReplayClipDefinition=>({clipId:id,clipVersion:'5.8.4',clipGeneration:1,displayName:id,assemblyType:'CLIP',orderedSegmentIds:[],sourceReplayItemIds:[],sourceBufferIds:[],sourceRangeIds:[],sourceMarkerIds:[],outputAspectRatioRole:aspect,outputRole:'PROGRAM',speedProfileReferences:[ref('speed:1x')],audioPolicy:audio,transitionPolicy:transition,graphicsPolicy:graphics,captionMetadataBoundary:{metadataOnly:true},thumbnailMetadataBoundary:{metadataOnly:true,noThumbnailGeneration:true},exportPolicyMetadataBoundary:{metadataOnly:true,noExport:true},publicationPolicyMetadataBoundary:{metadataOnly:true,noSocialPublishing:true},readinessPolicy:'ALLOW_OPTIONAL_DEGRADE',enabled:true,safeMetadata:{},createdAtNs:ns,updatedAtNs:ns});
const seg=(id:string,index:number,clipId='clip',required=true,enabled=true):ReplayClipSegment=>({segmentId:id,segmentVersion:'5.8.4',segmentGeneration:1,clipRef:ref(clipId),segmentIndex:index,sourceType:'PROGRAM',replaySourceRef:ref(`src:${id}`),replayBufferRef:ref(`buf:${id}`),replayItemRef:ref(`item:${id}`),replayRangeRef:ref(`range:${id}`),startPtsNs:0,endPtsNs:1000,startSequence:index*10,endSequence:index*10+9,sourceDurationNs:1000,speedProfileReference:ref('speed:1x'),direction:'FORWARD',videoStrategy:'EXACT_SOURCE_FRAME',audioPolicy:audio,required,enabled,rangeRetained:true,safeMetadata:{}});
const highlight=(id='hi'):ReplayHighlightDefinition=>({highlightId:id,highlightVersion:'5.8.4',highlightGeneration:1,displayName:id,highlightType:'SINGLE_EVENT',sourceEventReferences:[ref('event:explicit')],sourceMarkerIds:['marker:1'],sourceReplayItemIds:['item:s1'],sourceClipIds:['clip'],orderedSegmentIds:['s1'],categoryMetadata:{eventType:'SCORE_EVENT'},importanceScoreMetadata:1,operatorSelected:true,automaticSelectionMetadataBoundary:{metadataOnly:true,noAiDetection:true},outputRole:'PROGRAM',publicationEligibilityMetadata:{metadataOnly:true},enabled:true,safeMetadata:{},createdAtNs:ns,updatedAtNs:ns});
const request=(id='req'):ReplayClipAssemblyRequest=>({requestId:id,action:'ASSEMBLE',assemblyType:'CLIP',clipRef:ref('clip'),expectedReplayItemGenerations:[],expectedRangeGenerations:[],expectedSourceGenerations:[],expectedBufferGenerations:[],expectedMarkerGenerations:[],expectedSpeedProfileGenerations:[ref('speed:1x')],expectedTransitionReferenceGenerations:[],expectedGraphicsReferenceGenerations:[],expectedTimelineGeneration:1,requestedRuntimeFrame:1,deadlineNs:100,safeMetadata:{},correlationId:id});
function expectThrow(fn:()=>unknown, code:string){assert.throws(fn,(e:unknown)=>{ const err=e as {code?:string;name?:string}; return err.code===code||err.name===code; });}

const e=createReplayClipAssemblyEngine();
assert.equal(e.snapshot().version,'5.8.4');
expectThrow(()=>e.registerBackend(createSyntheticReplayClipAssemblyBackend()),'DuplicateReplayClipAssemblyBackend');
e.createPlaylist(playlist('pl','MANUAL_ORDER')); ['CHRONOLOGICAL','PRIORITY_ORDER','SOURCE_GROUPED','PROGRAM_SUMMARY'].forEach((t,i)=>e.createPlaylist(playlist(`pl${i}`,t as never)));
expectThrow(()=>e.createPlaylist(playlist('pl')),'DuplicateReplayPlaylist');
let p=e.updatePlaylist('pl',1,{displayName:'pl2'}); assert.equal(p.playlistGeneration,2); expectThrow(()=>e.updatePlaylist('pl',1,{}),'ReplayAssemblyGenerationMismatch');
e.addPlaylistEntry({...entry('e1',0,'pl'),playlistRef:ref('pl',2)}); e.addPlaylistEntry({...entry('e2',1,'pl',false),playlistRef:ref('pl',2)}); expectThrow(()=>e.addPlaylistEntry({...entry('e1',2,'pl'),playlistRef:ref('pl',2)}),'DuplicateReplayPlaylistEntry'); expectThrow(()=>e.addPlaylistEntry({...entry('e3',1,'pl'),playlistRef:ref('pl',2)}),'ReplayPlaylistEntryInvalid');
const ex=e.preparePlaylist('pl'); assert.equal(ex.preparedEntryCount,2);
const adv=(id:string,action:ReplayPlaylistAdvanceRequest['action'],target?:string):ReplayPlaylistAdvanceRequest=>({advanceRequestId:id,executionRef:ref(ex.executionId, e.snapshot().executions[0]?.executionGeneration??1),playlistRef:ref('pl',2),action,...(target?{targetEntryId:target}:{}),requestedRuntimeFrame:1,safeMetadata:{}});
assert.equal(e.advancePlaylist(adv('a1','CUE_FIRST')).status,'CUED'); expectThrow(()=>e.advancePlaylist(adv('a1','ADVANCE_NEXT')),'ReplayPlaylistDuplicateAdvance'); assert.equal(e.advancePlaylist({...adv('a2','ADVANCE_NEXT'),executionRef:ref(ex.executionId,2)}).status,'ADVANCED'); assert.equal(e.advancePlaylist({...adv('a3','INTERRUPT'),executionRef:ref(ex.executionId,3)}).status,'INTERRUPTED'); assert.equal(e.advancePlaylist({...adv('a4','RESUME_METADATA'),executionRef:ref(ex.executionId,4)}).status,'RESUMED_METADATA'); assert.equal(e.advancePlaylist({...adv('a5','COMPLETE'),executionRef:ref(ex.executionId,5)}).playlistComplete,true);
e.createHighlight(highlight()); expectThrow(()=>e.createHighlight(highlight()),'DuplicateReplayHighlight'); const h2=e.updateHighlight('hi',1,{displayName:'hi2'}); assert.equal(h2.highlightGeneration,2);
e.createClip(clip('clip','HORIZONTAL_16_9')); ['VERTICAL_9_16','SQUARE_1_1'].forEach((a,i)=>e.createClip(clip(`clip${i}`,a as never))); expectThrow(()=>e.createClip(clip('clip')),'DuplicateReplayClip'); let c=e.updateClip('clip',1,{displayName:'clip2'}); assert.equal(c.clipGeneration,2); expectThrow(()=>e.updateClip('clip',1,{}),'ReplayAssemblyGenerationMismatch');
e.addSegment({...seg('s1',0,'clip'),clipRef:ref('clip',2),sourceType:'PROGRAM'}); e.addSegment({...seg('s2',1,'clip',false,false),clipRef:ref('clip',2),sourceType:'CLEAN_FEED'}); ['AUX','CAMERA_ISO','GUEST','SCREEN_SHARE'].forEach((st,i)=>e.addSegment({...seg(`sx${i}`,i+2,'clip'),clipRef:ref('clip',2),sourceType:st as never})); expectThrow(()=>e.addSegment({...seg('s1',9,'clip'),clipRef:ref('clip',2)}),'DuplicateReplayClipSegment'); expectThrow(()=>e.addSegment({...seg('bad',9,'clip'),clipRef:ref('clip',2),startPtsNs:10,endPtsNs:1}),'ReplayClipSegmentInvalid');
const rev=e.createRevision('clip',2,'metadata edit',['s1']); expectThrow(()=>e.createRevision('clip',2,'conflict',[]),'ReplayClipRevisionConflict'); assert.equal(e.commitRevision(rev.revisionId).state,'COMMITTED'); const rev2=e.createRevision('clip',3,'cancel',[]); assert.equal(e.cancelRevision(rev2.revisionId).state,'CANCELLED');
e.submitAssemblyRequest({...request('req'),clipRef:ref('clip',3)}); expectThrow(()=>e.submitAssemblyRequest({...request('req'),clipRef:ref('clip',3)}),'ReplayAssemblyDuplicateRequest'); e.processTick({frameNumber:1,presentationTimeNs:1n} as never); const snap=e.snapshot(); assert.equal(snap.results[0]?.realRender,false); assert.equal(snap.results[0]?.metadataOnly,true); assert.equal(snap.plans[0]?.sourceDurationNs,5000); assert.equal(snap.plans[0]?.effectivePlaybackDurationNs,4500); assert.equal(snap.results[0]?.status,'DEGRADED');
const pkg=e.prepareHighlightPackage('hi'); assert.equal(pkg.metadataOnly,true); assert.equal(pkg.safeMetadata.noExport,true);
assert.equal(e.assertInvariants().valid,true); const sg=(await import('./replay-playlist-highlight-clip-assembly-foundation.js')).createReplayClipAssemblySourceGraphSnapshot(e); assert.equal(sg.realExport,false); assert.ok(REPLAY_CLIP_ASSEMBLY_OUTPUT_KEYS.engineHealth);
const s1=JSON.stringify(e.snapshot()); const e2=createReplayClipAssemblyEngine(); assert.equal(e2.snapshot().backendSelection[0], e.snapshot().backendSelection[0]); assert.equal(JSON.stringify(e.snapshot()),s1);
for(let i=0;i<10000;i++){const eng=createReplayClipAssemblyEngine(); eng.assertInvariants();}
for(let i=0;i<100000;i++){const eng=createReplayClipAssemblyEngine(); eng.processTick({frameNumber:i,presentationTimeNs:BigInt(i)} as never);}
e.shutdownEngine(); const shut=e.snapshot(); assert.equal(shut.health.healthState,'SHUTDOWN'); assert.equal(shut.health.activeAssemblyLeaseCount,0); assert.equal(e.shutdownEngine().health.healthState,'SHUTDOWN'); expectThrow(()=>e.submitAssemblyRequest({...request('after'),clipRef:ref('clip',3)}),'ReplayClipAssemblyShutdownError');
console.log('UBOS v5.8.4 replay playlist/highlight/clip assembly validation passed');
