/* eslint-disable @typescript-eslint/no-explicit-any */
const assert = Object.assign((condition: unknown, message?: string) => { if (!condition) throw new Error(message ?? 'assertion failed'); }, { equal(actual: unknown, expected: unknown, message?: string) { if (actual !== expected) throw new Error(message ?? `expected ${String(actual)} to equal ${String(expected)}`); }, throws(fn: () => unknown, pattern: RegExp) { let threw = false; try { fn(); } catch (error) { threw = true; if (!pattern.test(String(error))) throw error; } if (!threw) throw new Error('expected throw'); } });
import { createRtmpEndpointReference, createRtmpOutputEngine, createRtmpReference, createSyntheticRtmpOutputBackend, createDefaultRtmpChunkSizePolicy, createDefaultRtmpQueuePolicy, RTMP_OUTPUT_PROCESSOR_ORDER, type RtmpDestinationDefinition, type RtmpMediaInput, type RtmpOutputProfile, type RtmpOutputSessionDefinition } from './rtmp-rtmps-output-foundation.js';

const retry = { enabled:true, maximumAttempts:3, initialDelayTicks:1, maximumDelayTicks:8, backoffMode:'LINEAR' as const, jitterMode:'NONE' as const, retryableFailures:['synthetic'], resetAfterSuccess:true, safeMetadata:{} };
const app = createRtmpReference({ referenceId:'app-ref', providerMetadata:'validation', sensitiveValue:'live/application' });
const stream = createRtmpReference({ referenceId:'stream-ref', providerMetadata:'validation', sensitiveValue:'program' });
const key = createRtmpReference({ referenceId:'key-ref', providerMetadata:'validation', sensitiveValue:'secret-stream-key' });
const cert = createRtmpReference({ referenceId:'cert-ref', providerMetadata:'validation', sensitiveValue:'certificate-policy' });
function profile(id:string, protocol:'RTMP'|'RTMPS'|'RTMP_ENHANCED_METADATA'='RTMP'):RtmpOutputProfile{ return { profileId:id, profileVersion:'5.7.3', profileGeneration:1, displayName:id, protocolType:protocol, outputRole:'PROGRAM', sourceStreamingProfileId:'streaming-profile', sourceStreamingProfileGeneration:1, sourceEncoderSessionIds:['enc'], sourcePackageSessionIds:['pkg'], expectedVideoCodec:'H264_AVC', expectedAudioCodec:'AAC', videoRequired:true, audioRequired:true, applicationReference:app, streamNameReference:stream, streamKeyReference:key, deliveryMode:'LIVE', objectEncodingMetadata:'AMF0_METADATA_ONLY', chunkSizePolicy:createDefaultRtmpChunkSizePolicy(), acknowledgementPolicy:{window:5000000}, peerBandwidthPolicy:{mode:'SOFT'}, messageStreamPolicy:{id:1}, timestampPolicy:'RESET_ON_PUBLISH', sequenceHeaderPolicy:{required:true}, metadataMessagePolicy:{bounded:true}, connectionPolicy:'CONNECT_ON_START', publishPolicy:'PUBLISH_ON_READY', retryPolicy:retry, reconnectPolicy:'IMMEDIATE_BOUNDED', republishPolicy:'REPUBLISH_AFTER_RECONNECT', timeoutPolicy:['bounded'], queuePolicy:createDefaultRtmpQueuePolicy(), failoverPolicy:'PRIMARY_BACKUP', failurePolicy:'DEGRADE_OPTIONAL', backendPreference:'synthetic-rtmp-backend', criticality:'CRITICAL', safeMetadata:{}, createdAtNs:0, updatedAtNs:0 }; }
function dest(id:string, protocol:'RTMP'|'RTMPS'='RTMP'):RtmpDestinationDefinition{ return { destinationId:id, destinationVersion:'5.7.3', destinationGeneration:1, streamingDestinationId:`streaming-${id}`, streamingDestinationGeneration:1, protocolType:protocol, endpointReference:createRtmpEndpointReference({ endpointRefId:`ep-${id}`, rawEndpoint:`${protocol.toLowerCase()}://example.invalid/live`, protocolType:protocol, secure:protocol==='RTMPS' }), applicationReference:app, streamNameReference:stream, streamKeyReference:key, authenticationReferenceMetadata:createRtmpReference({ referenceId:`auth-${id}`, providerMetadata:'validation', sensitiveValue:'token' }), secure:protocol==='RTMPS', ...(protocol==='RTMPS'?{certificatePolicyMetadata:cert}:{}), regionMetadata:'redacted-region', primaryBackupRole:'PRIMARY', enabled:true, connectionEligibility:'ELIGIBLE', publishEligibility:'ELIGIBLE', failoverGroupId:'fg', safeMetadata:{}, createdAtNs:0, updatedAtNs:0 }; }
function session(id:string, p:RtmpOutputProfile, d:RtmpDestinationDefinition, role='PROGRAM'):RtmpOutputSessionDefinition{ return { rtmpSessionId:id, sessionVersion:'5.7.3', sessionGeneration:1, rtmpProfileId:p.profileId, rtmpProfileGeneration:p.profileGeneration, rtmpDestinationId:d.destinationId, rtmpDestinationGeneration:d.destinationGeneration, streamingSessionId:`streaming-${id}`, streamingSessionGeneration:1, distributionSessionId:`dist-${id}`, distributionSessionGeneration:1, outputRole:role as any, inputType:'ENCODED_PACKET', startupPolicy:['WAIT_FOR_ALL_REQUIRED_SEQUENCE_HEADERS','WAIT_FOR_VIDEO_KEYFRAME','WAIT_FOR_AV_CORRELATION','WAIT_FOR_STREAMING_FOUNDATION_READY'], connectPolicy:'explicit', publishPolicy:'explicit', pausePolicy:'bounded', stopPolicy:'bounded', reconnectPolicy:'bounded', republishPolicy:'REPUBLISH_AFTER_RECONNECT', queuePolicy:createDefaultRtmpQueuePolicy(), enabled:true, criticality:role==='PROGRAM'?'CRITICAL':'OPTIONAL', safeMetadata:{}, createdAtNs:0, updatedAtNs:0 }; }
function input(sessionId:string, seq:number, mediaType:'VIDEO'|'AUDIO', codecConfigPacket=false, keyframe=false):RtmpMediaInput{ return { inputId:`in-${sessionId}-${mediaType}-${seq}`, inputGeneration:1, submissionId:`sub-${sessionId}-${mediaType}-${seq}`, rtmpSessionId:sessionId, sessionGeneration:1, streamingInputId:`stream-in-${seq}`, streamingInputGeneration:1, outputRole:'PROGRAM', mediaType, codec:mediaType==='VIDEO'?'H264_AVC':'AAC', packetId:`pkt-${seq}`, packetGeneration:1, packetSequence:seq, pts:seq*3000, dts:seq*3000, duration:3000, timeBase:'1/90000', keyframe, codecConfigPacket, avCorrelationGeneration:1, discontinuityGeneration:0, estimatedBytes:mediaType==='VIDEO'?1200:256, ownership:'BORROWED_READ_ONLY', safeMetadata:{} }; }
function scenario(){ const e=createRtmpOutputEngine('validation'); e.registerBackend(createSyntheticRtmpOutputBackend()); const pr=profile('p-rtmp'); const ps=profile('p-rtmps','RTMPS'); e.registerProfile(pr); e.registerProfile(ps); const dr=dest('d-rtmp'); const ds=dest('d-rtmps','RTMPS'); e.registerDestination(dr); e.registerDestination(ds); e.createSession(session('s-rtmp',pr,dr)); e.createSession(session('s-rtmps',ps,ds,'AUXILIARY')); e.processTick(); e.createRequestAndSend(input('s-rtmp',0,'VIDEO',true,true)); e.createRequestAndSend(input('s-rtmp',1,'AUDIO',true,false)); e.createRequestAndSend(input('s-rtmp',2,'VIDEO',false,true)); for(let i=3;i<10003;i++) e.createRequestAndSend(input('s-rtmp',i,i%3===0?'AUDIO':'VIDEO',false,i%30===0),i); for(let i=0;i<100000;i++) e.processTick({ frameNumber:i } as any); return e; }
const e=scenario(); const snap=e.snapshot();
assert.equal(snap.version,'5.7.3'); assert.equal(snap.backends.length,1); assert.equal(snap.profiles.length,2); assert.equal(snap.destinations.length,2); assert.equal(snap.sessions.length,2); assert.equal(snap.handshakes.every(h=>h.completed),true); assert.equal(snap.tlsStates.find(t=>t.rtmpSessionId==='s-rtmps')?.handshakeState,'ESTABLISHED_METADATA'); assert.equal(snap.commands.filter(c=>c.commandType==='CONNECT').length,2); assert.equal(snap.results.every(r=>!r.realRtmpTransmission&&!r.realTls),true); assert.equal(snap.messages.length,10003); assert.equal(snap.validation.valid,true); assert.equal(snap.health.sentMessageCount,10003); assert.equal(snap.telemetry.sequenceRegressions,0); assert.equal(JSON.stringify(snap).includes('secret-stream-key'),false); assert.equal(JSON.stringify(snap).includes('rtmp://example'),false);
assert.throws(()=>e.registerBackend(createSyntheticRtmpOutputBackend()),/DuplicateRtmpBackend/); assert.throws(()=>e.submitInput(input('s-rtmp',2,'VIDEO',false,true)),/RtmpDuplicateSubmission|RtmpSequenceRegression/); assert.throws(()=>createRtmpOutputEngine().registerDestination({...dest('bad','RTMPS'),secure:false,endpointReference:createRtmpEndpointReference({endpointRefId:'bad',protocolType:'RTMPS',secure:false})}),/RtmpsTlsConfigurationInvalid/);
const replayA=JSON.stringify(scenario().snapshot()); const replayB=JSON.stringify(scenario().snapshot()); assert.equal(replayA,replayB,'determinism replay'); assert.equal(RTMP_OUTPUT_PROCESSOR_ORDER,1060);
e.shutdownEngine(); const shut=e.snapshot(); assert.equal(shut.connections.length,0); assert.equal(shut.handshakes.length,0); assert.equal(shut.plans.length,0); assert.equal(shut.validation.valid,true);
console.log('UBOS v5.7.3 RTMP/RTMPS output foundation validation passed');
