import { RundownTimelineExecutionEngine } from './rundown-timeline-execution.js';
const assertEqual=(actual:unknown,expected:unknown)=>{ if(actual!==expected) throw new Error(`Expected ${String(expected)} but received ${String(actual)}`); };
const assertThrows=(fn:()=>unknown,pattern:RegExp)=>{ try{ fn(); } catch(error){ if(pattern.test(String(error))) return; throw error; } throw new Error('Expected function to throw'); };
const tick=(frameNumber:bigint)=>({frameNumber,startedAtNs:0n,deadlineAtNs:0n,scheduledTimeNs:0n,actualTimeNs:0n,presentationTimeNs:0n,frameDurationNs:0n,driftNs:0n,latenessNs:0n,late:false,missedFrames:0n,discontinuity:false});
const engine=new RundownTimelineExecutionEngine();
engine.registerTimeline({timelineId:'show-a',generation:1,title:'Show A',metadata:{safe:'ok',secretToken:'nope'},cues:[{cueId:'open',generation:1,kind:'SCENE',startFrame:10,durationFrames:30,priority:10,metadata:{path:'/tmp/nope'},dependencies:[]},{cueId:'lower-third',generation:1,kind:'GRAPHICS',startFrame:12,durationFrames:60,priority:20,metadata:{label:'guest'},dependencies:[{dependencyId:'open-complete',cueIds:['open'],mode:'ALL_COMPLETED',required:true}]},{cueId:'music-bed',generation:1,kind:'AUDIO',startFrame:12,durationFrames:90,priority:5,metadata:{},dependencies:[{dependencyId:'no-failed-open',cueIds:['open'],mode:'NONE_FAILED',required:true}]}]});
assertEqual(engine.snapshot().timelines[0]?.metadata.secretToken,undefined);
assertEqual(engine.processFrame(tick(10n)).cues.find(c=>c.cueId==='open')?.state,'EXECUTING');
assertEqual(engine.processFrame(tick(12n)).cues.find(c=>c.cueId==='lower-third')?.state,'BLOCKED');
assertEqual(engine.processFrame(tick(12n)).cues.find(c=>c.cueId==='music-bed')?.state,'EXECUTING');
assertEqual(engine.snapshot().cues.find(c=>c.cueId==='open')?.exactOnceExecutionCount,1);
engine.completeCue('open',15);
engine.setCueReady('lower-third',16);
assertEqual(engine.executeReady(16).cues.find(c=>c.cueId==='lower-third')?.state,'EXECUTING');
assertEqual(engine.snapshot().telemetry.metadataOnly,true);
assertEqual(engine.snapshot().telemetry.realDeviceControl,false);
assertThrows(()=>engine.registerTimeline({timelineId:'show-a',generation:1,title:'stale',metadata:{},cues:[]}),/stale/);
for(let i=0;i<10000;i++) engine.processFrame(tick(BigInt(20+i)));
assertEqual(engine.snapshot().health.executingCount,2);
console.log('UBOS v5.10.3 rundown timeline execution validation passed');
