import type { ProductionGraph } from '../../shared/src/production-graph.js';
import type { RuntimeEventBus, RuntimeHealthStatus, RuntimeLifecycleState, RuntimeSubsystem, RuntimeSubsystemRegistration, RuntimeSubsystemSnapshot } from './broadcast-runtime-core.js';

const now = () => new Date().toISOString();
export type SessionState = 'Created'|'Loading'|'Ready'|'Running'|'Paused'|'Recovering'|'Stopping'|'Stopped'|'Archived'|'Disposed';
export type ProductionType = 'Live'|'Recorded'|'Hybrid'|'Rehearsal'|'Remote'|'Unknown';
export interface SessionHealth { readonly runtimeHealth: RuntimeHealthStatus; readonly deviceCount: number; readonly activeInputs: number; readonly activeOutputs: number; readonly uptimeMs: number; readonly operator: string; readonly warnings: readonly string[]; readonly errors: readonly string[]; }
export interface SessionMetadata { readonly sessionId: string; readonly name: string; readonly operator: string; readonly productionType: ProductionType; readonly workspacePreset: string; readonly activeRundown: string; readonly deviceSet: readonly string[]; readonly inputSet: readonly string[]; readonly outputSet: readonly string[]; readonly recordingTargets: readonly string[]; readonly streamingTargets: readonly string[]; readonly creationTime: string; readonly runtimeState: SessionState; readonly health: SessionHealth; readonly version: '4.6'; readonly containsMediaHandles: false; readonly containsMediaPayloads: false; }
export interface SessionCreateInput { readonly sessionId: string; readonly name: string; readonly operator: string; readonly productionType?: ProductionType; readonly workspacePreset?: string; readonly activeRundown?: string; readonly deviceSet?: readonly string[]; readonly inputSet?: readonly string[]; readonly outputSet?: readonly string[]; readonly recordingTargets?: readonly string[]; readonly streamingTargets?: readonly string[]; }
export interface SessionSnapshot { readonly snapshotId: string; readonly sessionId: string; readonly createdAt: string; readonly workspace: Readonly<Record<string, unknown>>; readonly panelLayout: Readonly<Record<string, unknown>>; readonly productionGraphMetadata: Readonly<Record<string, unknown>>; readonly runtimeHealth: SessionHealth; readonly registeredDevices: readonly string[]; readonly registeredOutputs: readonly string[]; readonly registeredInputs: readonly string[]; readonly operatorPreferences: Readonly<Record<string, unknown>>; readonly containsMediaSerialization: false; readonly containsMediaHandles: false; }
const transitions: Readonly<Record<SessionState, readonly SessionState[]>> = Object.freeze({ Created:['Loading','Ready','Archived','Disposed'], Loading:['Ready','Stopped','Disposed'], Ready:['Running','Archived','Disposed'], Running:['Paused','Recovering','Stopping'], Paused:['Running','Recovering','Stopping'], Recovering:['Ready','Running','Stopped'], Stopping:['Stopped'], Stopped:['Loading','Archived','Disposed'], Archived:['Disposed'], Disposed:[] });
export function assertSessionTransition(from:SessionState,to:SessionState){ if(!transitions[from].includes(to)) throw new Error(`Invalid session transition from ${from} to ${to}`); return to; }
const health = (s: Pick<SessionMetadata,'operator'|'deviceSet'|'inputSet'|'outputSet'>, state:SessionState, startedAt?:number, warnings:readonly string[]=[], errors:readonly string[]=[]):SessionHealth => Object.freeze({ runtimeHealth: errors.length?'Error':warnings.length?'Warning':state==='Running'?'Running':state==='Loading'||state==='Recovering'?'Initializing':state==='Stopped'||state==='Archived'||state==='Disposed'?'Offline':'Ready', deviceCount:s.deviceSet.length, activeInputs:s.inputSet.length, activeOutputs:s.outputSet.length, uptimeMs: startedAt && ['Running','Paused','Recovering','Stopping'].includes(state) ? Date.now()-startedAt : 0, operator:s.operator, warnings:Object.freeze([...warnings]), errors:Object.freeze([...errors]) });
export class SessionRegistry { private sessions=new Map<string,SessionMetadata>(); register(s:SessionMetadata){ if(this.sessions.has(s.sessionId)) throw new Error(`Duplicate session ${s.sessionId}`); this.sessions.set(s.sessionId,Object.freeze(s)); return this.get(s.sessionId)!; } update(s:SessionMetadata){ if(!this.sessions.has(s.sessionId)) throw new Error(`Unknown session ${s.sessionId}`); this.sessions.set(s.sessionId,Object.freeze(s)); return this.get(s.sessionId)!; } get(id:string){ return this.sessions.get(id); } list(){ return Object.freeze([...this.sessions.values()]); } }
export class SessionLifecycleManager { transition(s:SessionMetadata,to:SessionState,startedAt?:number){ assertSessionTransition(s.runtimeState,to); return Object.freeze({ ...s, runtimeState:to, health:health(s,to,startedAt) }); } }
export class SessionHealthManager { summarize(s:SessionMetadata, warnings:readonly string[]=s.health.warnings, errors:readonly string[]=s.health.errors, startedAt?:number){ return health(s,s.runtimeState,startedAt,warnings,errors); } }
export class SessionSnapshotManager { private snapshots=new Map<string,SessionSnapshot>(); create(s:SessionMetadata,input:Partial<SessionSnapshot>={}){ const snap:SessionSnapshot=Object.freeze({ snapshotId:input.snapshotId??`snapshot:${s.sessionId}:${this.snapshots.size+1}`, sessionId:s.sessionId, createdAt:now(), workspace:input.workspace??Object.freeze({ preset:s.workspacePreset }), panelLayout:input.panelLayout??Object.freeze({}), productionGraphMetadata:input.productionGraphMetadata??Object.freeze({ activeSession:s.sessionId, currentRundown:s.activeRundown }), runtimeHealth:input.runtimeHealth??s.health, registeredDevices:input.registeredDevices??s.deviceSet, registeredOutputs:input.registeredOutputs??s.outputSet, registeredInputs:input.registeredInputs??s.inputSet, operatorPreferences:input.operatorPreferences??Object.freeze({ operator:s.operator }), containsMediaSerialization:false, containsMediaHandles:false }); this.snapshots.set(snap.snapshotId,snap); return snap; } get(id:string){ return this.snapshots.get(id); } list(){ return Object.freeze([...this.snapshots.values()]); } }
export class SessionRecoveryManager { recover(s:SessionMetadata,snap:SessionSnapshot){ if(s.sessionId!==snap.sessionId) throw new Error(`Snapshot ${snap.snapshotId} does not belong to ${s.sessionId}`); return Object.freeze({ ...s, workspacePreset:String(snap.workspace['preset']??s.workspacePreset), deviceSet:Object.freeze([...snap.registeredDevices]), inputSet:Object.freeze([...snap.registeredInputs]), outputSet:Object.freeze([...snap.registeredOutputs]), runtimeState:'Recovering' as const, health:health(s,'Recovering') }); } }
export class SessionMetricsCollector { collect(s:SessionMetadata){ return Object.freeze({ sessionId:s.sessionId, uptimeMs:s.health.uptimeMs, deviceCount:s.health.deviceCount, activeInputs:s.health.activeInputs, activeOutputs:s.health.activeOutputs, warnings:s.health.warnings.length, errors:s.health.errors.length }); } }
export class SessionEventAdapter { constructor(private bus:RuntimeEventBus, private source='session-runtime-controller'){} publish(type:string,s:SessionMetadata,extra:Record<string,unknown>={}){ return this.bus.publish({ type, domain:'session', source:this.source, payload:{ sessionId:s.sessionId, name:s.name, operator:s.operator, state:s.runtimeState, ...extra } }); } }
export class SessionRuntimeController implements RuntimeSubsystem { readonly id='session-runtime-controller'; readonly domain='session' as const; readonly registration:RuntimeSubsystemRegistration=Object.freeze({ subsystemId:this.id, domain:this.domain, dependencies:['production-graph-runtime'], startupPriority:28, shutdownPriority:58, healthSource:'session-runtime:health' }); private state:RuntimeLifecycleState='uninitialized'; private revision=0; private activeSessionId:string|undefined; private startedAt?:number; readonly registry=new SessionRegistry(); readonly lifecycle=new SessionLifecycleManager(); readonly healthManager=new SessionHealthManager(); readonly snapshots=new SessionSnapshotManager(); readonly recovery=new SessionRecoveryManager(); readonly metrics=new SessionMetricsCollector(); readonly events:SessionEventAdapter; constructor(private bus:RuntimeEventBus){ this.events=new SessionEventAdapter(bus,this.id); }
  createSession(input:SessionCreateInput){ const base={ sessionId:input.sessionId, name:input.name, operator:input.operator, productionType:input.productionType??'Unknown', workspacePreset:input.workspacePreset??'default', activeRundown:input.activeRundown??'none', deviceSet:Object.freeze([...(input.deviceSet??[])]), inputSet:Object.freeze([...(input.inputSet??[])]), outputSet:Object.freeze([...(input.outputSet??[])]), recordingTargets:Object.freeze([...(input.recordingTargets??[])]), streamingTargets:Object.freeze([...(input.streamingTargets??[])]), creationTime:now(), runtimeState:'Created' as const, version:'4.6' as const, containsMediaHandles:false as const, containsMediaPayloads:false as const }; const s=this.registry.register(Object.freeze({ ...base, health:health(base,'Created') })); this.events.publish('SessionCreated',s); return s; }
  loadSession(id:string){ const s=this.transition(id,'Loading'); const ready=this.registry.update(this.lifecycle.transition(s,'Ready')); this.activeSessionId=id; this.events.publish('SessionLoaded',ready); return ready; }
  startSession(id=this.mustCurrent()){ this.startedAt=Date.now(); const s=this.transition(id,'Running',this.startedAt); this.events.publish('SessionStarted',s); return s; } pauseSession(id=this.mustCurrent()){ const s=this.transition(id,'Paused',this.startedAt); this.events.publish('SessionPaused',s); return s; } closeSession(id=this.mustCurrent()){ const stopping=this.transition(id,'Stopping',this.startedAt); const stopped=this.registry.update(this.lifecycle.transition(stopping,'Stopped',this.startedAt)); this.events.publish('SessionStopped',stopped); return stopped; } archiveSession(id:string){ const s=this.transition(id,'Archived'); this.events.publish('SessionArchived',s); return s; } disposeSession(id:string){ const s=this.transition(id,'Disposed'); this.events.publish('SessionDisposed',s); if(this.activeSessionId===id) this.activeSessionId=undefined; return s; }
  saveSnapshot(id=this.mustCurrent(), input:Partial<SessionSnapshot>={}){ const snap=this.snapshots.create(this.must(id),input); this.events.publish('SnapshotCreated',this.must(id),{ snapshotId:snap.snapshotId }); return snap; } restoreSnapshot(snapshotId:string){ const snap=this.snapshots.get(snapshotId); if(!snap) throw new Error(`Unknown snapshot ${snapshotId}`); const s=this.registry.update(this.recovery.recover(this.must(snap.sessionId),snap)); this.activeSessionId=s.sessionId; this.events.publish('SnapshotRestored',s,{ snapshotId }); this.events.publish('SessionRecovered',s); return s; }
  listSessions(){ return this.registry.list(); } currentSession(){ return this.activeSessionId?this.registry.get(this.activeSessionId):undefined; }
  initialize(){return this.snap('initialized');} configure(){return this.snap('configured');} prepare(){return this.snap('prepared');} standby(){return this.snap('standby');} ready(){return this.snap('ready');} start(){return this.snap('running');} pause(){return this.snap('paused');} resume(){return this.snap('running');} stop(){return this.snap('stopped');} recover(){return this.snap('recovering');} dispose(){return this.snap('disposed');}
  getSnapshot():RuntimeSubsystemSnapshot{ const current=this.currentSession(); return Object.freeze({ id:this.id, domain:this.domain, state:this.state, health:current?.health.runtimeHealth??'Ready', revision:this.revision, updatedAt:now(), metadata:Object.freeze({ sessions:this.registry.list().length, activeSession:this.activeSessionId??'', metadataOnly:true, snapshots:this.snapshots.list().length }) }); }
  private transition(id:string,to:SessionState,startedAt?:number){ return this.registry.update(this.lifecycle.transition(this.must(id),to,startedAt)); } private must(id:string){ const s=this.registry.get(id); if(!s) throw new Error(`Unknown session ${id}`); return s; } private mustCurrent(){ if(!this.activeSessionId) throw new Error('No current session'); return this.activeSessionId; } private snap(state:RuntimeLifecycleState){ this.state=state; this.revision+=1; return this.getSnapshot(); }
}
export function attachSessionMetadataToGraph(graph:ProductionGraph, session:SessionMetadata):ProductionGraph{ return { ...graph, broadcastSessionId:session.sessionId, session:{ ...graph.session, id:session.sessionId, name:session.name, activeOperatorId:session.operator, metadata:{ ...graph.session.metadata, activeSession:session.sessionId, sessionHealth:session.health.runtimeHealth, currentRundown:session.activeRundown, operator:session.operator, workspace:session.workspacePreset, creationTime:session.creationTime, containsMediaHandles:false } }, workspace:{ ...graph.workspace, selectedPreset:session.workspacePreset, metadata:{ ...graph.workspace.metadata, activeSession:session.sessionId, operator:session.operator, currentRundown:session.activeRundown } }, health:{ ...graph.health, metrics:{ ...graph.health.metrics, sessionHealth:{ value:session.health.runtimeHealth, status:session.health.runtimeHealth==='Error'?'critical':session.health.runtimeHealth==='Warning'?'warning':'good', updatedAt:now() } } }, metadata:{ ...graph.metadata, updatedAt:now(), revision:graph.metadata.revision+1 } }; }
