import type { SceneCompositor } from './compositor/index.js';
import type { AudioMixer } from './media-runtime/audio-mixer.js';
import type { ProgramOutput } from './output-pipeline.js';
import { createClock, type MediaClock } from './sync/clock.js';
import { FrameScheduler, type FrameTickEvent } from './sync/index.js';
import type { StreamingPipelineV2 } from './streaming-runtime/index.js';

export type BroadcastTransportProtocol = 'webrtc' | 'rtmp' | 'rtmps' | 'srt' | 'rist' | 'ndi' | 'smpte_st_2110';
export type TransportSessionLifecycle = 'idle' | 'negotiating' | 'connecting' | 'connected' | 'reconnecting' | 'stopped' | 'failed';
export type TransportHealth = 'healthy' | 'degraded' | 'critical' | 'unknown';
export type TransportRuntimeEventType = 'transport_session_created' | 'transport_negotiating' | 'transport_connecting' | 'transport_connected' | 'transport_metrics_updated' | 'transport_reconnecting' | 'transport_stopped' | 'transport_failed';

export interface TransportProtocolModel { readonly id: BroadcastTransportProtocol; readonly label: string; readonly family: 'realtime' | 'contribution' | 'distribution' | 'ip_video'; readonly direction: 'send' | 'receive' | 'bidirectional'; readonly supportsEncryption: boolean; readonly supportsLowLatency: boolean; readonly requiresSignaling: boolean; readonly implemented: false; readonly constraints: readonly string[]; }
export interface TransportSessionMetadata { readonly bitrateKbps: number; readonly latencyMs: number; readonly jitterMs: number; readonly packetLossPercent: number; readonly reconnectCount: number; readonly health: TransportHealth; readonly framesObserved: number; readonly audioFramesObserved: number; readonly clockDriftMs: number; }
export interface TransportRuntimeBindings { readonly streamingPipelineId?: string; readonly streamingSessionId?: string; readonly remoteProductionManagerId?: string; readonly mediaClockId: string; readonly audioMixerId?: string; readonly sceneCompositorId?: string; readonly programOutputId?: string; readonly containsRuntimeHandles: false; }
export interface TransportSession { readonly id: string; readonly protocol: TransportProtocolModel; readonly lifecycle: TransportSessionLifecycle; readonly endpoint: string; readonly sanitizedEndpoint: string; readonly createdAt: string; readonly updatedAt: string; readonly startedAt?: string; readonly stoppedAt?: string; readonly metadata: TransportSessionMetadata; readonly bindings: TransportRuntimeBindings; readonly events: readonly TransportRuntimeEvent[]; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; readonly containsEncodedPackets: false; readonly transmitsNetworkPackets: false; }
export interface TransportRuntimeEvent { readonly id: string; readonly type: TransportRuntimeEventType; readonly timestamp: string; readonly sessionId: string; readonly protocol: BroadcastTransportProtocol; readonly lifecycle: TransportSessionLifecycle; readonly message: string; readonly metadata: Readonly<Record<string, unknown>>; readonly containsMediaPayloads: false; readonly containsEncodedPackets: false; }
export interface TransportManagerSnapshot { readonly id: string; readonly sessions: readonly TransportSession[]; readonly protocols: readonly TransportProtocolModel[]; readonly events: readonly TransportRuntimeEvent[]; readonly backend: TransportBackendDescriptor; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; readonly containsEncodedPackets: false; }
export interface TransportBackendDescriptor { readonly id: string; readonly name: string; readonly mode: 'metadata_only'; readonly backendIndependent: true; readonly transmitsNetworkPackets: false; readonly implementsIce: false; readonly implementsTurnStun: false; readonly implementsHardwareIo: false; readonly encodesPackets: false; }
export interface RemoteProductionBinding { readonly id?: string; getSnapshot?(): { readonly id?: string }; }
export interface CreateTransportSessionInput { readonly id?: string; readonly protocol: BroadcastTransportProtocol; readonly endpoint: string; readonly streamingPipeline?: StreamingPipelineV2; readonly streamingSessionId?: string; readonly remoteProductionManager?: RemoteProductionBinding; readonly mediaClock?: MediaClock; readonly frameScheduler?: FrameScheduler; readonly audioMixer?: AudioMixer; readonly sceneCompositor?: SceneCompositor; readonly programOutput?: ProgramOutput; readonly targetBitrateKbps?: number; readonly expectedLatencyMs?: number; readonly metadata?: Readonly<Record<string, unknown>>; }
export interface UpdateTransportMetricsInput { readonly bitrateKbps?: number; readonly latencyMs?: number; readonly jitterMs?: number; readonly packetLossPercent?: number; readonly health?: TransportHealth; readonly tick?: FrameTickEvent; readonly audioFrames?: number; readonly metadata?: Readonly<Record<string, unknown>>; }

const now = () => new Date().toISOString();
const idFor = (type: string) => `${type}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
const sanitizeEndpoint = (endpoint: string) => endpoint.replace(/([?&](?:key|token|secret|password)=)[^&]+/gi, '$1REDACTED').replace(/\/[^/@\s]+@/, '/REDACTED@').replace(/[\0\n\r`$;&|<>]/g, '');

export const transportProtocols: readonly TransportProtocolModel[] = Object.freeze([
  { id: 'webrtc', label: 'WebRTC', family: 'realtime', direction: 'bidirectional', supportsEncryption: true, supportsLowLatency: true, requiresSignaling: true, implemented: false, constraints: ['No ICE signaling', 'No TURN/STUN implementation'] },
  { id: 'rtmp', label: 'RTMP', family: 'distribution', direction: 'send', supportsEncryption: false, supportsLowLatency: false, requiresSignaling: false, implemented: false, constraints: ['No packet encoding'] },
  { id: 'rtmps', label: 'RTMPS', family: 'distribution', direction: 'send', supportsEncryption: true, supportsLowLatency: false, requiresSignaling: false, implemented: false, constraints: ['No packet encoding'] },
  { id: 'srt', label: 'SRT', family: 'contribution', direction: 'bidirectional', supportsEncryption: true, supportsLowLatency: true, requiresSignaling: false, implemented: false, constraints: ['No packet encoding'] },
  { id: 'rist', label: 'RIST', family: 'contribution', direction: 'bidirectional', supportsEncryption: true, supportsLowLatency: true, requiresSignaling: false, implemented: false, constraints: ['No packet encoding'] },
  { id: 'ndi', label: 'NDI', family: 'ip_video', direction: 'bidirectional', supportsEncryption: false, supportsLowLatency: true, requiresSignaling: false, implemented: false, constraints: ['No hardware I/O'] },
  { id: 'smpte_st_2110', label: 'SMPTE ST 2110', family: 'ip_video', direction: 'bidirectional', supportsEncryption: false, supportsLowLatency: true, requiresSignaling: false, implemented: false, constraints: ['No hardware I/O', 'No packet encoding'] },
]);

const backend: TransportBackendDescriptor = Object.freeze({ id: 'transport-backend:metadata-only', name: 'Backend-independent broadcast transport model', mode: 'metadata_only', backendIndependent: true, transmitsNetworkPackets: false, implementsIce: false, implementsTurnStun: false, implementsHardwareIo: false, encodesPackets: false });
const emptyMetadata = (bitrateKbps = 0, latencyMs = 0): TransportSessionMetadata => Object.freeze({ bitrateKbps, latencyMs, jitterMs: 0, packetLossPercent: 0, reconnectCount: 0, health: 'unknown', framesObserved: 0, audioFramesObserved: 0, clockDriftMs: 0 });

export class TransportManager { private sessions = new Map<string, TransportSession>(); private events: TransportRuntimeEvent[] = []; private listeners = new Set<(event: TransportRuntimeEvent) => void>(); constructor(readonly id = 'transport-manager:program', readonly backendDescriptor = backend) {}
  createSession(input: CreateTransportSessionInput) { const protocol = transportProtocols.find((p) => p.id === input.protocol); if (!protocol) throw new Error(`Unsupported transport protocol ${input.protocol}`); const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const sessionId = input.id ?? `transport-session:${input.protocol}:${Date.now()}`; const remoteId = input.remoteProductionManager?.id ?? input.remoteProductionManager?.getSnapshot?.().id; const session: TransportSession = Object.freeze({ id: sessionId, protocol, lifecycle: 'idle', endpoint: input.endpoint, sanitizedEndpoint: sanitizeEndpoint(input.endpoint), createdAt: now(), updatedAt: now(), metadata: emptyMetadata(input.targetBitrateKbps, input.expectedLatencyMs), bindings: Object.freeze({ ...(input.streamingPipeline ? { streamingPipelineId: input.streamingPipeline.id } : {}), ...(input.streamingSessionId ? { streamingSessionId: input.streamingSessionId } : {}), ...(remoteId ? { remoteProductionManagerId: remoteId } : {}), mediaClockId: clock.id, ...(input.audioMixer ? { audioMixerId: input.audioMixer.id } : {}), ...(input.sceneCompositor ? { sceneCompositorId: input.sceneCompositor.id } : {}), ...(input.programOutput ? { programOutputId: input.programOutput.id } : {}), containsRuntimeHandles: false }), events: [], containsRuntimeHandles: false, containsMediaPayloads: false, containsEncodedPackets: false, transmitsNetworkPackets: false }); this.sessions.set(sessionId, this.withEvent(session, 'transport_session_created', 'Transport session created', input.metadata)); return this.must(sessionId); }
  negotiate(id: string) { return this.patch(this.must(id), { lifecycle: 'negotiating' }, 'transport_negotiating', 'Transport negotiation modeled'); }
  connect(id: string) { return this.patch(this.must(id), { lifecycle: 'connecting' }, 'transport_connecting', 'Transport connection modeled'); }
  markConnected(id: string) { const s = this.must(id); return this.patch(s, { lifecycle: 'connected', startedAt: s.startedAt ?? now(), metadata: Object.freeze({ ...s.metadata, health: 'healthy' as const }) }, 'transport_connected', 'Transport connected in metadata mode'); }
  updateMetrics(id: string, metrics: UpdateTransportMetricsInput) { const s = this.must(id); const md = Object.freeze({ ...s.metadata, bitrateKbps: metrics.bitrateKbps ?? s.metadata.bitrateKbps, latencyMs: metrics.latencyMs ?? s.metadata.latencyMs, jitterMs: metrics.jitterMs ?? metrics.tick?.jitterEstimate ?? s.metadata.jitterMs, packetLossPercent: metrics.packetLossPercent ?? s.metadata.packetLossPercent, health: metrics.health ?? deriveHealth(metrics.packetLossPercent ?? s.metadata.packetLossPercent, metrics.jitterMs ?? s.metadata.jitterMs), framesObserved: s.metadata.framesObserved + (metrics.tick ? 1 : 0), audioFramesObserved: s.metadata.audioFramesObserved + (metrics.audioFrames ?? 0), clockDriftMs: metrics.tick?.diagnostics?.driftMs ?? s.metadata.clockDriftMs }); return this.patch(s, { metadata: md }, 'transport_metrics_updated', 'Transport metrics updated', metrics.metadata); }
  reconnect(id: string, reason = 'Transport reconnect requested') { const s = this.must(id); return this.patch(s, { lifecycle: 'reconnecting', metadata: Object.freeze({ ...s.metadata, reconnectCount: s.metadata.reconnectCount + 1, health: 'degraded' as const }) }, 'transport_reconnecting', reason); }
  stop(id: string) { return this.patch(this.must(id), { lifecycle: 'stopped', stoppedAt: now() }, 'transport_stopped', 'Transport stopped'); }
  fail(id: string, message: string) { return this.patch(this.must(id), { lifecycle: 'failed', metadata: Object.freeze({ ...this.must(id).metadata, health: 'critical' as const }) }, 'transport_failed', message); }
  getSession(id: string) { return this.sessions.get(id); } getEvents() { return Object.freeze([...this.events]); } getSnapshot(): TransportManagerSnapshot { return Object.freeze({ id: this.id, sessions: Object.freeze([...this.sessions.values()]), protocols: transportProtocols, events: Object.freeze([...this.events]), backend: this.backendDescriptor, containsRuntimeHandles: false, containsMediaPayloads: false, containsEncodedPackets: false }); } onRuntimeEvent(callback: (event: TransportRuntimeEvent) => void) { this.listeners.add(callback); return () => this.listeners.delete(callback); }
  private patch(s: TransportSession, patch: Partial<TransportSession>, type: TransportRuntimeEventType, message: string, metadata: Readonly<Record<string, unknown>> = {}) { const next = Object.freeze({ ...s, ...patch, updatedAt: now(), containsRuntimeHandles: false, containsMediaPayloads: false, containsEncodedPackets: false, transmitsNetworkPackets: false }) as TransportSession; this.sessions.set(s.id, this.withEvent(next, type, message, metadata)); return this.must(s.id); }
  private withEvent(s: TransportSession, type: TransportRuntimeEventType, message: string, metadata: Readonly<Record<string, unknown>> = {}) { const event: TransportRuntimeEvent = Object.freeze({ id: idFor(type), type, timestamp: now(), sessionId: s.id, protocol: s.protocol.id, lifecycle: s.lifecycle, message, metadata: Object.freeze({ ...metadata, backend: this.backendDescriptor.id }), containsMediaPayloads: false, containsEncodedPackets: false }); this.events = [event, ...this.events].slice(0, 300); this.listeners.forEach((cb) => cb(event)); return Object.freeze({ ...s, events: Object.freeze([event, ...s.events].slice(0, 300)) }) as TransportSession; }
  private must(id: string) { const s = this.sessions.get(id); if (!s) throw new Error(`Transport session ${id} not found`); return s; } }

function deriveHealth(packetLoss: number, jitter: number): TransportHealth { if (packetLoss >= 5 || jitter >= 120) return 'critical'; if (packetLoss >= 1 || jitter >= 40) return 'degraded'; return 'healthy'; }
export const createTransportManager = (input: { id?: string } = {}) => new TransportManager(input.id);

export async function createDemoTransportWorkflow(input: { streamingPipeline?: StreamingPipelineV2; streamingSessionId?: string; programOutput?: ProgramOutput; audioMixer?: AudioMixer; sceneCompositor?: SceneCompositor; mediaClock?: MediaClock; frameScheduler?: FrameScheduler } = {}) { const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const scheduler = input.frameScheduler ?? new FrameScheduler(clock); clock.startClock(); const manager = createTransportManager({ id: 'transport-manager:demo' }); const createInput: CreateTransportSessionInput = { id: 'transport-session:demo:srt', protocol: 'srt', endpoint: 'srt://contribution.example/live?token=secret', mediaClock: clock, frameScheduler: scheduler, targetBitrateKbps: 8000, expectedLatencyMs: 120, metadata: { demo: true }, ...(input.streamingPipeline ? { streamingPipeline: input.streamingPipeline } : {}), ...(input.streamingSessionId ? { streamingSessionId: input.streamingSessionId } : {}), ...(input.programOutput ? { programOutput: input.programOutput } : {}), ...(input.audioMixer ? { audioMixer: input.audioMixer } : {}), ...(input.sceneCompositor ? { sceneCompositor: input.sceneCompositor } : {}) }; const session = manager.createSession(createInput); manager.negotiate(session.id); manager.connect(session.id); manager.markConnected(session.id); manager.updateMetrics(session.id, { bitrateKbps: 7900, latencyMs: 118, jitterMs: 12, packetLossPercent: 0.05, tick: scheduler.createTick(), audioFrames: 1 }); manager.reconnect(session.id, 'Demo network handoff'); manager.markConnected(session.id); manager.stop(session.id); return { manager: manager.getSnapshot(), session: manager.getSession(session.id)!, events: manager.getEvents() }; }
