import type { RenderFrame, RenderFrameLayer, SceneCompositor } from './compositor/index.js';
import type { GpuFrame, GpuRuntime } from './gpu-runtime/index.js';
import { createClock, type BroadcastClockState, type MediaClock } from './sync/clock.js';

export type TransitionEffectKind = 'cut' | 'dissolve' | 'fade' | 'dip_to_black';
export type TransitionLifecycleEventType = 'transition_started' | 'transition_progress' | 'transition_completed';
export type TransitionTimelineState = 'idle' | 'running' | 'completed';

export interface TransitionRenderRequest { readonly id?: string; readonly effect: TransitionEffectKind; readonly durationMs?: number; readonly fromSceneId: string; readonly toSceneId: string; readonly metadata?: Record<string, unknown>; }
export interface TransitionTimelineSample { readonly transitionId: string; readonly state: TransitionTimelineState; readonly frameId: number; readonly elapsedMs: number; readonly durationMs: number; readonly progress: number; readonly presentationTimestamp: number; readonly clock: BroadcastClockState; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface TransitionEffectContext { readonly request: TransitionRenderRequest; readonly timeline: TransitionTimelineSample; readonly fromFrame: RenderFrame; readonly toFrame: RenderFrame; readonly metadata: Record<string, unknown>; }
export interface TransitionEffect { readonly kind: TransitionEffectKind; render(context: TransitionEffectContext): RenderFrame; }
export interface TransitionRuntimeEvent { readonly id: string; readonly type: TransitionLifecycleEventType; readonly timestamp: string; readonly transitionId: string; readonly effect: TransitionEffectKind; readonly frameId: number; readonly progress: number; readonly fromSceneId: string; readonly toSceneId: string; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface TransitionRendererSnapshot { readonly id: string; readonly activeTransition?: TransitionRenderRequest; readonly timeline?: TransitionTimelineSample; readonly events: readonly TransitionRuntimeEvent[]; readonly clock: BroadcastClockState; readonly compositorId: string; readonly rendererBackend?: string; readonly metadata: Record<string, unknown>; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface TransitionRenderResult { readonly frame: RenderFrame; readonly gpuFrame?: GpuFrame; readonly timeline: TransitionTimelineSample; readonly completed: boolean; readonly events: readonly TransitionRuntimeEvent[]; readonly containsRuntimeHandles: false; readonly containsMediaPayloads: false; }
export interface TransitionRenderer { readonly id: string; start(request: TransitionRenderRequest): TransitionTimelineSample; renderNextFrame(): TransitionRenderResult; complete(): TransitionRendererSnapshot; getSnapshot(): TransitionRendererSnapshot; getRuntimeEvents(): readonly TransitionRuntimeEvent[]; onRuntimeEvent(callback: (event: TransitionRuntimeEvent) => void): () => void; }

const now = () => new Date().toISOString();
const idFor = (prefix: string) => `${prefix}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
const clone = (value: Record<string, unknown> = {}) => JSON.parse(JSON.stringify(value)) as Record<string, unknown>;
const clamp = (v: number) => Math.max(0, Math.min(1, Number.isFinite(v) ? v : 0));
const layerWithOpacity = (layer: RenderFrameLayer, opacity: number, role: string): RenderFrameLayer => Object.freeze({ ...layer, opacity: clamp(layer.opacity * opacity), metadata: clone({ ...layer.metadata, transitionRole: role, transitionOpacity: clamp(opacity) }) });
const solid = (frame: RenderFrame, opacity: number): RenderFrameLayer => Object.freeze({ layerId: `transition:black:${frame.frameId}`, source: { type: 'solid_color' as const, color: '#000000', label: 'Dip/Fade Black', metadata: { transitionGenerated: true } }, drawOrder: 10_000, zIndex: 10_000, geometry: { position: { x: 0, y: 0 }, size: { width: frame.canvas.width, height: frame.canvas.height }, rotation: 0 }, opacity: clamp(opacity), metadata: { transitionGenerated: true, transitionRole: 'black' } });
const frameFrom = (base: RenderFrame, id: string, layers: readonly RenderFrameLayer[], metadata: Record<string, unknown>): RenderFrame => Object.freeze({ ...base, id, layers, metadata: clone(metadata), containsRuntimeHandles: false, containsMediaPayloads: false });

export class TransitionTimeline { private request?: TransitionRenderRequest; private startFrame = 0; constructor(private readonly clock: MediaClock = createClock({ frameRate: 30 })) {} start(request: TransitionRenderRequest) { if (this.clock.getState().status === 'stopped') this.clock.startClock(); this.request = request; this.startFrame = this.clock.getCurrentFrame(); return this.sample(); } sample(): TransitionTimelineSample { if (!this.request) return { transitionId: 'none', state: 'idle', frameId: this.clock.getCurrentFrame(), elapsedMs: 0, durationMs: 0, progress: 0, presentationTimestamp: this.clock.getPresentationTimestamp(), clock: this.clock.getState(), containsRuntimeHandles: false, containsMediaPayloads: false }; const frameId = this.clock.getCurrentFrame(); const elapsedMs = Math.max(0, this.clock.getFrameTimestamp(frameId) - this.clock.getFrameTimestamp(this.startFrame)); const durationMs = Math.max(0, Math.round(this.request.durationMs ?? (this.request.effect === 'cut' ? 0 : 1000))); const progress = durationMs === 0 ? 1 : clamp(elapsedMs / durationMs); return { transitionId: this.request.id ?? 'transition:active', state: progress >= 1 ? 'completed' : 'running', frameId, elapsedMs, durationMs, progress, presentationTimestamp: this.clock.getFrameTimestamp(frameId), clock: this.clock.getState(), containsRuntimeHandles: false, containsMediaPayloads: false }; } complete() { return this.sample(); } }

export const createCutTransitionEffect = (): TransitionEffect => ({ kind: 'cut', render: ({ toFrame, timeline, request }) => frameFrom(toFrame, `transition-frame:${request.id ?? 'cut'}:${timeline.frameId}`, toFrame.layers, { ...toFrame.metadata, transitionEffect: 'cut', transitionProgress: 1 }) });
export const createDissolveTransitionEffect = (): TransitionEffect => ({ kind: 'dissolve', render: ({ fromFrame, toFrame, timeline, request }) => frameFrom(toFrame, `transition-frame:${request.id ?? 'dissolve'}:${timeline.frameId}`, [...fromFrame.layers.map((l)=>layerWithOpacity(l, 1 - timeline.progress, 'from')), ...toFrame.layers.map((l)=>layerWithOpacity(l, timeline.progress, 'to'))], { transitionEffect: 'dissolve', transitionProgress: timeline.progress, fromCompositionId: fromFrame.compositionId, toCompositionId: toFrame.compositionId }) });
export const createFadeTransitionEffect = (): TransitionEffect => ({ kind: 'fade', render: ({ fromFrame, toFrame, timeline, request }) => { const p = timeline.progress; const firstHalf = p < 0.5; const base = firstHalf ? fromFrame : toFrame; const blackOpacity = firstHalf ? p * 2 : (1 - p) * 2; return frameFrom(base, `transition-frame:${request.id ?? 'fade'}:${timeline.frameId}`, [...base.layers, solid(base, blackOpacity)], { transitionEffect: 'fade', transitionProgress: p, blackOpacity }); } });
export const createDipToBlackTransitionEffect = (): TransitionEffect => ({ kind: 'dip_to_black', render: ({ fromFrame, toFrame, timeline, request }) => { const p = timeline.progress; const base = p < 0.5 ? fromFrame : toFrame; const blackOpacity = p < 0.5 ? p * 2 : (1 - p) * 2; return frameFrom(base, `transition-frame:${request.id ?? 'dip'}:${timeline.frameId}`, [...base.layers, solid(base, blackOpacity)], { transitionEffect: 'dip_to_black', transitionProgress: p, blackOpacity }); } });

export function createTransitionRenderer(input: { id?: string; fromCompositor: SceneCompositor; toCompositor: SceneCompositor; outputCompositor: SceneCompositor; mediaClock?: MediaClock; renderer?: GpuRuntime; durationMs?: number; metadata?: Record<string, unknown> }): TransitionRenderer {
  const id = input.id ?? 'transition-renderer:default'; const clock = input.mediaClock ?? createClock({ frameRate: 30 }); const timeline = new TransitionTimeline(clock); const effects = new Map<TransitionEffectKind, TransitionEffect>([['cut', createCutTransitionEffect()], ['dissolve', createDissolveTransitionEffect()], ['fade', createFadeTransitionEffect()], ['dip_to_black', createDipToBlackTransitionEffect()]]); let active: TransitionRenderRequest | undefined; let latest: TransitionTimelineSample | undefined; let events: TransitionRuntimeEvent[] = []; const listeners = new Set<(event: TransitionRuntimeEvent)=>void>();
  const emit = (type: TransitionLifecycleEventType, sample: TransitionTimelineSample, metadata: Record<string, unknown> = {}) => { if (!active) throw new Error('No active transition'); const event = Object.freeze({ id: idFor(type), type, timestamp: now(), transitionId: sample.transitionId, effect: active.effect, frameId: sample.frameId, progress: sample.progress, fromSceneId: active.fromSceneId, toSceneId: active.toSceneId, metadata: clone(metadata), containsRuntimeHandles: false, containsMediaPayloads: false }); events = [event, ...events].slice(0, 300); listeners.forEach((cb)=>cb(event)); return event; };
  const snapshot = (): TransitionRendererSnapshot => Object.freeze({ id, ...(active ? { activeTransition: active } : {}), ...(latest ? { timeline: latest } : {}), events: Object.freeze([...events]), clock: clock.getState(), compositorId: input.outputCompositor.id, ...(input.renderer ? { rendererBackend: input.renderer.manifest.diagnostics.backend } : {}), metadata: clone({ ...(input.metadata ?? {}), backendIndependent: true, metadataOnly: true }), containsRuntimeHandles: false, containsMediaPayloads: false });
  return { id, start(request) { active = Object.freeze({ ...request, id: request.id ?? idFor(`transition:${request.effect}`), durationMs: Math.max(0, Math.round(request.durationMs ?? input.durationMs ?? (request.effect === 'cut' ? 0 : 1000))), metadata: clone(request.metadata) }); latest = timeline.start(active); emit('transition_started', latest, active.metadata); return latest; }, renderNextFrame() { if (!active) throw new Error('No active transition'); latest = timeline.sample(); const fromFrame = input.fromCompositor.composeFrame({ frameId: latest.frameId, rendererBackend: input.renderer?.manifest.diagnostics.backend, metadata: { transitionSource: 'from', sceneId: active.fromSceneId } }); const toFrame = input.toCompositor.composeFrame({ frameId: latest.frameId, rendererBackend: input.renderer?.manifest.diagnostics.backend, metadata: { transitionSource: 'to', sceneId: active.toSceneId } }); const effect = effects.get(active.effect)!; const frame = effect.render({ request: active, timeline: latest, fromFrame, toFrame, metadata: clone(active.metadata) }); input.outputCompositor.composeFrame({ frameId: latest.frameId, rendererBackend: input.renderer?.manifest.diagnostics.backend, compositionId: frame.compositionId, metadata: frame.metadata }); const renderer = input.renderer; const gpuFrame = renderer ? { frameId: frame.frameId, graphRevision: frame.graphRevision, executionBatchId: `transition:${active.id}`, mediaClockTimestamp: frame.mediaTimestamp, compositionPlanId: frame.compositionId, resources: [], metadata: clone(frame.metadata) } satisfies GpuFrame : undefined; if (gpuFrame) renderer!.execute({ id: `render:${active.id}:${latest.frameId}`, type: 'START_GPU_RUNTIME', timestamp: now(), graphRevision: frame.graphRevision, payload: { transitionId: active.id, effect: active.effect, progress: latest.progress } }, gpuFrame); emit(latest.state === 'completed' ? 'transition_completed' : 'transition_progress', latest, frame.metadata); const completed = latest.state === 'completed'; if (completed) active = undefined; return { frame, ...(gpuFrame ? { gpuFrame } : {}), timeline: latest, completed, events: Object.freeze([...events]), containsRuntimeHandles: false, containsMediaPayloads: false }; }, complete() { latest = timeline.complete(); if (active) emit('transition_completed', latest, active.metadata); active = undefined; return snapshot(); }, getSnapshot: snapshot, getRuntimeEvents: () => Object.freeze([...events]), onRuntimeEvent(callback) { listeners.add(callback); return () => listeners.delete(callback); } };
}

export async function createTransitionRendererDemo() { const fromCompositor = (await import('./compositor/index.js')).createSceneCompositor({ id: 'transition-demo:program', sceneId: 'scene:program', layers: [(await import('./compositor/index.js')).createRenderLayer({ id: 'program-layer', source: { type: 'video', sourceId: 'camera:program', metadata: {} } })] }); const toCompositor = (await import('./compositor/index.js')).createSceneCompositor({ id: 'transition-demo:preview', sceneId: 'scene:preview', layers: [(await import('./compositor/index.js')).createRenderLayer({ id: 'preview-layer', source: { type: 'video', sourceId: 'camera:preview', metadata: {} } })] }); const outputCompositor = (await import('./compositor/index.js')).createSceneCompositor({ id: 'transition-demo:output', sceneId: 'scene:program' }); const renderer = createTransitionRenderer({ id: 'transition-renderer:demo', fromCompositor, toCompositor, outputCompositor, durationMs: 500, metadata: { demo: true } }); renderer.start({ effect: 'dissolve', fromSceneId: 'scene:program', toSceneId: 'scene:preview' }); const firstFrame = renderer.renderNextFrame(); const completed = renderer.complete(); return { description: 'Preview transitions to Program through a metadata-only TransitionRenderer dissolve demo.', firstFrame, completed, events: renderer.getRuntimeEvents() }; }
