import { HealthStatus, redact } from '../observability/index.js';
import type { TenantContext } from '../multi-tenant/index.js';

export enum ExtensionCategory { SourceConnector='source_connector', OutputConnector='output_connector', DeviceDriver='device_driver', GraphicsPackage='graphics_package', AutomationPackage='automation_package', WorkflowTemplate='workflow_template', RulePackage='rule_package', AnalyticsModule='analytics_module', MonitoringAdapter='monitoring_adapter', SocialConnector='social_connector', ChatConnector='chat_connector', CaptioningProvider='captioning_provider', TranslationProvider='translation_provider', AIService='ai_service', ControlSurface='control_surface', ReplayExtension='replay_extension', MediaProcessor='media_processor', StorageProvider='storage_provider', AuthenticationProvider='authentication_provider', UIExtension='ui_extension', Theme='theme', ProductionTemplate='production_template', Integration='integration', Custom='custom' }
export enum ExtensionType { DeclarativePackage='declarative_package', UIExtension='ui_extension', ServicePlugin='service_plugin', DevicePlugin='device_plugin', WorkflowBundle='workflow_bundle', RulesBundle='rules_bundle', RemoteIntegration='remote_integration', MediaPipelinePlugin='media_pipeline_plugin', NativePlugin='native_plugin' }
export enum ExtensionRuntimeType { JavaScript='javascript', TypeScriptCompiled='typescript_compiled', WebAssembly='webassembly', Container='container', RemoteAPI='remote_api', Native='native', Declarative='declarative' }
export enum ExtensionRiskLevel { Minimal='minimal', Low='low', Moderate='moderate', High='high', Critical='critical' }
export enum TenantIsolationMode { SingleTenantInstance='single_tenant_instance', MultiTenantIsolated='multi_tenant_isolated', PlatformSharedNoData='platform_shared_no_data', DedicatedDeployment='dedicated_deployment' }
export enum PluginLifecycleState { Discovered='discovered', Downloading='downloading', Verifying='verifying', Installed='installed', Configuring='configuring', Enabled='enabled', Starting='starting', Running='running', Degraded='degraded', Stopped='stopped', Updating='updating', Suspended='suspended', Disabled='disabled', Failed='failed', Uninstalling='uninstalling', Removed='removed' }
export enum ExtensionIdentityStatus { Active='active', Suspended='suspended', Restricted='restricted', Revoked='revoked', Expired='expired' }
export enum CertificationStatus { Draft='draft', Submitted='submitted', Testing='testing', Approved='approved', Rejected='rejected', Expired='expired', Revoked='revoked' }
export enum CertificationLevel { Community='community', Verified='verified', ProductionReady='production_ready', BroadcastCertified='broadcast_certified', EnterpriseCertified='enterprise_certified', SecurityCertified='security_certified', UBOSOfficial='ubos_official' }
export enum MarketplaceListingStatus { Draft='draft', Submitted='submitted', InReview='in_review', Approved='approved', Published='published', Restricted='restricted', Suspended='suspended', Removed='removed', Retired='retired' }
export enum MarketplacePricingModel { Free='free', OneTime='one_time', Subscription='subscription', UsageBased='usage_based', PerTenant='per_tenant', PerProduction='per_production', PerOperator='per_operator', PerDevice='per_device', EnterpriseLicense='enterprise_license', ExternalPurchase='external_purchase' }
export enum ExtensionLicenseStatus { Trial='trial', Active='active', GracePeriod='grace_period', Suspended='suspended', Expired='expired', Revoked='revoked' }
export enum SubmissionStatus { Draft='draft', Uploaded='uploaded', Validating='validating', Testing='testing', SecurityReview='security_review', ManualReview='manual_review', ChangesRequired='changes_required', Approved='approved', Rejected='rejected', Published='published', Withdrawn='withdrawn' }
export enum PluginRestartPolicy { Never='never', OnFailure='on_failure', LimitedRetries='limited_retries', Always='always', OperatorApproval='operator_approval' }
export enum ExtensionHAMode { NotSupported='not_supported', Stateless='stateless', LeaderOnly='leader_only', ActiveStandby='active_standby', ActiveActive='active_active', ExternalService='external_service' }

export interface CapabilityScope { organizationId?:string; tenantId?:string; workspaceId?:string; productionId?:string; resourceType?:string; resourceId?:string; destination?:string; }
export interface RequestedCapability { capability:string; reason:string; required:boolean; scope?:CapabilityScope; riskLevel:ExtensionRiskLevel; }
export interface ExtensionEntrypoint { id:string; runtime:ExtensionRuntimeType; module:string; processType:string; startupMode:string; }
export interface NetworkRequirement { hostPattern:string; protocol:string; ports:number[]; direction:'outbound'|'inbound'; required:boolean; justification:string; }
export interface ExtensionIntegrityInfo { packageHash:string; manifestHash:string; signature:string; signingKeyId:string; provenanceHash:string; }
export interface ExtensionSupportInfo { contact:string; responseTargetHours:number; policy:string; }
export interface ExtensionLicenseInfo { license:string; pricingModel:MarketplacePricingModel; termsUrl?:string; }
export interface ExtensionManifest { id:string; name:string; description:string; publisherId:string; version:string; type:ExtensionType; category:ExtensionCategory; entrypoints:ExtensionEntrypoint[]; capabilities:RequestedCapability[]; supportedUBOSVersions:string; supportedEnvironments:string[]; tenantIsolationMode:TenantIsolationMode; riskLevel:ExtensionRiskLevel; dependencies:{type:string;id:string;versionRange?:string;required:boolean;reason?:string}[]; configurationSchema?:Record<string,unknown>; storageRequirements?:{type:string;quotaBytes:number;encrypted:boolean}[]; networkRequirements?:NetworkRequirement[]; support:ExtensionSupportInfo; license:ExtensionLicenseInfo; integrity:ExtensionIntegrityInfo; haMode?:ExtensionHAMode; }
export interface DeveloperOrganization { id:string; name:string; verificationStatus:'unverified'|'identity_verified'|'organization_verified'|'trusted_publisher'|'suspended'|'revoked'; administratorIds:string[]; signingKeyIds:string[]; supportContact:string; createdAt:number; }
export interface ExtensionCertification { id:string; extensionId:string; version:string; level:CertificationLevel; testResults:{name:string;passed:boolean;details:string}[]; approvedCapabilities:string[]; limitations:string[]; certifiedAt?:number; expiresAt?:number; status:CertificationStatus; }
export interface MarketplaceListing { id:string; extensionId:string; title:string; summary:string; description:string; publisherId:string; category:ExtensionCategory; currentVersion:string; pricingModel:MarketplacePricingModel; supportPolicy:ExtensionSupportInfo; certificationStatus:CertificationStatus; listingStatus:MarketplaceListingStatus; supportedRegions?:string[]; supportedLanguages?:string[]; }
export interface ExtensionIdentity { extensionId:string; installationId:string; publisherId:string; tenantId:string; workspaceId?:string; grantedCapabilities:string[]; credentialId:string; installedAt:number; installedBy:string; status:ExtensionIdentityStatus; }
export interface ExtensionInstallation { id:string; extensionId:string; version:string; scope:CapabilityScope; state:PluginLifecycleState; identity:ExtensionIdentity; sandbox:{maximumMemoryMb:number;maximumCPUPercent:number;maximumThreads:number;networkPolicyId:string;restartPolicy:PluginRestartPolicy}; health:{status:HealthStatus; failureCount:number; restartCount:number; updatedAt:number}; configuration:Record<string,unknown>; licenseId?:string; }
export interface ExtensionSubmission { id:string; extensionId:string; version:string; publisherId:string; packageReference:string; submittedAt:number; requestedCertificationLevel:CertificationLevel; status:SubmissionStatus; reviewFindings:{severity:ExtensionRiskLevel;message:string}[]; }
export interface ExtensionLicense { id:string; extensionId:string; tenantId:string; pricingModel:MarketplacePricingModel; entitlement:Record<string,unknown>; activatedAt:number; expiresAt?:number; status:ExtensionLicenseStatus; }
export interface ExtensionUsageRecord { extensionId:string; installationId:string; tenantId:string; metric:string; quantity:number; unit:string; periodStart:number; periodEnd:number; recordedAt:number; }
export interface ExtensionSecurityAdvisory { id:string; extensionId:string; affectedVersions:string[]; severity:string; description:string; remediation:string; fixedVersion?:string; publishedAt:number; }
export interface MarketplaceSnapshot { developers:DeveloperOrganization[]; manifests:ExtensionManifest[]; submissions:ExtensionSubmission[]; certifications:ExtensionCertification[]; listings:MarketplaceListing[]; installations:ExtensionInstallation[]; licenses:ExtensionLicense[]; usage:ExtensionUsageRecord[]; advisories:ExtensionSecurityAdvisory[]; audit:string[]; telemetry:{developers:number; extensions:number; listings:number; publishedListings:number; installations:number; running:number; suspended:number; advisories:number; deniedActions:number}; health:{status:HealthStatus; score:number; reasons:string[]}; }

const clone=<T>(v:T):T=>structuredClone(v); const freeze=<T>(v:T):T=>Object.freeze(clone(v)); const safe=(v:string)=>String(redact(v)); const SECRET=/secret|token|password|credential/i;
const highRisk=new Set(['production.program.change','recording.delete','stream.stop','security.role.manage','authorization.manage','media.pipeline.modify']);
function semver(v:string){ if(!/^\d+\.\d+\.\d+$/.test(v)) throw new Error('extension version must be semantic'); }
function hashOk(h:string){ if(!/^sha256:[a-fA-F0-9]{6,}$/.test(h)) throw new Error('integrity hash must be sha256'); }
function assertNoSecrets(o:unknown):void{ if(!o||typeof o!=='object') return; for(const [k,v] of Object.entries(o as Record<string,unknown>)){ if(SECRET.test(k)) throw new Error('configuration must not contain plain-text secrets'); assertNoSecrets(v); } }

export class MarketplaceExtensionPlatform { #devs=new Map<string,DeveloperOrganization>(); #manifests=new Map<string,ExtensionManifest>(); #subs=new Map<string,ExtensionSubmission>(); #certs=new Map<string,ExtensionCertification>(); #listings=new Map<string,MarketplaceListing>(); #installs=new Map<string,ExtensionInstallation>(); #licenses=new Map<string,ExtensionLicense>(); #usage:ExtensionUsageRecord[]=[]; #advisories=new Map<string,ExtensionSecurityAdvisory>(); #denyExt=new Set<string>(); #denyPublishers=new Set<string>(); #audit:string[]=[]; #denied=0; constructor(private readonly ubosVersion='5.11.9', private readonly maxHistory=20000){}
  registerDeveloper(org:DeveloperOrganization):DeveloperOrganization{ if(this.#devs.has(org.id)) throw new Error('developer already exists'); const s={...org,name:safe(org.name),supportContact:safe(org.supportContact),administratorIds:org.administratorIds.map(safe),signingKeyIds:[...new Set(org.signingKeyIds)].sort()}; this.#devs.set(org.id,freeze(s)); this.#audit.push(`DeveloperRegistered:${org.id}`); return clone(s); }
  createSigningKey(developerId:string,keyId:string):void{ const d=this.#requireDev(developerId); if(d.verificationStatus==='revoked'||d.verificationStatus==='suspended') throw new Error('developer cannot create signing keys'); this.#devs.set(developerId,freeze({...d,signingKeyIds:[...new Set([...d.signingKeyIds,keyId])].sort()})); this.#audit.push(`SigningKeyCreated:${developerId}:${keyId}`); }
  registerExtension(manifest:ExtensionManifest):ExtensionManifest{ if(this.#denyPublishers.has(manifest.publisherId)) throw new Error('publisher revoked'); const d=this.#requireDev(manifest.publisherId); semver(manifest.version); hashOk(manifest.integrity.packageHash); hashOk(manifest.integrity.manifestHash); if(!d.signingKeyIds.includes(manifest.integrity.signingKeyId)) throw new Error('unknown signing key'); if(!manifest.integrity.signature) throw new Error('signature missing'); if(!manifest.supportedUBOSVersions.includes('5.11')) throw new Error('unsupported UBOS version'); if(manifest.type===ExtensionType.NativePlugin && manifest.riskLevel!==ExtensionRiskLevel.Critical) throw new Error('native plugins require critical risk classification'); for(const cap of manifest.capabilities) if(highRisk.has(cap.capability)&&cap.riskLevel!==ExtensionRiskLevel.High&&cap.riskLevel!==ExtensionRiskLevel.Critical) throw new Error('high-risk capability requires high risk review'); const s={...manifest,name:safe(manifest.name),description:safe(manifest.description),networkRequirements:manifest.networkRequirements?.map(n=>({...n,justification:safe(n.justification)})),support:{...manifest.support,contact:safe(manifest.support.contact),policy:safe(manifest.support.policy)}}; this.#manifests.set(`${manifest.id}@${manifest.version}`,freeze(s)); this.#audit.push(`ExtensionRegistered:${manifest.id}:${manifest.version}`); return clone(s); }
  submit(sub:ExtensionSubmission):ExtensionSubmission{ this.#requireManifest(sub.extensionId,sub.version); this.#requireDev(sub.publisherId); const s={...sub,packageReference:safe(sub.packageReference),status:SubmissionStatus.Validating,reviewFindings:sub.reviewFindings.map(f=>({...f,message:safe(f.message)}))}; this.#subs.set(sub.id,freeze(s)); this.#audit.push(`ExtensionSubmitted:${sub.extensionId}:${sub.version}`); return clone(s); }
  certify(id:string, level:CertificationLevel, tests:{name:string;passed:boolean;details:string}[], approvedCapabilities:string[], at:number):ExtensionCertification{ const sub=this.#subs.get(id); if(!sub) throw new Error('unknown submission'); const failed=tests.filter(t=>!t.passed); const status=failed.length?CertificationStatus.Rejected:CertificationStatus.Approved; const cert={id:`cert-${id}`,extensionId:sub.extensionId,version:sub.version,level,testResults:tests.map(t=>({...t,details:safe(t.details)})),approvedCapabilities:[...new Set(approvedCapabilities)].sort(),limitations:failed.map(f=>f.name),certifiedAt:failed.length?undefined:at,status}; this.#certs.set(`${sub.extensionId}@${sub.version}`,freeze(cert)); this.#subs.set(id,freeze({...sub,status:failed.length?SubmissionStatus.Rejected:SubmissionStatus.Approved,reviewFindings:failed.map(f=>({severity:ExtensionRiskLevel.High,message:f.name}))})); this.#audit.push(`ExtensionCertified:${sub.extensionId}:${status}`); return clone(cert); }
  publish(listing:MarketplaceListing):MarketplaceListing{ const cert=this.#certs.get(`${listing.extensionId}@${listing.currentVersion}`); if(!cert||cert.status!==CertificationStatus.Approved) throw new Error('listing requires approved certification'); const manifest=this.#requireManifest(listing.extensionId,listing.currentVersion); if(this.#denyPublishers.has(listing.publisherId)||this.#denyExt.has(listing.extensionId)) throw new Error('publisher or extension revoked'); const s={...listing,title:safe(listing.title),summary:safe(listing.summary),description:safe(listing.description),category:manifest.category,certificationStatus:cert.status,listingStatus:MarketplaceListingStatus.Published}; this.#listings.set(listing.id,freeze(s)); this.#audit.push(`MarketplaceListingPublished:${listing.id}`); return clone(s); }
  activateLicense(lic:ExtensionLicense):void{ this.#requireManifest(lic.extensionId, this.#latestVersion(lic.extensionId)); this.#licenses.set(lic.id,freeze({...lic,entitlement:redact(lic.entitlement) as Record<string,unknown>})); this.#audit.push(`ExtensionLicenseActivated:${lic.extensionId}:${lic.tenantId}`); }
  install(listingId:string, ctx:TenantContext, configuration:Record<string,unknown>, at:number):ExtensionInstallation{ const listing=this.#listings.get(listingId); if(!listing||listing.listingStatus!==MarketplaceListingStatus.Published) throw new Error('listing unavailable'); const manifest=this.#requireManifest(listing.extensionId,listing.currentVersion); if(this.#denyExt.has(manifest.id)||this.#denyPublishers.has(manifest.publisherId)) throw new Error('extension revoked'); assertNoSecrets(configuration); const cert=this.#certs.get(`${manifest.id}@${manifest.version}`); if(!cert) throw new Error('missing certification'); const denied=manifest.capabilities.filter(c=>c.required&&!cert.approvedCapabilities.includes(c.capability)); if(denied.length) throw new Error('required capability not certified'); const license=[...this.#licenses.values()].find(l=>l.extensionId===manifest.id&&l.tenantId===ctx.tenantId&&(l.status===ExtensionLicenseStatus.Active||l.status===ExtensionLicenseStatus.Trial||l.status===ExtensionLicenseStatus.GracePeriod)); if(listing.pricingModel!==MarketplacePricingModel.Free&&!license) throw new Error('active entitlement required'); const granted=manifest.capabilities.filter(c=>ctx.permissions.includes(c.capability)&&(!c.scope?.tenantId||c.scope.tenantId===ctx.tenantId)).map(c=>c.capability).sort(); const id=`inst-${manifest.id}-${ctx.tenantId}`; const install={id,extensionId:manifest.id,version:manifest.version,scope:{organizationId:ctx.organizationId,tenantId:ctx.tenantId,workspaceId:ctx.workspaceId,productionId:ctx.productionId},state:PluginLifecycleState.Installed,identity:{extensionId:manifest.id,installationId:id,publisherId:manifest.publisherId,tenantId:ctx.tenantId,workspaceId:ctx.workspaceId,grantedCapabilities:granted,credentialId:`cred-${id}`,installedAt:at,installedBy:safe(ctx.actingIdentityId),status:ExtensionIdentityStatus.Active},sandbox:{maximumMemoryMb:manifest.type===ExtensionType.UIExtension?128:256,maximumCPUPercent:manifest.type===ExtensionType.MediaPipelinePlugin?15:5,maximumThreads:4,networkPolicyId:`net-${id}`,restartPolicy:PluginRestartPolicy.LimitedRetries},health:{status:HealthStatus.Healthy,failureCount:0,restartCount:0,updatedAt:at},configuration:redact(configuration) as Record<string,unknown>,licenseId:license?.id}; this.#installs.set(id,freeze(install)); this.#audit.push(`ExtensionInstalled:${manifest.id}:${ctx.tenantId}`); return clone(install); }
  enable(id:string):void{ const i=this.#requireInstall(id); if(i.identity.status!==ExtensionIdentityStatus.Active) throw new Error('identity inactive'); this.#installs.set(id,freeze({...i,state:PluginLifecycleState.Running})); this.#audit.push(`ExtensionEnabled:${id}`); }
  requestCommand(id:string, capability:string, tenantId:string):boolean{ const i=this.#requireInstall(id); const ok=i.state===PluginLifecycleState.Running&&i.identity.status===ExtensionIdentityStatus.Active&&i.identity.tenantId===tenantId&&i.identity.grantedCapabilities.includes(capability); if(!ok){ this.#denied++; this.#audit.push(`ExtensionCapabilityDenied:${id}:${capability}`); return false; } this.#audit.push(`ExtensionCommandAccepted:${id}:${capability}`); return true; }
  crash(id:string, at:number):void{ const i=this.#requireInstall(id); const failures=i.health.failureCount+1; const state=failures>=5?PluginLifecycleState.Suspended:PluginLifecycleState.Degraded; this.#installs.set(id,freeze({...i,state,health:{...i.health,status:failures>=5?HealthStatus.Critical:HealthStatus.Warning,failureCount:failures,restartCount:i.health.restartCount+(failures>=5?0:1),updatedAt:at}})); this.#audit.push(`ExtensionCrashed:${id}:${state}`); }
  uninstall(id:string, activeProduction=false):void{ const i=this.#requireInstall(id); if(activeProduction) throw new Error('cannot uninstall extension active in production without migration'); this.#installs.set(id,freeze({...i,state:PluginLifecycleState.Removed,identity:{...i.identity,status:ExtensionIdentityStatus.Revoked}})); this.#audit.push(`ExtensionUninstalled:${id}`); }
  publishAdvisory(a:ExtensionSecurityAdvisory):void{ this.#advisories.set(a.id,freeze({...a,description:safe(a.description),remediation:safe(a.remediation)})); this.#audit.push(`ExtensionAdvisoryPublished:${a.extensionId}:${a.severity}`); }
  revokePublisher(publisherId:string):void{ this.#denyPublishers.add(publisherId); for(const [id,i] of this.#installs) if(i.identity.publisherId===publisherId) this.#installs.set(id,freeze({...i,state:PluginLifecycleState.Suspended,identity:{...i.identity,status:ExtensionIdentityStatus.Revoked}})); this.#audit.push(`PublisherRevoked:${publisherId}`); }
  meter(r:ExtensionUsageRecord):void{ const i=this.#requireInstall(r.installationId); if(i.identity.tenantId!==r.tenantId||i.extensionId!==r.extensionId) throw new Error('usage tenant mismatch'); this.#usage.push(freeze(r)); this.#usage=this.#usage.slice(-this.maxHistory); }
  snapshot():MarketplaceSnapshot{ return clone({developers:[...this.#devs.values()].sort((a,b)=>a.id.localeCompare(b.id)),manifests:[...this.#manifests.values()].sort((a,b)=>a.id.localeCompare(b.id)),submissions:[...this.#subs.values()].sort((a,b)=>a.id.localeCompare(b.id)),certifications:[...this.#certs.values()].sort((a,b)=>a.id.localeCompare(b.id)),listings:[...this.#listings.values()].sort((a,b)=>a.id.localeCompare(b.id)),installations:[...this.#installs.values()].sort((a,b)=>a.id.localeCompare(b.id)),licenses:[...this.#licenses.values()].sort((a,b)=>a.id.localeCompare(b.id)),usage:[...this.#usage],advisories:[...this.#advisories.values()].sort((a,b)=>a.id.localeCompare(b.id)),audit:this.#audit.slice(-this.maxHistory),telemetry:this.telemetry(),health:this.health()}); }
  telemetry(){ return {developers:this.#devs.size,extensions:new Set([...this.#manifests.values()].map(m=>m.id)).size,listings:this.#listings.size,publishedListings:[...this.#listings.values()].filter(l=>l.listingStatus===MarketplaceListingStatus.Published).length,installations:this.#installs.size,running:[...this.#installs.values()].filter(i=>i.state===PluginLifecycleState.Running).length,suspended:[...this.#installs.values()].filter(i=>i.state===PluginLifecycleState.Suspended).length,advisories:this.#advisories.size,deniedActions:this.#denied}; }
  health(){ const t=this.telemetry(); const reasons=[...(t.suspended?[`${t.suspended} suspended extensions`]:[]),...(t.advisories?[`${t.advisories} advisories`]:[])]; return {status:reasons.length?HealthStatus.Warning:HealthStatus.Healthy,score:Math.max(0,100-reasons.length*15),reasons}; }
  #requireDev(id:string){ const d=this.#devs.get(id); if(!d) throw new Error('unknown developer'); return d; }
  #requireManifest(id:string,version:string){ const m=this.#manifests.get(`${id}@${version}`); if(!m) throw new Error('unknown extension manifest'); return m; }
  #requireInstall(id:string){ const i=this.#installs.get(id); if(!i) throw new Error('unknown installation'); return i; }
  #latestVersion(id:string){ const versions=[...this.#manifests.values()].filter(m=>m.id===id).map(m=>m.version).sort(); if(!versions.length) throw new Error('unknown extension'); return versions.at(-1)!; }
}
