import { HealthStatus, redact } from '../observability/index.js';

export enum OrganizationType { Platform='platform', ServiceProvider='service_provider', Enterprise='enterprise', Broadcaster='broadcaster', Government='government', Education='education', Sports='sports', HouseOfWorship='house_of_worship', EventCompany='event_company', MediaAgency='media_agency', Department='department', BusinessUnit='business_unit' }
export enum OrganizationStatus { Provisioning='provisioning', Active='active', Suspended='suspended', Restricted='restricted', Archived='archived', Deleted='deleted' }
export enum TenantStatus { Provisioning='provisioning', Active='active', Maintenance='maintenance', Suspended='suspended', ReadOnly='read_only', Decommissioning='decommissioning', Deleted='deleted' }
export enum IsolationLevel { Dedicated='dedicated', Logical='logical', SharedInfrastructure='shared_infrastructure', Federated='federated' }
export enum DelegationScope { Platform='platform', ServiceProvider='service_provider', Organization='organization', Tenant='tenant', Workspace='workspace', Production='production', Support='support' }
export enum SubscriptionStatus { Trial='trial', Active='active', Suspended='suspended', Cancelled='cancelled', Expired='expired' }
export enum QuotaAction { Allow='allow', Warn='warn', Throttle='throttle', ApprovalRequired='approval_required', Block='block', Override='override' }
export enum CustomerLifecycleStatus { Prospect='prospect', Provisioning='provisioning', Trial='trial', Active='active', Suspended='suspended', Archived='archived', Offboarded='offboarded' }
export enum MigrationStatus { Requested='requested', Validated='validated', InProgress='in_progress', Completed='completed', Failed='failed', RolledBack='rolled_back' }
export enum SupportSessionStatus { Requested='requested', Approved='approved', Active='active', Ended='ended', Expired='expired', Revoked='revoked' }

export interface Organization { id:string; name:string; type:OrganizationType; parentOrganizationId?:string; status:OrganizationStatus; brandingId?:string; policyIds:string[]; administratorIds:string[]; createdAt:number; }
export interface Tenant { id:string; organizationId:string; name:string; workspaceIds:string[]; policyIds:string[]; quotaId?:string; status:TenantStatus; }
export interface Workspace { id:string; tenantId:string; name:string; ownerIds:string[]; productionIds:string[]; policyIds:string[]; }
export interface BusinessUnit { id:string; organizationId:string; parentBusinessUnitId?:string; name:string; workspaceIds:string[]; policyIds:string[]; }
export interface Customer { id:string; organizationId:string; tenantIds:string[]; lifecycleStatus:CustomerLifecycleStatus; serviceProviderOrganizationId?:string; billingAccountRef?:string; }
export interface ResourceOwnership { resourceId:string; resourceType:string; organizationId:string; tenantId:string; workspaceId?:string; createdBy:string; }
export interface TenantContext { organizationId:string; tenantId:string; workspaceId?:string; productionId?:string; actingIdentityId:string; delegatedIdentityId?:string; permissions:string[]; at:number; }
export interface TenantPolicy { id:string; organizationId:string; tenantId?:string; name:string; permissions:string[]; isolationLevel:IsolationLevel; maxDelegationScope:DelegationScope; requireSupportApproval:boolean; version:number; }
export interface TenantQuota { id:string; tenantId:string; limits:Record<string,number>; warnAtPercent:number; emergencyOverrideAllowed:boolean; approvedBy?:string; expiresAt?:number; }
export interface UsageRecord { tenantId:string; resourceType:string; amount:number; recordedAt:number; billingMetadata?:Record<string,unknown>; }
export interface SharedInfrastructureAssignment { id:string; tenantId:string; region:string; clusterId:string; isolationLevel:IsolationLevel; encrypted:boolean; partitionIds:string[]; }
export interface DelegatedAdministration { delegatorId:string; delegateId:string; scope:DelegationScope; organizationId:string; tenantId?:string; workspaceId?:string; productionId?:string; permissions:string[]; effectiveFrom:number; expiresAt?:number; acceptedAt?:number; revokedAt?:number; }
export interface ServiceCatalogItem { id:string; providerOrganizationId:string; name:string; permissions:string[]; tenantTypes:string[]; active:boolean; metadata?:Record<string,unknown>; }
export interface ServiceSubscription { tenantId:string; serviceId:string; status:SubscriptionStatus; activatedAt:number; expiresAt?:number; }
export interface FederationRelationship { sourceOrganizationId:string; targetOrganizationId:string; permissions:string[]; expiresAt?:number; }
export interface TenantMigration { id:string; tenantId:string; fromRegion:string; toRegion:string; fromClusterId:string; toClusterId:string; requestedBy:string; integrityHash:string; status:MigrationStatus; startedAt?:number; completedAt?:number; }
export interface SupportSession { id:string; tenantId:string; requestedBy:string; approvedBy?:string; scope:string[]; status:SupportSessionStatus; startsAt:number; expiresAt:number; recordingRequired:boolean; }
export interface AuthorizationRequest { context:TenantContext; permission:string; resourceId?:string; targetOrganizationId?:string; targetTenantId?:string; supportSessionId?:string; }
export interface AuthorizationResult { allowed:boolean; reason:string; requiredApprovals:string[]; }
export interface QuotaEvaluation { tenantId:string; resourceType:string; limit:number; used:number; projected:number; percent:number; action:QuotaAction; reason:string; }
export interface MultiTenantSnapshot { organizations:Organization[]; tenants:Tenant[]; workspaces:Workspace[]; businessUnits:BusinessUnit[]; customers:Customer[]; ownership:ResourceOwnership[]; policies:TenantPolicy[]; quotas:TenantQuota[]; sharedInfrastructure:SharedInfrastructureAssignment[]; delegations:DelegatedAdministration[]; services:ServiceCatalogItem[]; subscriptions:ServiceSubscription[]; federations:FederationRelationship[]; migrations:TenantMigration[]; supportSessions:SupportSession[]; usage:UsageRecord[]; audit:string[]; health:{status:HealthStatus; score:number; reasons:string[]}; telemetry:{organizations:number; tenants:number; activeTenants:number; workspaces:number; orphanedResources:number; activeDelegations:number; activeSubscriptions:number; activeSupportSessions:number; federationRelationships:number; quotaWarnings:number}; }

const clone=<T>(v:T):T=>structuredClone(v); const freeze=<T>(v:T):T=>Object.freeze(clone(v)); const bounded=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const safeString=(v:string)=>String(redact(v));
const has=(list:string[], value:string)=>list.includes(value) || list.includes('*');

export class MultiTenantOperationsEngine { #orgs=new Map<string,Organization>(); #tenants=new Map<string,Tenant>(); #workspaces=new Map<string,Workspace>(); #units=new Map<string,BusinessUnit>(); #customers=new Map<string,Customer>(); #ownership=new Map<string,ResourceOwnership>(); #policies=new Map<string,TenantPolicy>(); #quotas=new Map<string,TenantQuota>(); #infra=new Map<string,SharedInfrastructureAssignment>(); #delegations=new Map<string,DelegatedAdministration>(); #services=new Map<string,ServiceCatalogItem>(); #subs=new Map<string,ServiceSubscription>(); #federations=new Map<string,FederationRelationship>(); #migrations=new Map<string,TenantMigration>(); #support=new Map<string,SupportSession>(); #usage:UsageRecord[]=[]; #audit:string[]=[]; constructor(private readonly maxHistory=20000){}
  createOrganization(org:Organization):Organization{ if(this.#orgs.has(org.id)) throw new Error('organization already exists'); if(org.parentOrganizationId&&!this.#orgs.has(org.parentOrganizationId)) throw new Error('unknown parent organization'); const safe={...org,name:safeString(org.name),administratorIds:org.administratorIds.map(safeString)}; this.#orgs.set(org.id,freeze(safe)); this.#audit.push(`OrganizationCreated:${org.id}:${org.type}`); return clone(safe); }
  updateOrganization(org:Organization):Organization{ if(!this.#orgs.has(org.id)) throw new Error('unknown organization'); const safe={...org,name:safeString(org.name),administratorIds:org.administratorIds.map(safeString)}; this.#orgs.set(org.id,freeze(safe)); this.#audit.push(`OrganizationUpdated:${org.id}:${org.status}`); return clone(safe); }
  suspendOrganization(id:string, reason:string):void{ const org=this.#requireOrg(id); this.#orgs.set(id,freeze({...org,status:OrganizationStatus.Suspended})); this.#audit.push(`OrganizationSuspended:${id}:${safeString(reason)}`); }
  archiveOrganization(id:string):void{ const org=this.#requireOrg(id); this.#orgs.set(id,freeze({...org,status:OrganizationStatus.Archived})); this.#audit.push(`OrganizationArchived:${id}`); }
  registerPolicy(policy:TenantPolicy):void{ if(!this.#orgs.has(policy.organizationId)) throw new Error('unknown policy organization'); this.#policies.set(policy.id,freeze({...policy,name:safeString(policy.name)})); this.#audit.push(`TenantPolicyRegistered:${policy.id}:v${policy.version}`); }
  provisionTenant(input:{organization:Organization; tenant:Tenant; workspace:Workspace; customer?:Customer; quota?:TenantQuota; policy?:TenantPolicy; at:number}):Tenant{ if(!this.#orgs.has(input.organization.id)) this.createOrganization(input.organization); if(input.tenant.organizationId!==input.organization.id) throw new Error('tenant organization mismatch'); if(this.#tenants.has(input.tenant.id)) throw new Error('tenant already exists'); const tenant={...input.tenant,status:TenantStatus.Provisioning,workspaceIds:[...new Set([...input.tenant.workspaceIds,input.workspace.id])]}; this.#tenants.set(tenant.id,freeze(tenant)); this.createWorkspace({...input.workspace,tenantId:tenant.id}); if(input.customer) this.#customers.set(input.customer.id,freeze(input.customer)); if(input.quota) this.#quotas.set(input.quota.id,freeze(input.quota)); if(input.policy) this.registerPolicy(input.policy); this.#audit.push(`TenantProvisioned:${tenant.id}:${input.at}`); return clone(tenant); }
  activateTenant(id:string):void{ const t=this.#requireTenant(id); this.#tenants.set(id,freeze({...t,status:TenantStatus.Active})); this.#audit.push(`TenantActivated:${id}`); }
  suspendTenant(id:string, reason:string):void{ const t=this.#requireTenant(id); this.#tenants.set(id,freeze({...t,status:TenantStatus.Suspended})); this.#audit.push(`TenantSuspended:${id}:${safeString(reason)}`); }
  offboardTenant(id:string, at:number, preserveAudit=true):void{ const t=this.#requireTenant(id); this.#tenants.set(id,freeze({...t,status:TenantStatus.Decommissioning})); for(const s of [...this.#support.values()].filter(s=>s.tenantId===id&&s.status===SupportSessionStatus.Active)) this.#support.set(s.id,freeze({...s,status:SupportSessionStatus.Revoked})); this.#audit.push(`CustomerOffboarded:${id}:${at}:preserveAudit=${preserveAudit}`); }
  createWorkspace(workspace:Workspace):Workspace{ const t=this.#requireTenant(workspace.tenantId); if(this.#workspaces.has(workspace.id)) throw new Error('workspace already exists'); const safe={...workspace,name:safeString(workspace.name),ownerIds:workspace.ownerIds.map(safeString)}; this.#workspaces.set(workspace.id,freeze(safe)); this.#tenants.set(t.id,freeze({...t,workspaceIds:[...new Set([...t.workspaceIds,workspace.id])]})); this.#audit.push(`WorkspaceCreated:${workspace.id}:${workspace.tenantId}`); return clone(safe); }
  registerBusinessUnit(unit:BusinessUnit):void{ if(!this.#orgs.has(unit.organizationId)) throw new Error('unknown business unit organization'); if(unit.parentBusinessUnitId&&!this.#units.has(unit.parentBusinessUnitId)) throw new Error('unknown parent business unit'); this.#units.set(unit.id,freeze({...unit,name:safeString(unit.name)})); this.#audit.push(`BusinessUnitRegistered:${unit.id}`); }
  assignOwnership(ownership:ResourceOwnership):ResourceOwnership{ this.#requireTenant(ownership.tenantId); if(ownership.workspaceId&&!this.#workspaces.has(ownership.workspaceId)) throw new Error('unknown workspace'); if(ownership.organizationId!==this.#requireTenant(ownership.tenantId).organizationId) throw new Error('ownership organization mismatch'); const safe={...ownership,createdBy:safeString(ownership.createdBy)}; this.#ownership.set(ownership.resourceId,freeze(safe)); this.#audit.push(`ResourceOwnershipAssigned:${ownership.resourceType}:${ownership.resourceId}:${ownership.tenantId}`); return clone(safe); }
  registerSharedInfrastructure(assignment:SharedInfrastructureAssignment):void{ this.#requireTenant(assignment.tenantId); if(assignment.isolationLevel===IsolationLevel.SharedInfrastructure&&!assignment.encrypted) throw new Error('shared infrastructure requires encryption'); this.#infra.set(assignment.id,freeze({...assignment,partitionIds:[...new Set(assignment.partitionIds)].sort()})); this.#audit.push(`SharedInfrastructureAssigned:${assignment.id}:${assignment.tenantId}`); }
  grantDelegation(d:DelegatedAdministration):void{ if(d.expiresAt!==undefined&&d.expiresAt<=d.effectiveFrom) throw new Error('delegation expiry must follow effective time'); if(d.delegateId===d.delegatorId) throw new Error('delegation cannot self-grant'); const tenant=d.tenantId?this.#requireTenant(d.tenantId):undefined; if(tenant&&tenant.organizationId!==d.organizationId) throw new Error('delegation organization mismatch'); const safe={...d,delegatorId:safeString(d.delegatorId),delegateId:safeString(d.delegateId)}; this.#delegations.set(this.#delegationKey(d),freeze(safe)); this.#audit.push(`DelegationGranted:${d.scope}:${d.organizationId}:${d.tenantId??'organization'}`); }
  revokeDelegation(delegateId:string, scope:DelegationScope, at:number):void{ for(const [key,d] of this.#delegations) if(d.delegateId===safeString(delegateId)&&d.scope===scope&&!d.revokedAt){ this.#delegations.set(key,freeze({...d,revokedAt:at})); this.#audit.push(`DelegationRevoked:${scope}:${d.organizationId}`); } }
  registerService(service:ServiceCatalogItem):void{ if(!this.#orgs.has(service.providerOrganizationId)) throw new Error('unknown service provider'); this.#services.set(service.id,freeze({...service,name:safeString(service.name),metadata:redact(service.metadata??{}) as Record<string,unknown>})); this.#audit.push(`ServiceRegistered:${service.id}`); }
  subscribe(subscription:ServiceSubscription):void{ this.#requireTenant(subscription.tenantId); const svc=this.#services.get(subscription.serviceId); if(!svc?.active) throw new Error('service unavailable'); this.#subs.set(`${subscription.tenantId}:${subscription.serviceId}`,freeze(subscription)); this.#audit.push(`ServiceSubscribed:${subscription.tenantId}:${subscription.serviceId}:${subscription.status}`); }
  unsubscribe(tenantId:string, serviceId:string):void{ const key=`${tenantId}:${serviceId}`; const s=this.#subs.get(key); if(!s) throw new Error('unknown subscription'); this.#subs.set(key,freeze({...s,status:SubscriptionStatus.Cancelled})); this.#audit.push(`ServiceUnsubscribed:${tenantId}:${serviceId}`); }
  setQuota(quota:TenantQuota):void{ this.#requireTenant(quota.tenantId); this.#quotas.set(quota.id,freeze({...quota,approvedBy:quota.approvedBy?safeString(quota.approvedBy):undefined})); this.#audit.push(`QuotaUpdated:${quota.tenantId}:${quota.id}`); }
  recordUsage(record:UsageRecord):void{ this.#requireTenant(record.tenantId); this.#usage.push(freeze({...record,billingMetadata:redact(record.billingMetadata??{}) as Record<string,unknown>})); this.#usage=this.#usage.slice(-this.maxHistory); }
  evaluateQuota(tenantId:string, resourceType:string, projected=0):QuotaEvaluation{ const quota=[...this.#quotas.values()].find(q=>q.tenantId===tenantId); const used=this.#usage.filter(u=>u.tenantId===tenantId&&u.resourceType===resourceType).reduce((s,u)=>s+u.amount,0); const limit=quota?.limits[resourceType]??Number.POSITIVE_INFINITY; const percent=Number.isFinite(limit)&&limit>0?((used+projected)/limit)*100:0; let action=QuotaAction.Allow; if(percent>=100) action=quota?.emergencyOverrideAllowed?QuotaAction.ApprovalRequired:QuotaAction.Block; else if(percent>= (quota?.warnAtPercent??80)) action=QuotaAction.Warn; const result={tenantId,resourceType,limit,used,projected,percent:bounded(percent),action,reason:`${used+projected}/${limit}`}; if(action!==QuotaAction.Allow) this.#audit.push(`QuotaExceeded:${tenantId}:${resourceType}:${action}`); return result; }
  extendQuota(id:string, limits:Record<string,number>, approvedBy:string):void{ const q=this.#quotas.get(id); if(!q) throw new Error('unknown quota'); this.#quotas.set(id,freeze({...q,limits:{...q.limits,...limits},approvedBy:safeString(approvedBy)})); this.#audit.push(`QuotaExtended:${q.tenantId}:${id}`); }
  updateBranding(organizationId:string, brandingId:string):void{ const org=this.#requireOrg(organizationId); this.#orgs.set(organizationId,freeze({...org,brandingId})); this.#audit.push(`BrandingUpdated:${organizationId}:${brandingId}`); }
  createFederation(rel:FederationRelationship):void{ if(!this.#orgs.has(rel.sourceOrganizationId)||!this.#orgs.has(rel.targetOrganizationId)) throw new Error('unknown federation organization'); this.#federations.set(`${rel.sourceOrganizationId}:${rel.targetOrganizationId}`,freeze(rel)); this.#audit.push(`FederationCreated:${rel.sourceOrganizationId}:${rel.targetOrganizationId}`); }
  removeFederation(sourceOrganizationId:string,targetOrganizationId:string):void{ this.#federations.delete(`${sourceOrganizationId}:${targetOrganizationId}`); this.#audit.push(`FederationRemoved:${sourceOrganizationId}:${targetOrganizationId}`); }
  requestSupportSession(session:SupportSession):void{ this.#requireTenant(session.tenantId); if(session.expiresAt<=session.startsAt) throw new Error('support session requires duration'); this.#support.set(session.id,freeze({...session,requestedBy:safeString(session.requestedBy),approvedBy:session.approvedBy?safeString(session.approvedBy):undefined})); this.#audit.push(`SupportSessionStarted:${session.id}:${session.status}`); }
  approveSupportSession(id:string, approvedBy:string, at:number):void{ const s=this.#support.get(id); if(!s) throw new Error('unknown support session'); if(s.expiresAt<=at) throw new Error('support session expired'); this.#support.set(id,freeze({...s,status:SupportSessionStatus.Active,approvedBy:safeString(approvedBy)})); this.#audit.push(`SupportSessionApproved:${id}`); }
  endSupportSession(id:string, at:number):void{ const s=this.#support.get(id); if(!s) throw new Error('unknown support session'); this.#support.set(id,freeze({...s,status:SupportSessionStatus.Ended})); this.#audit.push(`SupportSessionEnded:${id}:${at}`); }
  migrateTenant(migration:TenantMigration):void{ this.#requireTenant(migration.tenantId); if(!migration.integrityHash) throw new Error('migration requires integrity hash'); this.#migrations.set(migration.id,freeze({...migration,requestedBy:safeString(migration.requestedBy)})); this.#audit.push(`TenantMigrated:${migration.tenantId}:${migration.status}:${migration.toRegion}`); }
  resolveContext(identityId:string, tenantId:string, at:number, workspaceId?:string):TenantContext{ const tenant=this.#requireTenant(tenantId); if(workspaceId&&this.#workspaces.get(workspaceId)?.tenantId!==tenantId) throw new Error('workspace outside tenant'); const policies=[...this.#policies.values()].filter(p=>p.organizationId===tenant.organizationId&&(!p.tenantId||p.tenantId===tenantId)); const permissions=[...new Set(policies.flatMap(p=>p.permissions))].sort(); return {organizationId:tenant.organizationId,tenantId,workspaceId,actingIdentityId:safeString(identityId),permissions,at}; }
  authorize(req:AuthorizationRequest):AuthorizationResult{ const {context}=req; const tenant=this.#requireTenant(context.tenantId); if(tenant.status!==TenantStatus.Active&&tenant.status!==TenantStatus.ReadOnly) return {allowed:false,reason:`tenant ${tenant.status}`,requiredApprovals:[]}; const owner=req.resourceId?this.#ownership.get(req.resourceId):undefined; if(owner&&owner.tenantId!==context.tenantId) return this.#crossTenantAllowed(req, owner); if(!has(context.permissions,req.permission)&&!this.#activeDelegationAllows(context,req.permission)) return {allowed:false,reason:'permission denied',requiredApprovals:[]}; if(req.permission==='support.access'&&!this.#supportSessionActive(req.supportSessionId,context.tenantId,context.at)) return {allowed:false,reason:'support access requires active approved session',requiredApprovals:['customer_approval']}; return {allowed:true,reason:'authorized',requiredApprovals:[]}; }
  tenantAudit(tenantId:string):string[]{ return this.#audit.filter(a=>a.includes(`:${tenantId}`)||a.includes(`${tenantId}:`)); }
  tenantAnalytics(tenantId:string):UsageRecord[]{ return clone(this.#usage.filter(u=>u.tenantId===tenantId)); }
  anonymizedPlatformAnalytics():Record<string,number>{ const out:Record<string,number>={}; for(const u of this.#usage) out[u.resourceType]=(out[u.resourceType]??0)+u.amount; return out; }
  snapshot():MultiTenantSnapshot{ return clone({organizations:[...this.#orgs.values()].sort((a,b)=>a.id.localeCompare(b.id)),tenants:[...this.#tenants.values()].sort((a,b)=>a.id.localeCompare(b.id)),workspaces:[...this.#workspaces.values()].sort((a,b)=>a.id.localeCompare(b.id)),businessUnits:[...this.#units.values()].sort((a,b)=>a.id.localeCompare(b.id)),customers:[...this.#customers.values()].sort((a,b)=>a.id.localeCompare(b.id)),ownership:[...this.#ownership.values()].sort((a,b)=>a.resourceId.localeCompare(b.resourceId)),policies:[...this.#policies.values()].sort((a,b)=>a.id.localeCompare(b.id)),quotas:[...this.#quotas.values()].sort((a,b)=>a.id.localeCompare(b.id)),sharedInfrastructure:[...this.#infra.values()].sort((a,b)=>a.id.localeCompare(b.id)),delegations:[...this.#delegations.values()],services:[...this.#services.values()].sort((a,b)=>a.id.localeCompare(b.id)),subscriptions:[...this.#subs.values()],federations:[...this.#federations.values()],migrations:[...this.#migrations.values()].sort((a,b)=>a.id.localeCompare(b.id)),supportSessions:[...this.#support.values()].sort((a,b)=>a.id.localeCompare(b.id)),usage:[...this.#usage],audit:this.#audit.slice(-this.maxHistory),health:this.health(),telemetry:this.telemetry()}); }
  telemetry(){ const orphaned=[...this.#ownership.values()].filter(o=>!this.#tenants.has(o.tenantId)||(o.workspaceId&&!this.#workspaces.has(o.workspaceId))).length; const quotaWarnings=[...this.#quotas.values()].flatMap(q=>Object.keys(q.limits).map(r=>this.evaluateQuota(q.tenantId,r))).filter(e=>e.action!==QuotaAction.Allow).length; return {organizations:this.#orgs.size,tenants:this.#tenants.size,activeTenants:[...this.#tenants.values()].filter(t=>t.status===TenantStatus.Active).length,workspaces:this.#workspaces.size,orphanedResources:orphaned,activeDelegations:[...this.#delegations.values()].filter(d=>!d.revokedAt).length,activeSubscriptions:[...this.#subs.values()].filter(s=>s.status===SubscriptionStatus.Active||s.status===SubscriptionStatus.Trial).length,activeSupportSessions:[...this.#support.values()].filter(s=>s.status===SupportSessionStatus.Active).length,federationRelationships:this.#federations.size,quotaWarnings}; }
  health(){ const t=this.telemetry(); const reasons=[...(t.orphanedResources?[`${t.orphanedResources} orphaned resources`]:[]),...(t.quotaWarnings?[`${t.quotaWarnings} quota warnings`]:[])]; return {status:reasons.length?HealthStatus.Warning:HealthStatus.Healthy,score:reasons.length?bounded(100-reasons.length*15):100,reasons}; }
  #requireOrg(id:string){ const org=this.#orgs.get(id); if(!org) throw new Error('unknown organization'); return org; }
  #requireTenant(id:string){ const tenant=this.#tenants.get(id); if(!tenant) throw new Error('unknown tenant'); return tenant; }
  #delegationKey(d:DelegatedAdministration){ return `${d.delegateId}:${d.scope}:${d.organizationId}:${d.tenantId??''}:${d.workspaceId??''}:${d.productionId??''}`; }
  #activeDelegationAllows(context:TenantContext, permission:string){ return [...this.#delegations.values()].some(d=>d.delegateId===context.actingIdentityId&&!d.revokedAt&&d.effectiveFrom<=context.at&&(!d.expiresAt||d.expiresAt>context.at)&&d.organizationId===context.organizationId&&(!d.tenantId||d.tenantId===context.tenantId)&&has(d.permissions,permission)); }
  #supportSessionActive(id:string|undefined, tenantId:string, at:number){ if(!id) return false; const s=this.#support.get(id); return Boolean(s&&s.tenantId===tenantId&&s.status===SupportSessionStatus.Active&&s.startsAt<=at&&s.expiresAt>at); }
  #crossTenantAllowed(req:AuthorizationRequest, owner:ResourceOwnership):AuthorizationResult{ const federation=this.#federations.get(`${req.context.organizationId}:${owner.organizationId}`); const delegated=this.#activeDelegationAllows(req.context,req.permission); if(federation&&has(federation.permissions,req.permission)&&(!federation.expiresAt||federation.expiresAt>req.context.at)&&delegated) return {allowed:true,reason:'federated delegated access',requiredApprovals:[]}; return {allowed:false,reason:'cross-tenant access denied',requiredApprovals:['federation','delegation']}; }
}
