export type MonitoringSignalStatus = 'healthy' | 'warning' | 'critical' | 'unknown';
export type MonitoringSignalKind = 'metric' | 'log' | 'trace' | 'alert';
export type MonitoringCommandType = 'REGISTER_SIGNAL' | 'RECORD_SAMPLE' | 'ACKNOWLEDGE_ALERT' | 'CREATE_MONITORING_SNAPSHOT';
export interface MonitoringSignal { id: string; label: string; kind: MonitoringSignalKind; status: MonitoringSignalStatus; value: string; unit?: string; threshold?: string; metadataOnly: true; updatedAt: string; }
export interface MonitoringAlert { id: string; signalId: string; severity: Exclude<MonitoringSignalStatus, 'healthy' | 'unknown'>; message: string; acknowledged: boolean; metadataOnly: true; createdAt: string; updatedAt: string; }
export interface MonitoringSnapshot { id: string; signals: MonitoringSignal[]; alerts: MonitoringAlert[]; timestamp: string; metadataOnly: true; }
export interface MonitoringHealth { status: MonitoringSignalStatus; signalCount: number; activeAlerts: number; criticalAlerts: number; messages: string[]; metadataOnly: true; }
export interface MonitoringSession { id: string; name: string; signals: MonitoringSignal[]; alerts: MonitoringAlert[]; snapshots: MonitoringSnapshot[]; metadataOnly: true; }
export interface MonitoringManifest { version: '1'; session: MonitoringSession; supportedCommands: MonitoringCommandType[]; collectorsEnabled: false; externalTelemetryEnabled: false; metadataOnly: true; }
const commands: MonitoringCommandType[] = ['REGISTER_SIGNAL', 'RECORD_SAMPLE', 'ACKNOWLEDGE_ALERT', 'CREATE_MONITORING_SNAPSHOT'];
const now = () => new Date().toISOString();
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
function rejectUnsafe(payload: Record<string, unknown>) { for (const key of ['runtimeHandle', 'socket', 'ipAddress', 'credentials', 'connection', 'url', 'endpoint']) if (key in payload) throw new Error(`Unsafe monitoring field rejected: ${key}`); }
function isAlertStatus(status: MonitoringSignalStatus): status is 'warning' | 'critical' { return status === 'warning' || status === 'critical'; }
export function createMonitoringSession(name = 'Monitoring Session'): MonitoringSession { return { id: uid('monitoring'), name, signals: [], alerts: [], snapshots: [], metadataOnly: true }; }
export function createMonitoringManifest(session = createMonitoringSession()): MonitoringManifest { return { version: '1', session, supportedCommands: commands, collectorsEnabled: false, externalTelemetryEnabled: false, metadataOnly: true }; }
export class MonitoringRuntime { constructor(public session: MonitoringSession = createMonitoringSession()) {}
  registerSignal(input: Omit<MonitoringSignal, 'metadataOnly' | 'updatedAt'>) { rejectUnsafe(input as Record<string, unknown>); if (this.session.signals.some((signal) => signal.id === input.id)) throw new Error(`Duplicate signal id: ${input.id}`); const signal: MonitoringSignal = { ...input, metadataOnly: true, updatedAt: now() }; this.session.signals.push(signal); if (isAlertStatus(signal.status)) this.createAlert(signal.id, signal.status, `${signal.label} is ${signal.status}`); return signal; }
  recordSample(signalId: string, value: string, status: MonitoringSignalStatus) { const signal = this.mustSignal(signalId); signal.value = value; signal.status = status; signal.updatedAt = now(); if (isAlertStatus(status)) this.createAlert(signal.id, status, `${signal.label} reported ${value}`); return signal; }
  acknowledgeAlert(alertId: string) { const alert = this.mustAlert(alertId); alert.acknowledged = true; alert.updatedAt = now(); return alert; }
  snapshot() { const snapshot: MonitoringSnapshot = { id: uid('monitoring-snapshot'), signals: JSON.parse(JSON.stringify(this.session.signals)) as MonitoringSignal[], alerts: JSON.parse(JSON.stringify(this.session.alerts)) as MonitoringAlert[], timestamp: now(), metadataOnly: true }; this.session.snapshots.push(snapshot); return snapshot; }
  health(): MonitoringHealth { const active = this.session.alerts.filter((alert) => !alert.acknowledged); const critical = active.filter((alert) => alert.severity === 'critical'); const warnings = active.filter((alert) => alert.severity === 'warning'); const status: MonitoringSignalStatus = critical.length ? 'critical' : warnings.length ? 'warning' : this.session.signals.length ? 'healthy' : 'unknown'; return { status, signalCount: this.session.signals.length, activeAlerts: active.length, criticalAlerts: critical.length, messages: ['Metadata-only monitoring runtime', 'Collectors disabled', 'External telemetry endpoints disabled'], metadataOnly: true }; }
  enqueue(command: { type: MonitoringCommandType; payload: Record<string, unknown> }) { if (!commands.includes(command.type)) throw new Error(`Unsupported command: ${command.type}`); rejectUnsafe(command.payload); return command; }
  private createAlert(signalId: string, severity: 'warning' | 'critical', message: string) { const alert: MonitoringAlert = { id: uid('alert'), signalId, severity, message, acknowledged: false, metadataOnly: true, createdAt: now(), updatedAt: now() }; this.session.alerts.push(alert); return alert; }
  private mustSignal(id: string) { const signal = this.session.signals.find((item) => item.id === id); if (!signal) throw new Error(`Unknown signal: ${id}`); return signal; }
  private mustAlert(id: string) { const alert = this.session.alerts.find((item) => item.id === id); if (!alert) throw new Error(`Unknown alert: ${id}`); return alert; }}
