export type NavItemId =
  | 'dashboard'
  | 'production-graph'
  | 'nodes'
  | 'inputs'
  | 'scenes'
  | 'sources'
  | 'graphics'
  | 'media'
  | 'layouts'
  | 'replay'
  | 'outputs'
  | 'devices'
  | 'settings'
  | 'engine'
  | 'compositor'
  | 'runtime'
  | 'recording'
  | 'streaming'
  | 'security'
  | 'monitoring'
  | 'cluster'
  | 'plugins'
  | 'cloud'
  | 'analytics'
  | 'enterprise-admin';

/** Tabs in the adjacent source / diagnostic dock beside the left command rail. */
export type SourceDockTabId =
  | 'scenes'
  | 'sources'
  | 'media'
  | 'graphics'
  | 'guests'
  | 'diagnostics';

export type DockTabId =
  | 'audio'
  | 'layers'
  | 'graphics'
  | 'replay'
  | 'automation'
  | 'routing'
  | 'production-graph'
  | 'logs'
  | 'system-status'
  | 'media'
  | 'collaboration';

export type OperationsTabId =
  | 'guests'
  | 'inspector'
  | 'routing'
  | 'outputs'
  | 'health'
  | 'preview'
  | 'logs'
  | 'ai-director'
  | 'ai'
  | 'team'
  | 'automation'
  | 'devices'
  | 'engine'
  | 'compositor'
  | 'runtime'
  | 'recording'
  | 'streaming'
  | 'security'
  | 'monitoring'
  | 'cluster'
  | 'plugins'
  | 'cloud'
  | 'analytics'
  | 'enterprise-admin';
