'use client';
import {useEffect,useMemo,useState} from 'react';
import {filterSources,preparationQueue,sourceCollections,sourceHealthSummary,sourceLibrary,sourceTemplates,type SourceMetadata} from './source-metadata';
import './sources-workspace.css';
const NOTES_KEY='ubos.sources-workspace.notes.v5.14.0';
const icon:Record<string,string>={camera:'◉',screen:'▣',media:'▶',image:'◇',browser:'⌘',audio:'♫',guest:'◎',graphics:'✦',social:'◌',virtual:'◈'};
export function SourceSearchBar({value,onChange}:{value:string;onChange:(v:string)=>void}){return <label className="sources-search">⌕<input value={value} onChange={e=>onChange(e.target.value)} placeholder="Search sources, tags, or types" aria-label="Search sources"/></label>}
export function SourceFilters({state,onChange}:{state:string;onChange:(v:string)=>void}){return <select aria-label="Source health filter" value={state} onChange={e=>onChange(e.target.value)}><option value="all">All health</option>{['ready','warning','offline','missing','disabled'].map(x=><option key={x}>{x}</option>)}</select>}
export function SourceCard({source,selected,onSelect}:{source:SourceMetadata;selected:boolean;onSelect:()=>void}){return <button className={`source-card ${selected?'selected':''}`} onClick={onSelect}><div><i>{icon[source.type]}</i><span className={`source-state ${source.state}`}>{source.state}</span><b>{source.name}</b><small>{source.type} · {source.resolution} · {source.frameRate}</small></div><p>{source.audio?'Audio embedded':'No audio'} · {source.usageCount} scene{source.usageCount===1?'':'s'}</p><footer>{source.tags.map(t=><em key={t}>{t}</em>)}{source.favorite&&<strong title="Favorite">★</strong>}</footer></button>}
export function SourceCatalog({sources,selectedId,onSelect}:{sources:SourceMetadata[];selectedId:string;onSelect:(id:string)=>void}){return <section className="source-catalog" aria-label="Source catalog">{sources.map(s=><SourceCard key={s.id} source={s} selected={selectedId===s.id} onSelect={()=>onSelect(s.id)}/>)}{!sources.length&&<p className="source-empty">No sources match this view.</p>}</section>}
export function SourcePreviewPlaceholder({source}:{source:SourceMetadata}){return <div className="source-preview"><i>{icon[source.type]}</i><b>{source.name}</b><span>Preview placeholder · metadata only</span><small>{source.resolution} · {source.frameRate}</small></div>}
export function SourceUsageMap({source}:{source:SourceMetadata}){return <div className="usage-map"><b>{source.name}</b>{source.sceneUsage.length?source.sceneUsage.map((scene,i)=><span key={scene}>{i>0&&<i>↓</i>}{scene}</span>):<small>Not assigned to a scene</small>}</div>}
export function SourceRelationships({source}:{source:SourceMetadata}){return <section className="relationship-panel"><h3>Relationships <small>Future Production Graph integration</small></h3><SourceUsageMap source={source}/></section>}
export function SourceMetadataPanel({source}:{source:SourceMetadata}){return <div className="metadata-grid"><span>Type<b>{source.type}</b></span><span>Category<b>{source.category}</b></span><span>Resolution<b>{source.resolution}</b></span><span>Frame rate<b>{source.frameRate}</b></span><span>Audio<b>{source.audio?'Embedded':'None'}</b></span><span>Last used<b>{source.lastUsed}</b></span></div>}
export function SourceNotesPanel({source,notes,onChange}:{source:SourceMetadata;notes:string;onChange:(v:string)=>void}){return <section className="notes-panel"><h3>Notes <small>Saved locally</small></h3><textarea aria-label={`${source.name} notes`} value={notes} onChange={e=>onChange(e.target.value)} placeholder="Add preparation notes…"/></section>}
export function SourceInspector({source,notes,onNotesChange}:{source:SourceMetadata;notes:string;onNotesChange:(v:string)=>void}){return <aside className="source-inspector"><header><span className={`source-state ${source.state}`}>{source.state}</span><h2>{source.name}</h2><p>{source.type} source · {source.usageCount} scene usage</p></header><SourcePreviewPlaceholder source={source}/><h3>General</h3><SourceMetadataPanel source={source}/><h3>Usage & layouts</h3><p className="inspector-copy">Used by {source.sceneUsage.join(', ')||'no production scenes'}. Layout ownership remains metadata-only.</p><SourceRelationships source={source}/><h3>Health</h3><p className="inspector-copy">State: <b>{source.state}</b> · No runtime signal is connected.</p><SourceNotesPanel source={source} notes={notes} onChange={onNotesChange}/></aside>}
export function SourceHealthDashboard(){const health=sourceHealthSummary(sourceLibrary);return <section className="health-dashboard"><h2>Source Health <small>Static source inventory</small></h2><div>{Object.entries(health).map(([key,value])=><span key={key} className={key}><b>{value}</b>{key}</span>)}</div></section>}
export function SourceCollections({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}){return <aside className="source-collections"><h2>Collections</h2><button className={selected==='all'?'active':''} onClick={()=>onSelect('all')}>All sources <small>{sourceLibrary.length}</small></button>{sourceCollections.map(c=><button className={selected===c.id?'active':''} key={c.id} onClick={()=>onSelect(c.id)}><span>{c.name}<small>{c.description}</small></span><b>{c.sourceIds.length}</b></button>)}</aside>}
export function SourceLibrary({sources,selectedId,onSelect}:{sources:SourceMetadata[];selectedId:string;onSelect:(id:string)=>void}){return <section className="source-library"><header><h2>Source Library <small>{sources.length} shown · deterministic order</small></h2><span>Grid view · Name ↑</span></header><SourceCatalog sources={sources} selectedId={selectedId} onSelect={onSelect}/></section>}
export function SourceTemplates({onSelect}:{onSelect:(id:string)=>void}){return <div className="template-grid">{sourceTemplates.map(t=><button key={t.id} onClick={()=>onSelect(t.id)}><i>{icon[t.type]}</i><b>{t.name}</b><small>{t.description}</small></button>)}</div>}
export function SourcePreparationQueue(){return <div className="preparation-queue">{preparationQueue.map(item=>{const source=sourceLibrary.find(s=>s.id===item.sourceId)!;return <article key={item.sourceId}><span className={`source-state ${item.state.includes('blocked')?'missing':item.state==='ready'?'ready':'warning'}`}>{item.state.replaceAll('-',' ')}</span><b>{source.name}</b><p>{item.detail}</p><small>{item.owner}</small></article>})}</div>}
export function SourceWorkbench({source,notes,onNotesChange}:{source:SourceMetadata;notes:string;onNotesChange:(v:string)=>void}){const [tab,setTab]=useState('Relationships');const tabs=['Relationships','Templates','Preparation','Logs','Notes'];return <section className="source-workbench"><div role="tablist">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Relationships'?<SourceRelationships source={source}/>:tab==='Templates'?<SourceTemplates onSelect={()=>undefined}/>:tab==='Preparation'?<SourcePreparationQueue/>:tab==='Notes'?<SourceNotesPanel source={source} notes={notes} onChange={onNotesChange}/>:<p className="inspector-copy">12:24 source catalog opened · 12:21 Camera 1 inspected · no runtime events recorded.</p>}</section>}
export function SourcesWorkspace(){const [query,setQuery]=useState('');const [collection,setCollection]=useState('all');const [state,setState]=useState('all');const [selectedId,setSelectedId]=useState('camera-1');const [notes,setNotes]=useState<Record<string,string>>({});useEffect(()=>{try{setNotes(JSON.parse(localStorage.getItem(NOTES_KEY)??'{}'))}catch{setNotes({})}},[]);const filtered=useMemo(()=>filterSources(sourceLibrary,query,collection,state),[query,collection,state]);const selected=sourceLibrary.find(s=>s.id===selectedId)??filtered[0]??sourceLibrary[0]!;const saveNotes=(value:string)=>setNotes(current=>{const next={...current,[selected.id]:value};localStorage.setItem(NOTES_KEY,JSON.stringify(next));return next});return <main className="sources-workspace"><header className="sources-header"><div><p>PRODUCTION SOURCES · v5.14.0</p><h1>Sources Workspace</h1><span>Authoritative production input inventory · presentation only</span></div><div className="sources-actions"><SourceSearchBar value={query} onChange={setQuery}/><SourceFilters state={state} onChange={setState}/></div></header><SourceHealthDashboard/><div className="sources-layout"><SourceCollections selected={collection} onSelect={setCollection}/><SourceLibrary sources={filtered} selectedId={selected.id} onSelect={setSelectedId}/><SourceInspector source={selected} notes={notes[selected.id]??selected.notes??''} onNotesChange={saveNotes}/></div><SourceWorkbench source={selected} notes={notes[selected.id]??selected.notes??''} onNotesChange={saveNotes}/></main>}
