/** Operational Workspace contracts for the UBOS Live Experience OS. */
import { workspaceDefinitionLayouts } from './presets.js';
import type { WorkspaceDefinition, WorkspacePreset, WorkspacePresetId } from './types.js';

type Contract = Omit<
  WorkspaceDefinition,
  keyof typeof workspaceDefinitionLayouts.director | 'builtIn'
>;

const contracts: Record<WorkspacePresetId, Contract> = {
  director: {
    role: 'Production Director',
    responsibilities: ['Own program narrative', 'Approve next scene', 'Coordinate guests'],
    operationalPriorities: ['Program confidence', 'Preview readiness', 'Production warnings'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'scenes', 'sources', 'inspector'],
    commands: ['take', 'auto', 'cut', 'cue-next'],
    permissions: ['switch-program', 'manage-scenes', 'view-guests'],
    responsiveRules: ['Preserve Program and Preview', 'Collapse secondary docks before monitors'],
    persistenceRules: ['Persist layout metadata only', 'Never persist runtime production state'],
    acceptanceRules: ['Program and Preview visible', 'Scene workflow reachable'],
    statusIndicators: [
      'Program',
      'Preview',
      'Next scene',
      'Guest readiness',
      'Output health',
      'Production warnings',
    ],
  },
  'technical-director': {
    role: 'Technical Director',
    responsibilities: ['Protect signal routing', 'Observe graph health', 'Resolve runtime faults'],
    operationalPriorities: ['Routing health', 'Signal integrity', 'Graph synchronization'],
    defaultPanels: ['routing-matrix', 'broadcast-io', 'pipeline-inspector', 'telemetry'],
    commands: ['route-signal', 'inspect-graph', 'acknowledge-warning'],
    permissions: ['manage-routing', 'view-pipeline', 'manage-outputs'],
    responsiveRules: ['Prioritize routing controls', 'Keep diagnostics accessible'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Routing tab active', 'Program and Preview visible'],
    statusIndicators: [
      'Routing health',
      'Runtime status',
      'Graph synchronization',
      'Signal integrity',
    ],
  },
  'audio-engineer': {
    role: 'Audio Engineer',
    responsibilities: ['Mix program audio', 'Protect buses', 'Monitor talent'],
    operationalPriorities: ['Clipping', 'Muted channels', 'Bus health'],
    defaultPanels: ['audio-mixer', 'master-bus'],
    commands: ['mute-channel', 'solo-channel', 'adjust-bus'],
    permissions: ['manage-audio'],
    responsiveRules: ['Give mixer vertical space', 'Keep confidence monitors visible'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Audio mixer active', 'No audio runtime persisted'],
    statusIndicators: ['Clipping', 'Muted channels', 'Bus health', 'Monitor state'],
  },
  'graphics-operator': {
    role: 'Graphics Operator',
    responsibilities: ['Cue graphics', 'Verify assets', 'Protect overlays'],
    operationalPriorities: ['Queued graphics', 'Missing assets', 'Overlay status'],
    defaultPanels: ['graphics-library', 'inspector'],
    commands: ['cue-graphic', 'take-graphic', 'inspect-asset'],
    permissions: ['manage-graphics'],
    responsiveRules: ['Keep graphics library reachable'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Graphics library active'],
    statusIndicators: ['Queued graphics', 'Missing assets', 'Overlay status'],
  },
  'replay-operator': {
    role: 'Replay Operator',
    responsibilities: ['Mark replay moments', 'Build clips', 'Protect storage'],
    operationalPriorities: ['Replay buffer', 'Marked clips', 'Storage'],
    defaultPanels: ['replay-timeline', 'clip-library'],
    commands: ['mark-clip', 'cue-replay', 'play-replay'],
    permissions: ['manage-replay'],
    responsiveRules: ['Prioritize timeline height'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Replay timeline active'],
    statusIndicators: ['Replay buffer', 'Marked clips', 'Storage'],
  },
  'streaming-operator': {
    role: 'Streaming Operator',
    responsibilities: ['Maintain destinations', 'Protect delivery', 'Respond to auth failures'],
    operationalPriorities: ['Connected destinations', 'Dropped frames', 'Authentication'],
    defaultPanels: ['streaming', 'outputs', 'telemetry', 'system-status'],
    commands: ['start-output', 'stop-output', 'reconnect-destination'],
    permissions: ['manage-outputs', 'view-telemetry'],
    responsiveRules: ['Prioritize output health'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Output controls reachable'],
    statusIndicators: ['Connected destinations', 'Dropped frames', 'Authentication', 'Bitrate'],
  },
  'solo-streamer': {
    role: 'Solo Streamer',
    responsibilities: ['Run an independent live show', 'Engage chat', 'Monitor delivery'],
    operationalPriorities: ['Live status', 'Unified chat', 'Guests'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'chat', 'recording', 'streaming'],
    commands: ['take', 'toggle-recording', 'open-chat'],
    permissions: ['switch-program', 'manage-outputs', 'manage-chat'],
    responsiveRules: ['Favor Program', 'Collapse source dock first'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Program dominant', 'Chat reachable'],
    statusIndicators: ['Live status', 'Unified chat', 'Guests', 'Output state'],
  },
  'monitor-wall': {
    role: 'Confidence Monitor Operator',
    responsibilities: [
      'Observe production confidence',
      'Detect source failures',
      'Escalate incidents',
    ],
    operationalPriorities: ['Production health', 'Outputs', 'Source confidence'],
    defaultPanels: ['monitor-wall', 'program-monitor', 'preview-monitor'],
    commands: ['focus-monitor', 'acknowledge-warning'],
    permissions: ['view-monitoring'],
    responsiveRules: ['Collapse side docks', 'Prioritize monitor wall'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Monitor wall active'],
    statusIndicators: ['Production health', 'Recording', 'Outputs', 'Source confidence'],
  },
  compact: {
    role: 'Compact Production Operator',
    responsibilities: ['Maintain a minimal production view'],
    operationalPriorities: ['Program confidence', 'Critical warnings'],
    defaultPanels: ['program-monitor', 'preview-monitor'],
    commands: ['take', 'cut'],
    permissions: ['switch-program'],
    responsiveRules: ['Collapse all nonessential docks'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Minimal summary visible'],
    statusIndicators: ['Production summary'],
  },
  production: {
    role: 'Production Manager',
    responsibilities: ['Orchestrate scenes and switcher', 'Coordinate outputs', 'Manage scene stack'],
    operationalPriorities: ['Scene readiness', 'Transition accuracy', 'Output health'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'scenes', 'sources', 'inspector', 'recording', 'streaming'],
    commands: ['take', 'auto', 'cut', 'cue-next', 'start-output', 'stop-output'],
    permissions: ['switch-program', 'manage-scenes', 'manage-outputs'],
    responsiveRules: ['Preserve Program and Preview', 'Keep scene stack reachable'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Scene workflow reachable', 'Output controls visible'],
    statusIndicators: ['Scene readiness', 'Output health', 'Recording', 'Transition status'],
  },
  'social-fabric': {
    role: 'Community Director',
    responsibilities: ['Moderate unified chat', 'Engage audience', 'Monitor platform health'],
    operationalPriorities: ['Chat health', 'Audience engagement', 'Platform connections'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'chat', 'sources'],
    commands: ['send-message', 'moderate-chat', 'pin-comment'],
    permissions: ['manage-chat', 'view-analytics'],
    responsiveRules: ['Favor chat panel width', 'Keep Program visible'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Chat panel reachable', 'Platform status visible'],
    statusIndicators: ['Chat health', 'Audience count', 'Platform connections', 'Engagement rate'],
  },
  'media-operator': {
    role: 'Media Manager',
    responsibilities: ['Ingest and organize assets', 'Preview and tag media', 'Manage storage'],
    operationalPriorities: ['Ingest health', 'Storage capacity', 'Asset availability'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'sources', 'inspector'],
    commands: ['ingest-asset', 'preview-asset', 'tag-asset'],
    permissions: ['manage-media'],
    responsiveRules: ['Maximize asset browser width', 'Keep preview visible'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Asset browser reachable', 'Preview panel visible'],
    statusIndicators: ['Ingest health', 'Storage capacity', 'Asset count'],
  },
  'distribution-operator': {
    role: 'Distribution Manager',
    responsibilities: ['Monitor all destinations', 'Protect delivery health', 'Manage failover'],
    operationalPriorities: ['Destination health', 'Bitrate stability', 'Failover readiness'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'streaming', 'outputs', 'telemetry', 'system-status'],
    commands: ['start-output', 'stop-output', 'trigger-failover'],
    permissions: ['manage-outputs', 'view-telemetry'],
    responsiveRules: ['Prioritize destination list', 'Keep performance monitoring visible'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Destination list visible', 'Health metrics reachable'],
    statusIndicators: ['Active destinations', 'Total bitrate', 'Dropped frames', 'Latency'],
  },
  'automation-operator': {
    role: 'Automation Director',
    responsibilities: ['Run automation rules', 'Monitor cue execution', 'Manage macros'],
    operationalPriorities: ['Active automations', 'Failed cues', 'Schedule adherence'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'scenes', 'sources', 'inspector'],
    commands: ['run-automation', 'pause-automation', 'execute-macro'],
    permissions: ['manage-automation', 'manage-scenes'],
    responsiveRules: ['Keep automation builder accessible', 'Show execution log'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Automation list reachable', 'Execution status visible'],
    statusIndicators: ['Active automations', 'Pending cues', 'Execution health'],
  },
  analytics: {
    role: 'Analytics Director',
    responsibilities: ['Track audience metrics', 'Monitor performance', 'Generate reports'],
    operationalPriorities: ['Viewer count', 'Engagement rate', 'Platform performance'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'telemetry', 'system-status'],
    commands: ['export-report', 'view-analytics', 'filter-by-platform'],
    permissions: ['view-analytics'],
    responsiveRules: ['Maximize metrics display', 'Keep overview visible'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Analytics overview visible', 'Real-time metrics reachable'],
    statusIndicators: ['Concurrent viewers', 'Engagement rate', 'Watch time', 'Platform breakdown'],
  },
  streamer: {
    role: 'Content Creator',
    responsibilities: ['Run an independent live show', 'Engage chat', 'Monitor stream health'],
    operationalPriorities: ['Live status', 'Chat engagement', 'Stream quality'],
    defaultPanels: ['program-monitor', 'preview-monitor', 'chat', 'recording', 'streaming'],
    commands: ['take', 'toggle-recording', 'open-chat', 'start-output'],
    permissions: ['switch-program', 'manage-outputs', 'manage-chat'],
    responsiveRules: ['Favor Program', 'Chat always reachable'],
    persistenceRules: ['Persist layout metadata only'],
    acceptanceRules: ['Program dominant', 'Chat and stream controls reachable'],
    statusIndicators: ['Live status', 'Viewer count', 'Stream health', 'Chat activity'],
  },
};

export const workspaceDefinitions: Record<WorkspacePresetId, WorkspaceDefinition> =
  Object.fromEntries(
    Object.entries(workspaceDefinitionLayouts).map(([id, preset]) => [
      id,
      { ...preset, ...contracts[id as WorkspacePresetId], builtIn: true },
    ]),
  ) as Record<WorkspacePresetId, WorkspaceDefinition>;

export const workspaceDefinitionList = Object.values(workspaceDefinitions);
export const getWorkspaceDefinition = (id: WorkspacePresetId) => workspaceDefinitions[id];

/** Legacy layout API. Consumers receive a projection of the canonical catalog. */
export const workspacePresets: Record<WorkspacePresetId, WorkspacePreset> = Object.fromEntries(
  Object.entries(workspaceDefinitions).map(([id, definition]) => [
    id,
    {
      id: definition.id,
      name: definition.name,
      description: definition.description,
      activeBottomTab: definition.activeBottomTab,
      visiblePanels: [...definition.visiblePanels],
      collapsedPanels: [...definition.collapsedPanels],
      hiddenPanels: [...definition.hiddenPanels],
      zoneOverrides: { ...definition.zoneOverrides },
      collapsedZones: [...definition.collapsedZones],
      centerEmphasis: definition.centerEmphasis,
      zoneSizeDefaults: definition.zoneSizeDefaults
        ? { ...definition.zoneSizeDefaults }
        : undefined,
    },
  ]),
) as Record<WorkspacePresetId, WorkspacePreset>;

export const workspacePresetList: readonly WorkspacePreset[] = Object.values(workspacePresets);
export const defaultWorkspacePresetId: WorkspacePresetId = 'director';
export const getWorkspacePreset = (id: WorkspacePresetId): WorkspacePreset => workspacePresets[id];
