/**
 * Canonical panel ids and default layout metadata for existing UBOS
 * Control Room components.
 *
 * IMPORTANT: these definitions only describe layout placement. The
 * components themselves (Program monitor, Audio mixer, Replay panel, ...)
 * are untouched; they will eventually be imported and placed inside
 * DockablePanel wrappers that consume this metadata. If a component does
 * not fit the layout, an adapter wrapper is created around it — the
 * component is never edited directly.
 */
import type { WorkspacePanelDefinition } from './types.js';

export const WORKSPACE_PANEL_IDS = {
  programMonitor: 'program-monitor',
  previewMonitor: 'preview-monitor',
  scenes: 'scenes',
  sources: 'sources',
  inspector: 'inspector',
  chat: 'chat',
  recording: 'recording',
  streaming: 'streaming',
  routingMatrix: 'routing-matrix',
  broadcastIo: 'broadcast-io',
  pipelineInspector: 'pipeline-inspector',
  telemetry: 'telemetry',
  audioMixer: 'audio-mixer',
  masterBus: 'master-bus',
  graphicsLibrary: 'graphics-library',
  replayTimeline: 'replay-timeline',
  clipLibrary: 'clip-library',
  outputs: 'outputs',
  monitorWall: 'monitor-wall',
  systemStatus: 'system-status',
} as const;

export type WorkspaceKnownPanelId = (typeof WORKSPACE_PANEL_IDS)[keyof typeof WORKSPACE_PANEL_IDS];

/**
 * Factory returning fresh default definitions so multiple registries can be
 * populated independently (e.g. app shell and tests).
 */
export function createDefaultPanelDefinitions(): WorkspacePanelDefinition[] {
  return [
    {
      id: WORKSPACE_PANEL_IDS.programMonitor,
      title: 'Program',
      kind: 'monitor',
      defaultZone: 'center-stage',
      allowedZones: ['center-stage', 'external-monitor'],
      defaultVisible: true,
      defaultCollapsed: false,
      closable: false,
      collapsible: false,
      dockable: true,
      priority: 100,
      minWidth: 420,
      minHeight: 236,
      preferredWidth: 960,
      preferredHeight: 540,
      description: 'Live program output monitor (wraps existing Program monitor)',
    },
    {
      id: WORKSPACE_PANEL_IDS.previewMonitor,
      title: 'Preview',
      kind: 'monitor',
      defaultZone: 'center-stage',
      allowedZones: ['center-stage', 'external-monitor'],
      defaultVisible: true,
      defaultCollapsed: false,
      closable: false,
      collapsible: false,
      dockable: true,
      priority: 99,
      minWidth: 420,
      minHeight: 236,
      preferredWidth: 960,
      preferredHeight: 540,
      description: 'Preview/preset monitor (wraps existing Preview monitor)',
    },
    {
      id: WORKSPACE_PANEL_IDS.scenes,
      title: 'Scenes',
      kind: 'dock',
      defaultZone: 'left-dock',
      allowedZones: ['left-dock', 'right-dock', 'bottom-workspace'],
      defaultVisible: true,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 90,
      minWidth: 220,
      minHeight: 160,
      description: 'Scene list and switching (wraps existing scene workspace)',
    },
    {
      id: WORKSPACE_PANEL_IDS.sources,
      title: 'Sources',
      kind: 'dock',
      defaultZone: 'left-dock',
      allowedZones: ['left-dock', 'right-dock', 'bottom-workspace'],
      defaultVisible: true,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 89,
      minWidth: 220,
      minHeight: 160,
      description: 'Camera, capture, media, and browser sources (wraps existing source panels)',
    },
    {
      id: WORKSPACE_PANEL_IDS.inspector,
      title: 'Inspector',
      kind: 'inspector',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'left-dock', 'bottom-workspace'],
      defaultVisible: true,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 80,
      minWidth: 260,
      minHeight: 200,
      description: 'Selected item properties (wraps existing inspector)',
    },
    {
      id: WORKSPACE_PANEL_IDS.chat,
      title: 'Chat',
      kind: 'tool',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'left-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 60,
      minWidth: 240,
      minHeight: 200,
      description: 'Unified platform chat (wraps existing chat panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.recording,
      title: 'Recording',
      kind: 'status',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 58,
      minWidth: 240,
      minHeight: 140,
      description: 'Recording controls and status (wraps existing recording panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.streaming,
      title: 'Streaming',
      kind: 'status',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 57,
      minWidth: 240,
      minHeight: 140,
      description: 'Stream destinations and health (wraps existing streaming panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.routingMatrix,
      title: 'Routing Matrix',
      kind: 'workspace',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace', 'right-dock'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 70,
      minWidth: 480,
      minHeight: 180,
      description: 'Signal routing patch matrix (wraps existing RoutingPatchMatrix)',
    },
    {
      id: WORKSPACE_PANEL_IDS.broadcastIo,
      title: 'Broadcast I/O',
      kind: 'workspace',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace', 'right-dock'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 69,
      minWidth: 480,
      minHeight: 180,
      description: 'Broadcast inputs/outputs (wraps existing Broadcast I/O panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.pipelineInspector,
      title: 'Pipeline Inspector',
      kind: 'inspector',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace', 'right-dock'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 68,
      minWidth: 420,
      minHeight: 180,
      description: 'Media pipeline diagnostics (wraps existing Pipeline Inspector)',
    },
    {
      id: WORKSPACE_PANEL_IDS.telemetry,
      title: 'Telemetry',
      kind: 'status',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 55,
      minWidth: 260,
      minHeight: 160,
      description: 'System telemetry and health metrics (wraps existing monitoring panels)',
    },
    {
      id: WORKSPACE_PANEL_IDS.audioMixer,
      title: 'Audio Mixer',
      kind: 'workspace',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace'],
      defaultVisible: true,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 75,
      minWidth: 560,
      minHeight: 180,
      description: 'Channel strips and metering (wraps existing audio console)',
    },
    {
      id: WORKSPACE_PANEL_IDS.masterBus,
      title: 'Master Bus',
      kind: 'tool',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 54,
      minWidth: 240,
      minHeight: 200,
      description: 'Master bus processing and loudness (wraps existing master bus strip)',
    },
    {
      id: WORKSPACE_PANEL_IDS.graphicsLibrary,
      title: 'Graphics Library',
      kind: 'workspace',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace', 'left-dock'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 66,
      minWidth: 420,
      minHeight: 180,
      description: 'Titles, overlays, and stingers (wraps existing graphics panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.replayTimeline,
      title: 'Replay Timeline',
      kind: 'workspace',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 65,
      minWidth: 560,
      minHeight: 180,
      description: 'Replay capture timeline (wraps existing replay panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.clipLibrary,
      title: 'Clip Library',
      kind: 'dock',
      defaultZone: 'left-dock',
      allowedZones: ['left-dock', 'right-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 52,
      minWidth: 220,
      minHeight: 160,
      description: 'Captured replay clips (wraps existing clip library)',
    },
    {
      id: WORKSPACE_PANEL_IDS.outputs,
      title: 'Outputs',
      kind: 'status',
      defaultZone: 'right-dock',
      allowedZones: ['right-dock', 'bottom-workspace'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 51,
      minWidth: 260,
      minHeight: 160,
      description: 'Output destinations and encoders (wraps existing outputs panel)',
    },
    {
      id: WORKSPACE_PANEL_IDS.monitorWall,
      title: 'Monitor Wall',
      kind: 'monitor',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace', 'center-stage', 'external-monitor'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 64,
      minWidth: 640,
      minHeight: 200,
      description: 'Multiview source wall (wraps existing Monitor Wall)',
    },
    {
      id: WORKSPACE_PANEL_IDS.systemStatus,
      title: 'System Status',
      kind: 'status',
      defaultZone: 'bottom-workspace',
      allowedZones: ['bottom-workspace', 'right-dock'],
      defaultVisible: false,
      defaultCollapsed: false,
      closable: true,
      collapsible: true,
      dockable: true,
      priority: 50,
      minWidth: 420,
      minHeight: 160,
      description: 'System status workspace (wraps existing SystemStatusWorkspace)',
    },
  ];
}
