'use client';
import { BroadcastPanel, StatusBadge, cn, ubosTypographyClasses } from '@ubos/ui';
import { createProductionEngineManifest, type EngineManifest } from '@ubos/shared';
import { Phase17ExecutionPanels } from './ExecutionConsole';
const unavailable = 'Unavailable · No runtime connected · Metadata only · Not executing · No Production Graph integration';
function Panel({title, children}:{title:string; children:React.ReactNode}){return <BroadcastPanel variant="inset" padding={false} className="min-h-0 overflow-hidden"><div className="border-b border-ubos-border-subtle px-ubos-2 py-1.5"><h3 className={cn(ubosTypographyClasses.panel,'text-ubos-fg-primary')}>{title}</h3><p className="text-ubos-metadata text-ubos-fg-muted">{unavailable}</p></div><div className="ubos-scroll max-h-72 overflow-auto p-ubos-2 text-ubos-caption text-ubos-fg-secondary">{children}</div></BroadcastPanel>}
export function CommandQueuePanel({manifest}:{manifest:EngineManifest}){return <Panel title="Command Queue"><div className="grid gap-1">{manifest.commands.map(c=><div key={c.id} className="rounded-ubos-sm bg-ubos-midnight px-2 py-1"><span className="font-mono text-ubos-fg-primary">{c.type}</span> · definition only</div>)}</div></Panel>}
export function EventStreamPanel({manifest}:{manifest:EngineManifest}){return <Panel title="Event Stream"><div className="grid gap-1">{manifest.events.map(e=><div key={e.id} className="rounded-ubos-sm bg-ubos-midnight px-2 py-1">{e.type} · descriptive only</div>)}</div></Panel>}
export function DependencyGraphPanel({manifest}:{manifest:EngineManifest}){return <Panel title="Dependency Graph"><ol className="space-y-1">{manifest.dependencyGraph.nodes.map(n=><li key={n.id} className="rounded-ubos-sm bg-ubos-midnight px-2 py-1">{n.executionOrder}. {n.label} → priority {n.priority} · {n.validationStatus}</li>)}</ol></Panel>}
export function TransactionPanel({manifest}:{manifest:EngineManifest}){return <Panel title="Transaction Log">{manifest.transactions.length ? manifest.transactions.map(t=><div key={t.id}>{t.transactionId}</div>) : <p>{unavailable}</p>}</Panel>}
export function HistoryPanel({manifest}:{manifest:EngineManifest}){return <Panel title="History">{manifest.history.length ? manifest.history.map(h=><div key={h.id}>{h.kind}</div>) : <p>Undo · Redo · Rollback Point · Checkpoint metadata unavailable.</p>}</Panel>}
export function SnapshotPanel({manifest}:{manifest:EngineManifest}){const s=manifest.snapshots[0];return <Panel title="Snapshots"><div className="grid grid-cols-2 gap-1">{s ? Object.entries({Scene:s.currentScene,Graphics:s.graphicsState,Media:s.mediaState,Replay:s.replayState,Outputs:s.outputs,Audio:s.audio,Automation:s.automation,Timeline:s.timeline,Guests:s.guests,Devices:s.devices}).map(([k,v])=><div key={k} className="rounded-ubos-sm bg-ubos-midnight px-2 py-1">{k}: {v}</div>) : unavailable}</div></Panel>}
export function TimelinePanel({manifest}:{manifest:EngineManifest}){const t=manifest.timeline;return <Panel title="Timeline"><div className="space-y-1"><p>Current Time: {t.currentTime}</p><p>Current Segment: {t.currentSegment}</p><p>Upcoming Segment: {t.upcomingSegment}</p><p>Cue Markers: Unavailable</p><p>Transition Markers: Unavailable</p><p>Breakpoints: Unavailable</p></div></Panel>}
export function LockManagerPanel({manifest}:{manifest:EngineManifest}){return <Panel title="Resource Locks"><div className="grid gap-1">{manifest.resourceLocks.map(l=><div key={l.id} className="rounded-ubos-sm bg-ubos-midnight px-2 py-1">{l.label}: {l.state} · owner {l.owner}</div>)}</div></Panel>}
export function EngineInspector({manifest}:{manifest:EngineManifest}){return <Panel title="Inspector"><p>Schema {manifest.schemaVersion}</p><p>Runtime connected: {String(manifest.state.runtimeConnected)}</p><p>Production Graph integrated: {String(manifest.state.productionGraphIntegrated)}</p></Panel>}
export function EngineMetadataOverlay(){return <div className="rounded-ubos-sm border border-ubos-border-subtle bg-ubos-midnight p-ubos-2 text-ubos-metadata text-ubos-fg-muted">Metadata only · Not executing · No runtime connected</div>}
export function ExecutionQueuePanel({manifest}:{manifest:EngineManifest}){return <Panel title="Execution Queue"><p>State: {manifest.executionQueue.state}</p><p>{manifest.executionQueue.blockedReason}</p></Panel>}
export function EngineWorkspace({manifest=createProductionEngineManifest(), compact=false}:{manifest?:EngineManifest; compact?:boolean}){return <div className="flex h-full min-h-0 flex-col gap-ubos-2 overflow-hidden p-ubos-2"><div className="flex items-center justify-between"><div><h2 className={cn(ubosTypographyClasses.section,'text-ubos-fg-primary')}>Engine Workspace</h2><p className="text-ubos-metadata text-ubos-fg-muted">Command Bus · Event Bus · Dependency Graph · Metadata foundation</p></div><StatusBadge variant="neutral">Unavailable</StatusBadge></div><EngineMetadataOverlay/><div className={cn('grid min-h-0 gap-ubos-2 overflow-auto', compact?'grid-cols-1':'grid-cols-1 xl:grid-cols-3')}><Phase17ExecutionPanels/><CommandQueuePanel manifest={manifest}/><EventStreamPanel manifest={manifest}/><DependencyGraphPanel manifest={manifest}/><TransactionPanel manifest={manifest}/><LockManagerPanel manifest={manifest}/><ExecutionQueuePanel manifest={manifest}/>{!compact ? <><HistoryPanel manifest={manifest}/><SnapshotPanel manifest={manifest}/><TimelinePanel manifest={manifest}/><EngineInspector manifest={manifest}/></> : null}</div></div>}
